### ISSUE TITLE
SPIKE: Further analysis around calculating next upcoming event.

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#10176]
TIME BOX: 1 Day

## Description
When no events are marked as featured, the fallback is to grab the *next upcoming event*. #9576 captures a defect around this functionality. [The PR to address it](https://github.com/department-of-veterans-affairs/content-build/pull/1241) is an improvement but not a complete fix.

Iterating further needs to address two issues:
1. "Weekend staleness" - We need to consider the implications of calculating dates during the static build, and the timing concerns of doing so. For example, we don't build over the weekend, so the content that is live on a Sunday will have been generated on Friday. This could throw off dates.
2. "99% of cases" - The issues in the first point notwithstanding, we'd have a solution that solves all cases if we'd just remove the [limit of passing 10 events to the FE](https://github.com/department-of-veterans-affairs/content-build/blob/9615020dcf81b216e6856252ecc33a91fa28dadc/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L103). We need to assess how removing this limit would affect the payload passed to the FE.

### Goals
- Establish edge cases for possible prioritization, and tradeoffs of solution options.

## Acceptance Criteria
- [ ] Write up edge cases
- [ ] Identify any possible trade-offs
- [ ] Write new ticket(s) to solve the two issues described above, and be able to provide estimate(s)/context for the ticket(s).

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Just checked [the VA Minneapolis homepage](https://www.va.gov/minneapolis-health-care/) at 6:33 PM Mountain time on 8/11/2022

The featured event on the homepage already happened earlier this morning:

![Screen Shot 2022-08-11 at 6 34 04 PM](https://user-images.githubusercontent.com/9059428/184264313-0f73f572-e4e9-42ac-b128-9ae90fd893b1.png)

The homepage should be displaying the actual next event, the blood drive happening tomorrow, 8/12:

![Screen Shot 2022-08-11 at 6 34 45 PM](https://user-images.githubusercontent.com/9059428/184264405-65b31374-9e00-481a-b821-344c6cb028b3.png)

The logic behind calculating the next upcoming event should be based on universal timestamps (so that it is not affected by time zones)

**Comment by dsinla** [comment]
@ryguyk In discussions with the team we see this as primarily a PW responsibility? can you confirm, happy to discuss more.

**Comment by ryguyk** [comment]
@dsinla Yes, this falls on PW. I am tracking this. Thank you.

**Comment by ryguyk** [comment]
A possible error around filtering. Seems the Aug. 16 - Aug. 16 filter should show the Aug. 16 event:

https://www.va.gov/minneapolis-health-care/events/?selectedOption=custom-date-range&startDateDay=15&startDateMonth=08&startDateYear=2022&endDateDay=17&endDateMonth=08&endDateYear=2022
![image](https://user-images.githubusercontent.com/6863534/184988451-b934b13b-d49c-4600-9cdd-a766bfee1463.png)

https://www.va.gov/minneapolis-health-care/events/?selectedOption=custom-date-range&startDateDay=15&startDateMonth=08&startDateYear=2022&endDateDay=16&endDateMonth=08&endDateYear=2022
![image](https://user-images.githubusercontent.com/6863534/184988556-9becfdac-a19a-4c21-b498-10dc48ad584c.png)

https://www.va.gov/minneapolis-health-care/events/?selectedOption=custom-date-range&startDateDay=16&startDateMonth=08&startDateYear=2022&endDateDay=16&endDateMonth=08&endDateYear=2022
![image](https://user-images.githubusercontent.com/6863534/184988594-e7c8a824-7c8b-46a4-89a6-52e92e48ceba.png)

**Comment by ryguyk** [comment]
8/16/2022 4:49PM Central Time
![image](https://user-images.githubusercontent.com/6863534/184991405-2e71b9e3-b30d-47cc-a818-dfc87b3318f4.png)
![image](https://user-images.githubusercontent.com/6863534/184991463-af5a6651-8c4e-4933-882d-b966bb6f5160.png)
![image](https://user-images.githubusercontent.com/6863534/184991526-ade52a77-0ce2-4b64-bcdc-d47bea712af6.png)

**Comment by ryguyk** [comment]
Preliminary thought is that we need to **move as much time calculation as possible to the browser**. For example, the "Featured Event" is currently statically generated. This will always be delayed. It should likely be converted to a React widget that can calculate event timing relative to the exact moment a veteran loads the page.

**Comment by jilladams** [comment]
Assigned to @jtmst with @allisonlu as a pairing ride along to get up to speed on how events chrono logic works.

**Comment by jtmst** [comment]
Our initial proposed solution of removing the limit on number of events returned seems like most reasonable answer.  Before finalizing that recommendation I'd like to audit the prod CMS to look for facilities with an exceptional number of events, or other outliers.

**Comment by jtmst** [comment]
Recommendations to move forward are as follows:

1.  In order to address the event staleness issue, we need to include logic that filters out past events to the browser.  Currently graphQL handles that filtering, however this only occurs on daily build.  Logic needs to be added to src/site/layouts/health_care_region_page.drupal.liquid and the associated liquid.js helper file to ensure that no past events are in the data that the featured event component pulls from.

2. Increase the limit for future events pulled to allow for more coverage of future events by health care region.  Most regions have 10 or fewer future events, but the top 10 health care regions have more.  As of today, the top 3 health care regions have more than 100 future events, with the top region (puget sound health care) having 722.  

Increasing the limit to 1000 gives the leeway necessary to account for these outliers.   I do not recommend removing the limit entirely as a region with a large number of recurring events could result in a payload that hinders performance

**Comment by jilladams** [comment]
@jtmst can you cut a ticket for that next step and link it here?
