### ISSUE TITLE
DSN: Conduct VBA Veteran interviews

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10194]
Acceptance Criteria
- [x] Required number of sessions have been conducted
- [x] Notes from sessions are stored in research folder
- [x] Participant demographics have been recorded in a recruitment tracker
- [ ] Moderator has downloaded session recordings to local machine for synthesis

**Comment by davidmpickett** [comment]
Per [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-plan.md#timeline) these will begin at the tail end of Sprint 67 and carry into Sprint 68

**Comment by davidmpickett** [comment]
This is definitely not starting this sprint due to recruitment timelines

**Comment by davidmpickett** [comment]
Participant demographic information should be captured in a [recruitment tracker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md#lean-mvs-strategy). Preferred format is a sheet in the [shared excel doc](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Accessibility/RecruitmentChecker.xlsx?d=we0ffb06d5bac4cd5902c5f8b23fe988c&csf=1&web=1&e=FzYt5t) (requires CAG access), but there is also a [Google Sheets version](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit#gid=1116550612).

**Comment by davidmpickett** [comment]
@jcklpe @RWEagans  I filled out the ACs a little bit since they were blank

**Comment by jcklpe** [comment]
A vet mentioned they got some good info from this subreddit. Might be worth reading more here: https://www.reddit.com/r/VeteransBenefits/

**Comment by jcklpe** [comment]
Some thoughts I wanted to get out here while it's fresh.

As we have talked with vets some recurring themes appear to me. I don't want to be impose my bias on static so take this with a grain of salt:

*   Vets want to talk to a human. 
    *   People are responsive and dynamic. Sometimes a vet doesn't know exactly what they need help with or where to look on the website. 
    *   they trust talking to a person more. If they hand someone a form in person they know that person received it.
        *   Vets commonly express confusion about the status of the forms they fill out and the status they are in. 
        *   Vets commonly express unhappiness and feel like they're being treated like just a number that no one cares about. 
*   Vets generally express a preference for fulfilling their tasks online
    *   It's convenient. 

But how do we get those form systems up to snuff? And how do you make stuff available online while also filling that instinct towards talking to a person directly?

  
The only vet I asked about their opinion of engaging with a person online via chat was negative. They didn't like that idea. Just one person but I see a conflict between these two themes in terms of solutions.   
  
At least some of the instinct towards talking to a human is due to already broken trust in the automated systems. The automated systems have been garbage so they figure it's just faster to walk in to a physical location and talk to a human. I also can empathize with their frustration over being treated like a number. At the same time I see how an automated form system scales a lot better than a labor intensive human one. How to thread the needle between these two seems tricky (and also out of scope for the work we are actually supposed to be doing on the benefit office websites)
