### ISSUE TITLE
Put site in maintenance mode during deploy

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1022]
As a site user it would be nice to know when the site is actually being updated.
The site should be put into maintenance mode before update and config import is run.  It should be taken out of maintenance mode after the final cache clear has completed.

~~@ElijahLynn notes that when in maintenance mode, the status page does not return a 200 which causes some devops issue.  We should look into a solution for this.~~  - This has been resolved and is no longer an issue.

Dependencies https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1208

### Advanced warning

- [x] Add status warning message

- If jenkins can calculate the time (preferred): Roughly 15 min ahead of time,  the following drush command should be called on the cms

```
drush site_alert:delete "deploy-alert"
 drush site_alert:create "deploy-alert" "Around [CALCULATE THE TIME] ET today we will be running a system update. <br>The CMS will be temporarily unavailable for up to 15 minutes. You should plan to save ahead of time, or take a break during the update to avoid losing work." --severity=medium
```

### When the deploy starts 

- [x] Add status message to stop work.

```
drush site_alert:delete "deploy-alert"
drush site_alert:create "deploy-alert" "<strong>System update in progress</strong><br><br>Sit tight! Stay on this page to avoid losing unsaved changes. <br>Updates generally take up to 15 minutes.  We'll let you know when it's ok to resume working again." --severity=high
```  
 
Preferably wait 20sec before doing the next line  (that's the polling interval on the ajax.)
- [x]  Put the site in maintenance mode 

```
drush state-set system.maintenance_mode 1
```

- [x] after update db and config import and cache clear has completed, Take the site out of maintenance mode 

```
drush state-set system.maintenance_mode 0
```

- [x] Give the all clear message 

```
drush site_alert:delete "deploy-alert"
drush site_alert:create "deploy-alert" "The system update is complete, and it is safe to resume using the CMS. Carry on!  " --severity=low --duration="20"
```

**Comment by ElijahLynn** [comment]
The non-200 response issue is resolved by @swirtSJW's merge of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1026.

**Comment by swirtSJW** [comment]
I updated the exact messages in description of this ticket

**Comment by ElijahLynn** [comment]
As discussed on Zoom just now (@swirtSJW, @indytechcook, @oksana-c, @jonpugh & myself) w/4 main parts to this. Of note is that we cannot do this on DEV/STAGING easily because we wipe the DB on deploys, which loses any state we set. 

GitHub Deployments API consideration. 

1. Alert start, only PROD - use `release_wait` time to pass to `drush site:alert` command - Figure out a pre-release job for http://jenkins.vfs.va.gov/job/deploys/job/cms-auto-deploy/
1. Maint on - Run just before PROD deploy job - http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-prod/
1. Maint off & Alert complete - ansible/deployment/config/cms/tasks/post-init-tasks-prod.yml
1. DB backup while in maint mode will cause probs. DB backup job should turn maint mode off ansible/cms/roles/cms-db-sanitize/tasks/main.yml OR have backup job check if site is in maint. mode and wait or skip. OR whatever won't cause problems.

**Comment by swirtSJW** [comment]
Updated the text with latest content from Mural.

**Comment by rachel-kauff** [comment]
@indytechcook & @swirtSJW When this is done, do you mind sending me a few screenshots of the finished thing so I can include them in the release note? Thanks!

**Comment by ElijahLynn** [comment]
FYI: #1363 is blocking full testing of this.

**Comment by indytechcook** [comment]
Current WIP code: https://github.com/department-of-veterans-affairs/devops/compare/VACMS-1022-jenkins-alert-start?expand=1

**Comment by ElijahLynn** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/6793
