### ISSUE TITLE
Discovery: Document PDF Download use cases to test changes against

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10284]
## Description

Before we start tinkering with the seemingly unnecessary API calls in #10235 and #10236, we need to understand all the use cases that Find-a-form supports so that we can ensure we don't break them.

A starter list of possible differentiators between use cases:
- PDF origin (`www.va.gov` vs VBA subdomain, etc)
- Page where download occurs (Search page vs. Form Detail page)
- Whether "How to download a form" modal shows up or not
  - This doesn't show up every time, we think maybe a cookie ensures it only shows up once every 24 hours (or similar)

_Any other differentiators??_ Clues to consider:
- The PDF Download flow [Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1660150431569/27c80eaeeaedfd88c80322ae177b68c503345ba9?sender=u907f83e01e35bb04de6f8139)
- Codebase around this topic, specifically the `onDownloadLinkClick()` handler

## Acceptance Criteria
- [x] Locate existing documentation or document full list of use cases that need to be tested for the Find-a-form app
  - Located existing use cases here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
🕵️‍♀️  [Find VA Forms - Product Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md) updated 11/19/2021, which was launch timeframe for adding the download modal. This turned up via [va.gov-team/31832](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832)

- [Find a Form Search Landing Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md)
  - Use cases [S-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-f) and [S-G](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-g) are pertinent to the Forms modal design
- [Find a Form Detail Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-f)
  - Use cases [D-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-f) and [D-G](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-g) are pertinent to the Forms modal design

This design intent cycle was re: "Epic - Find a VA Form PDF Download Instructions" [#26816](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26816).

Specifically re: the modal: 
> Note - this modal is the product of [user research recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/research-findings.md#recommendations). After users failed to notice inline info-text and notes related to Adobe Reader, Marci met with Ryan Thurwell and Angela Fowler, and they agreed that this was a good use case for a modal to draw needed attention. In that meeting, a high-level design was agreed upon, and a https://github.com/department-of-veterans-affairs/va.gov-team/issues/29704. Marci took this design to Collab office hours on 9/29 for feedback.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-951315456
> User downloads PDF, opens in a browser and prints.
User downloads PDF, opens in a browser, fills out online and prints.
User downloads PDF, opens in a acrobat reader and prints.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-954287574
> Let's try to wrap this up! From what I'm hearing, it's most important to solve for the problem of the user trying to fill out the form in their browser or open the PDF on their mobile device. It's secondary to mention how to print it out, though good to mention for users who want to fill in their info by hand and mail in their form.

I checked with our stakeholder in disability comp and he said users can upload a claim through direct upload, which we link to from a handful of locations on our site. So explaining how to complete a fillable PDF on screen is important for users who want to type into the boxes rather than handwrite the info--and then either upload the form through direct upload or print it out.


## Ticket pile, chrono
* [Find a VA Form: Add new PDF alert to each PDF link on Search page #29706](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29706)
* [Find a VA Form: Add new PDF Alert to each PDF link on form detail pages #30377](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30377)
* [Find a VA Form: Mock up accessible PDF alert #29704](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29704)
* [Find a VA Form: Update modal mock-up with design intent updated copy #31708](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31708)
* [Collaboration Cycle Kickoff Decision Tools: Find a VA Form PDF Download Instructions #31713](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31713)
* [[COLLAB CYCLE CHECKLIST] Find a VA Form Modal #31849](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31849)
* [Design intent Decision Tools - Find a VA Form PDF Download Instructions #31832](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832)
* [IA Feedback - Design Intent - Find a VA Form PDF Download #32043](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32043)
* [Design Feedback - Design intent Decision Tools - Find a VA Form PDF Download Instructions #32019](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32019)
* [Find a VA Form: Detail Page PDF Modal: Update text, add 24 hour cookie #31873](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31873)
And:
* [Modal design system docs](https://design.va.gov/components/modal)

**Comment by jilladams** [comment]
Next steps: summarize relevant use cases for FE tickets blocked by this issue.

**Comment by wesrowe** [comment]
Based on a meeting this morning, it sounds like form-hosting origin might be an additional wrinkle that is not covered by the linked use cases. I.e., Daniel said that only forms hosted in www.va.gov get pre-fetched (and thus have the pre-fetch point of failure). 

Also of note – the use cases are all in TestRail. Not a tool we've used before now.

**Comment by wesrowe** [comment]
Closing since the documented use cases that Jill found meet the requirement. Adding link to use cases doc to the epic and relevant stories.
