### ISSUE TITLE
[RESEARCH] Check out lift to get accessibility tests passing with WCAG 2.1

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10368]
## Description
We should support WCAG 2.1.  Before making the switch, though, we should see how big the lift is so that the issue to fix tests (if necessary) can be sized appropriately.

## Acceptance Criteria
- [ ] Axe uses WCAG 2.1 standards **or**
- [ ] Followup issue(s) created to fix tests so that we can shift to WCAG 2.1.

**Comment by productmike** [comment]
@laflannery Talking with @ndouglas, I'd like to revive this ticket. I guess this is serving as both an FYI and an opty to speak your mind on the value to your a11y efforts here...any gothcha's from your side we should take into account?

**Comment by laflannery** [comment]
@productmike this would be great to move forward with. VA standards are 2.1 so I would love our CMS tests to also be running at that same standard. 

The one gotcha I see is that I am expecting new issues to be flagged because we are testing for additional criteria. We tried to expand test coverage once before (in a different way) and we didn't make room for or prioritize new issues which meant we couldn't merge that PR or fully complete the updated coverage task until all those issues were resolved - some still aren't. 

All this to say that if we move forward with the 2.1 upgrade, I want to make sure we reserve engineering time and possibly some UX Design time in each sprint to prioritize and remediated 2.1 issues.
