### ISSUE TITLE
Investigate tablefield patch

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10379]
## Description

The issue is that the current state of the tablefield module does not support specifing header row or column and the associated scope property.

This drupal.org issue seems to address the problem https://www.drupal.org/project/tablefield/issues/3128030

It creates an additional setting to record the heading orientation.

## Acceptance Criteria
- [x] Test patch in PR environment: does it fix the reported issue, does it break other tables?
- [x] Validate patch does not break existing nodes with tables in paragraphs
- [ ] Validate that setting the appropriate heading option will result in the proper scope value being set on the FE content build
- [ ] If the patch works.  RTBC it on the drupal.org issue.
- [ ] If it does not work, spec out what would need to happen to make it work.
- [ ] Summarize findings for Sitewide CMS review before merge (Erika, Cindy Terdiman)
- [ ] PM/DM: May require Change Mgmt, review scale of the change after findings
- [ ] Define next steps for required FE work, ensure that it's clear in #10372 

**Related issues**
- Main FE tracking ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10372
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10130
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10295
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2932

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Slack discussion

**Comment by swirtSJW** [comment]
One sample node   I will find more 
https://prod.cms.va.gov/node/986

**Comment by jilladams** [comment]
@chri5tia could you add points estimate before you start work?

**Comment by jilladams** [comment]
Christian Burk created an audit view for Table info: https://prod.cms.va.gov/admin/content/audit/table-audit
For more info: https://dsva.slack.com/archives/CT4GZBM8F/p1661354422964899
> I believe it is View that pulls in all paragraphs of type 'table'  Which is the thing that uses the table_field module https://prod.cms.va.gov/admin/structure/paragraphs_type/table/fields
> So that audit should show all instances of tables that would be affected by the patch.

**Comment by chri5tia** [comment]
https://api.druphelp.com/api/tablefield/tablefield.module/function/theme_tablefield_view/7.3 saving this for later in case it's helpful for FE

**Comment by chri5tia** [comment]
Didn't apply cleanly:

```
🐾 va.gov-cms: git apply patches/10379-tableview-scope.patch                                                 18:26
error: src/Element/Tablefield.php: No such file or directory
error: src/Plugin/Field/FieldFormatter/TablefieldFormatter.php: No such file or directory
error: src/Plugin/Field/FieldType/TablefieldItem.php: No such file or directory
error: src/Plugin/Field/FieldWidget/TablefieldWidget.php: No such file or directory
error: tablefield.install: No such file or directory
```

**Comment by chri5tia** [comment]
Benefits detail hub add content block > table (Paragraph type).

admin/structure/paragraphs_type/table/fields/paragraph.table.field_table
Not seeing settings regarding this here either.

Settings are the same for paragraph tables in the PR branch as well as an unrelated sandbox.

**Comment by chri5tia** [comment]
Testing on new PR review instance. See https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10426 PR for notes.

**Comment by chri5tia** [comment]
## Ticket scope
Will [this tableview patch](https://www.drupal.org/files/issues/2020-09-21/tablefield-header-orientation-3128030-13.patch) allow headers to be defined for screen readers?

## Context
Paragraph table input form now shows a checkbox to select whether or not the first row or first column is the table header:
![Screen Shot 2022-08-24 at 8 35 38 PM](https://user-images.githubusercontent.com/22764938/186568818-915d6a72-aeb7-448e-96e7-f10cb090f06e.png)

The relationship with the tablefield and the table paragraph type:

With `tablefield` module installed, field_table paragraph type was created using the "Table Field" field type (previously).

![Screen Shot 2022-08-24 at 8 14 33 PM](https://user-images.githubusercontent.com/22764938/186566256-50bc5d5d-585b-4c56-a898-88fdfc92d475.png)

![Screen Shot 2022-08-24 at 8 15 28 PM](https://user-images.githubusercontent.com/22764938/186566356-8824e82b-dd32-46a4-a644-3aec10770f4d.png)

Go to Go to content > add content > Benefit Detail Page > Add content block > Table > See if you are able to define if the first row or column is the header to see it in action.

## Testing done

### Manual functional testing

https://cms-skjshobxv5cgqe08fjzvlyugqwyl1qpy.ci.cms.va.gov/node/42031/edit

![Screen Shot 2022-08-24 at 11 08 14 PM](https://user-images.githubusercontent.com/22764938/186588050-9ed2dd7a-f11c-4398-a742-1c7dc8d78089.png)


```
The website encountered an unexpected error. Please try again later.

Drupal\Core\Entity\EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_table_row_header' cannot be null: INSERT INTO "paragraph_revision__field_table" ("entity_id", "revision_id", "bundle", "delta", "langcode", "field_table_value", "field_table_format", "field_table_caption", "field_table_row_header", "field_table_column_header") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9); Array ( [:db_insert_placeholder_0] => 96446 [:db_insert_placeholder_1] => 721105 [:db_insert_placeholder_2] => table [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => a:4:{i:0;a:3:{i:0;s:14:"Priority group";i:1;s:53:"Copay amount for first 3 visits in each calendar year";i:2;s:55:"Copay amount for each additional visit in the same year";}i:1;a:3:{i:0;s:23:"<strong>1 to 5</strong>";i:1;s:13:"$0 (no copay)";i:2;s:3:"$30";}i:2;a:3:{i:0;s:18:"<strong>6</strong>";i:1;s:203:"<strong>If related to a condition that's covered by a special authority*:</strong> $0 (no copay) <br /><br /><strong>If not related to a condition covered by a special authority*:</strong> $30 each visit";i:2;s:3:"$30";}i:3;a:3:{i:0;s:23:"<strong>7 to 8</strong>";i:1;s:3:"$30";i:2;s:3:"$30";}} [:db_insert_placeholder_6] => rich_text [:db_insert_placeholder_7] => 2021 urgent care copay rates [:db_insert_placeholder_8] => [:db_insert_placeholder_9] => ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

### Table audit
Looked at the table audit (/admin/content/audit/table-audit), in the PR review instance, to see if table items are good (downloaded as a csv).
Noting concerns. It appears that any table's first row has been set as a heading by default or the heading has been stripped. 

Downloading a CSV of before and after the patch, I can see that there is missing data:
![Screen Shot 2022-08-24 at 9 19 12 PM](https://user-images.githubusercontent.com/22764938/186574048-d4147107-0b34-4788-91bd-e610fa4ea7be.png)

Or perhaps moved data due to schema changes:
![Screen Shot 2022-08-24 at 9 20 41 PM](https://user-images.githubusercontent.com/22764938/186574170-5f749981-e1e3-4318-b079-0adde5f07d01.png)

See table audit diffs here.
[tableauditdiffs.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9421303/tableauditdiffs.xlsx)

### Automated testing on [PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10426) 
  - [ ] GraphQL failure
  - [ ] Status Report failure

Status report failure:
This code creates a mismatched entity and/or field definitions:
`The paragraph.field_table field needs to be updated`

It's not safe to run general entity updates the old way. Need to find out what specifically is needed and write a hook, most likely. To troubleshoot this entity mismatch:
    -  Resaved the different components ([Paragraph table field settings](https://cms-skjshobxv5cgqe08fjzvlyugqwyl1qpy.ci.cms.va.gov/admin/structure/paragraphs_type/table/fields/paragraph.table.field_table) and [tablefield settings](https://cms-skjshobxv5cgqe08fjzvlyugqwyl1qpy.ci.cms.va.gov/admin/config/content/tablefield)) .
    -  I checked to see if any configs needed to be exported as well as a result of this work. There was not and I did not make any config changes.
    - Rebuilt caches and ran database updates

## QA steps

[TBD]
We will need to go to the table audit and spot check or download the csv to ensure that enabling this doesn't break any of the content: 
https://cms-skjshobxv5cgqe08fjzvlyugqwyl1qpy.ci.cms.va.gov/admin/content/audit/table-audit

We will also need to check this on the front-end, after exploring the GQL error.

## Conclusion
Problematic or needs more work.

**Comment by jilladams** [comment]
From chatting with Christia about next steps, boiled down for my brain: 
This module changes the way the Paragraph table entity works in the database, and returns Entity definition mismatch. Fix might be as simple as writing a hook to resolve that mismatch.

It also failed a graphQL test, so we need to identify fix.

**Comment by chri5tia** [comment]
```
29   30/Aug 20:21   php             Error      Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Table Audit[table_audit]: SQLSTATE[42S22]: Column not found:  
                                                 1054 Unknown column '10' in 'where clause': SELECT COUNT(*) AS "exp                                                       
  28   30/Aug 20:21   php             Error      Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Table Audit[table_audit]: SQLSTATE[42S22]: Column not found:  
                                                 1054 Unknown column '10' in 'where clause': SELECT COUNT(*) AS "exp                                           
```

```
va.gov-cms: ddev drush updbst                                                                             13:49
 ----------------------- ----------- --------------- --------------------------------------------------------------------------------------- 
  Module                  Update ID   Type            Description                                                                            
 ----------------------- ----------- --------------- --------------------------------------------------------------------------------------- 
  tablefield              8002        hook_update_n   8002 - Add columns for setting row and column header per field value to the database.  
  paragraph entity type               entity-update   The paragraph.field_table field needs to be updated.                                   
 ----------------------- ----------- --------------- --------------------------------------------------------------------------------------- 
🐾 va.gov-cms: ddev drush updb -y                                                                            13:50
 ------------ ----------- --------------- --------------------------------------------------------------------------------------- 
  Module       Update ID   Type            Description                                                                            
 ------------ ----------- --------------- --------------------------------------------------------------------------------------- 
  tablefield   8002        hook_update_n   8002 - Add columns for setting row and column header per field value to the database.  
 ------------ ----------- --------------- --------------------------------------------------------------------------------------- 


 // Do you wish to run the specified pending updates?: yes.                                                             

>  [notice] Update started: tablefield_update_8002
>  [notice] Update completed: tablefield_update_8002
 [success] Finished performing updates.
🐾 va.gov-cms: ddev drush status-report                                                                      13:54
^CFailed to run drush status-report: exit status 130
🐾 va.gov-cms: ddev drush status-report |grep Error                                                          13:54
| Entity/field definitions                    | Error    | Mismatched entity and/or field definitions                                 |

```

Looking at this with Daniel. We need to write/rewrite a hook that updates the schema correctly with the definition update manager.

**Comment by chri5tia** [comment]
Re-saving an existing node after checking the box to make the first row the header gives:

```
The website encountered an unexpected error. Please try again later.

Drupal\Core\Entity\EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_table_row_header' cannot be null: INSERT INTO "paragraph_revision__field_table" ("entity_id", "revision_id", "bundle", "delta", "langcode", "field_table_value", "field_table_format", "field_table_caption", "field_table_row_header", "field_table_column_header") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9); Array ( [:db_insert_placeholder_0] => 113637 [:db_insert_placeholder_1] => 724637 [:db_insert_placeholder_2] => table [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => a:6:{i:0;a:4:{i:0;s:18:"Departure location";i:1;s:4:"Time";i:2;s:16:"Arrival location";i:3;s:4:"Time";}i:1;a:4:{i:0;s:7:"Bedford";i:1;s:9:"7:30 a.m.";i:2;s:10:"Gloucester";i:3;s:9:"8:45 a.m.";}i:2;a:4:{i:0;s:10:"Gloucester";i:1;s:6:"9 a.m.";i:2;s:7:"Bedford";i:3;s:7:"10 a.m.";}i:3;a:4:{i:0;s:7:"Bedford";i:1;s:7:"12 p.m.";i:2;s:10:"Gloucester";i:3;s:6:"1 p.m.";}i:4;a:4:{i:0;s:10:"Gloucester";i:1;s:9:"1:15 p.m.";i:2;s:7:"Bedford";i:3;s:6:"3 p.m.";}i:5;a:4:{i:0;s:9:"Test town";i:1;s:4:"noon";i:2;s:15:"Other Test town";i:3;s:8:"midnight";}} [:db_insert_placeholder_6] => rich_text [:db_insert_placeholder_7] => Bedford / Gloucester VA Clinic* [:db_insert_placeholder_8] => [:db_insert_placeholder_9] => ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

**Comment by chri5tia** [comment]
Gist to work toward a patch to replace the existing patch:

https://gist.github.com/chri5tia/f26ba664b413fe16c39f0436e901f2e3

**Comment by wesrowe** [comment]
Re UX and change management... I think the additional checkboxes look a little confusing, as they appear in the screenshots above. Their purpose is not immediately apparent. If these will appear for all Editors, I'd like to get a UXer to look at this.

**Comment by wesrowe** [comment]
FYSA, meeting scheduled Thurs 9/7 to determine next steps since the patch implementation was not as straightforward as hoped.

**Comment by chri5tia** [comment]
Summary
The patch needs work. 
- We need UX design to weigh in on placement and help text for the header checkboxes on the input form.
- We need to extend/rework the patch to actually update the database values with what is inputted.
- We need to create custom code to address table_field entity definition mismatch, if still applicable after fixing the patch.
- We will need an FE engineer to look at how the template will need to be updated to apply the scope property correctly once given the updated data.

@wesrowe is cutting tickets for these

**Comment by chri5tia** [comment]
As a side note, these are the following things I tested for this patch:
- removed all other tablefield patches to ensure they didn't cause any part of the issue
- upgraded to latest dev release
- used print_r to see what was contained in the array and why nothing is being sent to the row_header table, not sure because the array was null
