### ISSUE TITLE
Confirm alt text inline content guidance 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10495]
## Background

Before launching inline content guidance for alt text for VAMC editors, we must confirm the appropriate guidance with the 508 office. The [guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/inline-guidance/alt-text-quality-audit/Alt%20text%20audit%20for%20inline%20content%20guidance%20discovery.pdf) we will look to confirm is:

- Succinct: 150 characters or less
- Accurate & Equivalent: The "why" of the image and avoids irrelevant details
- Avoids redundant phrases: Does not contain "image of", "photo of" or "Logo of"
- Not using the file name  (was not a criterion but was included in initial research results, but would be a good thing to include in our guidance)

## Acceptance Criteria

- [x] schedule meeting (Martha Wilkes, Laura Flannery, Val Runde)
- [x] confirm guidance meets standard

**Comment by EWashb** [comment]
@valerierunde I've reached out to Martha Wilkes for the initial touchpoint. I'll keep you posted on scheduling,etc

**Comment by EWashb** [comment]
meeting scheduled with martha wilkes for 8/31 at 10 CST

**Comment by laflannery** [comment]
I found a link to [alt text guidance](https://www.oit.va.gov/design-guide/accessibility/images.cfm) in the VAMC Facility Image KB article.  It points to OIT so I wanted to make sure we were aware this exists and that we have at least one link directing editors here.

**Comment by laflannery** [comment]
@valerierunde Can you review my proposed inline alt text guidance?  I'm not sure if it's too much, too little, etc.  I also have a screenshot of what this would look like so that might help you judge the length. 

> Providing meaningful alternative text is important for accessibility. Add a concise description of the image, focusing on the main purpose of the image and how the image relates to the other content on the page. Avoid words such as “image”, “photo” or “graphic” and do not include the file name of the image.

![image](https://user-images.githubusercontent.com/106678594/188716199-db5003ec-eda3-4130-9c7e-41d4e562efce.png)

**Comment by valerierunde** [comment]
Thanks, @laflannery! What do you think about this? Bullet points make things more easily scannable so important points don't get lost or skipped over in the paragraph of text.

Alternative text is important for accessibility. Tips for writing alternative text:
 - Include a short, specific description of the image
 - Avoid words such as “image,” "picture," “photo,” or “graphic”
- Do not use the file name of the image
- Include any text that's part of the image

**Comment by valerierunde** [comment]
Learned that bullets are not available.

Alternative text is important for accessibility. Tips for writing alternative text: include a short, specific description of the image. Avoid words such as “image,” "picture," “photo,” or “graphic”. Do not use the file name of the image. Include any text that's part of the image.

**Comment by laflannery** [comment]
Thanks @valerierunde!

**Comment by laflannery** [comment]
@valerierunde I was thinking about this again, and I want to remove the last point - "Include any text that's part of the image".  I feel this could cause confusion for editors because I wish I could explain it more.  I do not want to encourage them to upload images with text especially a lot of text such as infographics. I feel this particular point may require more explanation that we currently do not have a way to easily provide.  

Let me know if you are ok with this change and/or if you want to discuss further

**Comment by valerierunde** [comment]
@laflannery I'm ok with that. Thanks for checking.
