### ISSUE TITLE
Update error state for character limits on input fields in the CMS

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10865]
## Description
Within the CMS on the edit screens, some fields that have a character limit enabled have a red indicator when the editor goes over the limit. This red color is used both on the border of the field and in the character count below the field. 

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/182946157-fc4fc87c-9074-4bf3-8637-b4367a8089f0.png)

## Acceptance Criteria
- [ ] Update the input border color to be `#e31c3d` (red-bright)
- [ ] Update the red text under the input field to be `#B20D01` (red-dark)
- [x] Confirm with Accessibility Lead

**Comment by laflannery** [comment]
@BlakeOrgan This is something that was done by our previous designer, I would like you to take another look at it and see if the ACs are what you would recommend (as I know you would tend towards less colors is better). Let me know if you want to discuss in person, if you need clarification on the ask here, thanks!

**Comment by BlakeOrgan** [comment]
This was originally an implementation ticket, but since @laflannery asked me to take a look at it and provide updated recommendations, I am putting my updated recommendations below and we can disregard the original AC. I am creating a new implementation ticket based on my recommendations below.

To follow the existing patterns of character counters and to ensure that the text will always meet the 7:1 AAA contrast requirements, the number for the character counter in an error state should always remain `#212121`. This update is also reflected in my recommendations about the warning state of the character counter text color in ticket #10135.

I would recommend changing the border UI element to `#B20D01` and @laflannery has confirmed these edits.

Figma design can be referenced here:
https://www.figma.com/file/gCSCL6VSGZGmYCMT0bq1Uu/Character-Counters?node-id=4%3A977&t=srvqt5e29PlK5GAd-1

The new implementation ticket can be referenced here: #12378
