### ISSUE TITLE
Testing SSO on php 8.1

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#10874]
needs to wait until 8.1 is on STAGING. doing the testing and fixing anything found that's broken.

- [ ] make sure SSO continues to work without errors on STAGING

**Comment by cmaeng** [comment]
this will need to be taken off of STAGING once testing is complete

**Comment by ElijahLynn** [comment]
I created PR https://github.com/department-of-veterans-affairs/devops/pull/12251/ for this and deployed it to STAGING. 

I tried to login with PIV and got a DNS error on SOCKS and then remembered that I need to test SSO/PIV login ON the network, so tried to login with CAG and got an error:

> You are not authorized to access Citrix Access Gateway (CAG)

So I need to call helpdesk tomorrow to get my PIV reactivated.

**Comment by ElijahLynn** [comment]
SSO is working on 8.1. Eric tested this on STAGING today and it works. 

![image](https://user-images.githubusercontent.com/1504756/202582288-6d351ef6-a78d-4b35-b7e1-bf62a861a7c7.png)


Disregard the Error in this screenshot, it is only that way because of an issue where we remove all the email addresses on STAGING (to prevent accidentally emailing lots of folks) on lower ENVs that use a developer DB snapshot.
