### ISSUE TITLE
test.staging.cms.va.gov deployment instability

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11031]
## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
I have test.staging stable for right now, BUT that is not permanent and it appears to be related to the instance size that it is deployed with. I made a PR to try to change the lock order here https://github.com/department-of-veterans-affairs/devops/pull/12048 but still noticed one deploy firing the jobs in the wrong lock order. And then I deployed test.staging with the same instance size that non-test uses, which is a c5.9xlarge (36vCPU) instead of a c5.xlarge (4 vCPU), both are the same clock speed. And the jobs firing in the wrong order (tests then deploy live steps) still enabled the instance to be deployed successfully. So it appears there is a timeout somewhere that needs to be adjusted for the slower deployment on the slower test CPU instance (less cores). The deployment and test runs were notably slower, and I need to get those values still.

**Comment by ElijahLynn** [comment]
Discussed with @olivereri last week and we discussed just upsizing the test.staging and test.prod instances to match the non-test instances for now. We will be off BRD in the coming future and it isn't worth the effort to fix this race condition right now.
