### ISSUE TITLE
Form audit tool: New/Deleted forms

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11116]
## Description

Add a tab to display all "New" form flags, and Deleted forms, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flags with columns
  - Title
  - Edit button
  - Content type (necessary?)
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
Putting this into the PR for #11115.

**Comment by swirtSJW** [comment]
@wesrowe  and @chri5tia When this was discussed before issues were created, I noted that "new" and "deleted" should be the same View so that we can quickly surface the common scenerio of someone deleting one, and creating a new one instead updating the existing one.

I encourage https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11117 and this one to be combined into one View.

**Comment by wesrowe** [comment]
@swirtSJW, thanks for catching that, I obviously missed that point in the process.
