### ISSUE TITLE
Implement help-text and character limits for all Homepage drupal fields

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11119]
***See ACs for time-box approach around risk/ambiguity***

## Description

As an Editor working on the new Homepage, I want to see helpful text with fields of custom blocks so that it's clear what I need to do to conform with governance.

## Acceptance Criteria

**Agreement in sprint planning: execute all the actionable ACs below, and work with PM/DM to break uncertain stuff out into separate tickets**

### Benefit promo custom block
<details>
<summary> Drupal screenshots for reference </summary>

![image](https://user-images.githubusercontent.com/55411834/194431004-a66df8f7-3f5e-4b7e-95f6-7f82fc9d2233.png)

![image](https://user-images.githubusercontent.com/55411834/194432827-26da5903-7432-4541-8bac-fa14fbfaef90.png)

</details>

- [ ] Promo headline - 35 character limit and help text "Use this headline to make it clear to Veterans what the topic of this promo is and that it's relevant to them" (recommended by Danielle)
- [ ] Promo text - 125 characters and help text "Use this text to tell Veterans how this promo topic affects them" (recommended by Danielle)
~~- [ ] Block description - As an editor, I need to understand that this will be seen only within Drupal and not on the front end.~~
- [ ] Link text - 40 characters and help text "Use this text to tell Veterans what to do next. Note: For accessibility and cognitive clarity, link text must include the intended purpose of and keywords from the H1 page title of the destination page." (recommended by Danielle)
~~- [ ] Administration > Structure > Entityqueues > Edit entity queues - As an editor I need to understand what is shown below the "Save, Reverse, etc" buttons, how it is different than the items shown above the buttons and how to get my newly created promo to appear in the queue. (as a separate issue, it allows me to click "add item" but no items appear)~~

### News promo custom block
- [ ] Promo headline - 55 character limit and help text "Use this headline to make it clear to Veterans what the topic of this promo is and that it's relevant to them" (recommended by Danielle)
- [ ] Promo text - 125 characters and help text "Use this text to tell Veterans how this promo topic affects them" (recommended by Danielle)
- [ ] Link text - 40 characters and help text "Use this text to tell Veterans what to do next. Note: For accessibility and cognitive clarity, link text must include the intended purpose of and keywords from the H1 page title of the destination page." (recommended by Danielle)

### Popular on VA.gov menu
<details>
<summary> Drupal screenshots for reference </summary>

![image](https://user-images.githubusercontent.com/55411834/194429966-b48557db-de1b-495f-8e56-c125f61e018c.png)
![image](https://user-images.githubusercontent.com/55411834/194430528-7b791094-13b6-4a52-ab19-1adb4a648189.png)
</details>

~~- [ ] Title - As an editor, I need to understand how many characters are allowed and that what I enter into this field will appear as the menu heading.~~
~~- [ ] Add menu link > Menu link title - As an editor, I need to understand how many characters are allowed ~~
~~- [ ] Add menu link > Description - As an editor, I need examples of what should be entered so that the hover text is appropriate and 508 compliant.~~ 
~~- [ ] Administration > Structure > Menus > list of links - As an editor, I need to know that I can drag and drop links to order them.~~
~~- [ ] Administration > Structure > Menus > list of links - As an editor, I need to know what checking/unchecking the "enabled box" means to the front end display.~~

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@mmiddaugh, do you want to take a pass at this?

**Comment by mmiddaugh** [comment]
Possibly separate issue but should I be able to "add item" if there aren't any to choose from? 
![image](https://user-images.githubusercontent.com/55411834/194432013-eb8fd5c6-c320-4e5d-bc8d-7ce9e6835576.png)

**Comment by mmiddaugh** [comment]
@laflannery appreciate any guidance you can lend to help text for editors here, particularly related to the news promo image

**Comment by laflannery** [comment]
@mmiddaugh Is there somewhere I can go in the CMS to see all the new fields, to see what an editor will see when managing the new homepage?

**Comment by laflannery** [comment]
The Benefits Promo and News Promo fields are very similar so the suggested guidance is the same for any fields that are the same.  I combined Danielle's recommendations in the description with some of the standard help text patterns in the rest of the CMS.

### Block description
- Used in both Benefits and News
- Suggested guidance: _This is used for identifying the block with the CMS. The description will not be shown on VA.gov._

### Promo Headline
- Used in both Benefits and News
- **Update**: Can you change to “Promo headline”, lower case h, to follow the standard pattern for field labels?
- Suggested guidance: _The headline indicates the topic of the promo that is most relevant to Veterans. The headline should use sentence case capitalization. [See capitalization guidelines](https://design.va.gov/content-style-guide/capitalization) from the VA content style guide._

### Promo Text
- Used in both Benefits and News
- **Update**: Can you change to “Promo text”, lower case t, to follow the standard text pattern?
- Suggested guidance: **This text should serve as a summary of the promo and tell Veterans how this promo topic affects them.** 

### Call to action
- Used in Benefits
- **Update**: Is it possible to wrap all the elements together with a border so it's more clear that both Link and Link text are within the "Call to action" field? Like with the Link field on Promo blocks:
![image](https://user-images.githubusercontent.com/106678594/195385058-a25b7e01-03e4-4ee2-862e-3e464d61e467.png)
#### Link text
- Suggested guidance: This text should tell Veterans what to do next and include the intended purpose of the destination page. For more link tips, visit the [links page](https://design.va.gov/content-style-guide/links) of the VA content style guide.

### Image
- Used in News
- Suggested guidance: Add a visually engaging image for the promo. For best results, add an image cropped to a 1:1 aspect ratio. The system will crop your image if it isn't already.

### Link and Link Text
Is it possible to also wrap all these two fields elements together with a border and a CTA field - like the request for the Benefits Promos?

### Link
This should be consistent with other link fields help text, the additional text should be removed as it is not relevant here: “Start typing to find content or paste a URL and click on the suggestion below.”

### Link Text
- Suggested guidance: Choose an option from the dropdown to tell Veterans what to do next.

**Comment by wesrowe** [comment]
@mmiddaugh, It's hard for me to discern whether everything needed for development has been provided, between Details and Comments. We can probably estimate this tomorrow in refinement, but I'll look to you to say it's fully ready. Ideally, all the text and char limits would be in the ticket Details at that point.

**Comment by jilladams** [comment]
Per homepage sync today, moved to post-MVP epic, since Michelle will enter the production content for launch.

**Comment by jilladams** [comment]
From sprint planning: 
* Keep this ticket to 3 points -- implement everything that has an existing paradigm to manage char limits
* Any items that do _not_ have an existing paradigm / require special work, break out into separate tickets
* One known item in that bucket: link text doesn't currently have a way to add char limits. SPIKE ticketed for follow up: #11509

**Comment by dsasser** [comment]
@wesrowe @jilladams @mmiddaugh 
These ACs are not doable without custom code/additional work:

## Benefit Promo:
- [ ] Block description - As an editor, I need to understand that this will be seen only within Drupal and not on the front end.

The block description isn't editable as seen on the block/add or block/edit pages. 


- [ ] Link text - 40 characters and help text "Use this text to tell Veterans what to do next. Note: For accessibility and cognitive clarity, link text must include the intended purpose of and keywords from the H1 page title of the destination page."

We *can* do the 40 character limit, but since we are leveraging an existing CTA paragraph, we are limited in how we can alter the form text, as it would be exposed anywhere the CTA paragraph is used. The 40 character limit is already setup in the CTA paragraph link text field.

## News Promo:
- [ ] Link text - 40 characters and help text "Use this text to tell Veterans what to do next. Note: For accessibility and cognitive clarity, link text must include the intended purpose of and keywords from the H1 page title of the destination page." (recommended by Danielle)

A link text description doesn't make sense to me in this context. This is a dropdown select field with only one selection available currently: "Read the full article". The 40 character limit is already in place.

## Menus:
- [ ] Title - As an editor, I need to understand how many characters are allowed and that what I enter into this field will appear as the menu heading. 
- [ ] Add menu link > Menu link title - As an editor, I need to understand how many characters are allowed 
- [ ] Add menu link > Description - As an editor, I need examples of what should be entered so that the hover text is appropriate and 508 compliant. 
- [ ] Administration > Structure > Menus > list of links - As an editor, I need to know that I can drag and drop links to order them. 
- [ ] Administration > Structure > Menus > list of links - As an editor, I need to know what checking/unchecking the "enabled box" means to the front end display. 

To my knowledge, none of the requested changes are possible without custom code. The menu fields are not editable in the UI like a field on a node would be, they are intentionally hidden from the manage fields UX by Drupal core.

**Comment by dsasser** [comment]
I have a draft PR for the current ACs. This will need review by @mmiddaugh and or @laflannery.

**Comment by wesrowe** [comment]
I crossed out help-text ACs that didn't have text – those will be moved to #11586.

**Comment by mmiddaugh** [comment]
I've moved the relevant guidance from @laflannery into #11586

**Comment by mmiddaugh** [comment]
<details>
<summary> Screenshots from PR tugboat </summary> 

![block screnshot](https://user-images.githubusercontent.com/55411834/202559938-b01e30a9-5821-4eb8-9ed9-4a1fda3b02e5.PNG)
![image](https://user-images.githubusercontent.com/55411834/202559599-093ddae0-cdb4-4f6e-992e-0146f7936afa.png)
![image](https://user-images.githubusercontent.com/55411834/202559609-7d4872a3-93ce-4063-87ce-f2bc2ec4f114.png)

</details>

**Comment by jilladams** [comment]
@mmiddaugh does that mean we're ok to merge what's implemented in the Tugboat, and any changes will come under #11586?
