### ISSUE TITLE
Unpublished Alert blocks are not visibly unpublished when selected on Benefits Detail Pages

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11230]
## Description
Benefits Detail Pages have a `field_alert`, which allows an editor to place an Alert block at the top of the page.
> Alerts draw attention to information that may be critical to a veteran, family member, or caregiver. You can [create a new alert](https://staging.cms.va.gov/block/add/alert?destination=/admin/content/alerts), or reuse an existing one.

It is possible to create a situation where the selected Alert block is not published. This can be done by selecting an existing one that is unpublished or by creating a new one via the link in the instructions and leaving that in the default "draft" state.

While creating the Alert, it might seem quite obvious that the selected Alert is not published. However, after initial creation, that situation is much less obvious. It's not immediately clear via the node-edit screen that the selected Alert is not published, and this [has created some confusion](https://dsva.slack.com/archives/CDHBKAL9W/p1666030268937839?thread_ts=1665667127.482519&cid=CDHBKAL9W).

![image](https://user-images.githubusercontent.com/6863534/196257642-c7b0f03e-385b-4fd3-8fa4-04da7ae43adc.png)

It also appears on the node Preview, despite it being unpublished:
![image](https://user-images.githubusercontent.com/6863534/196257959-7045a668-d50b-4b69-a180-45eb23f8539d.png)

It should be considered whether we might be able to indicate more clearly that a selected Alert is unpublished.

## Preferred fix
Style the Draft alert in the CMS UI using red highlighting like we do on draft nodes.

## Examples and links
Example BD node on prod: https://prod.cms.va.gov/node/16359/edit – "include alert" area/block displays a custom block that has been added to the page. If it were set to draft, it should appear pink.

## Acceptance Criteria
- [x] In node-edit screen for a Benefit Detail page, when an Alert block is selected:
  - [x] if the Alert is unpublished (never published or has unpublished changes), it appears with a light red background
  - [x] if the Alert is published, it appears with a white background
- [x] requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
I can see the argument for PW owning this as part of Banners / Benefit detail pages, and for Sitewide CMS owning it as part of editor experience and it might apply in more places within the CMS.  @swirtSJW do you have any sense of whether this might apply to more content types that can select Alerts, rather than just the Benefit Detail pages? (After our spec tool dive I'll be able to answer things like that myself! Til then though: appreciate your input.)

**Comment by wesrowe** [comment]
@ryguyk, how did you learn about this issue? Did it come in as an issue from an Editor?

**Comment by wesrowe** [comment]
Discussed in BE refinement – determined good/sensible path forward is to make the background pink in the node page to signal that changes here are not published. This is low effort and should be clear. We decided not to make any changes to the preview – it's much harder to do and lower value, since the Editor would at this point have seen the pink version.

**Comment by wesrowe** [comment]
@jilladams @dsasser @chri5tia, can one of you please confirm that the ACs reflect your understanding of our discussion in BE refinement.

**Comment by jilladams** [comment]
I think the styling related change makes sense and uses language I get, but would appreciate a Drupal second to that, just to make sure. 

RE: 508 review, red = draft is a common paradigm in the CMS today, so not sure the intent with that review. If we think the paradigm may have 508 problems, that'll probably be out of scope to fix here and need its own ticket.

**Comment by jilladams** [comment]
Steve probably knows off the top of his head how the red color / unpublished functionality works.

**Comment by chri5tia** [comment]
note to self: play with the example here not on prod: https://va-gov-cms.ddev.site/node/16359/edit

**Comment by chri5tia** [comment]
Hmm, not quite.

<img width="787" alt="Screenshot 2023-09-10 at 11 49 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/56aa204a-b938-4285-b381-f7608bebeb98">

**Comment by swirtSJW** [comment]
> I can see the argument for PW owning this as part of Banners / Benefit detail pages, and for Sitewide CMS owning it as part of editor experience and it might apply in more places within the CMS. @swirtSJW do you have any sense of whether this might apply to more content types that can select Alerts, rather than just the Benefit Detail pages? (After our spec tool dive I'll be able to answer things like that myself! Til then though: appreciate your input.)

I only missed responding to this by nearly a year  :(
This does impact other content types.

They can [be seen here](https://prod.cms.va.gov/admin/reports/content-model/fields?field_name=field_alert&field_type=entity_reference&entity_type=node&bundle=&label=)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/5e996cde-c5cc-47b4-a09c-29471ca7f64f)

**Comment by chri5tia** [comment]
We attempted to install the `preprocess` module so that we can use the entity subscriber for the entity browser on the form,  however, we were met with translation errors out of the box. 

We did move this from the .theme file where I had it to a .module and created a new block types helper module.

In order to put this as an entity subscriber, we'll need to cut a new ticket and explore this further.
To that end, I also need to keep the scope as benefit detail page only for now and scoping that out further can be explored as needed and by the appropriate team.

**Comment by chri5tia** [comment]
Let's also cut a ticket to explore new functionality within the view to highlight draft state rows and filter by published or not. Daniel showed my a concept model and I like it.

**Comment by chri5tia** [comment]
Summary:

Tickets for possible future work:
- [ ] Make this functionality global, not restricted to Benefit Detail Pages
- [ ] Move this method to an event subscriber, which needs the preprocess module, which currently conflicts with translation
- [ ] Improve the functionality of the view.

**Comment by jilladams** [comment]
@chri5tia with technical issues like this, it's often helpful to have engineers take a first pass at drafting the tickets needed, vs. @wesrowe doing a game of telephone. Are you willing to cut those suggested tickets? Can send Wes links when you're done so he can take it from there.

**Comment by chri5tia** [comment]
Debugging convo: https://dsva.slack.com/archives/C52CL1PKQ/p1694545279345899

It may be that we can't in this ticket style the field in real time because ajax doesn't work with the hooks we need to use. This needs to be researched more. However, all the other styling is implemented. It may be that this is ready to push as is, already a huge improvement.

**Comment by chri5tia** [comment]
Update:
PR is ready to review. The ajax/real-time update of block color is going to take more planning and not accounted for in the refinement process. Vastly improved experience over all.

**Comment by chri5tia** [comment]
@Jill Adams @wesrowe I am looking at how to use an ajax callback hook to improve the software further so that the background color of the block is updated in real time instead of just after save. If  the PR doesn't get approved and merged by the time I can add it, I'll just add it, otherwise it'll have to be a separate ticket that I already started working on.

**Comment by chri5tia** [comment]
This PR still needs a review. In case there is any question, the piece where the background color becomes highlighted in light red before form save needs more planning and needs a separate ticket. The nature of that work is going to require a lot more research. Javascript doesn't play nice with the entity browser and the ajax hooks require the form to reload. it might warrant more discussion. I will copy this to the ticket.
