### ISSUE TITLE
Propose VBA terms for Service Taxonomy (new and existing)

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11266]
## Description
Initial rough draft with Dave P. 

There are 3 sources of information that these terms can come from:
1. current services in the VA taxonomy that apply to VBA (Ex. VR&E vocational ...)
2. current VBA service dropdown in facility locator (~16 things, existing data around how Veterans interact with that group of things, powered by Sandys DB)
3.  The public contact research (includes list of every service, task, and document that was referenced in those conversations about what Veterans do when they are at RO, info about frequency included as well)

**Fields to consider**
- [x] Term name
- [x] "Type of Care" = categories of service
- [ ] ~~Plain language name~~
- [x] Common conditions / alternate names
- [x] National description
- [x] What to bring to your appointment
- [x] Online self-service
- [x] Service Region info
- [x] Local facility info

## Acceptance Criteria
- [x] I expect each of the above sources of information are reviewed and a list of proposed VBA terms are created 
- [x] I do not expect every field that goes with the above terms are determined, however some representative fields for these terms should be populated in the proposal to explain why we need that term 
- [x] I expect that the content drafted here supports the VBA design 5 and the Veteran facing usability research plan that is being written, and that this is confirmed with @thejordanwood and @cindymerrill 
- [x] I expect that there is an internal review with @kmariepat-cityfriends and @mmiddaugh at the end of sprint 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kmariepat-cityfriends** [comment]
for additional cards:
- [ ] Confirm with Taxonomy council that the proposed new terms should exist and are distinct from existing terms; determine if there are considerations for Vet Centers and VAMCs
- [ ] determine fields for each of the proposed terms from this card

**Comment by davidmpickett** [comment]
FYI - here's where I had been starting to work on this during my research synthesis
https://airtable.com/appftQ67nT0eopl4i/tblQXbm3wB9VxIkoQ/viwxaWZCYouGIwuzE?blocks=hide
[VBA Services-Grid view.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11409258/VBA.Services-Grid.view.csv)

**Comment by kmariepat-cityfriends** [comment]
Potential stakeholder process for this includes review with Sitewide Content/IA; @kmariepat-cityfriends to create intake ticket

**Comment by kmariepat-cityfriends** [comment]
This card will span multiple sprints and is blocker to design and UX research

**Comment by kmariepat-cityfriends** [comment]
@mmiddaugh can support to push parts of this forward

**Comment by mmiddaugh** [comment]
@davidmpickett  I'm looking at the Airtable notes for "Applying for benefits" (an existing VBA "service" on the FLocator), I think this is actually a task which is relevant to most services, rather than its own service. 
This is also supported by Cindy's top task research, as above. (i.e., applying for VA health or applying for education benefits)

**Comment by davidmpickett** [comment]
Transcribing my notes from Monday meeting with @davidconlon @mmiddaugh 

- "What to bring to your appointment"
  - Rephrase to "Helpful documents" or something that doesn't discourage people who don't have all documents from seeking service
  -  what information is specified nationally, regionally, locally - additive process
- Sitewide Content review should focus more on VBA Service Taxonomy, less on basic Facility info on prototype

**Comment by davidmpickett** [comment]
@mmiddaugh One area I would appreciate your brain on. The venn diagram of education / training / careers is very confusing, and if you have any historical perspective on how Veterans understand (or don't) the distinctions that would be amazing

- [Careers and employment](https://www.va.gov/careers-employment/)
- [Education and training](https://www.va.gov/education/)
- [Education benefits](https://www.va.gov/education/eligibility/)
- [Educational and career counseling](https://www.va.gov/careers-employment/education-and-career-counseling/)
- [VR&E](https://www.va.gov/careers-employment/vocational-rehabilitation/)

**Comment by davidmpickett** [comment]
@mmiddaugh new export from the Airtable. 

- [VBA Services-Everything.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11510680/VBA.Services-Everything.csv)
  - Main working list of terms 
  - Added some Type of Care ideas 
- [Full Benefit List-Grid view.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11510681/Full.Benefit.List-Grid.view.csv)
  - This is an artifact from work I did on Public Websites, but I'm using it here to crosswalk my understanding and having clear links to pages for further research

**Comment by mmiddaugh** [comment]
Our Vet Center taxonomy research included some insights about education and training, which you may have already seen. Caveat: this was related to non-therapeutic services, leading to the "Workshops and classes" taxon currently in use - which is different than the formal benefits and programs we're currently pondering.  You may have already found this in your wandering but just in case: 
- [Findings related to Veteran understanding of education and training from Vet Center research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/services-taxonomy/taxonomy-study/research-findings.md#1-education-and-training)
- [Question responses synthesis](https://airtable.com/shrAC18S413d1NXjM) - this might be interesting to look at the specific Veteran responses and words/concepts they associated with "education and training" 

I'll check with a few contacts and see what else I can learn.

**Comment by mmiddaugh** [comment]
@davidmpickett Thank you for all the thoughtful and mind-bending effort you've already put into this Taxonomy - I like where things are headed. 

Things I'm wondering...(possibly for a future brainstorm/chat next week?)
- Might there be rationale for separating the family member benefits (i.e. the proposed Compensation benefits for family members, Education benefits for family members, and Caregiver support) into a distinct "type of care"?
- Amending "Pension benefit" slightly to "Veterans Pension benefit" or "Veterans Pension Program" as on the benefit pages. This would also distinguish it from Employee pension (I recall some level of confusion reported during Top task research). 
- I believe VR&E is a familiar and recognizable acronym which can follow the full (and updated) name. 
- I agree with pulling Life insurance out into a separate benefit but still wrapping my head around "Financial services" 
- Any rationale for pulling the various account/contact updates together (i.e. updating direct deposit info, updates to dependents, and contact info)?
- Rather than eBenefits, can Regional offices assist with My HealtheVet registration? ("My HealtheVet coordinator" is an existing taxon.) 
- I'm wondering if "VA web account support" might convey assistance beyond the scope of the Regional office. 
- "Billing and insurance" may take on different meaning  when taken out of the VAMC page context. 
- I didn't notice a home for VA benefit letters - perhaps there is a taxon for these and other VA documents which cross multiple benefit services and programs vs those which are benefit-specific (i.e., COE for home loans and education). VA records might be too broad - wouldn't that include a Veteran's medical records, by definition?

If you haven't already stumbled across it, [this VA content brief for VA payments, debts, and copay bills](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/payments-debts-copay-bills.md#va-content-brief-for-va-payments-debts-and-copay-bills) might be helpful related to Veteran mental models on financial topics.

**Comment by davidmpickett** [comment]
@mmiddaugh @kmariepat-cityfriends - interesting development for Home Loans that warrants follow up with Office of Strategic Engagement. Sometime between Feb 20 and March 6 all the specific information for regional loan centers was removed from Teamsite:

https://web.archive.org/web/20230220091633/https://www.benefits.va.gov/HOMELOANS/contact_rlc_info.asp
https://web.archive.org/web/20230306022319/https://www.benefits.va.gov/HOMELOANS/contact_rlc_info.asp

**Comment by davidmpickett** [comment]
- I updated "type of care" categories based on convo with @mmiddaugh today
- made a couple tweaks to term names
- did a basic first pass at full horizontal content on a few key benefits
  - Disability benefits
  - Education benefits for Veterans 
  - Education benefits for family members
  - VA home loans
- The benefit-specific content is really rough, but might be good enough for @thejordanwood to flesh out more accordions and us to make calls about how to structure a complex set of information
- Added a column about "confidence level" to indicate terms that we think we have a good sense of, vs ones we might want to explore more via veteran research (@cindymerrill ) or stakeholder input (@kmariepat-cityfriends )
- Source of truth is still [airtable](https://airtable.com/appftQ67nT0eopl4i/tblQXbm3wB9VxIkoQ/viwxaWZCYouGIwuzE?blocks=hide)
- Added some basic formatting to the excel export:
[VBA_Services_2023_05_22.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11537672/VBA_Services_2023_05_22.xlsx)

**Comment by cindymerrill** [comment]
@davidmpickett Will the terms that you want to explore in Veteran research be included in the prototype for usability testing? Let's talk about what you want to learn. Looks like that would be about the following terms from your Excel export:

- Education and career counseling
- Education claim help
- Insurance claim help and financial counseling
