### ISSUE TITLE
 Reword  VA Form flag "Unflag link text" to describe the action.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11285]
## User Story or Problem Statement
VA form flags currently have "Unflag link text" that are a bit confusing because they are not all phrased as an action which leads to confusion on the action on our Flagged Views

![image](https://user-images.githubusercontent.com/5752113/197004836-255dd217-c6bd-4b24-af17-fe0e117d10c6.png)

![image](https://user-images.githubusercontent.com/5752113/197004860-3ebe8c70-1928-4159-b25d-69a870c1e41c.png)

![Screen Shot 2022-10-21 at 2 40 56 PM](https://user-images.githubusercontent.com/85581471/197293038-71bba38f-2aaa-4cb7-b7c4-e50ff6a4e844.png)

<details>
<summary>Original new/deleted screenshot</summary>
![image](https://user-images.githubusercontent.com/5752113/197004882-21de3cce-bad5-4eab-8642-99957ec8b5e6.png)
</details

Current text reads:

- Filename change resolved
- Title change resolved
- Remove deleted flag
- Remove New flag
 
This will need UX consultation, but am suggesting something like `Remove "<flagname>" flag`

## Acceptance Criteria
- [x] The 4 VA Form related flags have their action "Unflag link text" (action text) changed to 
`Remove [flag type] flag`
  - [x] Remove changed-filename flag
  - [x] Remove changed-title flag
  - [x] Remove new flag (`new` instead of `New`)
  - [x] Remove deleted flag 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@wesrowe FYI new ticket from Steve re: the new Forms views. Needs Product to decide language we should use, then can be estimated.

**Comment by wesrowe** [comment]
I feel like this is a good topic for Sitewide CMS. I agree with the sentiment.

Since we're clearing flags, I would suggest the following but would like signoff from perhaps @BlakeOrgan @davidmpickett or @EWashb: 

`Clear [flag type] flag`

So,
- Clear changed-filename flag
- Clear deleted flag
- Clear changed-title flag
- Clear new flag

**Comment by davidmpickett** [comment]
I don't know anything about flags, but unless there is a meaningful distinction between Clearing a flag and Removing a flag, I would suggest using Remove instead of Clear. It's a less ambiguous verb.

I think singular flag is fine. Even you you are removing the flag from multiple forms, you are still only operating on one flag type. The plurality comes from the selection you are applying the action to, not inherent in the action.

**Comment by jilladams** [comment]
Christia went ahead and changed a bit of this in her PR to add the views, https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11251, so I've updated ticket body to match what will ship there.

**Comment by chri5tia** [comment]
In #11115, I overrode the labels for those specific views, but in this ticket, I'll change them at the flag level, which will affect the site where it's used.

**Comment by chri5tia** [comment]
@davidmpickett These flags are set up to to signify if a VA Form has been altered, such as if it's new, deleted, title changed, etc. So that the editor can look at the list an "resolve" these changes. I am not sure what needs to happen or what needs to be done in order to mark them as resolved. So removing the flags is saying, "Okay, I saw this and did the things."
On the back end, technically a flag is added or removed. So removing "deleted" flag. Makes sense. It might also make sense to say "Resolved deleted form".

**Comment by chri5tia** [comment]
PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11335

**Comment by swirtSJW** [comment]
> Edit: Looks like the overrides for the individual views was removed, so that's good.

Yah I removed them so we would not have double overrides.  I called it out here https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11251#pullrequestreview-1151595942

**Comment by EWashb** [comment]
Did we ever figure out the process for who is clearing the flags currently @jilladams?

**Comment by swirtSJW** [comment]
Related discussion here 
https://dsva.slack.com/archives/C52CL1PKQ/p1666653889862889

**Comment by BlakeOrgan** [comment]
Okay, I talked with @laflannery, @davidmpickett, and @EWashb and to summarize what we discussed, we came up with the following for what should show in the action dropdown.

- [ ] Remove "Changed filename" flag
- [ ] Remove "Changed title" flag
- [ ] Remove "New form" flag
- [ ] Remove "Deleted" flag

Begin each option with the action Remove so people know what they're doing to the flag. Have the flag name match exactly what is shown in the table and surround it in quotes to be more user friendly so the the editors know which tag they are removing. [See screenshot](https://drive.google.com/file/d/13FkC824JKoZnmTWI255VTJYtzK-NMWZD/view?usp=sharing).

Also, while we think this updated wording will make it more clear as to what action users are taking and to which flag, we think that there is a larger discussion that needs to be had about how flags are being handled. Right now it seems that removing a flag doesn't equate to fixing an issue that caused the form to be flagged. This essentially just removes the notice that there might be an issue, at least from what I'm understanding. This can lead to flags being removed when a form might still have an issue. Happy to talk more about this if needed.

**Comment by jilladams** [comment]
Ok - I didn't realize that discussion was happening and had cleared Christia's PR to merge with the current ACs on this ticket. It's not merged yet, so may be possible to catch / change still. @chri5tia  holler with concerns. (I'm reviewing the thread for backstory on this update.)

**Comment by chri5tia** [comment]
@BlakeOrgan Currently, only content admins can remove a flag, so the hope is that they do whatever needs to be done e.g. do the things that are the reason we made the tool.
