### ISSUE TITLE
Discovery: Drupal GraphQL module version on PHP 8.1

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#11312]
## Description

[Drupal GraphQL module](https://www.drupal.org/project/graphql) is currently on version 4.x. We use 3.x and have for some time, and have avoided moving to 4.x due to overhead and potential incompatibilities. 

The 3.x version presents issues when used with PHP 8.1. In order to successfully transition to PHP 8.1, we will need to resolve those issues either by making accommodations so that the 3.x version functions, or else move to 4.x, along with all the additional changes needed for that.

## Background
The 3.x version of Drupal GraphQL is now in maintenance mode and is looking for new maintainers. This automatically puts us at risk because bugs will not necessarily be fixed upstream. 3.x is currently covered by Drupal's security advisory policy, but that may change.

Differences between 3.x and 4.x:
- the 3.x version automatically generates a GraphQL schema from Drupal entities and data structures. It exposes Drupal details over the GraphQL API. 
- The 4.x version leaves the GraphQL schema design to the developer, which makes it easier to hide Drupal internal details. The 4.x version requires the developer to setup and map the GraphQL API schema.

Additionally, we may have custom code or patches that changes the behavior of the GraphQL module. These need to continue to work.

## Acceptance Criteria
- [ ] Determine if staying with the 3.x version is even an option, and document outcome of that investigation
  - [ ] Take PHP 8.1 into account
  - [ ] Take Drupal 10 into account
- [ ] If staying with 3.x is possible, document what work would be needed to make it compatible with PHP 8.1 and with Drupal 10
- [ ] Look at requirements for moving to 4.x
  - [ ] Find a way to autogenerate schema like 3.x version
  - [ ] Identify other breaking changes if any
  - [ ] Determine how we would verify our move to 4.x is valid, i.e. has data integrity
- [ ] Make recommendation, based on LOE and consequences/benefits.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Let's chat with Platform CMS

**Comment by EWashb** [comment]
Hey @cmaeng can we sync on this? The lines are a bit blurry on the appropriate team, but we want to give platform cms the first right of refusal on this task.

**Comment by cmaeng** [comment]
@EWashb Platform CMS will want to investigate this and its possible dependencies with the upcoming Drupal 10 upgrade. switching the label for us to refine.

**Comment by ElijahLynn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-CMS-Epics-635835658949301b5392fa8a/issues/department-of-veterans-affairs/va.gov-cms/11312?planning-poker) with Zenhub @timcosgrove

**Comment by timcosgrove** [comment]
Deprecation warnings can be supressed with the following syntax:

**Comment by timcosgrove** [comment]
Ticket for updating 3.x to work under PHP 8.1: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11622

**Comment by timcosgrove** [comment]
Epic created to gather work for updating the CMS to use GraphQL version 4.x: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11625

My thoughts about GraphQL 4.x
* The amount of work needed to be done for this is substantial. Because GraphQL 4.x does not automatically provide schemas and data producers for Drupal entities, where GraphQL 3.x did, we must create those schemas & data producers for every content type, paragraph type, menu,  vocabulary, etc. Anything that is currently queried by Content Build would need to have that query explicitly defined, and the resolution for returning each piece of data explicitly defined.
* This work must be committed at-once. We cannot move some queries to GraphQL 4.x and still use GraphQL 3.x to respond to other queries. 
* This work will take several developers months. It is hard to provide a solid estimate for the time it would take; I would say 3 engineers doing nothing else for 3 months is a very optimistic estimate for this work.
* At the end of this work, we will arrive exactly where we started. There is no change or improvement to the CMS, apart from the fact that we would be using GraphQL 4.x rather than 3.x.
* The opportunity for defects creeping in is very high. In particular, because the process of rendering data to layouts is not testable (apart from broken link checking or data structures that cause Content Release to fail midway), the only testing that could be reasonably done is
  * trying to diff the JSON output of the GraphQL queries from 3.x and 4.x. This file's size is anywhere between 180MB and 300MB. Parsing those diffs will be nearly impossible.
  * Trying to diff the HTML output of content build with GraphQL 3.x and 4.x; there are so many places again where changes could creep in that this would very difficult.

My recommendations:
* While we continue to use Content Build, we continue to use GraphQL 3.x. GraphQL 3.x is currently seeking maintainers; it would be a better use of the VA's resources to have our own engineers maintain GraphQL 3.x, or else contract with an agency or individual to maintain it
* If we are interested in moving to GraphQL 4.x, that should be done in conjunction with a new front-end system and ideally a content architecture overhaul.
