### ISSUE TITLE
Write script for last human review for CMS content

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11497]
## Description

We need to parse out CMS migrator and bot-updated content from the CMS so that we might understand when the last human updated a piece of content. This will only count for published content, not those pieces in draft. This needs to be added to every node. Then you will have to save each node. 

All drafts will need to be floated to the top again (remember Linky) if new revisions are added.

## Implementation Recommendation

- No new revision for bulk scripted edits

## Acceptance Criteria
- [ ] Write script that populates new field with date/time stamp from the last human revision/edit 
- [ ] process every published node on site
- [ ] Determine implementation recommendation 
- [ ] exclude user 1 and CMS migrator
- [ ] No revision log needed
- [ ] create runbook 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@ndouglas do you have the capacity to work on this for Sprint 71?

**Comment by EWashb** [comment]
Currently blocked by @edmund-dunn's work on #11505

**Comment by ndouglas** [comment]
Working to make sure I understand the intended logic here.

So I've coded something to let me introspect and preview the effects on a given node before actually running it.

![Screen Shot 2022-11-22 at 4 11 58 PM](https://user-images.githubusercontent.com/1318579/203422039-83689e3b-a5b6-45fa-b8ce-2ed6bd8cea27.png)

The columns are:
- **NID**: Node ID.
- **VID**: Revision ID.
- **Publish**: Whether this specific revision is published.
- **Default**: Whether this specific revision is the default revision.
- **UID**: The UID of the user who authored the revision.
- **Human**: Whether the authoring user was a human.
- **Touched (Set)**: The value of the last-touched-by-a-human field _actually set_ for the revision.  This is `(not set)` currently, because, uh, because it hasn't been set.
- **Touched (Calc)**: The value of the last-touched-by-a-human field _calculated_ for the revision based on the revision logic.  This will be **Created** if the revision is updated by a human, otherwise 0.
- **Touched (Node)**: The value of the last-touched-by-a-human field as should be reported for the revision based on the per-revision logic, but using the value from the previous revision(s) if set.
- **Touched (Will Set)**: The value of the last-touched-by-a-human field that will be actually set, on the revisions that will actually be altered by the script under development.
- **Title**: (truncated)

NID    | VID     | Publish | Default | UID   | Human | Created             | Touched (Set)       | Touched (Calc)      | Touched (Node)      | Touched (Will Set)  | Title                                    |
------ | ------- | ------- | ------- | ----- | ----- | ------------------- | ------------------- | ------------------- | ------------------- | ------------------- | ---------------------------------------- |
38187  | 576957  | No      | No      | 3073  | Yes   | 2021-11-08 10:33:09 | (not set)           | 2021-11-08 10:33:09 | 2021-11-08 10:33:09 | (not set)           | Worcester Vet Center - Grief and bereave |
38187  | 589875  | No      | No      | 1342  | Yes   | 2021-11-30 09:41:51 | (not set)           | 2021-11-30 09:41:51 | 2021-11-30 09:41:51 | (not set)           | Worcester Vet Center - Grief and bereave |
38187  | 605448  | No      | No      | 3073  | Yes   | 2022-01-12 12:13:01 | (not set)           | 2022-01-12 12:13:01 | 2022-01-12 12:13:01 | (not set)           | Worcester Vet Center - Grief and bereave |
38187  | 609697  | Yes     | No      | 1342  | Yes   | 2022-01-25 18:54:47 | (not set)           | 2022-01-25 18:54:47 | 2022-01-25 18:54:47 | (not set)           | Worcester Vet Center - Grief and bereave |
38187  | 703841  | Yes     | No      | 1317  | No    | 2022-10-12 22:08:38 | (not set)           | (not set)           | 2022-01-25 18:54:47 | (not set)           | Worcester Vet Center - Grief and bereave |
38187  | 725883  | Yes     | Yes     | 3073  | Yes   | 2022-11-21 16:10:42 | (not set)           | 2022-11-21 16:10:42 | 2022-11-21 16:10:42 | 2022-11-21 16:10:42 | Worcester Vet Center - Grief and bereave |

Current logic I have in mind is to set the last-touched-by-a-human field as follows:
- unpublished nodes without human revision authors will not be touched
- unpublished nodes with human revision authors will have the latest (default) draft revision updated with the revision-creation-timestamp from the latest human-authored revision
- published nodes without forward drafts and without human revision authors will not be touched (don't think any of these exist, but they logically may)
- published nodes without forward drafts and with human revision authors will have the latest (default) draft revision updated with the revision-creation-timestamp from the latest human-authored revision
- published nodes with forward drafts and without human revision authors will not be touched (don't think any of these exist either)
- published nodes with forward drafts and with human revision authors will have the latest draft revision updated with the revision-creation-timestamp from the latest human-authored revision _and_ the latest published revision updated with the revision-creation-timestamp from the latest human-authored revision before or equal to that revision.

Tomorrow, I'll illustrate this logic a bit more with some examples.

**Comment by ndouglas** [comment]
Oops, I ended up getting distracted by some odd behavior and didn't resume where I was.

Anyway, I pressed on and am working on the script to set values now.

I think I'll go ahead and open a PR on this so that Edmund and I can poke around and see if it behaves as intended before going further.

**Comment by ndouglas** [comment]
```
real    111m41.037s
user    56m47.870s
sys     4m53.514s
```

Appears to have worked without issues 😬 🙏🏻
