### ISSUE TITLE
FE: Establish criteria to remove flipper facility_locator_show_community_cares                             

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11598]
## Description
As we investigate each Facilities related Flipper, document the criteria and timeline for when it should be removed.

Refer to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656

## Acceptance Criteria
- [ ] Criteria for Flipper removal is created in this ticket 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [X] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
@mmiddaugh The ticket you point out is, indeed, relevant. As far as I can tell, though, this was closed without any meaningful work. The feature flag is still present.

### Some more findings
- [This issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10698) discusses the need to "invert" this feature flag. Rather than have a flag that indicates whether this feature should be on, the decision was to have a flag that indicates whether this feature should be off (went from using `facility_locator_show_community_cares` to using `facilities_ppms_suppress_community_care`). This way, if there are problems determining the value of the feature flag, the feature will be on. That work was completed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13638), which rendered the existing Flipper feature flag (the one in this issue, `facility_locator_show_community_cares`) no longer applicable. **It can be removed.**
- Later, there was [additional work](https://github.com/department-of-veterans-affairs/vets-website/pull/18296) based on [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28782) that adds another Flipper feature flag to suppress _all_ community-care searches (seemingly in the event that things with these searches are determined to be broken, so that the options can be removed from the search dropdown). This does not specifically affect this current ticket, but it's useful to mention here as it's related.

### Steps for removal
#### vets-api
- This feature flag is no longer needed and can be removed.
- **HOWEVER**, this is a very interesting case because this feature flag is being used to test some behavior around Flipper toggles in general.
- So:
   - [The entry in `config/features.yml`](https://github.com/department-of-veterans-affairs/vets-api/blob/108d98af05d962434138f48563fd7c62af5d493f/config/features.yml#L335) can be removed.
   - [`event_subscriber_spec.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/ea27431db642ea0ab35b3e042f797d82626c4f4a/spec/lib/flipper/instrumentation/event_subscriber_spec.rb) needs to be updated to use a different feature toggle for testing.
   - [`feature_toggles_controller_spec.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/dd2a62c6704c8f6d181116a485a1c2d201da4d31/spec/controllers/v0/feature_toggles_controller_spec.rb#L7) needs to be updated to use a different feature toggle for testing.
   - Should there be feature toggles specifically for testing? Who would own that?
#### vets-website
- The code using this feature flag as a gate for the feature has already been removed (it was replaced by the code using `facilities_ppms_suppress_community_care`).
- There are, however, some references to `facility_locator_show_community_cares` that remain.
   - One is the entry in `featureFlagNames.js`. This can be removed.
   - The rest are in files outside Facilities' ownership. They are test files that have seemingly copied actual Flipper json values into mocks. They can be removed, but we'll likely need a code review from each of the owners.

**Comment by jilladams** [comment]
Scrum: this needs a follow up implementation ticket. That ticket should cover: 
* Removing the vets-api test or replacing the flipper used in that test with a different one
    * Platform support ticket & follow up to see if Plat is willing to take over that test & suggest a flipper
* Finish the vets-website PR and merge

**Comment by ryguyk** [comment]
Closing this issue. The discovery is done. Refer to [follow-up ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14112) for next steps.
