### ISSUE TITLE
FE Switch link not showing on policy page.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11691]
[Lovell VA Policies](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/policies/) page is not showing a switch link, 
![image](https://user-images.githubusercontent.com/5752113/203407688-d26bcf4e-51f3-4331-ada9-88daf3015191.png)

BUT
the [TRICARE pag](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/policies/)e is showing the switchlink.
![image](https://user-images.githubusercontent.com/5752113/203408206-bcbcfee1-2059-4128-b8f6-6e595080147c.png)

Likely the issue is that the VA policy page is a VAMC System Policies Page while the TRICARE version of the page is a VAMC Detail Page.

**Comment by dsinla** [comment]
One is a Detail page one is a Policy page, the TOGGLE logic should look at existence of the corresponding page. We suspect something about the lookup isn't quite right.  

Potentially might occur as well on:

Medical records
Register for care
Policies
Billing and insurance

**Comment by maxx1128** [comment]
I did another check and confirmed there are only two policy pages being returned in all of the Drupal data from the Lovell processing, and they have proper Switch links. So it's something after the Lovell processing that's causing this.

<img width="610" alt="Screen Shot 2022-12-07 at 4 04 58 PM" src="https://user-images.githubusercontent.com/10790736/206295701-bc18e0d7-32e9-407a-bdd8-5a3889fcb961.png">

**Comment by maxx1128** [comment]
Okay, _finally_ got the fix.

The cause: when a page doesn't have breadcrumbs, there's a function that generates that data and attaches it to the `entityUrl` object. But it assumed that object only has the breadcrumbs and the `url` properties, and anything else (like the switch path) would get lost. As it turns out, the VA Policy page had that very issue.

The solution: the breadcrumb function was adjusted to merge the data instead of overwrite it, which preserved the switch link. I've confirmed it works locally and am off to get a drink.

**Comment by maxx1128** [comment]
Pull request with the fix: https://github.com/department-of-veterans-affairs/content-build/pull/1393
