### ISSUE TITLE
SPIKE: Assess test coverage needed for homepage update

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11704]
## Description
https://dsva.slack.com/archives/C52CL1PKQ/p1669147632360019

We do not have a firm rubric for when / what code changes require test coverage, but we do want to be thoughtful about test coverage for the updated homepage. This ticket is a SPIKE to think that through. 

Areas for consideration: 
* What could break, that we want to protect against? 
* What code has logic dependencies that must be in place? 
* What kinds of test coverage are most appropriate for these pieces of code? (Unit tests, cypress, other?)

**Time-box to ~1 day**

## Acceptance Criteria
- [ ] Assess homepage iteration for necessary test coverage
- [ ] Comment on this ticket to spell out tests we should add
- [ ] Either cut new tickets or assign this ticket to Wes / Jill to write new tickets

**Ticket should not close until new tickets are written,** in the Harden homepage epic.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@apisandipas this is marked In Review/QA - could you add some notes re: takeaways?

**Comment by apisandipas** [comment]
# Homepage Testing Strategy 

## Questions:

### What Could Break?
If content is missing in any major section of the page, it would cause awkward rendering issues.

### What Code has logical dependencies that must be in place?
The most complex component of the new homapage is the Homepage Search, simply because it's a React-widget residing in `vets-website`, while everything else lives as a static template in `content-build`.

### What kinds of test coverage are most appropriate for these pieces of code?

The most appropriate type of testing for the majority of the new homepage is Cypress end-to-end testing to assure the rendering of content where expected.

## Existing Tests

Currently the tests for the homepage include verification of:

* 4 "Buckets" (Boxes just below hero)
* 11 Benefits Hubs 
* 3 OPIA News Features 
* Asserting the presence of the Google Analytics scripts 

## Recommended Tests

We don't want to specify the **content** of dynamic sections, only that the **content is present**, as this content is likely to change overtime, independent of our template and test suite. I recommend we assert the presence of the major components of each section. When it comes to links, we should assert they both have text and a value URL in the HREF attribute. 

### Hero Section 
* Assert presence of Headline, Blurb, Link Text and HREF 
* Assert presence of create account button and it's href. 
* Assert Presence of "Learn how.." link and its HREF 

### Top Pages (Common Tasks partial)

#### Homepage Search 
NOTE: The homepage search is powered by a React widget. 

* Assert that the component renders without an error. (Enzyme test within `vets-website`)
* Assert the validity and presence of 3 "Other Search Links"

#### Top Pages Links
* Assert the presence of the Heading H2 and the presence / validity of links.

### News Spotlight 
* Assert the presence of Image, Headline, Link Href, Blurb text, Read more link. 
* Assert the presence / validity of More VA News links

### Homepage Benefits 
* Assert the presence of H2 Heading 
* Assert the present of Benefit blocks 
  * H3 / Link + Text 

### Email Update Signup Form
* Assert that the form renders and can be submitted. 
* Assert that it must be submitted with a valid email address value.

**Comment by jilladams** [comment]
@apisandipas how do you feel like we should break up this work, ticket-wise? (Willing to cut tickets we could refine tomorrow? I'm happy to help on a zoom if that's best.) Not certain if these need to each be granular tickets, or could be grouped along some logical lines, etc?

**Comment by apisandipas** [comment]
@jilladams Since I imagine all the tests would reside in the same file and resemble each other (ideally) in structure, I'm thinking this could for the most part be done as a single ticket. If we wanted to split it up granularly, I think perhaps splitting it into top half / bottom half would be more favorable than a separate ticket for each section, just to reduce the overhead of ticket / PR / review churn.

**Comment by wesrowe** [comment]
@apisandipas, could I trouble you to also make a recommendation regarding e2e tests for the soft-launch modal?

**Comment by wesrowe** [comment]
Implementation ticketed: #11954.

**Comment by jilladams** [comment]
CLosing since we've assessed and ticketed next steps.
