### ISSUE TITLE
SPIKE: Investigate variability in GraphQL time

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11767]
## Description
GraphQL timing within Content build ("Get Drupal content") can be widely variable. Interestingly, the times cluster around 2 values, roughly 4.5 minutes and 9 minutes. There are occasional outliers, but by and large the timing data varies between one or the other. 

(e.g. 400K == 400,000ms == 400seconds)
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/203623/205147939-338533b8-34e4-4278-a3a8-52f5eeaecddd.png">
https://vagov.ddog-gov.com/dashboard/vnk-g4s-fru?fullscreen_end_ts=1669923931994&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1669319131994&fullscreen_widget=8443129296966730&from_ts=1669743450031&to_ts=1669916250031&live=true

We should investigate why this variability exists. If we can control it, we can get all GraphQL steps to be in the lower range, which will significantly improve Content Build times.

## Acceptance Criteria
- [ ] **Determine Cause of Response Time Differences** - Investigate why this exists
- [ ] **Record Cause(s)** Detail the cause(s) on this issue
- [ ] **Follow-up Tickets** If a clear course of action is indicated by the research, write follow-up tickets for it.
- [ ] **Knowledge Shared** Once cause of issue is determined, share with applicable/interested parties.

**Comment by ElijahLynn** [comment]
There could be certain cache tags getting invalidated or thinking about it the inverse way, certain cache groups that are populated.

**Comment by ElijahLynn** [comment]
There is a chance that this is related to the Memcache (Elasticache) issues we have been seeing lately. #11781

**Comment by ElijahLynn** [comment]
This might be related to the queries coming in during a DB backup. If so, we would want to setup replication and do the backups on the read-replica.

**Comment by ElijahLynn** [comment]
Another thing that could have affected this was up until a couple weeks ago, the ASG had the EC2 instances popping up in a random selection of 1A, 1B or 1C. And the Memcache nodes are in 1B and 1C, and the RDS is in 1C. So if the actual application code is popping up in a different AZ, for example 1A, then we have network requests crossing over 3 boundaries (1A, 1B and 1C) and we could see a notable variance here. Because for example, if everything is in 1C except for Memcache being distributed over 1A and 1C with two nodes vs Memcache being fully in 1C, the GQL request time goes from 5m to 4m, for a 20% variance. 

I have work in #11756 to make all the Memcache nodes in the same AZ, 1C, for now. This should be rolled out today and we can see if these times normalize at all. If we still see variance then we can look at the RDS backups every 15m too.

**Comment by TheBoatyMcBoatFace** [comment]
Moving to Sprint 74 due to interaction with
- #11756

**Comment by TheBoatyMcBoatFace** [comment]
Shifting to Sprint 74 due to the holidays and OOO schedules.

**Comment by timcosgrove** [comment]
I do not think this is worth the time investment it would require. I also strongly suspect that the differences are due to cache cold/warm differences.
