### ISSUE TITLE
New KB article : How to use the content search tool

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11784]
## Background context
**What is the request for?**
An article to tell admins how to use the new content search tool within the content audit tools available. 

**Person and team of requester:** 
Erika Washburn/Sitewide CMS

**Priority or deadline for request**
Sprint 73- high priority
 

**Is the article associated with an ongoing product or feature update?**
- [x] Yes [Add the link to the relevant issue](will add the new URL when live)
- [ ] No

  
## If requesting a new article:

**Audience:**
Who is this intended for? Internal teams (us, sitewide content team, etc.)
- CMS audit tools

**Related KB articles, if applicable:** 
- [If you know that related KB articles already exist, link them here]

  
**Any other relevant documentation, if applicable:** 
- [for example, could be the VA content style guide]

## Process
1. Sitewide CMS and Helpdesk teams will review request and confirm no current, applicable KB article/content exists.
2. Refine request and prioritize
3. Update KB article tracker to indicate that the article has been requested and is in progress
4. Assign to appropriate product team
5. Draft article content 
6. Sitewide CMS team will review for formatting and writing style guidelines
7. Helpdesk team will review for functionality and editorial tone
8. Publish
9. Update KB article tracker to indicate that the article has been published

## Acceptance Criteria
- [ ] Article is created using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) 
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Once published, the person requesting the article has been notified

**Comment by laflannery** [comment]
@swirtSJW I was writing this KB article and I have 2 questions I'm hoping you can answer:

1. What does the "Search word or phrase field" field actually search? I would like to confirm what I wrote is accurate or if there are other fields this searches that should be called out:

> This will search the content fields (i.e. rich text fields, plain text fields, etc.) within the entities for the keyword(s) entered.

2. I noticed (and I think I found in your PR notes?) that you have to type the exact name of the section you would like to filter by into the Section field, this will not work any other way.  Because this is so specific, is there any way we could add help text to this field, like some of the other fields have? I realized you have already merged this PR so if this is possible I could open a new ticket for next sprint.

**Comment by laflannery** [comment]
Putting the answers I got yesterday from Steve here:
1. Searches everything on the page not specific fields
2. We can put help text on the field, it is possible. Now that I know this is just Randi, I think maybe we can hold off on this for now and see how it goes and update as needed later on

**Comment by EWashb** [comment]
article complete https://prod.cms.va.gov/help/cms-basics/content-search-tool

**Comment by laflannery** [comment]
Thanks, I forgot!
