### ISSUE TITLE
Heading for Nearby Vet Centers if there are no nearby Vet Centers

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11789]
## Description
Vet Center Location pages include a "Other Nearby Vet Centers" section which is auto-populated with up to five nearby Vet Centers pulled from a 120-mile radius. Even with this radius, some Vet Centers have no "other nearby" Vet Centers. In these cases, the heading is still displayed without a list beneath.  

These results do not come from Drupal, but come direct from somewhere else (maybe Facility API, to be confirmed whether this is an API call within an API call to get specific info).

### Nested defect
For https://www.va.gov/grand-rapids-vet-center/locations/, we should see at least 2 Vet Centers within 120 miles, already, which can be seen in the [Facility locator results for this Vet Center](https://www.va.gov/find-locations/?page=1&address=Grand%20Rapids%2C%20Michigan%2049506%2C%20United%20States&facilityType=vet_center&serviceType&latitude=42.94449690443892&longitude=-85.63844959499795&radius=131&bounds%5B%5D=-88.22716634162103&bounds%5B%5D=40.48713493943856&bounds%5B%5D=-83.04973284837511&bounds%5B%5D=45.30754670807477&context=Grand%20Rapids%2C%20Michigan%2049506%2C%20United%20States&searchString=Grand%20Rapids%2C%20Michigan%2049506%2C%20United%20States). 

ACs mean we need to address this bug.

## Options
- We may be able to include 
    - CAPs: can't do this yet -- because they don't exist in the Facility API yet (blocked on LH V1)
    - Outstations: could expose these now
- Increase radius. Existing paradigm on Facility Locator. -- now included in ACs
- Remove the header if no results returned -- now in ACs
- Keep the header, but provide a "no results" message -- rejected

![image](https://user-images.githubusercontent.com/62269210/205375841-e206deb4-612c-4085-a3a7-580d35394d89.png)

[Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1670006794105279)

## Acceptance Criteria
- [ ] ~Vet Center "Other nearby Vet Centers" displays up to 5 Vet Centers or Vet Center Outstations within 200 miles as default~
- [ ] ~If no locations are within 200 miles, remove the header "Other nearby Vet Centers"~
- [ ]  Vet Center "Other nearby Vet Centers" displays up to 5 Vet Centers or Vet Center Outstations within 120 miles as default
- [ ] Vet Center "Other nearby Vet Centers" displays up to 5 Vet Centers or Vet Center Outstations within 120 miles birds-eye-view as fallback
- [ ] If no locations are within 120 miles birds-eye-view, remove the header "Other nearby Vet Centers"

**Comment by jilladams** [comment]
From refinement: if we return 200 miles for everything, this might increase build time. Keeping the conditional logic is a little more complex to implement, but would keep the build time down.

**Comment by jilladams** [comment]
From planning: the original decision to keep 120 as default and only expand radius to 200miles if no results was made in order to conserve build time. However: on second thought, Eli feels that 2 calls might actually be more expensive to the build than 1. We won't be able to tell that until we're in implementation, so: we'll pull this ticket in as defined, and if we determine that 1 call (default to 200 miles) is the better path, we can make that decision during sprint. 

Upped estimate to 5 to cover the complexity of sorting that out.

**Comment by xiongjaneg** [comment]
We have an assumption that one call is faster than two but needs testing.

**Comment by xiongjaneg** [comment]
Consider percentage of calls are satisfied by 1 versus needing additional mileage

**Comment by eselkin** [comment]
120 Mile radius is defined in `vets-website`: 
`src/applications/static-pages/facilities/vet-center/NearByVetCenters.jsx`
with:
`const NEARBY_VET_CENTER_RADIUS_MILES = 120;`

Difficult to determine if 1 call vs 2 calls is impactful.
Will be different based on highly dense regions or more sparse ones.

**Comment by eselkin** [comment]
I can handle this ticket early in this next (92) sprint. But it currently is not worked on in Sprint 91.

**Comment by xiongjaneg** [comment]
Should we just change the default to 200 miles?
Should we have the fallback process of 2 queries, 1) 120 doesn't return any, 2) 200 doesn't return any.

Per Michelle, decision is default to 200 miles. Then if 200 doesn't return any, remove the header.

**Comment by eselkin** [comment]
After debugging a bit (now that I have vets-api working locally), I am finding some interesting issues. The reason that `Other nearby Vet centers`
renders for this instance but shows no nearby locations is that the initial API call to the DB gets 5 results that are within a birds-eye 120 miles. However, in "driving"-miles they are all over 120 miles. 126 miles is the closest. 
@mmiddaugh 
Do we really want to increase the radius to 200? Or do we just want keep it at 120 and ignore the driving miles increase (at 120 there are 5 facilities returned).

**Comment by eselkin** [comment]
After discussion with @mmiddaugh we have decided to use birds-eye view when results exist but have been excluded because driving distance extended farther than the radius. Driving directions are still calculated in order to sort the distances from the page's facility (however, this is likely moot because order doesn't really mean the results will be in order of proximity for the user anyway).

Each "nearby" facility still maintains a link to search by google maps so the user can determine if the facility is in driving distance for them.

**Comment by eselkin** [comment]
New AC
- [ ] Vet Center "Other nearby Vet Centers" displays up to 5 Vet Centers or Vet Center Outstations within 120 miles as default
- [ ] Vet Center "Other nearby Vet Centers" displays up to 5 Vet Centers or Vet Center Outstations within 120 miles birds-eye-view as fallback
- [ ] If no locations are within 120 miles birds-eye-view, remove the header "Other nearby Vet Centers"

**Comment by jilladams** [comment]
Double checked this since it's now verifiable in prod: 

[Facility Locator: zoomed out to get ~120 miles around Grand Rapids](https://www.va.gov/find-locations/?address=Grandville%2C%20Michigan%2049418%2C%20United%20States&bounds%5B%5D%5B%5D=-88.22716634162103&bounds%5B%5D%5B%5D=40.48713493943856&bounds%5B%5D%5B%5D=-83.04973284837511&bounds%5B%5D%5B%5D=45.30754670807477&context=Grandville%2C%20Michigan%2049418%2C%20United%20States&facilityType=vet_center&latitude=42.904220899185816&longitude=-85.76588256490362&page=1&radius=123&searchString=Grandville%2C%20Michigan%2049418%2C%20United%20States&serviceType&bounds%5B%5D=-88.20067880075986&bounds%5B%5D=40.69453740810934&bounds%5B%5D=-83.33108632904964&bounds%5B%5D=45.03745157990642) (based on example in ticket)
<details><summary>Screenshots</summary> 
![Screenshot 2023-09-12 at 4 27 54 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/a0feaa91-8df3-4b3e-b99d-49b3f000bc02)
![Screenshot 2023-09-12 at 4 27 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/73e3003f-f2ac-418e-84aa-8b605a56f397)
</details>

Vet Center page: https://www.va.gov/grand-rapids-vet-center/locations/

**Nearby locations** comparison between the 2 (this is hard to repro exactly bc when you zoom the map out, it picks a different center point, but: this is the gist): 

| Facility Locator list | Locations page list |
| --- | --- |
| 91.5 miles - South Bend Vet Center |  **listed 1st** |
|99.5 miles - Saginaw Vet Center  |  **listed 2nd** |
|114.5 miles - Milwaukee Vet Center  |  not listed. (As the crow flies, is close, but driving, is on the other side of the lake |
|116.0 miles - Evanston Vet Center  | Not listed |
|126.6 miles - Forest Park Vet Center  |  Not listed |
|127.5 miles - Chicago Vet Center |  Not listed |
|128.0 miles - Fort Wayne Vet Center |  Not listed |
|128.4 miles - Traverse City Vet Center |  Not listed |
|128.6 miles - Gary Area Vet Center |  **Listed 4th** |
| Not listed | Pontiac vet center **listed 3rd** | 


And: verified that a Vet Center with no nearby locations, doesn't list an empty heading: https://www.va.gov/billings-vet-center/locations/

I would be content to close this, with one question: why this Grand Rapids center is only showing 4 locations instead of 5, given that Milwaukee and Evanston should theoretically appear in the list.

**Comment by jilladams** [comment]
From planning: 
* When we query for 5 locations, we receive 5 results that include the Vet Center we're looking at (e.g. Grand Rapids), so we exclude that one and display 4 results. 
  * Michelle signed off on keeping the display of 4, rather than expand the query to 6 results in order to get 5 to display. 
* Lighthouse provides the Facility API that we use for Facility Locator, and they ahve implemented the queries to PostGIS which provides the bounding box / radius results based on input. So: the exactness of which results we get based on which center point / query isn't really within our control. 

For big picture: we want to add Outstations and CAPs to further refine this, in future. Closing.
