### ISSUE TITLE
Discovery: HUD API for Income Limits data

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11929]
### User stories to guide API investigation

_As a Veteran, I want the app to calculate my GMT (geographic means test) threshold based on my zip code and number of dependents so that I know what income threshold applies to me for free medical care._

_As a Veteran who lives in Fairfield county, CT, I want the app to use the highest of the GMTs for my county so that the app accurately represents the VA's policy of using of the most generous threshold available in a county._

_As a Veteran who lives in a zip code that crosses county boundaries (eg? 83414, 83342, 82930, 82063), I want the app to help me identify which county I actually live in so that my GMT threshold is looked up correctly._

### Background

We determined in #11643 that HUD has an API to provide the same data that Income Limits tech stakeholders pointed us toward as the source. (They pointed us to this [Excel file](https://www.huduser.gov/portal/datasets/il/il22/Section8-FY22.xlsx).)

In this ticket, we need to determine whether the HUD API is a performant data source that would support the functionality we need.

### Assumptions:
- Ask questions of the HUD API owners 
  - Note: This is what Josh Faulkner said about the source data: `Its not really scrubbed, its just trimmed and sorted in a way that vista requires for it to be imported. The source data is here: https://www.huduser.gov/portal/datasets/il/il22/Section8-FY22.xlsx'
  - Another Josh Faulkner email: `The data is sourced from HUD, not from within VA. Roni and team just coordinate those HUD GMT updates to VistA and ES/IVM at the end of each year. The public facing site just needs updated in the same manner from the same source annually.'
  - `vista` here is "VistA", the VA medical records platform. At this time we don't know why VistA would be mentioned in a discussion of Income Limits.
- Review documentation
- No technical spike work in this ticket

### Technical questions:
- What traffic level can the API support?
- How would vets-api access it (keys, etc)?
- What look-up queries does it support?
  - zip code?
  - city, county?
  - can we get cities and counties per state from it?

## User Story Discovery Results
See [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11929#issuecomment-1368050635).

### What traffic level can the API support?

Unknown at this time. Investigating this will require enquiry to the API owner. However, we aren't likely to hit any HUD APIs in the new app since they don't offer the flexibility our new tool will need.

### How would vets-api access it (keys, etc)?

A bearer access token would need to be created. There plenty of examples in vets-api of using a bearer token (bid, veterans_health, mail_automation, etc), so this is not paving new ground.

#### Getting an Access Token for HUD APIs

Follow these steps to create an account and get an access token:

1. [Sign up](https://www.huduser.gov/hudapi/public/register?comingfrom=2,3) for an account and select the Datasets API you want to access.
2. Confirm your account, if it's new - Check your inbox for a confirmation email from HUD User.
3. After [log in](https://www.huduser.gov/hudapi/public/login), Get an access token by clicking on Create New Token.
4. Use it in the Authorization: Bearer header to make API calls.

### What look-up queries does it support?

The fully list of endpoints and their respective parameters and return values are discussed on the [HUD FMR/IL API landing page](https://www.huduser.gov/portal/dataset/fmr-api.html).

#### Zip code?
The HUD IL API does not have a zip code lookup. It does offer a [USPS Crosswalk API](https://www.huduser.gov/portal/dataset/uspszip-api.html), but the resulting return data doesn't include enough information to then lookup the GMT in the IL dataset. More on this is discussed in the [user story discovery results](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11929#issuecomment-1368050635).

#### city, county?
No IL data lookups by city or county exist. In fact, one can only lookup IL data by 10 digit FIPS code. [See the IL data endpoint](https://www.huduser.gov/portal/dataset/fmr-api.html#:~:text=Get%20IL%20data%20for%20a%20town,il/data/%7Bentityid%7D).

#### Can we get cities and counties per state from it?

- It can list [all states](https://www.huduser.gov/portal/dataset/fmr-api.html#:~:text=Get%20a%20list%20of%20all%20states,fmr/listStates)

- It can list [all counties given a state](https://www.huduser.gov/portal/dataset/fmr-api.html#:~:text=Get%20a%20list%20of%20all%20counties,fmr/listCounties/%7Bstateid%7D)

- It can list [all IL data for a given state](https://www.huduser.gov/portal/dataset/fmr-api.html#:~:text=Get%20IL%20data%20for%20a%20state,il/statedata/%7Bstatecode%7D).

## HUD API recommendation

Due to the needs of the new app which are still emerging, the HUD IL API is insufficient for several reasons:

- It does not support lookup of GMT threshold (the primary reason to use the HUD API is to get the GMT threshold) by zip code
- It does not support lookup of GMT given state + county.
- It only supports lookup of GMT by a given ten digit FIPS (referred to as "entity id" in the HUD API documentation. There is no known API for looking up the ten digit FIPS code, and Veterans are unlikely to know what this is nor how to obtain it on their own.

We also know that the legacy app doesn't use the API, probably for the above reasons. However, the legacy app does use the [HUD IL Excel data](https://www.huduser.gov/portal/datasets/il.html) published by HUD every year, so it is likely we will need to do the same for the new application.

I believe a Lighthouse powered API, proxied through vets-website, is the best choice for the new app, given what we now know.

## Acceptance Criteria

- [x] Documented in this ticket:
  - [x] Recommendation re HUD API
  - [x] Support rec based on questions above, any other considerations

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
**Contact info:**
Contact us at helpdesk@huduser.gov with questions, comments, or orders.
Fax: 1-202-708-9981
If you are experiencing difficulty accessing the data in the Income Limits Documentation System, please use the following link: https://www.huduser.gov/portal/datasets/il.html#2022_query and press the "Click Here for FY 2022 IL Documentation" button. Questions relating to the data used to calculate Median 
Family Incomes (MFI) and/or Income Limits (IL) or the calculation methodology used to generate the MFI estimates and associated ILs should be directed to pprd@hud.gov.
https://www.huduser.gov/portal/datasets/il/il2022/select_Geography.odn****

**Comment by wesrowe** [comment]
Re an API for the VBA data we need (eg Pension thresholds), I'm going to email our tech stakeholders to get them aligned on whether this is a possibility or not.

**Comment by dsasser** [comment]
The idea of using an API approach to power the new app is under review as an ideal approach. This [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1671663118539939) offers a lot of commentary on the subject. At this point we have more questions than answers. A notable quote from Steve Wirt on the state of things currently, found in this Slack thread:

> I am not sure we fully understand the problem space.  We know some of how the current process works.  We do not know what the pain points are or the failure points.   We also know there are other sources of data, I am not sure if we know what those are...

We are also aware that there appears to be some business logic applied to the processing/uploading:

> The EAS*1*220 pre/post install routines include logic to select and upload the first record for each unique Income Year/ FIPS Code (first 5 digits)/and MSA from the sorted spreadsheet.

-Roni Flowers, via email titled: VBA Income Limits data source

>  The concerns that Daniel is surfacing are concerns that I share almost to the tee. I do not want to try to duplicate business logic that is already being done elsewhere. It's pointless at best and risky at worst.

-Ryan Koch, Slack thread

In terms of next steps, we probably should start with an understanding of how the current app is leveraging data.

> I am interested with what method the old code uses to pull in the spread sheet that drives it. If most of this system does what they want, it seems silly to start brand new.  But that leads me back to not knowing what else was wrong with the old system.

-Steve Wirt, Slack thread

**Comment by dsasser** [comment]
I'm currently working to answer the user story questions posed in the issue description [here](https://docs.google.com/document/d/1AP_N8pf08x0DtopWzXd4eQT8IsoWb9fC-AaC1Apq1BQ/edit#).

Once that document is complete, I'll update this issue accordingly.

**Comment by dsasser** [comment]
# User Story Discovery Results

<details>
  <summary>As a Veteran, I want the app to calculate my GMT (geographic means test) threshold based on my zip code and number of dependents so that I know what income threshold applies to me for free medical care.</summary>

Some considerations:
- The raw HUD IL dataset does not include zip codes. It uses a 10 digit FIPS code which appears to be: the 2 digit state code + 3 digit county code + county/town code?. For the HUD API documentation, it refers to this code as the “entity id”, which is used in several of the endpoints as query parameters. [See HUD API documentation](https://www.huduser.gov/portal/dataset/fmr-api.html#:~:text=Get%20IL%20data%20for%20a%20town(in%20NE%20state)%2C%20county%20or%20metropolitan%20area.).
- Some zip codes may traverse [multiple counties or even states](https://www.huduser.gov/portal/datasets/usps_crosswalk.html#faq:~:text=ZIP%20Codes%20do%20not%20align%20with%20political%20or%20administrative%20boundaries.%20ZIP%20Codes%20frequently%20cross%20county%2C%20city%2C%20and%20town%20jurisidctions.%20ZIP%20Codes%20may%20also%20potentially%20cross%20state%20borders), meaning there could be more than one row for a given county. Eg: Fairfield County, CT has 23 records.
- The legacy application adds a 5 digit FIPS code (the first 5 digits of the 10 digit FIPS code) to the dataset before importing it to the backend. In the case of Fairfield, CT, 23 records share the same 5 digit FIPS code (since only the town/sub-county differs among the 23 records. When there are multiple records with duplicate 5 digits FIPS codes, only the record with the highest GMT (from column l80_1) is imported into their backend.

## Step 1: Get 5 Digit GEOID from HUD USPS Crosswalk API

Since the HUD IL API is not “zip-code aware”, we first need to obtain a FIPS code given a zip code. To do this, we can leverage the HUD USPS Crosswalk API.

The HUD USPS Crosswalk API contains several types of lookups. The one we are interested in is type 2 (zip-county). This type takes two query parameters: type, and query, where type is the type of query (see the chart for query types), and the query is the primary data parameter (in our case, a 5 digit zip-code).

An example request in CURL (YOUR_API_KEY is a bearer token which is generated by following the ‘Get Access Token’ steps on the [API documentation page](https://www.huduser.gov/portal/dataset/uspszip-api.html)):

```bash
curl -H "Authorization: Bearer YOUR_API_KEY" -G -d 'type=2&query=97086' https://www.huduser.gov/hudapi/public/usps
```

An example response:

```json
{"data":{"year":"2021","quarter":"4","input":"97086","crosswalk_type":"zip-county","results":[{"zip":"97086","geoid":"41005","res_ratio":1,"bus_ratio":1,"oth_ratio":1,"tot_ratio":1,"city":"HAPPY VALLEY","state":"OR"}]}}
```

Within the result returned by the API we are provided with a 5 digit code, referred to as a geoid in HUD API responses: _41005_.

This geoid is the first 5 digits of the 10 digit FIPS code from the fips2010 column of the HUD IL spreadsheet. This code is a representation of the two digit state FIPS code + the three digit FIPS county code. In our example: state = 41, and county = 005.

**Note:
As an aside, the HUD USPS zip-county dataset can be downloaded from the HUD website, rather than using an API. However, in terms of importing this dataset, this poses a new challenge, since the dataset changes (potentially) every quarter. So any automated routines that pull in this data will be subject to changing parameters over time, in order to fetch the most recent data. Additionally, it would then be prudent to maintain at least several years worth of data history, in order to fulfill requests for previous tax years.

## Step 2: Get Ten Digit FIPS Code

In a world where the HUD IL API accepted a 5 digit geoid, we would be able to remain within the HUD ecosystem of APIs. The workflow would be as simple as query HUD USPS Crosswalk API using zip code -> query HUD IL API using the geoid from the first query -> find the correct value based on the number of dependents. The GMT data is derived from the Low (80%) Income Limits set of columns, beginning with l80_. These columns range from l80_1 to l80_8. The numbers after the l80_ prefix represent the number of household family members. In our example, there are no dependents, and so the column l80_1 is used to retrieve the GMT threshold.

The HUD IL API does not accept a 5 digit geoid as a parameter, therefore using the HUD API at this stage is not yet possible, which further implicates a new API under our control is likely imminent and necessary for zip-code to GMT threshold lookups.

As is the case for the [current legacy application](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/LegacyGMTThresholds?FiscalYear=2021&PriorityGroupLevel=8), an ingest process will import records into a backend database for querying. This ingest process may, much like its predecessor, add an additional column to the data which represents the [5 digit FIPS code](https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html#:~:text=To%20make%20these%20county%20FIPS%20codes%20unique%2C%20the%20state%20FIPS%20codes%20are%20added%20to%20the%20front%20of%20each%20county%20(01001%2C%2002001%2C%2004001%2C%20etc)%2C%20where%20the%20first%20two%20digits%20refer%20to%20the%20state%20the%20county%20is%20in%20and%20the%20last%20three%20digits%20refer%20specifically%20to%20the%20county). The expectation, then, is that an API that we control, will have an endpoint for querying the HUD data given a 5 digit FIPS code/geoid.

In our example, the HUD USPS Crosswalk API provided 41005 as a geoid given the zip code of 97086. This corresponds to the full ten digit FIPS2010 code (retrieved using the EXCEL version of the HUD IL data): _4100599999_.

## Step 3: Query HUD IL API with 10 FIPS Code

Now that we have the 10 digit FIPS code, we can query the HUD IL API for the record. We use the [il/data/[entityid} endpoint](https://www.huduser.gov/portal/dataset/fmr-api.html#:~:text=Get%20IL%20data%20for%20a%20town,il/data/%7Bentityid%7D) to obtain the record for Clackamas County, OR.

**Note that the HUD API takes a year as a parameter for most requests, as is true for the HUD IL API. Due to the legacy app falling behind by over a year, we need to target the 2020 FY dataset, in order to match the 

The result set will include all income levels, but the ones we are interested in for GMT are represented with column names beginning with 180_. To find the correct result, we need to know the number of dependents in order to select the data from the corresponding column. In our case, we use “1” (no dependents/single person family) to obtain: $51,600. This matches the current legacy app's GMT threshold as seen below:
![Screen Shot 2022-12-28 at 2 19 18 PM](https://user-images.githubusercontent.com/221539/210102898-3977bd27-8438-4778-b1f6-25eb118fa2ae.png)

</details>

<details>
  <summary>As a Veteran who lives in Fairfield county, CT, I want the app to use the highest of the GMTs for my county so that the app accurately represents the VA's policy of using of the most generous threshold available in a county.</summary>

We can achieve this with the following rule: If there is more than one record for a 5 digit FIPS, then use the one with the highest GMT Threshold (highest value in the I80 _1 column).

This rule is in place in the current legacy system and is used to ignore rows (during import/processing of HUD data) where the criteria doesn’t match. The 5 digit FIPS code, then, is sufficient for looking up GMT for any zip code in a given county (generally speaking…there are exceptions such as those described in the next section).

</details>

<details>
  <summary>As a Veteran who lives in a zip code that crosses county boundaries (eg? 83414, 83342, 82930, 82063), I want the app to help me identify which county I actually live in so that my GMT threshold is looked up correctly.</summary>

Based solely on zip-code, there could be more than one possible county. For instance, given the zip code _83342_, the HUD USPS Crosswalk API will return 2 results (for year 2022), containing a unique 5-digit geoid for each: _16031_, and _16071_.

Without additional information, such as their full address, (and a corresponding address->county lookup API), or county, we would be unable to locate the correct GMT.

A different approach might be necessary here: ask the veteran which county they reside in. This dialog could be presented only if the USPS Crosswalk API returned multiple results. In order to display the county options, we could query the HUD IL API (or the API we create).

Creating our own API endpoint which accepts multiple geoid’s may be an ideal solution, since we would have control over the inputs and the result set. This is because the HUD IL API doesn’t accept a 5 digit FIPS code or 5 digit zip code as a parameter for any of its endpoints, and therefore it isn’t currently capable of doing this as it is.


</details>
