### ISSUE TITLE
Public S3 file storage: Transition Impact Assessment 

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#12006]
## Overview
As part of our plan to improve the performance and reliability of our media assets, we are transitioning storage from EFS to S3. Before moving forward with this change, it is important that we fully understand the potential impact on the CMS and its users.

### Explanation
Currently the CMS stores files on a firewalled EFS mount. "Files" in this case refers specifically to images, PDFs, etc. that editors add to their content and are CMS-managed. These files also get called 'media' within the CMS application.

Because the files are stored behind the firewall, they currently need to be copied to a publicly accessible S3 bucket as part of the content release process. This copying process is time-consuming. Other processes that interact with content build - various testing & review instance building for vets-website, local development on content-build repo, etc - also are required to copy images.

We are proposing to shift canonical storage of CMS-managed files to a publicly accessible S3 bucket. This has obvious benefits, mainly in eliminating the need to copy the files. However, there are also some concerns that need to be accounted for with this change.

### Potentially Impacted People
- Veterans
- CMS editors
- CMS engineers
- Front-end engineers interacting with the CMS

### Potentially Impacted Processes
- Link Checking Tool
- Hot-linking PDFs and other content by external parties
- Content Build
- Retiring files from public access
- Recreation of state of the CMS for auditing purposes

## Goal
The goal of this issue is to define a list of impact areas, not to necessarily find a solution or mitigate the impact. Before moving forward with the S3 transition, we need a clearly defined roadmap and impact assessment. 

## Acceptance Criteria

- [ ] Cross-team impact defined and written down
- [ ] Impact to Systems & Services investigated and defined

**Comment by TheBoatyMcBoatFace** [comment]
Documentation and mapping infrastructure created as sub-issue

**Comment by TheBoatyMcBoatFace** [comment]
CMS Support is asking about hosting videos on va.gov. We should clarify how we want to handle those. 

https://dsva.slack.com/archives/CDHBKAL9W/p1671745520663369

**Comment by timcosgrove** [comment]
## Impacted parties
### Veterans
Veterans obviously require files to be available reliably, both for usability of VA.gov and because they sometimes may link directly to a PDF or such. It is imperative that the files remain as readily available as they are today. Things to consider:
* Files should be viewable by direct link.
* Any domain or path changes must be accompanied by redirect patterns.

### CMS editors
CMS editors simply need files to continue to be usable on their CMS content. The one behavior change we are discussing - that file assets would be publicly linkable regardless of whether they are used on a published VA.gov page or not - needs discussion.
* What are current editor expectations re: files being available to the public?
* Is the proposed change viable?
* What change management process and documentation changes would be necessary, if any?

### CMS Product owners
We need to inform and get consent from CMS product owners around these changes, to make sure there aren't contingencies we have not account for. Some changes that need to be discussed and consented to:
* files will potentially be publicly linkable independently of them being used on a given piece of CMS content
* put another way, files will not have an 'unpublished' state that is not accessible to the public (under the current proposal)
* files *can* be deleted
* We currently archive the entire site, including all images, with every content build. This would end.

### CMS engineering for this effort
CMS engineers working on this effort will need to be cognizant of site stability with respect to file assets. Additionally, we need to ensure that we are operating in an approved manner with respect to how we manage and maintain file assets. 
* Do we log file creation and deletion sufficiently to meet our obligation to our ATO?
* The process of moving to this will be a migration rather than an all-at-once change. How will we manage that? How will we deal with files that get added or changed or deleted while we are in the migration process?
* How will we verify that we are in a good state and have not introduced any new defcets?

### CMS engineers
To most CMS engineers, this should not have much substantive impact. Drupal's handling of files via file fields and stream wrapping abstracts the storage location of the file away. The engineer does not need to know that a file is actually stored on a remote S3 bucket in order to use it or even to pull its full URL. Nevertheless, they should be made aware that we are storing files on a public S3 mount rather than on a local file mount, for awareness.
* What parts of CMS engineering might be impacted, if any? 

### Front-end engineers interacting with the CMS
Again, the should not have much impact for people working day-to-day in Content Build _on templates_. In terms of interacting with the data that is ultimately provided to the templating system by GraphQL/Content Build, a file is accessed at a URL which is provided with the file object. `field_portrait.url` will still work; it will just point to a different location underlyingly. Front-end engineers working on templates should not need to be concerned about this.

We should look out in the content-build templates for any code that makes reference to specific file locations (this is separate from the build process itself; see below).
* Are all file references in template code free of direct reference to specific domains? 

### Content build engineering
Content build will have to change substantially. There are several processes that interact with file assets during the build process. Files are identified and then later downloaded on every run. There are processes that do rewriting on domains that will need to be handled. The downloading of assets itself will need to be removed, *for assets Drupal maintains*. We must confirm that any files not currently managed via Drupal file fields are accounted for. 
* Does the content build 'Drupal asset' process handle any files that are not managed via Drupal file fields?
* Is actual file download necessary in any case? Can it be enabled conditionally?
* Will the removal of the processes that currently handle file assets have any unintended side-effects?
* How will we determine that we have maintained site state before and after transition? How will we know if we have inadvertently created defects?

**Comment by timcosgrove** [comment]
## Potentially Impacted Processes
### Link Checking Tool
Currently the link checking tool checks that any local URL resolves to a file that the build process has built or knows about. This includes file assets. Changing the file assets from local URLs to a remote domain may actually require no changes, since currently the link tool does not check URLs it considers remote. However, we need to ensure this works as expected when the file locations are shifted.

* Does shifting file location to a remote location require any changes to the link checking process?

### Direct asset links in content
In theory, files should always be referenced by means which Drupal mediates. Files would be considered something like `file://sites/default/files/2022-12/some-file.jpg`, or `entity:media/3849`, and Drupal is responsible for converting that to a full URL.

However, it is possible that references to a full url could be entered into rich text in a piece of content, referencing `/sites/default/files/2022-12/some-file.jpg` directly. We need to ensure that these are caught and handled. The broken link checker should help here, actually, as it *would* treat this scenario as a broken link and raise an issue.

* Are there references to file URLs anywhere in the CMS that are not managed by Drupal as entity URLs? How can we convert these?

### Hot-linking PDFs and other content by external parties
There are potentially quite a number of instances where people link directly to file asset content, particularly PDFs. These will need to continue to resolve after the change. This should be taken care of by redirects. These redirects should work for both the s3 URL and the www.va.gov/ variant of the URL. 

* Are there any issues with redirecting references within `sites/default/files` to a different domain?

Content Build

### Retiring files from public access
Currently, we can retire files from public access by no longer using them on a piece of content. At the same time, we don't have a clear way to know that a given file is removed from all content across the site.

Under the proposed changes, content would *always* be public. If it needs to be removed, it can be removed at the the media file level. 
* As discussed under CMS Product Owner above: will it be acceptable for public access to a file to no longer be tied to its use in content?


### Recreation of state of the CMS for auditing purposes
As defined by our current ATO, we are not required to be able to reproduce the site for any given point of time in its entirety. Currently we are able to do so, but it is not a requirement.

Under the proposed changes, we could still reproduce the state of the site at a given time through a combination of pulling down an HTML archive for a given time and using S3 versioning to retrieve earlier state of the S3 bucket. 
* Are there any product level issues in this shift in how we manage historical file state?
