### ISSUE TITLE
Broken Link Report Failing to Update

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#12040]
## Describe the defect
The [Broken Link Check JSON Report](https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/broken-link-reports/vagovprod-broken-links.json) has stopped updating. The last update was Friday, Dec. 16, 2022.

## AC / Expected behavior
The Broken Link Report should continuously update to reflect all broken links.

## Screenshots

![image (4).png](https://images.zenhubusercontent.com/63729773c8d3f81258e641b6/0c102aea-057d-4200-b5bb-b1aef2f92800)
_Screenshot: @swirtSJW_ 

 ## Additional context
- [Slack Conversation](https://dsva.slack.com/archives/C02HX4AQZ33/p1671555435083309)
- @stefaniefgray brought this up in the Sitewide CMS SCRUM on Dec. 20, 2022

## Acceptance Criteria

- [x] Cause of update failure determined
- [x] Broken Link Report actively updating
- [x] Cause of failure documented on this issue
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12040#issuecomment-1360733572

**Comment by timcosgrove** [comment]
Broken links have not been reported since that time in general; see https://dsva.slack.com/archives/C030F5WV2TF/p1671221098375109

**Comment by timcosgrove** [comment]
Almost certainly related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11948

**Comment by timcosgrove** [comment]
Code is merged; we will not be able to verify until next content release after Daily Production Release, approximately 4pm ET Wednesday 12/21/2022

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12053 is opened to update the broken link checking script.

**Comment by timcosgrove** [comment]
Cause of failure:
The ticket work which resulted in this defect was #11948, which was a ticket to implement recent Github Actions syntax changes for the workflows we use: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Most of our changes were in workflow files and function as expected. However, we also use node scripts to run certain steps in our workflows. In particular, the failing code is a node script which outputs information back to the workflow.

The form of the change normally is from first line to second:
```
echo ::set-output name=FOO::BAR
echo FOO=BAR >> $GITHUB_OUTPUT
```

Within the node script, the changes looked like this:
https://github.com/department-of-veterans-affairs/content-build/pull/1402/files#diff-7ec34fdf7d43b26b9dae523fe661dd2ecb8155b0aba9391b3f44b5724b55bb43

I made the (apparently bad) assumption that `console.log` would act as `echo` in both cases as far as GHA was concerned, since it was working for the first case. It's possible there was a different error also. 

The changes in these Node files are reverted back to their original form. #12053 is opened to do the work properly.
