### ISSUE TITLE
Refine site notification message wording

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1208]
AC
- [x]  Artifact/ mockup with text for all 3 alert messages
  - [x] deployment warning
  - [x] deployment in progress
  - [x] deployment complete

**Artifacts**
https://app.mural.co/t/vagov6717/m/vagov6717/1584658469272/3df1291f058897296948d3c3d1e21a210ee8536d

**Next steps**
- Get feedback from devs + design pod
- Explore whether we should AB test a few solutions with users
- Implement in Jenkins

**Comment by rachel-kauff** [comment]
Notes from call w/ Swirt today"

- Two different pieces of this work: 
  - Drupal contrib module that shows alerts prompted by commands from Jenkins
  - The content of the alert messages themselves, which comes from Jenkins commands
- 3 stages of deployment notifications
   1. One hour before: notification that the site will be going down due to a scheduled deployment
   - What editors need to know: the site will be down soon and they won't be able to make changes or use it
   - What editors need to do: plan to save their work either before or after the deployment window
   2. When the deployment starts: notification that the site is doing down
   - What editors need to know: the CMS is now unavailable
   - What editors need to do: avoid navigating away from the page they're working on, avoid making changes or edits otherwise their changes won't be saved
3. After the deployment window: The site is now up
   - What editors need to know: it is now safe to make changes and navigate away from the page
   - What editors need to do: proceed with what they're doing
- Some devops considerations:
  - There is a 20 second delay between Jenkins running the command and the alert appearing in the CMS
  - Deployment times aren't exact. We aim for 3:30, but it doesn't happen totally consistently, so we want to be loose with the language that specifies when things will happen
  - Sometimes deployments are triggered manually rather than being automatically scheduled
- Usability considerations:
  - Is an hour too much warning for editors?
  - During the deployment window, the site goes into maintenance mode, so in addition to not being able to save edits editors won't be able to view content during this time
  - If users navigate to other pages, those will also be covered by the red full screen alert
  - it's important for people to know that the CMS is temporarily inaccessible, but NOT BROKEN.

**Comment by rachel-kauff** [comment]
![image (1)](https://user-images.githubusercontent.com/41017988/76907376-4b252d00-6863-11ea-8119-c360769f72b5.png)
![image (2)](https://user-images.githubusercontent.com/41017988/76907380-4ceef080-6863-11ea-90b1-86163c423e52.png)
![image (3)](https://user-images.githubusercontent.com/41017988/76907381-4d878700-6863-11ea-840b-3c1b848f807e.png)
![image (4)](https://user-images.githubusercontent.com/41017988/76907384-4e201d80-6863-11ea-8d39-15cf0e0dda8b.png)

**Comment by rachel-kauff** [comment]
@swirtSJW I did an initial draft (see the mural link in the artifacts section of this ticket) and added some next steps for this work. I think it's important to get some more feedback on what I drafted, but if we want to call it an MVP, I'm ok with doing that in the next iteration. You'll notice I drafted two different messages for the initial notification. If possible, I think we should utilize two different messages depending on whether it's a regular or impromptu deploy. If that's not possible, the message that is more general (doesn't specify a time) will work.

**Comment by swirtSJW** [comment]
@rachel-kauff I like all the suggestions.   I will work with Elijah to see if our system can handle warnings at 15 minutes instead of an hour.

I also like the wording of "System update" so that "deployment" does not get confused with a front end deployment ... which we also may use similar live notifications.

**Comment by swirtSJW** [comment]
the messaging on the 15 minutes though might be odd though since the actual timing would depend on when they observed the message.   I'll see if Elijah can have it calculate the time and insert it.   Otherwise someone might turn back to their screen after talking to someone  for a while and see an alert that says 15 minutes or less, and 30 seconds later the site goes into full lockdown for the update.

**Comment by rachel-kauff** [comment]
@swirtSJW Thank you for these thoughts. Calculating the time would be ideal, but if that's too expensive or not possible, I'll revisit this today and see if I can revise accordingly.
