### ISSUE TITLE
Inconsistent breadcrumb capitalization on Lovell

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12107]
## Describe the defect
On some of the Lovell Federal pages the breadcrumb for Lovell does not have the proper capitalization that the rest of the VAMC does.  

**Lovell VA:**
It should say "Lovell Federal VA health care" but instead it says "Lovell federal va health care", with Federal and VA being incorrectly lowercase.
- [Policies page](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/policies/)
- [Events detail pages](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/events/49920/) 

**Lovell TRICARE:**
It should say "Lovell Federal TRICARE health care" but instead it says "Lovell federal tricare health care", with Federal and tricare being incorrectly lowercase.
- - [Events detail pages](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/events/49922/) 

## AC / Expected behavior

- [ ] ID issue
- [ ] Discuss path forward
-------------------------------------------------------------
- [ ] Correct the capitalization of the breadcrumb on Lovell VA
- [ ] Correct the capitalization of the breadcrumb on Lovell TRICARE

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/209344949-9dd55051-e6f4-42f5-89a1-3bb697374582.png)

![image](https://user-images.githubusercontent.com/106678594/209345918-049123d8-ff8c-40f2-be55-68e8f7120b04.png)

**Comment by Dottisea** [comment]
This may be resolved with the work of the name change

**Comment by ryguyk** [comment]
## This is not a problem that is specific to Lovell.

### Ex:
https://www.va.gov/minneapolis-health-care/events/48210/
![image](https://user-images.githubusercontent.com/6863534/213551409-0689f781-2de6-45ba-99d3-49b6c4d82db5.png)

**Should be like Pittsburgh**
https://www.va.gov/pittsburgh-health-care/events/52605/
![image](https://user-images.githubusercontent.com/6863534/213551769-55eb5453-c118-4325-bcdd-67e5f94c4355.png)

In fact, **ALL** event detail pages will have this problem _except_ events at Pittsburgh VA. This is due to seemingly very old code that specifically checks for Pittsburgh VA and handles appropriately. I imagine this is a remnant of the time when Pittsburgh was the first VAMC to be modernized.

The problematic code is [here](https://github.com/department-of-veterans-affairs/content-build/blob/8aa1bf102f4fa621588730fef9e33cc042d8b915/src/site/stages/build/drupal/page.js#L292). All event detail nodes have their breadcrumbs generated from the URL, even if the breadcrumb is already present. 

There is [code added by @maxx1128](https://github.com/department-of-veterans-affairs/content-build/blob/7a56d1bce5bd35e5bdb7304346b30cbf0b78cc08/src/site/stages/build/drupal/page.js#L355) that appears to be related. This code includes the very necessary step of checking whether a breadcrumb object already exists before attempting to generate one. The problem, though, is that this code does not block the previously mentioned code from later replacing the breadcrumb. Both blocks of code are executed on event nodes.

The conditional check in Max's code should be the appropriate pattern. It is likely the case that his code negates the need for any specific processing for event nodes (i.e. the problematic line of code can likely just be removed). However, it should be noted that his code adds a breadcrumb object to _all_ pages that don't have one. This was not the case prior to his addition, and that is why the `event` node handling was adding it explicitly.

**Comment by davidmpickett** [comment]
I updated the title, labels, and epic to reflect that this is not a Lovell specific issue. Needs a conversation with Sitewide Content / Design System

**Comment by ryguyk** [comment]
### Re: Policies page breadcrumbs

We see an issue with the [VA Policies page:](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/policies/)
![image](https://user-images.githubusercontent.com/6863534/213791361-1b3301c8-6cd1-411d-a8c4-298dad2093bf.png)


We do not see an issue with the [Tricare Policies page:](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/policies/)
![image](https://user-images.githubusercontent.com/6863534/213791492-8e5b7bb8-66f8-4345-82cf-3c30ccb7b87c.png)

This is due to the fact that, currently, these two pages are different content types. The VA page is a hardened VAMC Systems Policies Page while the Tricare page is a catch-all VAMC Detail Page. The former comes over without a breadcrumb, so it is generated. The latter comes with a breadcrumb, so it is retained.

**THIS IS A CONTENT ISSUE**
This is likely not how things are supposed to be. Noting here for good measure.

**Comment by ryguyk** [comment]
Since this is a bigger issue than just Lovell, closing this ticket in favor of a [more general ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12326).

**Comment by CherylEvans** [comment]
This ticket was recreated in the va.gov-team repo Ticket # [64850](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/64850)
