### ISSUE TITLE
Create Outdated Content Runbook

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12133]
## Description

After research from #9551 is completed, the Sitewide CMS team should create change management artifacts in the form of a runbook and plan for rolling out outdated content notifications.

This [mural](https://app.mural.co/t/vagov6717/m/vagov6717/1665021416634/0b8036c01e2223d76018b8ca79a832f181e13187?sender=ud7d3055567694e54f0133356) on outdated content may help us create the runbook. 

## Acceptance Criteria
- [x] Create checklist for editors on how to properly complete a revision log and review pages for 6102 compliance
- [x] Create runbook including:  KBs and other artifacts as needed for a rollout 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [X] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [X] `⭐️ User support`

**Comment by EWashb** [comment]
to do approximately sprint 77

**Comment by EWashb** [comment]
will work with @TroyA6 and @stefaniefgray  as needed

**Comment by EWashb** [comment]
Still on tap for Sprint 77

**Comment by EWashb** [comment]
I will work with Blake on this one

**Comment by EWashb** [comment]
What it means to be 6102 compliant:

- [ ] check links for accuracy and ensure they aren't broken
- [ ] Confirm heading order is correct
- [ ] Check content style guide for plain language, etc.
- [ ] Is the whole of the content still accurate?

Once these items are confirmed ok, complete the revision log and notate what changes were made or if everything was checked and no changes are needed. Then publish

**Comment by EWashb** [comment]
Also @BlakeOrgan feel free to add your own thoughts on what it means to be 6102 complaint

**Comment by EWashb** [comment]
[WIP Runbook](https://docs.google.com/document/d/13lwV2fyKhNWrkM5yS3jKOxqtSNFQOlt0oYKOl-6T-cU/edit?usp=sharing)

**Comment by BlakeOrgan** [comment]
Copying over our notes from the [WIP Runbook](https://docs.google.com/document/d/13lwV2fyKhNWrkM5yS3jKOxqtSNFQOlt0oYKOl-6T-cU/edit#) that Erika and I were working on since this is about wrapped up. @EWashb, can you look over this and make any corrections before we close this ticket out?

# Runbook for CMS Notifications for VA Directive 6102 Compliance

**Anticipated launch date: April 2023**



1. **Sprint 77**- Create Outdated Content Change Management Artifact(s) and Plan (this doc is part of this ticket): [https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12133](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12133)
    - Share checklist with VHA Digital Media on how editors become compliant (minimum requirements to becoming compliant plus nice to haves)
2. **Sprint 78**- Make updates to email prototype based on feedback: [https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12391](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12391) 
        - Decide where to point editors to in the email- to the report with access to only the sections they have access to 
            - Keep title, content type, section (only filter what they have access to), and filter by all outdated and most overdue
                - Make sure to restrict the section to only what a particular editor has access to
        - Blake to create dev ticket to implement this email once design is updated. (see step 5)
3. **Sprint 78**- Require revision logs for VAMCs (Steve)
    - Confirm that ALL revisions logs are out of scope. Slacked Dave about this already:  [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1675975966733349)
    - KB update for: [https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10430](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10430) 
        - Share updated KB with VHA Digital Media
4. **Sprint 78**- Open outdated content report to more editors (work completed- currently in DO NOT MERGE)
5. **Sprint 79**- Dev email creation (Blake to create ticket for Edmund)
    - Confirm the priority of adding tracking information (possibly not MVP but refining on 2/13/23)
        - First: Add support for open rate tracking to email notifications: [https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9713](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9713)
        - Second:  Create template runbook for adding tracking to notification emails: [https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9785](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9785)
6. Smoke test email distribution

**Change Management Items to be shared with stakeholders:**
1. Basic write-up of “what it means to be compliant” (must have vs. nice to have)
2. Create CMS escalation plan for non-compliance
3. KB article
4. Sample revision log messages to send to stakeholders
5. Inform stakeholders that we need to have a plan for removing people from the sections

**MUST HAVE in order to be 6102 compliant**
* Log in (They will most likely be directed to log in from the email notification that we'll be sending)
* Review content on the page for accuracy, edit or archive if necessary.
* Add the required revision log of what you did. Notate what changes were made or if everything was checked and no changes are needed.
* Publish

**NICE TO HAVE. (But not required to be 6102 compliant)**
 * Check links for accuracy and ensure they aren't broken
 * Check PDF links
 * Confirm heading order is correct
 * Check content style guide for plain language, etc.


**Example of a good revision log.**
* This content has been reviewed for accuracy and no updates were needed.
* Updated [insert updates here] because [insert reason here].
* Removed [insert updates here] because [insert reason here].
* Referred to [insert person here] to ensure the information listed here was still accurate.
    * This content has been reviewed for accuracy and no updates were needed.
    * Updated [insert updates here] because [insert reason here].
    * Removed [insert updates here] because [insert reason here].

**Example of a bad revision log:**
(Revision logs should be clear and specify what was changed and why.)
* Looks good!
* Checked.
* No problems.
* Updated the content.

**Thoughts on potential next steps:**
* Choose the amount of content that editors will be required to update each week for each facility type based on research from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12381
* Update email prototype. Have separate mockups for VAMC and Vet Center Emails.
* Build out a spreadsheet to figure out the downward trajectory for each facility over time.
* Do a monthly report to figure out which facilities are on track and which are not.
    * Edward might need to add a new count report function so that this information doesn't have to collected manually each month.
* Have an escalation plan in place so that points of contact (VHA Digital Media for VAMCs and Vet Center Directors for Vet Centers) can be made aware if editors are off track.

**Comment by EWashb** [comment]
This all looks good. Will chat with @davidconlon on MVP vs. Non-MVP items on this list and update our [planning mural](https://app.mural.co/t/vagov6717/m/vagov6717/1671567072116/59185a2c98e953b2dd387ccd939967ecf263fde4?sender=ud7d3055567694e54f0133356) if next steps/timelines change.
