### ISSUE TITLE
Homepage modal: increase % of users who will see the modal from 25% to 50%

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12160]
**BLOCKED until DaveC confirms** -- greenlight from Dave Mon 3/13

The homepage modal is currently set to show to 25% of users for launch.  We want to increment this to 50%.

Local storage var `show-homepage-soft-launch-modal` controls how many users will see the homepage modal on page load: 
https://github.com/department-of-veterans-affairs/vets-website/pull/23009/files#diff-bd506acc2fab742c1cca334e5ac7d1636e3887b8c96ae0f167ae72aaa023a070R18

## Acceptance Criteria

- [ ] Positive: Modal should appear for user assigned local storage var `show-homepage-soft-launch-modal` <=50
- [ ] Negative: modal should not appear for `show-homepage-soft-launch-modal` >50

**Comment by wesrowe** [comment]
Update from Dave sync 3/6:
- Targeting March 14 for this expansion to 50%
- Inputs to that decision:
  - Temperature check on how funnels are looking for New-HP vs Old-HP segments in GA, as well as how New-HP funnels compare to Cutover decision criteria
  - Customer satisfaction feedback (Medallia) for 2/21-3/6

**Comment by wesrowe** [comment]
### Google Analytics

As reported in Team of Teams, funnels are performing well – visitors who visit the New HP are more likely to subsequently complete key funnel tasks than those who don't.
- log in
- send a secure message
- download benefit letter
- apply for education benefits

Benefit hubs links on the homepage are seeing a significant rise in clicks. This was identified pre-launch as a positive metric and might be where traffic is shifting since the tasks above no longer have links in the homepage body.

### Medallia and customer satisfaction

see #12790

**Comment by jilladams** [comment]
Dave confirmed in sync with me/Wes today that we can make this change tomorrow.

**Comment by jilladams** [comment]
Verified on Staging: 
* local storage var = 13 = modal shows once per session
* var = 43 = modal shows once per session
* var = 75 = modal does not show
