### ISSUE TITLE
Discovery: Drupal translations editorial permissions

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12235]
## Description

As we explore Drupal OOTB translation options, it is essential to understand how the permissions/access will work for our editors. This will help us determine the level of change management and the approach for the editorial experience. 

What we would like to know:

- Can translations be on for just certain users?
- Will we need an additional user type for translation management?

## Acceptance Criteria

- [x] document the types of user permissions available in our CMS for Drupal translations OOTB in this ticket
  - [x]  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12235#issuecomment-1404117085
- [x] Share findings with PM

**Comment by timcosgrove** [comment]
The short answer is:
* viewing translations should be on for everyone
* editing translations should be restricted to certain roles. We can discuss best strategies, but, it should be available to some privileged role beyond administrator so that edits can be made when necessary without needing to reach out to CMS admins.
* managing translations should have its own role. There are permissions around managing the translation process that should be assigned in a granular way, rather than loaded onto an existing role.

**Comment by EWashb** [comment]
@davidconlon Tim's feedback here is interesting on the role of translation permissions. I wanted to loop you in.

**Comment by timcosgrove** [comment]
To be clearer, 'viewing translations' is just, the user is able to see translated content. There is also a 'view published content' permission, which should be granted to all users, for just seeing any Drupal content. Denying 'view translations' could also have unintended consequences for Content Build, for referencing other nodes from another node, etc.

In terms of what types of permissions, we should distinguish between Drupal translation and Translation Management (TMGMT), which is an add-on functionality. 

TMGMT is how we would create XLIFF files for translating a given set of content, connecting to the Translation Management System if one exists (I understand we're planning to do manual email of files, which I have thoughts about), and then reviewing the incoming translations on XLIFF files prior to accepting them into the system. Translation management should be its own role, though a reminder that a given user can be assigned multiple roles, so this is not really a "user type". Nevertheless, translation management is a reasonably complex task that should be restricted to a few people who are trained in how to use the system. 

'Translation editing' on the other hand is just that - taking existing translations and making modifications to them. We can also distinguish between creating new translations and editing existing ones, so for example we can require that all translations be initially created  by TMGMT processes, but then small modifications made later. 

I recommend Translation editing permission not be restricted to admins and the translation management role, because there will be cases where an editor might just need to correct a small detail of say a Spanish translation and shouldn't have to go through a Support Request cycle for that. OTOH, I also understand exposing that to the average editor might be both dangerous and confusing. 

These are things we can and will need to discuss. There are many UX, data integrity, and operational flow considerations. Nothing crazy, but things we'll want to discuss and make intentional decisions about.

**Comment by timcosgrove** [comment]
Translation management perms:
* Administer TMGMT itself - should only be admins
* Create, delete, submit translation "jobs" - should be granted to a Translation Manager role
* Accept translation jobs - we should discuss. This role is able to review incoming translations and check them, and turn them into translated content in Drupal. It can be separated from the job management, and we might assign it to a language expert, if we have that person. Currently it does not separate out permissions by target language, but we can add that without too much trouble if needed.

Translation perms:
* Administer translation - should be admin only
* Create new translation - should only be admins and translation managers
* Edit translations - we should discuss. There are plusses and minuses to granting this to 'rank-and-file' editors.
* View translations - this should be granted to everyone.
* Delete translations - should be admin only, and used very sparingly, same as with regular content
* Translate any entity - admin & translation managers only
* Translate editable entities - basically, if a user can edit content, they can also edit its translations. This deserves more investigation to see how it's used. But, for example, this is how we would restrict people to only editing translations on content they have permission to edit (say due to Section assignment)

**Comment by EWashb** [comment]
This was completed as part of #12186
