### ISSUE TITLE
Back End: Refactor to complete name change

### ISSUE THREAD

**Issue by Dottisea** [department-of-veterans-affairs/va.gov-cms#12234]
See: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12092

As a Back End Developer I want to know where in the code the current name of Lovell exists, so that I can make the name change, and I want to make that change.

# [va.gov-cms](http://va.gov-cms/) repo

The strings "Lovell Federal VA health care" and "Lovell Federal TRICARE health care" exist in the following:
## Drupal CMS
docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js:
docroot/modules/custom/va_gov_lovell/src/LovellOps.php:
docroot/modules/custom/va_gov_lovell/src/LovellEventSubscriber.php:

## Cypress Testing code
tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature:

## Acceptance Criteria
Content
- [x] VAMC System names have been updated (TWO systems).

Code
- [x] Audit has been completed to discover where name change needs to be made.
    - [x] Breadcrumbs
    - [x] Menus
    - [x] Content within nodes
- [x] Cypress tests have been created, updated, or determined to be not needed.
- [x] Enumerate the _ways_ the Lovell names appear to editors, as described this [cms-12234 Google Sheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=595146873).
- [x] Code has been updated with the name change.
- [x] Confirm that the name appears correctly in all _ways_ enumerated above.

### Non-code work to complete this issue
- [x] Update the TRICARE and VA systems
  - [x]  New names
  - [ ] New menu links
  - [x] New URL aliases
 - [x] Update all Lovell content through bulk edit
   - [x] Resave content
   - [x] Update URL alias

**Comment by omahane** [comment]
I will work with @ryguyk to make sure the JSON code is updated as necessary.

**Comment by omahane** [comment]
@Dottisea I'm looking for some advice on this one. 
On the VA side the facility is called
- Captain James A. Lovell Federal Health Care Center

Currently, on the TRICARE side, it's called:
- Captain James A. Lovell Federal TRICARE Health Care Center

This doesn't fit the naming convention, but I also don't know what it _should_ be called.

![Screen Shot 2023-01-18 at 7 42 40 PM](https://user-images.githubusercontent.com/766573/213336106-509b7c35-6ea6-4372-be3c-e402d1caf37b.png)

**Comment by Dottisea** [comment]
@omahane - here is what we have for the name change:
Systems Level
Lovell Federal health care - VA
Lovell Federal health care - Tricare

H1 Title & the URL will need to be updated.

For the actions we are injecting VA/Tricare into the names.

Facility level
Medical Center Facility level, to not to have Tricare or VA on it.
Official name of the facility is the name of the facility.
Breadcrumbs should also have VA/Tricare at the end.

At no time should we be changing the Facility name coming from VAST.

If it is a combined facility, unless it is one facility absorbing another, then we should not re-use the name of a facility.

**Comment by omahane** [comment]
@swirtSJW 
In my local dev environment, after making the change to the system names, menu links and urls, I ran into an issue with the breadcrumbs, but only on the facility and system heath services:
https://va-gov-cms.ddev.site/lovell-federal-health-care-tricare/health-services/psychiatry-at-lovell-federal-health-care-tricare
<img width="1056" alt="Screen Shot 2023-01-19 at 10 43 14 AM" src="https://user-images.githubusercontent.com/766573/213504900-ec05f61b-1910-481e-a7a1-5dbae06844a5.png">
https://va-gov-cms.ddev.site/lovell-federal-health-care-va/locations/kenosha-va-clinic/psychiatry
<img width="1074" alt="Screen Shot 2023-01-19 at 10 43 47 AM" src="https://user-images.githubusercontent.com/766573/213505020-97b5d2a2-f1fe-4c3c-8679-c96eb6511e5e.png">

I'm pretty sure the reason is the method `updateLovellBreadcrumbs` in `va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php`

```
if ($section_id === LovellOps::TRICARE_ID) {
        $breadcrumb = $this->swapAforB('VA', 'TRICARE', $breadcrumb);
        $breadcrumb = $this->swapAforB('BOTH', 'TRICARE', $breadcrumb);
      }
else {
        $breadcrumb = $this->swapAforB('BOTH', 'VA', $breadcrumb);
      }
```

and the `swapAforB` method, too:
```
protected function swapAforB($a, $b, array $breadcrumb) {
    $a_path = constant('\Drupal\va_gov_lovell\LovellOps::' . "{$a}_PATH");
    $a_name = constant('\Drupal\va_gov_lovell\LovellOps::' . "{$a}_NAME");

    $b_path = constant('\Drupal\va_gov_lovell\LovellOps::' . "{$b}_PATH");
    $b_name = constant('\Drupal\va_gov_lovell\LovellOps::' . "{$b}_NAME");
    foreach ($breadcrumb as $key => $link) {
      if (str_contains($link['url'], $a_path)) {
        $breadcrumb[$key]['url'] = str_replace($a_path, $b_path, $link['url']);
        if (is_string($link['text'])) {
          $breadcrumb[$key]['text'] = str_replace($a_name, $b_name, $link['text']);
        }
      }
    }
    return $breadcrumb;
  }
```

Would you have a little time to walk me through what this code is doing?

**Comment by omahane** [comment]
<img width="1840" alt="Screen Shot 2023-01-20 at 11 58 56 AM" src="https://user-images.githubusercontent.com/766573/213779839-5b8bb94a-34d3-403b-8022-3cf4a5a173bf.png">
@swirtSJW (cc: @Dottisea ): Do you know how this "Services and Locations" menu should be? Title Case or ALL CAPS?

**Comment by omahane** [comment]
> <img alt="Screen Shot 2023-01-20 at 11 58 56 AM" width="1840" src="https://user-images.githubusercontent.com/766573/213779839-5b8bb94a-34d3-403b-8022-3cf4a5a173bf.png">
> 
> @swirtSJW (cc: @Dottisea ): Do you know how this "Services and Locations" menu should be? Title Case or ALL CAPS?

After talking to @swirtSJW and @ryguyk, we determined that "Services and Locations" appears in ALL CAPS on the front end should appear so on the Drupal side, too.

**Comment by omahane** [comment]
I had a chance to talk with @swirtSJW and @ryguyk about the Lovell inconsistencies that I was tracking in my Google spreadsheet. It turns out the confusion around why some pages were in "Lovell Federal heath care system" section but had the VA-related URL were correct. The ones that didn't had not been opened and resaved since @JayDarnell did the menu work. We need to do that with all content in the "Lovell Federal health care" section. This now captured in #12334 .

**Comment by JayDarnell** [comment]
I changed SERVICES AND LOCATIONS to all caps on production today.

**Comment by omahane** [comment]
The code has been deployed and the content changes have been made.
