### ISSUE TITLE
Discovery: downtime alerts (existing feature)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12339]
## Description

As a VAgov stakeholder, I want to know how to use PagerDuty to trigger downtime alerts within the apps that are impacted by service interruption so that I can provide contextual, targeted information to Veterans. 

Note: Chante L-S is the OCTODE PO for this area.

### Background

What we think we know (via Dave C):
- Downtime alerts are react-driven
- Integration with PagerDuty enables a PagerDuty action to trigger the alert in real time
- When DS Logon had an outage a couple months ago, people generally weren't aware of the downtime alerts system and instead discussed (and decided against) blunter tools like maintenance banners.

### Resources
- Documentation in Public Websites product folder that may be wrong or misnamed: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/README.md#downtime-messaging 
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/scheduled-downtime-process.md
- [Platform documentation of Downtime Messaging](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications)

## Acceptance Criteria
- [ ] Document apps/screens on VAgov that have the capability to display downtime alerts
- [ ] What are the downtime alerts possible in each of those apps/screens?
- [ ] Document discrepancies (if any) between locations/messages above and what the documentation would lead to you expect.  Does documentation talk about an alert that isn’t used anywhere? 
- [ ] Determine whether the flipper `va_global_downtime_notification` (or similar) relates to this feature or something different, and update the Flipper retirement spreadsheet
- [ ] Notify Wes when ready to go over findings with Mike Chelen

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
@jilladams, per today's mid-sprint discussion of flippers, I added an AC about checking the flipper that sounds like it relates to downtime alerts. Can you add a link to some appropriate ticket or spreadsheet?

**Comment by jilladams** [comment]
Sure: Ticket to remove `va_global_downtime_notification` flipper = #11864

In the SPIKE about removing flippers, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10342 , we identified that the downtime flipper wasn't referenced anywhere else in code beyond creating the flipper itself, so that makes it a candidate to be removed as far as we know. 

Google sheet of notes across all flippers: https://docs.google.com/spreadsheets/d/1yQb5oDshNj7y0nvtF3PaZ9OLhtTuZ2aO8t4_n51YBWU/edit#gid=237722104&fvid=1552255965, this flipper is line 34

**Comment by jilladams** [comment]
Deprioritized/booted from sprint in favor of spanish toggles.

**Comment by jilladams** [comment]
Temp blocked: requires PagerDuty access, which requires VA email access, which Josh is temp blocked out of. Based on current capacity, can't pull into Sprint 80 for Josh til email access is restored: so we may be able to pull in for Bryan if/when Bryan returns.

**Comment by dsasser** [comment]
@jilladams @wesrowe where can I find the "Flipper retirement spreadsheet"?

**Comment by jilladams** [comment]
https://docs.google.com/spreadsheets/u/1/d/1yQb5oDshNj7y0nvtF3PaZ9OLhtTuZ2aO8t4_n51YBWU/edit#gid=237722104&fvid=1552255965

**Comment by dsasser** [comment]
- [x] Document apps/screens on VAgov that have the capability to display downtime alerts
[VACMS-12339 Downtime Discovery.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11408386/VACMS-12339.Downtime.Discovery.xlsx)

- [x] What are the downtime alerts possible in each of those apps/screens?
Downtime alerts appear in different ways depending on the type of downtime (current vs upcoming) occurring, and how they are configured. An application wrapped in the Downtime Notification React component typically responds in one of three ways:

1. Rendering the application as normal if the maintenance window does not start for upwards of an hour.

2. Displaying a dismissible modal informing the user of upcoming downtime and rendering the application as usual if the maintenance window starts within the hour.

![Screenshot 2023-05-05 at 9 48 19 AM](https://user-images.githubusercontent.com/221539/236519075-58f4ea48-dfd8-46db-ae66-f050572979a1.png)


3. Rendering an alert banner informing the user of active downtime instead of rendering the application if the maintenance window has already started.

![Screenshot 2023-05-05 at 9 52 06 AM](https://user-images.githubusercontent.com/221539/236519168-7e895fec-8363-46ba-a4a6-a9075a470126.png)

Additionally, the downtime message itself can be customized to display any component in the message area of the downtime component. However, it is recommended to use the default downtime message for consistency across va.gov.

- [x] Document discrepancies (if any) between locations/messages above and what the documentation would lead to you expect. Does documentation talk about an alert that isn’t used anywhere?

Platform's downtime documentation aligns with what I'm seeing in the codebase.

- [x] Determine whether the flipper va_global_downtime_notification (or similar) relates to this feature or something different, and update the Flipper retirement spreadsheet

The va_global_downtime_notification flipper was [removed](https://github.com/department-of-veterans-affairs/vets-website/pull/23345) from vets-api and vets-website, so it is is no longer providing functionality. Interestingly, the flipper is still showing as an active feature flag in the [flipper ui](https://api.va.gov/flipper/features).  

 - [ ] Notify Wes when ready to go over findings with Mike Chelen

**Comment by wesrowe** [comment]
@dsasser, thanks. I'll close the ticket and add the "discuss with Mike Chelen" topic to the Dave sync agenda for next time we talk.

I'm struck by the fact that only two unauthenticated apps have alerts (that I noticed): Find-a-form and Facility locator.

**Comment by jilladams** [comment]
Noting: there are 2 competing docs here from Platform perspective: 
1. The scrollhelp site that Daniel references in his findings: https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications. This process assumes, as Daniel noted, using standard content, with the capacity for custom content if needed.
2. Older 2020 Github documentation that focuses on the content workflow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/scheduled-downtime-process.md. 

I've started a couple related slack threads: 
1. With Content / IA re: updating their points of contact in the Github doc, since it still exists: https://dsva.slack.com/archives/C01K37HRUAH/p1683563657460669
2. With Platform re: the competing docs, and asking them to work out if the Github doc should be updated with modern points of contact, or archived: https://dsva.slack.com/archives/CBU0KDSB1/p1683566722618579

I think the relevant point for us is making sure that _if_ we need to post a downtime notification, PW is clear on whether the standard content is fine, or we need to follow the content workflow. And if we need to follow the content workflow, making sure Content/IA has their info up to date for how that workflow runs. I've added this as a note for the next sync Wes & I have with Dave.
