### ISSUE TITLE
Discovery: Siteimprove technical and security feasibility

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12364]
## Background

Once we receive the authorization document from VHA Digital Media, we will need to investigate the feasibility of using Siteimprove within the CMS. There may be considerations around the ESECC process which might require us to be approved for internal connections/access behind the firewall.  From the CMS perspective, it is important that we understand the blockers or other dependencies around compliance and what that would mean for our team and the stakeholders. 

## Acceptance Criteria

- [x] Locate contact at the Digital Transformation Center
- [x] DevOps/DM coordinates with DTC to determine what "VA Data includes"
- [x] Findings are shared with PM/PO via notes in ticket

**Comment by EWashb** [comment]
thoughts: What counts as "VA data"? The authorization only says about "No VA data" so what is that?

**Comment by EWashb** [comment]
Emailed JHL for more context around what constitutes "No VA Data".

**Comment by EWashb** [comment]
Per a follow-up email with JHL on 2/3/23-

 https://oit.va.gov/marketplace/user-guide/definitions, no VA data is defined as: 

No VA DATA: Does not exchange information with any VA systems and therefore does not require a VA authority to operate (ATO); these products only require a Privacy Threshold Assessment (PTA) to be completed.

JHL has recommended to reach out to the Digital Transformation Center staff to help with what those definitions mean. There is also a "How We Do It" aka playbook at https://www.oit.va.gov/marketplace/playbook that may be of use as well

**Comment by EWashb** [comment]
We failed to find a contact on the DTC website: https://www.oit.va.gov/marketplace/about

We will reach out to Wes to see if he has any leads on that team

**Comment by dawnpruitt** [comment]
Identified email for DTC support team late afternoon on 3/3.
Email sent to DTC Suport team on 3/6:
From: Pruitt, Dawn M. (liberty It Solutions, Llc)
Sent: Monday, March 6, 2023 3:19 PM
To: DTC Support Team <DTCSupport@va.gov>
Subject: Inquiry on Site Improve/Drupal CMS
Good afternoon,
My name is Dawn Pruitt and I am a contractor supporting OCTO with a focus on the CMS. We are researching the technical feasibility of deep linking Site Improve to our Drupal CMS.
In order to determine if our solution is feasible, can you please advise what constitutes “VA Data?” It’s possible that our solution would be unable to transmit “VA Data”, but we are unsure how VA defines VA data.
If you are not the correct team to assist, would you please let me know who may be able to help?
Thank you so much and please let me know if you have any questions.
3/7: awaiting reponse.

**Comment by EWashb** [comment]
As of July 2023, we will put this initiative on hold. I have coordinated with Blake Scates regarding integration and the costs and efforts associated with this work. VA currently has a roll out planned for AMP which is another accessibility scanning tool. Because of this, I believe we are trying too many solutions at once. AMP is currently being tested as a solution with our VHA DM partners and @laflannery. While AMP is undergoing testing and rollout planning, we should halt Siteimprove integration to ensure we are not duplicating effort. We can revisit once the AMP discovery is completed by both our team and our stakeholder parents at VHA DM.

**Comment by EWashb** [comment]
I have completed this work. The current implementation of siteimprove does not pose security risk. However, we would need to look into a contract modification if we would like to implement a prepub token behind the firewall and possibly need to shepherd it through a new ATO.  With this info in mind, I have worked with Blake Scates at VHA DM to pause this effort while we do discovery on AMP scans.
