### ISSUE TITLE
Audit CMS design system for discrepancies

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12362]
## Description

As we have begun rolling out the CMS collaboration cycle for product teams to build in the CMS it has become apparent that some of the [Figma files](https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=0%3A1&t=ovT6QKq11x84F5ff-0) do not reflect current state. This is especially true for changes made in Q3 2022 and Q1 2023. As we roll out the new collab cycle processes, it is imperative that designers on product teams can trust in and use the CMS design system to build upon. First, we should audit what lives in the CMS that may not be accurately documented in the design system. After completing that, we will look at what items require updates and make tickets to complete that work. 

## User Stories

- As a product team building in the CMS, I need to have confidence in the Figma design system to build products quickly and within the appropriate formats.
- As a CMS Team designer, I need the Figma files updated so that I might have a source of truth for the Drupal CMS.

## Acceptance Criteria
- [x] Audit current editorial interfaces for changes that must be updated in the CMS design system and documented
- [x] Create tickets for updates needed

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by EWashb** [comment]
We will also need to do somewhat of a post-mortem on how it got out of hand.

**Comment by BlakeOrgan** [comment]
### The Problem
Since we're wanting to align ourselves as much with the Platform team as possible, I took a look at the current state of the following resources in comparison to similar resources that the Platform team uses. It became apparent even if the Figma Design System should be the source of truth, that won't be the case if all of the touch points aren't aligned across the board so that the Design System is implemented in the way that we intend for it to be.

**CMS Touchpoints**

- Design Files ([Figma OLD](https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=0%3A1&t=YZNWfiyQN9dbiiMp-1) and [Figma NEW](https://www.figma.com/file/LAlrfgqFJgCV9EIq7eyDcw/Simplified-Design-System?node-id=210%3A123&t=F5t36ypkaNPkyb8k-1))
- [Design System Documentation](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1712324609/CMS+Design+System) in Confluence
- [Storybook](https://storybook-stdirdt4jxl4xlaze1syc4vdz1pb9gvr.ci.cms.va.gov/?path=/story/introduction--page)
- Finished Product (https://prod.cms.va.gov/)

**Platform Touchpoints**

- Design Files ([Sketch](https://www.sketch.com/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/p/3e88de6d-883b-4c18-92a9-a01b7304e09d))
- [Design System Documentation](https://design.va.gov/)
- [Storybook](https://design.va.gov/storybook/?path=/docs/about-introduction--page)
- Finished Product (va.gov)

After taking a look at the existing CMS Design System and comparing it to the Platform design system it became apparent that the CMS Design system has some work to do in order to become as mature as the Platform Design System, so I want to use Platform as a roadmap for what the CMS design system can become. The Platform team uses an [atomic design methodology](https://atomicdesign.bradfrost.com/chapter-2/) to building their design system. They use the following atomic levels and each level builds on one another using pieces from the level before it to create a more robust system.

-  [**Foundation**](https://design.va.gov/foundation/) - The Foundation section provides information about the visual language and styles used in the CMS.
-  [**Component**](https://design.va.gov/components/) - Components are interactive and non-interactive UI elements that can be grouped together or presented individually. They are independent, reusable chunks of a user interface.
-  [**Pattern**](https://design.va.gov/patterns/) - Patterns are solutions and researched best practices for solving user-focused tasks and recurring user interface design problems.
-  [**Template**](https://design.va.gov/templates/) - Templates, or page layouts, compose components within a single page. A layout can contain multiple variations of a component depending on the context.

In order to ensure that all of our updates are implemented properly moving forward, I have created the following resources:
- Created a [spreadsheet](https://docs.google.com/spreadsheets/d/1b5BxRM9UlM74G3dgKfJM1dqSeN8QoQrwzGAtbGiwdeE/edit?usp=sharing) that compares the documentation for Platform to what we have in the CMS.
- Created a [checklist for each touchpoint that needs to be in alignment](https://docs.google.com/spreadsheets/d/1b5BxRM9UlM74G3dgKfJM1dqSeN8QoQrwzGAtbGiwdeE/edit?usp=sharing).
- Created a [reusable template](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12947) for github tickets for updates and additions needed to the design system.

### Audit

The current state of the CMS design system has items for Foundation and Component elements, but these will need to be looked at on an individual basis to make sure all touch points are aligned across the board. Once these have been corrected, we can then work towards building out Pattern and Template elements that will be much more useful for cross team collaboration when it's needed. Here's a quick audit of what we have in our Design System in the terms of the atomic levels that Platform uses.

**Foundation**
We currently have all of the following, but we should ensure that all touchpoints are still aligned before proceeding

- Colors
- Typography/Heading levels
- Spacing
- Icons

**Components**
We have some of these, but some we do not.

- Buttons
- Inputs (This needs to be more granular, but should include the following)
- Text inputs
- Dropdowns (add)
- Single Choice (Radio) selections
- Multiple choice selections (add)
- Etc

**Patterns**
We have very few of these.

I foresee this being individual content types. There are a handful of these in the Design System but very few of them are accurate or they are screenshots of the CMS, which is not useful. I recommend that once we're in a place where we feel good about our Foundation and Component elements, we take a look at Content Types available to VAMC and Vet Centers a phase one and then expand to others as a phase two. As you can see in the [CMS content model documentation](https://airtable.com/appSg80z9nVWoesxn/tbl5o1AxKu7ufswjv/viwWTQYPMWSOV91rJ?blocks=bipz2F2iCJ6xlOlNM), there are ZERO FIGMA LINKS and ZERO STORYBOOK LINKS listed.

**Templates**
We have almost none of these.

When the combonation of foundation, components, and patterns come together to create a whole page within the CMS. Our templates should always reflect the current reality of the CMS. There are VERY FEW templates within the Design System that reflect the reality of the CMS. Lots of what exists within the Design System for things that are in this stage are screenshots, which provide almost no value when it comes time to actually use the template because you’ll have to build it using the foundation, components, and patterns.



### Phase 1: Update all of our foundational elements.

The following tickets have been created as next steps to address the immediate updates that are needed to have a good foundation to work off of for phase 1. Once our foundation is solid and these tickets are complete, we can then expand on building out additional tickets to align our touchpoints for components, patterns, and templates that are currently in the CMS, but not in the Design System and vice versa.


- Update Colors: [Ticket 12949](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/12949)
- Update Typography: [Ticket 12950](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/12950)
- Update Spacing: [Ticket 12951](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/12951)
- Update Icons: [Ticket 12952](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/12952)

**Comment by BlakeOrgan** [comment]
Post-mortem ticket is here.
https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/12871
