### ISSUE TITLE
CMS Design: new custom block for Homepage "Create account" content

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12388]
## Description

As a Homepage Editor, I want to edit the "Create account" content on the new homepage as a custom block type so that I can make copy changes without engineering help.

See the white box to the right of the screenshot:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/4054752/215910462-f35f09a4-f67c-43e1-a63f-58b4d062ae0f.png">

See Jill's excellent primer of existing homepage block UIs for ideas/guidance.

## Acceptance Criteria
- [x] Drafted design of CMS UI in Figma
  - [x] Has default fields for a custom block
    - [x] title
    - [x] description
  - [x] Has custom fields
    - [x] Teaser content – indicate future character limits
    - [x] Button text – indicate future character limits
    - [x]  Button link/URL
    - [x] Related info link text – indicate future character limits
    - [x] Related info link destination
- [x] Asked Wes to schedule CMS Collab Cycle kickoff (as soon as draft is done)
- [x] Conducted feedback cycle with Drupal dev(s) on team

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Re: examples of blocks:  custom blocks are very custom. They start with a Title and Description, but we recently did some customization for the homepage, and those examples are below for reference.

In general here we need to work backward with @wesrowe and probably @dsasser to understand: 
* what should the fields be for this new custom block
* should they be required
* help text

With the goal being: make it possible to modify the Create account text within the CMS, rather than requiring a code change.

### Homepage custom block examples
https://prod.cms.va.gov/admin/structure/block/block-content
Role required: Drupal Admin

**Add custom block to create, or Filter to by Block type to see existing blocks:**
![Screen Shot 2022-12-06 at 2 13 30 PM](https://user-images.githubusercontent.com/85581471/206035019-bd877b84-8d27-4d07-9229-b6a0e9764e61.png)

**Create: Add custom > Choose block type:** 
![Screen Shot 2022-12-06 at 2 14 04 PM](https://user-images.githubusercontent.com/85581471/206035075-48bef518-7e0f-4b82-9e61-e3aafd2b6112.png)

**Block form: populate required fields**
**V2 Home page Benefit promo form:** 
![Screen Shot 2022-12-06 at 2 16 07 PM](https://user-images.githubusercontent.com/85581471/206035609-855718e5-2f72-40b3-937b-fc8e32f409b3.png)
* Block description: not shown to Veterans, just helps identify the block in the CMS list of blocks

**V2 Home page News spotlight form:** 
![Screen Shot 2022-12-06 at 2 19 47 PM](https://user-images.githubusercontent.com/85581471/206035874-eca389f8-32b8-45d2-ba37-99e5051cbecd.png)'
* Block description: not shown to Veterans, just helps identify the block in the CMS list of blocks
* Image, CTA, Promo Headline, Promo Text are all custom fields

**Comment by wesrowe** [comment]
@thejordanwood, FYI, I added the necessary fields to the ACs above. The field names are my best guess/draft, but there are probably better names for them. Rather than get too wrapped up with naming, I think we can take that to CMS collab cycle for finalization.

I don't think char limits are necessary for the design. However, the existence of char limits might be visible.

**Comment by thejordanwood** [comment]
@wesrowe The initial design is in [this Figma file](https://www.figma.com/file/OJ6ncc4hAvABO6iX5Z1Aw6/Create-Account-content-block?node-id=0%3A1&t=VBISO5VfyiEpAcXQ-1) and is ready for the CMS collab cycle.

**Comment by thejordanwood** [comment]
The [figma file](https://www.figma.com/file/OJ6ncc4hAvABO6iX5Z1Aw6/Create-Account-content-block?node-id=46%3A1754&t=yf7VyAnOcahTJJb1-1) for this has been updated based on changes that came out of the collab cycle meeting.

[Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1676394302997389) requesting review / notes.
