### ISSUE TITLE
Update outdated content report to show only assigned sections

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12450]
## Description

Currently the outdated content tool allows users to see all sections, even when they are not assigned those sections. In order to avoid confusion with the editorial experience, we should rework the filters to only show editors content in the drop down that they are responsible for/can access. 

Current view:
![Screenshot 2023-02-06 at 1.12.41 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/2ac89a3b-3267-444d-b406-a70c57f78a6c)

## Acceptance Criteria
- [x] limit section filter view to match only what editors have access to
- [x] Add sort to Last Saved by and Editor column, asc, and make it the default sort
- [x] Move OUtdated content to the content menu dropdown
- [x] Requires design review
- [ ] Requires accessibility review

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
Notes from 16th min:
- We will only send 1 email/person (i.e. if a person is assigned to a whole VISN or multiple sections we will not be sending multiple outdated content emails to them)
- The messaging in the email should be generic - because it  will no longer be section specific (
- The link in this outdated content email will go to the outdated content report in the CMS
- This link will be smart - meaning we will know who the editor is and we will show them only the section(s) they have access to
- The Section dropdown filter will not display any section the editor does not have permission for (Edmund is going to remove these but preserve the hierarchy)
- Blake also asked if we could add a sort ability to the "Last saved by editor field" column in the table.  Edmund said yes and asked Blake to make a separate ticket for this.
