### ISSUE TITLE
Editorial Workflow changes

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12573]
## Description
The Editorial workflow has changed in Drupal 10 from what we currently have in prod

**Current situation:**
- The current state is noted
- Then there is a dropdown labeled as "Save as"
  - This dropdown is set to Draft, even if the node's current state is Published
![image](https://user-images.githubusercontent.com/106678594/218197527-e8b16c07-5ca8-49be-a244-a9895394dff0.png)

Drupal 10 situation
- The current state is noted
- There is now a dropdown labeled as "Change to"
  - This dropdown is now Published if the node's current state is published.
- Then we have the revision log message area
![image](https://user-images.githubusercontent.com/106678594/218197849-7bbbdfdc-87de-463e-b1b8-d5f10b932506.png)

### Additional Context
I am not sure I would call this an issue or a bug, but rather a possible enhancement  I had previously discussed this with the Help desk and there may be times when editors do not notice that the Save as dropdown is automatically set to draft and therefore they accidently "publish" new updates as draft - which means they don't publish them at all.  Respecting the current moderation state, might be a benefit to the editors.

**Comment by laflannery** [comment]
@edmund-dunn I put it in the note above but I think we (not just me and you but also @EWashb and possibly others) should chat about this before we do anything about it. That's assuming we can do anything about it - perhaps it's just a change we need to absorb and let our editors know about?  But either way let's make sure we discuss it.

**Comment by BlakeOrgan** [comment]
I agree. From a UX perspective, I think the default when making edits should be to keep whatever the last state was whenever you clicked to edit instead of always having draft as the default and forcing people to change it every time. It's extra work for the users that's not necessary.

If they're changing the state to something else, they will be aware of the change because they would have had to make the change themselves.

Also note that, Drupal 10 should continue to have "Save as" instead of "Change to" next to the dropdown.

**Comment by davidmpickett** [comment]
Hey hey. Looks like we intentional overrode the default Drupal label way back in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3507

**Comment by laflannery** [comment]
@EWashb @productmike and @BlakeOrgan I was doing my a11y testing today and noticed that this is still occurring.

So a couple things:
1. This does confirm that all these issues I noted were D10 issues that we definitely want to review prior to launch
2. I feel like  this needs some discussion because if this is something we choose to keep, we should notify folks about (and update KBs) because it's definitely a change in workflow and we don't want them accidently publishing things they are still working on.

**Comment by EWashb** [comment]
I agree that this is something we need to address before the D10 upgrade. The least disruptive thing to do right now is to mimic the workflow that we currently have. I agree with Blake's comment before. We should keep our current flow because changing it to what D10 offers would require a large amount of CM that isn't worth it, IMHO. @laflannery @productmike
