### ISSUE TITLE
Add test for va forms csv to detect date of file

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12592]
## Description

Similar to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10735 and the tests created there.  It just needs another test.

### User story
> As a VA Form product maintainer I would like to be alerted if the CSV file we keep moving and importing from goes stale sp that we can be alerted to an upstream failure.  Specifically, If they stop updating the export, we will keep grabbing the same copy and never know there is a failure.

### Engineering notes / background
There is an @todo in the existing test file for where to add this test.  https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12421/files#diff-87e4067ad8893e01fedfbf7ceee85fc5c4d63147b6f7cdd36f03f7a82373ea7fR18

### Tasks
Assuming we can check the timestamp, and the file is updated nightly (TODO: Verify based on comments below). 
* Confirm that the Forms CSV import machine (Jenkins?) can read timestamp from the Forms DB CSV hosting machine 
* Write the test - Check the timestamp is not > 3 days before today
* Find a way to hack proving it works with a local file that's > 3 days old

## Acceptance criteria

- [ ] If the date of the csv file that we move is over 3(? )days old a failure should be noted and prevent migration.  Three days should help avoid getting a false alarm Sunday evening if the file was not updated Saturday and Sunday.   This assumes it is updated m-f including holidays.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Backend Refinement: questions
1. How do we know the date of the CSV? CSV creation timestamp? Are we able to read it from the point we pull it in?
2. Does the CSV get updated nightly? e.g. is it a reasonable expectation to assume that every CSV we receive will never be more than 2 days old?  (Why: we don't want false positives. e.g if we only get a new CSV when forms mgrs update the Forms DB, then we may have an older CSV sitting until the next update). 

@swirtSJW we checked the [Forms migration docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form) but it's not clear if we get a new CSV every night by default. Do you know? If not, will ask Kevin Reid.

**Comment by jilladams** [comment]
Assigned to @chri5tia for prerefinement to help get these questions answered.

**Comment by swirtSJW** [comment]
> Do we need to look at the date from the file on our end or the file on the source server?

I would look at the date of our copy and I think Nate confirmed that the file comes in with the same file data that the source file has.  So testing one essentially checks the other.

> Is the file on our end downloaded each day regardless of changes?
It is downloaded via the task.yml and its runner daily, regardless of whether it changed or not.  And I sure the forms db does an export every day via cron whether anything has changed or not.

> Should I look at the unix date stamp on the server, a file name, etc.
The filename does not change.  You would be looking at the timestamp.

> Where can I go look at it on the server?
Details on the migration are here https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md#source-forms-db

**Comment by chri5tia** [comment]
Summing notes up from call with Jill and Nate. 
There doesn't seem to be a lot of usefulness of this test because the curl command that grabs the file from the source will always create a new file. This test will always pass unless the servers are down, and we would know if the server is down for other reasons. If the source file is borked, it will fail due to being empty or not having correct headers.
We could write that into the curl command but it involve more sophistication than simply adding a test. 

Nate suggested that we can grab the modified date header of the source file to ensure that it's not stale, but we should explore the failure conditions we are looking for by making sure the data isn't stale. He doesn't feel that this test would have much value.

Curl will create a new file automatically almost no matter what.

**Comment by jilladams** [comment]
Perfect, yes. And just my emphasis: if we add logic to the task that pulls down the file in the first place, to check the last modified header (which is really the source of truth for staleness of the file): that is a bigger risk factor because we are not able to test in Tugboat. We can only test in production. 

So: if in future we want to get at testing file staleness, we should cut a new ticket with new ACs, to either: 
1. Add a test that replicates the task that pulls the file, and check the Last modified timestamp in the remote file (duplication of the task code, but easier to test / less risk), OR
2. Update the task itself to check the Last modified timestamp and fail if it's stale. Bigger lift, more risk, harder to test. 

Closing this ticket as no-op.
