### ISSUE TITLE
Create training presentation on VA Facilities basics: VAMCs + Vet Centers

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12646]
## Description
When training new colleagues on the Facilities team, I would like to have an easy reference point explaining the different VA facility types.

**Link to presentation draft:** https://docs.google.com/presentation/d/1LM30wutdZ7N2DQMoTG-TAd5Vk_6BACqFB7OlAxE8mN4/edit?usp=sharing

## Acceptance Criteria
- [ ] Presentation explains differences between VAMCs and Vet Centers in real life, and in the CMS

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends This presentation is halfway done but a good reference to have -- can flesh out next week for our training

**Comment by mmiddaugh** [comment]
@xiongjaneg @jilladams can you take a look at this (non-urgent) and determine how to proceed?

**Comment by xiongjaneg** [comment]
I'll defer to @jilladams on this. This sounds like onboarding and I don't recommend creating yet another source of information for onboarding. That can be cognitive overload for new staff who often comment on having too much info in onboarding.

**Comment by jilladams** [comment]
Chatted with Stephanie. This came up during an era of PM transition on the contract, and since then we've updated more docs and have better info in place re: what our products are, e.g.
* [Facilities onboarding mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695856839558/7869f5644c50c0447de07631d3fe85f86ae2c9a7?sender=u0b235d03cbd64f7f93673243), and 
* [VAMC product documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers)
* [Vet Center product documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers)

So: calling this satisfied, and closing.
