### ISSUE TITLE
research: VISN: What Analytics are currently available?

### ISSUE THREAD

**Issue by Dottisea** [department-of-veterans-affairs/va.gov-cms#12655]
As a researcher, I want to understand the analytics currently available for use on the VISN websites so that I can analyze how  many Veterans use the website to access what content.

**Comment by xiongjaneg** [comment]
Closing this as the epic is closed. These analytics are largely provided by either [Google Analytics](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/new-users-to-google-analytics) from the Platform Analytics and Insights Team or [Contact Center CSAT (Medallia) data](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/accessing-and-utilizing-contact-center-data). Medallia quantitative data can be accessed through a Domo account (requested through VA Okta) and qualitative data can be submitted to Contact Center for a csv file (must use VA email because of potential PII or PHI submitted by users in CSAT text fields).
