### ISSUE TITLE
UX Review of Covid status changes

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12663]
**1. What is this request for?**

[COVID-19 status details are being changed](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10708) to allow editors at facilities to add facility-specific language to describe the COVID status guidance for a given facility.

**2. What is the primary function and/or purpose of the product?**

This change is intended to provide for more flexibility in communicating the local response and precautions for COVID-19 and to better prepare Veterans and their families with relevant guidelines as they plan their visit to a facility.

## Current workflow
https://user-images.githubusercontent.com/766573/219671572-5504d518-0dae-4fb8-8f1a-2e74708a22df.mov

## Future workflow

https://user-images.githubusercontent.com/766573/219671793-cbcc85b9-ab0f-4535-8910-e824aeaedc2d.mov

**3. Are there any known accessibility issues that have not yet been addressed? If so, please add GitHub links to those issues below.**

Not that I know of.
  
**4. Are there any specific testing requirements that should be noted?**

Turning off JavaScript on the page will break the new functionality, so it is required.

**5. Please provide anything needed to access and review the product.**

As an admin, log in and [create a new VAMC Facility](https://pr12403-yjq5zexhavmhassuj4kctou3kauqjue2.ci.cms.va.gov/node/add/health_care_local_facility) in the PR branch.

  
**6. When does the product need to launch?**

 February 28

**Comment by BlakeOrgan** [comment]
A couple of notes for things that need fixed:

- The text size of "Operating status" and "COVID-19 health protection guidelines" are incorrect. [See design](https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=236%3A32267&t=illFAFU5zbI379cK-1)
-  The sentence that says "Don't duplicate information contained in your COVID-19 status." at the top under operating status isn't necessary because the following sentence is part of the help text for Details when Facility notice, Limited services and hours, or Facility closed are selected. "Don’t include any information about masks, screening, or visitor policies due to COVID-19. This information is now covered in the COVID-19 health protection guidelines."
- "Learn more about COVID-19 safety guidelines" is repeated twice under COVID-19 status, once as plain text and once as a link. Remove the plain text and only have the link.
- The character counter doesn't update when switching between low/med/high levels when the number of characters changes.
- The code and quote options shouldn't be part of the RTE. These options aren't supported where displayed on the public facing site.

**Comment by omahane** [comment]
> The text size of "Operating status" and "COVID-19 health protection guidelines" are incorrect. [See design](https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=236%3A32267&t=illFAFU5zbI379cK-1)

It looks like the "Operating Status" is 32 px and "COVID-19 health protection guidelines" are 24 px. That's what I'll add to the CSS.

**Comment by omahane** [comment]
![Screen Shot 2023-02-20 at 9 17 28 AM](https://user-images.githubusercontent.com/766573/220145221-f3857c94-38cf-490a-a3fa-fe8c91aaada5.png)
I have addressed the first 3 issues identified. See screenshot above.

**Comment by omahane** [comment]
## Number of characters remaining
Changing the character count when selecting a different status was not captured in the Acceptance Criteria. The current functionality of the character count is that it changes on keystrokes. I have tested out a couple patches of the "textfield_counter" module (which provides the current functionality), but even those patches don't make the character count change with a different status choice.

How critical is this?

## WYSIWYG toolbar
The WYSIWYG is set to "Rich Text Limited," which provides the buttons in the toolbar. Dave Conlon did not want to create a new text format for this issue, which means that we have buttons not accounted for in the design.

**Comment by laflannery** [comment]
@omahane 1-3 look good, thanks! It looks like @davidmpickett rightly pointed out that the last 2 need a bit more guidance and should be talked about with the rest of the team so I'll leave that to you all unless you tag me back in again.

My last question - you did this right, it's in the design file but does this seem like proper grammar "This section is pre-populated with suggested text based on the level you selected but **_is editable to in order to make_** changes that fit your unique situation." (It's the text for the Detail field under the COVID-19 Status.) I feel like the first TO should be removed?

**Comment by omahane** [comment]
Good catch, @laflannery. I think we can slim it down to 
> This section is pre-populated with suggested text based on the level you selected but is editable to fit your unique situation.

**Comment by omahane** [comment]
I had some more time to think about these two issues, and my recommendation is that they don’t hold up the roll out. 

## WYSIWYG toolbar
The “Rich Text Limited” format has one button that is not useful for COVID Status Description, the <blockquote> button. The “Source” button is a convenience for editors, should they find their formatted text not behaving properly. When that was my job to create and edit web content before I was a developer, I found the ability to see what was going with the HTML to be helpful. So creating a new text format for a single button that the editors do not need to use is a lot of effort for very little gain.

## Number of characters remaining
The “Remaining Characters” work when the editors are editing, which is the most important function they have. The reason the field exists is not for content to prepopulate and be left (though it can, and the text meets the character limit [now that we aren’t counting HTML characters]). The point of the field is to give editors the ability to customize the text, during the the character counter does exactly what it is supposed to do. If there was a patch already created on the contributed module that solved this issue, I’d add and test it; but the ones I thought might have did not. While I think it would be worthwhile to contribute code back to the community, the fact that the current patches don’t fix this points to how difficult it likely is.

**Comment by omahane** [comment]
> Good catch, @laflannery. I think we can slim it down to
> 
> > This section is pre-populated with suggested text based on the level you selected but is editable to fit your unique situation.

@laflannery This has been updated on the PR environment: https://pr12403-yjq5zexhavmhassuj4kctou3kauqjue2.ci.cms.va.gov/node/add/health_care_local_facility

**Comment by laflannery** [comment]
@omahane A few final questions from reviewing (sorry if some of these were previously answered just want to be thorough):

1. The text under "Operating Status" is slightly different between Figma and the CMS. Is this intentional and Figma is an older version? (Totally fine if so I just want to make note of this)
   1. Figma: **_Use these statuses for events_** that impact your facility's operations. This content will display on the facility's location page and operating status page.
   2.  CMS: **_Use this status for weather or other events_** that impact your facility's operations. This status will display on the facility's location page and operating status page.
2. On the Low and Medium status levels, the prefilled content has a big space between the bullets and the last line of content.  The high level does not have this. I think perhaps this space should be removed?
   1. Low and Medium: ![image](https://user-images.githubusercontent.com/106678594/220674609-8f15a022-3895-4ece-a726-12c0d20f64b5.png)
   2. High: ![image](https://user-images.githubusercontent.com/106678594/220674687-ee9845eb-4248-4fd1-90a9-a84b8c6f2f24.png)
1. In Figma, the default text size within the WYSIWYG is much larger than in the CMS. I have a feeling this is not something we can or should change as it would be a more sitewide change? But again, I just want to note why it is different in Figma
   1. Figma - 18 px: ![image](https://user-images.githubusercontent.com/106678594/220676520-c19f27fb-483d-4573-9092-c6f0a9fca301.png)
   2. CMS - 15px: ![image](https://user-images.githubusercontent.com/106678594/220676708-8a4d4032-e7a0-4d7a-b0ee-37aeea680b21.png)

**Comment by omahane** [comment]
@laflannery 
## WYSIWYG in FIGMA is much larger than in the CMS
I'm not sure what the source is for the font size of any element in FIGMA. Multiple elements have a font size that is at odds with a current size ("Operating Status," "COVID-19 health protection guidelines" and the WYSIWYG). I don't think it is based on what we have right now throughout the CMS. I don't know if I should just change the sizes for this content type, which I have been doing and can continue doing, or whether the sizes in the FIGMA should be rolled out to the entirety of the CMS, which is bigger than Facilities.

**Comment by omahane** [comment]
@laflannery  
## The text under "Operating Status" is slightly different between Figma and the CMS.
This would be easy enough to change, but I honestly don't know if the Figma change was a copy/paste from an older design or a deliberate change. It might be something @BlakeOrgan did. (would @davidmpickett know?) The last time the file that creates this copy on the CMS was changed was 9 months ago. 
It's different back in May 2022 from either what is in the Figma or what it is currently:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9026
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8960

**Comment by omahane** [comment]
Per @Dottisea 
The remaining (remaining characters and text format) issues are not launch-blocking.
