### ISSUE TITLE
Create disabled menu items on the fly

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1267]
## User Story or Problem Statement

As a content creator, i want to add easily disabled menu items so that i can specify the breadcrumb, even when the page doesn't appear in a navigation. 

## Acceptance Criteria
* A content_editor can add disabled menu items on the fly in the right rail of the form. 

To do 

- [ ] Figure out which node types have it now and don't 
- [ ] Figure out which node  types should have it (may not be all of them)
- [ ] Fix the gap 

## Implementation

Locate disabled_node_menu_item custom module settings per content type and update.

**Comment by oksana-c** [comment]
@kevwalsh , I see that VAMC facility form allows the user to create a menu item.

NCA, VBA facilities and Vet Center forms currently do not expose any menu editing options to the user. Should they?

- /node/add/nca_facility
- /node/add/vba_facility
- /node/add/vet_center

**Comment by oksana-c** [comment]
@kevwalsh , also see https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1492 
<img width="895" alt="Screen Shot 2020-04-14 at 2 53 15 PM" src="https://user-images.githubusercontent.com/16477724/79273850-e8728180-7e60-11ea-8a22-263d5fba0f92.png">

all content types where checkbox is checked, allow users an option to "Provide a menu link". Since we allow to add/edit a menu link, we now also allow to exclude the link from the menu.

If you see any content types for which we should disable "Provide a menu link" option all-together - please let me know. Thanks,

**Comment by kevwalsh** [comment]
> @kevwalsh , I see that VAMC facility form allows the user to create a menu item.
> 
> NCA, VBA facilities and Vet Center forms currently do not expose any menu editing options to the user. Should they?
> 
> * /node/add/nca_facility
> * /node/add/vba_facility
> * /node/add/vet_center

Yeah if these node types are not yet menu eligible, then i suppose this setting is not very needed. I also can't really imagine them creating these nodes without menu items in the future.

**Comment by kevwalsh** [comment]
Content types that should **not** allow disabled menu items: 

* Benefits hub landing page
* VAMC system
* All the listing content types

**Comment by oksana-c** [comment]
thanks @kevwalsh , makes sense. I included your feedback in  #1492
