### ISSUE TITLE
Incident Response Planning: Find Alternate Route to Contact Active CMS Users if Drupal Is Inaccessible

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12673]
## Problem statement
As a VA Drupal CMS Help Desk staffer responding to an incident affecting https://prod.cms.va.gov/, I typically manually pull (see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12571) the list of active CMS user email addresses via the Drupal "People" page when I need to send out immediate correspondence.

However, if Drupal is down -- how do we contact our editors? 

I could go according to the last failed content release mass email list, or according to the Staging or Training sites, or even my own most recent backup of the user listing from https://prod.cms.va.gov/. 

Still, these are not the best methods for ensuring that all editors are contacted during a serious incident.

## Acceptance Criteria:
- [ ] Add backup route for contacting authors when you cannot pull list of Active user email addresses via the Drupal "People" page
- [ ] Look into Github tickets linked below in order to revive talks of an active user directory using a tool such as LDAP linked to user accounts, which would also help track account status such as Active vs. Blocked. 

@TroyA6 - "There should be an automated process for backing up active user accounts from Drupal at least once per day."

**LDAP mentions in other tickets where an active user directory would be useful:**
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11342
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9239

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
@EWashb @dawnpruitt This is something Dave C had mentioned being concerned about, and it ties nicely into other tickets regarding having an active user database (such as LDAP) that's synced to the CMS

See: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9239
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11342

**Comment by TroyA6** [comment]
@stefaniefgray @laflannery - I have reviewed our options with MS Outlook as a way to manage communications during 'incidents'. My proposal (still somewhat manual, but done in advance of urgent situations): Create email templates in Outlook so that when an incident occurs, there is a standard communication already in place (Done); Additionally, create Outlook 'Content Release Groups' that contain editor information - so when sending incident related communications, the Editors are already in groups of 250 so that it is a matter of creating an email from a template, adding Content Release Groups, and sending. Thoughts?

**Comment by TroyA6** [comment]
Met with Stefanie - we agree that this is a good starting point - we will monitor and adjust as needed; Content Release Failure Alert and Content Release Update templates have been created in MS Outlook, as well as the current CMS user list being added as  Distribution Lists (1-4 due to MS Outlook limitations). When an incident occurs, emails can be sent to the Editors with just a few mouse clicks.
