### ISSUE TITLE
SPIKE: Lovell: View all link on items in both section produces inconsistent results

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12691]
Making a spike to determine where the issue is and what the remedy would look like- 

## Description
For the listing pages (Events, Stories and News releases), these display both individual section items and items in both sections. If I click on an item there is a "View all" link at the bottom.  This link is not behaving as expected in all cases

**I started in the TRICARE section, I would think that the View all links would all bring me back to the main listing page in the TRICARE section.**

- Stories
- [A story in both sections](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-va/stories/test-story-for-both-lovell/)
  - When you click the link at the bottom of this item, it goes to an error
  - It's trying t go here: https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care/stories
- News Releases
  - [A new release in both sections](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-va/news-releases/test-a-press-release-for-both-lovell/)
    - When you click the link at the bottom of this item, it just appears to refresh the page
- Events
  - [An event in both sections](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-va/events/49924/)
    - When you click the link at the bottom of this item, it brings me to the events listing but for VA, not TRICARE. This is a confusing experiencing because it's not where I came from.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
@Dottisea for visibility

**Comment by ryguyk** [comment]
## Notes (WIP)
### A story in both sections:
https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-va/stories/test-story-for-both-lovell/

The view-all link URL is built from `fieldListing`. In this case, the story is set to the _Federal_ listing, since that is the method for adding it to _both_ VA and TRICARE. So, this story will show up in two places, and in both of those places the view-all link will point to a non-existent Federal listing page.
- https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-va/stories/test-story-for-both-lovell/
- https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-tricare/stories/test-story-for-both-lovell/

#### FIX
The resolution for this should involve updating `fieldListing` during the process of merging federal listing pages with their VA and TRICARE counterparts. When merging with VA, for example, `fieldListing` needs to be updated to reflect VA rather than Federal. The same goes for TRICARE.
