### ISSUE TITLE
New Homepage hard launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12772]
## Description
Replace the existing VA.gov homepage with the new homepage.

The existing preview path, /new-home-page, will stay live in its current state, for use in future iterations of the homepage, per previous discussions with DaveC.

**BLOCKED BY:**

- [x] #12162
- [x] Success criteria metrics provided for review by @wesrowe
- [ ] Metrics review by @rtwell & @davidconlon 
- [x] Dave C greenlight

### User story
**AS A(N)** Veteran
**I WANT** to see the most up to date and well researched content on the VA home page
**SO THAT** my navigation, search, and wayfinding experience is streamlined and efficient.

### Engineering notes / background
* Current homepage = ~https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/home.html~ https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/home.drupal.liquid
* New homepage = https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/home-preview.drupal.liquid

#### DRY conversation: 
* See [Ryan's detailed comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12772#issuecomment-1561199650) on a possible approach.
* Because we will eventually need to revive /new-home-page for future iterations we as a team decided we will _not_ try to DRY the templates, but will maintain both. Two way door: we could DRY it up later if it proves heavy tech debt to maintain both, and we don't iterate on homepage anytime soon.

#### CMS Feature flag
`FEATURE_HOMEPAGE_V2`
* on = new home page is visible at /
* off = new home page is not visible. Old home page contents are visible at /

## Launch steps
Pre-launch:
- [x] New home page content in the existing homepage template is behind `FEATURE_HOMEPAGE_V2` CMS feature flag, and is tested / verified in Tugboat.
- [x] After verified, can merge to main. **MUST** test CMS feature flag and verify on Staging before the daily deploy after merge, to ensure no accidents in prod.
- [ ] **MAYBE:** OPIA may need to update Promo content on /new-home-page prior to launch. DaveC to confirm.

Launch:
- [x] **BLOCKER:** Greenlight from DaveC
- [x] Start [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1685555161506669) in #sitewide-public-websites, cc Wes, Jill, Dave. Post updates to thread as steps are completed.
- [x] Night before release: ensure `FEATURE_HOMEPAGE_V2` CMS feature flag is OFF so that it snapshots down to Staging overnight
- [x] Confirmed in Staging post-merge that old HP looks unaffected
- [x] At/before Prod daily deploy: 
  - [x] Disable the `va_home_preview_modal ` Flipper - modal will no longer appear
- [x] After content-build daily deploy, switch out banner and NHP simultaneously
  - [x] Enabled `FEATURE_HOMEPAGE_V2` CMS feature flag
  - [x] Archive https://prod.cms.va.gov/banner/va-facility-and-status-updates, so that Facility status banner does not appear on new homepage after launch.
- [x] Monitor next content-release to ensure success (New HP showing, banner gone) & post to Slack to confirm.

Rollback plan: disable `FEATURE_HOMEPAGE_V2`.

## Acceptance criteria

**Modal**
- [x] Modal no longer appears to any site visitors
- [x] `va_home_preview_modal ` Flipper is disabled (will be deprecated by #13184)

**Homepage**
- [x] Archived https://prod.cms.va.gov/banner/va-facility-and-status-updates prior to cutover, so Facility status banner does not appear on new homepage after launch.
- [x] VA.gov homepage displays the new home page design / content, including Drupalized create account block, updated Home page hub list, news & benefit promo blocks, Search box, Top pages menu, and veteran images on desktop breakpoints.
  - [x] ensure meta tags are correct for actual home page, including va.gov <title> = `VA.gov Home | Veterans Affairs` 
- [x] va.gov/new-home-page continues to be visible to users, and contents do not change
  - [x] va.gov/new-home-page <title> remains `New VA.gov home page | Veterans Affairs`
- [x] Ensure that post-login redirect sends users to My VA (as on current homepage)
- [x] Update KB article language that refers to Soft launch, to be correct for hard launch / live page

**Comment by jilladams** [comment]
![Screenshot 2023-04-07 at 3 26 41 PM](https://user-images.githubusercontent.com/85581471/230686441-9dcff820-3418-46a2-af3b-09ec961a8e3d.png)

Added.

**Comment by jilladams** [comment]
Likely to move into Sprint 84

**Comment by jilladams** [comment]
Existing KB, "Managing homepage content blocks: --> https://prod.cms.va.gov/help/managing-homepage-content-blocks

**Comment by wesrowe** [comment]
@ryguyk, @randimays pointed out that there's an engineering question in the ticket details above:

>TO REFINE: Because the "new" home page path will stay live, it seems the best means of cutting over will be to just replace the contents of home.html with what's currently in home-preview. One is an html doc and one is a liquid template: what implications does that have?

I wonder if we could determine this ansync before sprint planning on Wednesday. Do you already know the answer?

**Comment by ryguyk** [comment]
@wesrowe A few notes:

- `home.html` is not what drives the existing homepage (as far as I can tell, it's old and can be considered for removal, though I'd need to examine more deeply the story behind this). `home.drupal.liquid` is the template.
- Replacing `home.drupal.liquid` with the contents of `home-preview.drupal.liquid` will not work. There are more pieces to this puzzle. There is some pre-processing work done in `src/site/stages/build/drupal/home.js` that sets up data objects that are used by the templates. The pre-processing for the current homepage is different than the pre-processing for the new homepage.
- It's not crystal clear to me what the goal is of having the page available in both places, but whenever I hear something that sounds like "same content in two places", I immediately go to a place of DRYing things up. In this case, I'd likely do this:
   1. Remove `home.drupal.liquid`.
   2. Rename `home-preview.drupal.liquid` to be `home.drupal.liquid`.
   3. Remove code in `src/site/stages/build/drupal/home.js` that sets up data for existing home page.
   4. Likely rename some things in the code in `src/site/stages/build/drupal/home.js` that sets up data for the new home page (rename to just be "homepage" rather than "preview" or "new").
   5. Where the actual html page is built (at the bottom of `src/site/stages/build/drupal/home.js`), I'd add a second file to be built:
      ```
      const homepageHtml = createFileObj(homeEntityObj, 'home.drupal.liquid');
      files[`./index.html`] = homepageHtml;
      files[`.${homePreviewPath}.html`] = homepageHtml;
      ```

It's worth noting that this approach will simply produce the same contents from the same template in two different places. In the event of a next iteration of a homepage refresh, the process would then have to include bifurcating things again.

**Comment by jilladams** [comment]
Point of clarification: after we split, is it ok for new-home-page to go stale with any interim homepage updates before the next iteration? Or do we need to maintain both in parity over time?

**Comment by jilladams** [comment]
Forgot to ask in planning, asked here: https://dsva.slack.com/archives/C52CL1PKQ/p1685048765507689

**Comment by jilladams** [comment]
Answered: post-launch, it's acceptable for va.gov and /new-home-page to fall out of sync, as we update the live home page.

**Comment by jilladams** [comment]
ACs met, KB updated / published, closing. WOO.
