### ISSUE TITLE
Post-mortem of current state of the CMS Design System

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12871]
## Description

Work being done for #12362 will highlight all of the issues with the state of the design system, but we should do a post-mortem and document how the issues came about in the first place.

Some of the causes of the CMS DS being not the source of truth are:

- Funding issues with PTEMS (lost many design resources)
- New CMS Designer was allocated to focus on other priorities such as CMS Notifications research/design/change management, Covid status udpates, and assisting other teams when building on the CMS, building out the CMS Collab Cycle
- Product teams are still confused about how to build on the CMS (we [The CMS Team] have found that we need to be more regimented in our design approaches, either through collab cycle or updated guidance.
- The first iteration of the design system did not track all of the components needed by product teams and there is no formal experimental design system process

This can live in CMS github documentation
[Template to use if needed](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/_template.md)

## Acceptance Criteria
- [x] Create post-mortem documentation about the CMS DS and plans to mitigate 
  - [x] Root cause of some of the drift
  - [x] Mitigation plan (processes to prevent this from happening again)

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by BlakeOrgan** [comment]
The post-mortem in it's entirety can be read using [this link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md). It includes sections on the following items.

- [Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#summary)
- [Root Cause Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#root-cause-analysis)
- [Ownership](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#ownership)
- [Timeline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#timeline)
- [Problem Statements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#problem-statements)
- [Resulting Issues](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#resulting-issues)
- [Why it's important](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#why-its-important)
- [Solutions & Action Items](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#solutions--action-items)
- [Conclusion](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#conclusion)
