### ISSUE TITLE
How might we implement user permissions that vary by content type?

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12911]
## User Story or Problem Statement

As a Product Team building on the CMS (Facilities Team), I want to restrict the actions that CMS Editors/Publishers can take on certain Content Types so that incorrect content isn't published to Veterans.

**Instances of CMS editors creating patient safety issues**
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10833#issuecomment-1332659220
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11231#issuecomment-1332666034
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10818#issuecomment-1560139497
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12000#issuecomment-1528478521
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10825
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7925#issuecomment-1434415211
- Phoenix 32nd Street VA Clinic https://prod.cms.va.gov/node/47359/revisions

**VAMC**
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11028
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13670
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5072
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12662
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5248

**VBA**
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334

**Service Taxonomy**
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7697
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13133

**CMS tickets**
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4965
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4759
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8232
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6114
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/900
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13442

## Possible Approaches

**Human validation via workflow and permissions**

- ✅ This is essentially the approach we are using now, except that we haven't fully enforced it. VAMC Editors are _supposed to_ check with Help Desk before Publishing or Archiving certain content types, but we haven't actually prevented Editors from doing this so we're in a half measure situation
- ✅ Having the general ability to have different sets of permissions per content type (via multiple workflows) could solve a lot of issues simultaneously, both for Facilities and alos potentially for other CMS Product Teams (Public Websites -> VA Benefit Taxonomy)
- ⚠️ Introducing a 2nd workflow after four years of only having 1 workflow could also create a lot of bugs simultaneously. We [previous tried to restrict permissions for some content types](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5248) by creating a 2nd workflow, but that created [this bug](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6342) so it got reverted
- ⚠️ Having certain CMS actions reliant on Help Desk (rather than VA employees in relevant product vertical) doesn't scale as we introduce more products into the ecosystem  Lowest initial effort but most effort long term.

**Drupal validation per content type**

- ✅ Less reliant on human labor long term (if everything works). 
- ✅ Specifically addresses each use case 
- ⚠️ Requires implementing specific rules for each content type
- ⚠️ Increases complexity of system and creates possibility for regressions / tech debt

**A little bit of both**

- ✅  Most robust solution with redundant human and machine governance
- ⚠️ Most effort (swirt added: most effort upfront, least effort long term)

**Comment by davidmpickett** [comment]
## Problem

The current Editorial Workflow conflates Drafts of unpublished entities with Draft Revisions of published entities into a single state.

![VBA Content model_2023-05-10_01-33-29](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/644cc46d-cef3-4a5b-a047-b43d1e6f55f3)

Therefore granting a Role (e.g. Content Publisher) permission to _Publish a Draft Revision_ of an already published entity (node status = 1) also grants that Role permission to _Change the Node Status_ from 0 to 1.

## Proposal 

### Step 1) 
Create a new Workflow (Editorial Workflow 2.0) that splits the Draft state into two separate states. The separation is the important part of the proposal, but naming these states so they are easily understood by editors is also important. Here are some possible names for the two states

**Draft Revision of Unpublished Entity**
- Draft
- Unpublished Draft

**Draft Revision of Published Entity**
- Published with Saved Edits
- Revision
- Published with Draft Revision

### Step 2) 
Set up the Workflow Transitions something like this:

**Approve**
* From: In review
* To: Approved

**Archive**
* From: Draft, In review, Approved, Published, Published with Saved Edits 
* To: Archived

**Edit**
* From: Draft, In review, Archived 
* To: Draft

**Save your changes without publishing them**
* From: Published
* To: Published with Saved Edits

**Publish**
* From: Draft, In review, Approved
* To: Published 

**Publish Revision**
* From: Published, Published with Saved Edits
* To: Published 

**Restore from Archive**
* From: Archived 
* To: Published 

**Review**
* From: Draft, In review 
* To: In review 

**Diagram**
 ```mermaid
flowchart LR
    A(Draft) 
    B(In review)
    C(Approved)
    D(Published)
    E(Archived)
    F(Published with Saved Edits)
    A -->|Edit| A
    A -->|Review| B
    B -->|Review| B
    B -->|Approve| C
    C -->|Publish| D
    D -->|Archive| E
    E -->|Restore from Archive| D
    B -->|Edit| A
    D -->|Save your changes without publishing them| F
    E -->|Edit| A
    A -->|Publish| D
    B -->|Publish| D
    D -->|Publish Revision| D
    F -->|Publish Revision| D
    E -->|Restore from Archive| D
    A -->|Archive| E
    B -->|Archive| E
    C -->|Archive| E
    F -->|Archive| E
 ```
 
 ### Step 3)
Assign some newly created entities (VBA content types and the VA Benefit Taxonomy are prime candidates) to use this workflow so we can find any bugs before applying more broadly.

This new workflow paradigm might need a couple different variants. A Restrictive Editorial Workflow 2.0 might prevent Content Publishers from Changing the Node Status (Publish, Archive, Restore) on sensitive entities like VBA facilities. A permissive Editorial Workflow 2.0 might be mostly identical with respect to the permissions for Content Moderation Roles as our current Editorial Workflow.

**Comment by swirtSJW** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/1561f137-a9e8-464c-9653-9b9d2a8552ad)

I think this is going to create more confusion than it resolves because it is marrying two things in odd ways.
Revisions are not aware of the status of the node, only the node is.   This naming  is making the revision state seem like it is aware of the the state of the node, when it is not.  It still conflates things as much as our current method, but now makes them even more deceptive. Looking at the revision log, imagine what this would look like.    ( I am working on a mockup but wanted to save this  so I don't lose it)

**Comment by swirtSJW** [comment]
Naming things is hard, and crucial at the same time.   Here are the issues with the list of names of states proposed so far.

**Draft Revision of Unpublished Entity**

**Draft** - This it the most accurate, however this is already used and understood by hundreds of existing editors a certain way.  Using an existing name to largely mean something marinally different means we have to overcome the bias already taught for this revision state.
**Unpublished Draft** - This is the most accurate of the three.  However unpublished also sounds like a reversal, a past tense verb/action.  Unpublished does not carry quite the same meaning as 'not published'  Again slightly problematic because it is marrying the state of a revision with the status of the node when those two things are not directly connected.  When I pull up a revision in the code.  I can not tell what the status of the node was for that revision, I can only tell whether the revision I have is the most recent, the "default revision"  (meaning it is tied to the current state of the node), or neither.
**Draft Revision of Published Entity** - This one is the most problematic for two reasons.  It seemingly contradicts itself with both draft and published.  It also uses the word "entity" which we have not trained any of the editors on.  It is a drupal-ism that is largely meaningless to all be devs and even then is murky, because ALL things in Drupal are Entities.  For most of our editors we have avoided the words entity.  It [only appears twice in our KBs](https://prod.cms.va.gov/help/search?keyword=entity) and they are more advanced topics   Some of the more savvy editors know the word node, to mean a page.  It also seems at odds with the heading this is listed under "Draft Revision of Unpublished Entity".  

**Published with Saved Edits**
**Revision** -  Every saved instance of a node or term is a revision.  Using this term here to denote a specific state makes it hard to understand its broader meaning within Drupal.  Especially when seeing it someplace like this
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a2f1ed70-8332-49ca-9f93-efb3c42c7fca)

**Published with Draft Revision** - Similar to "Draft Revision of Published Entity" it is slightly at odds with itself.  It is calling out two common states in one name and is tying node status and state together.


The premise I started with still applies, naming things is hard.  Just because what is being proposed is problematic does not mean we can't keep at it and come up with better names.  Here are some principles to keep in mind (in no particular order):

1. Avoid misleading in an attempt to simplify.  It gets in the way of actual understanding.
2. If something is going to be different, avoid naming it the same as something else people already know elsewhere in the system.  The only thing harder than learning, is undoing what is learned and re-learning ex: why so few people survive taking quantum mechanics courses.  
3. Transitions should be verbs.
4. States should be nouns or at least adjectives.  (we might have been better off with hidden and visible rather than archived and published, and it may have fit with our Content API approach more than our pages on the internet approach.)

**Comment by swirtSJW** [comment]
This transition is interesting
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/865bd2ea-7478-414c-893f-cd0f5a6177a2)

Using a transition that happens to be the same name as the tab they click on to do this action seems confusing.  Why would they click on the edit tab, make their changes and then choose a transition of edit. They have already done the editing.  What they really want is to either save it with any other allowed transition.

**Comment by davidmpickett** [comment]
> This transition is interesting ![image](https://user-images.githubusercontent.com/5752113/237567704-865bd2ea-7478-414c-893f-cd0f5a6177a2.png)
> 
> Using a transition that happens to be the same name as the tab they click on to do this action seems confusing. Why would they click on the edit tab, make their changes and then choose a transition of edit. They have already done the editing. What they really want is to either save it with any other allowed transition.

To be clear. Edit is the current name of this Transition in [our current Workflow](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/content-governance/content-moderation-roles#workflow-transitions). The only change I'm proposing is removing Published from the From States.

**Comment by davidmpickett** [comment]
> Revisions are not aware of the status of the node, only the node is

Is the purpose of a Workflow State to describe the state of the Node or the state of a Revision? Do editors actually understand this distinction?

How is the current paradigm of Workflow States being listed in a sequential order in the Content Filter creating confusion about whether Draft means not Published?
![Screen Shot 2023-05-11 at 5 37 10 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/69712edf-dfe6-4a4c-abd2-a8c76b7c33b4)

Those are all provocations, but the actual question I have is:
**How might we** separate the permissions of _Changing Node Status_ from _Publishing a Revision_ which are both currently encapsulated in Draft --[Publish]--> Published

**Comment by davidmpickett** [comment]
@swirtSJW see revised top comment and review/add

**Comment by swirtSJW** [comment]
Sorry.  I have discussed option C many time, but neglected to add it here.
### Option C
The problem we are trying to prevent is initial publish due to conditions of content (services assigned or not)  This is traditionally (in Drupal land) a content condition that is better handled by "entity validation".    Entity validation is were set content conditions that must be met in order for something to happen.  Usually the content conditions  are evaluated at node save and the save is prevented if the conditions are not appropriate.  

A simple example is a required field.  If you try to save a node with a required field, saving is not possible.

We can not employ a typical required field scenario here because there are no services fields on the facility.  The connections to the service are made on the service to the facility by entity reference.   But this can still be done with entity validation.   This model is extensible to any of the facility types that would require it (so far only VAMC and VetCenters, but soon VBA.)

This kind of validation (either through [Rules](https://www.drupal.org/project/rules), or custom code) would prevent content_publisher from doing bad things as well as content_admins and true admins.  It is the most protective of Veteran's having a bad experience.

If there is need to also have a human involved in the checks and balances then there are several options.  As we scale to ~3,000 facilities (not all of which will need this treatment) I suggest not leaning too heavily on the human check and balances.

**Comment by davidmpickett** [comment]
Closing this ticket as duplicate. The [workflow spike](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14529) provided a clear path forward for having permissions vary by content type. If the [experimental request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/sitewide/facilities/multiple-workflows.md) gets shut down by CMS then we can create a new ticket about a path forward. Nothing in this ticket that hasn't been stated better elsewhere
