### ISSUE TITLE
Process to keep CMS and Design system in sync

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12968]
## Description

As we work towards getting the CMS inline with the Design System, we want to ensure that it remains in sync as work with other teams continues. We need to create a clear process for everyone to follow to ensure that the Design System is being followed when updates to the CMS are being made.

## Acceptance Criteria
- [x] Create process and incorporate into collab cycle for all teams to use when working in the CMS
- [x] Document the process
- [x] Socialize the process to a teams

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by BlakeOrgan** [comment]
The process to keep the Design System and the CMS in line is addressed as part of the [Solutions & Action Items section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/Post-Mortems/Design/2023/Design-System-Post-Mortem.md#solutions--action-items) of the Design System Post-mortem. Confluence documentation has also been updated in order to reflect some of the initial process ideas stated  as part of the Solutions & Action Items section.

It has been socialized in [this slack message](https://dsva.slack.com/archives/CT4GZBM8F/p1680032623655729).
