### ISSUE TITLE
Add more details to CMS Collab Cycle "kickoff" step

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-cms#12963]
## Description
As part of the ongoing work to improve the CMS Collab Cycle/Flow for clarity and understanding, we need to update the documentation on the Confluence page with additional helpful information. Providing clear and specific expectations at each step will enable VFS team members to feel prepared and ready to collaborate with the CMS team. 

Information to potentially provide: 

- Who to invite to the meeting on their team and ours
- Who needs to schedule the meeting on their team
- What do they need to bring to the meeting
- What will happen during the meeting
- How will feedback from the meeting be given
- What are the next steps after the meeting

## Acceptance Criteria
- [ ] Socialize information
- [ ] New information is reviewed and opened to feedback from Sitewide team members
- [ ] Additional information is added to the Confluence page

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
@joagnitti Removed your assignment from this since you're booked for many sprints ahead. If this is something you'd like to continue, let's figure out how to make that happen! For now, I'm going to help drive the (re)draft of this and then we can continue to determine where the iterations points are.

**Comment by joagnitti** [comment]
@productmike Oh yeah, go for it! Feel free to take me off of all the collab cycle tickets I made (or even just delete 'em). Consider the baton officially passed!

**Comment by BerniXiongA6** [comment]
**Note for Product and Delivery:** We can keep this estimate of "5" on this Product ticket for now, let's regroup when we're all back so we can chat about how to size our Product and Delivery tickets without skewing the scrum team's sprint points. Thanks all! @EWashb @productmike

**Comment by EWashb** [comment]
Moving this to sprint 88 so we don't overcommit on a goal

**Comment by laflannery** [comment]
During planning we talked with Erika and we want to refine this a bit more before putting into a sprint, really define the ACs and make sure we know what the end goal of this is

**Comment by EWashb** [comment]
This is still valid. We want to flesh out information as much as we can so that teams understand how to interact with CMS.

**Comment by BlakeOrgan** [comment]
@EWashb @BerniXiongA6 @maortiz-27-80 

Do y'all think that we can close this ticket out since this seems very similar to the work completed in tickets [#15705](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15705) and [#15706](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15706)?
