### ISSUE TITLE
SPIKE: Learn about vets-api in order to prep for facility locator design updates 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12984]
### Background
We are prioritizing several updates to facility locator, primarily related to filtering capabilities. After an initial review of the proposed designs, Ryan (dev on facilities) mentioned that the data from lighthouse first encounters a middle layer known as the vets-api, this api is in ruby and in general the facilities team needs to gather more information about its function and architecture in order to be better prepared for the upcoming facility locator updates AND to identify risks that may be associated with the proposed designs 

link to designs: https://www.sketch.com/s/d5e5c924-e8c0-47af-b3e4-994c335d6f31

#### User Stories we are designing a solution to 
- As a Veteran, I want to see what Providers have completed Provider Core Training
- As a Veteran, I want to learn about Provider Core Training and what it means
- As a Veteran, I want to filter my search in the Facility Locator to return only providers who have received the Provider Core Training
- As a Veteran, I want to have more filtering capabilities, in part made possible after the facilities v1 migration
- As a Veteran, I want to have a filtering experience for Service type that is usable and consistent whether I am selecting from 5 items or 800
- As a Veteran, I want to be able to know what VA facilities are in a given state
- As a Veteran, I want to be able to know what VA facilities of a certain type are in a given state (e.g. Medical, Vet Center, Benefits, Cemetery)
- As a Facilities Product Manager, I want to be able to add several new filters to facility locator without needing to go through another design review (there should be a new design pattern that considers scalability of number of filters)
- As a Veteran, I want the filter titles to make sense to me so that I can more easily navigate the facility locator tool (background: the service type filter doesn't make sense for every use case of facility type selected, work with the content IA accessibility team to find better terms for some of the groupings, see images attached below for reference)

### Acceptance Criteria 
- [x] I expect that the below AC are completed within a timebox that reflects the size on this card
- [x] I expect time is spent learning about Ruby on Rails in general, these learnings should be documented in some way 
- [x] I expect time is spent learning about the vets-api specifically, these learnings should be documented in some way 
- [x] I expect the learnings are communicated to product and other devs

**Comment by omahane** [comment]
I'd like to better understand how vets-api and lighthouse-facilities are integrated.

**Comment by kmariepat-cityfriends** [comment]
add review of this to the AC:  https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/engineering,

**Comment by kmariepat-cityfriends** [comment]
add review of this to the AC:  https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/engineering,

**Comment by maxx1128** [comment]
Overall the documentation gave lots of good details and helped a lot in getting `vets-api` setup. This is constructive feedback I have for making the process easier to follow, especially for front-end devs like me with less back-end experience.

* I set up the app both with the full native approach, and the [hybrid (Native and Docker) approach](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/hybrid.md). In terms of easy and local maintainence, I would recommend the hybrid setup for any Macbook developers, especially those focused on the front-end.
* I also found the organization of the documentation for the base setup confusing, since it was a lot of jumping between different files. Having either a single markdown file with all needed steps laid out, or one file that links to all pages and sections linked in the correct order, could make them easier to follow.
* `rvm` is recommended in the docs but should include more details on how to set it up and manage the Ruby version.
  1. Install [Homebrew](https://brew.sh/) as an OS package manager (if not already)
  2. Install `rvm` with `brew install rvm`. This could be a whole.
  3. In the `vets-api` repo, check the ruby version in `.ruby-version`. Use that number to install the needed Ruby version with the command `rvm install <version_number>`. This could also be a while.
  4. Run `rvm use` to confirm that the correct version is being used.
  5. After the correct version is used, run `gem install bundler` and `bundle install` to ensure all gems are installed for the current version of Ruby.
  6. Steps 3-5 must be repeated if the repo's Ruby version is updated later on.
* It could be more clear about the steps needed to get the hybrid setup running
  * One terminal window should run the Docker command for the database side.
  * Once that is properly up and running, a separate window is needed for the app side. It needs to run `bin/setup` one time, then the Foreman command is needed.
  * The API should be up and running if both terminal windows are successfully running. An accurate check is seeing if [the local flipper page](http://localhost:3000/flipper/features) is active.
* The `pdftk` dependency had to be installed earlier than the listed steps, since not having it was throwing dependency errors for me. I think installing it after I had the proper Ruby version set up would have avoided this.
* This is just a suggestion, but it could be easier to save the `foreman start -m all=1,clamd=0,freshclam=0` command into a separate command. For example, putting it in `bin/up` so that could be referenced as a shorthand.

**Comment by jilladams** [comment]
@maxx1128 what are the action items to get those suggested changes done? If I understand correctly, the changes would all need to be made to https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/hybrid.md? We can consider ourselves open source contributors here and put up a PR to that doc that the owners can merge if they jive with the suggested changes. 

I know that's not an AC here, but: what would it take to contribute there? Shouldn't block other sprint work, but if we can contribute in this way, we should whenever we can.

**Comment by maxx1128** [comment]
@jilladams the changes would mostly be on the native and hybrid README files. I could open a few pull requests, one for each documentation change, so one specific documentation change won't block any of the others.

The last suggestion I have would be a pill request for the code base. But that's small and something I would still be able to test locally.

**Comment by kmariepat-cityfriends** [comment]
Overall this card was meant to be a timboxed discovery. That timebox is exhausted and the discovery that resulted is documented on the card, all of the below AC have been achieved. I  will close this and spin up a card that documents what Max is recommending as next steps 

@kmariepat-cityfriends to connect with @maxx1128 to refine out a next steps card 

- I expect that the below AC are completed within a timebox that reflects the size on this card
- I expect time is spent learning about Ruby on Rails in general, these learnings should be documented in some way
- I expect time is spent learning about the vets-api specifically, these learnings should be documented in some way
