### ISSUE TITLE
Spike/Discovery: Healthcare widgets (e.g. Refill Prescription) fail gracefully if API errors or hangs

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13062]
### User story

**AS A** Veteran
**I WANT** the e.g. [Refill Prescription widget](https://www.va.gov/health-care/refill-track-prescriptions/) to fail gracefully (i.e., NOT hang/spin infinitely) when an API call fails
**SO THAT** I can always do the health care related task I came to VAgov for.

[List of all 5 "cerner widgets."](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/Cerner-Support)

### Engineering notes / background

In early March 2023 a MHV endpoint was removed unexpectedly. The result was [BUG], where logged-in users visiting pages with Cerner widgets saw infinite spinners instead of buttons linking to MHV or My VA Health.

We want to engineer the widgets so that Veterans can take any step possible in the case of an API failure.

Focus on the [Refill Prescription widget](https://www.va.gov/health-care/refill-track-prescriptions/) as representative of other "Cerner" widgets.

### Quality / testing notes

You will need a test user to authenticate for testing/evaluation. See [docs for TUD](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-user-dashboard-guide) (Test User Database).

## Acceptance criteria
- [x] studied code that calls APIs 
- [ ] documented why widget hangs when an API call fails
- [ ] documented what API endpoints are called by widget
- [ ] documented what UI/UX components currently depend on each API call (e.g., what link/button(s) would be missing hrefs)
- [ ] consulted with product and/or design on what UI elements could be allowed to work when each API call fails
- [ ] Created flow diagram that shows the sequence of API calls and how they are used by the UX flow (new AC)
- [ ] ticket for implementation is accurate and ready: #15205

**Comment by chriskim2311** [comment]
# Spike Results

##  Studied code that calls APIs
The call that was causing the widget to fail actually occurred in the unauthenticated cta-widget component. This component is used for accounts that are not associated with any Cerner facilities.

##  Documented why widget hangs when an API call fails
The reason why the widget hangs when the API fails was that the call never completed successfully. In the componentDidUpdate it continually called the API since the result was never successful. 

##  Documented what API endpoints are called by widget
There is one API endpoint for mhv_accounts for the non-cerner CTA widget and there is an API call in the Cerner CTA widget that gets facility data.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckI4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--afe2c81e618856741a1fbc027ef38b2a556514d3/VA_Prescription_Refill_And_Tracking___Veterans_Affairs.png)

##  Documented what UI/UX components currently depend on each API call (e.g., what link/button(s) would be missing hrefs)
For accounts without Cerner facilities there is one API for mhv_account. With accounts that are associated with Cerner facilities they will rely on the facilities API screenshot above. 

## Consulted with product and/or design on what UI elements could be allowed to work when each API call fails
For Cerner facility accounts I don't think there can be a way to proceed with CTAs without the necessary information. We do account for errors in the FE for the facility details API. And with non-Cerner accounts we can add the same kind of FE error message for MHV_account API.  

## Ticket for implementation written
Add FE API error check and render error message if the API fails for non-cerner CTA widget.

**Comment by wesrowe** [comment]
@chriskim2311, under "ticket for implementation written" heading – did that imply you have written the ticket? (if so, where?) 

I'm having a little trouble grokking the notes, so hoped that the ticket would help me understand what you see as next step.

**Comment by chriskim2311** [comment]
@wesrowe Sorry I did not write the ticket yet. But I have completed it now thanks! https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15205

**Comment by wesrowe** [comment]
@chriskim2311, reading the follow-up ticket raised a couple questions for me on your notes here:

1. Does the widget _already_ have an anti-hang alert set for one of the EHR systems? (i.e., MHV or Cerner APIs)
2. Did you find or would you suggest a time-based pattern? e.g., force the MHV/Cerner call to timeout after X seconds?
3

**Comment by wesrowe** [comment]
Since it's EOD at end of sprint I'm open to closing this ticket. We can keep discussing post-close.

**Comment by chriskim2311** [comment]
@wesrowe I am open to closing this ticket. Sorry missed your message yesterday. The Cerner widget has error catching for the facilities detail API. It will not display the widget unless the facilities location data is returned from the Cerner facilities API.
In terms of a time-based API timeout, we will be able to catch the timeout errors in my suggested code implementation.

**Comment by wesrowe** [comment]
@chriskim2311, would you mind answering my two questions with numbers labeling? before refinement tomorrow ideally.

**Comment by chriskim2311** [comment]
This will carry over to next sprint I was working on higher priority tickets

**Comment by jilladams** [comment]
Discussed the results here and the new ticket. Closing.
