### ISSUE TITLE
Spike: UX discovery of permissions (dev support)

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13110]
## Description
Currently, within the CMS permissions schema, roles cannot have different permissions within different sections. This is an issue as new products that we want to bring into the CMS need to have this type of flexibility. How might we allow for users assigned to different sections to have different roles assigned to them for each of the sections they have access to? For example how might we enable a user to be a Content Editor for Vet Centers but a Content Reviewer in Benefits? See #13442 for additional guidance as well.

We need to investigate the technical piece of what would need to be done in order to make this change to permissions. We would be looking at access (or sections) as well as roles/permissions.

Artifact?
- Mural of permissions and access how they currently exist to easily show and explain how this is set up
- How folks access areas and do things based on these permissions

Make sure we are talking about permissions and access together!

Breakdown of role by access and then permission ie. Content editor can access this section and have these permissions

## Acceptance Criteria
- [x] Meet with UX to discuss permission spreadsheet and CMS UX.
- [x] Review with artifacts from Dave Pickett. Discuss current state of permissions.
- [x] Documentation of findings to make this change (can roles have different permissions within different sections?)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
Roles cannot have different permissions in different sections

**Comment by TroyA6** [comment]
@laflannery the existing list of permissions (https://prod.cms.va.gov/admin/people/permissions ) is very lengthy and very detailed...

**Comment by laflannery** [comment]
Combination of Engineering and UX together

**Comment by ElijahLynn** [comment]
> @laflannery the existing list of permissions ([prod.cms.va.gov/admin/people/permissions](https://prod.cms.va.gov/admin/people/permissions) ) is very lengthy and very detailed...

Truth, I wonder if there is a Drupally way to improve the UX of that permissions way through a contrib module for sites with a ton of permissions. This could be another story too.

**Comment by davidmpickett** [comment]
Here's a ticket that @swirtSJW and I will be working through for Facilities this sprint that may be a helpful real-world use case of how we map product/stakeholder needs to our current Drupal environment
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13272

**Comment by davidmpickett** [comment]
FYI -I just dug into the three Content Moderations roles and how they relate to workflow states & transitions Here's a mural where I mapped out the information I dug out of the depths of Drupal: https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1682544407635

I also took a pass at updating the relevant product documentation on GitHub (and mermaid-ified the workflow diagram) since it had never been updated beyond "[WIP]"
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-governance/content-moderation-roles/README.md

**Comment by davidmpickett** [comment]
Here's a screencap of the Editorial Workflow interface where all the Workflow States and Transitions are defined.
![screencapture-staging-cms-va-gov-admin-config-workflow-workflows-manage-editorial-2023-04-26-18_36_40](https://user-images.githubusercontent.com/51967950/234724818-ba01f380-04d9-4f94-8f57-baf165d3f69b.png)

Right now this is the only Workflow in the CMS and it applies to pretty much all content. If we wanted to have different workflows that applied to different content/entity types, that is possible. Would be a matter of defining that and some roles to correspond to the transitions. That would be an easy way to split out permissions for content types that already align with the section hierarchy. A VAMC Editorial Workflow could have VAMC roles overseeing VAMC content types and a Vet Center Workflow could have Vet Center Content Moderations  roles overseeing Vet Center content types. 

But what about shared content types like Events, Q&As, Leadership lists? Well I think that's where it gets messy.

The tricky bit seems to be that Sections are a totally different permissions paradigm than Workflows & Roles. They come from the [Workbench Access module](https://www.drupal.org/project/workbench_access) and so the technical discovery might need to dig into what we can do within the confines of that module (or contribute) if we want Sections to play nicely with Workflows & Roles. 

@swirtSJW lemme know if I'm way off-base here

**Comment by davidmpickett** [comment]
An old epic that might have some useful ideas/concepts https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1405

**Comment by jilladams** [comment]
Note: https://dsva.slack.com/archives/C0FQSS30V/p1683689426172249

**Comment by BlakeOrgan** [comment]
# Problem:

How might we allow for a user assigned to multiple sections to have different roles assigned to them for each of those sections? The following is an explanation of the current state of Permissions, Roles, and Sections and how they all work together.

# Permissions:

This is the most granular piece of the puzzle. There are currently 1541 individual permissions that enable the CMS to provide all of its functionality. Permissions are added to the CMS through Modules and each permission is tied to a specific module that was installed. Permissions are NOT the same thing as roles, although they are closely related.  
  
You can view the full csv of permissions and their associated modules using this file: [permissions.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11335770/permissions.csv)

**Analogy: Stars**  
**Think of permissions as all of the stars in the sky that make up the Drupal Universe. When you look up at the sky, each star is an individual permission that is one part of the bigger picture.**

# Roles:

In the simplest terms, Roles are groupings of Permissions that are created by an Administrator. Each role contains a set of permissions based on the different needs of the user groups that can access CMS. While some roles have access to more permissions than other roles, all roles must be assigned to each user by an Administrator based on the needs of that individual user.

  
In the CMS, we have 15 different roles that can be assigned to a user.

1.  **Content API Consumer**
    *   Used by GraphQL to access content via Content API. Should not be given to humans.
2.  **Content creator - Benefits hubs**
    *   Can create benefits hub content (hub landing pages and detail pages).
    *   Users with this role should also be editors, reviewers, or publishers.
3.  **Content creator - Resources and support**
    *   Can create content types related to resources and support products
4.  **Content creator - Outreach Hub**
    *   Can create content types related to Outreach Hub
5.  **Content creator - VAMC**
    *   Can create content types related to VAMC (except for the parent "VAMC" and "VAMC Operating Status" content types, which are created by content admins).
    *   Users with this role should also be editors, reviewers, or publishers.
6.  **Content creator - Vet Center**
    *   Can create Vet Center Health Services and CAPs.
7.  **Content editor**
    *   Can create and edit content, but can't review or publish it.
8.  **Content reviewer**
    *   Can approve content changes for publishing, but can't publish it.
9.  **Content publisher**
    *   Can publish content.
10.  **Content admin**
    *   For members of the Global UX team, and other content users who have permissions beyond those of Content Publisher.
11.  **Redirect admin**
    *   Can create and edit redirects.
12.  **CMS account admin**
    *   Can create and manage users, roles, and access to sections of content.
13.  **Administrator**
    *   Has all permissions.
14.  **Homepage Manager**
    *   Can create home page related components (news and benefit promo blocks; news spotlight and hero entityqueues).
15.  **Translation manager**

### **Analogy: Constellations**

**Think of Roles as constellations in the night sky. While admins can look at each star individually, it makes more sense to create groupings based on the unique needs of each of the user groups that have access to the CMS. Drupal users that have the Administrator role are like the gods of the Drupal universe and can create new groupings as new needs arise.**

# Sections:

While assigning a user a set of permissions in the form of a role is an additive process, (meaning that assigning users to roles allows them a certain set of permissions or functionality within the CMS), assigning users to sections is a subtractive process. This means that assigning a user to a section limits that user to only make edits within the section of the CMS that they have been assigned to.

For user groups that work at a facility such as a VAMC or a Vet Center (which make up the vast majority of our editor base), the section that they are assigned to is most likely their particular facility so that those editors can only make edits for the facility that they work at. While the majority of sections within the CMS align to the facility structure, there are also user groups that do not work at VA facilities that are assigned to sections within the CMS. For example, the Sitewide Content Team is a user group made up of contractors that work on behalf of the VA that make edits to VA.gov.

Sections are set up in a hierarchical structure. If an admin assigns a user to a top level section, that user will also have access to edit all of the individual sections that are a part of the top level section. If a user is assigned a bottom level section (for example an individual VAMC Facility, Vet Center, or Benefit Office) that user will only have access to edit their individual section and no other sections that are higher in the hierarchy.

### **Analogy: Telescope**

**With the current analogy, think of assigning a user a section as providing them with a telescope. While there are lots of different constellations and parts of the sky that a user can look at, they can only point their telescope at one constellation based on their role.**

**In the current implementation of the CMS, if we have a user assigned to multiple sections, they are currently only able to have the same roles assigned to both sections. Users need to be able have different roles for each of their sections.**

**For this use case, we will have a user with two telescopes, but they are currently only able to point both of their telescopes at one constellation because all roles assigned apply to all sections assigned. Users need each telescope to be able to look at a different constellation.**

The structure of sections is as follows:

## VACO

### Veterans Experience Office

*   Outreach Hub
*   VEO Campaign Landing Pages

### Office of Public and Intergovernmental Affairs

*   OPIA Alerts and Promo banners
*   OPIA Campaign Landing Pages
*   OPIA Home Page

## NCA

*   NCA facilities
*   NCA Resources and support
*   Burials and memorials benefits hub

## VBA

### VBA Campaign Landing Pages

### VBA facilities (58 Total Facilities)

*   Continental (12 Individual Facilities)
*   Northeast (20 Individual Facilities)
*   Pacific (13 Individual Facilities)
*   Southeast (13 Individual Facilities)

### VBA Resources and support

### VBA Benefits Hubs

*   Decision reviews
*   Disability benefits hub
*   Pension benefits hub
*   Life insurance benefits hub
*   Housing assistance benefits hub
*   Education benefits hub
*   Careers and employment benefits hub

## VHA

### Health care benefits hub

### VHA Campaign Landing Pages

### VHA Resources and support

### Centralized content: VAMC

### VAMC facilities (139 Total Facilities)

*   VISN 1 (8 Individual Facilities)
*   VISN 2 (9 Individual Facilities)
*   VISN 4 (9 Individual Facilities)
*   VISN 5 (6 Individual Facilities)
*   VISN 6 (7 Individual Facilities)
*   VISN 7 (8 Individual Facilities)
*   VISN 8 (7 Individual Facilities)
*   VISN 9 (5 Individual Facilities)
*   VISN 10 (11 Individual Facilities)
*   VISN 12 (8 Individual Facilities)
*   VISN 15 (7 Individual Facilities)
*   VISN 16 (8 Individual Facilities)
*   VISN 17 (7 Individual Facilities)
*   VISN 19 (8 Individual Facilities)
*   VISN 20 (8 Individual Facilities)
*   VISN 21 (7 Individual Facilities)
*   VISN 22 (8 Individual Facilities)
*   VISN 23 (8 Individual Facilities)

### Vet Centers (303 Total Facilities)

*   District 1 (81 Individual Facilities)
*   District 2 (49 Individual Facilities)
*   District 3 (55 Individual Facilities)
*   District 4 (47 Individual Facilities)
*   District 5 (71 Individual Facilities)

## OCTO

### Services taxonomy

### Sitewide content team

*   Campaign Landing Pages
*   Header and footer
*   Resources and support
*   Root pages
*   Forms
*   Records benefits hub

### VA.gov CMS Knowledge Base

# Next Steps

After talking with @edmund-dunn it was decided that some technical discovery is needed in order to best decide how to achieve the change that we are needing. Some initial ideas he discussed were...

*   Creating more granular roles that would need an associated section assigned to users
*   Extending Workbench Access
*   Custom code
