### ISSUE TITLE
Design patterns needed for alt text prototype

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13114]
## Description
We are looking to create an update to the editorial interface for the alt text field for uploaded images. The update will focus on 3 key improvements within the alt text field:

- Reducing the use of filename 
- Reducing the use of redundant phrases (i.e. "image of", "photo of", etc.)
- Limiting the length of the alt text content

These updates/improvements should be implemented with existing patterns within the design system however we need to determine if patterns exists for all of these scenarios. We are looking for existing patterns for:

- Character limits
  - We want to implement a Yellow/Red pattern for limiting the allowable character count in the alt text field
- Warning pattern
  - We want to display a warning when a redundant text pattern is detected in the alt text field. The text can still be entered and saved but the warning should discouraged editors from using this pattern.
- Field validation error pattern
  - When a node form is saved and an error is detected in a form field, and error is displayed. What error patterns exists (inline vs. node errors)?

## Acceptance Criteria
- [x] Document design patterns that exists and would be used for each scenario above
- [x] Document scenarios that are needed that do not have an existing pattern in the Design System 

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by BlakeOrgan** [comment]
Context: We are attempting to guide CMS editors to provide better alt text in the following ways when uploading images on this page. https://prod.cms.va.gov/media/add/image

# **Character limit patterns**

**We want to implement a Yellow/Red pattern for limiting the allowable character count in the alt text field.**

*   ✅ The current implementation of this pattern in the CMS can be seen in the “Description” text input on the [“Add Image” page](https://prod.cms.va.gov/media/add/image). We can use this same exact pattern on the alt text input field for images.
    *   Yellow text box outline  = Warning. You are 5 characters or less away from the character limit.
    *   Red text box outline = You are over the character limit. You can continue to type (aka, there is a “soft limit”), but you will get an error if you try to save and you won't be able to save unless you fix the error.
*   🚧 While we have an existing pattern in the CMS that achieves the need for this request to add a character counter to the alt text input field, the pattern in the CMS should ideally reflect [what exists in the Figma Design System](https://www.figma.com/file/LAlrfgqFJgCV9EIq7eyDcw/Simplified-Design-System?node-id=106%3A133&t=PhEus1p4B4j9kzM7-1). It currently does not. The following things would need to be updated in order for the CMS to reflect what is in the Figma design system. 
    *   Bold number for the character counter
    *   Should be formatted “**#** characters remaining” not “Characters Remaining: #”

# **Warning pattern**

**We want to display a warning when a redundant text pattern is detected in the alt text field. The text can still be entered and saved but the warning should discourage editors from using this pattern.**

*   ❌ This is a scenario that does not have an existing pattern in the Design System or within the CMS because no pattern has been established for showing either warning or error messages prior to a save attempt. A pattern would need to be created before this could be implemented as described above.
*   🧠 While there are no current warning or error message patterns that exist prior to a save attempt, there are two patterns that exist that would allow us to show either a warning or an error if users use a redundant text pattern such as "image of" or "photo of", but only after a save or save attempt has been made.
*   **Option 1 - Use Existing Warning Pattern**
    *   If we want to give them a warning, we could use the following pattern (see screenshot) that appears at the top of edit forms and the top of node view. However, we would be relying on the user to go back and make the correction after they have already made the mistake instead of proactively preventing them from making the mistake in the first place.

![](https://user-images.githubusercontent.com/113871419/230217741-38d2d401-9614-4b30-b2ac-26a43724ab24.png)

*   **Option 2 - Use Existing Error Pattern**
    *   If we want to instead give them an error, we could use the existing error pattern that has a description of what they will need to fix in order for them to save. See screenshot. While I think that providing a warning/error message prior to save as the original request is describing would be the best UX overall, if we wanted to use an existing pattern, this is the pattern that I would recommend.  This is because we know that it is bad practice to use redundant phrases like "image of" or "photo of" in alt text, so we should prevent them from doing this in the first place rather than allowing them to do it and notifying them of it after the fact, like option 1 would require.

![](https://user-images.githubusercontent.com/113871419/230220171-39aac237-d737-48ef-ba84-2c4a469112e2.png)

# **Field validation error pattern**

**When a node form is saved and an error is detected in a form field, and error is displayed. What error patterns exists (inline vs. node errors)?**

*   The screenshot above shows the existing error patterns that should be used when errors are found.
    *   ✅ One error at the top of the screen that summarizes the fields where errors are found.
        *   Number of errors noted
        *   Links to the field level errors found are noted.
    *   ✅ Each individual error is clearly indicated by a red outline around the input field along with a description of the error found and what needs to be resolved is explained in red text.
    *   🚧 There are currently some inconsistencies in how these errors are displayed in the CMS. This is likely because this pattern hasn't been fully defined in the Figma design system.
        *   There are differences in the text sizes and boldness of the error descriptions. Note the description error vs the image and section errors in the image above. There are also inconsistencies between the color of the red outlines used around the input fields.
        *   Error handling on both the alt text field and the "Name" field is completely different from how text field errors are handled in the examples above. For the alt text field and name field, you get a tooltip that goes away after a couple of seconds. See the screenshot below. This would need to be changed to match the patterns that we currently have in place for the other field level errors that exist on the page.

![](https://user-images.githubusercontent.com/113871419/230225045-da277c0f-220f-4533-bd6f-5d22befbb146.png)
