### ISSUE TITLE
Review of translation management documentation

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13121]
## Description
We have created documentation of the current state of translation management (#13097). To determine if this documentation is useful and clear, it is recommended that a UX team member review this documentation.

Documentation is here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/translation.md

## Acceptance Criteria
- [x] Documents are reviewed by UX for clarity and understandability
- [x] Provide recommendations/feedback for improvements 
- [x] Send to PO for review
- [x] Work with PO to schedule meeting with Content team: meeting intent to walk them through current state and documentation

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ElijahLynn** [comment]
Per refinement: Dawn is likely going to schedule the meeting.

**Comment by joagnitti** [comment]
UX checker chiming in. Here are is my feedback on both the documentation and the actual process. Adding as a comment here but let me know if a different delivery method is preferred. 

**Suggestions for documentation**
_(in order of appearance)_
- Does a user have to have a certain permission or access level in order to create a translation? Maybe add that to the intro for clarity and transparency. 
- **Change header:** “Sources” to “Select content for translation.” 
- This step, “In order to translate content, select its checkbox, and then use either the Checkout or Add to Cart functionality” could benefit from a screenshot (or better yet, a gif). I’m not clear on how to do this. Do you check the content item and then go back up and hit “add to cart”, or is there a button beneath this that I’m not seeing? This step is the one I’m most unsure of. 
   - Can you explain the purpose of the [currently titled] “Add to cart” section, and also how it relates to the [currently titled] “Checkout” section? How is a user able to use “either” to translate content? 
- Is it possible to add captions to your images? It will make following along with the steps easier.  
- Do you have a screenshot that illustrates “Suggestions” being added to a job? I’m having trouble understanding what that means. 
- Above the line, “Once you’ve created your job, there will be message that you can download the file with your translation data:” **insert Header:** “Create a translation file”
   - **Get rid of the header**, “Translation via file”
- **Change header:** “Jobs and file import” to “Import a translation file”


**UX suggestions for translation process**
_(in order of appearance)_
- Swap the order of “Checkout” and “Operations” blocks
- The shopping metaphor seems out of place. Do we have flexibility in the field and button labels? If so, I suggest changing the copy from __ to __ like so:
   - “Checkout” → Translation download 
   - “Operations” → Translation queue
        - “Add to cart” button —> Add to queue
- Provide an example of a helpful label within the inline guidance. 
   - So change: “You can provide a label for this job in order to identify it easier later on. Or, leave it empty to use the default one.” to “Give this job a label to easily identify it later (e.g., [Add helpful example here]).”
- What does “Provider” mean in this context? 
   - Maybe change, “The configured provider that will process the translation” to something like “This is the means by which your content will be translated.” (or something more descriptive)
- In the progress bar, what does green indicate? I don’t see it in the “state” legend.
- On the review step, do we need the checkmarks on the right? Maybe instead change the button on the bottom to, “Accept and save translations”

**Comment by BlakeOrgan** [comment]
### Documentation Improvements

- "Adding a label is optional but recommended. It will help you identify the content later." Maybe it would help to provide an example of a good label. Right now I'm not exactly sure what that does or where the label goes.

- "Your job may add items to ‘Suggestions’. It is not recommended to add Suggestions in with a given job, but it is useful for identifying other content that you may want to add to additional jobs." I'm not sure what this means. You might want to go into further detail here.

- "The progress numbers are by segments, rather than words." I'm not sure what this means. What is considered a segment?

- We should probably clarify who is doing the requesting and who is doing the translating in the documentation. Do they have separate views based on their roles?

- A user flow for how this process works would be VERY helpful in digesting how this process works at a glance.

- Provider: file exchange. What does that mean? Go into more detail here.

- Explain the difference between the "Save as completed" and "Save" buttons.

- Explain the difference between the "Validate" and "Validate HTML" buttons

### UI Improvements

- There’s no spacing between any of the dropdowns and buttons in the “Checkout” section of the Sources tab. These should be 8px apart

- Where are the icons that are being used pulled from? Are they part of the design system?

- Once we start to expand to other languages, what’s the plan for how we add them to this table? Will they just be tack onto the end? It’s fine for now since it’s only two languages, but I worry about the table getting overwhelming.

- Blue/yellow/ green pattern for the progress bar. There should be a key in the UI that explains what each of these colors mean.

- On the Jobs tab, the unprocessed and inactive icons are the same. What is the difference between them?

- Use the word "Cancel" rather than "Abort"

- Preview button shouldn't be styled as a link. Also, what are they previewing?








### UX Improvements

- Totally agree with @joagnitti about the shopping metaphor being out of place. We should be using more direct language, and I like what Jo has suggested.

- Right now the help text says "You can provide a label for this job in order to identify it easily later on. Or leave it empty to use the default one." What is the default label? Also the second part isn't a complete sentence.

- Progress column. Not exactly sure what it’s showing the progress of. Is it showing the progress of a file being uploaded? The progress of how much has been manually translated?
