### ISSUE TITLE
Create Lagoon Architecture Documentation draft

### ISSUE THREAD

**Issue by dawnpruitt** [department-of-veterans-affairs/va.gov-cms#13170]
## Description
Ticket #13111 is the architecture diagram.
The architecture documentation will be informed by the architecture diagram and by previous conversations we've had with Amazee.io about how we currently architect our projects around the existing network architecture. Additionally, this will be informed by Lagoon's limitations and verbal agreements to extend Lagoon beyond those limitations. 

```[tasklist]
# ACs
- [x] Lagoon Production Documentation draft describing architecture is created
- [x] Draft provided to PO for review
```
### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by olivereri** [comment]
# Lagoon Documentation

## Architecture and Design
### Requirements
### Assumptions
### Pitfalls

## Local Development
### DevOps Engineer
* Pygmy
* Docker-Compose
* Dockerfiles
### Drupal Engineer
* DDev, no change from current process.

## Deployment Process
### PR Merge to Deployment

## Access
### The Lagoon Dashboard
### Drupal
* SOCKS
* GFE
Mostly no change
### Service Containers 

## Roll Out Plan

**Comment by ndouglas** [comment]
I had this for the deployment flow:


### PR Merge to Deployment on Staging
* A developer merges an approved PR into `main`.
* This triggers GitHub to dispatch a webhook request to Lagoon Core, in the Utility cluster. This event includes the identifier of the latest commit to the `main` branch.
* Lagoon Core receives the request and instructs the Staging Lagoon Remote to build an image based on that commit. 
* The Staging Lagoon Remote instance:
  * builds a new container image containing the version of the codebase corresponding to that commit, including packages and dependencies as cached by Nexus Repository Manager,
  * passes that image to the Harbor instance running alongside the Lagoon Core deployment, 
  * deploys that image internally as a test environment (including pre/post-rollout tasks), 
  * runs the full battery of automated tests against the image, and 
  * informs GitHub of each test's pass/fail status. 

### Deployment on Production
* A scheduled GitHub Actions workflow dispatches a request to Lagoon Core to perform the daily deploy.
* Lagoon Core queries GitHub for the last "passed" commit on `main`; that is, the most recent commit that has been successfully built and has passed the full battery of automated tests.
* Lagoon Core instructs the Production Lagoon Remote to build images corresponding to that commit and promote them into the actual production environment, i.e. serving all traffic to editors
* Production Lagoon Remote requests images corresponding to that commit, which it can find already built in Harbor, and creates a new deployment for those images.
* When the deployment is completed, traffic is redirected to that new deployment and the previous version is removed from service.


Does that match reality/our understanding more-or-less? I didn't want to change what you had, because I'm not completely confident of my understanding.

**Comment by ndouglas** [comment]
I fluffed up some sections that seemed a little terse to me, fixed a couple typos, and fleshed out the sections on Access -- I _think_ I know what you meant here, so I went with it because it seemed like a boring section to write 🙂  If I was completely off the mark then feel free to delet this.

**Comment by olivereri** [comment]
### Deployment on Production
* A Lagoon scheduled [Custom Task](https://docs.lagoon.sh/using-lagoon-advanced/custom-tasks/) triggers a promotion from the Staging environment to Production via curl.
* The promotion workflow determines that last successfully deployed commit from the staging environment.
* Checkout the Git branch `main` in order to load the .lagoon.yml and docker-compose.yml files (Lagoon still needs these in order to fully work).
* Creates all Kubernetes/OpenShift objects for the defined services in docker-compose.yml , but with LAGOON_GIT_BRANCH=mainas environment variable.
* Copy the last successfully deployed Images from the `Staging` environment and uses them (instead of building Images or tagging them from upstream).
* Run all post-rollout tasks like a normal deployment.
