### ISSUE TITLE
Discovery: document architecture and data-load approach for non-VES database solution

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13189]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** PO
**I WANT** a back-up plan for maintaining our own database to power the Income Limits app
**SO THAT** we can evaluate an alternative to using the VES database as our back end.

### Engineering notes / background

This is because we just learned that the VES database is unreachable from local dev environments, potentially making it prohibitively difficult to work with.

Most threshold values could be input each year manually, as there are only 10-20 numbers.

The largest dataset, which would be difficult to manage manually, is the GMT (geographic means test) thresholds that come from HUD. The VES team does this every year, it would be nice to rely on their governance to add new years when data becomes available.

## Acceptance criteria

- [ ] Documented how to leverage Platform's existing database instance(s) in vets-api for Income Limits data _including_:
  - VBA-defined income limits, calculated per number of dependents
  - geographic (zip-based) income limits, calculated per number of dependents
- [ ] Outlined (high-level) options and steps for loading geographic (GMT) data each year from sources:
  - [ ] HUD spreadsheets
  - [ ] VES export or procedure (even possible?)
- [ ] Documented governance and maintenance plan, including data update cadence
- [ ] Met as sub-team to talk through options and framing for decision making including implementation ticket
- [ ] Schedule follow up with DaveC re: next steps

**Comment by dsasser** [comment]
# Overview of vets-api postgresql database solution

The vets-api stack includes a backend database running on PostgreSQL. This solution would leverage this postgresql database. The database can be queried directly in vets-api applications, including in local development environments, without going through a network connection to a remote database. This avoids needing SOCKS access, or a VPN, to connect directly to the database within the application. Many vets-api applications are already utilizing this database, including the VA Form application.

# Development

For initial development, the database tables will be created based on Ruby models defined in the new IncLim vets-api application. The Ruby on Rails (RoR) `db` commands will allow for not only initial creation of the tables, but using migrations, will be able to modify the schema as needed as changes are made to the models. The RoR Active Records ORM provides the utilities for creating and maintaining the database schema.

# Datasets

In order to populate and maintain datasets in the database, both locally and for upper environments, data will need to be imported routinely. Below exists detail regarding each of the known upstream datasets that would need to be added to postgres.

## VA-defined Income Limits Dataset

VA-defined income limits are distributed by [fill in who distributes, and who receives] via email. The emails contain a spreadsheet [screenshot below] which contains income thresholds for several categories and their values for one or more defendants.

Data never changes (historically) once added, and there is a single row of data added per year. There are 31 rows of data going back to 1993.

Distributed via	: Email
Format			: Excel spreadsheet

## GMT Data Dataset
The HUD GMT data contains data to establish a geographical means test threshold. Data is provided at the state+county level for each effective year for a given number of dependents. HUD doesn't distribute the dataset to parties, but has both an API, and a downloadable spreadsheet in Excel (.xlsx) format.

The average number of rows added per year is 4,765. There are a total of 97,000+ rows of data going back to 2001.

Distributed via	: api or document download from huduser.gov
Format			: api => json, download => Excel spreadsheet

## Zip-code to County Dataset
In order to lookup income limits by zip code (a requirement of the new IncLim application), and since the GMT dataset is grouped by state+county, we first need a way to lookup the county for a given zip-code. In the VES DB, the zip-county dataset is maintained and distributed by the VA Standard Data Services. However, this dataset is distributed as Oracle inserts/updates, and isn't presently publicized as an official public dataset on https://data.va.gov/.

Distributed via	: Email
Format			: Oracle updates/inserts

# Importing and Accessing Data

In order to populate the database, processes will need to be established, depending on where the data originates and the format it is delivered in. These variables will dictate the processes or mechanisms that need to be built.

Due to the headless nature of vets-api, (there is no frontend to vets-api) database inserts and updates happen in code only. While developers and other engineers may have access to the database itself, they aren't likely to be happy to write an insert statement with 4,765 values, so scripts/code must be employed for at least the larger datasets.

## Admin Interface
An Income Limits admin interface in Drupal would give us the flexibility to provide any admin experience we need. Initial thoughts around this involve not storing datasets in Drupal, particularly for the GMT and zip-code data (assuming we are not using an API for them), but using Drupal to house minimal data for later processing by a Sidekiq job in vets-api. This would be modeled after the VA Forms application which does similar things (though all forms are in fact stored in Drupal). For the large datasets (GMT and zip-code), the admin interface would contain only enough information for vets-api to pull in the data to postgres. For instance, for the GMT data, an admin may upload the spreadsheet to Drupal. Later, a nightly running Sidekiq job may pick up the file from Drupal and import the data to postgres. This would be a "pull" based approach. There does also exist a "push" based approach whereby facilities data is pushed into a Lighthouse API. Either one could work in theory if vets-api supports this.

# Final Thoughts
The bulk of the work to develop this method resides within data importing mechanism, scripts and interfaces that will need to be built. Additionally, work will be needed in multiple repositories/ownership contexts which will make rolling out changes more challenging. Overall, this is likely to be a more difficult lift than using the VES database by orders of magnitude--my initial ballpark for developing the implementation is 3-6 months.

**Comment by wesrowe** [comment]
@dsasser, I think I raised this elsewhere – is there an in-between possibility where VES exports tables that we import? So they're doing the heavy lifting into a format that's easier for us.

**Comment by dsasser** [comment]
> @dsasser, I think I raised this elsewhere – is there an in-between possibility where VES exports tables that we import? So they're doing the heavy lifting into a format that's easier for us.

That could be a possibility, if both VES and Platform are onboard with yearly/quarterly involvement. My above proposal assumes we want as close to 100% control over the process as possible.

The challenge here is that even though we have the data exported and delivered to us (the best way to deliver the exports would need to be discovered), a process will need to be developed to import the data on all environments. This means that data needs to be ingested separately into prod, staging, dev (that exists, right?) environments, which will require Platform/Lighthouse involvement. Additionally, the data won't be able to propagate to local environments: devs working on IncLim would need a way to get the exported data, and import it to their local vets-api database. This doesn't feel sustainable to me in the long run, but could be a way to at least get the first draft of the application going, buying time to pivot to the "right" way down the road.

I could be missing something here, so I'm happy to discuss.

**Comment by dsasser** [comment]
# Status Update 4/19/2023

We are pursuing an import/export architecture (while also pursuing the VES Oracle db connection simultaneously).

Joshua Faulker has provided the latest data export from the VES DB. These files are hosted on Google Drive [here](https://drive.google.com/drive/folders/1iTkVlOdcFum01nZrhaOxkMZSX_GeMRcH).

To support the import routine, we have [engaged with Platform](https://dsva.slack.com/archives/CBU0KDSB1/p1681834046150419) who noted that automation is the ideal path forward. Therefore, [tickets](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13320) have been created to establish functionality in the vets-api application that will support importing from remote (s3) files into [Active Record](https://guides.rubyonrails.org/active_record_basics.html#what-is-active-record-questionmark) models. The import will occur using Sidekiq automation script(s).

**Comment by wesrowe** [comment]
I think this is done. We discussed the plan with DaveC in refinement so a separate meeting is not called for.
