### ISSUE TITLE
Discovery: Audit Forms-related GraphQL queries that would be affected by upgrade to GraphQL 4.0

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13229]
### User story

**AS A** CMS Engineer
**I WANT** to have a detailed list of GQL queries that need to be updated to GQL 4.0 for the Forms API
**SO THAT** the Forms API remains stable and can receive expected data after GQL 4.0 / Drupal 10 upgrade.

### Engineering notes / background
The Forms API in Lighthouse pulls Form related data via vets-api, using GraphQL queries. We need to understand: 
* What queries they use
* What data they access

So we can share that with the CMS team, in service of the GraphQL / Drupal 10 upgrade project.

## Acceptance criteria

- [x] Forms API GraphQL queries in vets-api are identified and documented in this ticket
- [ ] Findings are shared with CMS Team (Tim, Edmund)

**Comment by jtmst** [comment]
It seems to me like a big part of this migration first me having to define a schema in the va.gov-cms repo, before we could look at the front end queries.  I'm not sure this makes sense to estimate as a front-end task right now

**Comment by swirtSJW** [comment]
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectiveness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid

**Comment by jilladams** [comment]
**4/18 meeting:** Tim, Steve, me, Josh, Daniel, Wes, Nate, Edmund, Mike, Kamari, Ryan. (Dawn)
**Good news**
* GraphQL 3 - can be used with D10 with the update of a few queries
* Won't block D10. We can keep GraphQL3 and hit D10 November upgrade deadline.
* Edmund has a playground up running D10 + patched GraphQL 3 (141811 library version, same as GQL 4). GraphQL keeps version info in Github (rather than Drupal.org)

**Open question:** 
* Is there an advantage to properly namespacing our fork of GraphQL3 in order to be able to run GraphQL 4 in parallel?
  * Nested question: would doing this ^ be advantageous for Fast Publishing somehow? (per Steve's note above)
  * JSON API will become the template / query language with Fast Publishing. GraphQL 4 becomes an optional Drupal query option, so we don't need to update FE templates to use new GraphQL 4 queries. 
  * "Forms in the Chatbot will drive the requirement to use GraphQL 4"
    * Swirt knows: a year ago, Chatbot team was trying to query specific paragraphs using GQL. They do have a CMS account / access, but they were struggling with the query. They have not accessed recently -- last API access = 2y1mo ago, virtual_agent_api = never. 
    * List of API users and last access (FYI @wesrowe ): https://prod.cms.va.gov/admin/people?user=api&status=1&role=All&workbench_access_section__section=All&order=access&sort=desc
    * So: this is a theoretical business requirement, but we _could_ move Chatbot to JSON API instead. 

Next steps sit with CMS team: 
* Verify that D10 + GQL 3 doesn't negatively affect anything in templates / performance.
* Evaluate JSON API vs. GraphQL performance (really a Fast Publishing topic?)
* Determine whether we are going to namespace GQL3 so we could run GQL4 in parallel.

**Comment by jilladams** [comment]
@wesrowe let's plan to talk about this one in FE refinement tomorrow. After you dropped from the GraphQL call we _did_ identify one need for GQL query info, for Forms. I updated the ticket with that in mind, but we should review it as a group.

**Comment by dsasser** [comment]
# VA Forms GraphQL queries used in vets-api

- https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_forms/config/graphql_list.txt
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_forms/config/graphql_query.txt
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_forms/config/test.txt

**Comment by jilladams** [comment]
@edmund-dunn @timcosgrove @swirtSJW ^ FYI

**Comment by jilladams** [comment]
Shared outcome with CMS team: https://dsva.slack.com/archives/CT4GZBM8F/p1682371789855499

Closing.
