### ISSUE TITLE
SPIKE: Remove in-line editing of reusable Q&A from FAQ & R&S content type

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13221]
### User story

**AS A** Content Editor
**I WANT** not to have the ability to edit a Q&A in-line on the FAQ content type, and instead edit directly in the standalone node
**SO THAT** I don't get Q&As into a publishing state where it's unclear what editing will impact.

***ADD SCREENSHOTS***

### Engineering notes / background
1. Same Entity Browser is used for FAQ and R&S, so modifying it in one place will affect both product types. 
2. We need to verify whether this will affect _more_ products. We need to consider change management. 

MVP = remove the edit button, not repurpose the Edit button. That would be next iteration.

## Acceptance criteria
- [x] Verify if an existing paradigm exists for handling the edit link, follow that (validate w/ Swirt, DaveC is high confidence on no)
- [x] Verify if the entity browser in use for FAQ & R&S will affect any other content types if we disable Edit
- [x] Conclusions are documented in this ticket, and #13220 is refined and/or other tickets created for next steps

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
@dsasser, if I followed correctly, you already finished this ticket by discovering quite easily that the path forward is easy and doesn't impact content types besides our targets (FAQ and R&S Detail). If that's correct, can you please update the ticket and close?

**Comment by dsasser** [comment]
# Spike Results

##  Verify if an existing paradigm exists for handling the edit link, follow that (validate w/ Swirt, DaveC is high confidence on no)
The edit link provided by Entity Browser cannot be easily manipulated. However, using the edit link isn't necessary to render a link to the Q&A node in the Entity Browser table.

There exists a mechanism to provide our own display (node title linked to node view page, opened in a new tab). Entity Browser leverages plugins that manage the display of entities in the Entity Browser table. The plugin is selected on the _field instance_ setting which is at a _per content type_ level.

In order to provide our custom node title link, we could build a new simple plugin. The plugin could make use of an optional configuration parameter to allow per-field-instance control of the 'open in new tab' setting.

## Verify if the entity browser in use for FAQ & R&S will affect any other content types if we disable Edit
We can remove edit from FAQ and R&S nodes separately, without affecting other content types. Entity Browser uses a common configuration for controlling the behavior and display of the _selection widget_. The edit and remove buttons are defined in the field instance form display settings, as seen in the screenshot below.

![Screenshot 2023-04-14 at 7 01 07 AM copy](https://user-images.githubusercontent.com/221539/232071286-6e9168b5-c08d-4ac7-9eac-30df61a5d5a2.png)
