### ISSUE TITLE
Review of translation management documentation: engineering

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#13247]
## Description
We have created documentation of the current state of translation management (#13097). To determine if this documentation is useful and clear, it is recommended that a engineering team member review this documentation.

Documentation is here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/translation.md

## Acceptance Criteria
- [x] Documents are reviewed by engineering for clarity and understandability
- [x] Provide recommendations/feedback for improvements 

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by tonytaylor** [comment]
I've looked over the docs, and have a few questions:

- Why is there both Checkout and Add to Cart?  What is done differently between them?
- Multiple icons can exist for a single piece of content... - I get a little lost on this one.  Might this refer to a possible state where an initial draft was successfully translated, but then the draft was updated and those updates have not been translated yet?
- Your job may add items to 'Suggestions'. It is not recommended to add... - Why is it not recommended?  What is the impact?
  - Also, what is Suggestions?  Is this a recommendation engine in the translation management system?
- Would an outline of the high-level operations be beneficial here?  (e.g. - 1) Go to Sources Page 2) Select Content 3) Add to Translator Cart, 4) Profit!)
- Translation via File - Is this a different translation process than the one that starts at the Sources page?
- Each collection of content that resulted in a file to download is a 'job'  Do all content translations wind up this way?  If not, what else can happen with content?
- On the Review page,  what happens when the user saves it as completed?
- On the Translate tab of the main content page, is the tab only available when there's translated content?  Can a user manage translating content as from the Sources page?  Can a user translate content from this page without executing a translation request from the Sources page?

**Comment by timcosgrove** [comment]
> Why is there both Checkout and Add to Cart? What is done differently between them?

I should have properly called 'Checkout' 'Request translation' since that is how it is labeled. 
* 'Request translation' takes you to a page to finalize setting up the translation job. You don't have an option add items to the translation job once you're in that final step. Using 'Request translation' from the Sources page is essentially 'Add to cart and check out'.
* 'Add to cart' collects items that will be added to your final translation job, similar to a shopping cart mechanism. This lets you do multiple searches and passes to find the content you want to translate.

> Multiple icons can exist for a single piece of content... - I get a little lost on this one. Might this refer to a possible state where an initial draft was successfully translated, but then the draft was updated and those updates have not been translated yet?
Yes. It might be better to call these 'statuses' than 'states', since 'state' generally implies one state of being from a bunch of mutually exclusive options. A translation item can have multiple statuses.

> Your job may add items to 'Suggestions'. It is not recommended to add... - Why is it not recommended? What is the impact?
> Also, what is Suggestions? Is this a recommendation engine in the translation management system?
'Suggestions' captures related items to a given piece of content in the translation job that may need translation. This will usually be entity references, such as taxonomy terms, blocks, menus, etc, that have not yet been translated.

I was steering the user away from using this because they would need to have a fairly solid understanding of Drupal's entity system and how it functions. It may be hard to make an informed decision about what should be added to Suggestions.

However, in thinking it through, I am actually thinking the default advice should be to add *everything* to Suggestions. This might be less confusing. 

> Would an outline of the high-level operations be beneficial here? (e.g. - 1) Go to Sources Page 2) Select Content 3) Add to Translator Cart, 4) Profit!)
Yes, I think it would be. The documentation is probably over-complicated and could benefit from something high-level.

> Translation via File - Is this a different translation process than the one that starts at the Sources page?
It is not different. 'Translation via file' means that the content for translation can be downloaded in a translation-oriented XML format (XLIFF). Our default flow will be 

1. Add content to translation job
2. Finalize translation job and save the job.
3. Download the resulting XML file.
4. Send that file via email to the translator.
5. Translator does their work and adds it to the XML file and sends it back.
6. File is imported.

'Translation via file' would be in contrast to translation via a Translation Management System (TMS). These are typically remote services with APIs for submitting translations requests, checking the status of the job within the TMS, and then retrieving the translated content again via API call. In these cases, the transmission of the XLIFF file in both directions is managed by TMGMT making calls to remote APIs. 

This is *vastly* preferable to manually downloading the file and emailing it. However, as our provider (Department of  Defense) does not provide any API by which content could be submitted, we are needing to go the manual route for the time being.

> Each collection of content that resulted in a file to download is a 'job' Do all content translations wind up this way? If not, what else can happen with content?
Any content translation ends up in a 'job'. 

> On the Review page, what happens when the user saves it as completed?
In the current setup, once every item up for review is accepted, the translation is saved into a node/entity. Either a new translation of a node is saved, or if it already exists, the updated content is saved into the translation of that entity.

Currently the translation saves into Draft state. 

> On the Translate tab of the main content page, is the tab only available when there's translated content? Can a user manage translating content as from the Sources page? Can a user translate content from this page without executing a translation request from the Sources page?
The 'Translate' tab is always available, and a user with sufficient permission could enter a translation directly here. Users could also manage translations from here, with the 'Request translation' and 'Add to cart' functionalities being available.
