### ISSUE TITLE
Footer defect: Broken link to VA social media page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13276]
## To Reproduce
1. Go to footer on any page
2. Click All VA social media, which links to https://www.va.gov/opa/socialmedia.asp
3. See "Sorry, we can't find that page" at destination
4. Note that you land on https://www.va.gov/web/standards/social-media-sites.cfm, indicating you were redirected

## AC / Expected behavior

Should land on a page with social media accounts listed.

## Screenshot
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/7d3b997b-5740-4434-a906-2cffb40b0c89)

**Comment by jilladams** [comment]
Per Dave, the destination link here is correct: https://dsva.slack.com/archives/C52CL1PKQ/p1681418246679079?thread_ts=1681393417.348859&cid=C52CL1PKQ.  That landing page is throwing the 404. 

That redirect isn't coming from either of the redirect files we help maintain ([redirects.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml) or client-side redirects in [crossDomainRedirects.json](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/redirects/crossDomainRedirects.json)).

**Comment by chri5tia** [comment]
Google indexed the same broken page, so that means this was the correct URL at one point in time: 
![Screenshot 2023-04-13 at 2 14 09 PM](https://user-images.githubusercontent.com/22764938/231884361-3b8c5aaa-44d4-4e4d-9bf1-e33f3bab4a7d.png)

Google [cached page](http://webcache.googleusercontent.com/search?q=cache:FPAT5VmWEV4J:https://www.va.gov/web/standards/blogs-social-media.cfm&hl=en&gl=us&strip=1&vwsrc=0) and [source code](http://webcache.googleusercontent.com/search?q=cache:FPAT5VmWEV4J:https://www.va.gov/web/standards/blogs-social-media.cfm&hl=en&gl=us&strip=0&vwsrc=1).

I have captured the source code in case anyone needs it and the google cache expires.

This means that that URL, https://www.va.gov/web/standards/blogs-social-media.cfm, was working as of Apr 11, 2023 05:39:57 GMT.

Related working URLs:

https://digital.va.gov/web-governance/social-media/
https://news.va.gov/social-media-policy/
https://news.va.gov/disclaimer/

Content search on staging didn't reveal anything about social media in the CMS.
This page must have gotten deleted or unpublished from the cfm side.

I searched for redirect tickets for this and didn't see any.

**Comment by jilladams** [comment]
Also, I updated to the new destination URL in the Footer menu, should it ever get to be drupalized int he front end. https://prod.cms.va.gov/admin/structure/menu/item/11591/edit?destination=/admin/structure/menu/manage/va-gov-footer

**Comment by chri5tia** [comment]
@jilladams Thanks for doing that. The link should be https://digital.va.gov/web-governance/social-media/social-media-sites/. I updated the footer on prod. We need to find the redirect for socialmedia.asp and fix it that. Looking now.

**Comment by chri5tia** [comment]
See ^^^ PRs to create override the redirect in the devops repo and to update the footer link in the FE repo

To test. We need to use a tugboat environment and pull in the content-build branch.

**Comment by jilladams** [comment]
Perfect, thanks. I closed the Devops PR with a comment that we really need to track down where the original redirect originated, and have that sent to the right place. We can always reopen when we learn more, if that ends up being the right thing to do. 

The FE pr looks good - added Daniel / Josh as reviewers. thanks for hopping on this.

**Comment by jilladams** [comment]
Verified link fix on Staging. Closing, and this'll go to prod when today's CI/CD madness clears up.
