### ISSUE TITLE
UXD: Prototype Feedback and Updates

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13385]
## Description
The prototype (#12825) will be reviewed with Dev and Accessibility to determine feasibility and readiness for usability research. 

This task exists to track the collection of feedback and change management that results. 

## Acceptance Criteria
- [x] Feedback from dev and accessibility documented.
- [x] Changes made to prototype documented.
- [x] Communicate changes with UX Research (Jo), PM (Mike) and Erika (PO) to ensure research plan isn't impacted.

**Comment by productmike** [comment]
@BlakeOrgan -- can you take a look at this prior to planning on Wednesday 4/26 to let me know if this the ACs and objective make sense to you for S83? Essentially, a continuation of #12825 in which the AC was to schedule the meeting with dev and a11y

**Comment by BlakeOrgan** [comment]
@productmike looks good to me

**Comment by productmike** [comment]
perfecto, I'm going to add to S83. I'm guessing the LOE is going to be dependent on the feedback we receive, so I'm not going to stress on the pointing unless you'd like to pick a middle of the road number :)

**Comment by BlakeOrgan** [comment]
@productmike 

I met with @edmund-dunn, @laflannery, and @joagnitti today to review the designs and we have discussed a couple of edits that need to be made.

- [ ] The "Redundant Phrases" flow should be changed to be blocking upon submission if we find that one of the redundant phrases was used.
- [ ] Add screens that show examples for when people make multiple errors and what that error state would look like.
- [ ] Change the language in the help text for creating good alt text to reflect the fact that these are no longer suggestions, but are requirements.
- [ ] Make the prototype clickable for @joagnitti to use during research sessions.

We also discussed a potential path forward for allowing for detected errors to be shown as they're typed rather than once submitted. While the current implementation doesn't allow for that, @edmund-dunn found two potential modules that could allow for that if they were implemented. Some discovery work would need to be done before deciding to move forward to allow for that though and what the LOE would be.

Those two potential modules are:
- [Clientside Validation](https://www.drupal.org/project/clientside_validation)
- [Field Validation](https://www.drupal.org/project/field_validation) 

@joagnitti is also going to look into gathering insights around error handling as an additional part of her research plan that she's putting together.

**Comment by productmike** [comment]
@BlakeOrgan 

I've passed your notes along to Erika and will look at them myself for potential feedback. In terms of moving forward, are the changes mentioned able to be addressed in S83 or will we need a linking ticket to do so?

**Comment by productmike** [comment]
Also, I've created a spike for the error detection discovery -- see 13604

**Comment by BlakeOrgan** [comment]
@productmike The updates listed above are in progress and are on track to be completed by the end of sprint 83.
