### ISSUE TITLE
Xfunc: Finalize Alt Text Prototype

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13429]
## Description
As a VA PO, I want to hear the final recommendation of how to best _improve the image upload editorial interface to allow editors to add better, more useful alt text for the images they are uploading (original HMW statement)_ - informed by usability research and design findings - so that I can determine best path forward for my editor audience. 

## Acceptance Criteria
- [x] Feedback from usability research has been incorporated into prototype. Items listed in comments.
- [x] Prototype is demo-able against the original HMW and key results are reviewed w/ PO, PM, DM and a11y (Laura).
- [x] Initiate feedback loops for approvals to implement prototype for broader editor audience.

**Comment by BlakeOrgan** [comment]
Suggested UI enhancements based on findings from the research sessions can be viewed as part of the [Editor-facing Alt Text Creation Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/alt%20text/Research%20findings.md#editor-facing-alt-text-creation-research-findings)

**Comment by productmike** [comment]
@BlakeOrgan Would you mind beginning to plan out how you'd like to address each of the educational and UI optys? Basically forming a recommendation for how you and Jo think we should approach? Probably worth getting with Laura as well but up to you. No right and wrong -- and some things may not have a path forward which is ok to state as well. Feel free to do within this ticket OR use our [confluence space ](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2716205060/)

LMK if any hurdles or questions there! Thank you!!


----UI Suggestions----
**Educational opportunities**

- Provide example alt text directly on the editing page to reduce the amount of clicks and time editors need to take to get guidance.
- Consider removing “clearly identifying the main purpose” from the first bullet point, to reduce confusion (and reading time)
- Consider increasing the character limit and removing this bullet point from the list since it is implied and enforced by the character counter.
- Provide rationale for why editors should avoid phrases like “image of”, "photo of", etc.
- Provide additional resources to help answer editors’ questions around the depth of descriptiveness (i.e., what details to include, gender neutrality considerations, etc)


**UI enhancements**

- Consider opening “Learn more” in a new tab so as not to disturb the editor’s progress, or ensuring that their work persists when navigating away from the page and back.
- Make the alt text field big enough to display all characters, or at least provide draggable corners so editors can view and edit all alt text at once.
- Align the alt text field with the other text fields on the page so editors can find it easier (e.g., left align and/or move it beneath the image thumbnail).
- Allow the full image to show within the alt text image preview (thumbnail) so that editors have a clear view of what they are describing.
- Make the distinction between alt text image thumbnail and image resizing options clearer so that participants don’t confuse the two.
- Increase the visibility of color indicators for character limitations; consider removing the yellow indicator as it showed no effect on situational understanding.
- For the condition where more than one error is found, consider consolidating the initial (top) error message so that it contains only one link to “Alternative text” instead of one for every error.
- Explore the possibility of showing error messages in real time, so editors can receive immediate feedback.

**Comment by productmike** [comment]
@BlakeOrgan based on @joagnitti's findings through her research, which of these (if not all) do you think we can address in Sprint 90 for planning purposes today?

**Comment by productmike** [comment]
From planning on 8/2, let's move forward with the following: 
1.  @BlakeOrgan clearly buckets design findings between Alt Text specific & items for further discussion. 
2.  @BlakeOrgan moves forward with Alt Text specific in this ticket. 
3.  @productmike will create tickets to support items for further discussion/refinement. Prioritizing error message handling as this is an OCTO-DE priority -- this can model potential success for other portfolio products.

cc: @EWashb @BerniXiongA6

**Comment by BlakeOrgan** [comment]
I created two seperate mockups depending on the direction that we decide to go. [The first mockup](https://www.figma.com/file/OXueAhBrPif6wh8vynPxGs/Alt-Text-Errors?type=design&node-id=501%3A1438&mode=design&t=nMUNdhhuGFpKV2eY-1) lays out how this flow should work if we end up not implementing the new clientside validation module and me and @edmund-dunn talked about. [The second mockup](https://www.figma.com/file/OXueAhBrPif6wh8vynPxGs/Alt-Text-Errors?type=design&node-id=529%3A11615&mode=design&t=bRCSfONgQTr3YR5F-1) shows how this flow should work if the clientside validation module IS implemented and is also the more ideal mockup because it provides more immediate feedback to users as they had requested as part of the research that @joagnitti did.

### Updates made

- Changed "Provide a name that will help other users of the CMS find and reuse this image. The name is not visible to end users." to be help text that is attached to the Name input rather than separate and at the top.
- Red colors updated to "--va-red-dark" HEX #CD2026 in order to increase visibility and to align with error messages on VA.gov
- Switched position of alt text input field and image preview so that input field is now left aligned.
- Image preview now shows the whole image and does not crop.
- Increased the height of the input field so that 150 characters can show within the field.
- Updated "Best practices" bullet points based on editor feedback and educational opportunities.
- Best practices bullet points should now default to closed to reduce cognitive load. We can rely on the error text to guide them in making corrections if they're made.
- Learn more link show open in a new tab so that any work done on this page is not lost.
- Removed the yellow "approaching character limit" indicator because it showed no effect on situational understanding and yellow is a difficult color to maintain AA contrast ratios on a white background.
- For conditions where more than one error is found within the same field [WITHOUT CLIENTSIDE VALIDATION](https://www.figma.com/file/OXueAhBrPif6wh8vynPxGs/Alt-Text-Errors?type=design&node-id=501%3A1438&mode=design&t=nMUNdhhuGFpKV2eY-1), the top error message should only show one indicator for the field instead of multiple indicators per error.
- For conditions where more than one error is found within the same field [WITH CLIENTSIDE VALIDATION](https://www.figma.com/file/OXueAhBrPif6wh8vynPxGs/Alt-Text-Errors?type=design&node-id=529%3A11615&mode=design&t=bRCSfONgQTr3YR5F-1), the top error won't be needed any more for the alt text input field because errors for this field will show up immediately and not upon clicking save. Here's the list of when errors will need to be thrown if we use clientside validation.
    * Alt text field is empty upon submit.
    * Immediatly when the alt text input field is over 150 characters
    * Immediately when the alt text matches the name of the uploaded file. If we’re not able to technically achieve that, the fallback situation would be to check specifically for the file extensions that are accepted in the image upload. (.png .gif .jpg .jpeg)
    * Immediatly when the alt text contains any of the following phrases “image of”, “photo of”, “graphic of”, or “picture of”. 

### Not addressed (and why)

- **Make the distinction between alt text image thumbnail and image resizing options clearer so that participants don’t confuse the two.** I did not address this because this will most likely be addressed once we allow for setting a focal point rather than cropping to specific aspect ratios.
- **Provide additional resources to help answer editors’ questions around the depth of descriptiveness (i.e., what details to include, gender neutrality considerations, etc)** I feel like this would be better done in the KB article rather than within the UI because we want to keep info within the UI as brief as possible.
- **Provide example alt text directly on the editing page to reduce the amount of clicks and time editors need to take to get guidance.** This would be hard to do without a photo reference and might cause confusion once they upload their own photo. I think this might be worth exploring more if we decide to eventually use AI to generate alt text.

**Comment by laflannery** [comment]
Another item we should add validation for is double quotes ("). The reason is because I happened to find an instance where an editor added these to their alt text and it breaks the formatting - the code thinks the attribute should actually be closed when it sees this, [example in this facility photo](https://www.va.gov/minot-vet-center/) (Also screenshot in case they update this):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjNDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1628d52c912dc0803b599e94c515b7246d749732/image.png)

2 suggestions (from Blake) on how the validation could work, just depending on tech feasibility:
- Simple, basic validation - We check for use of double quotes and if we find any we do not let them save and display an error message: "Alternative text cannot contain double quotation marks."
- More complex solution to help editors avoid the error in the first place - For example, automatically changing double quotes to single quotes upon save.
