### ISSUE TITLE
S83 Dependabot Risks

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13498]
## Description
There are currently 11 security alerts identified by Dependabot. Four (4) are thought to be straightforward; the other 7 require more investigation time.

## Acceptance Criteria
- [x] Document how we are going to address these moving forward. 
- [x] Prioritize the 11 issues along with basic impact analysis.
- [ ] Review with the PM (Mike) (and potentially PO dependent on Erika's desire to be this deep in the weeds).

**Comment by ndouglas** [comment]
## Dependabot Alerts Policy

### Background

Dependabot creates [alerts](https://github.com/department-of-veterans-affairs/va.gov-cms/security/dependabot) in response to security vulnerabilities detected within project dependencies. In the case of the CMS, these dependencies can be any of several different languages, installed through several package managers, span multiple subprojects and concerns within the greater CMS project, and be easily forgotten.

This policy's intent is to systematize how we handle these on an ongoing basis.

### Recommendations

1. We should consider establishing a second, private repository (e.g. `va.gov-cms-sensitive`) for tracking issues related to security. Any details about these packages and their vulnerabilities (e.g. name, version, risks, example code) should not be placed in the public repository. It's true that someone can simply clone our repo and run `npm audit` to gain a list of our current vulnerabilities, but it's not great to publish this information publicly. Dependabot alerts are themselves restricted to repository admins.

2. Determine who will handle these issues. This might be an existing team (`cms-devops-engineers`, `cms-qa-engineers`), etc, or simply any engineer on the CMS team.

3. Triage and create issues for Dependabot alerts during DevSecOps Refinement meetings. We don't need a lot of boilerplate here, and these things are almost impossible to size. But we can at least say "Try to knock out the stack overflow vulnerability in padLeft" or whatever.

4. Assign issues as part of sprint planning.

**Comment by ndouglas** [comment]
![Screenshot 2023-05-01 at 3 34 06 PM](https://user-images.githubusercontent.com/1318579/235516902-99d9b577-e6fb-4f29-9656-c24a026466a5.png)

**Comment by ndouglas** [comment]
I'm reconsidering my above suggestion of adding a second repository to handle security issues. I think the better thing to do would be to either maintain them completely in the open (given that literally anyone can see and run `composer outdated` or `npm audit` on our codebase). Especially given the nature of these vulnerabilities and how infrequently they are remotely exploitable, I think it'd better to minimize the overhead of managing these issues and the resuiting work.

That said, I would like to note in the policy that if something _is_ remotely exploitable or otherwise problematic, we should handle discussions within a more secure context.

**Comment by ndouglas** [comment]
I opened a PR here for comments: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13622
