### ISSUE TITLE
Change Management

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13533]
Determine the following artifacts necessary to deliver change management for this change to events 
- comms -- coordinate with MichelleM & VHA DM (in sync)
- Editors
  - Graduated rollout to specific users is ideal - ask Michelle who the right editors are who could be testers.
    - Are any existing VAMC events candidates for promoting?
- KB article updates - MUST
- ~videos~ -- deprioritized for Veterans Day launch, needs a follow up ticket 

## VHA DM comms
JennyHL (VHA DM) / Tim Hudak (VEO): ask them for requirements re: what is the bar for what kind of events should be promoted / guidance to provide to Editors. 
* Dave proposes talking to Michelle (on 10/11) to propose connecting these 2 to make the decision around release comms. 
* Once the guidance is settled, we can coordinate with Blake / Justin for roll out plan.
* Dave to confirm the beta events that _could_ be promoted to the National Calendar with these 2 stakeholders.

# ACs
- [x] Work with Facilities / VHA DM to get buy in on CM approach 
- [x] KB article update with
  - [x] How to use the checkbox, expected behavior
  - [x] Guidance re: which items to promote to the National Calendar
- [x] Create a ticket to track updating the Training video

**Comment by jilladams** [comment]
Wow, good catch. I had not remembered all the work in this epic that was done on Facilities behalf. I think this ticket stands, now as a Public Websites task for handling CM when the change is ready. Moved it over, and flagged the epic for Wes.

**Comment by jilladams** [comment]
From BE refinement: 
* Daniel and Christia have proven that the Drupal work done to implement the checkbox maps publishing to Outreach Events listing under the hood, with zero updates to the GraphQL query or the Front-end required.
* This can be proven via Tugboat. In Tugboat, an editor can modify the CMS and it can build a front-end to demonstrate the point
  * Test user who has generated many events for Spokane: [kristin.young2@va.gov](https://prod.cms.va.gov/user/2146)
  * CMS: https://vacms-10089-nat-outreach-cal-0gucur96dxwvqlweh9at2fojfrohmnya.demo.cms.va.gov/node/add/event
  * Content release: https://vacms-10089-nat-outreach-cal-0gucur96dxwvqlweh9at2fojfrohmnya.demo.cms.va.gov/admin/content/deploy
  * Front-end: https://web-0gucur96dxwvqlweh9at2fojfrohmnya.demo.cms.va.gov/

If we do need to hide/show the checkbox:
* To conditionally show to specific role: could add a permission and enable that perm for the role in question.
  * Could show to Content Admin -- small user group
* We can control display of this checkbox, we can use a CMS feature toggle to hide the checkbox. It will be on or off. When enabled, could use that mechanism to specify a shortlist of users who would see it via this permission.
* There are other more labor intensive / hacky ways to go about this temporarily if needed. (conditional checks on user ids, etc.)

**Comment by mmiddaugh** [comment]
The following health care systems were identified as candidates to test the functionality, either because

- they are power users who have created a significant number of events over the last year or 
- they are editors with less experience creating events but have events which might meet the criteria for pushing to the national calendar

They've been approved by VHA DM. 

- Boston 
- Butler 
- Central Iowa 
- Cincinnati
- Connecticut 
- Greater Los Angeles 
- Lovell 
- Louisville
- Madison 
- Minneapolis 
- New Jersey
- South Texas
- Two individual editors were also suggested by VHA DM 
  - one from VISN 17, Outreach hub
  - one from VISN 4. 

I provided user names and emails to Jill in a slack DM

**Comment by jilladams** [comment]
Notes from Dave: 
* He met with Michelle, she is following up on the Editors. Should be a short list of Editors by email / username.
* Dave synced with Mikki and has emphasized a hope for iterative improvements to keep Veterans Day launch goal.
  * Dave has proposed removing Events breadcrumbs, and replacing with a "Back" link
  * See more events at Event page foot: also a concern, IA are toying with options.

**Comment by jilladams** [comment]
@davidconlon @mmiddaugh @FranECross :  Re: Editor outreach on the Events national calendar - apologies for the late delivery here. I took a pass at an email draft, below (with some gracious input/revisions from Joann on the CMS team) . Putting this in Github so all 4 of us can access, since Fran doesn't have a VA email / Sharepoint access just yet.   Please edit this comment directly with your changes -- Github will show us a revision log.

We have VHA DM sync on Monday at 3p ET, where we should get this in front of Blake / Justin. @mmiddaugh if you get a chance to take a pass earlier in the day and want to go ahead to share with Blake / Justin, please do, or let me know and I can send prior to the meeting. @davidconlon trying to avoid too much open ended call for feedback, so feel free to weigh in if you object to any specific language here. Thank you!

---

Hi [first name of editor],

We would like to invite you to be among the first to explore a new feature in the VA.gov content management system (CMS). We've updated the Create Event section and would value your verification of the new functionality.

**The update in a nutshell:**

- Now when you create an event for your VAMC, you can also publish it on the National Outreach Calendar.
- Events eligible for this National Outreach Calendar are those related to topics relevant to Veterans anywhere and online events that can be attended from anywhere.
- Once your event is on VA.gov, it will show up in two places: on your VAMC Events page and on the National Outreach Calendar at https://www.va.gov/outreach-and-events/events/. When any VA.gov visitor clicks through to view your event, it will use your VAMC's breadcrumbs and URL.

**To take part in this opportunity and share your feedback, there are two important things you need to do:**

1.  Share your event (_note: We’re especially interested in Veterans Day events with national significance_) on the National Outreach Calendar by following these steps:
    - On the Create Event page in the CMS, select "Where should the event be listed?" and choose your VAMC.
    - Check the box that says "Publish to the National Outreach Calendar."
    - Finally, publish your event.
2. Tell us what you think! Please send the event link and your feedback to [email address] by Friday, October 27th at 5pm PT/8pm ET.

Thank you in advance for your willingness to help!

Best,
Blake Scates
VHA Digital Media

**Comment by FranECross** [comment]
☝🏼Thank you, @jilladams . The letter looks great, and I don't have any suggestions.

**Comment by jilladams** [comment]
KB article revision added in draft, to include guidance re: using the new national checkbox: https://prod.cms.va.gov/node/6483/revisions

**Comment by jilladams** [comment]
Training video ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16042

**Comment by jilladams** [comment]
Leaving this open til S97 to track any launch related change management required.

**Comment by jilladams** [comment]
Approved to ship on Monday. KB revision is published. Fran will close loop with Blake via email when it's live for all editors in prod. Closing!
