### ISSUE TITLE
I.L. FE: Protect/redirect users from inappropriate deep-linking to a bad state

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13593]
### User story

**AS A** Veteran
**I WANT** to land on the first page of the IL app if I mistakenly deep-link to a later page in the app and missing data would break the experience
**SO THAT** I don't have a broken experience.

Assumption: the URL will change from page to page within the app.

Therefore: A user could "drop into" e.g. the Results screen, but the react app wouldn't have a zip code or number of dependents. That's a bad state.

## Acceptance criteria

- [x] It's not possible to link directly to a later page in the app with a broken state due to missing data, non-linear flow through app, etc.
- [x] Edit action is a link if possible (a11y)

**Comment by randimays** [comment]
Progress notes:

We need to make some changes in the `devops` repository to enable client-side routing at the app level. Right now routing is happening on the server. I wrote some code in the React app to redirect as necessary if deep-linking, and I'm getting a 404. It doesn't hit the React code at all (when navigating to `/health-care/income-limits-temp/zip` because it's getting a bad response from the server instead.

Hopefully the `devops` changes will solve the problem. We'll be waiting until the Wednesday morning deploy for that to reflect and then I can continue. Meanwhile, I'm going to make changes in `content-build` and `vets-website` to update the temporary URL (`/health-care/income-limits-temp` to `/health-care/income-limits`) - Yay, this isn't in prod so we don't have to coordinate releases carefully.

**Comment by randimays** [comment]
Follow up on the above.

Once [the `devops` changes](https://github.com/department-of-veterans-affairs/devops/pull/13183) were merged, the changes I had made in `vets-website` to do the redirecting worked. [Here's the PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24718).

**Comment by randimays** [comment]
Loom walkthrough: https://www.loom.com/share/7171cafa1fce41a0a92b4a93e67fcf53?sid=394e5c41-7a1e-4de6-980d-b73bd1fa83a5

**Comment by wesrowe** [comment]
the loom looked great, I asked a couple questions and the answers were good. Can close!

**Comment by randimays** [comment]
Verified in staging. Good to close!
