### ISSUE TITLE
Understand and document the NCA Use Case

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13609]
## User Story
As a UXD, I need to understand the foundational differences between how VHA DM editors and National Cemetery Association editors divvy up content areas AND why the current schema does not work within both models.

## Measurements
TBD

## Acceptance Criteria
- [x] Meet with PM, PO to discuss NCA use case. 
- [x] Document differences and indicate that location in this ticket.

**Comment by davidmpickett** [comment]
Probably makes sense to loop me into this as I have a lot of context on Facilities and the CMS User Permissions Model

**Comment by productmike** [comment]
CMS team has meeting with PO 5/15 to clarify the problem statement re: scaling the cms.

**Comment by productmike** [comment]
Tracking CMS team use case/requirements (post meet with Erika and Blake this morning) through the canvas here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683147313588/afecd984e38a4d90f424e3ab80050f4d765ae7f6?sender=ub3a2c2a4de441f561d452324

**Comment by BlakeOrgan** [comment]
After talking with @EWashb and @productmike to discuss the NCA use case, one of the things that we are likely to need is for users assigned to multiple sections to have different roles assigned to them for each of those sections. UX Discovery of the current state of Roles, Permissions, and Sections was done as part of ticket #13110. Here are some things that might need additional tickets as we continue to discuss the possibility of Drupalizing NCA.

- We'll need clarity on the user base and the structure of sections that will be needed for the NCA user group(s). Discovery is needed for who currently updating site content on Teamsite.
- We'll also need to take a look at existing Teamsite content and evaluate how we might transfer existing content into Drupal content structures. Can we use existing content structures or will we need to create new ones for this new user group?
- We might need some cross team collaboration between CMS and Facilities. Is there an existing runbook of what the process looks like to bring on a new userbase into the Drupal CMS? Was the process for bringing on VBA users documented anywhere and were there any lessons learned that we can improve from when that process happened? @davidmpickett might be someone worth talking to in order to point us in the right direction.
- I assume we'll need to pick a pilot group of NCA users before rolling out NCA full scale. User research might also be beneficial to learn more about this new user base that will be using the CMS. @joagnitt
