### ISSUE TITLE
I.L. BE: Make API documentation consistent and add Swagger yaml file to vets-api

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13614]
### User story

**AS A** Engineer in the OCTO-DE ecosystem
**I WANT** all API documentation to be housed in the vets-api repo
**SO THAT** it's easily accessible to all the people and tools that need it.

**AS A** Engineer in the OCTO-DE ecosystem
**I WANT** all API documentation agree about request and response
**SO THAT** it's clear what/how to implement.

### Engineering notes / background

Daniel shared a link to swagger.io that only worked for him. Details available in #12584.

Swagger docs to date: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12249#issuecomment-1406818162

The swagger sample output in Daniel's [comment here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12584#issuecomment-1446629888) is correct in shape, but has parameters/fields we have since removed.

## Acceptance criteria

- [ ] IL API design yaml is updated to reflect business logic as implemented to [Mural](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1683232214853?sender=uebde62ceb342c6477fb09406&key=71389d5d-cc99-471d-bcaf-2bcc34aaaedb) – i.e., single values for Pension, NMT, and GMT thresholds, appropriate to the year, zip, and dependents in the API request
  - [ ] And no longer including fields the FE doesn't need, e.g. county name
- [ ] yaml updated to include new zip-validation endpoint
- [ ] IL API design yaml is in the right place on vets-api
- [ ] confirmed on Staging that vets-api is consuming it correctly by browsing the Swagger GUI (see [docs](https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/swagger))
- [x] Commented/clarified in tickets where API response is pasted that there is an updated design
  - [ ] #13585

**Comment by wesrowe** [comment]
assigned to Daniel for a quick pre-refinement if time allows

**Comment by jilladams** [comment]
From planning: this will publicize the API docs. If we then break the pattern during development toward launch, we could theoretically have consumers that we then break their API. In that event, we'd need to version the API. So: we don't need to do it now, this should happen closer to launch with API is tested / implemented against / final-ish.

**Comment by wesrowe** [comment]
Removing estimate to add some additional ACs around getting all the API design documentation straight.

**Comment by wesrowe** [comment]
@dsasser @jtmst, FYI I added an AC to this ticket for adding the new zip-validation endpoint to swagger yaml.

**Comment by dsasser** [comment]
@wesrowe
It appears that we (I) may have misunderstood how to get the swagger info into vets-api. What I thought was going to be quick placement of the swatter yaml turns out to be more involved. Essentially, the swagger yaml needs to be re-written in Ruby in order to be exposed as an public endpoint in the Swagger UI.

As a result, this is going to take a bit more time (1 day ish) than we anticipated.

**Comment by wesrowe** [comment]
@dsasser, thanks for the heads up. it's probably not a big deal unless it disrupts your commitments. and it's coding, yaaaaaaay!

@jilladams, FYI

**Comment by dsasser** [comment]
PR for Swagger UI updates in vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/13334

**Comment by wesrowe** [comment]
@dsasser, on the zip validator, should there be a failure (4xx) code as well? just curious

**Comment by dsasser** [comment]
> @dsasser, on the zip validator, should there be a failure (4xx) code as well? just curious

No the zip validator doesn't have a 422 error path. If a zip is invalid, a 200 response is still returned. The zip validation response is a JSON object that contains the validation status. eg:

![Screenshot 2023-07-25 at 11 41 55 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/6409fe5f-1472-4a51-a412-bcfdd0c166cc)

**Comment by dsasser** [comment]
@jilladams @wesrowe in order to view the new Income Limits api docs in the Swagger UI:

1. Visit https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/
2. At the top of the page, change to the 'v1' API version by entering `https://dev-api.va.gov/v1/apidocs` and click the Explore button.

![Screenshot 2023-07-28 at 7 58 47 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/1f106aad-2bf1-4e27-9b5e-5dfa28bdc17d)



Staging or prod API endpoints can be used as well (https://staging-api.va.gov/v1/apidocs, https://api.va.gov/v1/apidocs)

**Comment by wesrowe** [comment]
looks good! closing
