### ISSUE TITLE
UX Team Review of Options for character limits on text fields

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13646]
## User Story/Description
As a developer, I want to confer with UX teammates to ensure the option selected to handle the soft text limits is thoroughly vetted and impacts accounted for, so that consensus is built.

Continuation of: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13248#issuecomment-1522828596

## Acceptance Criteria
- [x] Approaches are discussed as a group (CMS Team, possibly folks from other teams).
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13646#issuecomment-1560071860
- [x] Course of action is decided upon and tickets written for its implementation.

**Comment by timcosgrove** [comment]
@BlakeOrgan @joagnitti and I discussed this. The situation we are trying to address is, English text tends to 'expand' when translated into many languages - that is, it requires more characters to express the same meaning in some languages, relative to English. This conflicts with setting character limits on text fields. If a user is given a text field that has a limit of 255 characters, and they use that entire space, when that text is translated into some languages, its length will exceed the limit of the text field.

The main proposals from a UX perspective are:

* We would like to move any text field that needs a text limit to use `text_long` fields and to use a 'Text/Textarea with counter' widget for edit forms
* We would like to drop the character limit that applies to English text fields when that content is translated or edited in a translated language. So, if a given text field has a limit of 1000 characters in English, that 1000 character limit would not be enforced in for example Spanish or Tagalog.

## Form widgets moving to textarea with counter
There are currently two kinds of text fields with character limits: fields that enforce character limits at a database/system level, and fields that enforce it at the form level with the countdown mechanism. Each of these presents the user with a different UI and flow.

It turns out that UX and engineering needs are in synergy here. From an engineering perspective: translated versions of text are stored in the same place in the database as their English counterparts. A limit on characters at the database will therefore not accommodate other languages. 

From a UX perspective, there is a desire to align on one experience for this functionality, and to align on the countdown version of the form widget. So, what UX wants matches what engineering wants here.

## Dropping character limits in translations
As we said, some languages need more characters to convey information relative to an English version of text. These differences have rough averages - for example, Spanish on-average expands 20% relative to English - but the exact amount of expansion depends on the content of a given sentence. 

We could attempt to enforce a *higher* limit based on the language type. But, it would need to be greater than the average, since for some translations, the expansion would be larger than the average. To be on the safe side, the limit would need to be quite a bit larger than the English limit, possibly as much as double the limit. Even in that situation, it is possible a translation might exceed that limit.

It is much simpler and less error-prone to simply remove the limits for other languages. Note that we will continue to have the same limits and behavior on English content. The translated content is entirely dependent on its English source content, and so effectively there are similar limits for other languages. They will just be enforced in the translation process rather than by the CMS.

## Risks
There are a few risks worth calling out. In our opinion, none of them change our approach.

**Comment by timcosgrove** [comment]
The move of all fields to text/textarea with counter and to underlying unlimited size is beginning with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13512 and will continue on from that ticket. #13512 is a POC and its findings will determine the timeframe for the rest of the migration.

Modifying form widgets that limit character input will be addressed in #13806.
