### ISSUE TITLE
Spec roles and permissions

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13800]
# Acceptance criteria

- [x] Take the stories from [13272](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13272) and come up with specific lists of roles, workflows, sections, that need to be created and what permission each will need for the VBA content types
- [ ] Update implementation ticket of roles & permissions https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334

# Stories by user type (from 13272)

These stories are all formatted the same way:
- I want to _DRUPAL ACTION_ a **DRUPAL ENTITY** in a `DRUPAL SECTION`

I tried to write these stories in a way that is agnostic about Drupal Roles & Workflows, since those should be configured to support these stories (rather than the reverse). To do so, I created this list of Drupal actions that is slightly different than the one we use in our existing workflow.

**Drupal Actions Glossary**
- _Create_ - Create a new instance of a Drupal entity
- _Edit_ - Draft a revision of an existing Drupal entity (regardless of publishing status)
- _Change Node Status_ - Publish or Archive a Drupal entity (change node_status between 0 & 1)
- _Publish Revision_* - Publish a new revision of a published Drupal entity (node_status = 1)
- _Submit for Approval_ & _Approve_ - Only used in situations with official sign-off steps

*The ability to perform this action cannot currently be granted without also granting the ability to _Change Node Status_

## VBA Local Facility Editors
e.g. Honolulu Regional Office employee

**MVP**
- I want to _Edit, Publish Revision_ a **VBA Facility**, in `a regional VBA section`
- I want to _Create, Edit, Change Node Status, Publish Revision_ a **VBA Facility Service**, in a `regional VBA section`
- ~~I want to _Create, Edit, Change Node Status, Publish Revision_  a **Banner**, in `a regional VBA section`~~ _Banners will be part of VBA facilities_

## VBA National Editors
e.g. Office of Strategic Engagement employees

- I want to do everything **VBA Local Editors** can & also...
- I want to _Edit, Approve, Publish Revision_ a **VBA Service Region**, in `all VBA sections`
- I want to _Edit, Submit for Approval, Publish Revision_ a **VA Service Taxonomy Term**, in `all VBA sections` ??
- I want to _Edit, Publish Revision_ a **Centralized Content**, in `all VBA sections`

## Facilities Admins
e.g. CMS Help Desk, Facilities Team Engineers

**MVP**
- I want to do everything **VBA Local Editors** & **VBA National Editors** can & also...
- I want to _Create, Change Node Status,_ a **VBA Facility**, in `all VBA sections`
- I want to _Create, Change Node Status_ a **VBA Service Region**, in `all VBA sections`
- I want to _Create, Change Node Status_ a **Centralized Content**, `in all VBA sections`

**Comment by jilladams** [comment]
@xiongjaneg @davidmpickett flagging: this is a ticket that might be closeable after our Workflow spike is done & reviewed with CMS Collab Cycle, if we determine workflow will work and we don't need Roles / Permissions done separately.

**Comment by davidmpickett** [comment]
> @xiongjaneg @davidmpickett flagging: this is a ticket that might be closeable after our Workflow spike is done & reviewed with CMS Collab Cycle, if we determine workflow will work and we don't need Roles / Permissions done separately.

Not true. The Workflow approach inherently uses Roles & Permissions. Workflow Permissions per Role are one subset of the massive Drupal Permissions matrix. "Role & Permissions" in the title here is shorthand for the whole kit and kaboodle of Drupal governance configuration which includes roles, permissions, workflows, & sections.

**Comment by jilladams** [comment]
Thanks for clarifying. In light of that, will need to be refined. Also: we've said a couple places that Roles / Permissions aren't necessary for MVP Pilot rollout. They _are_ necessary for MVP National rollout. Just noting that, since the Roles/Perms epic rolls up to PIlot vs. National right now -- seems like we should move that?

**Comment by davidmpickett** [comment]
Not sure who said "Roles / Permissions aren't necessary for MVP Pilot rollout" but it wasn't me. They absolutely are necessary so we can get our 7 MVP editors in the system creating an editing content.

**Comment by mmiddaugh** [comment]
not sure where else to capture these notes from a conversation earlier today... @xiongjaneg 

**tasks to support a second workflow**
- build workflow (or reuse the one that DaveP spun up)
- add Steve's patch
- convert existing views to use the new filter for moderation state

**Comment by davidmpickett** [comment]
New [content creator](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/content-governance/content-creator-roles) role: 
- label: Content creator - VBA
- machine name: content_creator_vba
- description: Can create VBA facility services
- Permissions: VBA Facility Service: Create new content
- Who should get this role: VBA Local Facility Editors & VBA National Editors

![Screenshot 2023-10-03 114441](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5dc1a713-8438-4059-a1d3-184e5f653d10)

**Comment by davidmpickett** [comment]
# Add a new workflow

- **Label:** Restricted archive workflow
  - _We should make sure everyone agrees this is the best name_
- **Machine name:** restricted_archive
- **Workflow type:** Content moderation

## States

### Draft
- **label:** Draft
- **machine name:** draft
- **Published:** Not checked
- **Default revision:** Not checked

### In review
- **label:** In review
- **machine name:** review
- **Published:** Not checked
- **Default revision:** Not checked

### Approved
- **label:** Approved
- **machine name:** approved
- **Published:** Not checked
- **Default revision:** Not checked

### Published
- **label:** Published
- **machine name:** published
- **Published:** Checked
- **Default revision:** Checked

### Archived
- **label:** Archived
- **machine name:** archived
- **Published:** Not checked
- **Default revision:** Checked

## Transitions

### Edit
- **label:** Edit
- **machine name:** create_new_draft
- **from:** Draft, In review, Published, Archived
- **to:** Draft

### Review
- **label:** Review
- **machine name:** review
- **from:** Draft, In review
- **to:** In review

### Approve
- **label:** Approve
- **machine name:** approve
- **from:** In review
- **to:** Approved

### Publish
- **label:** Publish
- **machine name:** publish
- **from:** Draft, In review, Approved, Published
- **to:** Published

### Archive
- **label:** Archive
- **machine name:** archive
- **from:** Draft, In review, Approved, Published
- **to:** Archive

### Restore from archive to published
- **label:** Restore from archive to published
- **machine name:** archived_published
- **from:** Archived
- **to:** Published

### Restore from archive to draft
- **label:** Restore from archive to draft
- **machine name:** archived_draft
- **from:** Archived
- **to:** Draft

## This workflow applies to

- Service Region
  _- Might be a good first content type to use this on since there's no existing content unlike VBA Facilities_ 
- Overtime this list can be expanded once we verify everything works as intended on Prod
 
## Workflow permissions

**Comment by davidmpickett** [comment]
For historical purposes a slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1693583415389719
And a bunch of images

![workflow_config_restricted](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/163a3f5f-17d4-40b2-842b-2c6696c76418)

![all_transitions_restricted](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/ab09419b-4065-4f81-bba5-a5b2b2685c1d)

![edit_transition_restricted](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/6dde36af-3519-4546-b811-5aad847ff0ff)

![content_publisher_permissions](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/6beaa9bc-87d6-4628-ade1-20fee5ded569)

**Comment by davidmpickett** [comment]
Per conversation in refinement today about [follow up ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334), this is complete.

**Comment by omahane** [comment]
@davidmpickett I don't see a role that can create Service Regions. Is that intentional?
<img width="1947" alt="Screenshot 2023-10-26 at 10 58 30 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/72d891ba-d14a-49b6-b354-bf42be06617a">

**Comment by davidmpickett** [comment]
> @davidmpickett I don't see a role that can create Service Regions. Is that intentional? 
Correct. This should be limited to Content Admins and Administrators. Content Admins get this power without it having to be checked in the permission matrix

**Comment by omahane** [comment]
@davidmpickett (cc: @swirtSJW )
I have run into a roadblock. I can't make this transition:
<img width="354" alt="Screenshot 2023-10-26 at 1 02 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/de8f2a2a-afd1-4f96-8329-fd5e4584dd4d">

I get an error, but I don't really know why:
![Screenshot 2023-10-26 at 1 04 21 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/e184da7a-6967-4cc2-96db-07747f2cb883)

**Comment by omahane** [comment]
The answer, per Dave Picket on [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1698344723049599?thread_ts=1698336088.394329&cid=C0FQSS30V) was to removed "Archived" from the "from" of the "Edit" transition
