### ISSUE TITLE
Design: Standardize spotlight patterns in CMS facility content types

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13804]
## Description
The Health services list and Vet Center content types in the CMS both have spotlight/featured content but they have different CMS fields and different displays on the front end. These should be updated to be standardized (follow VBA).

This was discussed in #14981 with a decision to "leave the spotlight section as is (for VBA), with blue boxes and in the same location. We can review this along with it's placement on Vet Centers at a later date."

This is for Drupal alignment with Front end.

## Design
Spotlight content page in [VAMC facilities Figma file](https://www.figma.com/file/bwnxdqh3b7W7Xp6KuQ4Sab/VAMC-facilities?type=design&node-id=117%3A2&mode=design&t=DZ6N66EaX8jY2D0w-1)

## Acceptance Criteria
- [x] Spotlight content is standardized across products
- [x] Review with accessibility 
- [x]  Review with content design 
- [x]  Review with engineers 
- [x]  Schedule review with UX Lead
- [ ]  <del>Create CMS Collab Cycle ticket for async review (tag Erika Washburn, Marisa Dominguez, Steve Rancour on CMS)</del> this process is changing, for now VA UX/PO reviews will take it's place
- [ ] Stub follow up tickets or tag PO to stub subsequent tickets.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment]
Just adding some screenshots and examples for clarity. The multiple blue boxes are currently used in two places (and soon to be a third with VBA regional offices). 

[VAMC health services page ](https://www.va.gov/chicago-health-care/health-services/)

![Screenshot 2023-10-27 140543](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/31d3d3bf-ac42-4fb0-8990-f8e9a271a2df)

[Vet center page](https://www.va.gov/evanston-vet-center/)

![Screenshot 2023-10-27 140607](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a1f81ce1-0b5a-4e83-8d4c-7e274b3aee04)

The single blue box approach is used on VAMCs. It is controlled at a System level, but shows up on multiple front end pages

- https://www.va.gov/chicago-health-care/
- https://www.va.gov/chicago-health-care/locations/jesse-brown-department-of-veterans-affairs-medical-center/

![Screenshot 2023-10-27 142408](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a694bbba-8484-49db-af24-d564e29e7a03)

**Comment by davidmpickett** [comment]
- Vet Centers are using `Featured content` paragraph type
- VAMC Health Services lists are using `Link teaser` paragraph type
- This hasn't been added to the VBA Facility content type yet
- VBA centralized content is using 'Featured content` paragraph type for 3 national 
- VAMC Health Services lists should probably switch to using the `Featured content` paragraph type for consistency

**Comment by xiongjaneg** [comment]
Per Dave in [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1698439529618469?thread_ts=1698432339.370229&cid=C0FQSS30V)

Want to point out that [@Laura Flannery](https://dsva.slack.com/team/U03JU991LCW)
 original point in filing [#13804](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13804) was to note a discrepancy in the CMS/editorial interface that is independent of FE display. Fixing that issue looks like:
content modelling > Drupal field migration > FE query update
Updating the FE display to use new components is a separate piece of work that would be more like:
Product design > FE template update

**Comment by laflannery** [comment]
@xiongjaneg I found [a comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13808#issuecomment-1561380641) that an AC was added to this ticket back in May and turns out it never was. I think technically the second AC you added here might cover it, but ultimately we want to make sure that the spotlight patterns use components when available or we consider componentizing them and I want to make sure that doesn't get lost.

**Comment by xiongjaneg** [comment]
@laflannery I added an AC that hopefully captures the missing AC but please edit if it doesn't quite capture the intent. Thanks for flagging!

**Comment by aklausmeier** [comment]
updated ticket with link to [Featured Content VADS V3 component](https://design.va.gov/components/featured-content#examples---v3) that we need to align with

**Comment by aklausmeier** [comment]
CMS Collab cycle will follow same ticket creation process with async review, no kickoff needed [slack thread with CMS for reference](https://dsva.slack.com/archives/CT4GZBM8F/p1710346833420779)

**Comment by thejordanwood** [comment]
@aklausmeier @laflannery @davidmpickett @omahane This is ready for your review! I've been working on aligning this across Vet Centers, VBA Regional Offices, and VAMCs. As Laura suggested in the ticket, we're going to align with VBA/Vet Centers. 

I've also been working on aligning the Drupal design with the card component we're converting the spotlight pattern to. I've captured some FE use cases in [this Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=108%3A1696&mode=design&t=L2QS63BvovclEcLv-1). In some of the use cases, editors for Vet Centers are using email addresses and phone numbers as CTAs instead of links. In other cases, they're using a combination of a phone number and link as a CTA. 

My recommendation is to encourage editors to only use one CTA, whether that be phone, email, or a link. I've explored that possibility in [this Figma file](https://www.figma.com/file/bwnxdqh3b7W7Xp6KuQ4Sab/VAMC-facilities?type=design&node-id=117%3A2&mode=design&t=y0ikgJQmRafuxjaA-1). The design would be similar to the Events content type, where we use conditional formatting to show different fields depending on what the editor chooses. 

We can discuss this in UX sync if that would be easier!

- @omahane I'm wondering if using conditional formatting here is possible?
- @laflannery Will using conditional formatting in this way be accessible?

**Comment by aklausmeier** [comment]
@thejordanwood left comments in the Figma file, looks like we need a mockup for the system level as well

**Comment by thejordanwood** [comment]
@aklausmeier Thanks! I just put in a mockup for the system level.

**Comment by davidmpickett** [comment]
@aklausmeier @thejordanwood - I took some of my concerns about the Link Collection variant from the Figma comment threads and spun up a [new ticket stub](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17624) for future consideration

**Comment by thejordanwood** [comment]
@omahane We reviewed this in UX sync, but I wanted to make sure I got your eyes on this too. 

For spotlight news sections, I'm proposing an MVP state that would align VAMC with Vet Centers/VBA. The next step would be to introduce conditional formatting to the CTA section. A bit more context can be found in [my previous comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13804#issuecomment-2009930266).

For spotlight sections that have relevant links, my suggestion is to remove the Title and Link summary fields. I've been told these don't map to the FE.

**Comment by omahane** [comment]
@thejordanwood I looked at the Figma, and I don't see any glaring issue. It looks very useful, in fact, in both the MVP and longer-term future state. The showing and hiding of fields based on a previous selection should be possible. 

When we go about implementing this, though, I think we need to be considerate of the [entities that currently use CTA](https://prod.cms.va.gov/admin/reports/content-model/entity-diagram/paragraph/button?max_depth=2):
![Screenshot 2024-03-26 at 10 54 39 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/e0a20b95-ce6e-40d1-bc17-2b5a54fb8dc9)

It would make sense to create a "spotlight CTA" that is distinct from the current one so that we don't have to figure out how to backport all of these fields to other entities and address what would be pretty extensive change management in terms of UX. As I was out for the last UX sync, I can't say for sure whether this has already been considered.

**Comment by aklausmeier** [comment]
@thejordanwood for our future selves, can you add @omahane's screenshot to our Figma file. That's a big bowl of Drupal spaghetti.

**Comment by thejordanwood** [comment]
@aklausmeier Just added that!

**Comment by jilladams** [comment]
Not sure about the state of review with Amanda - are we clear on this ticket except for ticketing next steps? 

Have also noted in epic the things we'll need to consider re: ticketing, when we get there: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15931#issuecomment-2021836133

**Comment by thejordanwood** [comment]
@jilladams Yes, I believe this ticket is ready to close. I agree that any additional tickets can be created later. 

Feel free to add any additional feedback you may have though @aklausmeier!

**Comment by aklausmeier** [comment]
@jilladams final review done, looks good, ok to spin up next step ticket and close

**Comment by jilladams** [comment]
From Figma review (#13804): my understanding of next steps for ticketing MVP is brain dumped below -- @thejordanwood could you sanity check, and if this is right, I'll work on ticketing (2 questions below): 

### VAMC Health Systems page:
update Common Links > Link teasers section: 
* Link Text field: 
    * add help text (present on VBA RO Local spotlights > CTA > link text field)
    * add character counter
* Remove Link summary field
* @thejordanwood (@aklausmeier ) one question: for Systems, the link field still has label URL instead of Link, like the others. Is that intentional?

### VAMC Health services pages
Update "Featured content on health-services page" section to match VBA "Local spotlights" treatment.
* Update header
* Add Title field with helptext & character counter
* Add Description rich text field with helptext & character counter
* Convert "Link teaser" to VBA's "Call to Action" treatment, including:
    * Link Text field: 
        * add help text 
        * Add character counter
    * remove Link summary

Also: @mmiddaugh the designs include a stop-gap update for VAMCs, and a bigger overhaul to address specific use of phone / email as CTA. I can go ahead and build out those tickets, if we think this is something to go ahead and queue up / get refined for implementation? Not sure where that sits in priority, relative to All The Things. Will add to product sync Qs for Monday.

**Comment by thejordanwood** [comment]
@jilladams These are my notes about the VAMC health system pages. The VAMC Health services pages section looks good to me. 

**update Common Links > Link teasers section**

- We're also removing the Title field. This isn't really where the title is controlled in Drupal. 
- Yes, it's intentional. I think the URL/Link fields are using different Drupal modules? I really can't remember the exact reasoning they're different, but have a vague memory of being told this in the past. I decided to keep this as URL since that's what it already says.

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17688 created! Closing.
