### ISSUE TITLE
Defect: Editor content not showing on front end 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13838]
Should the Any information that is additional to any time-sensitive situation updates field be limited or removed? I am only able to find 12 instance where this field was used but cannot find anywhere the text supplied in this field is actually displayed to end users. (Example: /node/49282/edit and https://www.va.gov/sierra-nevada-health-care/operating-status/ - the Air Quality Banner Alert does not include the text from this field)

**Comment by laflannery** [comment]
@kmariepat-cityfriends I had done some research a couple months ago regarding rich text editors in the CMS and I believe I might have some info for you on this.  I will review what I have today/tomorrow and get back to you

**Comment by laflannery** [comment]
@kmariepat-cityfriends I had done a previous audit of all Full rich text editors in the CMS so I knew this was showing somewhere (otherwise I would have noted it) and this is what I found, hopefully it helps:

This field is showing on the front end, it shows on the Operating status pages but it appears to be conditional based on Situation Updates - if there are no Situation updates, the Situation information will not show.

**Examples:**

- VA Shreveport
  - [CMS Node link] (https://staging.cms.va.gov/node/33054/edit)
  - There are no Situation Updates and but there is content in the Situation information field
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5778df1e-265f-409e-a7a9-2b5e82e53351)
  - On the [operating status page](https://staging.va.gov/shreveport-health-care/operating-status/), this display under the "On this page" ToC
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/8c46bfa5-8064-4bec-9fd8-a560a898b1ac)

- VA Wilmington
  - There is 1 Situation Update and there is content in the Situation information field (even though you can only tell from the source view)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/b2ea0ea6-06f7-40a4-aac6-d0570c3f62f1)
  - On the [operating status page](https://staging.va.gov/wilmington-health-care/operating-status/), no situation information is displayed under the "On this page" ToC
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/d34b8f8d-eb08-4650-90e9-5a9a0a89efca)


### Additional Notes
- This conditional display also seems to be supported if you read the help text or field label for these fields in the CMS closely:

> For "static" situation information that is additional to any situation updates.

> Any information that is additional to any time-sensitive situation updates

If it's "additional" to a situation update then that probably makes sense that it shouldn't show on it's own.

- From my audit, I had a recommendation that:
  - From what I was seeing, I felt that a limited rich text editor should be used here instead of a full editor because headers shouldn't be needed. I felt that the editors shouldn't be adding so much information that it would need to be broken out into sections with headings.
  - NOTE: That this was simply an observation/recommendation, not anything that was reviewed or determined to be a defined direction by a PO.

**Comment by Agile6MSkinner** [comment]
So what's the final story on this one, @laflannery? I feel like closing it...

**Comment by laflannery** [comment]
I don't believe [the original question](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13838#issuecomment-1563197595) ever got answered.

But for my part I had a separate recommendation (that came from when I was on the CMS team) that this should be changed to a limited rich text editor to limit the number of heading violations the editor could create

**Comment by Agile6MSkinner** [comment]
Ok, I don't think it has a champion anymore then. I'll close this and we can talk about the rich text editor on it own merits.
