### ISSUE TITLE
Create new content model document for `VAMC System Banner Alert with Situation Updates`

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13841]
- [x] I expect there is a content model document that references `VAMC System Banner Alert with Situation Updates`
- [x] document the internal workings of pushing to gov delivery and other processes aligned to `VAMC System Banner Alert with Situation Updates`
- [x] some documentation exist in the readme's that can be put into the new content model doc created here

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends This should be all set now. There is no PR for this so moving it directly for your review.

I did the following:

- Moved our existing documentation into a [CM Document](https://prod.cms.va.gov/admin/structure/types/manage/full_width_banner_alert/document) in the CMS
- I linked that document too all related code entries and documentation external to our team that I could not move into the CMS
- I [created a diagram](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/vamc-facilities.md#system-banner-alerts-and-situation-updates-to-govdelivery) that fully displays the relationship between the three systesm (CMS, content-build, and Granicus GovDelivery)   The diagram is in mermaid so had to live on the README instead of in the CM Document directly, because at the moment we do not support Mermaid in the CMS.
- Followed up on tracking down monitoring that was supposed to be put in place by platform team.
-

**Comment by swirtSJW** [comment]
@omahane I would like to have you review this document and the related connections to make sure it makes sense to you, and you are really good with the wordseses.
https://prod.cms.va.gov/admin/structure/types/manage/full_width_banner_alert/document

**Comment by omahane** [comment]
Moving for @kmariepat-cityfriends to close.
