### ISSUE TITLE
Wrap SMS text numbers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13934]
## Issue Description
Vet Centers frequently add information about the Veterans Crisis Line in their Suicide prevention accordions. The Crisis Line is available by phone, chat or text. If they add the text number, we should make it actionable so Veterans can click on it with their mobile device or assistive tech. 

![image](https://user-images.githubusercontent.com/55411834/159969381-4d7807dd-e0be-4401-9d55-8bb7087a541c.png)

---
## Tasks
- [ ] Add logic to identify text/SMS numbers and make them actionable

## Acceptance Criteria
- [ ] Veterans can use the text number to generate a text from their mobile device or using assistive tech

**Comment by eselkin** [comment]
988 is wrapped
I can't find the short SMS code in the text anywhere (I'm assuming that was replaced by 988).
I think this is not an issue any longer @jilladams @mmiddaugh 

However, I think there is a somewhat related issue with extensions in office phone numbers not always being wrapped. But maybe they aren't capable of being wrapped.

**Comment by jilladams** [comment]
Nice! I checked the backlog for extensions to see if that's known / filed and only found some extension-related issues for the Drupal side: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23260
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14238

Since this no longer repros, closing. @eselkin since you saw it happening today, could you write up a ticket re: the extension issue in the FE? That'll give us a breadcrumb to follow re: investigating whether or not it's possible to wrap them.
