### ISSUE TITLE
Research: Digest PACT Wizard mural and provide UX guidance on flow, recruiting strategy

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13965]
### User story

**AS A** Researcher
**I WANT** to review and provide feedback on the wizard flow from the perspective of a researcher and research participant 
**SO THAT** we can identify options and tradeoffs around prototyping for research.

### Engineering notes / background

Danielle Thierry's [PACT Wizard mural](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1679940171177?sender=uebde62ceb342c6477fb09406&key=d5f8d645-fad9-42ab-be60-1be6c75c08aa).

## Acceptance criteria

- [x] Reviewed mural and formulate recommendations
- [ ] Hypothesized how recruiting strategy could reduce need for branching logic
- [ ] Met with Danielle about feedback and next steps toward prototyping, recruiting, research planning

**Comment by wesrowe** [comment]
Meeting set for 6/14: Danielle, Cindy, Wes

**Comment by cindymerrill** [comment]
@wesrowe I reviewed the Mural closely, and I made an outline of all the survey logic we need in order to avoid asking users anything that we can figure out the answer to (see outline below). I also added comments to Danielle in the Mural about survey logic conditions that didn't appear correct. It doesn't seem like prototyping this with multiple surveys in Optimal Workshop is going to work because there are so many checks when branching and when deciding to ask specific questions to see if in the user's years of service.

- ask for service years and whether served outside US
- _if served outside US_
	- if service includes any time 2001-present, ask re location after a date
	- if service includes any time 1990-present, ask re location after a date
	- if service includes 1962-1975, ask re location and date range (SWAP w/next Q?)
		- if N and service includes 1962-1980, ask re another location and date range
			- if N and service includes 1962-1976, ask re another location and date range
				- if N and service includes 1972-1977, ask re another location and date range
					- if N and service includes 1967-1971, ask re another location and date range
						- if N and service includes 1969, ask re another location and date range
	- if service includes 1977-1980, ask re location and date range
	- if service includes 1966-1967, ask re location and date range
	- if service includes 1968, ask re location and date range
- _if didn't serve outside UX and service includes 1962-1986_
	- ask 3 q's; stop if get Y
- _if service includes 1953-1987_
	- ask 1 q

**Comment by cindymerrill** [comment]
Are we going to test/prototype the questions about health conditions, too?
Are we going to test/prototype the results screens?
@wesrowe

**Comment by cindymerrill** [comment]
@wesrowe Want to talk about this before our meeting with Danielle next week? We could recruit by service dates, but it's quite possible that someone with a long time in the military could have service dates that overlap multiple date ranges.

**Comment by cindymerrill** [comment]
@wesrowe I scheduled a meeting with you on Tuesday, and just scheduled another one with you on Monday because as a result of conversations I had with two other Ad Hoc researchers, I'm thinking that finding out more may help us decide how to prototype. I have questions for us to discuss in the new first section of my [research brainstorming doc](https://www.google.com/url?q=https://docs.google.com/document/d/1pct0qlJEC_UAoKp85QNnab1p109YYEN_Y5qJMYDgbmw/edit?usp%3Dsharing&sa=D&source=calendar&ust=1686786252507190&usg=AOvVaw35HVfFVunla4ODIa0GQHSs): **Questions to answer to inform prototyping options**.

The questions are about research outcomes and prototype requirements, including the following:

- What are we trying to learn from this research?
- What are potential outcomes of this research?
- How important is it that participants interact directly with the prototype to see the question and select a response?
- How important is it that the prototype be accessible to screen reader users? Since there’s no front end to test, I would think we could wait until later.

**Comment by cindymerrill** [comment]
Danielle updated her Mural with questions, and so I've updated my outline of the survey flow accordingly:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/69914583/f291336e-c840-4602-9e08-4d041f49f4fa)

This can be seen in my [research brainstorming doc](https://docs.google.com/document/d/1pct0qlJEC_UAoKp85QNnab1p109YYEN_Y5qJMYDgbmw/edit?usp=sharing).

**Comment by cindymerrill** [comment]
And here's a quick summary of the service years covered by Danielle's questions:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/69914583/2d7eebeb-aa34-4b3a-b15d-1c5b7add7b4b)

This can be seen in my [PACT Act Wizard years in questions spreadsheet](https://docs.google.com/spreadsheets/d/1oUsQO8dCuN3-mxYuEUXpGJAvM7sh3tjoCa53eM7AxFg/edit?usp=sharing)

**Comment by cindymerrill** [comment]
FYI @randimays

**Comment by cindymerrill** [comment]
Obtained an Optimal Workshop license and signed in to test survey branching logic. Confirmed that branching can happen based on single-select questions (radio buttons) but not multi-select (checkboxes), but chatted to customer support to confirm.

**Comment by wesrowe** [comment]
Research goals: 

- DT: Get a sense of whether these questions are “too much” – particularly someone who could have served in multiple “eras”, multiple branches of tool – is it an overwhelming number of questions? Are the questions too hard?
- Concerns:
  - Number of questions
  - Difficulty of questions
  - Results screen - can results be delivered in a way that participants understand? Note: We’re not getting into conditions, which are a key condition for getting disability benefits.
- There is a [new mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686687282873/beba3bd2c148677a82aa5b5c59a4f550e82d98e1?sender=uf8ddb00f0c9a241ee4573555) where dates are shifted to the results screen
  - Shifting dates to the results screen simplifies questions but complicates results
  - The prototype could enable testing of multiple versions of the results screen pretty easily; we think we're comfortable with the prototype screens not reflecting every nuance for every situation.

Next steps:
- DT to run new date-later approach by stakeholders for approval
- OW should work
- When content is final/approved, we can write research plan

**Comment by cindymerrill** [comment]
Today's scheduled CodePen meeting was postponed until next Monday. This meeting is input to making the prototyping decision. FYI @wesrowe @jilladams

**Comment by wesrowe** [comment]
@cindymerrill, I thnk that meeting was more relevant to another PACT ticket, #13722 or #14033. I would close this one.
