### ISSUE TITLE
Prep for Facility Locator Design Intent 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14011]
Design Tasks 

- [x] Conduct Design review with PM, PO, and other stakeholders 
- [x] Iterate on Designs based on design review

PM Tasks 

- [x] Update [Product Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/README.md)
- [x] Create KPIs
- [x] Schedule Design Intent

**Comment by jilladams** [comment]
My notes from today's design review: 

**Regarding Community Care results:**
Community Care can use type ahead. The data source does not make it possible to have user-friendly, plain language search results, as the data is driven by insurance coding terms. So: we should expect a UX difference here.

**Breadcrumbs:**
* "Browse VA facilities..." should become "Browse VA locations..."

**State**
* State dropdown will convert to become a search field
* List of State names with link will be removed
* State list of results: 
    * are filtered by state, then sorted alpha by facility name.
    * Paginated results, 50 per page
    * Performance: loading all facilities for a state, paginating in the browser, may be a performance risk . Swirt noted we could build this statically in the future. This is a detail to consider when we get to implementation.

**Comment by thejordanwood** [comment]
@kmariepat-cityfriends I've iterated the design in [the Sketch file](https://sketch.com/s/d5e5c924-e8c0-47af-b3e4-994c335d6f31) based on the feedback we received in UX refinement. The design changes I made:

**Search by state flow**
- The state dropdown was changed from a dropdown to a search bar with the help text "Search by state or territory" added
- The list of states on the entry page was removed
- Text was changed from "VA facilities" to "VA locations" in the breadcrumbs, header, and links at the bottom of the page
- VA facility type is now a required field

**VA health flow**
- The text in the dropdown was changed from "Search all VA health services" to "See results for all VA health services" to clarify that users are able to see results for all services instead of just one. I'm still in the process of getting feedback on this change to determine if the wording is clearer now.

<img width="414" alt="Screenshot 2023-06-30 at 3 41 53 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/b3a78966-a675-45dd-928a-4a51e40dcc74">

**Comment by thejordanwood** [comment]
@jilladams I just read over your notes. I think the paginated results on the state flow will only show 10 at a time, not 50. We should check with a dev to confirm this.

**Comment by mmiddaugh** [comment]
[Initiative Brief - Facility Locator Search Improvements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/search%20improvements/2023-initiative-brief.md) now available 
Baseline analytics pending

**Comment by thejordanwood** [comment]
Design intent has been scheduled for Friday, July 14 at 10:30 CT.
