### ISSUE TITLE
I.L. FE: Remove "expand/collapse all" button from Results screen

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14049]
### User story

**AS A** Veteran
**I WANT** not to be encouraged to open all accordions at once
**SO THAT** I can stay focused on my particular income and not burden my cognitive load.

### Engineering notes / background

This change was discussed [in slack](https://dsva.slack.com/archives/C52CL1PKQ/p1683306422235739) with Laura, who confirmed there is no a11y reason to include the button.

## Acceptance criteria

- [x] Each accordion on Results screen has to be tapped to open (no "expand all" option)

**Comment by randimays** [comment]
The Platform Design System doesn't support a multiselect without the "Expand all" button. [See various implementations here](https://design.va.gov/storybook/?path=/docs/components-va-accordion--default). The only thing that removes that button is to make it single select, which we don't want. I tried manually removing the "Expand all" button via CSS, but it's in the infamous shadow DOM which I cannot target directly (shadow DOM is like a firewall to the end user; only the authors of the code can make changes to its styling).

I [consulted with the design team](https://dsva.slack.com/archives/C01DBGX4P45/p1687546318385499) to see if there was a secret-ish way to get this done. They made a suggestion, but it causes a weird flickering behavior because it's kind of hacky for our use case.

So - I [created a bug](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1872) per their guidance to support our use case. In theory, it should be a quick code change (just passing a prop to say "I don't want the expand all button").

In the meantime, we are **blocked** on this ticket until we can get that bug ticket done on the design system side.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1687880009192279
> we should keep the one-at-a-time version without expand all

^ Decision
