### ISSUE TITLE
VBA: Review and Incorporate Feedback from sitewide content IA team

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14123]
[Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58511#issuecomment-1624302843)

**Feedback to address in Sketch design** 
- [x] Update intro paragraph per [comment in sketch](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff?annotation=e7f6d52e-1d66-4562-a154-9c2428ffeb50)
- [x] Update text under Office hours header per [comment](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff?annotation=4c041948-4ceb-4c0f-a1af-07e9460deca2)
- [x] Update all instances of "click" to "select" per [comment](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff?annotation=a3b2675b-1e61-4d3f-9829-167129f58691)
- [x] Change "&" to "and" for Family member & caregiver benefits header per [comment](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff?annotation=dd9ffc74-c2ca-4b41-a386-81f7c3f228d8)
- [x] Update the heading on the follow closed service accordions
  - [ ]  Military sexual trauma care -> Military sexual trauma-related claims
  - [ ] VA home loans  -> Home loans (also moves up to stay alphabetical) 
  - [ ] Veteran readiness and employment programs -> Veteran Readiness and Employment programs
  - [ ] Veterans pension -> Veterans Pension
  - [ ] Benefit letters & decisions -> Benefit letters and decision letters
  - [ ] I made [a comment with a simple text list](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14123#issuecomment-1626066849) of all the closed service accordions for easy reference
- [x] 🛑 Update "Can't find the service you're looking for?" alert [per comment thread](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff?annotation=a1f297c5-a12e-4acb-ae38-0d6f0aaec3fd) (🛑 awaiting response from SCAIA to my follow up questions) 
- [x] 🛑 Remove all "top tasks" from closed service accordions (🛑confirm with Alexis the research implication)

**Feedback to address in usability research plan**
- [ ] Removing Top Tasks from closed service accordions 
  - Hypothesis is that Veterans can find the appropriate accordion without this information. If we find during usability testing that they need more information, then we revisit the design. If we were to go forward with having all the tasks in the prototype, we wouldn't necessarily get data that showed if that information was necessary or not. 

**Feedback to address in VBA service taxonomy** 
- item 1
- item 2

**Comment by mmiddaugh** [comment]
@kmariepat-cityfriends this feedback will not impact Jordan's design but will likely lead to some Drupal adjustments for VBA in the short term and as backlog issues for VAMCs and Vet Centers.

The Content/IA team has suggested that VBA service "tasks" should be housed as separate attributes from the common conditions attribute to avoid making those harder to parse in the future and so that the taxonomy in general might be able to leverage these separate categories. 

---

**Examples:** 
a potential VBA service named `Burials and memorials` might be associated top tasks like `apply for burial benefits`, `get a burial flag`, and `request a Presidential Memorial Certificate`

`Women Veteran care` appears on VAMC pages listing the following "common conditions": `women's primary care, mental health, obstetrics and gynecology, pap smear, mammogram` - some of which might be closer to a task or procedure than a  a condition 

---

<details>
<summary> The taxonomy already allows us to define the attributes of a given taxon for Vet Centers differently from VAMCs (while keeping the taxon itself stable) </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/0a43a20b-d28a-4b46-bda7-4746983baae6)

</details> 

---

Two areas to address:
- VBA patient friendly name (as labeled in the editorial experience) -> Plain language name (or something similar which does not refer to Veterans visiting VBA locations as "patients"
- Tasks(?) rather than "common conditions"

**Comment by jilladams** [comment]
From UX refinement: 
* Use this ticket for comms on content when it comes in
* DaveP / Michelle to review and parse out: now, next, later / Design steps / research steps
    * Keep final content in a shareable state (Github?) with a final statement of verbiage for designs

**Comment by davidmpickett** [comment]
**Veteran benefits**
- Burial in a VA cemetery
- Careers and employment
- Disability compensation
- Education benefits for Veterans
- Home loans
- Homeless Veteran care
- Military sexual trauma-related claims
- State and local benefits
- Veteran Readiness and Employment programs
- Veterans Pension

**Family member and caregiver benefits**
- Burials and memorials
- Compensation benefits for family members
- Education benefits for family members

**Service member benefits**
- Pre-discharge claims
- Returning service member care
- Transition help

**Other services**
- Benefit letters and decision letters
- Financial services
- Medical records
- Military records
- Veteran profile information
- Veterans Service Organizations

**Comment by davidmpickett** [comment]
Met with @mmiddaugh @ALogsdon3 @thejordanwood today and we decided to move forward with removing the "top tasks" from the closed service accordions.
**Rationale**
- Aligns with [recommendation from SCAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58511#issuecomment-1624302843)
- Aligns with existing service accordions on VAMC and Vet Center where this space is reserved for "Patient-Friendly Name." While VBA services should be plain language already, we can't guarantee that they always will be, or other types of alternate names wouldn't be useful in this space
- More likely to hear from Veterans that they need more info on the closed version of the accordion if we remove this info than the resverse

**Action items**
- Jordan will remove from Sketch file
- Alexis will review research plan and conversation guide for possible rewording or questions/tasks
- Dave will work on updating interior of accordions

**Comment by davidmpickett** [comment]
Most feedback incorporated. Other feedback will be incorporated in later artifacts and has been noted in relevant tickets 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10473
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13960
