### ISSUE TITLE
BE: Enhance "magichead" error messaging around Depth/hierarchy in accessible UI

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14289]
### User story

**AS A** Content Admin using the accessible version of the magichead UI
**I WANT** error messaging to be clear when I manually pick a "bad" depth value and try to save
**SO THAT** I understand what I need to do to fix depth values and save, consistent with patterns elsewhere in CMS.

### Engineering notes / background

In the case of hierarchy issues, we need validation error messaging to direct the Editor clearly to the one field (per Section) that is preventing save: the Depth field.

#### Existing screenshots (from [tugboat](https://cms-**sszuuulgluyv7apczcgnke3zom2tnz5x.ci.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/add))

- validation error message is the same at top of page and under Depth field
<img width="368" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/6a99a570-890b-48ba-8ade-baa11c41408b">

- validation error is highlighting all the fields in the problem section
- the same error message appears under every field
<img width="805" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/61121f0e-2166-4b1e-8264-1a30eba38637">

## Acceptance criteria

When one or more Benefit Overview Sections has a Depth validation error:
  - [ ] The message at the top of the UI follows the pattern (which drupal gives us for free): `[number] error(s) has/have been found: Depth for Row X`

  - For each overview section with a depth error, 
    - [ ] only the Depth field is highlighted red and has an error message below it
    - [ ] in the case that the depth entered is greater than the max allowed, error message is: `Maximum depth allowed is [insert max depth value for instance (2 in Ben Tax)]`
    - [ ] in the case that the depth entered is less than zero, error message is: `Depth must be a positive integer`
    - [ ] in the case that the depth entered breaks the hierarchy rule, error message is: `Depth for a Section cannot be more than 1 greater than the Section immediately above it`
    - [ ] The other fields besides Depth have normal borders and no error message

  - For Sections without errors:
    - [ ] No fields are marked red, no errors

**Comment by dsasser** [comment]
@wesrowe 
In general, handling error display on the client-side based on the state of the "accessible/show row weights" option is challenging. See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14290#issuecomment-1625806024

> Only the Depth field of any Overview Section is highlighted red and has an error message below it

The challenge with this would be that the depth field isn't visible unless 'show row weights' is selected. We would need to work out how to show the depth field anytime there is an error on the widget, but only depth field errors. And this means wrestling with the functionality provided by the Drupal core tabledrag javascript, which adds risk/yet unknown factors to this request.
Lift: High

> The message at the top of the UI follows the pattern "[number] error(s) has/have been found: ['Heading depth' or similar]"

Since core provides the error display/handling, manipulating the overall message is not something achievable without a core patch. What we can do is provide the error message for the validation at the instance level.
Lift: ~

**Comment by thejordanwood** [comment]
@wesrowe Here are my suggestions. We may need to discuss the field error message a bit more–this one is tricky!

**Top error message:**
[number] error(s) has/have been found: Section depth

**Field error message:**
Please enter a number +1, equal to, or -1 than previous section depth.

**Comment by wesrowe** [comment]
Needs finalized error message text – Wes to obtain

**Comment by wesrowe** [comment]
Error message needed.

Draft to try: `Depth entered doesn't have a logical parent above it. Any section of depth N must have a section of depth N-1 somewhere above it. (The top section is an exception, it must have depth 0.)`

@thejordanwood and @laflannery, wondering if 1) that's accurate and 2) not too wonky?

**Comment by laflannery** [comment]
@wesrowe Is this error message being seen by editors? Or is this some sort of engineering validation error message that regular people would not see?

If editors are going to see this, I think it's confusing, mostly because I'm confused. Would the "N"s be replaced by actual numbers to make this less confusing?

**Comment by thejordanwood** [comment]
@wesrowe I'm getting a bit confused about what the error message should say. Could the section depth number be equal to or greater than the section depth above it?

For example, the above section depth is 2. The section below that could be a 1, 2, or 3. It can't be a 4 because that would be skipping section depths. 

I also agree with Laura that using "N" is confusing. Even using the phrase "logical parent" is confusing to me because the logic is hard to understand and the user also has to understand that we're talking about parent/child relationships here.

**Comment by wesrowe** [comment]
I actually hallway tested the concept of "parents" and found it was not intuitive to Justin.

**Comment by wesrowe** [comment]
We might need @chri5tia or @dsasser to explain what the actual validation rules are so we can try to put them into language. 
- I believe you can always go "shallower" from the one above, all the way to zero, regardless of what's immediately above.
- and then you can only go one deeper than the heading immediately above? is that right?

**Comment by jilladams** [comment]
From sprint planning, Daniel noted: This is the current message being used today:
“Please enter a number +1, equal to, or -1 than previous section depth"

**Comment by dsasser** [comment]
Confirmed in production:
![Screenshot 2023-08-28 at 1 19 27 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/947b4a0d-9cbf-4a6d-8ebe-245ebc7bb10e)
![Screenshot 2023-08-28 at 1 18 03 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/c52780d8-2a8b-4311-944c-916d4dd1396b)

**Comment by wesrowe** [comment]
It looks like we need to set the max depth to 2 for the Benefit Taxonomy to get the desired end result – Header, sub-header, sub-sub-header. Asked in slack if a new ticket is needed.
