### ISSUE TITLE
Update codeowners for va.gov-cms repo

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14342]
## Description
By default, the CMS Team will own all code in the repo. Then as we can start separating code out, we can start adding product teams as owners of specific sections of code, i.e. custom modules,.

## Acceptance Criteria
- [x] Create CMS Platform Team in GitHub, make all engineers on the CMS Team members
- [x] Update `.github/CODEOWNERS` to make CMS Platform Team the default owner of all code. (Use devops repo for pattern)
- [ ] Socialize with CMS Team and product teams using collab cycle meeting placeholder
- [ ] Document changes

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
This looks good!

I feel like this is going to be a multiple-ticket project because it impacts multiple teams. Plus: do we have PO buy-in from Erica? The other PO's? Was this their idea?  I'm not clear on the genealogy of this particular initiative, so it'd be good to document it here.

## Thoughts

Announce our general plan, discuss it with Jill, Wes, everybody else. Maybe this isn't necessary because that's already done, but I'm out of the loop here and would like to know what understanding already exists here from the other POs/PMs/DMs, and what has been socialized to ICs.

Open a PR with a draft of the initial CODEOWNERS file, allow comment/solicit modifications for a few days or a sprint. Maybe two sprints. 
  - This should discuss what code ownership actually signifies in this context.
  - This should enumerate code we need to manage ownership of, like:
    - sections of config, probably, like certain content types, etc. This might get gnarly.
    - contrib modules that are critical to certain functionality. If we're responsible for merging Dependabot updates, and the PR passes the tests, then I feel like we need to have an understanding of whom to reach out to to ask for a review of that contrib module. Otherwise it's merge by default, I feel.
    - specific PHPUnit tests. This should incorporate the test structure I've been working with recently, e.g. `tests/phpunit/<MODULE_NAME>/(unit|functional)/namespace/WhateverTest.php`, because that mirrors the custom module structure and isn't dependent upon schemaless random directory naming like we've used in the past.
    - specific Cypress tests or features. We have a good number of behavioral tests at this point, and I'd like to empower product teams to continue to create their own stuff as needed.
  - Be clear that some modules need to go away because they're too messy and impossible to manage, like `va_gov_backend`. I don't think there's a shortcut there, just we need to own it and if something bad happens we will suffer.
  
Documentation should include some specific things:
- why we're adopting this change
- the process we're following to get there
- how changes to ownership need to be managed in the future

**Comment by ndouglas** [comment]
This should wait for #15236, and be essentially a manifestation of one aspect of that ticket.
