### ISSUE TITLE
Draft content for Helpful Documents accordion under Prepare for your visit 

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14351]
## Description
@davidmpickett started a draft in comments thread - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14029#issuecomment-1595600993
@mmiddaugh replied and asked questions

We need to agree upon the copy so that @thejordanwood can insert it into design

We agreed on 7/13 that this could wait until after Midpoint review and be done during the prototype phase
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13960

### Stakeholder feedback
Sitewide Content needs to review. RO folks as well. We want to preserve history of drafts / final content in a single ticket, rather than cutting new tickets to align with sprint boundaries. In that spirit, we've defined ACs per sprint, understanding that this ticket will remain open across sprints. 

## Sprint 89: Acceptance Criteria - 8 points
- [x] I expect that content is drafted in a collaborative space for review (VA SharePoint Word doc)
- [x] I expect that content has been reviewed & signed off by @mmiddaugh @davidmpickett @cindymerrill 
    - [x] I expect that when copy is approved, comment is added to #13960 for design awareness

## Sprint 90: Acceptance Criteria - 2 points
- [ ] I expect that content review has been requested from Sitewide Content team (will block closing ticket)
- [ ] I expect that content has been shared with RO stakeholders

**Comment by jilladams** [comment]
From https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14029#issuecomment-1595600993

This is a first draft of content for the "What to bring / helpful documents for your visit" accordion. It's hard to know exactly how much information to put here since a lot of it won't apply in most cases. Also not sure exactly how to break it up. Thoughts and edits appreciated @mmiddaugh 

## What to bring

Depending on why you are visiting, you may need to provide certain personal information or official documents during your visit. If you do not have all of these documents, we may be able to assist you in gathering them.

Please [call the office](url) if you have any questions about what to bring for your visit.

**Personal information**
- A non-expired photo ID
- Your date of birth
- Your Social Security number
- A copy of your discharge or separation papers (DD214) 

**Information about your dependents**
- Their date of birth
- Their Social Security number

**Financial information**
- Bank account direct deposit information

**Medical information (for disability claims)**
- Your service treatment records 
- VA medical records
- Private medical records

**Education information**
- Your education history
- Basic information about the school or training facility you want to attend

**Comment by jilladams** [comment]
From UX refinement: if we determine that some content does not belong in the accordion, we need to determine what happens to it. Do we need to figure out where it _should_ go, or annotate in a ticket somewhere that the content is dangling, etc?

**Comment by mmiddaugh** [comment]
I just found a simplified version for Burial and Memorials on a pdf on how to [Apply for Burial in a VA National Cemetery and for Memorial Products](https://www.va.gov/files/2023-01/memorial-benefits-qsg.pdf)

> For burial in a VA national cemetery, a private cemetery (for a headstone, marker, or medallion) or for a Presidential Memorial Certificate, collect the following information and submit it with your application.
> * Discharge document(s) (DD214 member-4 or equivalent)
> * Orders, if activated by Executive Federal Order from the National Guard  or Reserves
> * Pre-need determination approval letter (if previously completed)

**Comment by mmiddaugh** [comment]
Simplified version for education on [Apply for Education Benefits](https://www.va.gov/files/2023-01/education-qsg.pdf)

> Collect the following information
>  - Discharge papers (DD214 member-4 or equivalent) 
>  - Orders, if activated from the Guard or the Reserves

**Comment by ALogsdon3** [comment]
Shared a draft doc with @davidmpickett and @mmiddaugh for their comments

**Comment by cindymerrill** [comment]
@ALogsdon3 I'd like to review the content at some point, but maybe after the feedback from Dave and Michelle has been incorporated

**Comment by ALogsdon3** [comment]
@cindymerrill That's what I was thinking! :)

**Comment by jilladams** [comment]
@ALogsdon3 could you add a link to the doc on here?

**Comment by ALogsdon3** [comment]
Here's the link to[ the document in Sharepoint](https://dvagov-my.sharepoint.com/:w:/g/personal/alexis_logsdon_va_gov/EZbcf-qK7dVGqRXBmrJ3L0oBwU2-EYg9GZb3N0Z2qK8mfQ). I have reviewed feedback from @mmiddaugh and @davidmpickett , but haven't yet integrated their suggestions for the intro paragraph. @cindymerrill I welcome your thoughts on all of it, but especially any ideas about that first paragraph!
cc @jilladams

**Comment by cindymerrill** [comment]
So far I agree with all of Michelle's and Dave's comments, but I'm unable to reply to their comments or add my own. Could you please grant me that permission, @ALogsdon3 ?

**Comment by cindymerrill** [comment]
How about "Depending on the purpose for your visit or call" or "Depending on what you want help with" instead of Michelle's "Depending on the benefit"? @ALogsdon3

**Comment by cindymerrill** [comment]
Isn't a DD214 all of your military records, not just your discharge or separation papers? @ALogsdon3

**Comment by ALogsdon3** [comment]
@cindymerrill I added comment/suggest access for you. 
In response to the question about DD214, @mmiddaugh [collected several Helpful document lists](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14351#issuecomment-1644560020) from various benefits pages a few comments up in this ticket. 
Each of them lists "Discharge document(s) (DD214 member-4 or equivalent)" or "Discharge papers (DD214 member)" as a "What to bring" item. So, I'm not sure if DD214 refers to all your military records, but I opted to leave this content as it was in @davidmpickett 's rough draft and consistent with the existing Veteran-facing documentation Michelle provided.

**Comment by ALogsdon3** [comment]
> Here's the link to[ the document in Sharepoint](https://dvagov-my.sharepoint.com/:w:/g/personal/alexis_logsdon_va_gov/EZbcf-qK7dVGqRXBmrJ3L0oBwU2-EYg9GZb3N0Z2qK8mfQ). I have reviewed feedback from @mmiddaugh and @davidmpickett , but haven't yet integrated their suggestions for the intro paragraph. @cindymerrill I welcome your thoughts on all of it, but especially any ideas about that first paragraph! cc @jilladams

I took another pass at the content below the header. It's a little different: I combined the "we can help you find out what to bring" and "we can help you request docs you don't have" into one sentence and put it in a para with the "Please call" sentence. I think this makes more sense structurally, but i'd like to hear your thoughts! I preserved the previous iteration on a separate page, so if we hate it I can go back to that version with everyone's feedback incorporated.

**Comment by ALogsdon3** [comment]
I have a few outstanding items that need feedback from @mmiddaugh and @davidmpickett 

For both of you:
I rephrased the paragraphs below the header significantly since you last reviewed it. Can you see if the current iteration adequately covers all of the feedback you offered? (Cindy has already reviewed it.)

For Dave:
In the Word doc, Michelle asked whether the helpful docs that are for surviving spouses (Marriage license, death cert, funeral bill, etc) could be included in the burials and memorials accordion. Since this is an open accordion, if we decided to include it in the accordion, would we need to make that call before the prototype gets built? Also, would that trigger a larger conversation about the content scope of open accordions? It doesn't seem like guidance on what to bring is a section in any of the open accordions presently. 

For Michelle: 

- If eBenefits are being phased out and most other benefit services only require one photo ID, I'm inclined to leave this item out of the helpful docs to avoid confusion. I know there's a concern that we not deter folks from coming in if they are missing something and seeing 2 forms of ID as suggested doc seems like it could be a pretty big deterrent. Does you agree?

- For VA disability rating decision, you commented that this might be relevant to other disability tasks. I asked a question in response: "I'm wondering if this is something that an RO would be able to access easilv on a Veteran's behalf. If so, it still feels like a good candidate for dropping from the core list." Do you have a strong objection to this, or further info to help us decide?

**Comment by mmiddaugh** [comment]
@ALogsdon3 thank you for your clear comment - it was very helpful in understanding your questions and to whom they are directed

I'm in agreement with your recommendations about items to appear in the list of helpful docs
- Mention only one form of ID
- Don't include the disability rating document as it isn't broadly applicable, will likely be brought by those who are seeking increases or other relevant tasks, and/or can be retrieved with RO assistance if needed

**Comment by davidmpickett** [comment]
> For Dave: In the Word doc, Michelle asked whether the helpful docs that are for surviving spouses (Marriage license, death cert, funeral bill, etc) could be included in the burials and memorials accordion. Since this is an open accordion, if we decided to include it in the accordion, would we need to make that call before the prototype gets built? Also, would that trigger a larger conversation about the content scope of open accordions? It doesn't seem like guidance on what to bring is a section in any of the open accordions presently.

I have said this in other contexts, but to respond fully with my proposal:
- I recommend that we stick to our [decision](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14029#issuecomment-1593658528) to not have a dedicated component for helpful documents inside service accordions. 
- When I work with Jordan to add the content of the 3 open accordions to the [prototype](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13960), I will look at whether this information can be incorporated into other fields (likely the national service description).
- If [usability testing](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10197) shows that users do not sufficiently understand what documents/information they might need based on just having this one accordion under Prepare for your visit, we can revisit solutions.

**Comment by jilladams** [comment]
@ALogsdon3 in the morning, could you comment here re: what's remaining that will carry into Sprint 90?

**Comment by jilladams** [comment]
From planning: we broke up Sprint 89 and Sprint 90 ACs, @ALogsdon3 to update checkboxes in ticket body when complete for S89 items which are basically done just nominally wrapping up today.

**Comment by ALogsdon3** [comment]
@davidmpickett @mmiddaugh @cindymerrill : I have incorporated everyone's feedback into the current draft. Thank you all.
@thejordanwood : I gave you edit access to the [Word doc in Sharepoint](https://dvagov-my.sharepoint.com/:w:/g/personal/alexis_logsdon_va_gov/EZbcf-qK7dVGqRXBmrJ3L0oBwU2-EYg9GZb3N0Z2qK8mfQ), but I am also sharing the content here for ease of access:

## What to bring

Some of the documents and information listed here could be helpful during your visit.

### Documents you may need
* ﻿﻿A non-expired photo ID
* ﻿﻿A copy of your discharge or separation papers (DD214)
* ﻿﻿Medical records

### Personal information
* ﻿﻿Social Security number
* ﻿﻿Direct deposit information

### Information about your dependents
* Dates of birth
* Social Security numbers

We can help you find out what documents to bring to your visit or request documents on your behalf. Call the office for more information.

**Comment by jilladams** [comment]
Closing, as we didn't flag any additional feedback required, and discussed in scrum at end of Sprint 89 that this was effectively complete.

**Comment by davidmpickett** [comment]
Request sent to SCAIA here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/58511#issuecomment-1673979336
