### ISSUE TITLE
Spike: per-CMS-environment Next.js server(s) investigation

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14418]
## Description
We will need to set up Next.js build and preview servers for each CMS environment. We should map out exactly what we need and what functions each server should perform. Things to consider:

Environments:
* Prod CMS
* Staging CMS
* Prod-test CMS
* Staging-test CMS
* Tugboat instances

Local development and non-CMS environments that need a front-end (vets-website/api review instances, CI, accessibility testing, etc) will be considered in a separate ticket .

* Can the same Next.js server function as both a build and a preview server or do we need separate servers?
* What can we use for a web server to function as an S3-equivalent for these different instances? 
  * Can each instance have an S3 bucket that functions as its prod equivalent? 
* Identify things we need to take care of for these, i.e. certs, CORS setup, etc.

Re: Preview: this ticket does not need to go in-depth re: preview configuration. We will set up a separate ticket for investigation into Preview.

Staging CMS vs Staging VA.gov and its interaction with Next.js servers need to be addressed. If the overly complex, make its own ticket.

## Acceptance Criteria
- [x] All CMS environments we would need Next.js servers for are identified (local left out)
- [x] Determine whether Build & Preview servers should be separate or can run from the same instance, for all environments
- [x] Determine what the web server should be for all environments (S3, nginx, etc)
- [x] Identify certs, CORS setup, etc. that need to be accounted for
- [x] Identify questions re: how Staging CMS / VA staging interact in this new setup to follow

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

**Comment by timcosgrove** [comment]
Tanner will do this.

**Comment by tjheffner** [comment]
## Environments:
- Prod CMS
- Staging CMS
- Prod-test CMS
- Staging-test CMS
- Tugboat instances


## Questions
### Can the same Next.js server function as both a build and a preview server or do we need separate servers?

YES. https://nextjs.org/docs/app/building-your-application/deploying#nodejs-server 

Each instance would run `next build` to generate static pages & application code (api routes etc) then run `next start` to start the server.
The running server should be able to handle ISR and preview, or any other server features that are enabled.


### What can we use for a web server to function as an S3-equivalent for these different instances?
Any hosting provider that supports node.js. This is a hard requirement for all environments.
nginx or docker (ddev?) should be fine for tugboat. look at `.tugboat` directory in cms repo
https://github.com/vercel/next.js/tree/canary/examples/with-docker-multi-env


prod, prod-test
staging, staging-test
- It was hard for me to get exact details on these environments without VA access. Look at these 4 cases a little closer when possible. I assume S3 will be used for most.

### Can each instance have an S3 bucket that functions as its prod equivalent?
I believe this is possible. We may want to explore having a shared bucket for serving images to tugboat instances.

otherwise, objects can be copied across buckets (does incur bandwidth costs). something like this should probably happen alongside the nightly/weekly mirrors of prod in general if necessary
https://docs.aws.amazon.com/AmazonS3/latest/userguide/copy-object.html

buckets can be configured to allow CORS (may be needed per instance)
https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html


### Identify things we need to take care of for these, i.e. certs, CORS setup, etc.
- certs:
next-build has the `VA-Internal-S2-RCA1-v1.pem` cert in it already. This is used in the drupalClient connection when fetching data from JSON:API. see `src/lib/utils/drupalClient.ts`
We may need to add additional certs or update this config for different environments, I am not sure. The cms repo has 3 certs in their `.tugboat` directory, and VA may have updated certs since the last time this project was active.

- CORS middleware, if necessary:
https://github.com/vercel/next.js/blob/canary/examples/api-routes-cors/pages/api/cors.ts

- connection to S3 buckets / equivalents (whether each instance has its own bucket or not)

- preview routes:
we may need a different secret token per env and/or authentication. tbd in the preview ticket #14419

- ensure existing pages are cached & shown when restarting the server / rebuilding pages (prevent downtime). particularly prod

- how each instance interacts with the respective content-build instance

- i18n routing:
after upgrading to nextjs 13 app routing + server components, we can do it like this: https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing nothing really changes per environment with i18n, just noting it here so i don't forget.
