### ISSUE TITLE
BE: Create test coverage for CLPs (Campaign Landing Pages)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14442]
### User story

**AS A** PO/Editor
**I WANT** the CLP content type covered by automated tests
**SO THAT** any regressions caused by updated code are caught immediately.

### Engineering notes / background

In the course of D10 testing Daniel found that the CLP (Campaign Landing Pages) content type is both complicated and relatively untested.

After collaborating with @ndouglas we decided that we shouldn't add anything to `i_create_a_node.js` for this content type and what is already there was intended for bare minimum, required field testing in lieu of eventually getting to this work we are doing in this ticket.

Adding to `i_create_a_node.js` is fragile and messy and it's worth breaking down what is already in there eventually into other tests.

We should divide up the CLP tests into small, individual tests in `campaign_landing_page.feature`, for differing sections of the CLP page. 

Creating new step definitions that others can also use in `step_definitions/common` will contribute to future forward work instead of adding on top of potential tech debt.

This approach creates a framework for further testing or modifying the campaign landing page in a more efficient and less cognitive way.

## Acceptance criteria

- [x] Researched and implemented proof-of-concept code to write tests in the framework discussed above, which is less flaky and enables reusability
- [ ] Implemented tests in that framework which cover that expected fields are present in the different sections and that enabling the sections works:
   - [ ] Test that expected form elements are present in Hero Banner segment
   - [ ]  Test that expected form elements are present in Why This Matters segment
   - [ ] Test that expected form elements are present in What You Can Do segment
   - [ ] Enable Video page segment and ensure expected fields are present
   - [ ]  Enable Spotlight page segment and ensure expected fields are present
   - [ ]  Enable Stories page segment and ensure expected fields are present
   - [ ]  Enable Downloadable Resources page segment and ensure expected fields are present
   - [ ] Enable Events page segment and ensure expected fields are present
   - [ ] Enable FAQ page segment and ensure expected fields are present
   - [ ] Check that Connect With Us page segment has expected fields/selections

**Comment by ndouglas** [comment]
Note that I've added a `va_gov_content_types` module with a base Bundle Class and some traits to help us make logic more testable 🙂 

But yeah, the Cypress test for this type is pretty barebones, just covering the required fields, and it's [still an absolute unit](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/f1f9342b2dd62400787ecb4cea7ab9b7397bb1e1/tests/cypress/integration/common/i_create_a_node.js#L34).

**Comment by chri5tia** [comment]
I intend to write tests for the following scenarios. Let me know if I am missing anything. 

- Test that expected form fields and sections are there.
- Custom code that changes the form, if there are any

**Comment by chri5tia** [comment]
Working on creating several new common.js in order to test the attachment drop points and other new patterns, with cucumber.

**Comment by jilladams** [comment]
From scrum: 
* Tests are one giant cypress test, and that's a paradigm that exists elsewhere (e.g. Events), so we aren't going to tackle breaking that up more logically right now. 
* the checkboxes that "Enable this page segment" are the most obvious paradigm here that does something custom to CLP that needs test coverage. Christia following up on where those originate.

**Comment by chri5tia** [comment]
Chunks

Must haves
- [x] Add remaining sections and enable them
- [ ] Test removing pre-existing and added forced clicks for links
- [ ] Test that expected items are present when section is enabled
- [ ] Take note of and test any other conditional logic in forms: enable this section, others?

Nice to haves
- [ ] Common.js for repeatable patterns
- [ ] Break out elements into human readable/cucumber for testing content editor experience to content editing feature
- [ ] Change out selectors for other easy-to-read patterns
- [ ] Test that other section expected items are present

**Comment by chri5tia** [comment]
Strategized with @ndouglas on this: 
- learned that `i_create_a_node.js` was originally intended for bare minimum, required field testing
- adding to `i_create_a_node.js` is fragile and messy and also legacy
- divide up the tests into very small individual tests in `campaign_landing_page.feature`, for differing sections of the CLP page. I already have work saved for this original approach in an alternate branch, that I have brought in.
- Since there are so many repeatable patterns within the CLP, we would only have to chunk through writing cypress code for those patterns (uploading media, etc.), making new step definitions that others can also use in `step_definitions/common`. 

The work will be more organized and approachable this way and less likely to have random failing of testing, and I won't have to deal with that `i_create_a_node.js` file at all.

## New Approach

This ticket
Test that expected fields are present in the different sections and that enabling the sections works. 

In `campaign_landing_page.feature`, add the following individual tests/scenarios:
- [ ] Test that expected form elements are present in Hero Banner segment
- [ ] Test that expected form elements are present in Why This Matters segment
- [ ] Test that expected form elements are present in What You Can Do segment
- [ ] Enable Video page segment and ensure expected fields are present
- [ ] Enable Spotlight page segment and ensure expected fields are present
- [ ] Enable Stories page segment and ensure expected fields are present
- [ ] Enable Downloadable Resources page segment and ensure expected fields are present
- [ ] Enable Events page segment and ensure expected fields are present
- [ ] Enable FAQ page segment and ensure expected fields are present
- [ ] Check that Connect With Us page segment has expected fields/selections

Later/Future Ticket:
- [ ] Test all fields, required or not, adding them to the above tests. Get rid of campaign landing page section of `i_create_a_node.js`.

**Comment by wesrowe** [comment]
@jilladams, in BE refinement it was raised that the original 5-pt estimate on this ticket was ridiculously low, given the framing work that we eventually learned is required to handle testing the right way. In your absence we decided to raise the points on this to 13, to cover the unforeseen work that has been done. 

We rejected an alternative idea: revise this ticket to cover the discovery that Christia has done (and close it), and then create a new ticket for the actual test implementation she's wrapping up now. It seemed like it would obscure the history here. But if you like we can go that route instead.

**Comment by chri5tia** [comment]
@wesrowe Where it sits, there are some tests needed for two components of CLP: CTA and Add media modals (or any iframe pop ups.) These should be their own tickets. For now this test looks to see if the option is there to use these features but does not test the features themselves. I move to name this ticket something to the affect of _Setting up the framework for future forward testing of CLP and testing the visibility of expected elements_

This could continue for months but this is a good stopping point. I have re-tagged Nate for another review of [the PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14763).

**Comment by wesrowe** [comment]
@chri5tia, I think it would be clearer if you take a stab at writing those tickets yourself. LMK when that happens and I can make sure they get into the refinement flow.
cc @jilladams

**Comment by jilladams** [comment]
Re; the question above on this ticket closing as Discovery, vs. letting this ticket track implementation: @chri5tia noted in 1:1 today that this should close in sprint, so I think we're fine with current plan.

**Comment by chri5tia** [comment]
Nate made some light suggestions that are a must-have so this should merge tomorrow
