### ISSUE TITLE
PACT Wiz: Draft prototype in survey tool (Survey Monkey)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14447]
### User story

**AS A** Researcher
**I WANT** to build an accessible prototype of the PACT Wizard for usability testing
**SO THAT** I can ensure the prototype meets the goals of the research.

### Notes / background

Documentation of content and branching:
- [Danielle's finalized wizard content doc](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/PACT%20Act%20wizard%20content%20for%20usability%20testing.docx?d=wfee483299a674f38ac4ec198c9cca463&csf=1&web=1&e=66EcOc)
- [Cindy's branching logic doc](https://dvagov-my.sharepoint.com/:w:/g/personal/cynthia_merrill_va_gov/EcVTOmN-ODhCp3Aeq58pxqoBQ8Dk8dFkuJ9CtjT83mMXMw?e=3nUU76)
- [Cindy's branching logic spreadsheet of questions](https://dvagov-my.sharepoint.com/:x:/g/personal/cynthia_merrill_va_gov/EXikKV__i2lEp3XHMSegLzMBLznLoS5Wakq3SRlXGPwkpw?e=e2xCFQ)
- [Jordan's visual interaction flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=uff8fa85716c1796ccf022668) -- **more up-to-date than any of the other documentation!**

## Acceptance criteria
Assumptions:
- Danielle incorporated feedback from SMEs and finalized the questions for usability testing

### **Sprint 91 ACs** - 5 pts
- [x] Enter questions into SM
- [x] Create intro screen
- [x] Build R2 and R3 results pages in Survey Monkey

### **Sprint 92 ACs** - 8 pts
- [x] Built branching logic in Survey Monkey and linked it out to the results screens on Staging
- [x] Completed survey preview shared with Danielle, Wes for review
- [x] Update research plan timeline

### ***Sprint 93 ACs** -  pts
- [ ] A11y reviewed to ensure survey-tool functionality is accessible to screen readers
~~- [ ] Set up meeting with Wes & Danielle to figure out which paths through survey to prototype (and recruit to) and which results screens we need~~
- [ ] Ticketed follow-up work outside SM, or SM work that is too big to fit this ticket's scope
  - [ ] incorporating feedback can be a new ticket

**Comment by wesrowe** [comment]
@cindymerrill, this one needs your input in general and on the list of reference docs.

**Comment by cindymerrill** [comment]
@wesrowe I added reference doc links and another acceptance criterion

**Comment by cindymerrill** [comment]
Just barely started creating the prototype in Survey Monkey, and then had meetings and VBA work to do.

**Comment by cindymerrill** [comment]
Uploaded all questions and options into the prototype, as well as created an intro screen.

**Comment by cindymerrill** [comment]
Today I reviewed Jordan's visual interaction flow that makes my branching spreadsheet easier to understand and refer to. That's what I plan to use when adding branching logic.

I also created the other two results screens in Survey Monkey: R2 and R3. Since Randi already implemented R1, that means that all 3 results screens are ready to use. Next I will start working on the branching logic...

**Comment by cindymerrill** [comment]
Shown in sprint demo today but didn't make it into this ticket:

- The [visual interaction flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=uff8fa85716c1796ccf022668) that @thejordanwood created in order to visualize my spreadsheet of branching logic.

- The working prototype of [Results screen 1](https://staging.va.gov/test/pact-act/results-1-1) on Staging that @randimays built for me to connect to the prototype and show during usability testing.

**Comment by cindymerrill** [comment]
Finished writing rules for all PAW prototype branching, but it doesn't all work so needs debugging. Also, the link to @randimays 's R1 results prototype often doesn't work (any progress on this?).

**Comment by cindymerrill** [comment]
Added a link to the Description above to [Jordan's visual interaction flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=uff8fa85716c1796ccf022668), which is more up-to-date than any of the other documentation as of yesterday, when we decided to change the design of 3 checkbox questions into radio button questions followed by checkbox questions only if the answer to the radio button is "yes".

I just finished debugging the logic in the [PACT Act Wizard prototype](https://www.surveymonkey.com/r/KKVHSFV) and it’s ready for review! I shared it in slack here.

**Comment by cindymerrill** [comment]
The prototype I shared is what I want to show research participants. I don't think it's worth prototyping a second version of the R1 results screen because I plan to show the one version we have to ALL participants, after first explaining that the specific details may not correspond to the answers they provided. If you agree (especially @DanielleThierryUSDSVA @wesrowe @aklausmeier ), then we no longer need this AC: "Set up meeting with Wes & Danielle to figure out which paths through survey to prototype (and recruit to) and which results screens we need".

**Comment by jilladams** [comment]
GO CINDY GO!  🎉  

I clicked around int he prototype this morning for fun, and ran into one weird page that may be well understood, but wanted to flag and verify just in case: 

![Screenshot 2023-09-08 at 9 28 32 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/c16cf6a5-c28b-460b-9818-6a06fd8dd490)

Is it expected that in some cases this will appear? If so, hooray. If not: I'll figure out my repro steps for how I got here, to troubleshoot.

**Comment by cindymerrill** [comment]
@jilladams This is totally expected. It's a page that I created for the prototype to get around a limitation of Survey Monkey's advanced branching rule engine, which allows only rules with AND or OR connectives but not both in the same rule. And my computer science background enabled me to get around this by writing the rules I wanted using 2 different pages instead of 1, which unfortunately ended up with a page without any user interaction in the middle. Obviously this wouldn't happen in @randimays's actual implementation because she's using a real programming language, but it was needed here to get around Survey Monkey's constraints. FYI @wesrowe @DanielleThierryUSDSVA @thejordanwood @aklausmeier @laflannery

**Comment by laflannery** [comment]
Update from accessibility testing today:

I took a look at the prototype earlier today with NVDA and inspected the markup and it's not as accessible as we would have hoped. I have a call out to the Survey Monkey technical support team and expecting them to call me back early next week to see if there is any improvements that can be made on either side (theirs or ours) to make this work better. I also plan to test this with JAWS and VoiceOver on my phone to see if this might work any better with those screen readers. I will follow up when I have more information

**Comment by laflannery** [comment]
I tested this morning with Narrator, JAWS and VoiceOver on iOS. Surprisingly Narrator was the best out of the 3, there are still issues because the markup is not right though. JAWS and VoiceOver still have issues were everything is not being read, questions start in the middle of the sentence. Narrator was not doing that however.

**Comment by cindymerrill** [comment]
@laflannery Looking forward to hear what Survey Monkey says, which may help determine whether we have to exclude screen reader users from usability testing.

**Comment by cindymerrill** [comment]
All ACs completed for Sprint 92, FYI @jilladams @wesrowe

**Comment by wesrowe** [comment]
[Prototype](https://www.surveymonkey.com/r/KKVHSFV)

Flows verified (logic, not close read of copy) – will update as I progress:
- 1990 or later

**Comment by jilladams** [comment]
Status update for end of sprint that we'll need to discuss more in sprint planning tomorrow, FYSA @davidconlon:

## Accessibility review updates
1. Survey Monkey is not accessible for screen readers, and their team has "created a ticket." We do not have line of sight on SM fixing this for us. Otherwise: the Survey Monkey prototype is complete and ready to launch recruiting.
2. Laura proactively investigated whether CodePen could help, and got a version of the prototype started using jquery. It's not clear yet whether branching logic is fully going to work here, but it seems promising so far. Laura estimated 1 more day of effort to see if we can achieve the branching logic as needed.
     * Acknowledging: yes, it's wild to find that the accessibility notes from Liz Lantz when we originally talked about CodePen are not actually a big concern from Laura's perspective. So far A11y is looking good.
     * We will need a paid account in order to run research using this. Gah. We will need to cross this bridge later.

The decision point on the table is: 
1. Move forward with Survey Monkey prototype, and do not recruit Screen reader users, which is not one of the research goals.
3. See if Laura's CodePen prototype will work. Estimating: 1 add'l day of effort to see if branching logic will fly, + 1 day of Cindy testing / validating the flows work as expected for the Research convo guide / plan

We'd like to plan to let Laura use tomorrow to verify if we can get there with CodePen. She thinks she'll have news by afternoon.

## Timeline
Draft timeline currently was hoping for:  
* Friday 9/15: launch Perigean recruiting
* Monday 9/18: kickoff meeting

## Current blockers to timeline
* Decision re: a11y / prototype platform
* Midpoint review: slots are available Friday 9/15 and Tues 9/18, with 48h required in advance to provide artifacts (including prototype) 
  * Dave / Danielle review of prototype / convo guide. We'd like to go ahead to Midpoint, and could loop Dave / Danielle into this as the feedback opportunity, if they have not provided feedback by the time we have a prototype judgment call made. (Note: Amanda K has provided feedback.)

**Comment by jilladams** [comment]
Counted 8pts for S92. Need a new points estimate added for whatever remains after sprint planning discussions for S93.

**Comment by jilladams** [comment]
From planning: 
* Yes, Dave & Danielle's feedback is required. 
   * Cindy to follow up with Dave async to provide threads for follow up. 
* No, that feedback should not block scheduling Midpoint.

Yes, fine to have Midpoint without Wes. Jill can cover, this means Tues 9/19.

Dave decision re: a11y: go with whatever's fastest. That means: Survey Monkey, which is complete, without accessibility for screen readers. FYI @laflannery. Dave's perspective here was: please continue to figure out the branching logic, so we will know for next time whether that's viable for future projects. So: we will not plan to use the CodePen prototype for research, but we would like to learn from it.

**Comment by jilladams** [comment]
@cindymerrill I'd like to vote that we call this complete, with the understanding that we have a separate ticket to keep track of incorporating Danielle's last content change.Closing, but ping me if you need to discuss.
