### ISSUE TITLE
SPIKE: Research & document Worklow previous failure and impact to VBA plans

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14529]
## Description
VBA Regional Offices need specific permissions, with an explicit goal of preventing VBA Editors from publishing an RO before it has services and an operating status.

In June 2023, we proposed a permissions model that uses an Editorial Workflow. In Drupal, we currently have a single Workflow that governs all content types. We are proposing creation of a 2nd, separate Workflow that would be considered an Experimental Feature, used only for VBA ROs. If successful, additional content types could be migrated to the 2nd Workflow later. ([Slack history](https://dsva.slack.com/archives/C03LFSPGV16/p1686934965430559))

However: the CMS Team / PO have expressed a preference for using Roles / Permissions, not a separate workflow. Because: 
* Workflow has been attempted in the past
* It affected the primary Content view filters by Editorial Workflow: https://prod.cms.va.gov/admin/content

SO: we want to: 
1. Understand what went wrong before
2. Look at how we might mitigate
3. Re-pitch our proposal to CMS team, with more comprehensive information to address their concerns.

**History**:
* @swirtSJW  might know how to find the immediately relevant tickets from the past
    * Steve think this is a known issue with Workflow as an upstream  
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/900 - epic re: Editorial Workflow Assignments (EWA) which might relate

## ACs

- [x] Understand what went wrong with Workflow in previous attempts
- [x] Document in ticket
- [x] Propose path(s) forward based on findings and schedule review with @mmiddaugh @xiongjaneg 
- [ ]  @xiongjaneg to draft and @mmiddaugh to edit a simple document for CMS Team to preview

**Comment by davidmpickett** [comment]
@swirtSJW Can you take a look at this

**Comment by jilladams** [comment]
From planning: 
* It's ok if we don't have final conclusions
* Main goal is to identify: snarly mess and needs more time later or: reasonable path maybe, let's think more now
* Not in MVP scope, so ok to push if that's the right thing todo

**Comment by swirtSJW** [comment]
Scratchpad for my findings:  Will update as I go

- Related upstream issues
   -  [Multiple Views Workflow Filter hides all content](https://www.drupal.org/project/workflow/issues/3298549)

**Comment by swirtSJW** [comment]
Kev proposed name spacing the states by role
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/864eaa16-870e-47c8-860e-8e8ef021a371)

However i think that is going to be problematic since some have multiple roles and would see multiple states.

**Comment by swirtSJW** [comment]
The problem does still exist (was not rectified in contrib modules)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/c0bb77d9-a2e2-428a-bbe3-648214a3c789)

**Comment by swirtSJW** [comment]
Minimal but non-ideal solution does work.  Multi select on the moderation state filters.  Allows you to multiselect the multiple published and see them all.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/62464f79-718a-4feb-aee5-c28d69d398cc)

**Comment by swirtSJW** [comment]
Hmmm Module: [State Machine](https://www.drupal.org/project/state_machine) might offer us a desired solution.

**Comment by swirtSJW** [comment]
I have a combo filter showing.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/6cd7c98f-fa72-4539-929e-f552ff081777)

Unfortunately the query is failing.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/dee06e48-eded-40b2-9e33-2c58d0ee6bb3)

**Comment by jilladams** [comment]
From scrum: 
* Swirt is working out the query logic to surface both types of Draft in a single View filter
* We cannot propose to Collab Cycle without confidence to resolve that query
* This ticket will span sprints, and continue into S91.

**Comment by swirtSJW** [comment]
Making progress.  I got it so the filter doesn't throw an error.  But clearly the results are messed up as it is returning too many results.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/5f4ddedf-8a65-42b5-b845-fa92efb804ef)

**Comment by swirtSJW** [comment]
I got the dupes fixed, and the filter is largely working, but something still is not right with the results
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/595be92c-e8ae-4a07-80f9-9900e140bfd2)

**Comment by swirtSJW** [comment]
This is almost working... just being minorly odd   Here is an example using a secondary workflow.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/427e153a-7461-41a6-b912-6e3c0ecc9d78)

**Comment by jilladams** [comment]
@swirtSJW it would be helpful to document on here what we expect to need to do for standard views. Meaning: what burden are we adding for creating any future audit views that apply to multiple content types / editorial workflows? We'll need to know that for the discussion with CMS team, I think.

**Comment by swirtSJW** [comment]
@jilladams part of the plan would have to be to convert all the current moderation state filters that are in use, to the new multiple moderation state filter.   Its not really an option.  It would have to be done because that old filter breaks as soon as we add a second workflow.

**Comment by swirtSJW** [comment]
Roadmap (defining this is still in progress, will update as I do):

1. Develop multiple workflow state filter
2. Contribute it as a patch to drupal.org core workflow module.
3. Present plan to CMS team for approval
4. Replace all instances of the workflow filter on **all** Views across the CMS (nobody would notice this change, they look identical)
5. Add a new workflow being careful to name similar states the same.
6. Update docs and notify editors of the new changes they might be seeing in the list of states.
7. Apply new workflow to whatever content types need it.

**Comment by jilladams** [comment]
Flagging some theoretical risk / burden for Facilities in this plan around #4 / 6, wherein we are taking on ownership of making changes to _all_ Views across the CMS, not just Facilities views, for our own sake. If buggy, that also means we have introduced a potential maintenance burden. I think we can volunteer to do the upfront work in order to get what we want as far as VBA workflow, BUT: when we review proposal in CMS Collab Cycle, we should clarify with CMS team that this would be for the initial lift, but we wouldn't own related maintenance ongoing. 

Is that a reasonable way to be thinking? (@swirtSJW & @xiongjaneg FYSA)

**Comment by swirtSJW** [comment]
Still having trouble getting this right.  The filter is actually working, but the display of moderation state in the table is misleading/wrong.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/2e86e2c1-f2fb-46a1-8d24-db9acbaf22ec)

**Comment by swirtSJW** [comment]
I have the filter largely working.  Though I just discovered  a second problem.  Workflow states that are named the same, jump the boundaries from one workflow to the other if two or more workflows share the same machine name.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/d2b4abf9-1b32-4788-b93e-3184750e5082)

**Comment by swirtSJW** [comment]
I have the multiple filter working perfectly

Filter
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/88b7ec6e-a048-41aa-98ea-88400fe9ff54)


![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/d9c411fe-cef4-4859-b3fd-6da2d682bfe7)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/f8947709-b0ba-4855-b3b5-f5b885e650ef)

**Comment by davidmpickett** [comment]
> I just discovered a second problem. Workflow states that are named the same, jump the boundaries from one workflow to the other if two or more workflows share the same machine name. ![image](https://user-images.githubusercontent.com/5752113/261897844-d2b4abf9-1b32-4788-b93e-3184750e5082.png)

If I understand this correctly, what you are calling out is:

- **IF** 
  - there are two workflow states that have the same machine name across multiple workflows
  - and these workflow states have different settings for the booleans `Published` or `Default Revision`
- **Then**
  - Workflow transitions that move entities into this state may not reflect the boolean settings for the workflow state instance that corresponds to the workflow that governs the related content type
  
![states](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/f074f0b9-a21f-43f6-9b2b-0724ce37feee)

**Comment by swirtSJW** [comment]
ALso noting this just in case we want same machine & effect, but differing label 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a62d1d28-eb7e-4755-ae08-9b0374dcba31)

**Comment by swirtSJW** [comment]
I submitted the upstream issue.  https://www.drupal.org/project/drupal/issues/3382759
Will submit patch tomorrow.

**Comment by swirtSJW** [comment]
Patch was submitted last night.   It could use a followup round of tests to increase the likelyhood that it will get accepted, but that is not a blocker for us using it within our normal patch workflow.

**Comment by swirtSJW** [comment]
So the roadmap exists [higher up](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14529#issuecomment-1681158294) and has been updated.  I believe we can close this can call it done.

@xiongjaneg or @jilladams let me know if you disagree.

**Comment by swirtSJW** [comment]
@jilladams I was not part of a meeting with Michelle.  I am not sure if she has seen the [roadmap](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14529#issuecomment-1681158294) or discussed it with @xiongjaneg

**Comment by jilladams** [comment]
Related thread where Michelle has also weighed in: https://dsva.slack.com/archives/C0FQSS30V/p1693336269574529

**Comment by xiongjaneg** [comment]
Questions:
Does the option of changing roles and permissions go away? Yes, this could be a change to workflow not roles/permissions.

What do we need to be able to show CMS Team? A simple document with our proposal and a summary of Steve's information.

What is the value to Veterans? Veterans get accurate information. Nothing is archived that shouldn't be archived.

Why can't we use existing methods? We want to present what makes this approach better or why this approach does something we can't do now. We need a new workflow to not allow people to archive who shouldn't be able to.
In the way that we currently block someone from archiving a content type in a code way, there is currently no record of which content types we block.

Vet Center editors example: When starting in CMS, they were given the editor role and not able to publish until national gave approval. That's a manual role change for the user not related to workflow.

Workflow states don't perfectly match published status. "Published is not always published."

Did not test switching a workflow. Would we want to do this ahead of time for VBA? Or do we wait?

Is this still the right thing to do if we found out we couldn't do this for VBA? It's attainable but the unknown is time and effort.

Is there a use case this doesn't work for? Per content type, there may be ones that people should always be able to archive, even if accidentally because the downstream effect is minimal (e.g., events).

What about services? Are they archivable? A facility editor should be able to archive a service if not offered locally, except for required services. Required services would be coded so they can't be archived by an editor (existing workflow). Can make it a property of the node.

Helpful links:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11028
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5248
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-governance/content-moderation-roles/README.md

**Comment by xiongjaneg** [comment]
If I can't archive a VC facility, can I archive a CAP? It doesn't have to be by facility. It is by content type. Each content type can only be in one workflow.

Steve could use the new diagram content model to demonstrate workflow 2 in a demo environment as a method to share this with CMS Team.

What are the success measures? Number of issues related to mistakenly archived nodes, particularly facilities

Timeline? This is not blocking VBA work. 

Any consequences for Drupal 10? The patch might not apply cleanly but that is a simple fix.

**Comment by xiongjaneg** [comment]
@xiongjaneg to draft and @mmiddaugh to edit a simple document for CMS Team to preview

@xiongjaneg to stub a ticket for testing the patch Steve worked on and Icebox it

**Comment by xiongjaneg** [comment]
Is the additional Workflow needed for VBA RO Pilot MVP? Considerations:

New VBA facilities will not be created during Pilot MVP. There would have to be change management on this later on if editors can archive VBAs.

There is a risk in switching workflows, particularly for existing editors.  An additional workflow could co-exist for existing facilities, but this could create a mental load for facility maintenance and editor support. There is likely not a visible benefit to Veterans or editors.

We have at least 4 views in Drupal that would have to be converted a new filter to display multiple workflows. This will create additional work because of many admin views needing to be found and updated because VBA facilities show up on these admin views with the Moderation state filter, which is breaking due to multiple workflows. This could be a find a replace but would require testing.

**Comment by xiongjaneg** [comment]
Next step is to take to CMS collab cycle. Scheduled for Oct. 2 with CMS product folks.
