### ISSUE TITLE
SPIKE: Refine VBA Status using supplemental status model

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14546]
## User Story or Problem Statement
In preparation for building out the VBA Facility content type, we need to define how we want status to work.  It was decided months ago to use a variant that largely consists of the supplemental status model that was leveraged for VAMC facility covid statuses.

We need to refine that model to be the source for all? VBA statuses.

Features of the model:
1. Flexible statuses as content
2. Flexible descriptions as content
3. Governance of the suggested descriptions
4. Editorial guidance as content

What is potentially missing:
1. The ability to specify statuses for use on certain facility types (similar to the way we restrict services)
2. The ability to specify whether a supplemental description is an override-able suggestion or rigidly defined (similar to what was used for COVID status)
3. The ability to have more than one status.

## Acceptance Criteria
- [x] Creation of an issue to cover editorial experience
   -  #15605
   - #15621
- [x] Creation of an issue to cover front end template
   - #15606
- [x] Creation of an issue to cover push to lighthouse
   - #15607
- [ ] ~Creation of issues to cover status supplemental data model changes (MVP pilot vs MVP national, etc.)~ -  It is not clear at this time what is MVP pilot vs MVP national
- [x] Creation of issue for documentation
   - #15608
   - #15634

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by xiongjaneg** [comment]
@xiongjaneg 
To discuss with Dave:
- Is this the COVID field or the More info field?
- Is this VBA only?
- Is this needed for RO MVP?

**Comment by xiongjaneg** [comment]
History:
VHA DM wanted to log the COVID status in addition to the operating status, so that used a flexible model using taxonomy terms for the status. The description of that taxonomy became the description for that status. There was a national status managed at the national level. A status selected at the national level could preempt the local status.

This allowed ad hoc potential other use cases (e.g., monkey pox). The editorial experience allowed "use this if..." and guidance.

The COVID supplemental status was disused due to confusion. Dave C. wanted this retained for VBAs.

There might be statuses specific to certain facilities. Toggles would need to be build into the facility status taxonomy so it could branch options per facility type.

Additional consideration: Should there only be one status? Con: e.g., an active shooter status (immediate status) AND limited services or hours (in the future). Multiple statuses would serve this, BUT editor should not be able to select competing statuses (open and closed). Statuses need to be able to be clustered.

Sets us up for future improvements to other facilities. Would not require change management to other existing facility editors.

Timing:
Doing it for MVP requires coordination for sending to Lighthouse, impact Facility Locator. Allows us to experiment with a smaller MVP group. Some necessary functionality "status, description, for VBA" could be implemented for MVP without significant delay. 

Doing it after MVP requires migration after the fact. Could also impact any potential other uses of supplemental status (e.g., another COVID situation comes up again).

**Comment by xiongjaneg** [comment]
@xiongjaneg stub out FE implementation of this supp status

**Comment by xiongjaneg** [comment]
@mmiddaugh I added some history and answers for you. Please let me know what other questions you have. We can also discuss in refinement (might need timeboxing).

**Comment by xiongjaneg** [comment]
uses same toggle for design

**Comment by mmiddaugh** [comment]
Question: could some supplemental statuses be limited to a particular facility type's use? (like services which can be used only by Vet Centers or only by VAMCs or by either)

**Comment by xiongjaneg** [comment]
@swirtSJW From new/upgraded Vet Center discussion, consider the possibilities for the use cases of displaying "coming soon" for
- A totally new Vet Center opening
- An outstation becoming a Vet Center at its current address
- An outstation becoming a Vet Center at a new address

**Comment by swirtSJW** [comment]
This is complete.

**Comment by jilladams** [comment]
@xiongjaneg Swirt linked all the new tickets he created, in the ACs area of ticket body. All of these tickets are: 
* Required for Pilot MVP, and in the Pilot MVP epic (thanks Steve!)
* Queued into Next Refinement column in the board.

**Comment by xiongjaneg** [comment]
Due to supplemental status being additional to operating status instead of replacing it and current timeline, supplemental status work is being moved to VBA national MVP.
