### ISSUE TITLE
FE: Review prototype & map out FE architecture for VBA Regional Office

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14552]
## Description
Dependency on #13960 results in a clickable prototype. Done in S90

Based on that prototype, FE engineers need to: 
* Review the prototype for any architectural concerns / questions for Design
* Map out an architectural plan for how to manage templates for Regional Offices. 
   * Evaluating the current state of VAMC templates may be a relevant starting point to consider what's similar, what's different, and where we can optimize for maintainability. 

## Engineering notes
Public Websites recently engaged in a FE architectural plan for PACT Act Wizard, and there may be insights to gain from that process. In that case, the architectural piece was how to manage presenting question data in a React app, without CMS involvement. In our case, CMS will provide all of our VBA data (eventually, some may be hard coded for MVP) so the use case / problems to solve are different, but the presentation of considerations / notes for review might be useful. (Or might not.)
* PACT Ticket: #14072  
* Resulting document: https://docs.google.com/document/d/1MAY0qdbnsguO9p4KHLu_ZVApaFqu03cL8O_-0WhGcCQ/edit?usp=sharing

## Acceptance Criteria
- [x] An architectural plan has been created and linked to this ticket, including considerations for how best to batch work into tickets
- [x] A11y review from Laura

**Comment by Dottisea** [comment]
Will break this up into two tickets - 1 for the work (SP 8), 2. for the reviews/feedback

**Comment by xiongjaneg** [comment]
split out review in ticket #14958

**Comment by jilladams** [comment]
DaveP = available until Fri 9/1
Swirt, Eli = here all sprint to support and answer questions / provide insight
Randi / Chris on PW = also here all sprint for addl ideas re: how they thought about PACT Act

**Comment by maxx1128** [comment]
@jilladams @xiongjaneg  I've looked over the designs and have some starting notes and questions to work off of for the next week. If anyone on the above list has any additions or answers, I appreciate them posting them here or we can sync on them at the start of next week 👍 I'll also start doing some more specific digging into what code can be reused and what code must be written from scratch.

cc: @swirtSJW @eselkin @randimays @chriskim2311 

## Notes

### General

* Accordion groups should be easy to copy from pages with a similar setup, and they likely have the same data structure too. Almost all of the content in each accordion looks the same as what is already used too.
Some accordions, like “Burials & Memorials,” have the “action link” component, which I don’t recall seeing in other accordions. Rendering it may require making a specific template for it to be used, like how alerts have their own template written for centralized content.
* There are only mobile layouts here, so I don’t know if the desktop would need a left-sidebar layout. If so, the context of what other links are used there would be needed. This could greatly affect the queries and templates used for the page.

### VBA Regional Office Page

* Outside of accordions, we'll be reusing the following components on the main Regional Office page. Each needs a specific template component as needed.
  * Table of contents
  * Location and Contact Info (with photo and map)
  * Address info
  * Phone number info
  * Office Hours
  * Spotlight panels (3)
  * Alert callout (info)
  * Updates link callout
  * Other Nearby VA locations list
* The link at the bottom would be more clear and readable if the URL was made part of link text, instead of being written out directly.
  * Example: You can locate a VA location near you by visiting [our facility locator.](#)

### Check Your VA Page

* This page will need the following template patterns:
  * Alert callout (success)
  * More info blocks

### Find VA Locations Page (Being Updated)

* [The “Tabs” component](https://design.va.gov/components/tabs) used for the Facility Locator page is listed as “use with caution” and has no documentation on how to implement it. We should reach out to the design system team about implementation. If that's not feasible, we may need to look into alternative ways to handle those views.

## Questions

### General

* What are the details for the desktop layout? If it’s the one with the left sidebar, what links will be shown there?
* Is there any information now about what GraphQL queries will be needed?
  * How much could they be based on existing ones?
* Just to confirm, but do these pages only use existing and currently available API endpoints?

### VBA Regional Office Page

* Clicking the “Make an Appointment” link goes to a page with scheduling an in-person and virtual appointment. Is this a fully separate page? Where do the buttons there link to?
  * Is it an external site or one being built on another subdomain? This is based on the extremely different layout and design on the Figma doc.

### Ask VA Page

* This page also has a noticeably different overall site design but is still in the VA.gov website. Which specific layout is being used or is it the same as the Regional VBA Office page?
* Do the buttons on this page link to another page? Or are we in charge of developing the UI for these functions and linking them to new API endpoints?

### Check Your VA Claim Page

* This page has the “sign in to check claim” alert, which will likely open up the current login modal. But when a user is already logged in, how does this part of the page change? Does it simply hide or does something else appear?
  * Do we have any other examples of this on the front end to copy or work off of?

**Comment by mmiddaugh** [comment]
@maxx1128 a few additional bits of context which might be helpful...

_There are only mobile layouts here, so I don’t know if the desktop would need a left-sidebar layout_
- we don't expect to need this for MVP but know that events are important and likely a fast follow effort - so thinking about the left menu in advance is a good idea. 

_The link at the bottom would be more clear and readable if the URL was made part of link text, instead of being written out directly. Example: You can locate a VA location near you by visiting [our facility locator.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14552#)_
- good catch - this is how the link was originally designed but I think a change might have been made which reverted it in the prototype. 

_Clicking the “Make an Appointment” link goes to a page with scheduling an in-person and virtual appointment. Is this a fully separate page? Where do the buttons there link to?_
- Our only responsibility here is linking to this page. We don't own the experience here or beyond here. 

_Ask VA Page_
- Similarly, we just need to link to this page. Another team is rethinking this experience, part of which is a plan to bring it into VA.gov. We will likely need to update the link at that time, fyi

_Check Your VA Claim Page_
- The front end experience for "Make an appointment" online is probably a decent example. It's present in VAMC facility services, such as [University Drive's Primary care accordion](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#primary-care). Again, we only are responsible for linking to the page.

**Comment by maxx1128** [comment]
Thanks @mmiddaugh! I updated my initial notes with your feedback.

**Comment by maxx1128** [comment]
Below is a breakdown of possible page architecture to go through. Answering the questions in bold should address most/all of the remaining architecture needs.

## Title & Description

1. Region name would be interpolated, so it would be something like `{{ regionName }} Regional Benefit Office`.
2. The description looks like it's universal, so it can be hardcoded onto the page.
3. Three [action links](https://design.va.gov/components/link/action) from the design system, and can be left empty for now.
4. The "[On This Page" component,](https://design.va.gov/components/on-this-page) also from the design system. I believe the links to the `H2` headers need to be hard-coded.

## Location and Contact Information

This should be in the right column on desktop screens, and all other content will be in the larger right column.

1. Image of the facility
    * **Is there a specific component for this or just a plain image tag?**
2. Directly below the image (flex column layout?) is the embedded Google map.
    * **Is there a component for this or is it a liquid partial?**
3. [Address block component](https://design.va.gov/components/address-block)
    * **The specific component looks different than the layout. Do we just place with HTML tags without a design system component?**
4. Phone numbers. Will use multiple [telephone components](https://design.va.gov/components/telephone)
5. Office hours, most likely a liquid partial

## Prepare for your visit

1. Looping through a series of content blocks and placing it inside [an accordion component.](https://design.va.gov/components/accordion) This needs to be in its own drupal node.

## In the spotlight at Boston Regional Office

1. I believe this is the spotlight component and will be created by looping through different spotlight content in a separate node
    * **Is this a partial? Should this be abstracted to a component?**

## Veteran Benefits, Family member & caregiver benefits, Service member benefits, Other services

These four sections are each a series of accordions. So each section will have the same basic structure:

1. A static `h2` heading
2. "Select a topic to learn more" or any other hard-coded text
3. Accordions rendered by an array of content data
    * **Are each of these arrays in a separate node, or will this data be structured as an array of arrays? This affects how the HTML will be written.**

The last section ends with the following different items:

1. [An informational alert,](https://design.va.gov/components/alert#informational-alert) which looks like it can be hard-coded with the text and links. It includes a telephone component and an HTML link.
    * **Where does the "VA benefits location" link go to? Is it an existing page or a new one?** If unknown, can be left blank. 
2. Social media links for the VBA
    * **Is there a liquid component for the social links that already exists?**
    * **If there's no liquid component, where does the social link data come from?**
    * **Is there a component of any kind for the surrounding callout box styles, or is it just a class?**

## Other nearby VA locations

1. A listing of nearby locations
    * I don't see a design system component for each location. **Is there a liquid template for this already?**
2. A list of social links in a callout box
    * **Does the callout box styling here just come from a class, or a template component?**
    * **Where from the CMS does this data come from?**

## VA locations in other areas

1. A hard-coded paragraph with a link to the facility locator.
    * From the previous comment, will be rewritten to something like "You can locate a VA location near you by visiting our [facility locator.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14552#)"

**Comment by swirtSJW** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/949542d5-0e50-4e70-8121-9a5bcff39ab1)

**Comment by swirtSJW** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/44fe8752-158a-4e4c-948d-3b471d8cc31a)

**Comment by maxx1128** [comment]
There are updates from syncing with others on the front end with @swirtSJW @randimays @chriskim2311. I've bolded important action steps for finishing the page architecture.

## General

* [These are the fields specific to the VBA Regional Facility.](https://prod.cms.va.gov/admin/reports/content-model/fields?field_name=&field_type=&entity_type=&bundle=vba_facility&label=)
* [This is an overview of how other data nodes connect to VBA Regional Facility.](https://prod.cms.va.gov/admin/reports/content-model/entity-diagram/node/vba_facility?max_depth=1) This is a good place to start for the page's GraphQL query and page content.

## Title & Description

1. The whole title at the top comes from the CMS side. It'll be placed directly into the `h1` tag.
2. The description text will also be coming from a field. If it's the same for each regional office then it will be from centralized content; if not, then it will come from a custom field on their page.
3. The action link pages may already exist, even if they don't exist yet. They will still be hard-coded onto the page.
4. The "On The Page" component dynamically generates the links from `h2` elements. This creates some flexibility if the sections are different for each regional office.

## Location and Contact Information

1. **Should check if there's a component for the map and photo combination.** If not, it may be worth making a ticket to make a component for it.
2. The address information is static on each page, but the Directions link is a component.
3. "Office Hours" is a liquid partial that exists on other facility types, so that same partial can be referenced here.

## Prepare for your Visit

1. For accordion content in this section and all others, **check to make sure the content renders as expected while building the page out.** The "action link" component may have never been used in the context of an accordion before. If this is the case for this component or any other new accordion components, it will need a new front-end "paragraph type" template. **Each new template will need its own ticket for adding it.** 

## In the spotlight at Boston Regional Office

1. **Check if the spotlight component is an existing pattern or template.** If not, it may be worth writing a ticket to make one.
2. **Check if the small underline under the spotlight title is part of the current pattern - check in with Jordan.**

## Veteran Benefits, Family member & caregiver benefits, Service member benefits, Other services

1. All the accordion-filled sections may be an array or arrays, or a bunch of separate arrays. It will use the same accordion pattern in either case, so it's not a major difference for the front end.
2. The informational alert will come from centralized content.
   * The bottom link goes to the facility locator. If it's version 2, it should already be filtering by benefits.
3. Updates from VBA are likely to be centralized content too, since the name implies they are national VBA social profiles.

## Other nearby VA locations

1. "Nearby VA Locations" will be shown the same way on Vet Center pages. This is the Nearby Vet Centers widget from `vets-website`.
    * This is the only `vets-website` widget used on this page.

## VA locations in other areas

1. The feedback button at the bottom of the page is a one-line `include script` added to the page layout.
2. "Last Updated" is a Drupal field.

**Comment by maxx1128** [comment]
Below are the full details for the front-end architecture, currently subject to change or additional details.

# Front-end Architecture for VBA Regional Office

## Title and Description

1. **Title:** Title is an `h1` tag, and is filled by the `vba_facility.title` variable
2. **Description:** Description will be in a `p` tag below the title, and is filled by the `vba_facility.field_cc_national_des` field.
3. The three action links will be hard-coded into the page using the [action link](https://design.va.gov/components/link/action) component with hard-coded links. If the pages do not exist, then the link paths can be left empty.
4. **Table of Contents:** This will use the [On This Page](https://design.va.gov/components/on-this-page) component. It automatically generates the list of jump links based on the included `h2` elements.

## Location and contact information

1. **Location and Photo:** The location photo and embedded Google map will be built from the `src/site/includes/image_and_static_map.liquid` partial.
2. **Address:** The address information will be built from `vba_facility.field_address` without a specific component. The directions link will be created with the `src/site/includes/directions-google-maps.liquid` partial.
3. **Phone Numbers:** This will be plain text, and the phone numbers will come from `vba_facility.field_phone_number` and be built with [phone number](https://design.va.gov/components/telephone) components (one for each number).
4. **Office Hours:** This data comes from `vba_facility.field_office_hours` and be passed into the `src/site/includes/hours.liquid` partial.

## Prepare for your Visit

1. **Accordions:** the field for these accordions' data is currently unknown. But it will be an array of data that will need to be passed into the `<va-accordion>` and `<va-accordion-item>` [design components.](https://design.va.gov/components/accordion), similar to health care local facility pages at `src/site/layouts/health_care_local_facility.drupal.liquid`.

> NOTE: check to make sure the content renders as expected while building the page out. The "action link" component may have never been used in the context of an accordion before. If this is the case for this component or any other new accordion components, it will need a new front-end "paragraph type" template. Each new template will need its own ticket for adding it.

## In the spotlight at Boston Regional Office

1. **Spotlights:** The field for the array of spotlight data is currently unknown. But the array items will need to be looped through the `src/site/includes/vet_centers/featured_content.liquid` partials.
    * Jordan Wood has confirmed this is the accurate design, and this partial will have that design.

## Veteran Benefits, Family member & caregiver benefits, Service member benefits, Other services

1. **Accordions:** Accordions will be handled with the same `<va-accordion>` and `<va-accordion-item>` [design components](https://design.va.gov/components/accordion) as "Prepare for your Visit."
    * It is currently unknown what those fields will be called, or if they will be an array of arrays in one field or a series of fields each with a specific array. As long as each section as the correct headings with `h2` elements, it should still render properly and create the expected table of contents at the top of the page.
2. **Informational Alert:** This will use the [informational alert component](https://design.va.gov/components/alert#informational-alert).
    * The content will be populated from a centralized content field.
    * The bottom link goes to the facility locator. If it's version 2, it should already be filtering by benefits.
3. **Updates from the VBA:** The text and link text/URLs will likely come from centralized content fields as well, since it refers to national VBA social profiles. It will use the `src/site/facilities/facility_social_links.drupal.liquid` template.

## Other nearby VA locations

1. **Nearby Vet Centers:** This section will use the `NearbyVetCenters` component located at `src/applications/static-pages/facilities/vet-center/NearByVetCenters.jsx`. It will need to use the `src/site/includes/vet_centers/nearby.liquid` partial. Below is a example of what code will _likely_ need to be (which will include the `h2` header).

```liquid
{% include 'src/site/includes/vet_centers/nearby.liquid' with
    mainVetCenterPhone = vba_facility.fieldPhoneNumber
    mainVetCenterAddress = vba_facility.fieldAddress
    mainVetCenterId = vba_facility.fieldFacilityLocatorApiId
%}
```

## VA locations in other areas

1. **Last Updated and Feedback:** Both parts of this section will be built from `src/site/includes/above-footer-elements.drupal.liquid`.

**Comment by eselkin** [comment]
This looks like a great breakdown.

**Comment by mmiddaugh** [comment]
@xiongjaneg let's please identify the best `early` place to loop @laflannery into this FE work and ensure her review is part of the AC in relevant tickets

**Comment by laflannery** [comment]
I do have some clarifying comments on the above - just additional specifics (I only included items that I had notes on):

## Front-end Architecture for VBA Regional Office - Accessibility notes

### Title and Description

1. **Title:** Title is an `h1` tag, and is filled by the `vba_facility.title` variable
    _1. This will not have an `aria-describedby` attribute (there is one on the Vet Center H1 and we should not be copying that markup)_
2. **Description:** Description will be in a `p` tag below the title and is filled by the `vba_facility.field_cc_national_des` field.
    _1. Wrapped in a `div` with class `va-introtext`_
3. **Action Links:** These will be hard-coded into the page using the [Secondary action link](https://design.va.gov/components/link/action#secondary) component with hard-coded links. The link paths can be left empty if the pages do not exist.
    _1. To clarify, if the pages so not exist, the entire link should not display on the FE, it should not be an `<a>` with an empty `href`_


### Location and contact information

_**Heading structure**
H2 - Locations and contact information
H3 - Address
H3 - Phone numbers
H3 - Office hours_


Did the "Limited services and hours" section get missed? I didn't see a section for it. But it should use the [Alert Expandable component](https://design.va.gov/components/alert-expandable), the color would depend on the status level

1. **Location and Photo:** The location photo and embedded Google map will be built from the `src/site/includes/image_and_static_map.liquid` partial.
    _1. Be sure to include the alt attribute and pull the text from Drupal_
2. **Address:** The address information will be built from `vba_facility.field_address` without a specific component. In other instances on the site, it is built from a paragraph tag with line breaks added where needed.
    _1. This should be built using the `<address>` tag as is used on Vet Centers_
3. The directions link will be created with the `src/site/includes/directions-google-maps.liquid` partial.
    _1. Must open in a new tab using `taget="_blank"`
    2. Must also have `rel="noreferrer"` attribute
    3. Must have sr-only text containing the title of the facility to create unique links - following pattern used on Vet Center and VAMC pages_


### Prepare for your Visit

_**Heading structure**
H2 - Prepare for your Visit
H3 - Each accordion header
More? If the content within accordions is non-WYSIWYG content I will want to specify/review headers here as well._

### In the spotlight at Boston Regional Office

_**Heading structure**
H2 - In the spotlight at Boston Regional Office
H3 - Each spotlight title_

### Veteran Benefits, Family member & caregiver benefits, Service member benefits, Other services

_**Heading structure**
H2 - Each top level Benefits section header
H3 - Each accordion header
More? If the content within accordions is non-WYSIWYG content I will want to specify/review headers here as well._


1. **Accordions:** Accordions will be handled with the same `<va-accordion>` and `<va-accordion-item>` [design components](https://design.va.gov/components/accordion) as "Prepare for your Visit."
    * It is currently unknown what those fields will be called or if they will be an array of arrays in one area or a series of fields, each with a specific array. If each section has the correct headings with `h2` elements, it should still render correctly and create the expected table of contents at the top of the page.
        _1. I'm not clear what this means but just to clarify, each accordion header title will be an H3, not an H2. Accordions will not be included in the "On this page" ToC component._ 
2. **Informational Alert:** This will use the [informational alert component.](https://design.va.gov/components/alert#informational-alert)
    * The content will be populated from a centralized content field.
    * The bottom link goes to the facility locator. If it's version 2, it should already be filtering by benefits by passing in the needed variables in the URL.
    _* The alert should use a level 3 heading (I'm thinking of this as a child of "Other Services")_
6. **Updates from the VBA:** The text and link text/URLs will likely come from centralized content fields since they refer to national VBA social profiles. It will use the `src/site/facilities/facility_social_links.drupal.liquid` template.
   _1. Links must open in a new tab using `taget="_blank"`
   2. Links must also have `rel="noreferrer"` attribute_

### Other nearby VA locations

_**Heading structure**
H2 - Other nearby VA locations
H3 - Each facility name_


### VA locations in other areas

1. **Last Updated and Feedback:** Both parts of this section will be built from `src/site/includes/above-footer-elements.drupal.liquid`.

_**The text here needs to change. We cannot have a naked link. I believe this was waiting to be changed until research was done. Now that is has we can follow up with Jordan I believe.**_

## Remaining Questions

2. We need to check if any new components are being used in the accordions that have not been used, such as the action links. If so, we must create new templates for them, or they won't render on the page. Cc: @laflannery for potential accessibility issues
   _1. I didn't see any use of an action link or anything else fancy inside of an accordion. Cna you point me to where you are seeing this?_

**Comment by jilladams** [comment]
@xiongjaneg @maxx1128 2 notes: 
1. re: the tickets Max suggested at the end of his [comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14552#issuecomment-1712035536) -- just noting that, holler if you would like help cutting those.
2. A11y review of the plan is a (smart) add-on here, and I don't think it's worth making a new ticket. In the spirit of keeping everything in one place I've proposed a new AC for this for Sprint 93, in this ticket body, to review/integrate that feedback. @xiongjaneg if there's a better way to handle that, feel free to edit / do what makes most sense.

**Comment by xiongjaneg** [comment]
@jilladams Michelle and I discussed and agreed there's the follow-up ticket that actually captures a bunch of what was done here. I'm going to move the AC you created to that ticket, and make it a PO assigned ticket as it's review of the work done in this ticket. Thanks!

**Comment by jilladams** [comment]
Ok! That in mind: closing this ticket.

**Comment by maxx1128** [comment]
@jilladams @xiongjaneg I have just integrated the accessibility feedback into the ticket. As per @laflannery's question about where an action link is inside an accordion, I saw an instance of it in the "Home Loans" accordion in the linked Figma doc (see below).

<img width="409" alt="Screen Shot 2023-09-14 at 9 40 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/59471f8b-7227-4f67-915f-9063b19e09cd">

**Comment by xiongjaneg** [comment]
RE: Create all remaining VBA Regional Facility GraphQL queries.

- These should cover all data needed in each page section.
- It should be confirmed that the data is accessible in the page layout.

Is the list of remaining tickets correct?
