### ISSUE TITLE
Error prevents deleting a facility

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14565]
## Describe the defect
When deleting a facility, which should be avoided, there is an error that prevents it.

> Drupal\va_gov_content_types\Exception\NoOriginalExistsException: No original version exists for this node. in Drupal\va_gov_content_types\Entity\VaNode->getOriginal() (line 42 of /var/www/cms/docroot/modules/custom/va_gov_content_types/src/Traits/GetOriginalTrait.php). [dd.trace_id=9223372036854775807 dd.span_id=8118747153603467487]

## To Reproduce
1. Go to '/node/3819/delete'
2. Click on  the delete button
5. The deletion does not occur.
6. See recent log messages for the cause.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/dc9adb5f-2b7e-4dbc-822f-e52b4baae9ec)

## AC / Expected behavior
The facility node should delete successfully.

## Additional context
[This line](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_content_types/src/Traits/GetOriginalTrait.php#L47) is making an assumption that $node->original is there, when in many cases (node creation, deletion) it is not there at all.

**Comment by jilladams** [comment]
@swirtSJW can you add a comment here to clarify status - we have 2 closed PRs / nothing merged but ticket is closed. Not sure what that means, for reportings' sake.

**Comment by jilladams** [comment]
@swirtSJW @ndouglas : But now confused again. 

1. This ticket had a PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14567 -- closed in favor of a different PR
2. The different PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14569, merged
3. There is also a ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14576 - closed in favor of a different ticket
4. The different ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14580
5. THis ticket is also closed but I'm not clear on whether: 
    a. It's closed as a dupe of #14580 also, OR
    b. It's closed bc it was resolved by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14569, meaning this bug should not repro in Prod any longer

I need to report it one way or the other, because of https://dsva.slack.com/archives/C0FQSS30V/p1690576693783859?thread_ts=1690576263.569249&cid=C0FQSS30V. Please let me know!

**Comment by ndouglas** [comment]
The confusion might come because there are two related but distinct problems here:
1. Deleting a facility does not trigger a content release.
2. Attempting to delete a facility _did_ trigger a nasty error.

- #14565 is for an error that occurred when deleting a facility
- #14567 and #14569 were slightly different approaches to fixing #14565 that @swirtSJW and I collaborated on.
- I opened #14576 to deal with the issue that Swirt and Christian were looking at (triggering a content release when deleting a facility)
- Swirt opened #14580, probably not seeing #14576. I read #14580 and it was better than #14576, so I closed #14576 without further comment.

So this ticket is closed by the work Swirt and I did in #14569. It is not a duplicate of #14580.
