### ISSUE TITLE
Spike: review environments for Next Build PRs

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14600]
## Description
Currently we are able to run tests as part of the CI process for a pull request in Next Build. However, it will also be useful and necessary to have a shared review environment available for testing purposes.

Potential options (not limited to these):
* Tugboat
* VA Platform review instances (Tech Team 4)

## Acceptance Criteria
- [ ] Technologies for review instances are identified and compared
- [ ] If a clear best candidate emerges, identify it and provide basic implementation guidance (this can be as simple as a link to documentation)
- [ ] If a clear best candidate does not emerge, identify what research/POC/etc would help determine a best candidate

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

**Comment by timcosgrove** [comment]
Tanner

**Comment by tjheffner** [comment]
> There are no limits on seats so yall are fine to use [tugboat]
- Erika

**Comment by tjheffner** [comment]
the VFS-CMS team has tugboat implemented already.

I also found these existing documents on tugboat feasibility + poc from Tech Team 4:
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2398912575/Tugboat+A+Feasibility+Discovery
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2422112428/Tugboat+POC

The latter seems like similar steps to set it up for our repo. I will check on integrating it with next-build later today

**Comment by tjheffner** [comment]
I created a tugboat project for `next-build` here: https://tugboat.vfs.va.gov/64d5537c2d3036648da7c7fc
Tugboat environments are generated for next-build PRs as of here: https://github.com/department-of-veterans-affairs/next-build/pull/138

Initial builds failed due to lack of memory when running the export command to generate static pages.

@ndouglas graciously updated the memory for that tugboat project like so:
```
ssm-session utility tugboat
sudo su - root
tugboat update 64d5537c2d3036648da7c7fc memory=8192
```

After bumping the memory (and playing with the certificate loading some), `yarn export` passed successfully. The first two builds initially failed on six various slugs, but all looked correct in the cms (and exported locally). There have been no weird slug errors in that PR's builds since, but it is something to note / keep an eye on.

Currently, it's about 8 minutes for a full build of the tugboat container, installing node and yarn dependencies then exporting all static pages that next-build currently knows about (News Stories & Listings).

Once that is merged and the config is available to all branches, I will set up a new base preview from the `main` branch which should cut that time for new PRs.

In the future, we may want to create a docker image that has the correct node and yarn versions pre-installed, that will further decrease times for all builds. Potentially a task for Kit once they are onboarded.
