### ISSUE TITLE
Oracle testing database

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#14818]
For the Income Limits application in vets-api, we need to query the VES Oracle database routinely. vets-api has no current pattern for connecting to an Oracle database, so we will need to learn how to do this for the first time.

Because the VES database is not accessible from a local machine, creating the scripts to query VES could potentially create lots of churn with PRs, reviews, and iterations, we need a way to query an Oracle database locally. Any test instance will work.

# ACs
- [ ] Work with Devops/Platform to get an Oracle database (docker?) that is accessible locally.

**Comment by wesrowe** [comment]
@dsasser, can you please estimate? 

And if I understand right, this is a blocker to the "export from VES" ticket?

**Comment by dsasser** [comment]
> @dsasser, can you please estimate?

Difficult to estimate given the possible dependencies on other teams, but I think we should limit to a 5.

**Comment by jilladams** [comment]
Notes from planning: 
* Without access to an Oracle db, we don't necessarily know how to query it
* We can use vets-api draft PRs and get a review instance where we could try queries pre-merge / pre-prod
  * As a developer experience, this will be the flow for maintenance ongoing. But: once we develop the query, have this in place, maintenance should be minimal. Needs to be documented.
* Oracle is not free, so if we _do_ end up needing one in order to figure out the work, this will be a process.

**Comment by jilladams** [comment]
@dsasser @FranECross I think this ticket is also now obsolete and can be closed. Closing, but if I'm wrong, please reopen.
