### ISSUE TITLE
Flagged Facilities: Fort A.P. Hill renamed Fort Walker

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14872]
## Description or Additional Context 
Fort A.P. Hill will officially be renamed Fort Walker as of August 28, 2023. This will impact the [Pre-Discharge Site at Hill Air Force Base vba_341g](https://www.va.gov/find-locations/facility/vba_341g)

## Steps for Implementation
Refer to runbook for VBA changes:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vba-facility-name-change.md

VBA facilities haven't been published, so right now they are being handled from a user-facing perspective by the Facilities API only.

Currently, these facilities don't have aliases yet.

## Acceptance Criteria
- [ ] Flag removed

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by mmiddaugh** [comment]
@xiongjaneg this one needs to be pulled into the next sprint as the renaming ceremony occurs today

**Comment by omahane** [comment]
@xiongjaneg A couple items for your awareness. We do have a runbook for VBA changes:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vba-facility-name-change.md

VBA facilities haven't been published, so right now they are being handled from a user-facing perspective by the Facilities API only. 

In that regard, even the runbook to which I linked is not right (currently) because these facilities don't have aliases yet.

**Comment by mmiddaugh** [comment]
I made the necessary updates in Sandy's VBA database.

**Comment by omahane** [comment]
And the flag has now been removed.
