### ISSUE TITLE
Accessibility audit of VBA menu

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14894]
**1. What is this request for?**

VBA menu is a new component being created for the VBA Regional Office MVP

VBA Content Specs XLS linked in #13096

### Acceptance Criteria
- [ ] Code recommendations documented as ticket  
- [ ] UX recommendations documented in Figma created in #14845

**Comment by laflannery** [comment]
@Agile6MSkinner This was created by a previous PM as a separate ticket to audit a future thing once we build it. However I would like to close this because:
- That's not how we typically work, I do my audit within the scope of the build tickets
- We don't know when this will be built, how, the parameters, etc. I feel like having this ticket hang around at this point is not necessary.

Feel free to reopen if you disagree though!

**Comment by Agile6MSkinner** [comment]
I love closing tickets. No argument here.
