### ISSUE TITLE
FE: Opening Crisis modal on top of Login widget results in inability to close the modal

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14925]
## Description
@jtmst discovered an issue with having the login modal and the Crisis Line modal open at the same time. This can happen if you load the page with `va.gov/?next=loginModal`, and click on the Crisis Line modal before the login widget loads. Reproducing this on a fast connection is not highly likely, but those with slower connections will have enough time to trigger this issue.

Josh's Loom of the defect:
https://www.loom.com/share/7123bf6497504f559583e4c458feae59

### User story

**AS A** Veteran
**I WANT** to be able to close all modals using the `X` button
**SO THAT** I have the best user experience and do not have a page in an unrecoverable state

### Engineering notes / background

Steps to reproduce:

1. Go to `va.gov/?next=loginModal`, hovering over the area where the Crisis Line trigger is (red banner)
2. Click on the Crisis Line trigger before the login modal loads
3. Note that the Crisis Line modal is not able to be closed by the `X`

## Acceptance criteria
 * GIVEN: a Veteran or other user is on va.gov
 * WHEN: the Crisis Line is open
 * THEN: do not open the login modal

**Comment by randimays** [comment]
@jilladams @FranECross @thejordanwood This is a tricky one to solve:

If a person lands on `/?next=loginModal`, that doesn't necessarily mean they want to log in. They could have saved that link while trying to sign in previously, and now use it as the VA homepage.

There's also a slim, but not zero, chance that someone will click on the Crisis Line button immediately after loading this page. They could accidentally click it. I thought I could simply hide the Crisis Line modal if the Sign In modal shows up. But it seems the Crisis Line modal should take priority given its emergency nature.

It would be a confusing (and likely not desired, from a design perspective) experience to have 2 modals open at once. Any thoughts about what the behavior **should** be here?

**Comment by FranECross** [comment]
@randimays I agree that the Crisis Line modal should take priority and not be closed automatically.  In the Loom video, it appears that clicking the X on the Crisis Line modal actually does close it, but that Josh had to click it twice. Is that true?

**Comment by randimays** [comment]
@FranECross Yes, in Josh's video he could click it twice and it worked. But for some reason, it's not working that way for me. The focus is still on the login modal, so when the user would try to interact with the Crisis Line modal, they'd end up pressing a login button instead.

https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/d583f0a9-261a-47f7-9fa7-39cdd7aa5008

**Comment by randimays** [comment]
[Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1701112778779749) discussing the decided behavior: if Crisis Line modal is open, do not open login modal.

**Comment by randimays** [comment]
Mid-sprint update: This will likely carry over since we prioritized some PACT Act work in front of it.

**Comment by randimays** [comment]
End-of-sprint update: This will carry over due to the PACT Act content prioritization.

**Comment by randimays** [comment]
Update: This defect is proving to be a tricky one. I found a solution for the mobile header, but the desktop header uses the dev-template.ejs locally and is otherwise coming from content-build (I think). Continuing to troubleshoot and hoping to find a solution for this today.

**Comment by jilladams** [comment]
Per discussion with Randi: she checked GA ([report since Sept 1](https://analytics.google.com/analytics/web/#/report/acquisition-channels/a50123418w177519031p176188361/_u.date00=20230901&_u.date01=20231212&_r.drilldown=analytics.trafficChannel:Direct&explorer-table.plotKeys=%5B%5D&explorer-table.filter=va.gov~2F%3Fnext=loginModal)) and it seems no one lands directly on [va.gov/?next=loginModal](http://va.gov/?next=loginModal). If you go to [va.gov](http://va.gov/) and click Sign In, you're redirected to [va.gov/?next=loginModal](http://va.gov/?next=loginModal) and the login widget pops up. If you reload the page there, you will land on [va.gov/?next=loginModal](http://va.gov/?next=loginModal). But it seems we don't have organic traffic to that link.

Fran conferred with Dave today, and he agreed: because this is a difficult-to-trigger edge case that is not making progress on a solution, he's ok setting this aside and focusing on other front-end priorities. Removing from Sprint 99, closing as no-op. 

Dave also noted that long-term: he's questioning having VCL info open in a modal at all, and may agitate to change that during Header/Footer rebuild, tbd.
