### ISSUE TITLE
Front End template skeleton for Facility content type for VBA

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14940]
## Description or Additional Context 
Front End skeleton template for updates to VBA Facility content type per spec #13130 

### Resources
- Refer to VBA Content Specs XLS linked in #13096
- [Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)

### Assumption
Query is ready.

## Acceptance Criteria
- [x] All needed data is pulling in from the query, except for data that is not available on the CMS. (part of the engineering 5 points)
- [x] The pages are rendering at the expected URL (not necessarily linked to other pages yet). (part of the engineering 5 points) -- URL is tbd from 10/11 meeting out of #15490 
- [ ] Accessibility is reviewed by Laura (estimate 3 of the points)
- [x] Work is in a DO NOT MERGE PR, and ticket is moved to Complete Pending Integration

**Comment by xiongjaneg** [comment]
Add ACs to the next ticket (8 pts)
- [ ] The front end shown matches the design file to a reasonably accurate extent.
- [ ] Any refinements to the front end have been stubbed out in tickets.
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by maxx1128** [comment]
I started this ticket later in the sprint and have begun working on the code. It will carry over into the next sprint or whatever sprint we push it to.

**Comment by jilladams** [comment]
Mid-sprint: Spotlights aren't coming through, centralized content, needs to be flattened. Max working on it today, will leave notes for Eli to follow up if that doesn't wrap today. 

Then: last a11y review and ready to merge.

**Comment by jilladams** [comment]
@eselkin reminder that this ticket includes A11y review, so when you feel like it's ready for @laflannery please ping her with pointer to the environment where she can take a look. 

And Laura: FYI that in scrum today we discussed the fact that this ticket is _really_ a skeleton, so lots of empty spaces where content will come later.

**Comment by jilladams** [comment]
Discussed with Eli: 
* Review Instances keep 502ing. 
* Tugboat: Max has a tugboat with Cms content, and needs to be refreshed with content-build changes, so this may be a place for @laflannery to review, if that gets working. 

Eli will holler if /when that gets working. Since this PR isn't going to merge ins print anyway, if the A11y review gets delayed, we _could_ split it into its own ticket, to call this done.  @xiongjaneg for awarenss in case this is where we land for end of sprint.

**Comment by jilladams** [comment]
From scrum: this shouldn't merge to prod. We _could_ put it behind a feature flag, but for now: can move to Complete Pending Integration.

**Comment by eselkin** [comment]
I forgot to put a comment here, but it is now operational on Max's tugboat. The URL that is in the image on the PR is: 
https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/vba-facilities/locations/seattle-regional-office/

**Comment by jilladams** [comment]
For end of sprint: 
* Laura has a couple of a11y questions[ in the PR](https://github.com/department-of-veterans-affairs/content-build/pull/1762) that will get covered under #15315 
* Because this PR will not merge until later, this ticket is staying in Complete Pending Integration, but reported as complete for sprint boundary.
