### ISSUE TITLE
PAW: Design checkbox and radio button validation experiences for multi-select questions

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14951]
### User story

**AS A** Veteran
**I WANT** to be alerted clearly when my checkbox selections are contradictory and be told clearly how to resolve the issue
**SO THAT** I can continue with minimal cognitive difficulty.

**AS A** Veteran
**I WANT** to be prevented from advancing from a required radio button question until I select a resonse
**SO THAT** I can continue with minimal cognitive difficulty.

#### Checkboxes
Several questions in the wizard experience (as of prototype phase) use a checkbox interface. The first options are essentially "yes" responses, as they indicate locations where the Veteran served. The final two checkboxes are "None of these" and "I'm not sure." If Veterans check a box(es) in both the "yes" list, and also No or Not sure, we need to ask them to resolve the contradiction.

#### Radio buttons
This is a simple required-response situation. Design system component may provide an error response already, otherwise a pattern should be easy to find.

#### Design 

[PACT Act Sketch file](https://sketch.com/s/2bf4405b-5cc4-4672-88fb-d215abdf3b0d)

## Acceptance criteria

- [x] Sought existing patterns for this type of validation of contradictory checkbox responses
- [x] Created [a Sketch file](https://sketch.com/s/2bf4405b-5cc4-4672-88fb-d215abdf3b0d) that depicts all the possible states for one of these checkbox questions
- [x] Documented radio button validation experience for required questions
- [x] Internal review with Wes, Amanda
- [x] A11y review

**Comment by wesrowe** [comment]
@thejordanwood, this is a likely pickup for you in the next sprint. Pre-refine when you have a sec, and/or we'll discuss in refinement if we have time.

**Comment by thejordanwood** [comment]
@wesrowe After speaking with @laflannery about the checkbox validation, our recommendation is that we keep all "Did you serve in these locations?" questions structured consistently. Instead of having conflicting checkboxes on these questions, we should divide them up into 2 questions. 

1. First question would be "Did you serve in any of these locations?" with the answer options Yes/No/I'm not sure.
2. If yes to question 1, the next question would be "Which locations did you serve in?" with a list of checkboxes and locations. 

This would impact 3 questions total (S2.2, S2.2.1, S2.3 shown in [the Mural Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=u01810f3edbfc878c08be5925)).

<img width="320" alt="subtask 2" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/b50473a1-0437-4191-be98-6846da9b440a">

<img width="320" alt="subtask 1" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/979117dd-a435-402c-b0f4-e779d47fddf2">

**Comment by cindymerrill** [comment]
Changing the checkbox questions into 2 questions would affect the content and increase the number of questions (which we really don’t want to do!) and would need to be run by Danielle. The content is hers and we'd need to discuss the change with her.

**Comment by cindymerrill** [comment]
Decided via [aync collaboration in Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1693952233210549) with Danielle to go with @thejordanwood and @laflannery 's suggestion above because adding 2 more questions seems less problematic than adding complexity to the R1 results screens.

**Comment by thejordanwood** [comment]
This work is approved and the [visual flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=u01810f3edbfc878c08be5925) has been updated to show the new questions.
