### ISSUE TITLE
Defect: Campaign Landing Page button leads to Campaign Landing Page

### ISSUE THREAD

**Issue by chri5tia** [department-of-veterans-affairs/va.gov-cms#14955]
## Describe the defect
This button does nothing and also refreshes the page in a way that is scary and could lose Editor's data.

## To Reproduce
* Steps to reproduce the behavior:
  * When logged in as a user with the "content_admin" role
  * And I am at "node/add/campaign_landing_page"
  * And I click to expand "Downloadable resources"
  * And I click to enable the page segment
  * And I click the "Add existing Downloadable resource" button
  * And I click the "Add Downloadable resource" button
  * I am brought to the beginning of the Campaign Landing page node add form

It doesn't matter if a previous downloadable resource has already been loaded up and previously entered content remains but it the page is reloaded so some content may not be cached or entered data could be lost.

## AC / Expected behavior

-[ ] The "Add Downloadable resource" should allow the user to add another resource. 
-[ ] Investigate and fix

## Screenshots

<img width="611" alt="Screenshot 2023-08-23 at 10 17 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/dc17d49f-5760-408d-ad24-c6e6b362d4cd">

<img width="507" alt="Screenshot 2023-08-23 at 10 17 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/d0017538-84db-45a0-b7d9-2523b50bd35c">

<img width="559" alt="Screenshot 2023-08-23 at 10 18 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/56597e72-9138-44b5-bf35-2e5ddf70f08b">

 ## Additional context

<img width="333" alt="Screenshot 2023-08-23 at 10 22 32 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/096df66e-7886-4f49-a342-e266b9fd3bba">

**Comment by wesrowe** [comment]
Next step: we think this button probably is duplicating the "cancel" function. If we can verify that, then the solution is obvious: remove it.

Wes to try it out.

**Comment by dsasser** [comment]
## Status Update 12/21/23

This bug has been more difficult to wrangle than I originally estimated. I've done a lot of debugging and this is what we currently know:

- The 'Add Downloadable Button' (the button in question under this ticket) is visible only after choosing the 'Add an existing Downloadable Resource' in the 'Resources' section of a CLP node edit form.
- This button is rendered by the Inline Entity Form module from the `inline_entity_form_complex` widget.
- The button has '#ajax' settings added by IEF which causes the button to be submitted via an ajax callback, rather than a full page refresh (at least that is the intent).
- The enabled module Entity Browser Entity Form (EBEF), the `entity_browser_entity_form`, overrides part of the rendering of the IEF widget if an Entity Browser is selected in the field form settings.
- In EBEF's `entity_browser_entity_form.module` file, in a 'hook_inline_entity_form_reference_form_alter' hook, the module modifies the button's #ajax properties of the button, adding an 'event' of 'entities-selected', which changes the triggering event when the button is pressed, to one controlled by Entity Browser Entity Form.
- If this code is removed (line 72 of entity_browser_entity_form.module), the button is processed by ajax as expected, and the page does not refresh
- However, this causes Entity Browser to behave oddly--after a selecting Documents (not unexpected since we removed code from the module)
- This issue is demonstrable in a bare-bones, freshly installed Drupal site with no custom code.

**Comment by Becapa** [comment]
Here's what I think is going on with this:

- IEF (Inline Entity Form) is creating this portion of the form. It adds an `entity_autocomplete` field for adding an existing downloadable resource followed by a save button ('Add Downloadable resource') and a cancel button. This is all done in the function `inline_entity_form_reference_form` in `inline_entity_form.module`.  
- Entity Browser then takes over and replaces the entity_autocomplete with an `entity_browser`. Instead of being an autocomplete field it is now a link ('Select Downloadable resource') that opens the entity browser. Once something is selected in the browser modal, it automatically triggers the save button. This happens in function `entity_browser_entity_form_inline_entity_form_reference_form_alter` in `entity_browser_entity_form.module`.

Since the save button is being used by the entity browser, I don't think we can just remove it. Maybe we can hide it?

**Comment by jilladams** [comment]
@Becapa wanna go ahead and see what hiding it does / get it in a Tugboat for review? 

I think it's worth noting that https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6160 exists as an epic to "Deprecate and/or reduce and standardize the use of Inline Entity Form" so if there's a bigger picture out of this ticket that we should track there re: how we'd like things to work in future, feel free to note it on that epic.

**Comment by jilladams** [comment]
Noting for end of sprint: this will roll to Sprint 101 to work out the approach.

**Comment by dsasser** [comment]
Confirmed in prod.
