### ISSUE TITLE
Facilities - Front End tickets

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14963]
### VBA Regional Office Pilot MVP remaining tickets 
- 3 -  Front End: #15959 refined
- 1 - Front End: #14947 refined
- 3 - Front End: #14937 refined
- 5 - Front End: #14929 refined
- 5 - Front End: #16243 refined
- Front End: #14938 
- Front End: #14927 
- Front End: #14943 
- Front End: #14936 
- Front End: #15223 
- Front End: #16311 
- Front End: #16254 
- Front End: #16144 cross-listed with VAMC

12/20/23 - 17pts + (8 x ~3? guesstimate til after SPIKE) = ~41 pts  

### Facilities API: Lighthouse V1 upgrade for other teams' consumption
- [x] #15000 
- [ ] #15344 

SPIKE blocks full assessment of size / cutting remaining tickets.

### Facilities products: Adopt V1 in prep for v0 deprecation remaining tickets
- [ ] 3 - #12156 

## Other VBA tickets
- Drupal: #14531 refined
- Drupal: #16146 refined
- Drupal: #11628 refined
- Drupal: #15901 refined
- Drupal: #16327 
  - FE: May result in ticket
- Drupal: #16348 cross-listed with VAMC
  - FE: May result in ticket
- UX: #15989 refined
- UX: #16068 refined
- UX: #15155 
- Product: #16369 refined
- Product: #14758 refined
- Product: #14482 refined
- Product: #11304 refined
- Product: #16268 
- Product: #15381 
- Product: #15752 

### Police Transparency MVP remaining tickets
- UX: #16413 
- UX: #16415 
- Drupal: #16329 
  - Implement UX updates re: Police /VAMC menu placement & multiple phone #s - would be included or need sep tickets?
- 5 - Front End: #15722 refined
- 3 - Front End: #15723 refined
- 5 - Front End: #16407 refined
- Front End: #16414 
- Front End: #16438 
- Product: #16330 refined
- Product: #16267 refined
- Product: #16023 refined

Questions: 
* Is it likely the remaining UX tickets will generate new FE / Drupal tickets, or any changes are covered by existing tickets?
* To confirm: existing tickets cover implementing the components we removed from MMVP scope? 

### VAMC
- Front End: #16144 cross-listed with VBA
- Front End: #15693 
- Drupal: #15576 
- Drupal: #14731 
- Drupal: #15559 
- Drupal: #16348 cross-listed with VBA

### Vet Centers
- Drupal: #16362 

### Facility Locator
- Front End: #16282 
- Front End: #16368
- Front End: #15569 

### Accessibility 
- Front End: #12089 
- Front End: #14755 could go at the same time as following FL pagination issues
- Front End: #14895
- Front End: #12088 

### Monitoring/Testing
- Front End: #16083 
- Front End: #16084

**Comment by xiongjaneg** [comment]
check on [Drupal 10 Testing epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13112)

**Comment by mmiddaugh** [comment]
@xiongjaneg 

- unless there is immediate application for [Editors shouldn't be limited to adding only 3 Service locations #7252](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7252) (i.e. relevance to VBA), let's save it for our future selves (acknowledging that I'm the one who dredged it up to begin with)
- suggest we connect [Facility phone audit report is missing some content types #14721](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14721) to the mental health phone number work somehow since that is the business need driving its prioritization 
  - I assume we should also connect [Create VAMC facility Phone View #15648](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15648)
- suggest moving [Restrict VBA RO editors from editing certain fields #15396](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15396) up in the order -> probably somewhere above [VAMC services are showing too much of the service term on node view #15387](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15396) so we address the VBA items first)

also, I'd like to see us get as far as we can stubbing out the tasks to complete the police data work so we can fairly evaluate the amount of work remaining and determine if we need to start making some concessions

**Comment by mmiddaugh** [comment]
@xiongjaneg @jilladams - Adding a few new items to your radar

- Update VR&E name in Facility Locator [#15837](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15837) 
  - high priority:  this change is long overdue and should be prioritized quickly
- Staff Profile sidenav accessibility defects - no label and empty list [#15519](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15519)
  - [please see @laflannery's comment](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15519#issuecomment-1775914978)
- Standardize spotlight patterns in CMS facility content types [#13804](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13804)
  - If we've resolved the blockers (which in part prevented us from previously resolving the related duplicate "Read more" accessibility issue), I'd like to prioritize this to resolve the defect and to allow us to leverage the spotlight boxes to support VA health chat for a few pilot VAMC locations
- FE Provider training design implementation [#15823](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15823)
  - Given Max's success this past sprint, I believe we're able to now pull through the PPMS training data through to the front end 
  - it will still need to be turned off but this will allow us to complete our implementation and just await sufficient data

**Comment by xiongjaneg** [comment]
@davidmpickett Is #13804 a UX ticket?

**Comment by mmiddaugh** [comment]
[Feature function for Story content types only allows one Featured story](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11221#top) #11221 - [see comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11221#issuecomment-1789087403)

**Comment by xiongjaneg** [comment]
@xiongjaneg create a spike ticket for service region subsection

**Comment by mmiddaugh** [comment]
@xiongjaneg based on the next steps mentioned by Eli in the closed Monitoring/Testing issues #15260 and #15225, I stubbed out the following placeholder issues to give you a place to start - they can be refined/separated/edited as needed 
- Add e2e tests for Cypress on Content-build #16083
- Improve alerting via DataDog #16084

I would like to know the level of effort for the testing/monitoring tasks Eli feels have the highest value

**Comment by mmiddaugh** [comment]
Unless there is a compelling reason, I don't see a need to prioritize a level 4 defect to [Avoid mouse centric instructions #13937](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13937) at this time. Please let me know if I am missing important context. 

I suggest moving the pagination issue out for now because we should probably discuss this group together
- pagination scroll behavior
  - #14755
  - #14895
- pagination announcement
  - #12089
- #12088 (which may or may not be blocked by the design system

I'd propose swapping in a defect -1 level issue for Invalid ARIA attributes #10300
@laflannery is there a high value ally issue you'd recommend?

**Comment by laflannery** [comment]
@mmiddaugh I haven't been recommended or pulling forward any Drupal issues lately due to other priorities - #10300 is a Drupal issue and while it is important it is not Veteran facing.

If there is space to add accessibility issues, I would suggest the pagination issues, we have quite a few of those as you mentioned and those are the most high value FE issues currently in the backlog.

As far as the defect-4 goes - it was only suggested as a quick fix issue that could be done if someone had a small amount of time.

**Comment by xiongjaneg** [comment]
@xiongjaneg Create ticket to create widget for data for the VA Police including all the things Dave updated for the ACs for the JSON ticket and widget should accept data from content build in form of definitions from cc

**Comment by xiongjaneg** [comment]
@jilladams Check on PII in vets-api issue, will want that to be pretty stable before working on it
