### ISSUE TITLE
Add directive text to VBA Centralized Content

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14978]
**May overlap with #14978**

## User Story or Problem Statement
The [National VA benefit office content](https://prod.cms.va.gov/centralized-content/national-vba-facilities-content) node has been created to power content blocks that will display on all Regional office & Satellite office pages. 

Within Centralized Content nodes, there are Centralized content descriptor fields that help give national editors context for what the different fields do. These will show up as gray boxes for editors.

![screencapture-prod-cms-va-gov-node-61744-edit-2023-10-11-10_07_39](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/011e3b13-ee98-48fe-b137-49790ad7a985)

In #14699, @davidmpickett reviewed the Titles of the Centralized content descriptors, but did not touch the Descriptions. These should be reviewed / rewritten to make sure adequate context is provided. These can be edited by true admins

![screencapture-staging-cms-va-gov-node-61744-edit-2023-10-11-09_56_31](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1b6d3319-a193-4899-90cb-d53d7de22b94)

## Acceptance Criteria
- [x] VBA centralized content descriptor fields have been reviewed and rewritten
- [x] Requires design review

**Comment by xiongjaneg** [comment]
Add $14699 CC text AC to this ticket

**Comment by omahane** [comment]
The implementation of #14699 is directly tied to this. What type of content we add in the centralized content blocks determines the paragraph types used, and thus, the paragraph IDs/UUIDs, which is what we will then put into the Entity Field Fetch fields. Thus, this needs to be done in tandem with 14699.

**Comment by xiongjaneg** [comment]
From Michelle: she can provide content too if needed

**Comment by jilladams** [comment]
@davidmpickett added a draft AC while reviewing today with Jane, if you could take a look and verify this is what we meant, and estimate points? (Which we won't track if Michelle does the work.)

**Comment by jilladams** [comment]
@thejordanwood assigned this to you with the understanding that #14978 may encompass the work and this might be closable.

**Comment by thejordanwood** [comment]
I suggested copy changes in a comment on the VBA Centralized Content page in [the Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=166%3A798&mode=design&t=st3bxMjN7F3wdPqa-1).

**Comment by thejordanwood** [comment]
@davidmpickett Surfacing this here because there are a lot of comments in the Figma file. My suggested changes for the directive text are below, along with a suggested change to the spotlight content header. Let me know if you have any feedback!

Note: Steve suggested not getting too specific with this help text, because any changes to the FE template will mean we need to rewrite this text. We can get rid of the part in my text where it tells editors where the sections will appear on the FE if we're concerned that may happen. 

**Benefit office overview**
Add a brief description of the facility. The overview will show below the facility name on VA.gov.

**VA benefits hotline**
Add a hotline that will show as an additional phone number below the main facility number on VA.gov.

**Benefit office hours may vary**
Add additional information that will show in the facility hours section on VA.gov.

**Featured spotlight content**
Add content that is relevant to every facility. This content will show on all VA benefit office pages, below the Prepare for your visit section on VA.gov. 

**Can't find the benefit service you're looking for?**
Tell Veterans how they can find benefit services at other locations. This content will show below the list of services on VA.gov.

**Get updates from VBA**
Tell Veterans how they can get updates by email, social media, etc. These links will show below the service section on VA.gov.
