### ISSUE TITLE
Updates to VBA RO FE design based on usability findings 

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14981]
## User Story or Problem Statement
Placeholder ticket for parking any proposed changes to the VBA FE design that come up during usability testing.

## Description or Additional Context 
- [Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)
- [Figma prototype](https://www.figma.com/file/8RYmYfVGS9CUfZbomH5lBe/VBA-Regional-Office-Prototype?type=design&node-id=0%3A1401&mode=design&t=SlHJILwOK72VDczD-1) (This will not be updated after usability testing)

## Steps for Implementation

(Updated after refinement on 10/19/2023)

**MUST**
- [x] ~~Using different design system component for spotlight items to reduce "false footer" effect ([featured content component](https://design.va.gov/components/featured-content))~~ Refinement feedback: Leave the spotlight section as is, with blue boxes and in the same location.

**SHOULD**
- [x] From Sitewide CAIA - Suggest adding a sentence under the "Manage your benefits online" header to help make it clear why we're including this on the location page. "You always have the option to apply for and manage your VA benefits online."
- [x] Consider moving phone number above hours within accordion
- [x] Consider appointments info above hours
- [x] Consider having order of info in accordions match that of page (e.g. appointment action link towards top)
- [x] Consider a way to indicate when hours in a service location differ from the office vs being a repeat

**CONSIDER**

- [x] Consider placement of spotlights on page (especially on mobile)
- [x] Whether accordion content is too complex for an accordion
- [ ] ~~Consider ability to share information from accordion (help users deeplink without understanding HTML)~~
- [ ] ~~From Sitewide CAIA - Could break service location brief description into a bulleted list. "Our benefit counselors can help you with tasks like these:~~
  - ~~Checking your eligibility for benefits~~
  - ~~Gathering documents~~
  - ~~Filling out forms~~

## Acceptance Criteria
- [x] Usability findings are reviewed and approved by PO/DM
- [x] Usability findings are implemented
- [x] Sitewide CAIA recommendations are implemented
- [x] Accessibility is reviewed by Laura or a subsequent ticket is created if needed

**Comment by davidmpickett** [comment]
Won't be refined until sometime during Sprint 94, but would also like work to begin in Sprint 94

**Comment by jilladams** [comment]
@ALogsdon3 @thejordanwood (cc @mmiddaugh ) Noting: we need to finalize this ticket for Sprint 95, once Research findings are done, and make sure Michelle is aligned on the changes we're suggesting before this gets started. Noting this to help us all remember during planning.

**Comment by thejordanwood** [comment]
Feedback from refinement: Let's leave the spotlight section as is, with blue boxes and in the same location. We can review this along with it's placement on Vet Centers at a later date. 

@xiongjaneg Did you want to create that future ticket or should I?

**Comment by xiongjaneg** [comment]
@thejordanwood I'll create the ticket and link here. Thanks for the tag!

**Comment by thejordanwood** [comment]
Design notes: I didn't do 2 of the changes listed under "consider" and wanted to explain why. 

1. **Breaking service description into bulleted list**
I’m against making this change. The description should be brief, and I think adding a bulleted list to it will make it longer. Making it longer forces people to scroll more before they get to relevant info.

2. **Consider ability to share info from accordion**
I agree with making this change but am wondering if this is more of a site wide issue? In my mind, we would hyperlink similar to how it works on the [VA design system pages](https://design.va.gov/components/accordion). When you hover over a header, you see a hyperlink symbol next to it. We could use that behavior on accordions here too. I think that’s a bigger issue than just VBA pages and may be out of scope for this. 

@xiongjaneg For number 2, would you suggest creating a ticket for this to add to the backlog?

@swirtSJW Tagging you for awareness since number 2 was your idea. I think being able to hyperlink accordions would be really beneficial and hope we can do some work on this!

**Comment by xiongjaneg** [comment]
@thejordanwood Will stub ticket and link here. Thanks!

**Comment by thejordanwood** [comment]
Updates discussed in refinement have be made to [the Sketch file](https://sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff).

**Comment by laflannery** [comment]
I did not catch this before - I should have so my bad but the spotlight links should be underlined, we don't have a pattern in the DS for non-underlined links:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/a20cf408-5c76-472b-9c1d-f4c41dd83e5e)

**Comment by xiongjaneg** [comment]
@laflannery I see your note above. Is there more accessibility review needed on this one or is it ready to close?

**Comment by laflannery** [comment]
@xiongjaneg I have done my review and that was my only note so if i was last then this can be closed!

**Comment by thejordanwood** [comment]
@xiongjaneg @laflannery I've underlined the spotlight links in the Sketch file. Thanks Laura!
