### ISSUE TITLE
SPIKE: FE dive on how to achieve KISS / data searches

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15054]
## Description

Epic = https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14993 and contains notes on the scope / potential approaches for how to allow plain language search of health services within the Facility Locator 

All of the plain language associations are available within the health services taxonomy.

KISS has been proposed as a means to pull the Taxonomy content, make it available browser side for on the fly querying. 

## Engineering notes
Right now KISS's main implementation is using Drupal to manage Cerner data. This is documented in https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for, and this is a model for how KISS could also be used for managing Taxonomy data, to some extent.

Swirt knows KISS and can be consulted for details. Ryan Koch built the Cerner implementation and could also be available, as needed. (Be judicious in use of his time.)

## Acceptance criteria
- [x] Existing KISS implementation / options are reviewed / understood, and any concerns re: usage for Taxonomy / Health services search are documented on ticket
- [x] Proposal / plan for path forward are documented on ticket
- [x] Any alternative ideas for how to manage plain language search, if not KISS, are documented on ticket
- [ ] Engineering plan scheduled (ask Jane to schedule and include Drupal and UX) for gotchas / next steps in terms of ticketing

**Comment by xiongjaneg** [comment]
Kiss it simply Static, here's a knowledge transfer ticket from Ryan Koch: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13823

**Comment by xiongjaneg** [comment]
What is the plain language search supposed to be? The search is based on a typed in term, e.g., kidney plain language search turns up renal, nephrology, etc. What about typos?

Search logic is based on 526ez Form https://www.va.gov/find-forms/about-form-21-526ez/.  If login is needed to view the form, there's a Github login or Laura can help identify the right person to ask.

**Comment by xiongjaneg** [comment]
est 5

**Comment by eselkin** [comment]
> What is the plain language search supposed to be? The search is based on a typed in term, e.g., kidney plain language search turns up renal, nephrology, etc. What about typos?
> 
> Search logic is based on 526ez Form https://www.va.gov/find-forms/about-form-21-526ez/. If login is needed to view the form, there's a Github login or Laura can help identify the right person to ask.

Here's the file with the autosuggest logic
`src/applications/disability-benefits/all-claims/pages/addDisabilities.js`
in `vets-website`

**Comment by aklausmeier** [comment]
commenting for my own visibility to stay in the loop on this

**Comment by eselkin** [comment]
Just putting this here from some notes I was developing.

My notes above document how the form 526 uses data in vets-website from a hard-coded taxonomy file. Data is fed directly from the file to the autocomplete text field. There is no redux interaction, nor any drupal interaction. 

It does **NOT** follow the `Cerner->VistA` method of relying on a redux reducer to pull data from drupal, nor could it switch over to that. 

The `Cerner->VistA` method was instituted because lots of disparate parts were relying on flippers per-facility to determine if that facility needed a link to Cerner or VistA portal. Whether a facility was Cerner or VisA was placed behind a redux slice that got data from drupal _en masse_.

If 526 in the future needed to pull from a list of conditions on drupal, that would not be super complicated, but it would be a one-off process. If we want to pull from a file and then move to pulling from drupal, this is possible as well. It would be advisable to pull all taxonomy for health services into redux and have redux process and give the component the data via a slice. 

The reason for allowing such a redux interface would be that you could change where the data was being loaded from in an action with little difficulty and it's abstracted from the person working on facility locator or whatever service in the future might need the data.

**Comment by xiongjaneg** [comment]
@eselkin What's the process for refreshing data? How often should the process be refreshed, for example if a new taxon is added.

**Comment by eselkin** [comment]
I didn't see this. It would get refreshed at every build/deploy of content-build.

**Comment by jilladams** [comment]
Updated #14993 with pointers to these SPIKE results, and that ticket is queued for next refinement. SInce Jane is gone this week, and we won't get to the engineering meeting in th elast suggested AC before she's back, I'm closing this as done, and we can regroup in next FE prefinement about what happens next.

**Comment by xiongjaneg** [comment]
discussed at 10/19/23 engineering refinement
