### ISSUE TITLE
CMS Collab Cycle intake request – Q&A Naming Conventions (PW)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15150]
## Description of the problem / issue / enhancement

Requesting Collab Cycle guidance – Public Websites discovered that the addition of "reusable Q&As" (aka "Q&A - Single") to the CMS resulted in a lot of confusing naming conventions. We designed a solution and feel ready to implement.

- Immediate need from CMS team: Do you want to review this change? _We don't really think CMS team would have any reason to block the name changes, since they only affect PW products and we have studied the problem thoroughly._
- Longer term: We also see Q&As as a possible addition to the CMS Design System. Curious about your thoughts.

- See [**this Mural**](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689892596393/dc147aedc3e6182dbe0ad911a4c10877ac06c129?wid=0-1692828153761) for observations about how naming conventions and help text around Q&As might need to change in order to make them less confusing for CLP Editors.

## Description of known dependencies
All existing impacted products belong to PW.

## Rough estimate of urgency and impact
* urgency as it relates to timeframe needed and why
* impact as it relates to # of people affected, their roles, and severity (i.e. can't perform their job duties)

We would like a quick ruling on CMS team's interest in this, as we have momentum going to improve Q&As and add to a new content type.

## Acceptance Criteria
- [x] The Product Manager for the recommended intake team is pinged through Slack about the issue
- [ ] The Product Manager has discussed with the respective Product Owner to determine prioritization
- [ ] Any decisions made on prioritization or implementation are communicated back to the originating team

### Team
Please check the team you project will do this work. If not sure, select "Program".

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by BerniXiongA6** [comment]
@EWashb -- can we discuss?

**Comment by EWashb** [comment]
@wesrowe thank you for alerting us to this change, and I appreciate the thoughtful mural the team put together! The only initial thought with what you have listed there is using the word "section." Usually, we have avoided calling things sections within our help text since "section" in Drupal has a meaning on its own. 

Additionally, expounding on the workflow differences within your help text would be helpful. The current help text does a great job explaining the new element, but help text should be written to encourage/explain to the editor how to complete the action. The button should not stand alone as the sole indicator of what to do to complete an action. 

Otherwise, I agree with your statement that a full-out collab cycle review/meeting, etc., isn't appropriate here.

**Comment by wesrowe** [comment]
@EWashb, how does this fit into the Must Should Could framework? 

That would help us figure out if we're blocked or not. (And whether we need to get back into this after it has been approved by CAIA.)

**Comment by wesrowe** [comment]
Update: @EWashb, we found an easy substitution to make, we'll call them "groups" instead of "sections." And Jordan will take your help text note also. Closing!

**Comment by EWashb** [comment]
@wesrowe sorry I missed the tag. I would say neither of those suggestions is launch blocking :)
