### ISSUE TITLE
BE: Events: Editor should be prevented from canceling the initial instance of a recurring event

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15168]
### User story

**AS AN** (Event) Editor using the "Edit event series" UI
**I WANT** to be prevented from deleting a recurring event's first instance
**SO THAT** I don't create weird and/or system-corrupting data.

### Engineering notes / background

Background:
- The need for this safeguard was uncovered in fixing a defect where an Editor deleted all instances of a recurring event, #15085

Design ideas (to pre-fine):
- Change the dropdown options on the first instance of the recurrent event to remove "cancel"
- (less desirable) Leave the dropdown/UI as-is, but block it at save

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ] In the "Edit occurrences" modal, the "Cancel event" option is hidden from the dropdown on first instance
- [ ] Added tests (what kind? etc)
- [ ] Design review
- [ ] PM review

**Comment by wesrowe** [comment]
@dsasser, rather than starting off asking @thejordanwood to design how this should work – do you have an idea for the most drupal-y way to handle this?

**Comment by wesrowe** [comment]
discussed in BE refinement – we decided it would be an adequate Editor experience to hide the delete option from the dropdown. this is a very edge-case situation.

**Comment by FranECross** [comment]
@jilladams @dsasser If we're light on backend/drupal work, is this a possible candidate, or is it such an edge case that we should just keep it in the ice box?

**Comment by dsasser** [comment]
> @jilladams @dsasser If we're light on backend/drupal work, is this a possible candidate, or is it such an edge case that we should just keep it in the ice box?

I think the last time we tested this, it wasn't occurring any longer. We might want to make sure it is still a problem before we commit it to a sprint.

**Comment by FranECross** [comment]
Would a small testing story be more appropriate for ya'll to see if it's still a problem? I could then prioritize this or close it as no longer needed. Not a rush, just grooming tickets today.

**Comment by dsasser** [comment]
@FranECross 

I just tested this, and it isn't possible to create an Event without at least one date, be that a recurrence, or the primary start/end dates. So the original edge case is not possible to realize.

If a user creates an Event with one or more recurrences, and manages to cancel all the occurrences (including the primary Event date), they will receive an error on save. You can see this in the screenshot below.

![Screenshot 2023-11-29 at 3 57 53 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/3f90091f-5e96-4fde-8776-2ae2050e1b1d)

My $.02 would be that this is a no-op, since there may be cases where the primary Event date, for whatever reason, needs to be canceled, but the recurrences may not. Having this in place means that the Editor is given the utmost control over the dates of the Event without allowing them to break things, nor having to re-create an event because the primary Event date could not be canceled.

**Comment by FranECross** [comment]
@dsasser Thanks so much for testing this and your observations! I agree and will close as not needed.
