### ISSUE TITLE
Test coverage / dependencies gap analysis for Facility pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15225]
## Description
As the Facilities team, we want to be the first to know when connections between our pages and their sources of data have been disrupted. 

## Tasks
- Document what is known today about the following, related to connections necessary to render information on VAMC, Vet Center, and future RO pages 
  - What are the connections responsible for VA facility searches?
   - What are the connections responsible for community care data searches?
   - Who owns each connection?
   - Will we know if the connection fails?
     - If so, how will we know? What test or system will tell us? Do we currently monitor this test or system? 
   - If we identify an issue, how do we notify the owning team? Who is the POC?
   - If this connection fails, what happens in the Veteran experience? (is there a graceful error message?)
   - Do other teams depend on our connection?
     - If so, which teams and how will we notify them? 
- Identify missing knowledge and processes

## Considerations
Datadog could tell us more, but requires access. 
We can request, and if Platform isn't responsive, can request help from DaveC to get response.

## Acceptance criteria
- [x] Existing processes and knowledge are documented
- [x] Issues to address missing knowledge or processes are created and ready for refinement

**Comment by mmiddaugh** [comment]
@swirtSJW @omahane 
Where does the CMS push to Lighthouse fit into this? Who is responsible for monitoring?

**Comment by eselkin** [comment]
https://docs.google.com/document/d/1RGvcbqnmYM7i-PQcdTMZgNrleI1pbskSJPBYg2UhEOk/edit?usp=sharing

**Comment by eselkin** [comment]
# Facilities and Facility Locator pages dependencies and testing

## Table of Contents

1. [Landscape chart](#landscape-chart)
2. [System Dependencies](#system-dependencies)
3. [Component Dependencies](#component-dependencies)
4. [Unit Testing](#unit-testing)
5. [Integration Testing](#integration-testing)

## Landscape chart
```mermaid
flowchart TD;
    subgraph VA
        vast[VAST, Access To Care, etc] -->fapi;
        vapi[[Vets-API]];
    end
    subgraph CMS[CMS]
        fapi[(Facility API)] -->migrations[CMS migrations];
        migrations-->nodes[Nodes: VAMC, Vet Centers, VBA, NCA];
    nodes-->data
    data[CMS supplemental data: status, health services] -- On change in CMS -->fapi;
    end
    subgraph FEG[Front End Sitewide]
        vw[[Vets-website Sitewide]] -- GH Actions on PR --> t(("`Testing: 
         component / e2e cypress`")) -- GH Actions --> cb;
        subgraph FAC[Facilities FE]
            fapi --> vapi --> vw;
            fl[[Facility Locator]] --> vw; 
            findl[[Find-locations pages]] --> vw;
            cb[[content-build PW & Fac]];
            facilities[[Facility Pages Vet centers, VAMC, VBA RO, etc]] --> cb
        end
        subgraph PW[Public Websites FE]
            pwp[[Public Website pages]] --> vw & cb
        end
        nodes --> cb
    end
    subgraph DES[Design]
        uswds[U.S. Web Design System]-->vads[VA Design System]-->dtest(("`Testing & 
        Storybook`"))-->fl & findl & pwp & facilities
    end
    cb -- week days --> deploy((Deployment))
```

## System Dependencies

### CMS (prod/staging)
#### Content-build
The CMS system is the primary dependency on which content-build relies. All pages are processed from the pages.json file statically at compile time and therefore doesn’t depend on CMS at runtime. This makes it not a likely point of failure. The only type of failure that could happen is if the CMS diverges from the graphql queries in `stages/build/drupal/graphql`. If there is divergence, broken pages will result (verified by modifying data in the graphql queries without corresponding values in the CMS– causing banners to appear when they shouldn’t). The metalsmith build process doesn’t seem to indicate what testing is being done on the pages built from the liquid components. There don’t seem to be any tests to guarantee correctness of data on any page. This is likely due to the fact that the majority of pages are dynamic based on CMS content.

> In case of failure, likely contact Steve Wirt or Christian Burk, but in the case of something like “CMS is not responding” escalate to the platform team. 

#### Vets-website
Vets-website does not directly pull from dynamic CMS. So, changes in CMS will not affect vets-website. It does pull from static CMS data in the form of the `https://www.va.gov/data/cms/vamc-ehr.json`. However, this is a small portion of the data on vets-website. There is an indirect link between CMS and vets-website, in that CMS pushes data to LightHouse and LightHouse is consumed via vets-api by vets-website.

### Vets-api

#### Content-build
No dependencies in content-build

#### Vets-website
Vets-website heavily uses vets-api for all facility related data (locator/find-locations/details about various types of facilities). All calls to vets-api from vets-website should be using vets-api’s v1 endpoints.

For facilities such as Vet centers, VA Benefits, VAMC facilities, and VA Cemeteries the vets-website makes a call to `https://api.va.gov/facilities_api/v1/va`. For CCP vets-website makes a call to `https://api.va.gov/facilities_api/v1/ccp/provider`. For Urgent care `https://api.va.gov/facilities_api/v1/ccp/urgent_care`. For Emergency care `https://api.va.gov/facilities_api/v1/va?type=health&services[]=EmergencyCare` and `https://api.va.gov/facilities_api/v1/ccp/provider?specialties` with several (4) specialties. For Pharmacy `https://api.va.gov/facilities_api/v1/ccp/pharmacy`

All routes on Vets-api are managed by the Facilities team and monitored in datadog. Facilities team, up to this point, has been managing the routes but ICs on the team had not had access to datadog directly. We recently got access to datadog. 

> Vets-api is a bit ambiguous who the line of defense is for when the system fails. If vets-api services dev, sandbox, staging, or prod are not responding, escalate to the platform team via a support request. These systems are on EKS and therefore unlikely to be completely down. 

### Lighthouse (LH)
While lighthouse is not directly called by vets-website or content-build, vets-api heavily relies on lighthouse for data. CMS feeds data directly to lighthouse and therefore, to some degree vets-website depends indirectly on CMS.

> Questions about LH on the DSVA slack platform channel often end up identifying that the platform team does not control LH or operate on LH in any meaningful way.

### Sandy’s Database
While Sandy’s database is not directly called by vets-website or content-build, vets-api and CMS rely on data from this database for things such as location of facilities, hours of operation, etc. Michelle Middaugh has access to this database. It is unknown if there are any systems tests or monitoring of this data source.

> Questions about this database should be directed to Michelle, or platform team. However, it appears that it is not necessarily the platform team who is responsible for this data source. 

### VAST
Outside OCTO. VAST is consumed by Facility API


## Component Dependencies

### Content-build
Uses the dsva components which in turn use uswds components

### Vets-website
Uses the dsva components which use uswds components

> If components are not functioning correctly, contact design system team


## Unit Testing

For all unit tests, the Facilities team is responsible for successful testing of components. Contact Maxwell Antonucci or Eli Selkin about testing that is not complete.

### Content-build

Most unit tests in content-build are tests to determine whether the liquid processing helper functions are correct. 

> There are some facility specific tests, such as the spec which tests centralized content processing. This is maintained by the Facilities team. Contact Maxwell Antonucci or Eli Selkin or Steve Wirt about this test.

### Vets-website
> Responsible people for failing tests: Maxwell Antonucci or Eli Selkin
These tests seem somewhat sporadic. Components tested are in `src/applications/facility-locator/tests/components`. 

Those include:
- CCProvider link
- Covid19 component for facility locator
- Location directions link
- Location distance
- Location information
- Operational status
- Phone Link
- CCP result
- Covid Result
- Emergency Care result
- Pharmacy
- Urgent care
- VA Facilities


## Integration testing

### Content-build
According to cy:open/cy:run there are only a few specs for e2e testing vets-website:
VA and TRICARE Lovell About page (2) ✅
VA and TRICARE Lovell Main pages (2) ✅
An accessible dialog that does not work ❌
A required test for analytics and homepage test ✅
No other facility static page has testing. It may be that testing these pages is impossible or superficial testing for unchanging objects would yield not useful data. Additionally, when datadog status is in place, the only types of monitoring on these pages would be to determine if the pages are receiving 404s or some other error.

### Vets-website
There are 499 end-to-end tests. The majority are tests related to form completion either by mouse-clicks and typing or keyboard only navigation and not related to facilities. There are a number of end-to-end tests related to facilities that should be maintained by the Facilities team that must pass (are not disabled).

Find-locations via URL with facility ID (nested under facility-locator, is this misleading?) - no separate testing for keyboard accessibility
- detail page uses: http://localhost:3001/find-locations/facility/vc_0304V
- Closed message: tests alert for facility closed ✅
- Limited service: as above but for limited service ✅
- No message: no alert ✅
- Any message ✅

Facility locator - 
- messages in returned data - no separate accessibility for the error message tested✅
- downtime notification - waits for tool to break - looks like a broken test, but is running correctly ✅ AXE NOT INJECTED
- accessibility - tests everything except whether search actually functions. However doesn’t enter text in zipcode text input ❓
-  CCP Disabled - ✅ - disables option in dropdown
- CCP Enabled - ✅- enables option in dropdown 
- detailPage - AXE NOT INJECTED - also this seems like the wrong location for this 
- errorMessages - AXE NOT INJECTED - error messages for facility locator drop downs and text boxes ✅
- facilitySearch all succeed except breadcrumbs. Uncertain why it’s left in an ambiguous state. Possibly because it doesn’t multiple tests missing AXE, but is it necessary in all scenarios?
- gaEvents - ✅
- Geolocation - AXE missing -  ✅
- Map-zoom - flaky❓
- Mobile - missing AXE check ✅
- Provider search - About half are missing AXE check ✅
- serverErrors  Missing AXE check ✅


## Axe tests
Axe testing is done via cypress injection. Axe tests are required to be done in any unit or integration test. However, a majority of tests do not have Axe injected into the testing and there are warnings all over the place that Axe was not included. It is not just facilities tests that do not include Axe. It is possible the Axe injection and the rule to inject it came after those tests were created. 

> If Axe tests fail, consult Maxwell Antonucci, Eli Selkin, or Laura Flannery 


## Future directions (alerting)

### Content-build and vets-website need datadog/sentry alerting

In order to alert, we need to know if metrics are being gathered on deployed content-build. Currently in datadog dashboard all mentions to `content_build` are either for build details or deploy details, not post-deployment. 

- Number of requests below a certain threshold of 200 responses
- Threshold of 400+ errors (unknown what current rate is)
- Proportion of 200 to 400+ errors

### Vets-api needs alerting for all vets-api routes or Facility controllers 
- 429 errors (blocks)
- Number of 200 errors below a certain threshold
- Number of 400+ errors on each of the routes mentioned in section Dependencies > Systems > Vets-api > Vets-website

CMS uncertain if alerting needed
- Alerts on pushes from CMS to LightHouse? Can `vagov` datadog monitor this?

**Comment by xiongjaneg** [comment]
@eselkin @maxx1128 I'm going to put the dependencies and testing findings in a Github page and will add that link here.

I'll create two tickets for each future direction item for future refinement. Thank you!

**Comment by xiongjaneg** [comment]
The analysis pertains to Facility Locator in #15224. The analysis for this ticket should focus on VAMC, Vet Center, and future VBA pages. Reopening this ticket.

**Comment by eselkin** [comment]
4 points done, it's about separating the facility-only content from the above post. Basically, there's not any significant testing for facility pages and the most we can do analytics-wise for facility pages is find if there are 404s (not possible through Datadog at the moment).

**Comment by jilladams** [comment]
@eselkin clarifying: am I reading this right that most Facility pages don't have significant unit test / e2e test coverage? If that's the case, we'll need tickets to flesh that out per-product, in addition to monitoring / alarms.

**Comment by eselkin** [comment]
Right. We need to find a way to test.

**Comment by eselkin** [comment]
For all VAMC/Vet Center pages (i.e. all pages depending on CMS in content-build- not vets-website):
Here's screenshots of the e2e testing done
![screencapture-github-department-of-veterans-affairs-content-build-actions-runs-6303137029-job-17115255543-2023-09-26-16_19_25](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/4bfc4b90-577c-49c1-b1f3-a4ac60ce7e85)

and the unit tests

![Uploading screencapture-github-department-of-veterans-affairs-content-build-actions-runs-6303137029-job-17114080758-2023-09-26-16_20_35.png…]()

All the unit tests are basically functional tests of the processors that are used in the pages. Things that convert one format to another, make some modification of the paths, or change something Lovell-y, etc. are tested in the unit tests. The only thing remotely facility-related is Lovell stuff in the e2e testing.

What takes forever in testing content-build is the drupal content processing, not testing or anything. It takes a long time to download and process drupal data.

**Comment by xiongjaneg** [comment]
Steve: There is monitoring for failed pushes to Lighthouse. The area of concern for a test is should the front end be able to pull information from facility-api. It wouldn't be happening on the front end repos.

**Comment by eselkin** [comment]
I think we should say that this is done, given that my search for testing (nearly nothing found) and dependencies (charted in the mermaid graph) was as complete as possible.

**Comment by xiongjaneg** [comment]
@mmiddaugh Let's review and discuss at our 1:1. Thanks.

**Comment by xiongjaneg** [comment]
@mmiddaugh To review and comment, specifically looking at end to end testing

**Comment by xiongjaneg** [comment]
@eselkin Did you review the hook from Facility Locator search results to modernized pages? Please comment here and ask @mmiddaugh if you have any questions.

**Comment by xiongjaneg** [comment]
@xiongjaneg Move updated process info to Github doc and link that doc to incident response for shared knowledge

**Comment by eselkin** [comment]
What is the hook from Facility Locator to modernized pages? I may have considered it, but what are we talking about when we say modernized?

**Comment by xiongjaneg** [comment]
@eselkin Usually when we say modernized, we're differentiating between content living in Drupal CMS versus the old CMS Teamsite (which our teams don't support). But I would defer to @mmiddaugh for her specific reference.

**Comment by eselkin** [comment]
@xiongjaneg All pages I considered were pages that are either created in content-build (from Drupal) or generated dynamically in vets-website (e.g. from combinations of vets-api/LH etc). I imagine the modern pages we're talking about getting hooked in are the ones from `/find-locations` that get populated after the link, I didn't consider any non-modern pages, you might say, because those don't have drupal/vets-api/testing dependencies that are in the CI pipeline as currently being built.

**Comment by jilladams** [comment]
Next step: Eli / Michelle to sync for understanding takeaways in plain language. Jane to schedule.

**Comment by jilladams** [comment]
@eselkin can you confirm if you've talked to Michelle & state of this ticket for end of sprint?

**Comment by swirtSJW** [comment]
> @swirtSJW @omahane Where does the CMS push to Lighthouse fit into this? Who is responsible for monitoring?
@mmiddaugh Sorry I missed this question.  Kudos to @omahane for bringing my attention to it.

I think in @eselkin diagram he captured the CMS pushe piece here
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/eb9e9608-6a03-47ce-8325-0d50a17d7d21)


The question of monitoring is a good one.   Each push is self monitoring.  If a push of either service or status fails to be received, an alert it made to the cms-notifications channel.
Example:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/7675a04e-f945-4399-b8b3-76b5eb736b1f)

These are also logged to the CMS so then end up in Sentry too.

We also have several hundred rounds of tests that confirm the right conditions result in pushes.

**Comment by jilladams** [comment]
Next step: FE refinement will stub follow up tix.

**Comment by xiongjaneg** [comment]
In content build, we have a bunch of tests for things like does this processing step change this format to that format.
We don't have end to end tests for example, does a random page have x,y,z (H2) element on it? A lot of these pages are so dynamic, we don't know what is going to be on a page from one day to the next. It's hard to write tests for this stuff.

We can go through the liquid templates and find the if conditions and pick random facilities that we think fall into one condition of a branch or another and test those against the branch condition. This would take a considerable amount of work to find the conditions and find a facility that has that branch of the condition. The testing would likely have to be Cypress testing after the page is build (example, Lovell).

There might be the possibility of testing raw page data in the JSON and look for conditions that are in the raw data such as the URL should be tested. We could create a test on a certain page that's pulled from the JSON.

We would want to get this done relatively soon but this could wait until code freeze time.

**Comment by xiongjaneg** [comment]
Will stub out tickets at next pre-refinement as future work can wait until code freeze time.

**Comment by jilladams** [comment]
This ticket will close during S96, as next FE refinement is on 11/1.

**Comment by jilladams** [comment]
Closing per convo with Jane in planning.
