### ISSUE TITLE
Node 18 does not run on our ASGs due to OpenSSL errors

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15239]
### What is the problem?

When attempting to run Node 18 on our own self-hosted runners provisioned by ASG, we get an error referencing 'unsafe legacy negotiation'. 

### Who is affected?
 
Engineers attempting to run Cypress tests.

### How urgent is the issue? 
**Critical** / Major / Minor

```[tasklist]
###
- [x] Cypress tests are able to run and complete on CI
```

### How can we see the problem? (repro steps)

1. Open a PR with the `cypress.yml` file enabled, as with https://github.com/department-of-veterans-affairs/next-build/pull/161.
2. Observe the resulting workflow run. 

**Expected result:** Workflow should run and not throw Node errors.<br />
**Actual result:** Errors are thrown as seen in logs below.

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))

When running `yarn set version stable`
```
Run yarn set version stable
  yarn set version stable
  HUSKY=0 yarn install --immutable
  shell: /usr/bin/bash -e {0}
  env:
    NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
    OPENSSL_CONF: /etc/ssl/openssl.cnf
error An unexpected error occurred: "https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js: write EPROTO C047CD9F087F0000:error:0A00015[2](https://github.com/department-of-veterans-affairs/next-build/actions/runs/6152452302/job/16694609491#step:5:2):SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:[9](https://github.com/department-of-veterans-affairs/next-build/actions/runs/6152452302/job/16694609491#step:5:10)22:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/runner1/_work/next-build/next-build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by tjheffner** [comment]
The openssl + node errors have been sorted out in https://github.com/department-of-veterans-affairs/next-build/pull/180. It should be merged early sprint 94.


I worked through the GHA workflow to solve the openssl/node 18 errors with the updated `.github/workflows/cypress.yml`. 

But I also instead decided to have cypress tests running per PR on the tugboat build instead of GHA. this way we only have to build & host once per PR.

The workflow for cypress on ASG should be utilized for a daily/nightly/weekly/etc that runs the sitemap a11y check in a follow-up ticket.
