### ISSUE TITLE
Create a new runbook for New Vet Center

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15265]
## Description
The best time to document the steps necessary for creating a new Vet Center facility in CMS may be when the situation actually occurs. 

## Acceptance Criteria
- [ ] a new runbook has been created in the form of a github issue template
- [ ] the specific steps to create this new runbook have been created with help desk input
- [ ] supporting KB articles are created and/or updated

**Comment by mmiddaugh** [comment]
This is blocked until the situation arises

**Comment by jilladams** [comment]
@mmiddaugh Noting that our [Flagged Facilities runbook docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/flagged-facilities.md#runbooks) point to a runbook for new Vet Centers: [runbook-vet-center-new.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-new.md). It looks like that's been around for a bit but hasn't been updated since this ticket was created. Would you be able / willing to take a look and update here if you expected to see any specifics that aren't present there?  If not, we can probably close this one.
