### ISSUE TITLE
Front End: Rack attack

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15290]
## User Story or Problem Statement
Tech Team 1 noticed reoccurring requests to the V1::Facilities::VAController endpoints from a single user in Datadog. This is a possible incident/DoS attack. Recommended solution: Put rate limiting in place for your endpoint via rack_attack

## Description or Additional Context 
See [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1695046907329529)

## Acceptance Criteria
- [ ] Team has implemented pretective measures to prevent DoS attacks from a single user

**Comment by jilladams** [comment]
I took a stab at an AC, super loose since we don't know the right mechanism yet, and what's within our scope of control exactly. Other notes from this morning's scrum discussion: 

**Datadog**: only Jill and DaveP have read access

Attack seems to be from one caller at a specific IP who is both a legit user, and sending spammy amounts of calls to V1::Facilities::VAController.

Rac_attack.rb is a throttler that throttles IP addresses being allowed into vets-api. Not a big picture traffic throttler. It restricts any given IP to a certain number of calls in a specified amount of time.

Doesn’t impact Lighthouse, since it's one user, as far as we know. 

We can exclude this user's IP, but that will limit/block their legitimate activity. If we go this route, we likely need to work with Helpdesk on comms?

**Comment by eselkin** [comment]
tested on va.gov and is now limiting after 30 rapid refreshes of the locator.
