### ISSUE TITLE
[SPIKE] Investigate timeouts in `content-build` content release workflows and shorten them where possible.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15302]
## Description

As detailed [here](https://dsva.slack.com/archives/C02VD909V08/p1695133252153049?thread_ts=1695070625.941539&cid=C02VD909V08), I suspect that workflows occasionally assign jobs to unhealthy runners and then idle waiting for the runner to actually start the job for some unknown period of time.

Some workflow steps should take only a few seconds to run; if they take upwards of a minute, we should consider them failed and retry them or move on to avoid holding up the pipeline.

## Acceptance Criteria

- [ ] Timeouts in the workflow have been investigated and are well understood.
- [ ] Issues have been addressed, or followup ticket(s) have been opened to address them.

**Comment by ndouglas** [comment]
I'm not positive this can be tackled effectively, so I'm calling this a spike and suggesting it be timeboxed to a couple points. Don't go nuts beating your head against the wall on this one.

**Comment by ndouglas** [comment]
@ariperez I'm not sure if this holds true for the GH API, but in the UI: when this happens, the runner is usually marked `offline` but actually deleting it is not possible. Maybe that's a GH UI bug. So, yeah, ideally we should continually zap any runner that is offline, but that's more the subject of a different ticket (#15301).

This ticket aims to work around another problem: that once GHA assigns a task to a crap runner, even one that goes offline or otherwise dies, that task will just sit there for several minutes. So ideally, we'd be able to shorten the timeout so it only wastes a minute or so max before saying "okay, this is dumb, let's try again".

**Comment by ariperez** [comment]
There doesn't seem to be a straight forward to set a timeout to tell GH Actions to move on after 'x' amount of mins where the job is stuck or hasn't fully kicked off.  Not sure why GH doesn't expose this.  

There is a possibility after completing department-of-veterans-affairs/va.gov-cms#15301, this will not be an issue since we will be telling the GH Action API to remove the runner at the exact moment the EC2 is no longer active.  This might be what GH needs to stop trying or not try in the first place.
