### ISSUE TITLE
Design: CLP aspect ratio: Document approach for CMS and FE move to 1:1 ratio

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15351]
### User story

**AS A** CLP Editor
**I WANT** to upload an image that will look good across all aspect ratios seen by Veterans across devices
**SO THAT** Veterans have the best experience with my campaign.

### Engineering notes / background

In #15147 we determined that the actual shape of the CLP hero image across most browser/portal widths is approximately 1:1. The exception is very wide desktop browsers, where the image extends beyond the width of the rest of the VAgov page.

Jordan's audit in that ticket found the following characteristics of published CLPs:
>This is my audit of the current published CLPs. I think we could make the new image ratio work for all of them, although I may need to manually fix a couple of images. 

**Will not impact:**
1. https://www.va.gov/initiatives/veteran-trust-in-va/
2. https://www.va.gov/initiatives/veterans-experience-action-centers/
3. https://www.va.gov/initiatives/recognizing-lgbtq-veterans-during-pride-month/
4. https://www.va.gov/initiatives/vote/ (original image is a square)
5. https://www.va.gov/initiatives/end-of-life-benefits/ (I could manually crop if needed)
6. https://www.va.gov/initiatives/covid-flu/ (I could manually crop if needed)
7. https://www.va.gov/initiatives/sign-in-securely-with-logingov/ (I could manually crop if needed)
8. https://www.va.gov/initiatives/national-buddy-check-week-talk-to-10-veterans/ (moved this to will not impact because it looks like a different image is in the hero now)

**May impact:**
1. https://www.va.gov/initiatives/emergency-room-911-or-urgent-care/ (original image is 3:2 ratio)

### Design

- [Front end design in Sketch](https://sketch.com/s/b0ab7a47-11d3-4175-90c1-c54638ca9925)
- [CMS design in Figma](https://www.figma.com/file/WBMLh7tvl4FIb1ZLYFHn3h/Campaign-Landing-Pages?type=design&node-id=0%3A1&mode=design&t=nSVpeHnS5TeUo83S-1)

## Acceptance criteria Sprint 94 - 3pts

- [x] Documented the new FE and CMS designs in Figma/Sketch
- [x] Detailed the steps we would take to mitigate existing images per your audit above
- [x] Worked with PM/DM to ticket the steps for implementation and image adjustments

## Acceptance criteria Sprint 95
- [x] Gradient updated to use Homepage gradient (dark blue to lighter blue, left to right)
- [x] Ensure that character limits protect the text box from getting "too tall"
- [x] Define exactly what happens to image ratio as desktop view is narrowed toward tablet width - current version seems to get wider than 1:1 at widest width
- [x] Update help text and help image for Editors (e.g. https://prod.cms.va.gov/node/add/campaign_landing_page)
- [x] Review with Amanda K

**Comment by wesrowe** [comment]
assigned to @thejordanwood for pre-refinement.

**Comment by wesrowe** [comment]
@thejordanwood, I discussed this with Jill – this picks up where the previous ticket left off with more complete documentation. ACs include figma/sketch, and a step-by-step plan to deliver the changes without a period where existing images are whack.

**Comment by thejordanwood** [comment]
@randimays @chriskim2311 After thinking this through a bit more, I'm wondering if it's possible to design the CLP header like this. This design extends the gradient all the way to the edge on the left side and extends the image to the edge on the right side. This way we don't have an awkward white background on the edges. 

This would change the 1:1 ratio we originally suggested to a 4:3 ratio. Here's [the Sketch file](https://sketch.com/s/b0ab7a47-11d3-4175-90c1-c54638ca9925) with this design. 

<img width="800" alt="Screenshot 2023-10-04 at 5 14 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/0e9b021e-5606-45c5-b825-3aad484135a6">

**Comment by thejordanwood** [comment]
@randimays Thanks Randi! In that case, we can move forward with this design.

**Comment by thejordanwood** [comment]
@wesrowe @jilladams I've created designs for this and have determined that we should probably crop images at a 3:2 ratio instead of the 1:1 I previously stated. 

- [Front end design in Sketch](https://sketch.com/s/b0ab7a47-11d3-4175-90c1-c54638ca9925)
- [CMS design in Figma](https://www.figma.com/file/WBMLh7tvl4FIb1ZLYFHn3h/Campaign-Landing-Pages?type=design&node-id=0%3A1&mode=design&t=nSVpeHnS5TeUo83S-1)

For next steps, these are the pages with images I'll probably need to crop: 

1. https://www.va.gov/initiatives/vote/ 
2. https://www.va.gov/initiatives/end-of-life-benefits/ 
3. https://www.va.gov/initiatives/covid-flu/ 
4. https://www.va.gov/initiatives/sign-in-securely-with-logingov/ 

I'm not sure where in the development process I should do this. We can create a ticket for this work and once @randimays or @chriskim2311 get to a place where they're ready for me to crop images, then I can do that. It should only be a 2 point ticket at most and not take too much time.

**Comment by wesrowe** [comment]
@thejordanwood, I probably missed some of the discussion that led us here. However, hearing that you're stretching the image to the right for the first time here – it seems to reintroduce the very-wide-screen problem again. I.e., creating conditions where the aspect ratio on the FE could be significantly distorted from the more-typical 1:1. So I'm wondering if that's the case and how you view the tradeoff.

**Comment by thejordanwood** [comment]
@wesrowe You didn't miss anything! I came up with this alternative option while putting the designs in Sketch yesterday. 

I think the main problem with the hero image currently is that it's trying to stretch across the entire screen. This creates a narrow view port that is partially covered with text. My hope was that the new option would be better because the image isn't having to scale across the entire screen anymore, but the hero banner will still appear full width. The 1:1 ratio is going to cause some awkward spacing on the sides. 

If we still want to go with the 1:1, we can do something like this. 

I added both options into [the Sketch file](https://sketch.com/s/b0ab7a47-11d3-4175-90c1-c54638ca9925) if you'd like to compare. 

<img width="691" alt="Screenshot 2023-10-05 at 4 42 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/fd3e9b32-5a8e-4d28-8d67-f0a198f963a4">

**Comment by wesrowe** [comment]
I scheduled a meeting on 10/10 to review options and finalize next steps.

**Comment by jilladams** [comment]
10/10 meeting resulted in new ACs for SPrint 95, and Jordan has next step to review design / options with @aklausmeier

**Comment by thejordanwood** [comment]
Reviewed options with @aklausmeier. For tablet, there should be no image at vertical sizes and a 1:1 image at horizontal sizes. Please follow what the square image for VA news does [on the homepage](https://www.va.gov/).
