### ISSUE TITLE
BE: Enable Event Editors to use email as call to action

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15385]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS AN** Event Editor
**I WANT** to be able to offer an email address instead of a URL for Veteran responses (etc)
**SO THAT** I can hear from Veterans in the best way for me.

### Engineering notes / background

Design in [Figma](https://www.figma.com/file/8ZT1nnu8r2twbOlEhysnNp/Events?type=design&node-id=133-575&mode=design&t=sAtiArZmX0MbM8Ra-0).

Help text:
> Add an email address that people can contact to sign up for this event. Use a general VA email address whenever possible. Example: [contact@va.gov](mailto:contact@va.gov).

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

**NOTE: Don't merge until FE & Change Management are ready
- [x] Audit the existing URL field on Events to understand if any existing, published Events use mailto: in the field. 
- [x] When an Editor selects a CTA (e.g. Register), a new "How to sign up" dropdown appears per Figma design offering URL and Email options
- [x] If they pick URL, the existing "URL" field is displayed and is required
- [x] Validation prevents saving an email in the URL field
- [x] Validation enforces VA.gov email domain
- [x] If they pick Email, a new "Email" field is displayed and is required
- [x] Validation checks to make sure a well-formed email has been entered
- [x] When switching "How to sign up" from Email to URL, or URL to Email, we follow UX guidance for conditional logic to clear existing field entries 
- [ ] **_Email or URL is saved in BE such that it will be displayed by FE_**
  - [ ] _this needs FE implementation ticket_
- [x] Headings and help text are updated
- [x] Tests added as appropriate
- [ ] Requires PM review
- [x] Requires Design review
- [x] A11y review with Laura
- [x] PR is marked DO NOT MERGE, ticket is moved to Complete Pending Integration pipeline

**Comment by wesrowe** [comment]
Assigned to @dsasser for pre-finement (by next week).

**Comment by jilladams** [comment]
@thejordanwood can you confirm: if a user chooses "How to sign up" > Email, enters an email, then switches to URL (or vice versa) we think we should be clearing the Email value when we switch. Yes?

**Comment by thejordanwood** [comment]
@jilladams I agree that it should clear when switching.

**Comment by jilladams** [comment]
From refinement: 
* Email field: per Dave, has policy guidance that we think it should not be a personal email. Maybe 6102 policy. We need to validate that -- if so, need to update Email field helptext.
  * CAIA has looked into this as well. Reach out to them about "named user email addresses". 
  * CMS team created a 6102 mural w/ plain language explanations: https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1662643881820/ad0f6da63dba4998516450701abca6ec1944ec74?sender=u10a597890f85398daa3c4805
* We should not validate / block entry of a personal email, but should advise against it. 
* Updating help text should be a fast follow.

**Comment by thejordanwood** [comment]
> Email
> Add an email address that people can contact to sign up for this event. Use a general VA email address whenever possible. Example: contact@va.gov.

This is the recommended text for the email field. After reviewing directive 6102, we only need to suggest that a general VA email be used here. This was approved by Blake in [the Figma file](https://www.figma.com/file/8ZT1nnu8r2twbOlEhysnNp?node-id=136:3780&mode=design#597336282).

Note: contact@va.gov email address will not be a link. This is a Github styling issue that I can't fix.

**Comment by jilladams** [comment]
@dsasser one note from VHA DM: we need to enforce only va.gov as the email domain for this field. Adding to ACs.

cc @FranECross

**Comment by dsasser** [comment]
## AC: Audit the existing URL field on Events to understand if any existing, published Events use mailto: in the field.

Events using mailto: are below. There are 29 of them as of 11/14/23 @ 10:30AM
[VACMS-15385-mailto-links-query-export.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13353925/VACMS-15385-mailto-links-query-export.csv)

**Comment by dsasser** [comment]
@jilladams @FranECross
Because we are adding 2 new fields (the 'how to sign up', and the email field), and given the existence of mailto: data in the existing URL field we have a wrinkle or two.

1. What do we want to do with the events that have mailto: in them? We could migrate those mailto: addresses into the new Email field, but...
2. I need to control the visibility of the CTA field (email, URL) depending on the value of the new 'how to sign up' field: if 'how to sign up' = Email, display the new email field, if set to URL, display the existing URL field. However, what do we want to do for existing events where the value of the new 'how to sign up' field has no value? We could default the value of 'how to sign up' to URL, which would avoid any issues with existing events, but I wasn't sure if there was a hidden data migration/population not called out on the ACs for this.

**Comment by jilladams** [comment]
Firstly: Checked and all the affected events are in the past, so that's a good starting point / lower risk to make changes to them specifically.
[VACMS-15385-mailto-links-query-export.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13370475/VACMS-15385-mailto-links-query-export.csv)
![Screenshot 2023-11-15 at 2 52 03 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/0d10f4b2-7ec2-4306-9731-dcb98f8f525b)

For the rest of it, I'm gonna add to 16th min for tomorrow (11/16 Thurs) bc I think discussing will help Fran / Jordan get heads around it. Some thoughts meantime: 

* For the 29 events with mailto in the URL field today: If we default to URL, leave those events as is / don't worry about migration, would it break things, or would it just mean an Editor would have to fix it next time they try to edit the Event? (Which they prob won't ever.)
* For other existing events: if we say "An event that includes a URL today should be migrated to set "How to sign up" to `URL`", is that migration big / how does it affect effort here? It seems like a wise path if it's not a gigantic effort.

**Comment by dsasser** [comment]
## Handling of existing URL fields (16th minute decision)

Based on our discussion in 16th minute scrum today, and related to the [previous](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15385#issuecomment-1813172850) questions:

### Existing Event with URL field populated
If an existing event is populated with an registration url

- The 'how to sign up' field will be made visible
- The URL field will be made visible
- No action is required from the user to display the existing url

This will prevent necessitating a migration/population of data into the new 'how to sign up' field.

### Existing Event with a mailto: link in the URL

If an existing event includes a 'mailto:' link in the registration url field:
- The 'how to sign up' field will be made visible
- The URL field will be made visible
- Upon saving the Event, the system will generate an error message, requiring the user to change to use the new Email field, or update the mailto: to point to an URI.

Since all existing events using a mailto: email address in the URL field are past events, and we will be adding validation to prevent that, taking no further action here is little risk.

**Comment by dsasser** [comment]
## Constraint/Form error jump links

Jump links for constraint-provided errors are not working. We are using constraints to provide the validation for this ticket, but the jump links provided (by core?) are not working as expected. The jump links should be targeting element IDs related to the field with the error, but the jump link URLs do not match the element IDs. I spent about an hour trying to figure out why, but it is a deep rabbit hole, or at least not very obvious why this is occurring. This probably should be surfaced to the CMS team for further testing once this gets merged.

**Comment by dsasser** [comment]
## End of Sprint Update

The [PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16173) has been approved by [Nathan](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16173#pullrequestreview-1741975103) (code), [Laura](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16173#issuecomment-1821580076) (a11y, UX), and [Jordan](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16173#issuecomment-1821580076) (UX/Design).

The PR cannot be merged this sprint, as we also need FE work to wire in the new Email field in content-build.

**Comment by dsasser** [comment]
Verified in Prod:

![Screenshot 2023-12-20 at 10 37 37 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/fcee8d67-2f7f-4658-9d8e-42d42b9d6d6c)
