### ISSUE TITLE
Spike: Load balancing between two S3 buckets

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15402]
## Requirements

We need to verify that we can set up a load balancer that directs traffic to one or another S3 bucket according to rules, so that we know if our planned architecture for Content Build & Next Build traffic is viable.

```[tasklist]
### Acceptance criteria
- [x] A load balancer is set up that is reachable via the web or curl.
- [x] Two test S3 buckets are created or designated for testing
- [x] The load balancer directs traffic to one or the other S3 bucket based on rules.
```

## Background & implementation details

The load balancer is most likely to be an Application Load Balancer: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html

Load balancer listener documentation is here, linked specifically to path-based rules: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#path-conditions

The POC ALB & buckets should be left intact after the ticket, to use with future spike/research (particularly API manipulation of the listener rules). 

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
Updating the rules based on Next Build paths will be its own forthcoming ticket.

**Comment by timcosgrove** [comment]
This is stretch.

**Comment by tjheffner** [comment]
## Current status

here's the load balancer:
[https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#LoadBalancer:loadBalancerArn=arn[…]b/0fb54fea2014364e;tab=listeners](https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#LoadBalancer:loadBalancerArn=arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/next-build-test-lb/0fb54fea2014364e;tab=listeners)

I have a listener for a target group, and here is that target group:
[https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#TargetGroup:targetGroupArn=arn:a[…]-target-group-1/e097918c85f822d1](https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#TargetGroup:targetGroupArn=arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/next-build-test-target-group-1/e097918c85f822d1)
but i'm not able to register any targets to it... i think because of the VPC settings? or where those s3 buckets live in relation to the new vpc? honestly not really sure

here is the new vpc i created:
https://console.amazonaws-us-gov.com/vpc/home?region=us-gov-west-1#VpcDetails:VpcId=vpc-064fd7ffd55b7b0a6
the two S3 buckets in question (very basic, just some html files)
https://us-gov-west-1.console.amazonaws-us-gov.com/s3/buckets/next-build-test-bucket-1?region=us-gov-west-1&tab=objects
https://us-gov-west-1.console.amazonaws-us-gov.com/s3/buckets/next-build-test-bucket-2?region=us-gov-west-1&tab=objects


I then raised this thread in #platform-cop-devops on DSVA slack:
https://dsva.slack.com/archives/C04CYC4LMU6/p1697660589584569

Towards the end there is this note:
> just a heads up , it's a pretty big "please do not" when it comes to using IGW's. ideally all traffic traverses the TIC. it's only a suggestion before someone comes asking. all of that said, your CIDR blocks overlap with the VA's, so even if you did use the transit gateway and TIC, you'd need diff CIDR's to prevent conflict in routing


so the initial setup should be updated to not do that.

**Comment by olivereri** [comment]
Tanner did the tough stuff and I finished the configuration. Platform folks are right, use of Internet Gateways are prohibited and I believe they periodically scan from them. But this isn't hooked up to anything in production, and couldn't functionally connect with the VA network. The risk is minimal but I'll remember that a heads up to Platform crew before creating one is necessary.

I've tweaked the network settings and rule settings for the ALB and now it routes traffic based off these rules:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/31904439/afbfa438-7fe0-4f3c-870d-699c53a20fe1)

http://next-build-test-lb-341534115.us-gov-west-1.elb.amazonaws.com/index.html ALB sends requests to next-build-test-bucket-1 by **default**
http://next-build-test-lb-341534115.us-gov-west-1.elb.amazonaws.com/foo/bar.html ALB sends requests for /foo/bar.html to next-build-test-bucket-1
http://next-build-test-lb-341534115.us-gov-west-1.elb.amazonaws.com/stories/example.html ALB sends requests for /stories/example.html to next-build-test-bucket-2

Notice that the hostname **next-build-test-lb-341534115.us-gov-west-1.elb.amazonaws.com** gets redirected to either:

next-build-test-bucket-**1**.s3.us-gov-west-1.amazonaws.com
next-build-test-bucket-**2**.s3.us-gov-west-1.amazonaws.com

However, defining rules with a leading wildcard doesn't function as you'd expect. A Path condition with `*/stories/*`  and `/*/stories/*` won't catch http://next-build-test-lb-341534115.us-gov-west-1.elb.amazonaws.com/butler/stories/story.html and redirects to the default rule.

Exploring the API is next.

**Comment by olivereri** [comment]
AWS ALBs are soft limited to 100 rules. I don't know the maximum number of rules it can be increased to is. However, I think the max is far lower than the number of rules we'll need, especially when ALB rules don't support leading wildcards. An alternative to the ALB must be explored due to current technical limitations.

**Comment by tjheffner** [comment]
Closing this as we've effectively ruled out the ALB approach.

#16089 & #16090 for further investigation.
