### ISSUE TITLE
Explore creation of a Datadog dashboard for Helpdesk reporting

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15470]
## Description

A lot of user stats are copied manually from production and tediously manually sifted for reporting. Helpdesk should use the same stats that are reported to Datadog.

This might involve a decent amount of networking/communication with helpdesk to make sure that the numbers match up, or Helpdesk could pair with DevOps to perform the work.

## Acceptance Criteria

- [x] Sync with Nate has been completed.
- [x] Development of a Helpdesk dashboard that has parity with current Helpdesk figures has been explored and investigated

**Comment by BerniXiongA6** [comment]
Hi @stefaniefgray -- how many points have been completed, how many points left to complete? Will use final point count on my planning calculator, thanks!

**Comment by ndouglas** [comment]
My availability probably blocked this ticket, since I've been firefighting or vacationing all this sprint.

**Comment by BerniXiongA6** [comment]
No worries @ndouglas , we can move this issue to carry over in S96.

**Comment by stefaniefgray** [comment]
Currently blocked by waiting for permissions updates from DOTS team; have reserved time to work on this on Mon/Tues as soon as permissions are enabled

**Comment by stefaniefgray** [comment]
### Update from Friday 11/17/2023 (I posted this on Slack):

"I’m in a live chat right now with a Federal Support Engineer at DataDog and am troubleshooting how to link Jira Service Desk to DataDog to measure support ticket metrics. I’ve been trying for days, but the main issue is, in order to link Jira Service Desk as an integration, you need to be able to log into [app.datadoghq.com](http://app.datadoghq.com/). ([More info](https://docs.datadoghq.com/integrations/jira/))

However, [app.datadoghq.com](http://app.datadoghq.com/) requires a username and password combo — and with FedRamp security guidelines in place making VA DataDog access “SAML strict,” there is no way to set a password for an account that uses a PIV card for login.

On the other hand, I might be able to use the [Jira Service Desk REST API](https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/) to pull metrics into DataDog in a roundabout way. The DataDog Federal Support Engineer I’m talking to right now is looking into this on our team’s behalf, and provided some [helpful metrics documentation](https://docs.datadoghq.com/api/latest/metrics/) in the meantime. (Also, he is just an awesomely helpful person and very nice to speak with!)"

### Update from Monday 11/20/2023:

@ndouglas and I met and were able to get Jira Service Desk connected to Datadog; we were temporarily blocked by necessity of logging into app.datadoghq.com, which can't be done via VA.gov PIV single sign-on (see above notes)

Got the integration working, but are waiting to see if DataDog will allow us to load widget tools and measure Jira Service Desk metrics. May take some time for metrics to load; will have to submit test ticket to see if Event is recorded within DataDog.

**Comment by BerniXiongA6** [comment]
Hey @stefaniefgray and @ndouglas -- I think we might be OK if we modify the AC a little on this ticket to say that we've explored the options for "creating" a Datadog dashboard for Helpdesk reporting even if we haven't technically "created" a dashboard yet given the blockers mentioned above. What say you @EWashb ? cc: @maortiz-27-80

**Comment by EWashb** [comment]
That's fine with me @BerniXiongA6.

**Comment by BerniXiongA6** [comment]
The ticket title and AC has been modified since exploration of the creation of a helpdesk dashboard has been completed. Next steps are for @maortiz-27-80 and @BerniXiongA6 to create a ticket to prioritize enhancing Helpdesk Reports and Dashboards within Jira Service Management instead. cc: @EWashb

**Comment by stefaniefgray** [comment]
@BerniXiongA6 @EWashb @maortiz-27-80 
Hi all -- in place of creating a Datadog dashboard, I've created a Jira Service Desk dashboard compiling some of our stats from the past 30 days and from the past year regarding ticket counts, resolution times, SLAs, components (VAMC, Vet Center, etc.) and labels: https://va-gov.atlassian.net/jira/dashboards/10111

This dashboard is only visible to licensed users

Please let me know if this looks like a good start/substitution for the original goals of this ticket, and if there are any other stats you'd like to see. Thanks, and happy Thanksgiving!
