### ISSUE TITLE
Manchester Vet Center - Portsmouth-Newington Vet Center CAP URL change

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15524]
## User Story or Problem Statement
CAP was misnamed as Manchester Vet Center - Portsmouth-Newington Vet Center Outstation

Barb (RCS) updated the name to Manchester Vet Center - Portsmouth-Newington but the previous name is retained in the URL (manchester-vet-center-portsmouth-newington-vet-center-outstation)

The node in question is [Manchester Vet Center - Portsmouth-Newington(https://prod.cms.va.gov/manchester-vet-center/community-access-point/manchester-vet-center-portsmouth-newington-vet-center-outstation)

[Runbook link](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md)

[Vet Center link](https://prod.cms.va.gov/admin/content/bulk?title=&type=All&moderation_state=All&taxonomy_entity_index_tid_depth=796)

## Acceptance Criteria
- [x] Vet Center URL matches the updated Vet Center name.

## Team
- Facilities

**Comment by jilladams** [comment]
Talked to Christian about this one today bc the URL change was confusing. 

1. Portsmouth Vet Center Outstation -  https://prod.cms.va.gov/manchester-vet-center/portsmouth-vet-center-outstation - incorrect outstation, Editor has requested it be removed from VAST. 
2. Manchester Vet Center - Portsmouth-Newington
 - https://prod.cms.va.gov/manchester-vet-center/community-access-point/manchester-vet-center-portsmouth-newington-vet-center-outstation - Correct facility, CAP, does not have its own URL, appears in Other Locations here: https://www.va.gov/manchester-vet-center/locations/

**Sidebar:** 
Portsmouth Vet Center Outstation _also_ appears in Other Locations on the FE, even though:  it's in Draft in the CMS. This is because the FE builds Vet Center nearby locations from API data, and this will disappear when the location is removed from VAST.

**Comment by omahane** [comment]
This has now been updated in production: 
https://prod.cms.va.gov/manchester-vet-center/community-access-point/manchester-vet-center-portsmouth-newington
