### ISSUE TITLE
Review of updated KB article : How to create a CLP

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15657]
## Which article(s) need review?
Provide the link to latest revision of each article that requires review.
-  https://prod.cms.va.gov/node/27393/revisions
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [x] Deadline: TBD
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [ ] Low

## Associated KB article ticket
Provide the original ticket where the article was originally created/updated so we can refer back there for any additional context if necessary.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15384
  
## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [x] Yes, all article(s)s within this ticket can be published once reviewed
- [ ] No, the article(s) within this ticket should not be published and should only be reviewed
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [x] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [x] Article reviewed by CMS Team
- [ ] Article reviewed by Help desk
- [ ] If approved above, article is published
- [ ] Requesting person/team has been notified that article was reviewed/published

**Comment by BerniXiongA6** [comment]
<img width="653" alt="CMS suggested edits for christia" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85254824/8f7f395a-31ac-4432-99d4-9047693b6230">

Hi @chri5tia cc; @jilladams I've reviewed the content, great start! There are 3 suggested edits I have from line editing standpoint. Below I've indicated which line number to go to along with the suggested edited text you could use to replace what's drafted:

2. Ensuring IA (#sitewide-content-ia) has reviewed / approved the requested vanity URL

3. Helpdesk or Drupal admin creating a CMS user, if needed, and assigning proper permissions

5. Implementing the redirect for the vanity URL

I'll also cc: @stefaniefgray @TroyA6 to see if they have any feedback on the logic here since this concerns helpdesk instructions -- thanks!

**Comment by jilladams** [comment]
@BerniXiongA6 FYI I got redirected on the contents of this draft today, so am unassigning y'all and assigning to myself for now. We _will_ need Helpdesk review, for the next draft, timing TBD -- the deadline will move out accordingly.

One thing DaveC noted about this KB -- as it exists today, it's Admin facing. Typically, admin notes are in unpublished KBs or live in other Helpdesk documentation. So when we iterate this article, it will become Editor facing to educate them about the steps they need to take internally to request a CLP, before it gets to Drupal. Dave would like us to move / remove the Helpdesk / Admin steps, and put those somewhere else. Feel free to ignore that for now / address it when we come back with the edit ready to review, but flagging for awareness.
