### ISSUE TITLE
Search Pagination: update component to use "with middle"

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-cms#15678]
## Description
When a user gets a paginated list of items, the pagination component by default shows a previous button, 5 current pages (modifiable) and a next button. It is difficult to jump to the first or last page of results.

The design system has solved for this with the "with middle" option: https://design.va.gov/components/pagination#with-middle 
![Screenshot 2023-10-13 at 11 48 18 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/012bf9ef-684c-41de-9957-84dd6aecbfd5)

**Suboptimal Workarounds:**
* if a user has clicked past page 5 of results and wants to return to the first page, they need to press the "Prev" button numerous times, or restart the search process. 
* If the list in question uses query parameters to display the page number, a user can modify the page # to reach page 1 (or 24). However: not all listings use query params to display the page. 

![Screen Shot 2020-02-18 at 2 50 28 PM](https://user-images.githubusercontent.com/136959/74777482-2edfa180-525f-11ea-9d74-24efd836b184.png)

## Specs:

- Device: Any
- Browser: Any
- Test User: N/A

## Steps to Reproduce

1. Go to https://www.va.gov/search/?page=5&query=va
2. Now go to page 1 without modifying the URL

## Desired behavior

- Make it easier to jump to the first / last page
- Allow the user to jump to a specific page

## Future iterations the DST could consider
Not ticketed to them. Example new pagination layout

![Screen Shot 2020-02-18 at 3 11 35 PM](https://user-images.githubusercontent.com/136959/74778694-b62e1480-5261-11ea-8297-39f025da2bec.png)

## Acceptance Criteria

- [ ] Should use V3 components
- [ ] Search pagination should show the first and last page as jump options

**Comment by jilladams** [comment]
There are 2 issues here: 

## Search / results pagination that does not include the  1st / last page as jump options
So a user must click "Prev" or "Next" to reach them.
Keeping this ticket for this purpose, and updating ticket body.

Design system has solved for this, and there is now an option to enable the Pagination component using "With Middle" format -- https://design.va.gov/components/pagination#with-middle. That options provides 1st and last page as clickable options, in addition to Prev/Next, and the "middle" # of options you've defined. 

**To do:** Update Search to use this Middle declaration, rather than the current Default. 

### **Search page today:**
![Screenshot 2023-10-13 at 11 46 08 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/66a1587e-712d-4bc2-ac9d-8cfa7c0a76e4)


### **Middle option we can use instead**
![Screenshot 2023-10-13 at 11 48 18 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/bb4926c2-fbab-47b8-b6d2-75e7cef5b6ae)

## Some paginated listings do not use query parameters, and reaching specific result pages by URL does not work
Search results _are_ paginated with URL query params, e.g. https://www.va.gov/search/?page=3&query=healthcare&t=false

We can follow that implementation to do the same for listings that do _not_ work this way. Audit: 

**Public Websites:** 
* Find a form results, https://www.va.gov/find-forms/?q=10-10 - 🔴 does not use params
* Events listings (VAMC & Outreach), https://www.va.gov/outreach-and-events/events/ - 🔴 doesn't use params
* Outreach materials, https://www.va.gov/outreach-and-events/outreach-materials/#3 - 🟢 does use a form of page # in URL. Does _not_ use the pagination component, is being deprecated eventually (#14835), and we won't mess with this. 

**Facilities:** 
* Stories listings,  https://www.va.gov/minneapolis-health-care/stories/page-2/ - 🟢 uses params
* VAMC News Releases listings,  https://www.va.gov/minneapolis-health-care/news-releases/page-2/ - 🟢 uses params

Leadership & Health Services Lists don't paginate,

**Solution:**
Design system team opinion ([Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1697205692473209?thread_ts=1697152386.993119&cid=C01DBGX4P45)): 
* we can pass the current page number to the page prop of the component based on the url value (from outside the component). The component would then display based on that value. 

**Ticketed here:**

**Comment by chriskim2311** [comment]
New component is being seen on prod, Closing!

<img width="1563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFBDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f48df4f87d76ed44811c236a665c023a6d7a432/Search_Results___Veterans_Affairs.png" alt="Search_Results___Veterans_Affairs.png" />
