### ISSUE TITLE
Sync mysql config between PHP/AWS Params and my.ini settings

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1568]
This is a follow up on https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1560 to sync the MySQL settings between the different places.  This will make it more transparent about what the settings are.

Ideally, they would all be in AWS  as these don't need to be in PHP.

**Comment by oksana-c** [comment]
@ElijahLynn is this story still relevant?

**Comment by ElijahLynn** [comment]
Yes, still relevant. And some implementation notes: 

- We have config in devops:/.../terraform now (didn't used to) for the param groups, each a key=value
- We have config for Lando in CMS repo
- We have config for Tugboat in CMS repo

We can easily get Lando and Tugboat in sync, using the same file, but the Terraform RDS state will be harder because it is a different repo, and we can't have a dependency on the CMS repo for devops engineers to have to pull that in, unless maybe it is a single file fetch. At any rate, would be really nice to have these all in sync.

**Comment by TheBoatyMcBoatFace** [comment]
Not a priority. Reopen if needed.
