### ISSUE TITLE
[cms-ci] Server under constant load with no jobs running

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1579]
DevShop is showing steady load now, even with no PRs running. I see drush cron tasks running which are churning mysql processes.
We need to disable the crons, I think there is a setting in the UI.
![image](https://user-images.githubusercontent.com/1504756/80021692-c051d680-848f-11ea-8c4b-35ecab98b650.png)
![image](https://user-images.githubusercontent.com/1504756/80021701-c47df400-848f-11ea-84c8-005137f94f35.png)

**Comment by ElijahLynn** [comment]
http://devshop.cms.va.gov/admin/hosting

I think this is the setting, I am unchecking it for now:
![image](https://user-images.githubusercontent.com/1504756/80021805-f000de80-848f-11ea-87cd-c64b74b01994.png)

**Comment by ElijahLynn** [comment]
Server load is down again now, especially mysql when no processes running and the cron command isn't running anymore either. 

![image](https://user-images.githubusercontent.com/1504756/80022207-8e8d3f80-8490-11ea-97a2-0e81fb63b5ee.png)

**Comment by jonpugh** [comment]
That's a good way to turn off the cron queue completely. You can also uncheck the "Cron" queue in the admin/hosting/queues page. (won't be there now because you disabled the module.)

I think disabling cron on CI machines is a good idea. It's a source of instability, as a test run might kickoff during a cron run, or vice versa.

Some sites, like demo sites, might need cron, but there is currently no way to turn cron on and off on a per-site basis.

It would be worth looking into why the cron queue has such an impact on performance. Could be the SQL used for the hosting_cron queue. It's possible it doesn't filter out disabled sites, so as we scale the number of sites, the cron queue lookup query gets slower ans slower?

**Comment by ElijahLynn** [comment]
> That's a good way to turn off the cron queue completely. You can also uncheck the "Cron" queue in the admin/hosting/queues page. (won't be there now because you disabled the module.)
> 
> I think disabling cron on CI machines is a good idea. It's a source of instability, as a test run might kickoff during a cron run, or vice versa.
> 
> If a cron run is needed for a test, then the test should run `drush cron` or similar by itself to confirm it works.
> 
> Some sites, like demo sites, might need cron, but there is currently no way to turn cron on and off on a per-site basis.
> 
> It would be worth looking into why the cron queue has such an impact on performance. Could be the SQL used for the hosting_cron queue. It's possible it doesn't filter out disabled sites, so as we scale the number of sites, the cron queue lookup query gets slower ans slower?

Noted, thanks. The cron issue was introduced last week and is something to do with node_revision_cleanup and a very large queue table, @swirtSJW and @indytechcook are working on that now.
