### ISSUE TITLE
Spike: investigate Playwright for testing

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15925]
## Requirements

Cypress in CI for next-build currently takes 17 minutes to run 4 tests 😱 

Investigate using https://playwright.dev/ instead to see if we can reduce that time. Because that speed for Cypress is unsustainable.

```[tasklist]
### Acceptance criteria
- [ ] Time difference between Cypress & Playwright suites are noted
- [ ] Current next-build Cypress tests (`/cypress/e2e/*.cy.js`) have Playwright equivalents
- [ ] A11y tests are available in Playwright. Individual & full sitemap
- [ ] Jest tests still function as expected
```

## Background & implementation details

This can all live in a root level `playwright/` directory for the purposes of this ticket

https://playwright.dev/docs/accessibility-testing shows `@axe-core/playwright`

Playwright integration with VS Code: https://playwright.dev/docs/getting-started-vscode

Playwright & GHA: https://playwright.dev/docs/ci-intro We should be able to run Playwright tests as a GHA

**Comment by jtmst** [comment]
### Summary
After testing and configuration of Playwright, I recommend moving forward with migrating to Playwright from cypress for next-build.  Performance seems to be approximately 25% faster in local environments with our current test suite for standard e2e tests.  A11y tests are able to be performed in a similar manner on both individual tests and for the full sitemap.  Additionally the migration itself should be a light lift as the syntax for both testing frameworks are similar.

#### Test Suite Conversion
In order to test for this ticket, I migrated our existing e2e tests from cypress to playwright on a test branch. (https://github.com/department-of-veterans-affairs/next-build/tree/15925-playwright-tests)  After some config, the conversion of tests to Playwright is pretty painless. A dev experienced in writing cypress tests should be able to pick up working with playwright quickly.  

Playwright also offers a very handy test generation tool (https://playwright.dev/docs/codegen-intro) that will help teams rapidly expand test coverage in the future.

#### Accessibility Testing
Accessibility testing capabilities were explored using @axe-core/playwright.  We were able to successfully implement accessibility checks for individual pages and the full site map.  In its current state (running locally). It is taking about 27 minutes to run the a11y tests for the full site map, but this could potentially be trimmed down with more resources running in our ci/cd pipeline.


#### Jest integration
After implementing playwright tests, Jest tests continued to function as expected.  Playwright tests were isolated to ensure no interference with existing unit tests.

#### Performance
On local environments, I found our cypress test suite to average approximately 11 seconds, and the same tests in playwright to run in about 7.5 seconds.  My only concern for playwright at this time is the duration of a11y tests against the full site map (currently approx 27 minutes), but we will need to see how this performs in our CI/CD environment.

#### Next Steps
Playwright config will need to be set up for our environments, cypress tests removed, and a11y tests split into their own action.  Playwright tests will need to be added to the ci/cd pipeline via github actions, and cypress test calls should be removed from tugboat.  Issue for this work started here: https://github.com/department-of-veterans-affairs/next-build/issues/249
