### ISSUE TITLE
Create High-Level Testing Plan for Siteimprove 30-day trial pilot

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15923]
## Background 

VHA DM would like to start a 30-day trial of Siteimprove, and is requesting for the CMS Team to potentially get this into a demo environment to allow some editors to do some research with this. They're proposing a testing start date of Monday, December 4, 2023.

## Problem statement

CMS team needs to discuss what we want to test both technically and from a user experience standpoint so that we can determine our testing requirements and timeline and share that testing plan with VHA DM.

## What you need to know / Related info 
- Due to known holidays, vacations, code freezes and upcoming D10 update, December could be an ideal timeframe for testing

- For info about Siteimprove CMS integration, see epic [#10201](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10201) 
- What is CMS deeplinking: https://help.siteimprove.com/support/solutions/articles/80000448272-what-is-cms-deeplinking
- Per Nate: Should just be ~2-3 hour lead time to get something up on test.staging with environment variables, module installed, etc.
- Drupal: https://www.siteimprove.com/integrations/cms-plugin/drupal/

## Acceptance Criteria
- [ ] Timeline and requirements for testing Siteimprove has been proposed by DevOps (can we do Dec 4th realistically?)
- [ ] Timeline and requirements for testing Siteimprove has been proposed by a11y (can we do Dec 4th realistically?)
- [ ] Timeline and requirements for testing Siteimprove proposal has been shared with PO (Erika) by November 3rd 8AM ET

## To Do (not required for AC)
- [ ] once we learn more, we can create ticket/s for UX

**Comment by ndouglas** [comment]
**DevOps/QA Thoughts**: This isn't very demanding from a DevOps POV. The environment variables are already available on CMS-Test and in Tugboat. All we need to do is install the module and turn it on and deploy it.

- December 1:
  - Install and enable module in a feature branch.
  - Determine whether any issues have occurred already, and if so, fix them.
  - Open a PR in draft to have a reviewable Tugboat preview.
  - Push branch to `va.gov-cms-test` and deploy to test.staging.
  - Determine whether any issues have occurred already, and if so, fix them.
- December 4:
  - Populate environment variables in Tugboat and SSM Parameter Store.
  - Rebuild Tugboat environment. Should Just Work™
  - Redeploy test.staging environment. Should Just Work™
  - Determine whether any issues have occurred already, and if so, fix them.
  - Communicate to team and stakeholders.

💅🏻

**Comment by laflannery** [comment]
**Accessibility**
From my standpoint, there shouldn't be anything I need to do before this is turned on. After we get it working and I can start poking around I would be looking for the following:

- Does this clearly communicate where accessibility issues are within a node?
- Does this clearly communicate how to fix those accessibility issues?
- Does this provide a clear/easy/straightforward path to get from the issue to the fix (meaning is it a much more direct path than it is now, making it more likely folks will be inclined to fix these)?
- Is there any sort of prevention methods to stop errors from being created available with this integration that we could implement (not necessarily MVP)
- Does this provide any methods for scanning PDFs that have been added to either a particular node or Drupal in general?
- How does administration work? Is everything (permissions, false positives, etc.) still controlled by the main SI account or does the integration have a different set up?

I mainly want to make sure that if we go forward, we are providing editors with something useful and helpful to correct (and ideally prevent) accessibility errors, not just more noise and confusion that they aren't sure what to do with.

Regarding the timeline, I am out December 8 and December 11 I have a half day agency virtual agency meeting, but otherwise I can make this my priority as soon as we get it working.

**Comment by EWashb** [comment]
confirmed testing plan with VHA DM. They had no issues with anything listed. Blake and Justin will also see if they can get a few editors on board to test in the demo environment once it is on. A few follow ups:

- @JunTaoLuo @ndouglas is there any concern that a VAMC editor wouldn't be able to access the Tugboat? (I assume no)
- I am in contact with the Siteimprove account manager, Andrew Urness, and they have said of the 30-day trial- "we would turn it on and you would then download it in the integrations menu. Also, the 30 day trial would begin once it is turned on".
- @joagnitti if we are able to get a couple of editors on board to test in the environment, can we create some sort of doc or checklist where they can document their reactions/feedback in the system on an async basis? I foresee a log that allows them to track in a way but gives structure as well. 
- Testers would include, our UX and accessibility folks as well as Blake Scates, Justin Warren, and potentially a couple of trusted/seasoned editors.
cc: @BerniXiongA6

**Comment by ndouglas** [comment]
@EWashb Figure we'll deploy it to Tugboat and test.staging.cms.va.gov both. The latter should be usable via PIV. Tugboat's easier to iterate on if we have quick changes we wanna make (e.g. config changes).

**Comment by joagnitti** [comment]
@EWashb I can help create that note doc!

**Comment by EWashb** [comment]
@joagnitti thank you! Whatever doc will just need to be in an accessible format on the VPN so possibly an excel sheet or other Office-based product. We will need to create a separate ticket for that work as well.

**Comment by BerniXiongA6** [comment]
Hi @EWashb I'm closing this ticket since the initial testing plan has been sorted out.

**Comment by BerniXiongA6** [comment]
cc: @maortiz-27-80
