### ISSUE TITLE
Design error and empty states for Facility Locator 

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#15935]
## Description

Error states should be designed for Facility Locator to show intended behavior. According to [#14993](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14993), the primary error states needed are:

**Error/Empty states:**

- Browser isn't allowed to use location and the "Use my location" button is selected
- No location is entered
- Invalid location is entered
- No facility type is selected
- No service type is entered (if required)
- Invalid service type is entered (if required)
- No results are found for the specified service and location
     - This messaging will need to be different on mobile, where map and list views are in separate tabs.
- Map needs to zoom in to search
- Map doesn't display results (system error)
- List doesn't display results (system error)

So current error states are documented on the [Facility Locator error states page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/engineering/error_states.md). 

### Design

Error/Empty states page in the [Facility Locator Figma file](https://www.figma.com/file/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?type=design&t=FDwcjWSz9mOOeI2y-6)

## Sprint 104 Acceptance criteria

- [x] Error messages / intended behavior are shown in design file

## Sprint 105 Acceptance criteria
- [x] Review with accessibility
- [x] Review with engineers
- [x] Review with UX/UI lead
- [x] Review with PM/PO
- [x] Update #17388 with any notes needed for CAIAI review

**Comment by thejordanwood** [comment]
@xiongjaneg I had a request come in a few weeks ago on a FE ticket (#14933) to design error states for Facility Locator. I've been unable to prioritize this request, and wanted to create this ticket so it doesn't get lost. 

This may be a blocker for part of the work on that FE ticket. I'll need to do this one sprint ahead of that ticket getting pulled in.

**Comment by jilladams** [comment]
Thread re: leaving this ticket til Sprint 102, updated points to 5, and hope to move the file to Figma beforehand: https://dsva.slack.com/archives/C0FQSS30V/p1705511358426309. (FYI @xiongjaneg )

**Comment by mmiddaugh** [comment]
@thejordanwood @aklausmeier @xiongjaneg if this issue is pulled in to support design for the mobile map iteration/testing prototype, we really only need a more elegant response for searches which do not return results for the specified service and location. But you may want to review this [error state documentation in Github product folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/engineering/error_states.md) to see what else might ne needed. (Note this was last updated in 1/2022 and likely is incomplete or outdated). 
- Additional error states will be needed to support new search functionality (such as situations in which the search terms do not match keywords in the service taxonomy) as mentioned in [#14993](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14993) but it may make sense to move those into a separate issue which can be pulled in at that time. 

The "no results" scenario isn't actually an error state - the system is working correctly and the user has completed all fields. But the message currently displayed is quite lengthy and may not serve Veterans well, especially those using a screen reader. See the details mentioned in [#13919 Revisit Facility Locator "no results" error message](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13919). We may want to consider what guidance to provide based on the list vs map view (if we're able to display a different message for each). 

You can experience this sort of no results scenario in a variety of ways, including
- [Location = almost anything + Facility type = `Community providers` + Service type = `Poetry therapist`](https://www.va.gov/find-locations/?page=1&address=denver%2C%20colorado&facilityType=provider&serviceType=102X00000X&latitude=39.739236&longitude=-104.984862&radius=33&bounds%5B%5D=-105.734862&bounds%5B%5D=38.989236&bounds%5B%5D=-104.234862&bounds%5B%5D=40.489236&context=Denver%2C%20Colorado%2C%20United%20States)
   - there is almost no way to resolve this scenario - poetry therapy is an extremely rare service type
- [Location = `Polson, MT` + Facility type = `VA benefits` + Service type = `Burial claim help`](https://www.va.gov/find-locations/?page=1&address=polson%2C%20mt&facilityType=benefits&serviceType=BurialClaimAssistance&latitude=47.69053&longitude=-114.163761&radius=33&bounds%5B%5D=-114.913761&bounds%5B%5D=46.94053&bounds%5B%5D=-113.413761&bounds%5B%5D=48.44053&context=Polson%2C%20Montana%2C%20United%20States)
   - in this case, changing the Service type to `All VA benefit services` returns a search result
- [Location =`"Washington"` + Facility type = `VA benefits` + Service type = `All VA benefit services`](https://www.va.gov/find-locations/?page=1&address=washington&facilityType=benefits&serviceType&latitude=48.0250054263449&longitude=-120.094292506456&radius=443&bounds%5B%5D=-121.494292506456&bounds%5B%5D=46.6250054263449&bounds%5B%5D=-118.694292506456&bounds%5B%5D=49.425005426344896&context=Washington%2C%20United%20States)
   - in this case, changing the Facility type to `VA health` returns a search result but really, I shouldn't be able to enter just a state so we may need to work with the engineers to see what options we have for enforcing the appropriate entry. 

---

We may be able to close [#13919 Revisit Facility Locator "no results" error message](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13919) as a result of the work done for this one.

**Comment by aklausmeier** [comment]
@thejordanwood Renamed ticket to include empty states (no results)

**Comment by mmiddaugh** [comment]
Engineering questions for future discussion

- How does the Facility Locator define a valid location? (What is accepted/expected?)
- Can error messages be tailored to the type of facility/service?
- For which types of "problems" can we show the "We've run into a problem"...message?
- Will error messages be announced by the screenreader as displayed? Or is a different behavior expected? (This one might be for Laura)
- Timing for display of error messages/wait to validate

**Comment by thejordanwood** [comment]
@laflannery Can you review this? Michelle also has a question in the comment above about how error messages work. 

> Will error messages be announced by the screenreader as displayed? Or is a different behavior expected? (This one might be for Laura)

**Comment by thejordanwood** [comment]
@maxx1128 @eselkin Can you review the updates to the error states I'm proposing? They can be found on the Error/Empty states page in the [Facility Locator Figma file](https://www.figma.com/file/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?type=design&t=FDwcjWSz9mOOeI2y-6). Some questions we have in a comment above are:

> - How does the Facility Locator define a valid location? (What is accepted/expected?)
> - Can error messages be tailored to the type of facility/service?
> - Timing for display of error messages/wait to validate

If any of this in confusing (I know that Figma page has a lot of content), then I can set up a meeting for us to discuss!

**Comment by aklausmeier** [comment]
@thejordanwood reviewed and added comments to Figma

**Comment by laflannery** [comment]
@thejordanwood I looked at the disabled button and added my comments in Figma. Regarding [the question](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15935#issuecomment-1971903567) from @mmiddaugh above, the error message should be read exactly as they are displayed visually. A screen reader will immediately hear the error once it appears and then we should make sure to handle the focus so that their next tab stop is into that incorrect field so they can easily fix their mistake.

**Comment by thejordanwood** [comment]
I'm taking info from some comments in Figma to answer these questions:

> How does the Facility Locator define a valid location? (What is accepted/expected?)

This is defined by Mapbox and we're not sure if we get that level of feedback. We may need to stick with the "For better results" message.

> Can error messages be tailored to the type of facility/service?

This is probably possible. I'm going to move forward with suggesting different error messages for when no service type is entered and when an invalid service type is entered. 


@maxx1128 @eselkin Feel free to add any additional information I may have missed.

**Comment by thejordanwood** [comment]
@xiongjaneg I've updated the CAIA review ticket with the suggested error/empty states messaging. We've also reviewed this in UX sync, so I believe everyone has had a chance to see this. 

I think next steps are CAIA review, making any additional design updates after that, then handing this off to engineering and addressing anything that comes from that.

**Comment by jilladams** [comment]
@thejordanwood from [#98598](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98598#issuecomment-2551348510) we got CAIA feedback on error states, in this Google doc; https://docs.google.com/document/d/1zRbvGpmShiFnkJfP9Eo8gUnTE0-08C17MM5CPQEaWx8/edit?tab=t.0#heading=h.lyudg63kzow1.  Are these copy updates possible to roll into one of your existing FL tickets in this sprint (#18960 or #19916) or would you like a separate ticket to update them?

**Comment by thejordanwood** [comment]
@jilladams Let's do a separate ticket and I can get to it next sprint.
