### ISSUE TITLE
Initial design for VA Health Chat on VAMC pages

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16008]
## Description or Additional Context 
This is a placeholder for the initial designs for VA Health Chat on VAMC pages.

Consider: how to show Health Chat at all relevant touch points.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by mmiddaugh** [comment]
Because we are moving forward with initial recommendations (see [this comment](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/68030#issuecomment-1771817287) in the CAIA request #68030, it may make sense to take the design thinking in a different direction.

**Comment by mmiddaugh** [comment]
Closing this in favor of Design: Add VA health connect and VA health chat to VAMC page #17308
