### ISSUE TITLE
VAMC Service Location audit view

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16152]
## User Story or Problem Statement
As a Facilities Team member, I need a way to see how many service locations each ~VAMC~  service has.

## Acceptance Criteria
- [x] A View created under the content audit tab
- [x] Each node's row shows a count of service location.
- [x] exposed filter showing appropriate content types: VAMC facility health service, VAMC facility non-clinical service, VBA facility service
- [x] exposed filter  moderation state (multiple workflows)
- [x] exposed filter for section 
- [x] Has a column for VA service taxonomy term name label
- [x] Follows [Views style guide](https://prod.cms.va.gov/admin/structure/cm_document/note/124/views-style-guide). 
- [x] Has a matching CSV export
- [ ] Requires accessibility review

**Comment by swirtSJW** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/16152?planning-poker) with Zenhub @omahane

**Comment by omahane** [comment]
@xiongjaneg @jilladams It turns out that we can't both "Use aggregation" and show "Moderation state" field values in the same view: https://www.drupal.org/project/drupal/issues/3135409

Our options are to 
1. proceed without the moderation state field in the view (though it still works in the filter)
2. test the patch that's been proposed (though the reviewer is skeptical that it fixes the issue)
3. remove the moderation state filter, too.

I propose 1, as this view is still usable without the moderation state being in the output. 
(cc: @swirtSJW )

**Comment by omahane** [comment]
@xiongjaneg @jilladams 
So . . . I actually applied the patch and it worked. But then I found this view that we already had:
<img width="1840" alt="Screenshot 2023-12-04 at 11 57 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/5f799234-65de-432a-adcf-f1804280db3c">
- https://prod.cms.va.gov/admin/content/facilities/vamc-facility-health-services


A couple changes to it, though, should meet the requirements:
![Screenshot 2023-12-04 at 11 54 48 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/93568af2-8ee1-4b96-ac97-6b3d10dd4119)
- https://pr16301-r16rx5vxpijx3tsoifnbyzz6ocipmbfm.ci.cms.va.gov/admin/content/facilities/vamc-facility-health-services

Also, this view will need to be changed when we change Service Locations for VAMC, anyway, but we could use it as is right now.

(cc: @swirtSJW )

**Comment by swirtSJW** [comment]
This was merged.  Will not likely land on prod until tomorrow.

**Comment by jilladams** [comment]
@omahane a11y review is listed as an AC, but I don't see Laura on PR or here. Did you already review with her?

**Comment by jilladams** [comment]
Because Christian's offline for the day, and this has shipped and is now in prod, https://prod.cms.va.gov/admin/content/audit/facility-services, I'm going to resolve this as closed, and have requested @laflannery 's review in a new ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16509

FYI @xiongjaneg
