### ISSUE TITLE
Hide unneeded elements from JSON:API response for event and event_listing nodes

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16190]
## Requirements

We want to hide unneeded elements of the JSON:API response for node elements, so that our response sizes are both smaller and less confusing to developers.

```[tasklist]
### Acceptance criteria
- [ ] event and event_listing responses do not contain the data identified below
- [ ] changes are delivered as json_api_extras config
```

## Background & implementation details

For `news_story` and `story_listing` nodes, a number of pieces of data are hidden from the response. This same set should be hidden from `event` and `event_listing` nodes.

We currently use JSON:API Extras to modify our JSON:API response. Configuration for resource overrides can be found in the local development environment at https://va-gov-cms.ddev.site/admin/config/services/jsonapi/resource_types

The follow items should be excluded from the response:
```
* vid
* revision_timestamp
* revision_uid
* revision_log
* uid
* promote
* sticky
* default_langcode
* revision_default
* revision_translation_affected
* menu_link
* content_translation_source
* content_translation_outdate
* field_last_saved_by_an_editor
```

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by alexfinnarn** [comment]
I could export the configuration for those event and event_listing resource/node types or do a dynamic exclude. 

The config export is known and just need to check the boxes, export the config, and update any related tests. 

For dynamically excluding fields, I found this module which adds a decorator to the resource type responses: https://git.drupalcode.org/project/jsonapi_bulk_exclude/-/blob/1.0.x/src/ResourceType/BulkExcludeFilteredResourceTypeRepository.php?ref_type=heads It's such a small amount of code, I think it should go into a custom module vs. dealing with a seemingly abandoned module without security coverage. 

There are some cons to the dynamic exclusion approach:

1. Performance - Dynamically excluding fields can cost in performance since a layer of Drupal caching will be removed vs. the config export route. A higher level of caching might mitigate the impact, but it is something to consider.
2. Confusion/Maintenance - We will have to remember that the resource override UI doesn't fully control disabling fields in the response. I can modify the form to let people know that, but it does deviate from that UI as it is now. 

If the node types are fairly stable, I’d recommend keeping config exports if performance is the main concern since dynamically excluding the fields can cost in performance, even if only slightly. If the node configurations are static, then it’s only one export. 

Questions to ask/answer:

1. How many resources on https://va-gov-cms.ddev.site/admin/config/services/jsonapi/resource_types will need overrides? If some only need fields excluded, then it points more toward dynamic, global excludes. But if they will all get overrides eventually, then dynamically excluding makes less sense to me.

**Comment by alexfinnarn** [comment]
Another way to go about this would be from the client side by only requesting the fields needed to build the page: https://github.com/d34dman/drupal-jsonapi-params#addfields

I'm still not sure how many consumers va.gov-cms has, but limiting the JSON:API output could affect anyone who wants this data. Would it be better to do this in the next-build side of things? 

If the query definition won't need to change often, I think the best solution is to do this during the fetch rather than altering Drupal configuration.

Pros:
- Hides unneeded fields and fulfills the ticket requirements
- Keeps caching at the request level instead of trying anything dynamic with Drupal/PHP code
- Other consumers can use JSON:API without these configuration restrictions
- Any other request customization can be done with query parameters vs. altering Drupal configuration...I think this means less time since next-build is owned by VA team?
- Requests are more explicit about the data they need

Cons:
- Any request where you want to limit fields needs to have them specified in the request vs. the server limiting fields for you

References:
- Drupal blog post - https://atendesigngroup.com/articles/json-api-getting-just-data-you-need-sparse-fieldsets
- JSON:API sparse fieldsets - https://jsonapi.org/format/#fetching-sparse-fieldsets

So, I can think of more pros than cons to switch the field inclusion/exclusion to next-drupal vs. va.gov-cms, but I wonder what others thing?

**Comment by alexfinnarn** [comment]
Thanks for the insights @tjheffner! After reading your comments and thinking more I'm going with the simplest solution of configuration exports since its the most straightforward and maintainable with no custom code. We would have to remember the custom code, and it could impact performance with caching.

So, I created a draft PR with a functional test for the field exclusions. I'm not sure how close or off the PR is in regards to standards nor do I know if it will run the tests on a draft PR.
