### ISSUE TITLE
Facility Locator broken links in results to urgent care and emergency care benefits

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16195]
## User Story or Problem Statement
There are broken links on Facility Locator results for urgent care and emergency care.

For urgent care, there's link text to "Learn about your in-network urgent care benefits" that appears on every urgent care search result that is a broken link that used to go to https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent_Care.asp

For emergency care, there's link text to "Learn about your in-network emergency care benefits" that appears on every emergency care search result that is a broken link that used to go to
https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency_Care.asp

New links (not automatically redirected) replaced the underscore with a hyphen and that's why they're broken:
https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent-Care.asp
https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency-Care.asp

## Steps to replicate

1. Go to https://www.va.gov/find-locations
2. In "City, state or postal code" enter 55101
3. In "Facility type" choose Urgent care.
4. Click "Search."
5. Under the first result, click "Learn about your in-network urgent care benefits"
6. Get a "Sorry — we can’t find that page" message.

<img width="1025" alt="Screenshot 2023-11-22 at 12 15 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/5d01f977-41e7-4585-93fb-16c510bceda0">
<img width="1152" alt="Screenshot 2023-11-22 at 12 16 18 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/b4f38935-e8ab-46ac-b8c1-9da6b796c3c4">

## Acceptance Criteria
- [ ] "Learn about your in-network urgent care benefits" links to https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent-Care.asp
- [ ] "Learn about your in-network emergency care benefits" links to https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency-Care.asp

**Comment by maxx1128** [comment]
It looks like the links use a dash instead of an underscore in the final parts of the links, such as `Urgent_Care.asp` instead of `Urgent-Care.asp`. These links are hard-coded in three places in the `vets-website` repo (see below) and would need to be changed in these places. I would put this at **1 point.**

* `src/applications/facility-locator/components/search-results-items/UrgentCareResult.jsx`
* `src/applications/facility-locator/containers/UrgentCareAlert.jsx`
* `src/applications/facility-locator/components/search-results-items/EmergencyCareResult.jsx`

The weird thing is that those links haven't been updated in the codebase for 2-3 years 🤔 is this a new bug or one that's somehow gone unnoticed? Or has the URL structure changed on the `https://www.va.gov/COMMUNITYCARE/` side?

**Comment by xiongjaneg** [comment]
Community Care must have changed their URL from an underscore to a dash. When this happened is uncertain though could probably be determined by waybackmachine. It was reported [in this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1700672859600919)

**Comment by xiongjaneg** [comment]
Just for kicks, I checked waybackmachine and the old link was working as of Nov. 4, so this change happened early this month.

**Comment by xiongjaneg** [comment]
Confirmed both urgent care and emergency care links are working in Facility Locator results
