### ISSUE TITLE
Add system dependencies to next-build managed AMI

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#16240]
## Requirements

the playwright GHA workflow in next-build fails due to missing system dependencies. We want to install them into an AMI without effecting the base AMI for other teams in production.

This is a follow-on to the initial Playwright tickets #15925 + #16172 

```[tasklist]
### Acceptance criteria
- [x] System dependencies for Playwright can be installed & the Playwright GHA workflow runs successfully
```

## Background & implementation details

Slack threads for context:
https://dsva.slack.com/archives/C01SR56755H/p1701128585606099
https://dsva.slack.com/archives/C04CYC4LMU6/p1701202536707919

**Comment by olivereri** [comment]
This required a significant amount of work much of it is documented in DSVA Slack.  A quick summary however:

- Platform provided GHA Self-hosted runner automation isn't flexible for custom packages
  - Solution: Fork the image creation workflows and Packer configs and run them in the next-build repository
  - Todo: 
    - Fix Launch template updates
    - Remove Next-build from DevOps repo automation
- The entire Playwright workflow depends on versions of Node that will not use TLS unsafe renegotiation. VA networking devices do NOT support safe TLS renegotiation,
  - Solution: Cache dependencies in the next-build repository for offline install, otherwise avoid Node fetches and perform downloads so that they'll use the system's UnsafeLegacyRenegotiation openssl configuration. 

https://dsva.slack.com/archives/C01SR56755H/p1701821999818269
https://dsva.slack.com/archives/C01SR56755H/p1701795703847379
https://dsva.slack.com/archives/C01SR56755H/p1701730550664439
https://dsva.slack.com/archives/C01SR56755H/p1701376017432539
https://dsva.slack.com/archives/C01SR56755H/p1701128585606099
