### ISSUE TITLE
SPIKE: Front end discovery about component testing for VBA

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16243]
## User Story or Problem Statement
As a front end engineer, I need to know how we use mock data to create a test for VBA components.

## Acceptance Criteria
- [x] One set of mock data for a VBA component has been generated.
- [x] One test of mock data for a VBA component has been done.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by eselkin** [comment]
We can do testing similar to how testing is done in VBA Banner unit tests (https://github.com/department-of-veterans-affairs/content-build/pull/1849) using mock data and the renderHTML function. This does not bring in all React components, but for most components it functions well. You can even test shadow DOM component contents, despite the version of react-testing/dom not being able to access shadowRoot. 

We might consider updating the testing library to one that uses JSDOM so we can check shadow DOM directly, rather than relying on hard coding data-testids and finding them directly. 

**Why does the shadow DOM stuff matter?** All the VA Design system components render using shadow DOM. Why? This makes it so things like extensions in chrome don't alter the components and so styling for the components doesn't affect other pieces of the page.

**Comment by eselkin** [comment]
Turns out we can't really update any of the components without a huge overhaul of the content-build testing ecosystem. It's stuck back in packages from 2020 or earlier that don't allow for rendering with the elements in shadow DOM.

**Comment by xiongjaneg** [comment]
All VA design system uses shadow roots and we can't test certain things with shadow roots. We can still use data test IDs to find things that should be findable in the page. We should be able to get some of the data in the pages that can be testable.

**Comment by xiongjaneg** [comment]
Working on the banner test, Eli wrote a test that can be used for the other VBA components that brings in mock data and allows us to render the component and check that the different versions of the mock data we're using render correctly in the page.

**Comment by xiongjaneg** [comment]
Eli is waiting on banner test PR to be reviewed and then will close the last AC.
