### ISSUE TITLE
Next Build Tugboat preview servers need files from vets-website build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16288]
## Requirements

When using a Next Build preview server on a Tugboat instance, we want vets-website files to be built, so that when viewing the preview all parts of the page work correctly.

```[tasklist]
### Acceptance criteria
- [ ] When previewing on Tugboat, any vets-website 'generated' file referenced by the preview page does not 404
```

## Background & implementation details

For now, build vets-website `main` branch on Tugboat, and do not intertwine or rely on content-build's use of vets-website here.

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
vets-website download and build is currently dependent on content-build.

We build faster, so we get not found until content-build provides them.

Could we do this earlier as part of the base-preview?
Should we checkout and install and build to the same location and avoid double checkout/build?

**Comment by tjheffner** [comment]
Switching to simply start the dev server instead of `yarn build:preview && yarn start`, the assets built by content build do eventually make themselves present to the dev server. However, fonts are missing still, so the time-to-load a page is still rather long as it continually attempts to fetch them (6x, per next-build retries).

I am now attempting to build vets-website separately first and include the assets for the initial `yarn build:preview`. We'll see if that sets all necessary assets, fonts included, into the correct location. 🤞

**Comment by tjheffner** [comment]
Building & symlinking separately, instead of sourcing assets from the vets-website pulled in via content-build, has no issues and the assets appear immediately present.
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16340
