### ISSUE TITLE
CMS Editors should not see error messages due to CMS Preview secrets expiring

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16289]
## Requirements

We want CMS Editors to always be able to see their preview pages without error, so that they do not become confused and lose trust in the preview system.

```[tasklist]
### Acceptance criteria
- [ ] CMS Editors do not get an error message even after an arbitrary amount of time
- [ ] If there is a secrets-related error, a useful message is displayed indicating to try reload
```

## Background & implementation details

Preview secret expiration time is a Next.js 'site' setting: 
![Image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/203623/25b9c26d-512a-492a-b671-3399659197d3)

If a preview link is generated, and the editor then clicks through that link after the expiration time, they will receive an error.

Ideally this would never happen. Things to consider:

- What are the dangers of making the expiration time arbitrarily long?
- The initial solution is 'reload the page'. Can we force a reload if the response is this specific error?
- Is a secret required for ALL preview, or only for draft preview? 
- Can non-CMS users preview draft content, given a particular URL?
- 

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
Questions:
* do we need a secret at all, given that the preview servers are internal-only?
* Can we simply extend the time to say 1-2 days?
* Can we handle the non-technical-stakeholder-views-draft-of-page scenario (probably not MVP)

**Comment by tjheffner** [comment]
both the `drupal/next` module & the `next-drupal` npm package require a secret for using preview mode. possibly an area to contribute back to make that optional.

lowest lift - extend the secret expiration from 5 minutes to 1 day. would need to test how this behaves when a deploy happens. whether via the daily deploy or a tugboat server re-deploying.

alternatively, may be able to update the preview button to generate a new secret upon click, rather than pageload. this may make sharing preview links more challenging (would likely have to share the link to the drupal node view instead)
