### ISSUE TITLE
Playwright tests run in CI

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16304]
## Requirements

We want Playwright tests to run in CI so that we can use the tests as a code quality marker and prevent new code from breaking existing functionality.

```[tasklist]
### Acceptance criteria
- [x] Playwright is able to be run on a self-hosted runner via Github Actions
```

## Background & implementation details

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
This is only if #16240 does not fully get Playwright running on CI.

**Comment by olivereri** [comment]
This required a significant amount of work much of it is documented in DSVA Slack.  A quick summary however:

- Platform provided GHA Self-hosted runner automation isn't flexible for custom packages
  - Solution: Fork the image creation workflows and Packer configs and run them in the next-build repository
  - Todo: 
    - Fix Launch template updates
    - Remove Next-build from DevOps repo automation
- The entire Playwright workflow depends on versions of Node that will not use TLS unsafe renegotiation. VA networking devices do NOT support safe TLS renegotiation,
  - Solution: Cache dependencies in the next-build repository for offline install, otherwise avoid Node fetches and perform downloads so that they'll use the system's UnsafeLegacyRenegotiation openssl configuration. 

https://dsva.slack.com/archives/C01SR56755H/p1701821999818269
https://dsva.slack.com/archives/C01SR56755H/p1701795703847379
https://dsva.slack.com/archives/C01SR56755H/p1701730550664439
https://dsva.slack.com/archives/C01SR56755H/p1701376017432539
https://dsva.slack.com/archives/C01SR56755H/p1701128585606099
