### ISSUE TITLE
/files/ appearing on FE of published stories 

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16376]
## Describe the defect
There have been at least two (2) instances reported from the Help Desk where editors have published a Story and on the front end, `/files/`, appears randomly. ` /files/` does not show in the Preview for editors.  See filename: files_front_end_bug.png

## To Reproduce
1. Go to 'https://www.va.gov/salt-lake-city-health-care/programs/telehealth-services/'
2. Scroll down to 'VA Video Connect (VVC).'
3. Click on the '+' to expand
4. See error <img width="711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFpOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ff50111d4eb00dc06708cb52dae552746bb2ab8/image.png" alt="image.png" />

## AC / Expected behavior
When publishing a story, the text, `/files/`, should not appear on the front-end.  

 ## Additional context
Notes per Steve Wirt: 
- this is nearly identical to the problem we saw before.  It was not a FE JS error then because the `/files/` was visible in the data object. 
- What they do have in common is a link to a pdf file on another Drupal based site. 
- This may be something that needs to be fixed in the content-build. 
- [Slack thread #1](https://dsva.slack.com/archives/CDHBKAL9W/p1698177367617469)
- [Slack thread #2](https://dsva.slack.com/archives/C02730UEZPS/p1701729957077479)

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

<img width="752" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe1ff22ebed34727104b690efa66045101d49b24/files_front_end_bug.png" alt="files_front_end_bug.png" />

cc: @BerniXiongA6 @ndouglas @EWashb @TroyA6 @stefaniefgray

**Comment by TroyA6** [comment]
@xiongjaneg @BerniXiongA6 @stefaniefgray @maortiz-27-80 - There was a work-around at one point: totally deleting the text in the accordion, then recreating that text from scratch. I tried that in this case, and it did not work.

**Comment by swirtSJW** [comment]
My hunch, but unproven at this time:
In both examples so far, there has been a link to a file on another drupal system.   A different domain but still matching the traditiional drupal file paths.
There is code on the FE that rewrites paths in the VA cms file system to make them match where files are moved to the content build.  
The [code is here](https://github.com/department-of-veterans-affairs/content-build/blob/f898e20d02cbf011e6e26976de95c5d33eace1c0/src/site/filters/liquid.js#L145-L169)   I suspect the code is somehow misfiring on drupal paths that are not VA CMS and somehow we are ending up with an extraneous `/files/' hanging being injected in the wrong location for the wrong reason.

**Comment by ndouglas** [comment]
I have a different proposed culprit:

In `assets.js` we have this:

![Screenshot 2023-12-12 at 8 29 18 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/eafcb000-931d-41be-b3a3-c46679a87e7b)

I think this is the root cause: `data.match(/^.*\/sites\/.*\/files\//)`.

That will match _literally any string that contains `/sites/` and later contains `/files/`, then pass it off to `convertAssetPath()`.

For instance:

![Screenshot 2023-12-12 at 8 36 11 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/b870629d-fcec-449a-aa1f-228ef3ab9b34)

`convertAssetPath()` looks like this:

![Screenshot 2023-12-12 at 8 31 57 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/c6d7d5bf-b1e9-43fc-bb0c-38a0dfabadd8)

It will first attempt to replace the beginning of the text (if it begins with `http` etc) with nothing, then return that. It won't find it in the example above. Then it'll check to see if the string begins with `http`... still doesn't. Then it splits by a question mark, and if that ends with a file extension, returns a different path -- which it normally won't.

Otherwise, it returns `/file/${path}`, and `path` may not be defined here, so we'd see `/path/`.

So, I think the solution is to un@#$% that first regex.

**Comment by ndouglas** [comment]
I think `#^https?://([a-z0-9]+(-[a-z0-9]+)*\.)+cms\.va\.gov/sites/[\w-]+/files/#` would work (similar to the regex in `convertAssetPath()`, but setting a different delimiter so we can remove the annoying backslashes, and replacing a scary greedy wildcard). That should match anything that looks like a `cms.va.gov` URL at the beginning but allow normal text to pass through without mutilation.

**Comment by ndouglas** [comment]
Apparently it was tighter, but the change was reverted: https://github.com/department-of-veterans-affairs/content-build/pull/332 so I'm going to loosen up my pattern a bit.

**Comment by ndouglas** [comment]
![Screenshot 2023-12-12 at 9 15 42 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/0c3ae776-fc2b-4a7c-9950-625f97ae5786)

One problem, I think, is that if we do something like this:

```html
Here is a <a href="https://prod.cms.va.gov/sites/default/files/pdf.pdf">link to a PDF</a>.
```

Then I think we expect that inner link to be replaced. Or perhaps that's being replaced in that code you mentioned, @swirtSJW , which would mean that this here Should Just Work™?

**Comment by ndouglas** [comment]
![Screenshot 2023-12-12 at 9 20 54 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/df4831e3-ab27-4313-ab75-71f8b7454fd4)

Made the regex easier to read. It doesn't really matter if it's a valid domain name... that's not really our problem.

**Comment by ndouglas** [comment]
Relevant discussions:

https://dsva.slack.com/archives/C0MQ281DJ/p1625685915353300

https://dsva.slack.com/archives/C0MQ281DJ/p1625694464385700

It looks like a change was reverted, but then the underlying issue was never actually resolved. We _don't_ want to reference other Drupals' files with relative paths, which is why I was confused. So I'm going to re-tighten my regex.

**Comment by ndouglas** [comment]
![Screenshot 2023-12-12 at 9 32 40 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/d5db4734-5d10-45e3-99a8-9b91cc3edd8d)

**Comment by TroyA6** [comment]
If this helps @maortiz-27-80 and @ndouglas  @stefaniefgray @BerniXiongA6  - The following link breaks the Accordion functionality: 
https://connectedcare.va.gov/sites/default/files/2023-01/OT_va-telehealth-va-video-connect-feature-fact-sheet.pdf

There is a different link to a different PDF that seems to work: 
https://www.va.gov/files/2023-10/VVC%20Appointments_SLC_Brochure_DIGITAL508_Reader%20Extended_JD_20230928.pdf 

The difference that I see is the location of the file (connectedcare.va.gov vs. www.va.gov/files)
Both links are working links outside of the accordion --
