### ISSUE TITLE
Metatag updates

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16382]
## Requirements

In [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16382) we did much of the work of implementing Metatags. We should implement pieces of the Metatag system that were not previously implemented, so that our implementation is complete.

```[tasklist]
### Acceptance criteria
- [x] Default metatags are implemented
- [x] `field_last_saved_by_an_editor` added back to JSON:API response for our active content types
- [x] lastUpdated is implemented
- [x] implement iOS banners
- [x] TODO comments are removed for these and for `article:tag`
```

## Background & implementation details

- `article:tag` is not observed by most search engines or by metadata rendering mechanism (search results, embeds, etc); it can be removed. 
- Default metatags should be implemented (this is fallback; not everything has metatag information. See https://github.com/department-of-veterans-affairs/content-build/blob/f898e20d02cbf011e6e26976de95c5d33eace1c0/src/site/includes/metatags.drupal.liquid#L88-L146
- Implement `lastUpdated` (this can be pulled from `field_last_saved_by_an_editor` or else from `changed` if that field is not avaliable)
- showIOSBanner should be implemented as a code-based manual lookup table for routes, as it is in Content Build. This can be tested by temporarily adding routes that Next Build currently builds. See https://github.com/department-of-veterans-affairs/content-build/blob/f898e20d02cbf011e6e26976de95c5d33eace1c0/src/site/filters/liquid.js#L1741-L1756 

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by alexfinnarn** [comment]
The only thing not really resolved in the list of acceptance criteria are the default metatags listed in content build: https://github.com/department-of-veterans-affairs/content-build/blob/f898e20d02cbf011e6e26976de95c5d33eace1c0/src/site/includes/metatags.drupal.liquid#L88-L146

We discussed this during a standup, and it was determined that metatags like "keywords" should always come from the CMS. Furthermore, we discussed how the Metatag module provides defaults that are inherited on "/admin/config/search/metatag". For example, all event nodes get "Global -> Content -> Content: Event" defaults applied even before an editor adds custom metatags per individual event node entity. So, it is extremely unlikely that JSON:API will return an empty metatag set for any content entity. In code `resource.metatags?.length > 0` determines when `CustomTags` are rendered and so I wonder what resource request would return an empty metatag array? 

For the metatag default values, I looked to `/jsonapi/metatag_defaults/metatag_defaults/f42b456a-5bd3-4c7a-a22e-2ce306a4ba1b` which outputs this for the default "Content" metatag configuration.

```json
description: "[node:field_description:value]",
image_src: "https://www.va.gov/img/design/logo/va-og-image.png",
title: "[node:title] | Veterans Affairs",
og_description: "[node:field_description:value]",
og_image: "https://www.va.gov/img/design/logo/va-og-image.png",
og_image_alt: "U.S. Department of Veterans Affairs",
og_site_name: "Veterans Affairs",
og_title: "[node:title] | Veterans Affairs",
twitter_cards_description: "[node:field_description:value]",
twitter_cards_image: "https://www.va.gov/img/design/logo/va-og-image.png",
twitter_cards_image_alt: "U.S. Department of Veterans Affairs",
twitter_cards_site: "@DeptVetAffairs",
twitter_cards_title: "[node:title] | Veterans Affairs",
twitter_cards_type: "summary_large_image"
```

Since the description value is entirely dynamic, `[node:field_description:value]`, I left that out of the defaults. I only added the alt tags from the list ^^^ above and copied over what was listed in content-build. So not every default tag listed in Drupal is accounted for.

But is the `Derive the title.` section in the content-build metatag code covered, you might ask? Well, looking at Drupal Metatags configuration, I would say yes. The content-build tags seem generic and try to cover several content types but the Drupal Metatags are set per content type and will be reflected in the `CustomTags` component output.

1. Drupal event metatag for title:`[node:field_listing:entity:field_office] | [node:title] | Veterans Affairs`
2. content-build metatag code for title: `{% elsif fieldOffice %} {% assign metaTitle = fieldOffice.entity.title %}`

What if the stakeholders don't like the custom metatag titles? Well, I say update it at the CMS level rather than adding conditionals in the code. I could be totally misunderstanding how/why the default metatags functioned in content build; however, I think it is an improvement to allow editors to alter the metatags as they choose without needing developer intervention.
