### ISSUE TITLE
PACT Act Wizard foundational testing artifact

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16443]
## Description
For Staging review, we must:
* do a11y foundational testing of our product; ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72031)
* product artifacts to prove it
* File a [Platform collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&projects=&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) providing those artifacts and notes on our testing, 4 business days prior to our scheduled Staging Review

## Additional Context 
* [PACT Act logic flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=u0b235d03cbd64f7f93673243)
* Staging app: https://staging.va.gov/pact-act-eligibility/introduction

## Acceptance Criteria
- [x] Foundational testing is complete
- [x] Artifacts are provided
- [x] Platform cc a11y ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/72031) is ~filed~ updated

**Comment by jilladams** [comment]
Michael _may_ be able to reach Staging. Maybe not. Could help if so.

**Comment by jilladams** [comment]
@FranECross , @Becapa verified he can reach Staging so we can have him handle this. This would be great to pick up. This is higher priority than the GraphQL linting SPIKE by a mile, so @Becapa may be wise to find a logical stopping point there and pull this in instead? We can report that in current sprint if you get started before Wed, or Sprint 100 if not.

Also! @laflannery flagged: doing foundational testing for every single question in the wizard is a lot, and most of these questions use the same custom markup for things like radio buttons, text entry, checkboxes, etc. She is going to check with Brian DeConinck (the a11y lead on the Platform governance team) to confirm the extent of the testing we need to do here.

Also note to self: I need to add to this ticket: 
* Logic flow link
* The staging url

**Comment by jilladams** [comment]
Also also: @Becapa Laura did a presentation on Foundational testing awhile back that you can check out for context on the thinking / tooling / process: 
[Foundational accessibility testing video](https://youtu.be/cTOXiOW4oE4)
[Slides](https://docs.google.com/presentation/d/1QGgCFZgwOQ8KiixNhvJ1Z4xi8OwN6FZ6UoKhYal9Rp0)

**Comment by Becapa** [comment]
@jilladams I just want to double check, but it looks to me like the first and third bullet points in the first part of the description are the kind of the same thing. The third bullet point created the first one? Also, I'm assuming based on the Foundational accessibility testing video that the only artifact needed is the filled out[ cc a11y ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72031), or are there additional items that are needed?
c.c. @laflannery @FranECross

**Comment by jilladams** [comment]
Good call -- you're right. So what Laura typically does is create the a11y ticket like #72031 that you noted, and use that ticket to track progress through the test cases, then ping Brian DeConinck on that ticket when she's done to review the output. We created this separate ticket just to be able to track the work in our sprints. I updated the ACs to be a little more clear on that, since in this case, the a11y ticket already exists.

**Comment by laflannery** [comment]
@Becapa Notes on testing:

We want to make sure that we hit all 3 results scenarios so that means you will need to go through at least 3 scenarios to get to each screen. You don't necessarily need to test every question each time though because they are the same. My recommendation:
- Scenario 1:
  - **TEST: S1 > "During both these time periods"**
  - **TEST: 2.1 > Yes** 
  - **TEST: 2.2 > Yes > Choose location**
  - **TEST: 2.3 > Yes > Choose location**
  - **TEST: 2.4 > Yes > Results 1.1 > Results 1.2**
- Scenario 2:
  - IGNORE: S1 > "During both these time periods"
  - IGNORE: 2.1 > No
  - IGNORE: 2.1.1 > No
  - IGNORE: 2.1.2 > No
  - IGNORE: 2.2 > No
  - IGNORE: 2.2.1 > No
  - **TEST: 2.2.2 > No**
  - **TEST: 2.2.3 > No**
  - IGNORE: 2.3 > No
  - **TEST: 2.4 > Yes > R2**
- Scenario 3:
  - IGNORE: S1 > "During both these time periods"
  - IGNORE: 2.1 > No
  - IGNORE: 2.1.1 > No
  - IGNORE: 2.1.2 > No
  - IGNORE: 2.2 > No
  - IGNORE: 2.2.1 > No
  - IGNORE: 2.2.2 > No
  - IGNORE: 2.2.3 > No
  - IGNORE: 2.3 > No
  - **TEST: 2.4 > No > R3**

Also, it's probably a good idea to put my name in the accessibility artifact ticket - so they know we have someone on the team. I'm thinking in the "Additional Findings" section, you can put something to the effect of "Advanced testing was completed by our accessibility specialist" and then tag me.

Any questions you have when doing this please feel free to reach out!

**Comment by jilladams** [comment]
@Becapa I think we could call this done now, and any additional feedback / questions will pop up during the Staging Review. Closing, but @laflannery once you're back online, if you disagree or have concerns, please feel free to reopen.
