### ISSUE TITLE
OpenAPI UI Event Subscriber

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#16456]
## User Story or Problem Statement
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16454 adds Swagger UI functionality for viewing and exploring Drupal's JSON:API.

In the effort of merging with minimal composer fighting, a JS library was added with a hook_page_attachments instead of an EventSubscriber. This should be converted to use an EventSubscriber with dependency injection.

## Description or Additional Context 
Examples of EventSubscribers already in use in the va.gov-cms repo: https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fva.gov-cms%20EventSubscriber&type=code

## Acceptance Criteria
- [ ] The code in the `va_gov_api_page_attachments` hook is moved to an appropriate Event Subscriber instead.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [x] Accelerated Publishing

**Comment by alexfinnarn** [comment]
So this was a bit of a doozy since I can't find an event that approximates what the hook, `hook_page_attachments()`, does. 

Firstly, the `hook_page_attachments()` documentation states "Use this hook when you want to conditionally add attachments to a page." which is the exact reason why I chose to use the hook in the first place. It is still used in Drupal core `10.x` and doesn't have a deprecation notice. So, I would think Drupal core developers would be fine with leaving the hook in the codebase, especially since we need to have an end-to-end test to verify the Swagger UI is functioning properly which also proves the hook works. 

Having said that, I went ahead and converted the hook code to an event using the "get out of jail free" event subscriber, a.k.a. `OnKernelResponse`. You can do anything you could possibly want in that event subscriber, and I tend to use it when I need to do something across a lot of responses. In this case, it's just one route, though. 

I'm still not sure how to properly attach a Drupal library via the `OnKernelResponse` event, or any other event for that matter, but I certainly know how to inject a script tag into the page. I got things working, and I will post the branch for now and some caveats. 

Branch: https://github.com/department-of-veterans-affairs/va.gov-cms/compare/VACMS-16456-hook-to-event?expand=1

My first hurdle in appending JS to the DOM somewhere in the response was the fact that `$event->getResponse()->getContent()` gets you the whole HTML document whereas I wanted to only modify the HTML body. My code was working, but I had weirdly included the JS 18 times on the page when I thought I was adding it only once. I concluded that I would need to parse the document to append the JS and switched to that method using `DOMDocument()`.

However, adding the JS more specifically still ended up with 18 instances of the code running. At that point, I thought it must be subrequests...and it turned out AJAX calls were the culprit. So anything loaded via AJAX got the JS attached to that HTML, which in this case were mostly all menu links. I guess the admin menu or parts of some menu are loaded after the first main request. 

Adding `$event->getRequestType() == HttpKernelInterface::MAIN_REQUEST` allowed me to only target the main request. Then, I got another weird set of errors.

```
Warning: DOMDocument::loadHTML(): Tag nav invalid in Entity, line: 137 in Drupal\va_gov_api\EventSubscriber\AddJsEventSubscriber->onResponse() (line 58 of modules/custom/va_gov_api/src/EventSubscriber/AddJsEventSubscriber.php).
```

They all happened with `$dom->loadHTML($responseContent);` and apparently, 21 tags on the "/admin/config/services/openapi" route are invalid. Since it's an admin page, I don't think this is a big deal, and so I suppressed that with: 

```
      // Need to suppress errors due to invalid tags.
      libxml_use_internal_errors(TRUE);
      $dom->loadHTML($responseContent);
      libxml_clear_errors();
```

But why did those errors not show up before I targeted only the main request? I have no idea...

I'll pause on this to work on my other sprint ticket. I might try adding a test, but the code seems to work as-is. I'm also open to other suggestions on how to convert this hook into an event.

**Comment by tjheffner** [comment]
`docroot/modules/contrib/hook_event_dispatcher/modules/core_event_dispatcher/src/PageHookEvents.php` or `docroot/modules/contrib/hook_event_dispatcher/modules/core_event_dispatcher/src/Event/Theme/PageAttachmentsEvent.php` may be the event you want
