### ISSUE TITLE
R&S Editor: Remove Tag/Topic selection restrictions

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16574]
## Description
There is a mechanism controlling the total amount of "Tags" (the sum of all topics and beneficiaries/non-beneficiaries), which limits the total amount to 4. The current behavior works by counting the total number of Tags, including Topics and Beneficiaries, with the intent to cap the total to 4. Once the editor makes a total of 4 selections, the Tags field is locked for further editing.

We have approval from Mikki/Danielle to remove the restrictions completely.

### User story

**AS A** editor of Resources & Support node
**I WANT** to be able to add multiple Beneficiary types as well as multiple topics, without restriction
**SO THAT**  the R&S page more accurately represents reality.

### Engineering notes / background
- this is a fast-follow ticket in conjunction with [#13188](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13188#top)

## Acceptance criteria

- [ ] Change the help text, removing the maximum of 4 statement.
- [ ] Update the code to not restrict/lock out the Topics field at all (IOW an editor may add as many topics / beneficiaries to an article as they like)

**GIVEN:** A resources and support node editor is creating an article
**WHEN:** the editor adds 4 or more beneficiaries
**THEN:** the editor may add 1 to all the remaining topics
**AND** the editor encounters no errors and is able to publish / save the article (e.g. editor may add all beneficiaries and all topics successfully; no restrictions)

**Comment by jilladams** [comment]
Pulling into Sprint 101, likely to roll into 102, in order to fix #16850, correlated new bug.

**Comment by jilladams** [comment]
REopening to verify in prod

**Comment by jilladams** [comment]
Verified in Staging (which is prod mirrored) as Megan Zehnder (CAIA).  All 6 R&S content types allow >4 tags to be applied, across Tags / Beneficiaries field.

- checklist
- media_list_images
- media_list_videos
- step_by_step
- faq_multiple_q_a
- q_a
- support_resources_detail_page

I hadn't previously noticed, but Non-beneificiaries is still a radio button. Not an issue, not in scope for any changes here or in 13188, but just noting since I noticed it.

Closing.
