### ISSUE TITLE
Publish updated Alt Text KB Article

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16685]
## User Story or Problem Statement
As an editor, I would like to know why alt text is important so I can ensure that when I upload media files, the alt text is accessibility compliant. 

## Description or Additional Context 
New alt text client side validation has a tentative launch date of January 11.  As part of this launch, we need to include an updated KB article.  Current alt text KB link: https://prod.cms.va.gov/help/cms-basics/alternative-text. This ticket relates to [#15549](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15549).

[Updated article from Laura](https://docs.google.com/document/d/1_V2JfLMBnY6hSTyk5M6MS0lnOqV6cO9Hc8FCSu9buLE/edit#heading=h.2g3fvchjm8bh). 

## Acceptance Criteria
- [x] Add new KB article with new content
- [x] Update existing KB article to remove any duplicate content that was added into the new article
- [ ] Requires PO review

## Team
Please check the team(s) that will do this work.

- [X] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by laflannery** [comment]
Thanks @maortiz-27-80 I will get this done early next week

**Comment by laflannery** [comment]
@maortiz-27-80 and @EWashb I updated the 2 KB articles and they are ready for review:
- New KB article ["Alternative text for images"](https://prod.cms.va.gov/help/cms-basics/alternative-text-for-images)
  - This is the new training article, what is alt text, why is it important, why should you do it, etc.
- [Updated existing article](https://prod.cms.va.gov/node/49612/latest)
  - Update this to be strictly "How to add or update"
  - Linked to the new article in both the body content and in the related articles section

**To Dos:**
- If these look good, they both can be published whenever, they do not need to wait until you launch the new updates
  - You have to published them at the same time though since they are sort of dependent on each other
- When you do publish the new updates, you need to [update the existing article](https://prod.cms.va.gov/node/49612/latest) and replace the first 2 screenshots because the UI has changed.

Let me know if there are any questions on anything!

**Comment by maortiz-27-80** [comment]
@laflannery - These look great and I say feel free to publish.  We can update the screenshots post prod deploy of the feature on 01/11.  Any objections, @EWashb ? cc: @BerniXiongA6

**Comment by laflannery** [comment]
@maortiz-27-80 `Both articles have been published, the last item would just be to update screen shot to show the new UI

**Comment by maortiz-27-80** [comment]
[Existing article](https://prod.cms.va.gov/node/49612) has now been updated with images.  Thank you for your help, @laflannery !  Closing. cc: @BerniXiongA6 @michelle-dooley @EWashb
