### ISSUE TITLE
[Figma Migration] Move FAF Download PDF Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16687]
**Status 2024-02-28:**

- All files have been moved from Agile Six Figma to VA Platform Figma ahead of the March 29, 2024 deadline
- Next step is to convert components in design files to Figma VA design system components. This will be done whenever time permits. 

## Description

The FAF Download PDF Sketch files need to be imported into VA Figma because the Sketch license ends on February 16th, 2024.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Sketch file imported to VA Figma (this is currently tracked as a check mark in this file)
- [x] File Cleanup: Design components and styles relinked to Figma VADS

**Comment by thejordanwood** [comment]
I only updated the modal shown on the Final page of this file. For consistency when updating these files, I haven't been updating the Working page because those pages usually contain a lot of clutter. Saying this to acknowledge that there are other mockups that could be converted on the Working page, but I'm not sure how relevant they are. 

Link to new file: [FAF Download PDF](https://www.figma.com/design/jNtNhQJOVzzhAb87LYJZvJ/FAF-Download-PDF?node-id=1%3A3348&t=ieVDkZkKDjUev6DU-1)
