### ISSUE TITLE
Fill out Privacy Threshold Analysis (PTA) and new registration screenshots documents

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16821]
## User Story or Problem Statement
Fill out: (1) Privacy Threshold Analysis (PTA) form and (2) new registration screenshots as a prerequisite to register CMS as a "minor application" in accordance with VA SOPs.  VA security has setup a [Sharepoint folder here](https://dvagov.sharepoint.com/:f:/r/sites/OCTOInformationSecurity/Shared%20Documents/Ge[…]eview/Minor%20Applications/CMS/Intake?csf=1&web=1&e=Bdj0XG) for CMS team documentation for collaboration and single source of truth.  Due Thursday, January 18, 2024. 

## Description or Additional Context 
VFSP-VA.gov and CMS team met on 01/11/24 to discuss CMS-specific ATO-related information. PTA is a required document for the ATO process. This allows application owners to list and describe the data elements in the application. It is also used to identify sensitive data and determine Confidentiality Impact level of the application.

Files attached. 

## Team
Please check the team(s) that will do this work.

- [X] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

[FY23StandardPTATemplate.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenU4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--960caa3c094d79fec17b7afabf826070da21e836/FY23StandardPTATemplate.docx)
[new registration screenshots.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejI4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0499f8dccfbf869abada31bb7b2ac2fcfbd6e9e4/new%20registration%20screenshots.docx)

cc: @BerniXiongA6 @EWashb @michelle-dooley

**Comment by maortiz-27-80** [comment]
@ndouglas - Note per Ray, re: prioritization: the responses to the data fields are what we need first and pta can come next

**Comment by BerniXiongA6** [comment]
@ndouglas please update ticket thanks!

**Comment by ndouglas** [comment]
As mentioned in this [thread](https://dsva.slack.com/archives/CT4GZBM8F/p1704991396622869), I'm confused about what "data" means in this context.

If we're talking about "data" as in outputs from the eMASS registration process, I don't have that and can't provide it because I can't figure out where the eMASS registration process is actually housed. I have screenshots, but no actual address. I found a site that seems to offer something like that, but I do not seem to have permissions to actually initiate eMASS registration. I can only view pending eMASS registrations.

If we're talking about "data" as in what data we actually process in the CMS, and whether that's PHI/PII or not or sensitive in any other fashion, etc, then I uploaded a document to the Sharepoint folder on the 11th called "Notes on PTA", perhaps visible at this link: https://dsva.slack.com/archives/CT4GZBM8F/p1704991396622869 that answers these questions as best I could.

At first I thought we were talking about the former, but now I think it's more likely we're talking about the latter. In which case we might just need Paul to read through that and see if there's anything I or someone else should clarify.

cc @EWashb

**Comment by EWashb** [comment]
I emailed Paul Walker and team on 1/18/24 to confirm that the drafts were uploaded to the SharePoint and are ready for review.
