### ISSUE TITLE
Verify GovDelivery callback works in AP, before content-build deprecation

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16833]
## User Story or Problem Statement
Currently there is a handshake between CMS and content-build where content-build alerts the CMS when a content release has been completed so that the CMS can then send time related items in the queue to govDelivery.
[Primary Documentation](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/vamc-facilities.md#system-banner-alerts-and-situation-updates-to-govdelivery) 

[other related documentation - downstream dependencies](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/downstream_dependencies.md)

Depending on the behavior of AP and the time from save to content appearing on FE, we may be able to remove some of these dependencies.  It is also possible that AP could just trigger the callback to CMS and things will continue to work just fine.   

## Acceptance Criteria
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by timcosgrove** [comment]
At AP launch, a substantial amount of the Facilities pages will still be published by Content Build. While that is true, the GovDelivery mechanism should be the same, since it is still time-bound by the speed of Content Build.

Once every page type that a Situation Update/banner could appear on is migrated, this can be revisited. The assumption is that by that point, Next Build will be doing speedy incremental publishing, and so the publishing system no longer needs to be involved. It should be enough to send the GovDelivery callback from CMS itself upon save of the Situation Update/banner. By the time anyone would receive notification via GovDelivery, the content should already be visible in production.
