### ISSUE TITLE
New authenticated users without extra roles have no ability to log out or view profile

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1685]
## Description

As a new authenticated user who has not been assigned any additional roles, I need to have a way of logging out while my profile is being processed.

As a new authenticated user who has not been assigned any additional roles, I need to be able to access my profile, so as to understand that I am indeed logged in.

## Acceptance Criteria
- [ ] New authenticated user who has not been assigned any additional roles, can access their profile page and has access to logout link.

**Comment by kevwalsh** [comment]
This (and #1684) stem from the fact that we PIV card login has allowed people to create totally useless CMS accounts for themselves. 

The easiest might be to simply provide access to the admin toolbar.  But perhaps in the #1029 epic (Q2 2020, maybe) we prevent people from creating their own approved accounts. PIV login could begin an account approval process, where role and section are asssigned.

**Comment by ndouglas** [comment]
As it turns out, this is causing issues with the Drupal 9 upgrade; the Behat tests look for content within the page to determine whether a user is logged in.  By default, this is text like "Log out," which is provided by the toolbar.  If we give toolbar access to authenticated users, this solves the problem.  As an alternative I think we can add a class to the `<body>` tag, like `logged-in`, which has fewer UX implications.

**Comment by kevwalsh** [comment]
This has been resolved by #4918
