### ISSUE TITLE
CMS Preview for Prod and Staging should have logs collected and forwarded

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16956]
## Requirements

We want logs for our preview servers collected and forwarded to a central logging system, so that we can monitor the health of those systems and troubleshoot any issues with them.

```[tasklist]
### Acceptance criteria
- [ ] Logs for Staging and Production Preview servers are forwarded to Datadog
```

## Background & implementation details

This may just be a confirmation task.

**Comment by jschmidt-civicactions** [comment]
Looks like this is working correctly, although I'm going to look into passing env tags to Datadog so that we can filter the logs better. Hector Barreto is looking into the current best practice for this, since it isn't 100% clear from the current apps or documentation what values to use there. I don't want to clutter up anyone else's envs if some are special-purpose.
