### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for the the PACT Act Wizard

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17004]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

[PACT Act App](https://staging.va.gov/pact-act-eligibility/introduction)

### V1 components that need to be upgraded

1. Accordion
   - Accordion section on results screen to be updated [to v3](https://design.va.gov/components/accordion#examples---v3).
2. Button
   - Back button on results sreen should be using the [v3 component](https://design.va.gov/components/button/#examples---v3)
3. Button pair
   - Each screen should be using the [v3 component](https://design.va.gov/components/button/button-pair#examples---v3)
4. Additional Input
   - C-123 screen should have [v3 component](https://design.va.gov/components/additional-info)
## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [x] the V3 components are now used for the features listed above, and display/function correctly
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [x] a11y review

**Comment by randimays** [comment]
[Laura verified in Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1708541491209849?thread_ts=1708538129.616729&cid=C52CL1PKQ) that we are good to go from an accessibility standpoint. I verified in staging just now (see screenshots below). Because this app is not deployed to production yet, there is no need to verify there. Closing!

Accordions
<img width="402" alt="Screenshot 2024-02-21 at 5 14 19 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/65dfbf06-4f22-45e2-91b8-e72d0d38a4b5">
<img width="804" alt="Screenshot 2024-02-21 at 5 14 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/09d064a0-15ff-4861-9ce8-625575478a95">
<img width="398" alt="Screenshot 2024-02-21 at 5 14 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/00410a18-63c5-4450-9ca1-ca3b408eb4a4">

Button Pair
<img width="403" alt="Screenshot 2024-02-21 at 5 13 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b9914747-0a6e-4d58-8784-db8a7a36c1fa">
<img width="403" alt="Screenshot 2024-02-21 at 5 14 48 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/1cb11fd9-e54c-4886-90db-2644f831356d">

Additional Info
<img width="710" alt="Screenshot 2024-02-21 at 5 14 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b3999ab1-4f78-460e-b493-efb172cf5948">

Button
<img width="522" alt="Screenshot 2024-02-21 at 5 14 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/eae86453-3a8d-4cbc-b565-bcda3f8f28b8">
<img width="401" alt="Screenshot 2024-02-21 at 5 14 04 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/d100f5b1-eb3a-41f2-a8cb-d5510ae2dee8">
