### ISSUE TITLE
Specify default JSON:API Extras enhancers link fields globally

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#17021]
## Requirements

We want to be able to override the default output of fields in JSON:API automatically, so that all fields output as we want and new fields will also output correctly.

JSON:API has a concept of 'enhancers', which are data formatters. Rather than outputting the default data structure for a field, an enhancer either adds to the data or reformats it. For example, there is a URL formatter for link fields which adds `url` to the output, which contrasts with `uri`. `uri` may be in a Drupal-internal format that is not usable on the front-end; `url` provides the translation from internal format to general format.

We can override individual field output now. However, in the link field example above, we will always want all link fields to include this information. We want to apply this format to link fields globally, without having to specify it field by field. This will also apply the formatting to new fields as they come into the system.

```[tasklist]
### Acceptance criteria
- [x] For a given JSON:API instance, link field enhancers can be applied globally
- [x] New fields added to the system have the default enhancer applied to them automatically
- [x] Other enhancers can still be applied on a per-field basis
```

## Background & implementation details

This ticket grew out of the need to address things like `field_default_link`, visible in this API response: https://prod.cms.va.gov/jsonapi/paragraph/react_widget/5663a0dd-a69c-40b7-b50b-526646e32204?resourceVersion=id%3A16094

Specifically, these sorts of values:
```
      "field_default_link": {
        "uri": "internal:/pension/application/527EZ",
        "title": "Apply for Veterans Pension Benefits",
        "options": [
          
        ]
      },
```

Questions:
For default enhancers generally:
* Is the a field creation/add event that we can key off to apply the enhancer to new fields?
* Is it important that we be able to apply 'none' as an override from the default enhancer? This would have implications for how we can go about doing the default & overrides.

For link fields specifically:
* Is all link data coming out with the same format from the CMS? Is it a field configuration issue? What are the potential side-effects of changing field configuration, if that is a viable option?
* How many different field configurations do we need to take into account for this change?

**Comment by alexfinnarn** [comment]
I've figured out how the `jsonapi_extras` module applies field enhancers to resources after searching through the `jsonapi_extras` codebase and using Xdebug. 

The application of enhancers happens in the `FieldItemNormalizer` class. It looks to see if the resource type has a field enhancer defined in configuration, and then transforms the data using the specified enhancer. It technically decorates the `jsonapi` field normalizer and also uses setter injection to load the field enhancer. I didn't dig too much into the architecture or the curious "Impostor" classes, but at least I found where I can start attempting to modify the code. 

There is one part of the normalize function where I think the default enhancer would be best placed. 

```php
  public function normalize($object, $format = NULL, array $context = []) {
    // First get the regular output.
    $normalized_output = parent::normalize($object, $format, $context);
    // Then detect if there is any enhancer to be applied here.
    /** @var \Drupal\jsonapi_extras\ResourceType\ConfigurableResourceType $resource_type */
    $resource_type = $context['resource_object']->getResourceType();
    $enhancer = $resource_type->getFieldEnhancer($object->getParent()->getName());
    if (!$enhancer) {
     // @todo Add the default enhancer here...
      return $normalized_output;
    }
   // ...More code.
```

I think adding a method to the resource type class to look for `$resource_type->getDefaultFieldTypeEnhancer($object->getParent()->getType())` makes sense. The defaults would have to have configuration, just like individual field enhancers. Something like gathering all the field types and then listing them the same way as fields are for individual resource types. With that setup, this code might even be appropriate for inclusion in the `jsonapi_extras` module. 

The biggest difficulty I see now is the potential for field configuration to have many different data shapes for a link field based on the field formatted being used. If someone adds a new field formatter, what do you do? The default for the link field type might not take the new formatter into account, and that would break the output. 

I don't think it is possible to deal with these potential breakages, which is why this feature could be tricky to implement. With the current field enhancers, you already have created the field and know the output of the default/non-enhanced field so it is pretty safe to apply enhancers to that particular field instance. Looking for the internal protocol on link fields should be straightforward, but transforming anything else without knowing the data shape ahead of time is hard. 

Then there's caching. The current field normalizer applying the enhancers also adds cache tags and context. In cases when the default field type enhancer is applied and there is also a field instance enhancer you would want to only cache one set of data, and then clear the cache if the configuration changed. Maybe caching the field type enhancer is unnecessary and field instance enhancer or no enhancer conditions already cache properly, but another thing to think about.

**Comment by alexfinnarn** [comment]
I've gotten some hacky code working where a link URI of `entity:node/123` ended up as an alias like `/outreach-and-events/events/craven-county-north-carolina-veterans-stand-down` but I'm not sure how to best integrate it with current code as it is. Like most of this work, I'm still pretty new to JSON:API, its history, and how the code has evolved. 

So, I started going through open issues for the `jsonapi_extras` module, https://www.drupal.org/project/issues/jsonapi_extras, and I found this issue relating to adding field types to field enhancers: https://www.drupal.org/project/jsonapi_extras/issues/2997353 . A lot of people agree with the usefulness of adding field types to enhancer metadata. If that change had landed, I could use it...and maybe we wouldn't need to do anything since there would be a way to add a field enhancer to all field instances of a certain field type.

I've gotten further with adding configuration so code can read whether or not each field type has a default enhancer applied to it. However, there's no good way to add code that won't slow down JSON:API responses. There are hundreds of field instances that would all have to be checked for a default enhancer for the field type on top of an enhancer for the field instance. I have no idea of the actual performance costs, which would relate to how many fields a resource has on it.

**Comment by alexfinnarn** [comment]
Regarding performance costs, the code I added can take into account the field type enhancer configuration as well as field instance enhancers. I was mistaken in thinking a config file per resource needed to be checked when, in fact, only one configuration file for all field types is needed. 

I ended up adding another configuration form for the field type enhancer at "/admin/config/services/jsonapi/field_types" that lists all field types and allows the user to choose a field enhancer + settings per field type. 

This worked well locally, but on Tugboat the PHP configuration is different. So when I tried to save the config form on Tugboat I got: 

```
Warning: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0
```

Looking at `phpinfo()` output, local has `max_input_vars` as 5000, where on Tugboat it is 1000. I also noticed `memory_limit` is 4G locally but unlimited on Tugboat. 

I'm not sure what the policy for keeping PHP settings aligned across environments is, but I generally try to advocate for settings to be as similar as possible so it's not "works on my machine" because I have different PHP configuration locally than on Tugboat. 

I also thought to check staging and prod but https://staging.cms.va.gov/ is on the install screen again and I'm not sure how to log into production. My lower environment creds aren't the same and I didn't get a password reset email.

I can work on the code to have the ability to exclude all field types unless they are included in an allowlist. It's probably not a good idea to add all field types on the site as many would never be appropriate for adding field enhancers. I can print out the field types available and then have a comma-separated list of field types that actually have a form element rendered.
