### ISSUE TITLE
Breadcrumbs incorrectly displaying in Spanish

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#17082]
### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [X] Something else

### Describe your request

We noticed a few disability pages are showing part of the breadcrumbs in Spanish. None of these pages have a Spanish equivalent. Two examples:

https://www.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/
https://www.va.gov/disability/eligibility/former-pows/

### Time constraints / launch deadlines

No hard timing

### Your product/team Slack channel

Sitewide CAIA

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by FranECross** [comment]
@dsasser Is this something you'd be able to take on in the sprint starting Wednesday? If so, will you please provide an Estimate swag? Randi Mays indicates this is exclusive to Drupal menu, so front-end or drupal engineers could work on it. Given the header/footer deadline, I wanted to tag you with it. cc @jilladams

**Comment by dsasser** [comment]
@FranECross 

> Is this something you'd be able to take on in the sprint starting Wednesday
If you are asking if I have the technical ability, then yes. If you are asking capacity, I don't know what that looks like yet.

> If so, will you please provide an Estimate
I would have to estimate fairly high as I am not familiar with how breadcrumbs work and would have to spend some time getting up to speed on that. Thinking a 5 would do it.

**Comment by dsasser** [comment]
@RLHecht This is occurring because there are multiple menu links in the `disability-benefits-hub` that point to the same node and happen to share the same "weight". This isn't a problem in and of itself, but for the purpose of breadcrumb creation, Drupal will grab the "first" menu link that matches the current page, and build breadcrumbs from that.

The solution is simple enough: change the weight of one of the duplicate menu links for each page.

To test and confirm, I created a Tugboat and changed the link weights for the two affected pages by editing the links in the menu UI. After rebuilding the FE, it looks like the affected pages are showing the correct breadcrumb.

Please confirm the desired outcome here:
https://cms-x05v0cnfaj4rgcpfdutaoxa2jyrtzt6t.demo.cms.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/
https://cms-x05v0cnfaj4rgcpfdutaoxa2jyrtzt6t.demo.cms.va.gov/disability/eligibility/former-pows/

if confirmed, I'll set the weights for the menu links in production and we'll just need to wait for a content release to update (no need for a code change for this issue).

**Comment by dsasser** [comment]
cc @FranECross ^

**Comment by jilladams** [comment]
Noting: in the past we've had issues where CAIA folks don't have SOCKS and can't access Tugboat, so if Randi H can't access, may need to provide screenshots for verification.

**Comment by RLHecht** [comment]
@dsasser The Tugboat links worked for me but I'm not sure if the breadcrumbs are set up correctly. On the pages you sent there is a "Get benefits" section of the breadcrumbs that's not showing on Prod. When I click the preview in Tugboat it's still showing in Spanish.

**Comment by dsasser** [comment]
@RLHecht 

> On the pages you sent there is a "Get benefits" section of the breadcrumbs that's not showing on Prod. 

These labels are only present on the CMS side, they won't be rendered on the FE. 

> When I click the preview in Tugboat it's still showing in Spanish.

This was an oversight on my part--just needed another content release.

Also I neglected to send the FE pages for review which can be found at:
https://web-x05v0cnfaj4rgcpfdutaoxa2jyrtzt6t.demo.cms.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/
https://web-x05v0cnfaj4rgcpfdutaoxa2jyrtzt6t.demo.cms.va.gov/disability/eligibility/former-pows/

**Comment by RLHecht** [comment]
Thanks @dsasser! Those 2 preview links look good to me. Is there something the CAIA team should be doing going forward when either building new Drupal pages or working on existing ones to prevent this from happening?

**Comment by dsasser** [comment]
> Thanks @dsasser! Those 2 preview links look good to me. Is there something the CAIA team should be doing going forward when either building new Drupal pages or working on existing ones to prevent this from happening?

The only thing you can do is look out for links to the same page/node appearing multiple times in a menu. If any of those links share a "weight", then Drupal doesn't alway pick the right one for building the breadcrumbs for that page.

**Comment by dsasser** [comment]
@RLHecht I made the change on production so we should see the changes reflected on the FE in the next content release.

@FranECross FYI ^
