### ISSUE TITLE
Front end: Implement Lovell Cerner (Oracle Health) changes

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17107]
## Description or Additional Context 
#16485 identified some outstanding questions in support of the Lovell Cerner (Oracle Health) changes expected for March 2024.

The ACs for this ticket are specific to Lovell VA page, not Lovell TRICARE. TRICARE of scope for this ticket, changes moved to #17299

## Acceptance Criteria
- [x] For the Lovell VA page, the transitioning to Cerner toggle being present in staging is confirmed.
- [ ] Verify if tests should be added/updated.
- [ ] If needed, stub tickets for follow-up.

**Comment by mmiddaugh** [comment]
@xiongjaneg 

> What are the specific MHS Links that need to be used for each link label?

_We know the general patient portal link is: https://my.mhsgenesis.health.mil/ but I am trying to understand if deeper task-specific links are expected. Requested from Lovell POCs on 1/30/2024_ 

> What was the specific reason that these links were hidden on TRICARE pages? Will they still need to be hidden from TRICARE pages under some circumstances, or will this change mean they can always be visible?

_They were hidden because they are hard coded and the links would not be correct for Lovell TriCare populations. Lovell POCs indicated they would like the Manage your healthcare online made available for Tricare pages but I am trying to confirm if it should be applied to all Tricare locations in the same way. Requested from Lovell POCs on 1/30/2024_ 

> How much will we need to coordinate with public websites and similar Cerner changes they've made on their widget?

_Possibly less critical than the need to coordinate with other teams working to support Lovell's EHR transition. I am coordinating in [#vagov-oracle-launch-coordination](https://dsva.slack.com/archives/C0190MTGNUE)_

**Comment by xiongjaneg** [comment]
There's nothing for Facilities to do on the VA side only for Tricare.

**Comment by mmiddaugh** [comment]
Tricare effort in #17299
@xiongjaneg are there tests which should be added/updated?

**Comment by jilladams** [comment]
We completed QA today in Staging. @eselkin your [PR for those changes](https://github.com/department-of-veterans-affairs/content-build/pull/1945/files) didn't include any. new tests that I can see, per MIchelle's comment above. Could you chat with @xiongjaneg about whether new tests would be beneficial? If so, could get those done under this ticket if we add to ACs.

**Comment by eselkin** [comment]
That's a good point. I didn't find a regular way to component test since it's a conditional in an existing template. However, since it's published content that shouldn't change, I think I can add a e2e test on Lovell links and that would test the extent of links.

**Comment by xiongjaneg** [comment]
Testing will likely carry over to sprint 106

**Comment by xiongjaneg** [comment]
@eselkin Have we gotten any further on the remaining testing ACs? Does testing need updating or do we need new ones?

**Comment by eselkin** [comment]
We need new ones there are no old tests and it was hard to come up with an idea for testing while the data was changing. I have to write some tomorrow. I was chasing errors and alerts today with Michelle and the CI kept failing while I was trying to get the Vet Center PR ready.

**Comment by xiongjaneg** [comment]
Sounds good, thank you!

**Comment by eselkin** [comment]
Test PR is up but CI is still being weird
