### ISSUE TITLE
PW intake: Add the Spanish toggle and left nav on new disability page from CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#17304]
### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [X] Something else

### Describe your request

We recently published the About VA DIC for spouses, dependents, and, parents in Spanish. We now will need the Spanish toggle and left nav set up. Here's the Spanish page: https://www.va.gov/disability/dependency-indemnity-compensation-esp/ 

### Time constraints / launch deadlines

No hard timing

### Your product/team Slack channel

Sitewide CAIA

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by jilladams** [comment]
@chriskim2311 @randimays this is one we can prefine and pull over to stretch / pick up whenever we have capacity.

**Comment by randimays** [comment]
Updated the ticket title to include left nav as mentioned in the description.

**Comment by randimays** [comment]
@RLHecht Is this the Spanish translation for `Survivor and dependent compensation (DIC)` (for the left nav):

`Sobre VA DIC para cónyuges, dependientes y padres`

**Comment by RLHecht** [comment]
We'd like to have it mirror the English left nav if it works in Spanish so let me confirm with our translators what the Spanish translation of "Survivor and dependent compensation (DIC)" would be. For future work I can make sure that we have this translation already approved before I create these tickets so you'll have what you need.

**Comment by RLHecht** [comment]
@randimays Here's the content for the left nav: Compensación para sobrevivientes y descendientes (DIC)

Thank you!

**Comment by randimays** [comment]
End-of-sprint update: This will likely carry over. I got bogged down this sprint by CI issues and struggled to get my other tickets reviewed and over the line. I have added the toggle to the page but the left nav still needs to be done. @jilladams @FranECross If another Drupal admin has some time today and can add the left nav, that would be helpful! Otherwise I'll get to this ASAP.

**Comment by randimays** [comment]
End-of-sprint/contract-update is same as above. It will carry over. I haven't been able to get back to this.

**Comment by randimays** [comment]
@RLHecht We're having trouble getting the sidebar to show up on this page. We think it's because of a section mismatch between the English and Spanish version of the pages.

English version:
<img width="378" alt="Screenshot 2024-04-02 at 10 06 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/bf1cfedc-4685-4d90-be5d-48e8bd57dedf">

Spanish version:
<img width="383" alt="Screenshot 2024-04-02 at 10 06 54 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/834bb9db-2f16-46c6-91b3-aa2855213a39">

Could someone please update the section for the Spanish page?

**Comment by RLHecht** [comment]
@randimays just updated the section so you should be good to go. Let me know if you need anything else.

**Comment by RLHecht** [comment]
Perfecto! Thanks for your work on this!

**Comment by randimays** [comment]
Wonderful, thanks @RLHecht! Closing as complete.
