### ISSUE TITLE
Service location: "Unspecified" online scheduling should map to NULL following migration 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17518]
## Description
Prosthetics and rehabilitation - Portland VA Clinic "Unspecified" online scheduling requirement maps to "No" in Tugboat following migration

[Tugboat FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/maine-health-care/locations/portland-va-clinic/)
[Tugboat CMS Service node](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/maine-health-care/locations/portland-va-clinic/prosthetics-and-rehabilitation)
[Prod FE](https://www.va.gov/maine-health-care/locations/portland-va-clinic/)
[Prod Service node](https://prod.cms.va.gov/node/64831/edit)

## Current behavior

<details>
<summary> Tugboat online scheduling service option </summary>

<img width="221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd5e78077fc4e949e03963ea97299881a72d56f8/image.png" alt="image.png" />

</details>

<details>
<summary> Tugboat FE display </summary>

<img width="687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a9799a238309774d93b4b55177135ae366cc16a/image.png" alt="image.png" />
</details>

---
<details>
<summary> Prod FE and CMS display </summary>

<img width="616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--791d17d788b17bdef957d8172f59bb82a33e2756/image.png" alt="image.png" />

<img width="396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--407963b608620f72e194e3c37d1fa1cbcc59d5d5/image.png" alt="image.png" />

</details> 

## Expected behavior
- OLD online scheduling = Unspecified, 2, [null]
- should map to NEW online scheduling = [null] in Drupal 
- should not be included in the front end display. 

## ACs
For "Is online scheduling available for this service?"
- If "Unspecified," "2," or [null] is selected, that maps to "null."
- Null should result in nothing displayed for online scheduling on the front end.

**Comment by davidmpickett** [comment]
This one is definitely unintended. In #16348 the new field was configured to allow "Yes" and "No" as valid options, but did not include "Unspecified." 

@omahane Do you remember if there was any discussion about this back when you worked on that ticket (or when Steve worked on the migration)? I didn't catch it in the PR, and the full list of options wasn't specified in the ACs, so might have just slipped through

**Comment by davidmpickett** [comment]
Update from a conversation @mmiddaugh and I had last week:
- Looking back on the [original use cases](https://www.figma.com/file/R06MIbS5jKqjZqY4UnTnTy/VA-Medical-Centers-forms?type=design&node-id=0-1&mode=design&t=2CE7YrAKDofju1p9-0), "unspecified" was intended to be an option to support temporary uncertainty during the initial set up of new services, not a valid long-term selection.
- As seen in [this report](https://prod.cms.va.gov/admin/content/facilities/vamc-facility-health-services?facility_title=&field_service_name_and_descripti_target_id=All&field_referral_required_value=All&field_walk_ins_accepted_value=All&field_online_scheduling_availabl_value=not_applicable&moderation_state=published&workbench_access_section__section=All), Currently 3000 / 14,000 (21%) of health services have this set as unspecified
- Because we are mapping this to a new field, we would have to intentionally add "Unspecified" as an option in this list. Rather than continue to allow for this exception from a required field, we should move towards a tighter content model.

## Option 1 - Map to [null]
- During migration, possible to have [null] values for required fields
- Because this is a required field, editors will have to select "Yes" or "No" the next time they edit the health service 
- Requires updating the migration
- Lighthouse push issue?

## Option 2 - Map to "No"
- Still doesn't show on the FE
- Current migration behavior, no changes needed

## Option 3 - Map to "Unspecified"
- Requires adding "Unspecified" as a distinct choice that will be a valid selection for future health services

**Comment by davidmpickett** [comment]
Per conversation with @mmiddaugh today, **Option 1 - Map to [null]** is the desired path

**Comment by xiongjaneg** [comment]
Audit view is where changes can be confirmed

**Comment by davidmpickett** [comment]
@omahane Ditto this one and accounting for "2" and [null]. "2" is currently mapping to [null], but [null] is mapping to "No"

**Comment by omahane** [comment]
@davidmpickett For my own sanity, where are there 2s at all (let alone thousands of them)?

Here's one example for reference:
https://prod.cms.va.gov/washington-dc-health-care/locations/franklin-street-va-clinic/mental-health-care

**Comment by davidmpickett** [comment]
Back in 2021, Steve [changed the value](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/a87c879b99d0405cff68aab786acbf109e70e46f) from `2` to `not_applicable`. (The label also changed from "Unknown" to "Unspecified"). 

It appears that rather than migrating the existing data into the new format, they simply opted to have the Front End treat `2` and `not_applicable` the same way. With this migration we will wipe that technical debt off the books ;)

**Comment by davidmpickett** [comment]
Confirmed on Tugboat

![Screenshot 2024-04-10 at 2 36 35 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2c38a768-8436-4047-9224-fc2744be9cc9)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/tampa-health-care/locations/temple-terrace-va-clinic/

![Screenshot 2024-04-10 at 2 40 26 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3d90de81-f967-4ff8-a5b8-507fda8724b2)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/charleston-health-care/locations/beaufort-va-clinic/

![Screenshot 2024-04-10 at 2 42 38 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/139f32e8-c329-4fd1-a9dc-3ad52d4cda81)



https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/wilkes-barre-health-care/locations/allentown-va-clinic/

**Comment by davidmpickett** [comment]
I also confirmed that Yes and No are still working as intended too

![Screenshot 2024-04-10 at 2 50 44 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/7471c858-161f-449a-ae8a-87c4b00a4bc2)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/battle-creek-health-care/locations/battle-creek-va-medical-center/

![Screenshot 2024-04-10 at 2 52 10 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/aa62adaa-9572-4ffb-8bb1-53721aee9f7c)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
