### ISSUE TITLE
Appointment phone number on VAMC facility health service duplicated on migration 

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17605]
## User Story or Problem Statement

When the migration ran today, it looks like it duplicated the Appointment phone number in some but not all cases. We need to understand if this was a fluke or if has the possibility of happening again.

![screenshot_2024-03-22_at_12 31 40___am](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/9c14b722-c215-4aaa-8697-5f9effcf95b9)

## Description or Additional Context 

https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/greater-los-angeles-health-care/locations/captain-rosemary-bryant-mariner-outpatient-clinic/primary-care

## Acceptance Criteria
- [ ] Migration has been run and tested to verify if behavior repeats and ticket has been cut to address any bug identified
- [ ] Add any notes about post-launch audit cleanup to the Launch ticket #16825

**Comment by davidmpickett** [comment]
Still happening in @omahane's updated version of the migration [as seen in this PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17703#pullrequestreview-1977122628) so this definitely needs a look
![Screenshot 2024-04-03 at 10 00 12 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/b60430e2-0be6-481f-894b-58ab901f61ee)

**Comment by jilladams** [comment]
To verify: can build in a new or clean env, run migration once. Verify on the example node. 
Run it again. Verify if we see the duping. 

This will help clarify if it's just an artifact of running this migration twice.

**Comment by omahane** [comment]
Actually, it's more complicated than that. I'm seeing services with duplicated numbers and services without duplicates.

# Duplicated phone numbers
- https://pr15622-jghdzknmoah3rsxdihibboelvhkdfu6h.demo.cms.va.gov/greater-los-angeles-health-care/locations/captain-rosemary-bryant-mariner-outpatient-clinic/geriatrics
- https://pr15622-jghdzknmoah3rsxdihibboelvhkdfu6h.demo.cms.va.gov/greater-los-angeles-health-care/locations/captain-rosemary-bryant-mariner-outpatient-clinic/blind-and-low-vision-rehabilitation

# Non-duplicated phone numbers
- https://pr15622-jghdzknmoah3rsxdihibboelvhkdfu6h.demo.cms.va.gov/greater-los-angeles-health-care/locations/captain-rosemary-bryant-mariner-outpatient-clinic/neurology
- https://pr15622-jghdzknmoah3rsxdihibboelvhkdfu6h.demo.cms.va.gov/greater-los-angeles-health-care/locations/captain-rosemary-bryant-mariner-outpatient-clinic/nutrition-food-and-dietary-care

**Comment by omahane** [comment]
I'm going to rebuild the environment.

**Comment by davidmpickett** [comment]
@jilladams Adding this to Sprint 1 since it's in progress, but this wasn't part of the Sprint commitment

**Comment by omahane** [comment]
# A wrinkle in testing
The environments don't seem to run the migration the same way, as the same health service on my local and [the service in Tugboat](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/physical-medicine-and-rehabilitation) have different numbers of phone numbers.
![Screenshot 2024-04-11 at 15 53 03](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/88f42c32-2483-459b-89c0-e1a0b4585ad6)

**Comment by omahane** [comment]
After rebase of `integration-service-location`, I began the Service location migration.

No noticeable dupes so far:
[Service locations audit | VA.gov CMS.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14961568/Service.locations.audit.VA.gov.CMS.pdf)

**Comment by omahane** [comment]
# We got dupes (right here in river city)
We ended up getting duplicates and I **think** I know why.

When I started the migration on Tugboat, everything was going great. I was checking the view of service locations audit, and I wasn't seeing any dupes. At some point, my computer screen saver turned on. When I unlocked the screen, the Tugboat terminal window was disconnected.

So I ran the drush script again to restart the migration from the location it was at when it stopped. It proceeded to run the migration from somewhere in the middle. 

Looking at the service locations audit, I found dupes (not among those health services with node ideas in the 300 or 400s). 

I reached out to Steve to talk through what I was seeing, and he had me look at the revision log, which showed 2 revisions among those nodes with dupes, at least 15 or 20 minutes apart. In talking it over, I came up with the following theory: Tugboat's terminal window is not the source of truth, regarding whether the script is running or not. When my browser window disconnected, the migration did not stop running. Thus, when I restarted the migration, even though it started somewhere in the middle, it was not the only instance of the script running. Both instances were running. And because there can be more than one phone number, the second instance of the script did not overwrite the old data but was appended to it. That's the theory, anyway.

All that being said, Steve has a module (codit_batch_operations) that he created out of the work he did at the very end of his stint on the VA to make the running of scripts more consistent and manageable. One of the key pieces of functionality is a browser-based logging, making it unnecessary to rely on the Tugboat terminal to determine the progress of the script. I have added it refactored our code slightly to use it. I am testing it locally.

**Comment by omahane** [comment]
# The bug was in our steps
When we found duplicate phone numbers in the Service locations audit, we thought there might be something awry in the migration script itself. The problem turned out to be that we were calling it more than once when our browser would disconnect from Tugboat. We assumed that in doing so, the script would stop running. But it keeps running to completion.

The duplicates happened because we would restart the script. It would appear to start in the middle of the group of items to update. While that was true, it was also true that the first script was continuing to run. Therefore, all services that the 2nd script changed had two revisions. In the case of phone numbers, that meant duplicates.

As long as we just run the script once, the script completes and only processes each service once.

I downloaded the results from a recent test on Tugboat, and found that of the 16,207 processed, all but 4 had the same phone information after migration. (We know there's going to be some minor cleanup after the migration).

![Screenshot 2024-04-16 at 14 35 40](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/b2c57a04-01d2-4cef-b0e7-547ba68c1395)
![Screenshot 2024-04-16 at 13 52 04](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/995cbc21-1a31-4c01-918c-efbcba042690)




# Codit Batch Operations slows to a crawl
In testing Codit: Batch Operations to better track logging and the starting/stopping of long-running scripts, I determined that it kept getting slower and slower the longer it ran. I created an issue to track this: https://www.drupal.org/project/codit_batch_operations/issues/3441186

**Comment by jilladams** [comment]
@omahane sounds like we now understand the dupes, how to prevent them when we migrate in production, and we don't need to write code to fix anything or to need to specific post-launch audits to account for this issue. I'm going to go ahead and close the ticket, but let me know if I've misunderstood anything and please reopen if so.
