### ISSUE TITLE
Determine Drupal and FE text for all Service Options

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17600]
## User Story or Problem Statement

This needs a lot more refinement, but basically we need to decide on the precise wording for all Service Option scenarios and confirm that they are working as intended

Pulling this example from #17566

- If an editor selects `Yes, on a first-come, first-served basis` for Virtual support, a corresponding message should be displayed. 
- @thejordanwood looks like the intention was Phone icon + "Call at your convenience"?

<details><summary>Tugboat FE and Drupal</summary>

![Screenshot 2024-03-20 at 3 42 01 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0bfd3a12-da8f-49bd-9a11-c5a09b6c58f2)

</details>

<details><summary>Design in Figma</summary>

![Screenshot 2024-03-20 at 4 03 09 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/98c47893-b20e-4300-815a-4ee0d91d820c)

</details>

## Acceptance Criteria
- [x] Wording recommendations are documented
- [ ] Wording recommendations are approved by Product and Design
- [x] Follow up Drupal and FE tickets are drafted

**Comment by eselkin** [comment]
Was there some difference between VAMC and VBA? I'm sure I saw the calendar icon and the wording somewhere. Maybe an earlier design?

**Comment by thejordanwood** [comment]
@davidmpickett I think there's been a mix up between all of the revisions we went through for this. Laura recommended that the wording we show in Drupal should be the same wording we show on the FE and I agree. Since the wording doesn't specifically say "phone" or "video call" anywhere, then I suggest we just use the calendar icon for virtual support. 

Here's my suggested wording to align FE with Drupal:

<img width="819" alt="Screenshot 2024-03-22 at 4 20 18 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/7f90880f-bee9-4b58-a716-f3b82246b845">

Note: The building icon is different than previous designs. I think this will be a later update, but the older icon isn't available to me in Figma anymore.

**Comment by davidmpickett** [comment]
Dredging up some historical context. Original recommendations were in Sharepoint. Here's a local copy of the relevant portion:

[VBA Service Delivery Options.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14749195/VBA.Service.Delivery.Options.xlsx)

**Comment by davidmpickett** [comment]
## DRAFT - Desired state for launch

Drupal selection | FE VBA | FE VAMC facility | FE VAMC top task
-- | -- | -- | --
Office visits - NULL | [No display] | [No display | [No display]
Office visits - No | [No display] | [No display] | [No display]
Office visits - Yes, by appointment only | Visit our office, by appointment only | Visit our office, by appointment only | [No display]
Office visits - Yes, ~~on a first-come, first-served basis~~ **no appointment necessary** | Visit our office, ~~first come, first served~~ **no appointment necessary** | Visit our office, ~~first come, first served~~ **no appointment necessary** | [No display]
Office visits - Yes, with or without an appointment | Visit our office, with or without an appointment |  Visit our office, with or without an appointment | [No display]
Virtual support - NULL | [No display] | [No display] | [No display]
Virtual support - No | [No display] | [No display] | [No display]
Virtual support - Yes, by appointment only | Schedule a virtual appointment | ~~Schedule a virtual appointment~~ Telehealth appointments available for some services | [No display]
Virtual support - Yes, ~~on a first-come, first-served basis~~ Veterans can call at their convenience | ~~Schedule a virtual appointment~~ **Call at your convenience** | ~~Schedule a virtual appointment~~ **Call at your convenience** | [No display]
Virtual support - Yes, with or without an appointment | Schedule a virtual appointment | Schedule a virtual appointment | [No display]

**Comment by jilladams** [comment]
@davidmpickett noting: new tickets go to the Icebox. pulling this over to UX refinement column on assumption that's correct since it's listed as launch blocking in the launch plan.

**Comment by mmiddaugh** [comment]
@davidmpickett 
suggestions for wordsmithing consideration: rather than "Telehealth appointments available for some services"
- "Telehealth appointments may be available" 
- "Virtual visit" rather than "Telehealth"?

**Comment by jilladams** [comment]
From UX sync: 
* Pulled into sprint 1
* Needs ACs
* Dave is going to try to finish this week, so we can cut Drupal / FE tickets to refine & pull into next sprint.

**Comment by davidmpickett** [comment]
[Shared in slack](https://dsva.slack.com/archives/C0FQSS30V/p1712951198246389) for Product and Design review

**Comment by mmiddaugh** [comment]
1. I agree with the following proposals
- The Drupal wording should match the FE wording for Editor usability 
- We do not need to change the Drupal interface for Virtual Support from radio buttons to check boxes 
- We do not need to show these options for VAMC top task pages (neither in Drupal nor to Veterans).

2. "Virtual support - Yes, by appointment only" 
- I'm concerned about "Schedule a virtual visit" as the recommended FE display 
  - it does not align with the Drupal text
  - it doesn't convey that an appointment is *necessary*, only that it is *possible* to schedule a virtual visit
  - it reads like a call to action and I have no knowledge of any method for Veterans to schedule a virtual visit for VA health online 
-> Suggest FE wording that aligns with both the Drupal UX and the proposed Office Visit FE display, such as "Virtual visits, by appointment only"

3. I'm concerned about the options for VAMC Virtual visits
- I appreciate the point about Veteran testing but the options are a miss from the business perspective. 
- PAOs need an option that accurately represents the reality that virtual visits *may* be available (based on the type of care needed or the provider's participation with telehealth). Otherwise they will be forced to make a decision on how to represent the availability of virtual services without an option that is accurate.  
-> Suggest adding an option to indicate virtual support *might* be available and make it available to both VAMC and VBA editors. It should be displayed on the FE accordingly, i.e., "Virtual visits may be available. Please call us to learn more." 

4. "Virtual support - Yes, with or without an appointment"
- As far as I know, we don't actually have a documented use case for this scenario
- It wasn't part of the prototype so hasn't been tested with Veterans
- There may be valid use cases for this option which we haven't yet encountered but I'm reluctant to include an option which *might* be needed, especially while ignoring an option with an established need. 
-> Suggest removing this option 

We certainly could come back and fix this later but if possible, I'd prefer we address these disconnects as quickly and simply as we can now before editors begin adding data that we have to unwind later.

**Comment by davidmpickett** [comment]
Updated draft

##  Desired state for launch - Office Visits

**Drupal selection** | **FE VBA** | **FE VAMC facility** | **FE VAMC top task** | Change explanation
-- | -- | -- | -- | --
Office visits - NULL | [No display] |  [No display | [No display] | No change
Office visits - No | [No display] | [No display] | [No display] | No change
Office visits - Yes, by appointment only | 🏢 Visit our office, by appointment only | 🏢 Visit our office, by appointment only | [No display] | No change
Office visits - Yes, ~~on a first-come, first-served basis~~ **no appointment necessary** | 🏢 Visit our office, ~~first come, first served~~ **no appointment necessary** | 🏢 Visit our office, ~~first come, first served~~ **no appointment necessary** | [No display] | This is the wording we used in the prototype for usability testing. It has been validated with users. The "first come, first served" language was never intended for FE display.
Office visits - Yes, with or without an appointment | 🏢 Visit our office, with or without an appointment |  🏢 Visit our office, with or without an appointment | [No display] | No change

## Desired state for launch - Virtual Support

**Drupal selection** | **FE VBA** | **FE VAMC facility** | **FE VAMC top task** | Change explanation
-- | -- | -- | -- | --
Virtual support - NULL | [No display] | [No display] | [No display]  | No change
Virtual support - No | [No display] | [No display] | [No display]  | No change
Virtual support - Yes, by appointment only | 🗓️  ~~Schedule a virtual appointment~~ **Virtual visits by appointment only** | 🗓️ ~~Schedule a virtual appointment~~ **Virtual visits by appointment only** | [No display] | More clearly indicating that appointments are required for virtual visits.
Virtual support - Yes, ~~on a first-come, first-served basis~~ **Veterans can call at their convenience** | ~~🗓️ Schedule a virtual appointment~~ **📞 Call at your convenience** | ~~🗓️ Schedule a virtual appointment~~ **📞 Call at your convenience** | [No display] | This icon and wording is what we validated with users during testing. 
**Virtual support - Virtual visits may be available** | **🗓️ Virtual visits may be available** | **🗓️ Virtual visits may be available** | [No display] | Add this option to allow for partial availability
~~Virtual support - Yes, with or without an appointment~~  |   ~~🗓️ Schedule a virtual appointment~~ | ~~🗓️ Schedule a virtual appointment~~ | [No display] | Remove this option - no use cases

**Comment by davidmpickett** [comment]
I've stubbed the two follow up tickets. Won't be able to finish refiing until we have final decisions here, but I think we're getting a decent sense of the size.
- #17843
- #17844
cc @jilladams

**Comment by davidmpickett** [comment]
@thejordanwood and @mmiddaugh have signed off on the updated proposal. Last step is getting @aklausmeier's sign off when she's back in the office tomorrow.

**Comment by davidmpickett** [comment]
Approved [in slack](https://dsva.slack.com/archives/C0FQSS30V/p1712951198246389)
