### ISSUE TITLE
FE Display of Non-Clinical Services on VAMC Top Task Pages should not be in a Card component

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17632]
## User Story or Problem Statement

In the tugboat Integration branch, non-clinical services on VAMC Top Task Pages are presenting inside a bordered box for Service Locations. This does not match the [current](https://www.va.gov/northeast-ohio-health-care/billing-and-insurance/#pay-in-person) design ( or [future design](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-Master?type=design&node-id=555-6767&mode=design), later).

## Description or Additional Context 

- https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/northeast-ohio-health-care/medical-records-office/#get-your-records-in-person
- https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/northeast-ohio-health-care/billing-and-insurance/#pay-in-person
- https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/northeast-ohio-health-care/register-for-care/#patient-registration-admission

<details><summary>SCREENSHOTS</summary>
Examples of 3 top task pages where the bordered box is visible, and needs to go away:
![screencapture-web-xptmfsnjoodldn85nzgkrgljqtfbz24b-ci-cms-va-gov-northeast-ohio-health-care-register-for-care-2024-03-25-22_08_15](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/01b372f7-dea8-43b5-b86b-e2a603283bab)

![screencapture-web-xptmfsnjoodldn85nzgkrgljqtfbz24b-ci-cms-va-gov-northeast-ohio-health-care-billing-and-insurance-2024-03-25-22_08_07](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/69acf3b9-7f5a-425a-8e71-a5f1b4f648e5)

![screencapture-web-xptmfsnjoodldn85nzgkrgljqtfbz24b-ci-cms-va-gov-northeast-ohio-health-care-medical-records-office-2024-03-25-22_07_56](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/16b94a60-3bd7-4f5d-9443-3e0d25c6929a)
</details>

## Acceptance Criteria
- [x] Non-clinical service locations do not use the card component/border on these templates
  - [x] Billing and Insurance
  - [x] Medical Records
  - [x] Register for Care
- [ ] Requires design review

**Comment by jilladams** [comment]
This is in PR. 
The Tugboat FE needs to be built from the PR branch in order to QA for merge. 
That is queued behind Christian's rebuild for the Unspecified = NULL migration fix.

**Comment by thejordanwood** [comment]
I reviewed [the PR for this](https://github.com/department-of-veterans-affairs/content-build/pull/2024) and have approved it. 

Following up on spacing: @eselkin Thanks for bringing up in scrum that the space between the location header and the facility address is 48px instead of the 45px specified in the design mockup. In this case, I'm fine with the difference since the VADS ecosystem doesn't have the 45px spacing.

**Comment by laflannery** [comment]
I just want to note here for reference because it seems as thought [my direction on the PR ](https://github.com/department-of-veterans-affairs/content-build/pull/2024#pullrequestreview-2017228229) looks to be in contrast to Jordan's comment above. 

I am working on off [this Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-Master?node-id=550%3A10920&mode=dev) in which the space between the Facility address and the "Location" header is 24px, which us just about [the standard DS spacing](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=539-888&mode=design&t=SWI8gRZaBVVYyIZU-0) (they actually state it should be 25.5px)
![Screenshot 2024-04-23 at 12 04 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/ca3616b8-2acb-48d7-af57-dcec48d11033)

This is why I have recommended in my comment we remove the extra large spacing and custom spacing I was seeing and stick instead with the standard DS spacing.

**Comment by davidmpickett** [comment]
This ticket was not supposed to include altering any spacing. it was only supposed to be about removing the border. I apologize for linking to a speculative WIP design as reference. By default, these should match the current spacing on Prod (which is 25.5)

![Screenshot 2024-04-23 at 6 47 30 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d0c8b3a3-bbba-4371-978c-50f6288204c5)

**Comment by davidmpickett** [comment]
Last step is verifying this on SL tugboat after the migration finished and Content Release runs

**Comment by davidmpickett** [comment]
Confirmed on Tugboat
![Screenshot 2024-04-29 at 10 01 46 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/de8e50bb-48f4-4033-aa62-c0e1572af403)
![Screenshot 2024-04-29 at 10 02 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d3e87b8b-0724-477f-9d4e-9e3ecbc21b62)
