### ISSUE TITLE
[SPIKE] Forms controller: investigate calls to BGS/Claims service 

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17638]
## Description
Discovery by chatting with the Platform team and doing research.
- Timeboxed at a 3

The Forms controller has experienced 3 recent spurts of monitoring errors, when the  BGS/Claims service is unavailable. 

During those windows, as far as we are aware, the Lighthouse Forms APi was up, and returning 200s. Meaning: the vets-api layer shut down API responses, and Veterans received errors. 

**What's happening / why:**
The Platform Support team helped explain that within vets-api, when a service is detected as down, if any endpoints call that service, vets-api will temporarily shutdown service calls: 
> breakers is a middleware that we use with Faraday to make requests to external services through the fwdproxy (think of it just like a circuit breaker would work). If too many error responses are returned (the default is 50% error rate), then the breaker goes up. Every 60 seconds, requests will check for success status of the service and allow a few requests to go through. We manage breakers internally and there's additional info in the readme here: https://github.com/department-of-veterans-affairs/breakers.
> the breaker will go up for that downstream service. Anything that calls it (multiple endpoints) will all return errors
> If your endpoint calls a given service, it will be affected, if not, it won't be. Breakers is supposed to alleviate cascading latency issues across all of [va.gov](http://va.gov/). If requests are taking longer, the puma backlog will fill up causing the entire site to become latent Breakers will automatically return error responses for these services to avoid said latency, avoiding long hanging threads.

**Implication:**
Somewhere in the Forms controller, we appear to be calling the BGS/Claims service. When it's down, even though the Forms API is up and responsive, our API calls are shut down at the vets-api layer. 

We want to understand why we call BGS/Claims, and if there is a path to being more resilient to its outages. If we don't need the call, we could avoid these outages. 

### Related monitoring / Slack threads
Timestamps: 
* Mar 16, 4:13 pm PT – Mar 16, 6:43 pm (PT)
    * https://dsva.slack.com/archives/C063TF8RJS2/p1710783517468119
    * https://dsva.slack.com/archives/C05THHJHH2R/p1710783045596029?thread_ts=1710773095.095059&amp;cid=C05THHJHH2R
* Mar 23, 8:50 pm – Mar 24, 12:47 am (CT)
    * https://dsva.slack.com/archives/CUB5X5MGF/p1711375389434959 
    * https://dsva.slack.com/archives/CUB5X5MGF/p1711375389434959
* Mar 25, 4:29 pm – Mar 25, 4:43 pm (PT)
    * https://dsva.slack.com/archives/C05THHJHH2R/p1711409538595139
* Platform support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1711468698967449

### Related documentation
https://github.com/department-of-veterans-affairs/breakers

## ACs
- [ ] Understand and document in ticket the calls to BGS/Claims service, in order to understand if we can be resilient to the service's outages
  - [ ] Understand how the call to the Faraday middleware comes into play (we don't actually reach explicitly past that out to BGS/Claims anywhere. So that middleware call is likely the culprit here, and we need to understand what's implied by it.)

**Comment by jilladams** [comment]
From scrum: we just call the Faraday middleware, we don't actually reach explicitly past that out to BGS/Claims anywhere. So that middleware call is likely the culprit here, and we need to understand what's implied by it.

**Comment by randimays** [comment]
Pulling in as stretch on 4/12

**Comment by randimays** [comment]
Update: New Platform support thread here: https://dsva.slack.com/archives/CBU0KDSB1/p1713283630966809

Summary so far: 

I have thoroughly searched vets-api in both the forms and the claims applications to try to identify any connection between the two. The Faraday configuration for both services seem generic and there is no obvious link between these services (as identified in the description of this ticket).

I did a quick search in Datadog to confirm there have been no new Forms service issues relating to the BGS/Claims service since March 25 ([Datadog logs here](https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20operation_name%3Arack.request%20resource_name%3A%22V0%3A%3AFormsController%23index%22%20service%3Afind-a-form%20status%3Aerror%20&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&refresh_mode=paused&shouldShowLegend=true&sort=time&spanType=all&spanViewType=errors&traceQuery=&view=spans&start=1711342860000&end=1713285060000&paused=true)).

We are still fairly certain the issue exists within the Faraday/breakers middleware and are asking for Platform's help in untangling the two services.

**Comment by randimays** [comment]
Kristen Brown jumped into the support thread posted above ([her comment here](https://dsva.slack.com/archives/CBU0KDSB1/p1713289737285289?thread_ts=1713283630.966809&cid=CBU0KDSB1)). 

In short, her team's (Appeals API) service also had BGS/Claims errors during the timeframes we saw them. Her team discussed this with the Lighthouse team that owns the BGS/Claims service, and the BGS/Claims team [pushed a fix](https://github.com/department-of-veterans-affairs/vets-api/pull/16075/files). This was merged in on March 26. The last day PW saw BGS/Claims errors was March 25.

@FranECross @jilladams It sounds to me like we don't need to make any code changes or further Platform requests here. I think we can continue to monitor the Forms API and escalate any issues like this to the proper LH team (if applicable), and close this spike. Thoughts?

**Comment by FranECross** [comment]
@randimays Thanks for this information. During your investigation, were you able to determine if we actually need to call the BGS/Claims service? I think the concern is that if we don't actually need to call it, could we remove that linkage and not run into issues in the future if there are problems with it. 

I do agree that it sounds like the underlying issue was more than likely fixed by the update they did, though. @jilladams thoughts? Should be mothball this ticket for now and revisit later, when we don't have as many other more urgent or pressing things to address?

**Comment by randimays** [comment]
@FranECross Oops, apologies for not bridging the gap here. The issue was ultimately completely upstream; we don't have any code that calls the BGS/Claims service; it was integrated by mistake. This is what the Lighthouse BGS/Claims team said re: their fix:

> The issue with the BGS/Claims error should be resolved. Caseflow and the BGS service we use had identical matchers so we were essentially enabling the breakers if either event were to acknowledge down time. We had a fix go out today to focus specific to the port we require as well, which will eliminate said issue.

Caseflow is specific to the Appeals team, so I think the thing that fixed us was BGS/Claims specifying the port BGS/Claims requires. Somehow the BGS/Claims service was being treated as an upstream dependency for many completely unrelated services, and should be fixed now. No code action is needed on our end.

**Comment by jilladams** [comment]
Agree! Closing.
