### ISSUE TITLE
Research Discovery: Vet Centers 2.0 & VBA events

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17667]
### User story
**AS A** Researcher
**I WANT** to review what we learned in past Vet Center, VBA, and VA research
**SO THAT** we can identify knowledge gaps

Discovery is a time to establish the fundamental approach for a research initiative. Potential tasks may include the following:

**What do we want to know?**
- [x] Align with Sitewide UX Lead, Product Manager, and Product Owner on the high-level purpose and scope of the research
     - Scope: This research discovery should focused on a broad Vet Center redesign, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17661 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17665.
- [x] Review Product Outline to understand background context
     - [Vet Center product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/product-brief.md)
     - [VBA RO product brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices)
- [x] Draft big picture research questions
     - Identified knowledge gaps and research questions for [Vet Center/VBA events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis/Vet%20Center%20%26%20VBA%20RO%20events.md) and [expanding satellite locations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis/Expand%20satellite%20locations.md)

**Has anyone else researched this before?**
- [x] Review previous research on this product 
     - [Vet Center research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/research)
- [x] Review Research Repo for previous relevant research from other teams 
     - [VA research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)
     - [CMS research repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research)
- [x] Summarize findings from research review
     - Finding are in a [secondary research synthesis Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis)

**How might we learn more?**

Note: This discovery work covered a wide range of potential updates to Vet Centers/VBA regional offices. Knowledge gaps have been identified. Further consideration for methodologies, participants, and timelines can be explored at a later date when this work is prioritized. 

- [ ] Consider methodologies - do we have the right tools to build a useful prototype?
- [ ] Consider participants - do we have access to the right users?
- [ ] Consider timeline - how long will this take? how much time do we have?

## Acceptance Criteria
- [x] Findings from research review are documented [in Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis) 
- [x] Findings are reviewed by Sitewide and VA UX Lead
- [x] Updates are made based on feedback
- [x] Findings are shared with PM/PO
- [ ] ~~High-level scope of research is drafted and agreed upon~~
- [ ] ~~Subsequent tickets are created~~

**Comment by jilladams** [comment]
@thejordanwood I just slapped the template contents in here. Customize at will.

**Comment by aklausmeier** [comment]
Previous [Vet Center Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/research)

**Comment by aklausmeier** [comment]
@thejordanwood For scope clarity, research discovery is focused on a broad Vet Center redesign, [Epic - Vet Center design 2.0 #17661](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17661) and [VBA Events #17665](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17665).

One hypothesis we should explore: Vet Centers have their own logo, likely this may need to stay present in some form on the redesign as Veterans have a sense of trust and safety in seeking mental health support.

**Comment by davidmpickett** [comment]
@thejordanwood has capacity this sprint to look broader than just events, so this may cover https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17661 as well

**Comment by aklausmeier** [comment]
@thejordanwood There is no right or wrong way to summarize secondary research findings but what might be helpful if this is handed off to another researcher is a one pager in a GitHub research folder which we could always link to a Mural. Let me know if you have questions along the way!

**Comment by aklausmeier** [comment]
VBA Events - [Honolulu use case example](https://www.benefits.va.gov/honolulu/), scroll down to see the type of events they hold

**Comment by davidmpickett** [comment]
Note from this morning's UX Scrum. Because #17713 was injected into this sprint and is time sensitive, @thejordanwood may not be able to complete this ticket in Sprint 1. Will have a better sense at mid-sprint next week, but communicating early and often for no surprises.
cc @mmiddaugh @jilladams @aklausmeier

**Comment by thejordanwood** [comment]
I've compiled this research discovery work into [a Sharepoint doc](https://dvagov.sharepoint.com/:w:/r/sites/SitewideFacilitiesTeam/Shared%20Documents/UX%20Research/Research%20discovery%20for%20Vet%20Centers%20%26%20VBA.docx?d=w88694408c10346a880cfad3598de2053&csf=1&web=1&e=hcJjCT).

**Comment by mmiddaugh** [comment]
@thejordanwood thank you for diving headfirst into these topics!
Regarding [Satellite location knowledge gaps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis/Expand%20satellite%20locations.md#knowledge-gaps) - apologies - I should have given more context 

<details>
<summary> Problems to solve </summary>

- Background: Outstations are smaller versions of a Vet Center, with at least one full-time counselor providing services in a VA owned/operated physical space. Community Access Points (CAPs) offer Vet Center services on a part-time basis (such as once weekly or monthly) using rented space in the community, such as inside other VA facility, VFW, or church. 
- Today, Vet Center editors do not have a way to indicate the services available or details about the ways the service is delivered, such as evidence based modalities or support groups for either of these types of locations. This creates two problems. 
     - If I search for Vet Centers in the Facility Locator, I might find an Outstation in the search results but the card links to the Locations page for its main Vet Center. The Outstation is listed as a location only, without any information about the services available or how to prepare to visit the location. CAPs are also listed as locations on the main Vet Center Locations page but are not surfaced in Facility Locator search results at all. 
    - If nothing changes, in the future when we are able to integrate the full list of services from CMS into the Facility Locator, a Veteran searching for Mental Health services will see the closest Medical Center, Clinic, and Vet Center offering the service in the search results. Neither the Outstation in the next town where counselors are available daily nor the CAP down the block where counselors provide services once a week would be included. 
 </details>

---

**Knowledge Gaps**

<details>
<summary> "It’s unclear what the impact will be to IA when satellite locations pages are more prominent."</summary> 

- My assumptions is that some, if not all, Outstations should have their own page, like the main Vet Centers. This would support Veteran discovery of these locations and their understanding of the services available. 
   - If these pages existed, would it make sense to leverage a slim version of the VAMC secondary navigation menu (i.e. Locations section)?
- Community Access Points should not have their own pages because it would be a significant editorial effort to create and maintain a page for locations which are not permanent. 
  - However, it could be valuable to associate services with these locations. Would it make sense to this leverage the "Available at these locations" VAMC pattern or service delivery locations? 
  - How might secondary navigation support these locations?
</details>

<details>
<summary> "Do Veterans understand the structure of satellite location pages?"</summary>

- Assuming Outstations follow the same page format as a Main Vet Center page, we can assume they will understand the structure of the page. 
- If we're able to associate services with CAPs in some way, we will want to validate that our design supports Veteran understanding of what services are available, when, and where - especially because CAPs operate part-time at a community location and we need to avoid situations in which a Veteran drops by a church, VFW or other location expecting a particular service to be available every day. 
</details>
<details>
<summary> "Do Veterans understand why some satellite locations have daily hours and a full suite of services while others don’t?" </summary

- Past research finding from the Vet Center detail page usability study (non-client), Jan 2021: “Participants understood “Satellite locations” as related to the main location and that they are often smaller and with a reduced service offering than its parent location.”
- The relationship between an Outstation and Main Vet Center is similar to that of a VA Clinic associated with the main large Medical Center, such as Kernersville VA Clinic and [W.G. (Bill) Hefner Salisbury Department of Veterans Affairs Medical Center](https://www.va.gov/salisbury-health-care/locations/wg-bill-hefner-salisbury-department-of-veterans-affairs-medical/). Given the number of Veterans who experience this in their healthcare journey and the prevalence of satellite locations in other industries (i.e., main Bank branch vs community location), we can make the assumption that Veterans understand that satellite locations typically have a subset of services or less daily availability than main locations. 
- As of April 2024, there are 21 Outstations nationwide with six new locations planned this year. Only 1 or 2 Vet Centers have more than one Outstation. Veterans are unlikely to have the opportunity to compare what is available at one location vs another. 
   - </details>

**Comment by mmiddaugh** [comment]
@thejordanwood thank you for diving headfirst into these topics!

For background on the Veteran journey and the services provided by Vet Centers, I highly recommend the following short videos:
- [Vet Center Services](https://www.youtube.com/watch?v=VMzkZNbKk1I)
- [Vet Center testimonials](https://www.youtube.com/watch?v=4nH815Hsq04)

<details> 
<summary> For context: a summary of problems to solve </summary>

- Background: Outstations are smaller versions of a Vet Center, with at least one full-time counselor providing services in a VA owned/operated physical space. Community Access Points (CAPs) offer Vet Center services on a part-time basis (such as once weekly or monthly) using rented space in the community, such as inside other VA facility, VFW, or church. 
- Today, Vet Center editors do not have a way to indicate the services available or details about the ways the service is delivered, such as evidence based modalities or support groups for either of these types of locations. This creates two problems. 
     - If I search for Vet Centers in the Facility Locator, I might find an Outstation in the search results but the card links to the Locations page for its main Vet Center. The Outstation is listed as a location only, without any information about the services available or how to prepare to visit the location. CAPs are also listed as locations on the main Vet Center Locations page but are not surfaced in Facility Locator search results at all. 
    - If nothing changes, in the future when we are able to integrate the full list of services from CMS into the Facility Locator, a Veteran searching for Mental Health services will see the closest Medical Center, Clinic, and Vet Center offering the service in the search results. Neither the Outstation in the next town where counselors are available daily nor the CAP down the block where counselors provide services once a week would be included. 
 </details>

---

[Knowledge gaps from the secondary research synthesis on expanding satellite locations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis/Expand%20satellite%20locations.md#knowledge-gaps)
<details>
<summary> "It’s unclear what the impact will be to IA when satellite locations pages are more prominent."</summary> 

- My assumptions is that some, if not all, Outstations should have their own page, like the main Vet Centers. This would support Veteran discovery of these locations from the Facility Locator and ability to learn about and understand the services available. 
   - Vet Centers currently have only Main and Locations pages. Given this, they do not currently have a secondary navigation menu. How can we support the discovery of these locations and navigation from Vet Center main pages to individual pages for associated Outstations? Would it make sense to leverage a slim version of the VAMC secondary navigation menu (i.e. Locations section)?
  - Only 14 of the 300 Vet Centers have associated Outstations. 3 Vet Centers have 2 Outstations. How might a secondary navigation support this scenario?
- Community Access Points should not have their own pages because it would be a significant editorial effort to create and maintain a page for locations which are not permanent. There are 528 Outstations, across 181 Vet Centers, as of April 2024. On average, Vet Centers have three CAPs. 19 Vet Centers have six or more CAPs. Scranton Vet Center has 18. 
  - However, it could be valuable to associate services with these locations. How might we easily allow editors to indicate the services available? Would it make sense to leverage the "Available at these locations" VAMC pattern or service delivery locations? 
  - How might secondary navigation support these locations?
</details>

<details>
<summary> "Do Veterans understand the structure of satellite location pages?"</summary>

- Assuming Outstations follow the same page format as a Main Vet Center page, we can assume they will understand the structure of the page. 
- If we're able to associate services with CAPs in some way, we will want to validate that our design supports Veteran understanding of what services are available, when, and where - especially because CAPs operate part-time at a community location and we need to avoid situations in which a Veteran drops by a church, VFW or other location expecting a particular service to be available every day. 
</details>

<details>
<summary> "Do Veterans understand why some satellite locations have daily hours and a full suite of services while others don’t?" </summary

- Past research finding from the Vet Center detail page usability study (non-client), Jan 2021: “Participants understood “Satellite locations” as related to the main location and that they are often smaller and with a reduced service offering than its parent location.”
- The relationship between an Outstation and Main Vet Center is similar to that of a VA Clinic associated with the main large Medical Center, such as Kernersville VA Clinic and [W.G. (Bill) Hefner Salisbury Department of Veterans Affairs Medical Center](https://www.va.gov/salisbury-health-care/locations/wg-bill-hefner-salisbury-department-of-veterans-affairs-medical/). Given the number of Veterans who experience this in their healthcare journey and the prevalence of satellite locations in other industries (i.e., main Bank branch vs community location), we can make the assumption that Veterans understand that satellite locations typically have a subset of services or less daily availability than main locations. 
</details>

---

**[Knowledge gaps from the secondary research synthesis on Vet Center & VBA RO events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis/Vet%20Center%20%26%20VBA%20RO%20events.md#knowledge-gaps)**
<details>
<summary> "There isn’t a clear understanding of how Vet Centers and VBA Regional Offices would use events. Are these events different than VAMCs? Do satellite locations and mobile Vet Centers have different event needs than regular Vet Centers?" </summary

Vet Centers
- I'd suggest reviewing the use cases for Vet Centers described in [Initiative - Events for Vet Centers #12926](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/12926). 
- If you have additional questions, I already have approval for us to leverage Vet Center office hours to gather additional insight. I also have approval for you to interview two specific Vet Center Outreach Specialists who have been given additional duties supporting RCS. 
- Existing Vet Center pages may have event information in their spotlights but past events have not been archived. 

VBA Regional Offices
- Suggest reviewing [Phoenix](https://www.benefits.va.gov/phoenix/), [Honolulu](https://www.benefits.va.gov/honolulu/), [San Juan](https://www.benefits.va.gov/sanjuan/), [Oakland](https://www.benefits.va.gov/oakland/), [San  Diego](https://www.benefits.va.gov/sandiego/)
- If more details are needed, we can start by leveraging Training sessions to learn more about VBA event needs. 
</details>

<details>
<summary> VBA Regional office page event examples </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/f0d2c3b2-4963-4c6a-8c1a-78c67e1b47fb)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/2c411011-d4d0-4419-91ea-46b32dbaf5ee)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/c076995a-c329-4f8e-ba00-0cbc92cd9091)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/9f43db11-cdf8-4fe2-8376-971f185630e0)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/04594954-d2bb-4375-8ab6-13c3b61f8b49)

</details>

**Comment by aklausmeier** [comment]
@davidmpickett see Michelle's comment above regarding satellite locations and IA, this will likely be most of what you are looking for regarding #17696

**Comment by aklausmeier** [comment]
An interesting event use case: Some of the Phoenix ones are VAMC events but VBA list them as events they will have presence at. One event but ability to populate across multiple facilities: VAMC and VBA RO.

**Comment by mmiddaugh** [comment]
@thejordanwood @aklausmeier @davidmpickett @jilladams 
At this time, this redesign should limit event scope to determining how Veterans will navigate from the main Vet Center page to Events (which is being handled by PW) - this part of the design can be implemented in the front end once we are able to open events to Vet Center editors

**Comment by thejordanwood** [comment]
Thanks for the additional context @mmiddaugh! This is all very helpful.

**Comment by davidmpickett** [comment]
@mmiddaugh @jilladams @aklausmeier @thejordanwood 

In the interest of scoping this ticket to close in Sprint 1, I'm recommending we strike the following ACs
- [ ] ~~High-level scope of research is drafted and agreed upon~~
- [ ] ~~Subsequent tickets are created~~

My rationale is that these two actions are more properly Product / UX Lead actions as a follow on from Jordan's initial Research Review documented here. Some of the clarifications on Scope and open questions should probably be migrated to Product Artifacts like the [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-centers-2.0/initiative-brief.md) and [relevant epics](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17661) before we get into drafting tickets.

 I'm going to put this on the Agenda for UX Sync later this week.

**Comment by jilladams** [comment]
@davidmpickett I am ok with that if Amanda is, with the understanding that you own next steps for UX Sync discussion. Holler if you need support on ticketing / initiative brief edits.

**Comment by jilladams** [comment]
From discussion with Amanda / Dave: next steps:
* Dave / Jordan to work together on defining a UX/Product workshop to clarify knowledge gaps & define black/white for next steps & scope of the project
    * Jordan is fully booked in Sprint 2 on the typography audit + PTO
* Background information provided in ticket comments here should be incorporated into artifacts
* Jill to work on updating https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-centers-2.0/initiative-brief.md

**Comment by mmiddaugh** [comment]
Given staffing and competing priorities, I encourage us to design with best bets based on what is known when we return to this initiative. If there are critical gaps, we can leverage Vet Center office hours and limited interviews with identified stakeholders.

**Comment by davidmpickett** [comment]
I discussed this with both @aklausmeier and @thejordanwood today and we are going to close this ticket to represent that Jordan's research synthesis was delivered. @thejordanwood  are jointly working on defining follow-up steps and creating tickets for them. 

We'll talk through this more in UX Sync tomorrow
