### ISSUE TITLE
[EPIC] Accommodate new 640px breakpoint & deprecation of 768px breakpoint

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17746]
## Description
The Design System Team will be deprecating the 768px breakpoint and adding a 640px breakpoint (tentatively) in mid-August.

We need to ensure this change doesn't adversely affect any Public Website managed features/apps/products.

### User story

**AS A** PO/PM for Public Websites apps/features/products
**I WANT** to ensure we accommodate the deprecation of the current 768px breakpoint and addition of a new 640px breakpoint
**SO THAT** Veterans, their caregivers, family and survivors continue have a good experience when in VA.gov

## Acceptance criteria

- See individual tickets for AC

**Comment by FranECross** [comment]
@thejordanwood @jilladams Isn't it true that even if a very small population of users of our products actually use the 768px breakpoint that is being deprecated, we would still need to test every screen of our products on the new 640px breakpoint, or am I overthinking things? Thanks.

**Comment by jilladams** [comment]
I'd expect most products to need at least some tweaking for a new breakpoint. 

If we went full laissez faire: Technically speaking, I don't know what happens if 640px ships / 768 gets deprecated without us doing anything. That's a question for FE eng, probably. If it's technically feasible to let that happen without any explicit intervention on our part, it's a conversation with PO re: whether we're comfortable handling any fall out in prod once it's identified. Typically no. 

A creative way to think about it might be: is there a way to build the 640 breakpoint / remove 768 in a lower environment and just see what happens? We can spot check and flag totally broken things that need big help vs. things that are mostly ok. I've not worked on a project where we added a new breakpoint in ages -- @FranECross this might be a great thing to tap the Product COP at A6 about and see if folks have suggestions on how we could strategize handling it.

**Comment by jilladams** [comment]
(Also curious about Jordan's POV)

**Comment by FranECross** [comment]
@jilladams Thanks so much for your reply and suggestions. I'll bring it up in the Product COP to see what they say.

**Comment by FranECross** [comment]
@thejordanwood Thanks so much for your feedback and offer to test on the lower environments. Do you feel that wireframes/mockups are actually needed, or testing and then tweaking as necessary would cover it?  I ask because maybe I can repurpose the existing wireframe ticket to be a testing ticket for you, with findings as the AC. cc @jilladams

**Comment by thejordanwood** [comment]
@FranECross It's hard to say. For bad cases, a wireframe/mockup might still be needed.

**Comment by FranECross** [comment]
Thanks, @thejordanwood ! I'll create a testing ticket for you to fit into an upcoming sprint, if possible.

**Comment by jilladams** [comment]
Closing this. We've decided we'll work on adopting the 640 breakpoint for all our products, when we move everything over to Accelerated Publishing templates.

**Comment by FranECross** [comment]
I'll close the linked tickets as well, and we can create any new needed in future.
