### ISSUE TITLE
[FE 640px] Stand-up a branch with 640px breakpoint to enable testing

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17775]
## Status
**[2024-4-17]** Testing won't begin until Sprint 3.

## Description

In support of Jordan testing the upcoming new 640px breakpoint, make a branch with the $medium-screen variable changed to 640px. An assumption [broached to Micah here in Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1712600577344609?thread_ts=1712600088.087039&cid=C01DBGX4P45), is that all of the web components will be adjusted from that also.

### User story

**AS A** Veteran, their caregiver, family member or survivor viewing products, features and apps (that the Public Websites Team manages) at a 640px breakpoint
**I WANT** to be able to view and utilize all features (buttons/links/etc.) everything without issues
**SO THAT** I have an excellent experience in VA.gov and my trust in the website is not eroded

## Acceptance criteria

- [ ] Make a branch with the $medium-screen variable changed to 640px
- [ ] Share information with Jordan Wood, Fran Cross, and Jill Adams

**Comment by jilladams** [comment]
We have opted to deprioritize the breakpoint audit until after typography review.

**Comment by randimays** [comment]
@jilladams @FranECross Should this be in the "Ready" column instead?

**Comment by jilladams** [comment]
good call, moved back to Ready and it's already tagged later into Sprint 5.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C03R5SBELQM/p1717088433049829

The new 640px breakpoint is now available for use. In order to use it, teams can follow the same convention currently in place for accessing shared Formation variables by importing our design tokens into your application's stylesheet:

`@import "~@department-of-veterans-affairs/css-library/dist/tokens/scss/variables";`

and then using its token name, $tablet , for example:
```  @media (min-width: $small-screen) and (max-width: $tablet) {
    .usa-content,
    .va-nav-breadcrumbs {
      padding-left: 0.9375rem;
      padding-right: 0.9375rem;
    }
  }```

Not sure the implications for us standing up an environment to test in, when the time comes, just noting the guidance while it's fresh.

**Comment by FranECross** [comment]
Per Jill Adam's note in the Epic: Closing this. We've decided we'll work on adopting the 640 breakpoint for all our products, when we move everything over to Accelerated Publishing templates.
