### ISSUE TITLE
Update Drupal UI for Phone number in Staff profile content type

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17860]
## Description
In order to make it easier for editors to enter their phone number correctly, we want to convert this single Telephone number field to use the Phone paragraph type field, which uses separate fields for the phone and extension.

## Background
Currently the Phone number field in the Staff profile content type is using the Telephone number field type. This is a single field for the editor to enter the phone number information as well as any applicable extension information.  However, phone numbers and extensions require specific formatting in order to meet VA guidelines and to display and function properly on the FE. 

### Additional Notes
- We do not need any additional help text besides the default
- Please hide the **Label** field so that this is not available to editors, we do not need this because we are going to just keep the hardcoded label on the FE

```[tasklist]
### Acceptance Criteria
- [ ] Phone number field on Staff profile content type uses the Phone paragraph type
- [ ] Label field is hidden in Drupal UI
```

```[tasklist]
### Drupal - Field Migration
- [ ] Script is written to migrate Staff profile content type phone numbers from field to paragraph.  Can use https://www.drupal.org/project/codit_batch_operations.
- [ ] Cardinality for phone_number paragraph type on Staff profile content type is set to 1
- [ ] 'Label' field on phone_number paragraph type is hidden on Staff profile content type Node:Edit
- [ ] Current`field_phone_number` is hidden but not removed
- [ ] Update phone number audit view to display phone paragraph type field AND the Telephone number type field (in order to compare values before and after migration)
- [ ] Migration is tested and validated
- [ ] Manual Code review
- [ ] CMS PR is created and approved but not merged
```

**Comment by davidmpickett** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/17860?planning-poker) with Zenhub @dsasser @jv-agile6 @omahane

**Comment by dsasser** [comment]
## Engineering Pre-Refinement Notes:

There are 5774 phone numbers to migrate:

```sql
select count(*) from node__field_phone_number nfpn
where nfpn.bundle = 'person_profile';
```

Source phone numbers are not in a standard format, eg:
801-582-1565, ext. 4557)
+1-801-582-1565, ext. 2764

The destination paragraph breaks out phone number and extension into separate fields, field_phone_extension, and field_phone_number.

field_phone_number is standardized in the format nnn-nnn-nnnn

field_phone_extension is not standardized. Existing examples from other entities:
6632 or 6801
4 then 2
Select 3

There are going to be GraphQL changes which means there is also a FE component to this work. See [this](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17861#:~:text=This%20is%20our%20standard%20order%20of%20operations%20for%20migrating%20Drupal%20fields%20that%20are%20part%20of%20GraphQL%20queries).

**Comment by davidmpickett** [comment]
> field_phone_extension is not standardized. Existing examples from other entities: 6632 or 6801 4 then 2 Select 3

We have [a ticket to standardize the extension field](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17863) to prevent non-numeric characters. Should that be a blocker for this ticket? Or could they happen in either order?

**Comment by dsasser** [comment]
> > field_phone_extension is not standardized. Existing examples from other entities: 6632 or 6801 4 then 2 Select 3
> 
> We have [a ticket to standardize the extension field](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17863) to prevent non-numeric characters. Should that be a blocker for this ticket? Or could they happen in either order?

I don't have a strong preference, but If we do #17863 first, we'll have to add additional work here to standardize the extension during the migration, which could add heft to this ticket.

**Comment by omahane** [comment]
Does this hide the old phone field?
Does this remove data from that field?
Does this remove the field?

**Comment by dsasser** [comment]
[Slack](https://dsva.slack.com/archives/C03LFSPGV16/p1724173787339299) discussion on phone and extension extraction logic.

**Comment by dsasser** [comment]
## Notes

@davidmpickett suggests we pick up [17861](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17861) & [17862](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17862) before tackling this one. They each deal with migrating ~100 phone numbers as opposed to the ~5000 this ticket does.

**Comment by dsasser** [comment]
> ## Notes
> @davidmpickett suggests we pick up [17861](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17861) & [17862](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17862) before tackling this one. They each deal with migrating ~100 phone numbers as opposed to the ~5000 this ticket does.

We ended up starting with this ticket.

**Comment by jilladams** [comment]
Work is done.
Needs QA, and a suggestion was made to break out Phone number QA into its own ticket to handle all 3 changes together. @Agile6MSkinner to make a QA ticket, for Sprint 12 if we can.
Will need an integration branch to stage it. @dsasser to handle, and set up a Tugboat.

**Comment by dsasser** [comment]
## Mid-sprint Update

This work is in PR review and pending [review](https://dsva.slack.com/archives/CT4GZBM8F/p1725985848690919) by the CMS platform team. While awaiting review, we are unable to merge other phone tickets since they are also based on the changes from this work, the first PR in the group.

The CMS team has stated they will be scrutinizing the new codit_batch_operations module, we added here, and we rely on it on to make the phone number migrations easier to write. That module isn't strictly required, but it does make for a much better developer experience. Should CMS push back on that module, we will need to pivot to a more "traditional" batch operations methodology, or implement our own batch operations class, both of which are small to medium size tasks.

**Comment by dsasser** [comment]
## End of Sprint Update 9/16/24

We haven't received review by the CMS team just yet. And as this work is blocking the other two phone number tickets, since they all rely on the new module, we are unable to move forward on those until this is merged in. Once done, the other two tickets can PR against the already created integration branch `VACMS-17854-integration-phone-number-migrations`, or, if no conflicts exists on individual branches, PR against `main`.

**Comment by dsasser** [comment]
Decision:

Noting that @omahane and I decided, due to Tugboat timeouts, that we would not automatically run the migrations during deploys, but instead will use Drush to execute the migrations manually. This means I'll have to circle back to this once-completed issue and remove the deploy script, which will be a very quick removal.

**Comment by jilladams** [comment]
Launched in production today.
