### ISSUE TITLE
[Aging Content] Implement text for Developer Configuration Drupal fields

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18019]
## Description

The new developer-facing Drupal fields created as part of the Aging Content Notifications work should have descriptive field text that will aid the developer in their understanding of what to do.

### Glossary

- Entity = Content
- Bundle - Description

### User story

**AS A** Drupal developer who is configuring aging content expiration and notifications for one or more content types (banner, block, etc.)
**I WANT** descriptive labels on the various fields in the UI that I'll utilize
**SO THAT** I can easily and quickly configure the aging content expiration and notification emails

## Acceptance criteria
- [ ] 'Expirable Content types' screen: 
  - [ ] **Entity type**: Text = Select the entity type to add content that can expire.
  - [ ] **Entity bundle**: Text = Select the bundle of the entity type.
  - [ ] **Last updated field**: Text = Select the name of the field that will calculate when the entity was last updated.
  - [ ] **Days before expiration**: Text = Enter the number of days before the entity will expire. This will be the number of days after the entity was created or last updated.
  - [ ] **Days to notify before expiration**: Text = Enter the number of days to notify an editor before an entity expires.

### Artifacts

1. Ticket for Drupal work: #15506 
 
2. Expirable Content types fields

![image-1](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/8f02f0a2-75d2-43cd-806c-2055e4bc8a5c)

3. Structure fields

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/c41e3d2d-1b25-4e84-879a-a16dddd29379)

**Comment by dsasser** [comment]
## Status Update 6/18/24

** Blocked on #18005 **
Since #18005 is also updating Expirable Content, we'll need to wait for this to merge before we can proceed with this work.

The code for the text changes has been [committed](https://git.drupalcode.org/project/expirable_content/-/commit/8f195b7c11937804e3ba5f5ce34022c0741192bd) to the Expirable Content module. In order to realize the update in the CMS, we'll need to:

1. Wait for #18005 to merge
2. Cut a new Expirable Content release
3. Update Expirable Content to the new version in the CMS repo.

**Comment by dsasser** [comment]
This PR is in but it is failing cypress tests which I'm now looking into.

**Comment by dsasser** [comment]
## End of Sprint Update 7/9/24

PR is in and awaiting review. Since Christian is out, I [reached out](https://dsva.slack.com/archives/CT4GZBM8F/p1720542489394639) to other CMS engineers for review assistance.
