### ISSUE TITLE
Typography Audit Issue: Discharge upgrade wizard

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18082]
## Description
From Phase 1 of the Typography audit, we found 2 issues on the Discharge Upgrade Wizard:

1. The labels of the questions on the typography PR do not match the styles currently on Prod. The reason we would like these to be what is on prod is so that each question/label gets the same font weight treatment and importance. It looks like the styles in the  "dischage-wizard.scss" file aren't being picked up in the PR.
![image (6)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/9c28521d-3471-4d82-a260-6b32b299daf7)
![image (7)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/9c7ece8b-575b-4801-8126-1caab9b26e1e)

2. There is also a max-width on the page in the PR that is coming from the <article> however this isn't present on Prod. It's much more obvioius (and a bigger issue) on the review screen. Is there a reason the PR would have different markup than Prod?
![image (8)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/eae4f80e-a8c3-4ca8-9eb9-94e289dd749f)
![image (9)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/47899cf3-b6da-44cd-8eb4-37c5e642184f)

## Acceptance Criteria
- [ ] Proper styles are applied to the wizard
- [ ] The wizard is using the correct width
- [ ] Requires design review

**Comment by FranECross** [comment]
@FranECross to message the DST folks to ask why markup is changing, and is that intended.

**Comment by randimays** [comment]
I did some testing locally and here are my findings:

## Label sizing issues
I figured out why the labels are behaving strangely. Since we're developing a new DUW app and supporting the old one in tandem, running the new app and old app in the local environment can be tricky. We have some logic in place that **always** sets up the page for the **new** DUW in all environments except production. But the routing behaves strangely because of this.

**Old application URL** (this is what lives in production): `/discharge-upgrade-instructions`
**New application URL** (this lives in all environments except production): `/discharge-upgrade-instructions/introduction`

Scenario 1:
If you run locally and go to `/discharge-upgrade-instructions`, you will get the page setup for the **new** application and the routing/components of the **old** application (Frankenstein).

Scenario 2:
If you run locally and go to `/discharge-upgrade-instructions/introduction`, you will get the page setup for the **new** application and the routing/components of the **new** application.

Scenario 3:
This is the only way to get the old application running correctly locally. Adjust the logic in this file: https://github.com/department-of-veterans-affairs/vets-website/blob/32c0f3872b0599af24ef5e0bcbeede146a78facf/src/applications/discharge-wizard/components/DischargeWizardApp.jsx#L10 to always return what is in the `isProd` block.

**Ok cool but what does all this mean?** DST does not need to take any action; what we are seeing is our own Frankenstein.

## Page width issues
I have a PR open for the page width issues for DUW: https://github.com/department-of-veterans-affairs/vets-website/pull/29694 I accidentally introduced some style problems when I took over Chris's DUW review page PR. Once we get that merged and DST pulls in those changes, they should be resolved in their branch; but we won't know until that happens.

**Comment by FranECross** [comment]
- Closing as a no-op per comment above.
- I see that Randi closed the loop with Micah in the Slack thread telling him they no longer need to look at this issue (thank you!).

**Comment by randimays** [comment]
Closing per Fran's comment above
