### ISSUE TITLE
LH V1: Migrate `FacilitiesDrupalCMS` API key calls to LIghthouse (Drupal migrations) to V1 endpoint

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18108]
## User Story or Problem Statement
As a Lighthouse Facilities API user, I want all my API calls to route through V1 so that nothing breaks when V0 is deprecated on / around June 1.

## Description or Additional Context 
https://dsva.slack.com/archives/C02BTJTDFTN/p1715629775668819
>  For the Facilities API V1 migration we are tracking the VADOTGOV_FacilityLocator key used by the front end being migrated but have not discussed the FacilitiesDrupalCMS key. That looks like it is just the pushes from your end to our cms-overlay endpoint. We need to make sure that gets ported over too.

> It should be as simple as changing /v0 to /v1 in the endpoint path as we tried to ensure that endpoint is version agnostic and we handle remapping the fields internally. We should of course verify with some pushes to Sandbox when you have the change staged on your side.

Documentation about the `FacilitiesDrupalCMS` API consumer: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-pages/technical-documentation.md#api-userkey

## Scope
* Any Drupal migrations from Lighthouse that currently call the V0 endpoint, including both GET and POST

## Acceptance Criteria
- [ ] All LH API calls made by the `FacilitiesDrupalCMS` consumer are updated to use the `/v1` endpoint
- [ ] MIgrations are verified for data fidelity on both sides, GET vs. POST

**Comment by jilladams** [comment]
GET is not hard to test
POST is harder, bc LH has to be available to verify it worked.

**Comment by omahane** [comment]
I tested the migrations of all facilities locally. They imported as expected.

I am awaiting the word from Lighthouse to test the data pushes ([via Slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1715799904783689?thread_ts=1715629775.668819&cid=C02BTJTDFTN)).

**Comment by jilladams** [comment]
Noting: LH identified the blocker, will work this week to fix it, and we should be theoretically unblocked next week.

**Comment by omahane** [comment]
I have achieved success with importing an NCA facility. 

That being said, we have different migration configuration for each facility type. Plus, it turns out that the data structure of V0 and V1 have changed, which I was not aware of when sizing this ticket.

<img width="1382" alt="facilities-api-v0-to-v1-nca-facility" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/dcf10f1a-2004-4948-a17e-9eafd4cd7072">

Given the change to the data structure, however, I will not feel confident in these migrations without finding facilities with the most complete data in each facility type. That could take a while.

 It's _possible_ that this will be ready to review on Tuesday. I don't know if it will be able to reviewed by then. I would say this went from 🟡 to 🔴 to be completed for the sprint.

**Comment by omahane** [comment]
Facility migrations are documented here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-facility.md

**Comment by jilladams** [comment]
We found a root cause for failing tests: a single NCA phone number is not successfully migrating, causing test failures.

Once we work out why, can be fixed / unblocked.

**Comment by jilladams** [comment]
Adam / Christian verified: https://dsva.slack.com/archives/C02BTJTDFTN/p1718302995936679
