### ISSUE TITLE
[SECURITY] Protect Geolocation in Facility Locator #553

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18128]
Making this ticket in Facilities board only because when we want to find it later, it will be hard to find the history. 

Security issue with logging Faciltiy Locator URLs that include user PII in the address URL param was mitigated here:
https://github.com/department-of-veterans-affairs/va-iir/issues/553#issuecomment-2030486055

**Comment by jilladams** [comment]
Remaining open tickets that should be listed here when we can get help from IIR to move them: 
* https://github.com/department-of-veterans-affairs/va-iir/issues/563
* https://github.com/department-of-veterans-affairs/va-iir/issues/564

**Comment by jilladams** [comment]
Note: the Platform team has raised a question about the use of POST rather than GET for this work. 

@JonathanKamensDVA we would like you to take a look at the discussion here, and please advise: https://dsva.slack.com/archives/CBU0KDSB1/p1716929906522089?thread_ts=1716928779.346589&cid=CBU0KDSB1. Relevant posts starting from that point: 
> Trying to figure out why it's a POST
> Looks like they're just fetching generic data (edited) 
>  ya, this was changed to a POST in hopes of hiding data that was getting logged by the former GET request with query params containing user location.
> The suggestion was that POST should have more restrictions on the request body being logged in Datadog/Sentry/other, so if the user location data was handled there, we should avoid that data being available in the logs.
> If I'm being honest I'd use a GET rather than a POST, since that's the intention of the route itself (but I looked over that doc Jill linked and see this was already a conversation)
> This is a bit of a weird case cause your 'POST' is really a 'GET' in disguise so doesn't really need CSRF protection
> I can understand why he'd want to make the change from a security perspective but from an API designer perspective it's a super confusing recommendation
> I don't think it's being correlated with a user either as the API request doesn't appear to be passing the session cookie

We understand that Security likely has the final say here, but want to respect the sensibility of the vets-api owners as possible. Please let us know if you would like to discuss further. 

cc @Agile6MSkinner @mmiddaugh @eselkin

**Comment by Agile6MSkinner** [comment]
I suspect there's a middle ground here that could be worked out by having the Platform and Security teams talk to each other about the solution. This section:

> This is a bit of a weird case cause your 'POST' is really a 'GET' in disguise so doesn't really need CSRF protection
> I can understand why he'd want to make the change from a security perspective but from an API designer perspective it's a super confusing recommendation
> I don't think it's being correlated with a user either as the API request doesn't appear to be passing the session cookie

Makes me think it's a more nuanced discussion than just "GET vs POST."

How do we get that conversation to happen? Meeting? Email? Slack?

**Comment by JonathanKamensDVA** [comment]
The requirement that was satisfied by converting this query from GET to POST is that putting PII in URLs is not permitted. The most common address put into the facilities locator is the user's home address, so it's presumptive PII. PII can't go into URLs because URLs go all over the place--GA, Sentry, Datadog, etc.--so putting PII in URLs makes it essentially impossible for us to control where it goes.

I don't really understand what is meant here by "'POST' is really a 'GET' in disguise," but the rule against putting PII in URLs is not going to change.

I would like to understand better why having this endpoint be a POST rather than a GET is a problem, now that (as far as I understand it) the bug / performance issue discussed in the thread linked above has been fixed. Putting queries in POST to avoid having them logged in URL query strings is a common pattern; it's not clear to me why it would be problematic.

I imagine at this point we should have a f2f discussion rather than go back in forth in Slack or GitHub issues, so if somebody from Platform wants to drop a meeting onto my calendar for further discussion, that might be the best path forward. Please not before July 1, though... I am anticipating the next couple of weeks to be very turbulent for me so I would prefer to defer the discussion until then. Thank you!
