### ISSUE TITLE
[VA Benefit Taxonomy] Content modeling for Exclusionary and Simultaneous Benefits

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18165]
## Artifact Produced
[Text proposal](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18165#issuecomment-2214455744)

## Description

Exclusionary and Simultaneous Benefits can be confusing for Veterans to understand, and to his end, we need to enable editors to enter clear instructions and information for any benefits falling into this realm.

This ticket is to provide content modeling for benefits where exclusionary or simultaneous benefits apply.

Please include the following people when scheduling content modeling for taxonomy, per this [Slack channel request](https://dsva.slack.com/archives/C0NGDDXME/p1712850812171859):
Gene Dreyband, yevgeny.dreyband@va.gov
Nicole Kontrabecki,  nicole.kontrabecki@va.gov
Kristen McConnell, kristen.mcconnell@va.gov

### User story

**AS AN** editor of benefits that entail exclusionary or simultaneous benefits 
**I WANT** to be able to provide clear information to Veterans, their family members and/or caregivers
**SO THAT** they will understand their benefits and be able to easily apply without frustration or confusion.

## Acceptance criteria
- [x] Content model is completed showing benefits with their excluded or simultaneous adjacent benefits
- [ ] Review with Michelle M., Fran Cross, Daniel Sasser, and Amanda K.
- [ ] Review with CAIA

**Comment by davidmpickett** [comment]
Estimate this at about a 5. The actual modeling of the relationships between Benefits should be pretty simple, but the naming of these fields and explaining the proper use cases will take a little finesse. I'll also want to clarify the involvement of the various stakeholders listed in the ticket body before calling this fully refined.

**Comment by davidmpickett** [comment]
In the monthly Content COP call today, CAIA talked through an example with plaques and urns being exclusionary with other burial benefits. https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/

**Comment by davidmpickett** [comment]
# Dave's Scratchpad WIP

## Unidirectional relationship 

### Model
```mermaid
flowchart TB
    subgraph AB [Actual benefits]
    direction LR
        A(Benefit 1) -->|is a pre-requisite for| B(Benefit 2)
    end
    subgraph DE [Drupal entities]
    direction RL
    C(Term 2) -->|field_va_benefit_prerequisite| D(Term 1)
    end
    AB ~~~ DE
```

### Example
```mermaid
flowchart TB
    subgraph AB [Actual benefits]
    direction LR
        A(VA health care) -->|is a pre-requisite for| B(VA dental care)
        A -->|is a pre-requisite for| Z(VA vision care)
    end
    subgraph DE [Drupal entities]
    direction RL
    C(VA dental care) -->|field_va_benefit_prerequisite| D(VA health care)
    Y(VA vision care) -->|field_va_benefit_prerequisite| D
    end
    AB ~~~ DE
```

**Comment by jilladams** [comment]
@davidmpickett sounds like it'll roll over sprint boundary, all good, but could you flag maybe a % of effort here that's complete vs. remaining, so we can work out how much capacity we may have to work with in sprint planning for Content stuff for you on Wed? (cc @Agile6MSkinner @FranECross )

**Comment by davidmpickett** [comment]
- [Shared on slack](https://dsva.slack.com/archives/C52CL1PKQ/p1720472361222369) for async review
- Plan to use some UX Sync this week to give background context to @FranECross @mmiddaugh @aklausmeier (@dsasser is welcome too, but he was here when this was built, so probably knows a lot of it already)

**Comment by davidmpickett** [comment]
> @davidmpickett sounds like it'll roll over sprint boundary, all good, but could you flag maybe a % of effort here that's complete vs. remaining, so we can work out how much capacity we may have to work with in sprint planning for Content stuff for you on Wed? (cc @Agile6MSkinner @FranECross )

Bulk of the remaining stuff is reviews / product conversations. Maybe 3 points left depending on how substantial the feedback is.

**Comment by davidmpickett** [comment]
I gave a presentation in UX sync today about the Taxonomy and how this piece of work fits into it.
@jilladams can you adda comment here with the meeting recording one it has processed?

**Comment by mmiddaugh** [comment]
@FranECross @davidmpickett I will get answers to the open questions during a meeting with Danielle and Randi H on 7/24

**Comment by davidmpickett** [comment]
**End of sprint 8 update**

- Gave presentation in UX sync
- Identified open questions that need product/stakeholder before moving forward 
- Chatted 1on1 with Michelle about this and related tickets
- Reviewed related tickets and left notes
- This work will roll into Sprint 9 since we won't have more info until after that 7/24

**Comment by davidmpickett** [comment]
Moving this to Admin/Workflow to represent that it is blocked pending stakeholder input

**Comment by mmiddaugh** [comment]
Summary from conversation with Danielle and Randi

**Re: Pre-requisite benefits**
Yes, they agree with the suggestion to add validation to prevent reciprocal references between pre-requisite benefits 

**Re: Simultaneous**
- there are no known clear cases for this logic 
- in reality, a Veteran may use the same application to apply for certain benefits (i.e. Healthcare and Dental) but the benefits are not necessarily both granted or may not be granted at the same time. It's more accurate to say, "If you are approved for A, you might also be eligible for [one or more other benefits] 
- "related" may be a better description than "simultaneous" but not obviously distinct from "co-considered"

**Re: Exclusionary**
- most of the scenarios we considered can be characterized by "know your options" making it more important to surface the possible ramifications of choosing one benefit over another than to enforce logic such as "if A, than not B"
- the granularity needed to cover the variations of exclusionary relationships could introduce a risk for editor confusion when choosing between two possible categories 

The taxonomy is not expected to determine eligibility at this stage. Because of edge cases and the complexity of the relationships between benefits, we determined that simultaneous and exclusionary benefit relationship categories are not necessary for MVP.  These scenarios can be covered by the "co-considered benefits" category for now. The content will be responsible for providing the details, rather than the content model.  

@davidmpickett @FranECross If we've failed to consider any implications here, please let us know.

**Comment by davidmpickett** [comment]
All of that makes perfect sense to me! I will spin up the ticket for preventing the reciprocal references on Pre-Requisite benefits before close this.

**Comment by FranECross** [comment]
I'll update the product brief with this info and remove from MVP, scooting to will not do with explanation.
