### ISSUE TITLE
[VA Benefit Taxonomy] Benefit Description fields minimum character limits & other updates

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18170]
## Status
**[2024-08-07] [Daniel]** Daniel pre-refined.
**[2024-07-31] [Fran]** Asked Daniel [via Slack](https://dsva.slack.com/archives/C03LFSPGV16/p1722461629618799) to async refine.
**[2024-07-26] [Dave]** Dave updated the ticket to reflect the updated direction. There are still some open questions / considerations, so definitely needs more refinement, but probably ready for Daniel to take an async pass.
**[2024-07-24] [Dave]** @davidmpickett to take next pass at refining based on decisions
**[2024-07-19] [Fran]** Moved back to Drafts pending a meeting Michelle M has with Danielle and Randi H on 7/24.

## Description
There are three (existing) fields for providing Benefit Descriptions to Veterans, their family members, and/or caregivers: 
* Teaser summary
* Brief summary
* Longer summary

When we first set up the taxonomy, we set maximum character limits on two of the fields, but did not make any field required or set minimum character limit.

![screencapture-staging-cms-va-gov-admin-structure-taxonomy-manage-va-benefits-taxonomy-add-2024-07-26-11_14_31](https://github.com/user-attachments/assets/116cd016-e4e9-46b5-8c98-cbf76db6f5ca)

### Desired field configurations

✅ = already in place  
🔲 = work to do in this ticket

* **Teaser summary:**
    * Maximum characters = 300 ✅
    * ~~Minimum characters = 20 🔲~~
    * Required 🔲
 * **Brief summary:**
    * Maximum characters = 500 ✅
    * ~~Minimum characters = 301 🔲~~
    * Optional ✅
 * **Longer summary:** 
   * Maximum characters = unlimited ✅
   * ~~Minimum characters = 501 🔲~~
   * Optional ✅

 
### Minimum characters
The module we use for character counters doesn't currently have a way to set/display/enforce minimum character limits. There's an [open upstream issue](https://www.drupal.org/project/textfield_counter/issues/3263433). If we want to display minimum characters dynamically, we'd probably need to address that.

I believe we could set a minimum that's enforced on save, but that's not a great user experience to get an error message.

**11/4/24 update**: Minimum character count did not work with the patch; patch is faulty. Min chars has been removed from ACs, and we will instead provide help text to indicate the min char count, since this is CAIA, and they can manage without programmatic enforcement.

### Help text updates
Fran to work with CAIA to provide content for the editorial interface for best practices:
  * Note that CAIA will provide editorial context e.g. help text.
  * Note from CAIA: We need to think about how much depth we want to go into for the “Longer summary.” For example, for health care benefit programs, would we include what’s covered and what’s not in the full (Longer summary) description? This is something for us (CAIA) to do. We’ll think through this more and document it, but we want to capture it here as part of our overall findings as we began to use this taxonomy.

### User story

**AS AN** editor adding benefit descriptions in the editor interface
**I WANT** to clearly understand the character limits for the Longer summary, Brief summary, and Teaser summary, as well as that the Teaser summary is required
**SO THAT** I'll can enter content appropriate to each field

### Questions
* Are there any excluded symbols? If so, take into consideration:
  * Should helper text indicate excluded symbols?
  * Specific error messaging will need to display if excluded symbols are used.
* Teaser summary is currently using `string_long` which means [it can't do Text Format validation](https://dsva.slack.com/archives/CT4GZBM8F/p1721861648472019?thread_ts=1679509489.664729&cid=CT4GZBM8F). 
   * Might want to switch it to text_long and use "Plain Text" Text Format
   * Might also want to create a new "Plainer Text" text format since even "Plain Text" allows some HTML tags

## Acceptance criteria
- [ ] Teaser Summary field:
  - [ ] required and shows red asterisk indicating such
  - [ ] character field limits / requirements:  Maximum length 300
  - [ ] Character limits are displayed to the user/editor just under the field: "e.g. "300 characters remaining", and as they type, this number will decrease accordingly.
- [ ] Brief Summary field
  - [ ] optional (no red asterisk)
  - [ ] character field limits / requirements:  Maximum length = 500 
  - [ ] Character limits are displayed to the user/editor just under the field: "e.g. "500 characters remaining", and as they type, this number will decrease accordingly.
- [ ] Longer Summary
  - [ ] optional (no red asterisk)
  - [ ] no field character limit

**Comment by davidmpickett** [comment]
The logic here seems a little backwards. Essentially the logic is ensuring that there always needs to be a summary that is under 300 characters. But rather than the primary place that the shortest description lives being the field with the 300 character limit (Teaser summary), it could be in field with a 500 character (Brief Summary) or the one with a larger character limit (Longer summary). 

From the perspective of a FE developer querying these fields, if I wanted to get a description that was less than 300 characters I'd have to have a logic that always checks all three fields and possible count the length of them.

**Fields and possible responses**
- Teaser summary
  - Null or < 301 characters
- Brief Summary
  - Null, < 301 characters, or 301 - 500 characters 
- Longer summary
  -  < 301 characters, 301 - 500 characters, > 500 characters

If we flipped the logic and made Teaser summary Required and added MIMIMUN character limits on the other two fields then the expected responses would map like this:

- Teaser summary
  - < 301 characters
- Brief Summary
  - Null, or 301 - 500 characters
- Longer summary
  - Null, or > 500 characters

**Comment by FranECross** [comment]
@davidmpickett Thank you for your explanation and information! I'm tagging @DanielleThierryUSDSVA and @RLHecht for their review/agreement since (I believe) Dave C mentioned the requirements were reviewed with / came from them, and also @mmiddaugh as our new PO.

@DanielleThierryUSDSVA, @RLHecht and @mmiddaugh, regarding the Benefit Description fields (Long summery, Brief Summary, Teaser Summary), will you please review Dave Picket's suggestion in the the comment just above and let me know if we should alter the requirements to fit what he proposes (BTW I think it makes good cents - my 2 cents).

**Comment by davidmpickett** [comment]
@FranECross - FYI, I chatted with @mmiddaugh about this briefly in a 1on1 today. She is aligned with me on the direction of keeping the fields consistent lengths and having a more straightforward Required / Not Required implementation rather than the conditional Required logic proposed in the ticket body.

**Comment by mmiddaugh** [comment]
@FranECross @davidmpickett I will address this topic during a meeting with Danielle and Randi H on 7/24

**Comment by davidmpickett** [comment]
Moving out of next refinement until that meeting has happened

**Comment by mmiddaugh** [comment]
@davidmpickett @FranECross - Danielle and Randi approved your proposal to make only the teaser summary required with the character restrictions as written

- Teaser summary
  - < 301 characters
- Brief Summary
  - Null, or 301 - 500 characters
- Longer summary
  - Null, or > 500 characters
  
Moving this into the refinement column

**Comment by davidmpickett** [comment]
@FranECross @dsasser FYI - I have updated the ticket to reflect the updated direction. There are still some open questions / considerations, so definitely needs more refinement, but probably ready for Daniel to take an async pass.

**Comment by dsasser** [comment]
## Engineering Pre-Refinement

Point estimate: 5️⃣ (assumes we are going with the below approach):

The bulk of the work here is adding minmum length for Textfield Counter fields.  We will try the [patch](https://git.drupalcode.org/project/textfield_counter/-/merge_requests/3.diff) to the Texfield Counter module to resolve this. This will promote and leverage community involvement. However the patch is sizeable, so we may need to spend a good amount of time time debugging and updating the patch.

### Answers(?) to open questions

> Are there any excluded symbols? If so, take into consideration:
> Should helper text indicate excluded symbols?
> Specific error messaging will need to display if excluded symbols are used.

That seems like a different validation that could be added later. Trying to keep issues lean but if this is a requirement that I'm not seeing please ignore.

> Teaser summary is currently using string_long which means [it can't do Text Format validation](https://dsva.slack.com/archives/CT4GZBM8F/p1721861648472019?thread_ts=1679509489.664729&cid=CT4GZBM8F).
> Might want to switch it to text_long and use "Plain Text" Text Format

Not sure this belongs here. It would require a data migration/wonky config wrangling as storage types cannot be swapped out easily (it isn't a UI change, and there are no APIs for making this easy to do). This has my vote for being its own ticket.

> Might also want to create a new "Plainer Text" text format since even "Plain Text" allows some HTML tags

I'm not sure what the use case would be? HTML tags are allowed in plain text fields because they aren't treated as HTML but their respective [HTML entities](https://www.w3schools.com/html/html_entities.asp). Either way, sounds like another thing we could possibly peel off to a separate ticket since there seems like a discussion/more context would be needed to flush this out.

**Comment by jv-agile6** [comment]
Reviewed Acceptance criteria
[ ] Character limits are enforced for all three fields
[ ] All character limits are communicated to user
[ ] Required/optional status is enforced for all three fields
[ ]

But read discrepancies with within the comments

> Teaser summary:
> Maximum characters = 300 ✅
> Minimum characters = 1? 🔲
> Required 🔲
> Brief summary:
> Maximum characters = 500 ✅
> Minimum characters = 301 🔲
> Optional ✅
> Longer summary:
> Maximum characters = unlimited ✅
> Minimum characters = 501 🔲
> Optional ✅

Looking for clarification on acceptance criteria

**Comment by FranECross** [comment]
@davidmpickett @dsasser @jv-agile6 I just updated the AC, but then read more of the comments, and am not sure I have the expected field declarations to editors correct in the AC. Are we only adding the field counter as text under each field, and not telling the user minimums? Could use some help with that part of the AC.

**Comment by davidmpickett** [comment]
We definitely want to tell users about all field requirements. The exact we we do this depends on what technical approach we are using for minimum character validation. Are we patching the Texfield Counter module? 

- **Yes**: I think we could do an updated dynamic message below the character counter that would include both the minimum and maximum amounts. I can support with crafting that wording once the module is patched and we know if there is an updated variable for the widget settings.
- **No:** I can figure out how to rework this message using existing variables only.

**Comment by jv-agile6** [comment]
Had issues w/ spec'd patch file. Huddled w/ @dsasser and discovered an updated patch file on ==> https://www.drupal.org/project/textfield_counter/issues/3263433. Applied [#4 patch](https://www.drupal.org/files/issues/2024-08-26/textfield_with_minimum_counter.patch) and committed branch.

**Comment by jv-agile6** [comment]
Min and max fields for benefit descriptions in VA Benefits taxonomny configuration updated.
- Teaser summary:  min 20 max 300 Prevent form submission when user goes over character count or remains below minimum count: Yes
- Brief summary: min 301 max 500 Submission not enforced
- Longer summary: 501 max Unlimited 500 Submission not enforced

**Comment by jv-agile6** [comment]
Resolved Unlimited Max field for Longer Summary by an empty field which disables max number of characters.

Testing assume means creating VA content that uses the VA benefit taxonomny and then validating the AC conditions. Reached out to @dsasser for appropriate testing content. Validating against tomorrow

**Comment by jv-agile6** [comment]
An issue I'm encountering with the addition of the "Teaser Summary" field marked as a necessary field (indicated by the red asterisk). This requirement is currently causing my form submission tests to fail, as the field is not meeting the AC correctly in certain scenarios for form submission.

**Comment by jv-agile6** [comment]
This is my testing documentation:
Teaser summary AC:
Maximum characters = 300 
Minimum characters = 20 
Required 

Form Submission under min characters
Form Submission 20 characters
![Image](https://github.com/user-attachments/assets/cd634036-e33f-4959-ab0c-c8634a6a6b13)
Form Submission over max characters



Brief summary AC:
Maximum characters = 500 
Minimum characters = 301 
Optional 

Form Submission under min characters
Form Submission 301 characters
Form Submission over max characters

Longer summary:
Maximum characters = unlimited 
Minimum characters = 501 
Optional 

Form Submission under min characters
Form Submission 501 characters
Form Submission over max characters

**Comment by jilladams** [comment]
Got Michelle's approval to drop the minimum character count, as long as we provide reasonable help text to guide the editor. Removing from ACs. cc @davidmpickett who can help with any questions / input needed on that help text, as needed.

**Comment by dsasser** [comment]
## Decision 11/5/24

Per UX discussion with @davidmpickett @omahane and @jv-agile6 we agreed that:

- Minimum character count requirements are not enforced, so minimum count help text is not suitable. Minimum guidance should be put into the related KB article.
- Longer summary does not need a character counter or related counter help text.

ACs updated to reflect this.

**Comment by jilladams** [comment]
From PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19751#issuecomment-2457656057
On "Brief Summary", if you enter >max characters, you get: 
* Two references to an error on the Brief Summary field, as jump links. 
* Jump links do not work. 
* Resolve the >max chars issue resolves both error reports.

The broken Jump links is a Drupal core bug, from even before D10. Out of scope to fix.

The double error for a single actual problem is only happening on the Brief Summary field (first case of seeing this anywhere in the CMS), and is mysterious. Resolving the >max chars problem makes both reports of the same error go away. So: it's a mildly confusing UX, but easy to resolve by removing extra characters above max.

Daniel / Jerry have explored what it would take to fix either/both of these, and we think they are somehow connected but don't have clear path to a fix. Will require a fix to a module (didn't catch the name, counter something), which Edmund on CMS team co-maintains.

Decision: neither broken jump links or double error report blocks this ticket / PR from merging. We will ignore broken jump links. We might ticket the double error in case CMS team or our team is able to later prioritize trying to root cause / fix it.

**Comment by jv-agile6** [comment]
Pull request has been merged and moved to complete pending

**Comment by jilladams** [comment]
Took a quick look in Prod -- @FranECross can you double check and close if you're satisfied? 

Taxonomy: https://prod.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/overview - can check on any term in that list
* Teaser Summary is required, 300 char limit
* Brief summary is not required, 500 char limit
* Longer summary is not required, no char limit

**Comment by FranECross** [comment]
Reviewed and looks great; closing. Thanks!
