### ISSUE TITLE
[Analytics] [Benefits Hub] Custom GA events removal & va-link component w/analytics adoption

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18185]
## Description

The va-link component has been enhanced to provide destination and can be used now for applicable Benefit Hubs features, along with removal of the GA custom events.

Details are in the AC.

### User story

**AS A PO/PM** managing Public Websites products & features
**I WANT** to (where appropriate) adopt the va-link component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria

- [x] **Element with custom events:** "The PACT Act and your VA benefits" link
  - [x] convert to va-link? No, already converted
  - [x] enable DST analytics
  - [x] remove custom code
- [x] **Element with custom events:** (Right Rail) Follow us social links (Twitter, Facebook, YouTube)
  - [x] Convert to va-link? Yes, if not already done.
    - DST web component baked-in analytics data: click event on "va-link" with link text only
  - [x] enable DST analytics
  - [x] remove custom code
- ~[ ] **Element with custom events:** (Right Rail) Call us links~
  - ~[ ] convert to va-link? Yes, if not already done~
    - ~DST web component baked-in analytics data: click event on "va-telephone" with contact number and extension~
  - [ ] ~enable DST analytics~
  - [ ] ~remove custom code~
- [x] **Element with custom events:** (Right Rail "Not a Veteran?") links
  - [x] convert to va-link? Yes, if not already done
    - DST web component baked-in analytics data: click event on "va-telephone" with contact number and extension
  - [x] enable DST analytics
  - [x] remove custom code

**Comment by randimays** [comment]
Pulling in from stretch.

**Comment by randimays** [comment]
@FranECross This will be in staging by 7am PST today. Will you please review when you have a moment? Here's the PR: https://github.com/department-of-veterans-affairs/content-build/pull/2125 if you want to refer to the screenshots for the links that were updated.

**Comment by randimays** [comment]
@FranECross I have a bit more work to do on the "Call us" links in the right rail. Feel free to hold off on reviewing until I can get that merged. Apologies for the flip flop.

**Comment by FranECross** [comment]
@randimays No worries, and sounds good!

**Comment by randimays** [comment]
Struck out the comment from above. In going back to update the Call us links to `va-telephone` components, I put a design question out to Jordan and tagged Laura about splitting up the phone number description and the actual number: https://dsva.slack.com/archives/C06NMUK12LR/p1718129765580799

Laura pointed out that because we have a bit too much wriggle room in the CMS for adding phone numbers, our `va-telephone` component cannot easily support all the different types of numbers it'll receive. (The GIBILL number on va.gov/education is a good example of an outlier). Her ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17326

When #17326 is addressed, we can convert (at least most of) these phone numbers to `va-telephone` and remove the custom events on them.

@FranECross (phew, sorry) we're ready to validate in production and close this ticket on your signal. Also updating the ACs to exclude this phone number stuff too.

**Comment by FranECross** [comment]
@randimays Turns out I can't test on Staging because Adswerve isn't available and I don't have permissions to upload it, but the screenshots give me what I need. Approved! Thanks so much.

**Comment by randimays** [comment]
No worries, Fran! I was able to validate everything in production 👍🏻 Closing as complete.
