### ISSUE TITLE
VBA QA:  "Get updates" link text does not match what is in Figma design

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18217]
(I actually think this is a non-issue but I'm making a ticket anyway)

## Description
In the [Figma Designs for VBA](https://www.figma.com/design/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?node-id=0-1107&t=hrYlJNEbuJRGoJrC-0) the "Get Updates" link text is:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/74b875a6-e736-4396-875d-3eee60c875c4)

However, [in Prod](https://preview-prod.vfs.va.gov/preview?nodeId=4237) these links are different:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/97bcf176-6b37-4696-abcf-bb26b080aeec)

## Acceptance Criteria
- [ ] Confirm is the prod links are correct
- [ ] If not, determine what they should be and correct them
- [ ] Requires design review

**Comment by davidmpickett** [comment]
These are controlled by the VBA Centralized Content Node. Content can be edited directly by Michelle if needed. No action required by Facilities team.

This was an [intentional change in a previous revision](https://prod.cms.va.gov/node/61744/revisions/view/824667/824677/visual_inline) to match CAIA guidance.

**Comment by mmiddaugh** [comment]
Related: #17886
