### ISSUE TITLE
All published VBA services are not showing on the FE

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18214]
## Description
Not all services are showing on the front end on the facilty page. It seems like there might be a max of 10 total set somewhere. For example:
- Honolulu has 15 published and only 10 showing. The missing ones are and I noticed that those were the most recently published ones:
    - Direct Deposit
    - Education benefits for family members
    - Disability compensation
    - Burial and memorials
    - Benefits letters and decision letters
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/9088ea22-2d9d-4ac2-aa0a-d9eeb88d5d42)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/fe3326e8-0136-4057-b5c3-6c7d5eed5b71)

- [National Capital](https://web-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/national-capital-region-va-regional-benefit-office/) as 11 published and only 10 showing, again this is the last published one:
    - Home loans
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/c905a9c3-cc56-4ef1-aaa3-d38c7ec0fc43)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/bd818430-5ca8-47d6-b68f-bd05d879a2bf)

## Acceptance Criteria
- [x] Determine is there should be a limit to how many services display - Answer: no limit
- [x] All VBA Facility services should appear

**Comment by davidmpickett** [comment]
There should not a be a limit. All published services should display.

This is a problem and should be investigated ASAP. While this might not technically be blocking of Staging Review (since it is unlikely for Platform to notice) it will be prevent our team from fully testing & QAing VBA.

**Comment by eselkin** [comment]
Turns out Drupal sets a limit to 10 when no explicit limit is set on the subqueries. What is an appropriate limit we should set? 25? 50? 100? I'm guessing we should go with an arbitrarily highish (100) number since we always want to return all services. @Agile6MSkinner @jilladams

**Comment by davidmpickett** [comment]
Copying my notes from [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1718158368844779?thread_ts=1718112021.386079&cid=C0FQSS30V)

BLUF: Other places where we are doing queries like this seem to use a limit of 500 ([example 1](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js#L37), [example 2](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/vetCenter.graphql.js#L94)).

Similar to the [epiphany I had in in 17681](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17681#issuecomment-2151102095), this seems to be another reason why VAMCs and Vet Centers call Services as a Field Query rather than a Reverse Node Query. A field query doesn't seem to have a limit (unless the field itself has a cardinality limit).

While adding a limit ([here](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/vbaFacility.graphql.js#L129) I think?) would be a quick fix, this makes me think that long term we should probably add an Entity Reference field to VBA Facilities to pull in the list of Services (Drupal Config PR) and switch the query to a Field Query (Content build PR). That would make the queries more consistent across facility types and also not having to declare a limit seems more future proof than just picking a high number.

**Comment by eselkin** [comment]
Updated my 100 limit to 500 per similar limits, though that's a combined total of 1000 services... Not that any facility will reach that, but that seems like a lot.

**Comment by jilladams** [comment]
@Agile6MSkinner We need some product help here to decide whether / how to modify the current Drupal implementation. Dave left notes [above](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18214#issuecomment-2161976454) -- if we do want to align the handling of how we call services acros products, that's new Drupal work & FE template work we need to do to update this implementation. Could you make a note of this for us to talk about in our next refinement, to decide if this is done for now, or if we want to call this tech debt, and clean it up now vs. later? 

cc @mmiddaugh

**Comment by Agile6MSkinner** [comment]
@jilladams Ok, I've moved this to the top of the order for next refinement.

**Comment by eselkin** [comment]
The work to do the limit increase is in PR (@dsasser is waiting on us resolving whether we want to go ahead wit the limit increase or do the field modifications and changes to graphql). If we change to do the graphql changes and field updates, I doubt that would be done before the end of sprint.

**Comment by davidmpickett** [comment]
This can't really be verified on prod because no VBAs are published and Preview Server won't show services. So instead I am doing a Content Release on my tugboat with Main & Main (whereas I previously was using PR 2128 for content-build. Once that completes should be verifiable here: https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/

**Comment by davidmpickett** [comment]
Verified on Tugboat
![screencapture-web-jdujzwgvp8kmj36hcfonqejlgtq5b6st-demo-cms-va-gov-philadelphia-va-regional-benefit-office-2024-06-24-14_35_29](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4c372883-bdc3-4829-8ec0-d535fd2ee5b5)
