### ISSUE TITLE
Unable to upgrade Drupal module with composer: The .git directory is missing from...

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#18257]
## User Story or Problem Statement
I am receiving this error when attempting to upgrade a Drupal module from a dev release to an alpha version.

```
The .git directory is missing from /var/www/html/docroot/modules/contrib/expirable_content
```

This occurs both locally and in Tugboat.
<img width="1145" alt="Screenshot 2024-05-30 at 6 22 18 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/cebc79e0-c96a-4f10-9ec5-82a08149b6e2">

The error can be bypassed locally by responding to the prompt, but this isn't an option in CI.

## Description or Additional Context 
This was noted by [Tim](https://dsva.slack.com/archives/CT4GZBM8F/p1678307939948779?thread_ts=1678126053.329369&cid=CT4GZBM8F) last year, and it was solved by manual edits to a lock file

> Edmund was able to bypass this by directly editing composer.lock, but the problem will continue to occur when folks next regenerate composer.lock.

## Steps for Implementation

1. Checkout the main branch
2. Run composer install
3. Checkout branch `VACMS-18005-aging-content-tests`
4. Run composer install
5. Get the error

## Acceptance Criteria
- [ ]

**Comment by timcosgrove** [comment]
As near as I'm able to reconstruct, this removal of .git directories behavior traces back to this PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11893

There was no associated ticket, and not much associated discussion; the only Slack discussion I found is here: https://dsva.slack.com/archives/CT4GZBM8F/p1670544135956989

Based on that discussion and what was written in the PR, this was put in place to alleviate some amount of developer annoyance. This is a worthwhile goal if it doesn't interfere with normal code management.

The problem with this solution is that any package that needs to be managed via source and via a branch rather than a tag becomes a problem here, as .git directories are required in those packages so that they can be updated. In composer, this is any package that is referenced via a `dev-` branch, as we did for expirable_content in this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15506

No longer removing .git directories should not cause problems with the normal deploy operations of the site, though this will need to be monitored as it rolls out.
