### ISSUE TITLE
URL Change for: Findlay VA Clinic - New Facility

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18294]
### Implementation date
When does this request need to be live:
TBD

⚠️ New facilities don't get redirects ⚠️ 

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_506GG | https://www.va.gov/ann-arbor-health-care/locations/findlay-va-clinic/ |

**Comment by jilladams** [comment]
@TroyCMSSupport noting: this ticket somehow didn't get the appropriate labels applied to show up in the Facilities board for awareness. I noticed that pointers to the URL change runbook from the [Flagged Facilities docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/flagged-facilities.md) were 404ing, so I updated the links there. In future, using those URL Change runbook links will help create a ticket with the correct labels for us to act on the new tickets. Thanks! (cc @ian-sears )

**Comment by davidmpickett** [comment]
It looks like this facility is still assigned to [VA Ann Arbor health care section](https://prod.cms.va.gov/section/vha/vamc-facilities/va-ann-arbor-health-care) rather than [VA Dayton health care section](https://prod.cms.va.gov/section/vha/vamc-facilities/va-dayton-health-care). I think that the URL aliases in Drupal may be based on that section, so this may need to be updated in order for the FE URL to change

**Comment by TroyCMSSupport** [comment]
@davidmpickett @ian-sears - This facility should be part of Ann Arbor; Dayton was initially (and incorrectly) assigned to Findlay

**Comment by davidmpickett** [comment]
@TroyCMSSupport noted. Sorry for the confusion! 

There's still an element that's connecting it to Dayton. The Parent Link is currently set to Dayton/Locations rather than Ann Arbor/Locations. So the [menu of doom](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11790) will need to be opened. I'm not sure if that's normal runbook procedure, or an artifact of it switching systems

![Screenshot 2024-06-17 at 4 26 44 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a15e0d0b-d2fe-4364-9688-ff6b664cdd7e)

**Comment by TroyCMSSupport** [comment]
Ah, yes @davidmpickett -- How could I forget the Menu of Doom??? 
As always, your wisdom and knowledge beyond your years is greatly appreciated!

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears @jilladams  - The Editor has already published this page; the Section is correct (VA Ann Arbor health care), and I believe this is ready for Redirect - Please let me know if you find othewise.

**Comment by omahane** [comment]
I removed the redirect related information, as new facilities don't require redirects.

I have put in the request for a CSV change [via Slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1719594660449489?thread_ts=1719340047.322509&cid=C02BTJTDFTN).

**Comment by omahane** [comment]
The canonical URL has been deployed, [per Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1720015713762209?thread_ts=1719340047.322509&cid=C02BTJTDFTN), and verified by me on VA.gov.
