### ISSUE TITLE
Update Cerner CTA Widget to use v2 Facilties API endpoint

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#18319]
## User Story or Problem Statement
PW Cernter CTA calls v1 VAOS endpoint but needs to call v2 Facilities API endpoint so it's off V0 lighthouse.

## Acceptance Criteria
- [x] facilities-api endpoint usage is updated to use V2
- [x] CTA login widget behavior does not change from current behavior in Prod / Staging

**Comment by jilladams** [comment]
Pages PW owns that use the CTA widget: 
| --- |
| https://www.va.gov/health-care/refill-track-prescriptions/ |
| https://www.va.gov/health-care/secure-messaging/ |
| https://www.va.gov/health-care/get-medical-records/ | 
| https://www.va.gov/health-care/view-test-and-lab-results/ | 
| https://www.va.gov/health-care/schedule-view-va-appointments/ | 

**Contents of the CTA widget / redirect destination will depend on the test user being used.** 
* If the user has VistA healthcare: redirect will send to MHV
* If the user is affiliated with a VAMC System that uses Cerner:  redirect will point to Oracle Health / Cerner portal
* Some Veterans have both, and both CTAs should appear

If you've never logged in before or not since the Terms of Use were updated, here's the behavior I get in prod: 
* Start from Rx page
* Login using CTA widget
* Redirect to Terms of Use, accept them
* Get sent to homepage

So the redirect gets lost if TofU is in the way, and we don't need to worry about that in our testing.

**Comment by jilladams** [comment]
Sidebar: Apparently the Test User Dashboard is no longer supported (lolob)
<img width="760" alt="Screenshot 2024-06-14 at 10 53 59 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/702e0cd2-6bd5-4b80-9939-c14232cd2506">

But it does still work if you're on SOCKS: https://tud.vfs.va.gov.  The listed users can auth on Staging, and Review Instances, not on Prod. 


None of the credentials I've found around Slack for Cerner users work so far (e.g. ([here](https://dsva.slack.com/archives/C04PRFEJQTY/p1717077432586499?thread_ts=1716304571.633459&cid=C04PRFEJQTY)). The risk of not testing with a Cerner user is that once logged in, the CTA widget wshould show all locations where a user is affiliated with the System, so it would prove our Facility logic with this code is actually working. Gonna reach out to the Oracle cutover channel to figure out if they have one.

**Comment by jilladams** [comment]
Tested each of those 5 pages with a login.gov test user that is only affiliated with MHV and it looks fine. Cerner is really the concern here, as far as how the Facility logic is used / verifying that nothing changed. 

For our future selves: Turns out there is a Github doc in the Sensitive repo of Cerner test users: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-cerner.md

**Comment by jilladams** [comment]
@eselkin Good news: [ssoissoetesting+spokane2@gmail.com](mailto:ssoissoetesting+spokane2@gmail.com) user can be used on Staging to verify the Cerner test case. 

Bad news: code on the RI fails the test case -- comparing to Staging, we do not get the expected list of Cerner locations: 

<img width="1364" alt="Screenshot 2024-06-14 at 11 41 03 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/938bed0c-4834-4ee9-ae9e-635a6e8b7598">

**Comment by eselkin** [comment]
I'm not seeing it make any request. Trying now

**Comment by eselkin** [comment]
Do you have the URL you used to test the component @jilladams ?

**Comment by eselkin** [comment]
Wait something is odd. https://staging.va.gov/health-care/get-medical-records/ is not using the endpoint but refill is... could be caching let's wait

**Comment by eselkin** [comment]
<img width="1481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXh0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--597428be619f0dd597872416d9efbdbf097be5cd/Screenshot%202024-06-17%20at%2010.39.38%E2%80%AFAM.png" alt="Screenshot 2024-06-17 at 10.39.38 AM.png" />

**Comment by jilladams** [comment]
OOB deployed: https://github.com/department-of-veterans-affairs/va.gov-team/issues/86164

**Comment by davidmpickett** [comment]
Do we have a way to verify this on Prod?

**Comment by jilladams** [comment]
Nerp. We have asked around, and do not have any Prod veterans with Cerner care facilities associated who can verify for us, that we have found. We also have not heard any complaints or issues since the work merged. I think must needs call it closed, and can reopen if we get field reports of problems.
