### ISSUE TITLE
Answer OPIA Team Questions

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18357]
## User Story or Problem Statement
As a member of the OPIA team, I need to understand the how to interpret the fields and how the fields are used so that I can correctly use the JSON file for my work.

 
## Description or Additional Context 
After delivering the MVP solution to the OPIA team, the team has questions about the JSON data file that we sent them. 

## Steps for Implementation
Answer the following questions: 
1. What field is the start time for the event? 
2. Investigate what is going on with the "Mama Bear Club" meeting. Why is there so many values? Is a repeating meeting? 
3. What is supposed to be in the additional listing field? 

## Acceptance Criteria
- [ ] Answers to OPIA team's questions have been sent to the OPIA team.

**Comment by anantais** [comment]
1. The date-time field shows both the start and end times for the event.
2. The "Momma Bear Club" is a recurring event in the system.
3. The additional-listing field does not appear to be used right now. I included it because I thought it was being used but now that I have investigated more it appears to have been disabled.
