### ISSUE TITLE
Breadcrumbs pulling from wrong place for Family Member Hub

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18412]
## Status
**[2024-07-03]** [Fran] Targeting Sprint 8. Request for async refinement in Slack [here](https://dsva.slack.com/archives/C52CL1PKQ/p1720042624395829). 

## User Story or Problem Statement
The CAIA team created the Family Member Hub and the breadcrumbs are not correct on the page. The CAIA team troubleshooted and determined that the breadcrumbs are displaying due to a bug within the system. 
 
**CAIA's Report**
We launched family member hub here: https://www.va.gov/family-and-caregiver-benefits/

This Benefit Detail page has the wrong breadcrumbs, even though it's set up the same as the other child pages in this section: 
* FE page: https://www.va.gov/family-and-caregiver-benefits/health-and-disability/
* CMS URL: https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability
* Actual Breadcrumbs:  [Home](https://www.va.gov/) > [OCTO](https://www.va.gov/section/octo) > [Sitewide content team](https://www.va.gov/section/sitewide-content-team) > [Family and caregiver benefits hub](https://www.va.gov/section/octo/family-and-caregiver-benefits-hub) > [Health and disability benefits](https://www.va.gov/family-and-caregiver-benefits/health-and-disability) -- **same breadcrumbs occur in both CMS and FE**
* Expected breadcrumb: [Home](https://www.va.gov/) > [VA benefits for family and caregivers](https://www.va.gov/family-and-caregiver-benefits) > [Health and disability benefits](https://www.va.gov/family-and-caregiver-benefits/health-and-disability) 

Same breadcrumbs as other child pages, like this one (which we think is set up identically in drupal):
* FE page:  https://www.va.gov/family-and-caregiver-benefits/life-insurance/
* CMS URL: https://prod.cms.va.gov/family-and-caregiver-benefits/life-insurance
* Breadcrumbs: [Home](https://www.va.gov/) > [VA benefits for family and caregivers](https://www.va.gov/family-and-caregiver-benefits) > [Life insurance for family members](https://prod.cms.va.gov/family-and-caregiver-benefits/life-insurance)

## Relevant Links
- IA helpdesk request: https://dsva.slack.com/archives/CDHBKAL9W/p1719423109227689
- Main thread with CAIA for comms about this issue: https://dsva.slack.com/archives/C01K37HRUAH/p1719436649312759?thread_ts=1719332572.216609&cid=C01K37HRUAH
- Helpdesk follow up to ask CMS team for help: https://dsva.slack.com/archives/CT4GZBM8F/p1719445428981519
- CMS team asked DST for help, https://dsva.slack.com/archives/C01DBGX4P45/p1720016865086939.
  - DST said: Sitewide may be faster. 
  - DST has an open PR they hope to merge by ~7/8: https://github.com/department-of-veterans-affairs/content-build/pull/2095 We should make sure that's merged before starting FE work on this ticket, and verify whether it has an impact on the reported behavior

## Steps for Implementation
- Verify https://github.com/department-of-veterans-affairs/content-build/pull/2095 is merged
- Re-check reported behavior 

## Acceptance Criteria
- [x] The breadcrumbs are displaying correctly for the Family Member Hub.

**Comment by JakeBapple** [comment]
confirming that pages that are seemingly structured the same (same content type, section menu), are experiencing different breadcrumbs. The incorrect one: https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability and this is an example of one that is correct: https://prod.cms.va.gov/family-and-caregiver-benefits/life-insurance

A screenshot of the pathing on the admin side:
![breadcrumb](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/166155028/9510568a-7b7f-4dc4-bfda-31199579fb06)

**Comment by JakeBapple** [comment]
Suggested fix would be to give the incorrect one a different menu parent, save, and then change back and save to see if that helps.

**Comment by laurwill** [comment]
@JakeBapple I changed section to VACO, saved, and published. Breadcrumbs didn't change in Drupal preview or on live site after next content build. 

I changed the section back to the correct section (OCTO, Sitewide content, Family member hub), since that fix didn't seem to work. 

I'll be OOO next week, but @kristinoletmuskat will be available if you need us to do anything else! Thanks so much for your help.

**Comment by gracekretschmer-metrostar** [comment]
Thanks, @laurwill. @JakeBapple is out until 7/8 and then can pick up this work once he is back.

**Comment by anantais** [comment]
Update: It looks like this may be something that another front end team needs to alter the settings for. I am currently trying to figure out who owns the files I have found.

**Comment by jilladams** [comment]
@anantais per Slack thread today that will come back to Sitewide. Could you add your notes in comments here re: which files you're looking at / what you've figured out so far? That will help our team figure out where to start.

**Comment by gracekretschmer-metrostar** [comment]
And @anantais please include links to the public slack threads where you posted questions and help for this breadcrumb issue. Thanks!

**Comment by anantais** [comment]
I made a post in #platform-cop-frontend but a person there directed me to post in #platform-design-system. Here is the thread there: https://dsva.slack.com/archives/C01DBGX4P45/p1720016865086939

And the original slack thread: https://dsva.slack.com/archives/CDHBKAL9W/p1719423109227689

**Comment by anantais** [comment]
These are a couple of files I found that appear to reference breadcrumbs or overrides.

vets-website/src/applications/ivc-champva/10-7959C/containers/App.jsx - "family and caregiver benefits" breadcrumbs line 12
content-build/src/applications/registry.json - breadcrumbs overrides "family and caregiver benefits" line 195

I could not find any files in Drupal where I was able to change breadcrumbs. Just the general taxonomy which does not directly correspond to what is shown in breadcrumbs.

**Comment by jilladams** [comment]
Hi y'all - I took another look here, and I think we need to revisit the assumption that this doesn't start with the CMS. (@anantais Maybe you can help us understand how you ruled out CMS as the root of the issue.) I am asking, because the same incorrect breadcrumbs show in the Drupal UI for this node as they do in the VA.gov front-end: 

Incorrect crumbs: https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability
![Screenshot 2024-07-03 at 2 51 22 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/1b1efaf2-940e-416d-bd20-a72f939faf9a)

Vs. Correct crumbs: https://prod.cms.va.gov/family-and-caregiver-benefits/life-insurance
![Screenshot 2024-07-03 at 2 51 52 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/1ae5af54-770f-4b63-8163-00fdbb632303)

In our decoupled instance, that indicates that Drupal is somehow involved in setting the incorrect crumb that's being passed to the FE.

There are some very high level docs about how Breadcrumbs are built starting from the CMS in the Drupal content model docs here: https://prod.cms.va.gov/admin/structure/cm_document/note/126/breadcrumbs.  Also: your good friend @timcosgrove was instrumental in updating the breadcrumb logic while on the last contract, so may be a good person to ask about that.

**Comment by jilladams** [comment]
Noting: Took a look at the 2 files referenced further up in comments: 

https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/ivc-champva/10-7959C/containers/App.jsx#L9 - "family and caregiver benefits" breadcrumbs line 12
* This is building the breadcrumbs for this application: https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/ , unrelated to the Benefit detail page crumb reported in this issue.

https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json#L184C17-L184C135
* This section is setting the front-end breadcrumbs for https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg, also unrelated to the Benefit detail page crumb reported in this issue.


All that said: there's a chance the DST PR (https://github.com/department-of-veterans-affairs/content-build/pull/2095) may fix it, potentially, but if not, I'd like us to collectively triple check the CMS crumbs and how they are implicated, since they're showing up wonky in Drupal, too.

**Comment by jilladams** [comment]
This is a random probably bad idea. but: I did also just test in Tugboat: what would happen if we just recreate the page with busted crumbs? Will the bad crumbs repro? They do not. 

* Original page, bad crumbs: https://cms-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/family-and-caregiver-benefits/health-and-disability-0
  * Changed URL alias to add -0
* New dupe page: https://cms-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/family-and-caregiver-benefits/health-and-disability -- crumbs are perfect (why?? Who knows)
  * Gave it the original URL alias.
* Menu: https://cms-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/admin/structure/menu/manage/family-and-caregiver-benefits
  * Made sure the `Health and disability benefits` pointed to the correct URL / new dupe node, after those URL changes

Looks good in Drupal: 
![Screenshot 2024-07-03 at 3 37 07 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/aba4cf1d-90bf-4912-92d7-f9e7f017f126)

I just did a content release, FE will build here: https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/family-and-caregiver-benefits/health-and-disability.  If that looks good, we could opt to go this route in prod as well, if CAIA is comfortable with it. ... 🤷‍♀️

**Comment by jilladams** [comment]
FYI @kristinoletmuskat ^ since I know Laura's out.

**Comment by kristinoletmuskat** [comment]
@jilladams if it works, we are fine with it! I think another test would be to see whether the work y'all are doing to add the left nav would result in correct or incorrect breadcrumbs. Over in [that ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86962), Daniel's screenshot showed the same weird breadcrumbs showing up in tugboat -- no idea what's going on over there, but could we try this solution on that side too?

**Comment by jilladams** [comment]
@kristinoletmuskat Yep, the page Daniel flagged is the same page, so should fix it. If I'm not mistaken, we can get all these changes queued to go out in the same content release -- can queue that up, but would want someone from CAIA to sign off that nothing is wrong on the new/dupe page before I publish and make the swap. Are you working with someone from Content while Laura's out who could help with that?

**Comment by jilladams** [comment]
Duped content page is in draft: 
* Original: https://prod.cms.va.gov/node/65069/edit
* DUPE: https://prod.cms.va.gov/node/70374/edit -- breadcrumbs are looking correct

**Comment by kristinoletmuskat** [comment]
Yes sounds like @RLHecht can take a look!

**Comment by RLHecht** [comment]
@jilladams this dupe looks good to me to publish.

**Comment by jilladams** [comment]
Dupe is published, original node is archived, and menu has been updated. THe update is waiting on content release now. 

https://github.com/department-of-veterans-affairs/content-build/actions/workflows/content-release.yml
11535 is currently in progress. theoretically these changes will be in #11536 

And then https://www.va.gov/family-and-caregiver-benefits/health-and-disability/  should show correct crumbs. 

I'm reassigning this to myself, since this content fix should remove the need for a CMS deep dive on what happened here, and we can always revisit if another node gets into a similar state in the future.

**Comment by jilladams** [comment]
Fixed crumbs are live! https://www.va.gov/family-and-caregiver-benefits/health-and-disability/. Closing.

![Screenshot 2024-07-05 at 1 44 12 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b3019881-e0e8-4da0-a37c-b77097600382)
