### ISSUE TITLE
Evaluate ECA framework for other use cases

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18737]
## Description 
We're excited about the possibility of applying the new ECA framework to other use cases. We need to understand the types of scenarios which are reasonable for this framework and the associated general level of effort so that we can prioritize accordingly. 

## Scenarios for evaluation

- Moderation state as a trigger for a notification
  - example: when an editor saves content as "in review", a supervisor/approver is automatically notified by email 
     - assume the recipient exists at a different level than the editor (not identical sections)
  - example: editor or supervisor/approver is notified when content has been stagnant (no moderation state change for x period) 

- Outdated content iteration 
   - example: VHA editors are reminded to update/review and validate certain content (such as a mental health number) with different cadence from other outdated content notifications

- Automating processes
  - flagged facility processes
     - example: new facility can be published once editor does x - when x is complete, node is auto published
  - forms processes
    - when new form seen following migration, CAIA is notified
  - content meeting certain criteria (i.e., time since creation) is auto archived
  - content is auto-archived or replaced on defined date/time
    - example: Vet Centers have spotlights they use to promote outreach activities. If the date of the event has passed, the spotlight could be auto-archived or automatically replaced by evergreen content which is not time sensitive
  
- User management 
   - example: generate list of editors who have not accessed Drupal in x period of time and email it to leadership (or remove access)
   - example: editor who has completed training is automatically assigned role/permission

- Content delay notifications
  - example: when content build is delayed by x period of time, post Drupal banner
     - when delayed by y period, send an email to notify editors

- Publication of KB article or release notes node triggers notification on dashboard (or email to specific editor type)

## CMS considerations
CMS team needs to learn ECA and will be involved in applying it to future use cases. If we can loop CMS engineers (Jake Bapple, primarily) in on discussions / usage / use cases, that is a desired outcome.

## Acceptance criteria

- [ ] For each use case, indicate whether the framework is 
  - [ ] possible
  - [ ] a rough estimate of time/difficulty 
  - [ ] factors or dependencies which should be considered
- [ ] cc Jake Bapple when you post findings

**Comment by mmiddaugh** [comment]
@EWashb for awareness

**Comment by FranECross** [comment]
@dsasser @jv-agile6 This seems like it would be a big enough effort to have this be a spike, or a research ticket that would be pointed and placed in a sprint, instead outside it. Do you concur? Thanks in advance!

**Comment by FranECross** [comment]
Who is supervisor/approver for a particular node, and other questions that Daniel will enter into the ticket.

**Comment by dsasser** [comment]
@davidmpickett just seeing this but I'll be done by COB today, sorry I would have been happy to have you involved earlier. If you want to take a second look I'm sure there are things I incorrectly interpreted from the given scenarios, and having you look at it would help me feel better about the accuracy.

**Comment by davidmpickett** [comment]
No worries, I was just looking for any tickets in sprint that I could feasible help with. Definitely happy to review

**Comment by dsasser** [comment]
# Evaluate ECA framework for other use cases

## VACMS-18737

Issue: [https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18737](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18737)

# Evaluating the Events, Conditions, Actions (ECA) module for various use cases.

This document evaluates automation capabilities using ECA under several different scenarios. For each scenario, the document will describe if the work is possible, the overall work estimate in terms of t-shirt sizes, and any dependencies that the scenario brings.

Possible scenarios will be flagged as ✅(possible), ⚠️(maybe possible), 🛑(not possible). Possible scenarios will contain events, conditions, and actions, and maybe possible and not possible scenarios will have descriptions detailing why could or could not be achieved.

## Moderation state as a trigger for a notification

### When an editor saves content as "in review", a supervisor/approver is automatically notified by email. Assume the recipient exists at a different level than the editor (not identical sections)

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ✅ | M | A means to select/identify the correct recipient for any given content. Email content. |

This is possible to do using built-in ECA content and workflow plugins listed below. What makes this a Medium estimate is the recipient. Once we have a more concrete understanding of who the recipient is, how they are managed, and where that information is coming from in the CMS, the estimate could go down.

#### Events

* Workflow state transition (includes workflow state condition): [https://ecaguide.org/plugins/eca/workflow/events/workflow\_transition/](https://ecaguide.org/plugins/eca/workflow/events/workflow_transition/)

#### Conditions

* (none needed: built into the workflow transition event)

#### Actions

* Queue email: Create an AdvancedQueue Job and optionally enqueue it. (custom: VA.gov ECA module)

### Editor or supervisor/approver is notified when content has been stagnant (no moderation state change for x period)

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ⚠️ | M to L | The ability to track moderation stagnation. |

There is no current mechanism for tracking ‘no moderation state change for x period’. Building such a system to interact with Content Moderation in Drupal core is not a trivial pursuit. However, ECA can use any View result as input for an action, so if we can define “stagnant” as something like “latest revision of the node is in the workflow state ‘in review’, and is greater than x days old” then we can achieve that today using existing build in ECA plugins, which I have outlined below.

#### Events

* Cron: [https://ecaguide.org/plugins/eca/base/events/eca\_base\_eca\_cron/](https://ecaguide.org/plugins/eca/base/events/eca_base_eca_cron/)

#### Conditions

* (unknown)

#### Actions

* Queue email: Create an AdvancedQueue Job and optionally enqueue it. (custom: VA.gov ECA module)

## Outdated content iteration

### VHA editors are reminded to update/review and validate certain content (such as a mental health number) with different cadence from other outdated content notifications

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ⚠️ | S to L | Field level expiration tracking |

Sending mail (assumes reminding editors is being done by email) on a particular cadence is possible, but it is unclear what that cadence would be, and how it would be refreshed. This likely needs its own discovery, which is why I have such a large estimate range. Once we determine how to track the freshness of a mental health number, we’ll be able to utilize that in an ECA model.

## Automating processes

### flagged facility processes, eg: new facility can be published once editor does x \- when x is complete, node is auto published

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ✅ | S |  |

#### Events

* Entity presave: [https://ecaguide.org/plugins/eca/content/events/content\_entity\_presave/](https://ecaguide.org/plugins/eca/content/events/content_entity_presave/)

#### Conditions

* Entity compare field value: [https://ecaguide.org/plugins/eca/content/conditions/eca\_entity\_field\_value/](https://ecaguide.org/plugins/eca/content/conditions/eca_entity_field_value/)

#### Actions

* Entity workflow transition: [https://ecaguide.org/plugins/eca/workflow/actions/eca\_workflow\_transition\_editorial/\#fields](https://ecaguide.org/plugins/eca/workflow/actions/eca_workflow_transition_editorial/#fields)

### Forms processes: when new form seen following migration, CAIA is notified

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ✅ | S |  |

#### Events

* Insert content entity: [https://ecaguide.org/plugins/eca/content/events/content\_entity\_insert/](https://ecaguide.org/plugins/eca/content/events/content_entity_insert/)

#### Conditions

* (none)

#### Actions

* Queue email: Create an AdvancedQueue Job and optionally enqueue it. (custom: VA.gov ECA module)

## Content meeting certain criteria (i.e., time since creation) is auto archived

### Content is auto-archived or replaced on defined date/time. Example: Vet Centers have spotlights they use to promote outreach activities. If the date of the event has passed, the spotlight could be auto-archived or automatically replaced by evergreen content which is not time sensitive

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ✅ | S to L | Evergreen content A means to parse Event data from a Spotlight |

This particular scenario is M or larger because spotlights are CTAs with Rich Text fields, rather than structured event data, which means we would need to account for that, and parsing Rich Text is not without its cost in terms of performance.

However, in general, content meeting a certain criteria can be affected by ECA in its current form, or with custom ECA Events, Conditions, or Actions, so the issue at hand pushing this to M and L is with existing data structures, not with ECA itself.

## User management

### Generate list of editors who have not accessed Drupal in x period of time and email it to leadership (or remove access)

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ✅ | S to M |  |

Acting on a list of entities is built into ECA Views, and is currently in use in VA production ECA models for Aging Content notifications. These models are built similarly to [this](https://ecaguide.org/library/simple/send_email_to_users_of_a_given_role/) ECA provided example that iterates over a list of users to send emails.

#### Events

* Cron: [https://ecaguide.org/plugins/eca/base/events/eca\_base\_eca\_cron/](https://ecaguide.org/plugins/eca/base/events/eca_base_eca_cron/)  
* ECA custom event (entity-aware): [https://ecaguide.org/plugins/eca/content/events/content\_entity\_custom/](https://ecaguide.org/plugins/eca/content/events/content_entity_custom/)

#### Conditions

* (none)

#### Actions

* Views: Execute query: [https://ecaguide.org/plugins/eca/views/actions/eca\_views\_query/?h=views+query](https://ecaguide.org/plugins/eca/views/actions/eca_views_query/?h=views+query)  
* Trigger a custom event (entity-aware): [https://ecaguide.org/plugins/eca/content/actions/eca\_trigger\_content\_entity\_custom\_event/](https://ecaguide.org/plugins/eca/content/actions/eca_trigger_content_entity_custom_event/)

## Content delay notifications

### When content build is delayed by x period of time, post Drupal banner; when delayed by y period, send an email to notify editors.

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ✅ | L |  |

While there has been some Github integration wired into the CMS for controlling content releases, there lacks any integration of this with ECA, which is a bit of an unknown lift. Given the complexity of the two, this would likely be a large lift.

## Publication of KB article or release notes node triggers notification on dashboard (or email to specific editor type)

| Possible | Estimate | Dependencies |
| :---- | :---- | :---- |
| ✅ | M | Email content |

Triggering on node changes is a core function of ECA Content, and email delivery is a capability we are already leveraging in Aging Content notification models, so this type of activity is relatively easy to implement generally speaking. However, there are complexities doing things like creating new notifications (lifecycle ownership of content created by ECA), or creating complex content (ECA is not great at creating deeply nested structured content), so I have put a M estimate on this type of scenario.

**Comment by davidmpickett** [comment]
Just read through it and all of the assessments of complexity match my understanding of the problem space(s). I will hold any additional thoughts/comments I have about specific use cases for now since that would be getting deeper into things than we need to. This is a great high level overview which is exactly what is needed now

**Comment by jilladams** [comment]
Findings are documented, ready for review with Product / CMS team. Closing per planning discussion.

**Comment by FranECross** [comment]
@mmiddaugh I've reviewed the findings and can add the information to the epic for an overall view. Please let me know which items you're interested in implementing and I'll cut tickets for refinement/prioritization. 

BTW I think these are good candidates to pursue in the short term (in order of priority):
- Moderation state as a trigger for a notification
- Forms processes: when new form seen following migration, CAIA is notified
- Automating processes: flagged facility processes, eg: new facility can be published once editor does x - when x is complete, node is auto published
- Publication of KB article or release notes node triggers notification on dashboard (or email to specific editor type)
- User management: Generate list of editors who have not accessed Drupal in x period of time and email it to leadership (or remove access)
- Content meeting certain criteria (i.e., time since creation) is auto archived: Content is auto-archived or replaced on defined date/time. Example: Vet Centers have spotlights they use to promote outreach activities. If the date of the event has passed, the spotlight could be auto-archived or automatically replaced by evergreen content which is not time sensitive

And this one, using the avenue Daniel suggested:
- Editor or supervisor/approver is notified when content has been stagnant (no moderation state change for x period)
  - Stagnant = latest revision of the node is in the workflow state ‘in review’, and is greater than x days old

**Comment by jilladams** [comment]
Noting: Michelle / Fran met on 11/6 to discuss ECA options out of the SPIKE in #18737. Notes from the SPIKE were shared as a [SharePoint doc](https://dvagov.sharepoint.com/sites/SitewidePublicWebsites/_layouts/15/doc.aspx?sourcedoc=%7b0b77bf03-e74a-40f5-9ceb-9a5d5a6d8b66%7d&action=edit) of potential story mapping / effort, and stories have been cut for the epic.
