### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event 'onsite-search-results-change' on FE Find Forms

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18791]
## Description

The duplicate event(s) on the FE page **Find Forms** identified and listed on line 138 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: (Search results) sorting by a value
- **Event name:** onsite-search-results-change
- **Other event data:** 
  - "search-query: {search query}
  - search-page-path: ""/find-forms""
  - search-results-change-action-type: ""sort""
  - search-results-change-action-label: {dropdown selection, such as ""closest match""}
  - search-results-pagination-current-page: {current paginated page number}
  - search-results-total-count: {total of search results}
  - search-results-total-pages: {total of search result pages}
- **Example URL:** https://www.va.gov/find-forms/?q=1010

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
Closing as a no-op. It turns out that the `va-select` web component that this sorting behavior uses only has opt-in baked-in analytics. Meaning: if we want the web component to fire baked-in analytics, we have to tell it to do so, and we currently aren't. The `onsite-search-results-change` custom event is the only event being fired on this sort functionality currently, so we're good to go here.

<img width="546" alt="Screenshot 2024-08-01 at 4 41 35 PM" src="https://github.com/user-attachments/assets/3ca7ba4d-4a18-40f2-822b-7a29726c923a">
