### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event 'view_search_results' on FE Find Forms

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18790]
## Status
**[2024-09-10] [Fran]** Unblocked; moving to Ready.
**[2024-09-03] [Fran]** There is a DST defect blocking this; the DST ticket was closed as a No Op because the PW team is going to fix it and contribute back to the Design System. PW Ticket (in QA/Code Review) [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18846).

## Description

The duplicate event(s) on FE Find Forms identified and listed on line 133 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: (When searching for forms)
- **Event name:** view_search_results
- **Other event data:** 
  - "search-page-path: ""/find-forms""
  - search-query: {query}
  - search-results-total-count: {count} and \
  - search-results-total-pages: {total pages}
  - search-selection: ""Find forms""
  - search-typeahead-enabled: false
  - search-location: ""Find a Form""
  - sitewide-search-app-used: false
  - type-ahead-option-keyword-selected: undefined
  - type-ahead-option-position: undefined
  - type-ahead-options-list: undefined
  - type-ahead-options-count: undefined"
- **Example URL:** https://www.va.gov/find-forms

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
Putting this ticket into Blocked. The `va-search-input` web component (that Find Forms uses) does not make use of the `disable-analytics` prop that we'd want to use here (to lean on our custom event instead). The prop applies to the component, but the baked-in event still fires. I opened an issue with DST here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3122. When that issue is resolved and the component release is made, we can resolve this ticket.

**Comment by chriskim2311** [comment]
Verified on Prod only one event is being recorded, closing!
