### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event view_search_results on FE Home page search

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18797]
## Status
**[2024-09-10] [Fran]** Ticket unblocked. Moving to Ready.
**[2024-09-03] [Fran]** PW Ticket (in QA/Code Review) [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18846)
**[2024-08-07] [Fran]** This ticket is blocked because the va-search-input web component (that homepage search uses) does not make use of the disable-analytics prop that we'd want to use here (to lean on our custom event instead). The prop applies to the component, but the baked-in event still fires.

We have a DST issue open for this issue and agreed to contribute to their repo to fix it with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18846, but it is moving slowly due to local dev issues and after it is merged will still require a release on DST's end to be available.

## Description

The duplicate event(s) identified on the FE **Home Page** and listed on line  in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: (After entering a search query in the dropdown in the header) clicking the search button
- **Event name:** view_search_results
- **Other event data:** 
  - "action: ""Homepage - Search""
  - search-page-path: {current URL}
  - search-query: {query}
  - search-results-total-count: null
  - search-results-total-pages: null
  - search-selection: ""All VA.gov - In page search""
  - search-typeahead-enabled: false
  - search-location: ""Homepage Search""
  - sitewide-search-app-used: false
  - type-ahead-option-keyword-selected: null
  - type-ahead-option-position: null
  - type-ahead-options-list: null
  - type-ahead-options-count: null"
- **Example URL:** https://www.va.gov/

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by aklausmeier** [comment]
@randimays Can you clarify if this is the search in the header or the in-page search w/in search tools section on homepage?

**Comment by randimays** [comment]
@aklausmeier This is for the in-page search within search tools on the homepage

**Comment by randimays** [comment]
Didn't catch this in refinement. This ticket is blocked because the `va-search-input` web component (that homepage search uses) does not make use of the disable-analytics prop that we'd want to use here (to lean on our custom event instead). The prop applies to the component, but the baked-in event still fires.

We have a DST issue open for this issue and agreed to contribute to their repo to fix it with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18846, but it is moving slowly due to local dev issues and after it is merged will still require a release on DST's end to be available.

This ticket is unlikely to be unblocked this sprint.

**Comment by chriskim2311** [comment]
Verified on prod, closing!
