### ISSUE TITLE
[Aging Content] Aging content notification for Homepage news spotlight block

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#19077]
## Status
**[2024-09-04] [Fran]** Verbiage updated and ticket moved to Next refinement. A separate ticket will be created for the KB article updates.
**[2024-08-29] [Fran]** Awaiting review/approval of email verbiage, as well as KB article text updates (comment below).

## Value to Veterans
Visitors to the VA.gov homepage want to complete priority tasks and engage with relevant content. By definition, content displayed as "news" should be regularly refreshed to be interesting, timely, and relevant to readers. 
The Home Page News Spotlight Block still points to a news story published on May 7, 2023, shortly before the redesigned homepage became the default. 

## Overview
An aging content notification for full-width banners (Epic #15504) was the first use of the ECA framework. Other content types are still notified by the original notification system set on a 365 day cadence.

To ensure the news promo spot on the homepage is regularly refreshed and provides timely information to Veterans and other users of VA.gov, we need to implement biweekly notifications for the Home Page News Spotlight Block. 

This notification should not be applied to the Home Page Benefit Promo Block. (The Home Page Benefit Promo Block will be updated shortly and considered evergreen content for the interim. ) Auto-archiving the content is out of scope for this work. We will evaluate the feasibility of a feed from VA News as a separate effort. 

## Headlines
- **VA stakeholders** - Asst. Secretary, OCTO, OPIA 
      - Adam Farina (Assistant Secretary) approved the implementation of notifications for the news promo block on 8/29/2024.
- **OCTO lead** - Michelle Middaugh
- **Is this project tracked to an upcoming event or congressional deadline?** No

## Details

- **Who is the primary user?** 
      - OPIA
- **Who is the primary audience?** 
      - Veterans and other beneficiaries
- **What are the business goals?**
      - Ensure homepage content is routinely refreshed with automatic reminders to ensure homepage content remains timely and relevant
- **How does this map to our North Star?**
      - CSAT improvement
- **What is OCTO's role in this work?**
     - Extension of ECA framework to content types beyond full-width banners

**Known risks**
Notifications may not lead to homepage news spotlight content being refreshed more frequently

### Text for the email sent three (3) days before expiration date

**Subject:** 
Home Page News Spotlight Block content expiring soon

**Body:** 
As a reminder, Home Page News Spotlight Blocks were designed to provide a curated top news article “promo” to highlight or promote content on the homepage that is not directly related to new or changed benefit information.

Unless there is a compelling reason, the Home Page News Spotlight Blocks should not promote the same content for longer than fourteen (14) days. Updating the content on a regular basis ensures it remains interesting, timely, and relevant to readers. Refreshing this content regularly also improves SEO and page traffic. 

Your published Home Page News Spotlight Block titled '[Title of Home Page News Spotlight Block]' will soon expire. Please plan to refresh this content by [expiration date]. 

To extend the display of the content, log in to Drupal, edit the block, resaving it with a comment to that effect. The 14-day countdown window will reset.

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight) for tips and best practices to manage compliance.

**Need help?**
Contact VA.gov Drupal CMS support at support@va-gov.atlassian.net

### Text for the email sent the morning of the expiration date

**Subject below:**
Home Page News Spotlight Block content is now expired

**Body:** 
Your published Home Page News Spotlight Block titled '[Title of Home Page News Spotlight Block]' has displayed for fourteen (14) days. Please replace the content of this published Home Page News Spotlight Block.

If there is a compelling reason to continue this particular display, you can reset the 14 day countdown window by logging into Drupal, editing the block, and resaving it with a comment to that effect. 

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight) for tips and best practices to manage compliance.

**Need help?**
Contact VA.gov Drupal CMS support at support@va-gov.atlassian.net

## Acceptance Criteria 

- [x] - Home Page News Spotlight Block content type expires two weeks (14 days) after it was last published. 
- [x] - A notification email instructing the editor to edit to extend the timeframe is sent to the last published author based on the set expiration 3 days before expiration date.
- [x] - A 2nd notification email is sent to the last published author based on the expiration date at midnight the morning of the  expiration date.
- [x] - The editor can refresh content in the Home Page News Spotlight Block at any time before expiration and the clock will "reset" for the newly published content.  
- [x] - The editor can edit the Home Page News Spotlight Block when still within (or outside) the chosen date range, and the expiration date is 'reset'. (we don't actually yet auto-archive the content, so the date is reset anytime the content is updated).
- [x] - The notification email instructs the editor to edit to extend the timeframe and points to the relevant KB article.
- [x] - Notify PM (@FranECross) to update KB article
- [x]   - Relevant KB article is updated 
- [x] - Help desk is informed
- [x] - QA testing:
   - [ ] Drupal admin will have to make an edit to receive the email and verify

**Comment by FranECross** [comment]
@mmiddaugh Using the template of the notification emails we're using for full-width banner alerts, I edited the text to be in line with the Homepage News Spotlight Block. Will you please review and offer edits/approve? Is there anyone else you'd like to review? Thanks in advance!

### Text for the email sent three (3) days before expiration date

**Subject below:**
Please update or archive your Home Page News Spotlight Block content by [expiration date]

**Body below:**
Your published Home Page News Spotlight Block titled '[Title of Home Page News Spotlight Block]' will expire on [expiration date]. Please plan to archive, or edit to extend display of, this content by the expiration date noted above.

As a reminder, Home Page News Spotlight Blocks are to be used to provide timely news to Veterans, their caregivers, family members or survivors and should display for no longer than 14-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the banner, simply edit with a comment to that effect, and the 14-day countdown window will reset.

For more information, you can read this [Knowledge Base article](link to article) for tips and best practices to manage compliance.


### Text for the email sent the morning of the expiration date

**Subject below:**
Home Page News Spotlight Block has displayed for fourteen (14) days

**Body below:**
Your published Home Page News Spotlight Block titled '[Title of Home Page News Spotlight Block]' has displayed for fourteen (14) days. In order to meet the purpose of this type of content, please plan to archive, or edit to extend display of, this published Home Page News Spotlight Block by EOD today.

As a reminder, Home Page News Spotlight Blocks are to be used to provide timely news to Veterans, their caregivers, family members or survivors and should display for no longer than 14-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of this banner alert, simply edit it with a comment to that effect, and the 14-day countdown window will reset.

For more information, you can read this [Knowledge Base article](link to article) for tips and best practices to manage compliance.

**Comment by FranECross** [comment]
Here is the proposed update to this section of the [KB article](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight): 

### Content limitations and best practices
#### Content

In order to ensure a good user experience and align with the “bite-sized” content strategy for this content area, character limits are enforced on length of content.
- Headline is restricted to 55 characters, including spaces
- Promo text is restricted to 125 characters, including spaces
- Home Page News Spotlight Blocks are to be used to provide a curated top news article “promo” to highlight or promote content on the homepage that is not directly related to new or changed benefits information for beneficiaries news to Veterans, their caregivers, family members or survivors and should display for no longer than 14-days, unless there’s a compelling reason to extend display of the content. Please note that this content should be regularly updated to increase SEO and page traffic.
- Notification emails will be sent to the last publisher of a home page news spotlight block three days prior to day fourteen, and then again on the morning of day fourteen (expiration date) reminding them to either archive the banner, or update by adding a comment, which will then reset the 14-day window.
- Call to action text is governed by a drop-down selection, which currently contains one option: “Read the full article.” This is the most accessible default language.
- Other options for the drop down can be considered in the future.

**Comment by aklausmeier** [comment]
@FranECross The following sentence is quite long and suggest breaking up a bit for ease of readability. 

> As a reminder, Home Page News Spotlight Blocks are to be used to provide a curated top news article “promo” to highlight or promote content on the homepage that is not directly related to new or changed benefits information for beneficiaries news to Veterans, their caregivers, family members or survivors and should display for no longer than 14-days, unless there’s a compelling reason to extend display of the content.

**Comment by mmiddaugh** [comment]
@FranECross, for brevity, I'd suggest this text 

**For the 3 day reminder:** 
Subject: Home Page News Spotlight Block content expiring soon

Body: 
As a reminder, Home Page News Spotlight Blocks were designed to provide a curated top news article “promo” to highlight or promote content on the homepage that is not directly related to new or changed benefit information.

Unless there is a compelling reason, the Home Page News Spotlight Blocks should not promote the same content for longer than fourteen (14) days. Updating the content on a regular basis ensures it remains interesting, timely, and relevant to readers. Refreshing this content regularly also improves SEO and page traffic. 

Your published Home Page News Spotlight Block titled '[Title of Home Page News Spotlight Block]' will soon expire. Please plan to refresh this content by [expiration date]. 

To extend the display of the content, log in to Drupal, edit the block, resaving it with a comment to that effect. The 14-day countdown window will reset.

For more information, you can read this [Knowledge Base article](link) for tips and best practices to manage compliance.

**For the day of**

Subject: Home Page News Spotlight Block content is now expired

Body: 
Your published Home Page News Spotlight Block titled '[Title of Home Page News Spotlight Block]' has displayed for fourteen (14) days. Please plan to replace the content of this published Home Page News Spotlight Block by EOD today.

If there is a compelling reason to continue this particular display, you can reset the 14 day countdown window by logging into Drupal, editing the block, and resaving it with a comment to that effect. 

For more information, you can read this [Knowledge Base article](link) for tips and best practices to manage compliance.

**Comment by FranECross** [comment]
email and KB article text reviewed and updated where necessary to remove reference to archiving.

**Comment by dsasser** [comment]
## End of Sprint Status Update 10-30-24
Work is complete and the PR has PW approval. We need Platform CMS approval due to CODEOWNERS being triggered for devops CMS engineers (some of the code added by the PR is in the va_gov_notifications module which is also used by the Outdated Content work, but we are not altering any existing logic used by the Outdated Content module). I will engage with the CMS team via Slack in the morning.

**Comment by jilladams** [comment]
DaveC received the email today!

![Image](https://github.com/user-attachments/assets/99e294c1-5047-41d6-b070-eb8394ab86ad)

@FranECross there are some ACs here for you as follow up to update KB article and inform helpdesk. Reassigning to you.

**Comment by jilladams** [comment]
Yep! In that channel, there's a @cms-helpdesk user group we can ping

**Comment by FranECross** [comment]
Help desk alerted in Slack [here](https://dsva.slack.com/archives/CDHBKAL9W/p1727988156330979).
