### ISSUE TITLE
Explore why preview server went down during cert renewal

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19072]
## User Story or Problem Statement
The CMS team needs to better understand why the preview server displayed an error during the cert renewal process so that it can be prevented in the future. 

## Description or Additional Context 
During the certificate renewal process, editors began reporting that they saw an error when they tried to preview content in Drupal CMS. Due to competing priorities (prod going offline and urgency of finalizing the certificate renewal), the CMS team were not able to determine why the preview server was displaying an error, but assumed that once the certificate renewal process was complete, the preview server would no longer display the error. That assumption was correct and after the certificate renewal process was complete and daily deploy was run, the preview server began to operate as expected again. Since the certificate renewal process will happen again, we want to explore how we can prevent this from happening again. 

## Reference Links
- https://easyretro.io/publicboard/NqWKfJWUr2dFRoCJjX2ybXcRyws2/106dbee4-53b0-4b2c-97a7-29c9080f6158
- https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3353247840/Draft+Postmortem+2024-07-25+25+30+CMS+Prod+Offline+Incidents#Certificate-Renewal
- https://dsva.slack.com/archives/CT4GZBM8F/p1722019888224209

## Steps for Implementation
- Timebox discovery to half a day. 

## Acceptance Criteria
- [ ] A write up of what was found during the four-hour research session in this ticket.

**Comment by timcosgrove** [comment]
Also let's discuss w/ @nfpappas-oddball how the cert is applied to the preview server - whether it's direct or via LB - and whether that might have contributed to the issue.

**Comment by 7hunderbird** [comment]
The short summary is that `content-preview` doesn't use HTTPS and a renewal wouldn't be able to break it.

---

https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/content-preview-prod.yml#L23

![Image](https://github.com/user-attachments/assets/23d1d36e-ed5e-4daa-968b-ca53a63c3c2b)

1. The target groups are defined by protocol.  If there were a https protocol target group for `content-preview` we'd have something to investigate.

Because we don't, there's no possible way there could be a correlation between the cert renewal and the root cause of the issue.

2. We won't be able to determine a root cause because the logs for Jenkins don't go back that far.
