### ISSUE TITLE
Discovery to where Sentry is used in Drupal CMS and Content Build

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19076]
## User Story or Problem Statement
The platform team needs to understand how and where Sentry is being used. 

## Description or Additional Context 
Product Platform team needs us to identify how and where the CMS team is using Sentry because the platform team is planning on retiring Sentry. For the CMS team's usage, CMS uses the package called Raven (not Sentry) to call Sentry. Clint Little from Platform team will have the best insight to understand platform team's plan of action to move away from Sentry. 

## Related Links
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17230
- https://vfs.atlassian.net/wiki/spaces/PPT/pages/3356917782/Sentry+Usage+by+other+teams

## Platform questions to be answered
- How is Sentry used?
- Is your Sentry data available in Data Dog?

## Steps for Implementation
- Identify how and where CMS team is using sentry by going through the CMS and Content Build code base. 
- For the places in the code base that are found, verify that the data is reaching Sentry. 
- Fill out platform team's sentry survey. 

## Acceptance Criteria
- [x] Where and how Sentry is used in Drupal CMS.

**Comment by anantais** [comment]
This module is installed on the Drupal production site: https://www.drupal.org/project/raven

It looks like this module is currently sending info to Sentry on Javascript errors, PHP errors and requests, and performance tracing.

**Comment by anantais** [comment]
Note: I will be adding comments here and filling out Platform's Sentry survey when I have completed discovery.

**Comment by anantais** [comment]
Logs when content editors input incorrect data
-lots of sql and database specific errors
-SQLSTATE errors are also recorded in Drupal reports at /admin/reports/dblog
-GraphQL errors logged
-cannot find similar metrics in Datadog - only API get/post messages


Examples:
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9D\x90\x91\xF0\x9D...' for column `dsva_cms_prod`.`search_api_db_content`.`field_body` at row 1: INSERT INTO "search_api_db_content" ("aggregated_moderation_state", "aggregated_published", "aggregated_title", "rendered", "body", "field_additional_information_abo", "field_answer", "field_banner_alert_situationinfo", "field_body", "field_content_block", "field_full_story", "field_hservice_appt_leadin", "field_image_caption", "field_operating_status_more_info", "field_press_release_fulltext", "field_va_form_title", "moderation_state", "name", "status", "type", "uid", "search_api_datasource", "search_api_language", "item_id") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14, :db_insert_placeholder_15, :db_insert_placeholder_16, :db_insert_placeholder_17, :db_insert_placeholder_18, :db_insert_placeholder_19, :db_insert_placeholder_20, :db_insert_placeholder_21, :db_insert_placeholder_22, :db_insert_placeholder_23); Array

Alternative text cannot contain file names. polygon_image.png was submitted.

Alternative text (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) cannot be longer than 150 characters. 152 characters were submitted.


Drupal\simplesamlphp_auth\Exception\SimplesamlphpAttributeException: Error in simplesamlphp_auth.module: no valid "adUPN" attribute set. in Drupal\simplesamlphp_auth\Service\SimplesamlphpAuthManager->getAttribute() (line 284 of /var/www/cms/docroot/modules/contrib/simplesamlphp_auth/src/Service/SimplesamlphpAuthManager.php).

RuntimeException while trying to render item entity:node/72610:en with view mode search_index for search index Content: Failed to start the session because headers have already been sent by "/var/www/cms/docroot/vendor/symfony/http-foundation/Response.php" at line 1315. in Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() (line 132 of /var/www/cms/docroot/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php).

**Comment by anantais** [comment]
After monitoring this channel for approximately two days, I am satisfied that it is capturing the sane data as Sentry (in addition to a lot of other data): https://vagov.ddog-gov.com/dashboard/vnk-g4s-fru/cms-prod--staging?fromUser=false&refresh_mode=sliding&from_ts=1726685243041&to_ts=1726688843041&live=true

I also verified that there no longer appear to be any Sentry alerts in our #cms-notifications slack channel.

I am going to fill out the sentry survey.

**Comment by anantais** [comment]
We will also need a ticket to uninstall Raven from the CMS.
