### ISSUE TITLE
Content audit search: Content types list is not visibly sorted

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19173]
## User Story or Problem Statement
As a CMS user performing a content audit search, 
I want to be able to select relevant content types easily, 
so that I get relevant results.

## Description or Additional Context 

On the content audit search, the list for content types is not visibly sorted. https://prod.cms.va.gov/admin/content/audit/search

If you inspect, it becomes clear that it's sorted by content type machine name. However, when machine names are no longer used as the popular / common name for a content type, that makes the list weird to navigate. 

![Screenshot 2024-09-10 at 10 21 10 AM](https://github.com/user-attachments/assets/c40a8dd8-172b-4749-ae65-36183a78c409)

## Acceptance Criteria
- [ ] Content type list on content audit search uses a visible sort for better UX

**Comment by jilladams** [comment]
I became annoyed by this, talked to DaveP about it, and he POCed a fix that would alpha sort this list by the value used in the Select, rather than the machine name. SO: I'm cutting the ticket to provide a pathway to merge that improvement.

**Comment by davidmpickett** [comment]
@jilladams PR is ready for review and approval. I'll let you ask CMS team for review

**Comment by davidmpickett** [comment]
Confirmed in prod. The first result is still out of order, but otherwise alpha: https://prod.cms.va.gov/admin/content/audit/search

![Screenshot 2024-09-16 at 4 19 57 PM](https://github.com/user-attachments/assets/64be6ebd-7045-4fe9-95d7-9f3e6757d3d9)


![Screenshot 2024-09-16 at 4 20 05 PM](https://github.com/user-attachments/assets/b38b6d66-9544-4bac-a213-05506314f34a)
