### ISSUE TITLE
Identify and Scope Removal of PII (Drupal username/email address) in Datadog 

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19183]
## User Story or Problem Statement
As OCTO Lead Security Engineer, I need to understand the where there is PII leak from Drupal data in Datadog, how it impacts users, and level of effort to remove that data.

## Description or Additional Context 
If there are other instances where employee emails are used in Data Dog, scope out those instances (including level of effort) and then regroup with Jonathan about how he wants to move forward. Note: in Drupal CMS, the username is the user's email address. 

## Guidance on what is PII by VA Security
- https://dsva.slack.com/archives/C01CJV0L9PS/p1725992605856549

## Steps for Implementation
- Audit the data within Data Dog and identify queries where Drupal's username and/or email address are used.
- For each instance where it is used, identify the level of effort to remove the username and/or email address, scope of impact to users, and identify if the data needs to be replaced with UID.
- Synthesize each finding into a task ticket in Github.

## Acceptance Criteria
- [x] A documented understanding of all the areas where username or email address is used in Data Dog that can be used by VA Platform Security (Jonathan Kamens, specifically)  and CMS team to understand a path forward for a mitigation plan. 

## Tickets 
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19177

**Comment by timcosgrove** [comment]
In addition to patching of the CMS code to modify outgoing log messages with PII (this work has been completed), there is the possibility of modifying logs that are in the process of being sent to Datadog. This takes the form of defining configuration rules for the Datadog Agent which would then be deployed to the CMS application as part of BRD.

We can 'filter' logs:
https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile&site=gov#filter-logs
This takes the form of blocking a log entry from being sent to Datadog if it contains a pattern.

It is also possible that we could scrub logs using `mask_sequences` rules: 
https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile&site=gov

This would be a substitution and redaction of sensitive information, without otherwise being destructive to the logs. 

It is unclear if we actually have access to the latter functionality, as it is in private beta. I have a question out to the COP.

**Comment by timcosgrove** [comment]
We do not have the `mask_sequences` functionality enabled, so we are limited to filtering.

**Comment by gracekretschmer-metrostar** [comment]
Since we have identified all the areas where PII and a mitigation plan, I am going to close this ticket.
