### ISSUE TITLE
SPIKE: Do we need a code exception for Manila and the Get Updates box?

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19272]
There's a Get Updates box at the bottom of the facility pages. Is there something about Manila that would require exceptions to be made in the code?

## Background
- When @davidmpickett did a proof of concept for Manila, he got errors related to the Get Updates box when attempting a Content Release. He cut those bits out of the code in order to test the basic concept
- https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/health-care-region.js#L195
- Likely related to this being a System that doesn't have a published VAMC system page at it's root
- Does VAMC system Drupal node need to be Published but excluded creating a page from Content build? We do something similar with Lovell Federal VAMC system
-

**Comment by Agile6MSkinner** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/19272?planning-poker) with Zenhub @dsasser @eselkin

**Comment by eselkin** [comment]
Probably needs a conditional to handle it.

**Comment by eselkin** [comment]
When I publish Manila VA Clinic or Manila VA System I get the Get Updates Box, so not sure why we're saying it does't work. Maybe if only one of those is published it doesn't work? Like without the system or something? But I'd need @davidmpickett to identify which gets published the system or the clinic only or do both get published, but since the clinic doesn't link to the system then it just shows the clinic as the base page?

**Comment by eselkin** [comment]
With just Manila VA Clinic published (not the VA System). I get the Updates block and the correct GovDelivery codes ("1") for the signups as in the CMS. However, I do not get the side nav, but I think that's another ticket.

**Comment by eselkin** [comment]
So the limitation on side nav is due to: https://github.com/department-of-veterans-affairs/vets-website/blob/06563d07360e3960525c69dd60e73e8a7bfcd8a7/src/platform/site-wide/side-nav/helpers.js#L48

I'll put the rationale in the other ticket. It's coming across correctly from content-build to vets-webiste. But v-w processes out the dependent pages for some reason.

**Comment by jilladams** [comment]
## Follow ups
*  If we publish and then archive the Manila system, the Get Updates box works correctly on the Clinic facility page (which will act like a system for Manila)
- [ ] @eselkin In order to update "system-level" data after Publish > Archive, we need to test Publish > Archive > Draft to prove that this will work and won't break Get Updates box (or anything else). (That all needs to happen in one Content Release, so we don't break stuff in Prod for Manila.)
- [ ] @Agile6MSkinner We probably need to do something programmatic to prevent the Manila System node from ever staying published. 
- [ ] @eselkin @Agile6MSkinner we need to figure out what the work is out of this ticket

**Comment by eselkin** [comment]
Archive -> Draft does update the system Get Updates information
![Image](https://github.com/user-attachments/assets/ac9eba38-6cfa-43f8-8599-5ad4a35b3e0d)

**Comment by jilladams** [comment]
Nice! I think that means the 2 things left to sort are: 
1. Drupal: a mechanism to never let Manila System move to Published. 
  * In prod, we need to move to Published > Archived, nowish.
  * After that move, you can go Archive > Draft, and Draft > Archive, and Manila System should never be allowed to publish again.
2. The menu questions.

**Comment by jilladams** [comment]
From Slack : https://dsva.slack.com/archives/C0FQSS30V/p1727974260585079
Plan for managing the system: 
> Right now: we publish > Archive the system node, so it's handled for launch.
> We make a ticket to prevent any future publishing of the System to the FE, a la Lovell. Not a launch blocker, immediate fast follow

I stubbed this ticket for fast follow: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19406

**Comment by jilladams** [comment]
Today I published / Archived the prod VAMC System, FYI. 

@eselkin is the rest of the menu stuff here resolved? I feel like we have tickets in sprint knocking out the actual wokr, and we can say this is done?

**Comment by eselkin** [comment]
Right. For the system that's it.
