### ISSUE TITLE
SPIKE: Forms migration overwrote When to Use data on VA Form 21-0781

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19429]
## Description
https://dsva.slack.com/archives/C52CL1PKQ/p1728326132933719

On September 26, 2024 a CMS migration revision log shows modifications to When to Use field content on Form 21-0781.
* Revision: https://prod.cms.va.gov/node/6022/revisions

### User story
**AS A** Sitewide Content editor
**I WANT** "When to use" copy to retain CAIA's changes and not get overwritten by Forms DB migrations
**SO THAT** we ensure veteran-facing copy meets VA.gov governance / guidelines.

### Engineering notes / background
I did pull last migration CSV and narrow it down to only this form, in this CSV. There's nothing that mirrors the sort of content update from the CMS migration revision that compares:
[va_forms_data-10-6-2024.csv](https://github.com/user-attachments/files/17283267/va_forms_data-10-6-2024.csv)

We need to verify whether anything in the Forms migration is mapped to update / modify When to Use field. 
* If so: please document which source field writes to When to Use, and add the git blame ticket reference if there is one
* If not: ...we need to define a plan during refinement?

## Acceptance criteria

- [ ] Provide notes to explain field mapping for forms migration, and update https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md with those notes
- [ ] If migration does not modify "When to Use" field, ...

**Comment by davidmpickett** [comment]
Copying my notes from Slack:

**Revision Confusion**

Looking at the revision history this seems to be a case of draft changes from one user getting demoted from latest revision when another user publishes a change.

There was a published revision on 7/11 and then a whole bunch of draft revisions that were never published by Katherine. Then the Form migration made a small change to the Revision Date on 9/26. If you compare between the two most recent Published revisions all that the migration changed is the form revision date. https://prod.cms.va.gov/node/6022/revisions/view/903752/920799/split_fields

This is a known quirk of the revisions functionality in Drupal. See #2501 for previous exploration of ways to make it easier to recover draft revisions after a competing change has happened on published revisions.

**Migration situation**

The Process tab shows the mapping of fields the Forms Migration:
https://prod.cms.va.gov/admin/structure/migrate/manage/forms/migrations/va_node_form/process

Since field_va_form_usage is not on that list, that means the migration doesn't update that field.

**My conclusion**

- The migration correctly updated the Form Revision Date. 
- It also correctly ignored all the Draft Revisions. If it had published those changes when updating the Revision Date, that would be skipping the editorial process.
- Revisions are confusing. We might need some better documentation on how to recover draft work. Right now all we have about Reverting revisions is a mention in the [View Revisions](https://prod.cms.va.gov/help/cms-basics/how-to-view-revisions) kb article. Doesn't really address the complexities or resolving conflicts when you want to recover old drafts edits while also respecting the published edits

**Comment by jilladams** [comment]
Amazing. It's still a little confusing to me that the migration can modify the last published version of a node and not also publish all the draft content, but: it tracks with the evidence provided, despite my confusion. 

I'm going to close this ticket as complete, since we deduced the root cause. I've shared the update with CAIA here: https://dsva.slack.com/archives/C01K37HRUAH/p1728336696787529

And if we opt to Do Something About this UX, it'll need to be via a CMS collab cycle process, since it's core to Drupal. Woo.
