### ISSUE TITLE
Create Service for Banner Interactions and Data Retrieval (Story 3)

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19450]
## Description
Develop a new service for managing banner interactions and storing the necessary data in production. This includes setting up initial database ACTIVE RECORD for storing alert banner data in the pSQL database, ensuring scalability and reliability for full deployment.

**Sequence Note:** This task can be done after story 2 and in parallel with story 4, but must be completed before Story 6.

## Testing & QA
- [ ] Code Review

### Roles / assignments
* **Code review:** 

## Acceptance criteria
- [ ] vets-api DB parity with Drupal on published banners
- [ ] New app/module created for managing production banner interactions
- [ ] Production-ready database models for storing alert banner data created

**Comment by dsasser** [comment]
@SnowboardTechie 
I took a first attempt at content modeling for a Banner model that could work for both the MVP (VAMC banners w/o situation updates) and future alerts/banners.

I ended up with this schema (described as a FactoryBot object because it was handy):

```ruby
FactoryBot.define do
  factory :banner do
    entity_id { 1 }
    entity_bundle { 'full_width_banner_alert' }
    headline { 'Important Alert!' }
    alert_type { 'warning' }
    show_close { false }
    content { '<p>This is a warning alert.</p>' }
    context {
      [
        {
          entity: {
            title: 'Operating status | VA Puget Sound health care',
            entityUrl: {
              path: '/puget-sound-health-care/operating-status'
            },
            fieldOffice: {
              entity: {
                fieldVamcEhrSystem: 'vista',
                title: 'VA Puget Sound health care',
                entityUrl: {
                  path: '/puget-sound-health-care'
                }
              }
            }
          }
        }
      ]
    }

    operating_status_cta { false }
    email_updates_button { false }
    find_facilities_cta { false }
    limit_subpage_inheritance { false }
  end
end
```

I think the most notable of the schema is in the "context" value. I didn't want too much in the way of facility/VAMC specific fields in the db (we ended up with a few booleans but they are optional) to keep Banners generic for other banner types in the future. And for VAMC banners, the path(s) that are used to determine display are housed within these related VAMC entities on the banner node in Drupal, and coming back as a json object in graphql:

```graphql
          "fieldBannerAlertVamcs": [
            {
              "entity": {
                "title": "Operating status | VA Puget Sound health care",
                "entityUrl": {
                  "path": "/puget-sound-health-care/operating-status"
                },
                "fieldOffice": {
                  "entity": {
                    "fieldVamcEhrSystem": "vista",
                    "title": "VA Puget Sound health care",
                    "entityUrl": {
                      "path": "/puget-sound-health-care"
                    }
                  }
                }
              }
            }
          ],
```
So I created this 'context' field on the Banner ActiveRecord object, which has a storage type of 'jsonb' in the backend, to contain the VAMCs. In future banners, we can store other data as needed there. The API will then have a distinct way of determining if a banner should be displayed per banner type. This maps well to the related content types in Drupal. Hope this makes sense, holler if not.

**Comment by dsasser** [comment]
There are two PRs to track for this issue:

1. [VACMS-19450: Creates Banner Module department-of-veterans-affairs/vets-api#19056](https://github.com/department-of-veterans-affairs/vets-api/pull/19056)
2. [VACMS-19450: Banner model migration department-of-veterans-affairs/vets-api#19069](https://github.com/department-of-veterans-affairs/vets-api/pull/19069)

PR 1 adds the new schema to the postgres database. PR 2 is the remaining portion of the work for this issue.

**Comment by dsasser** [comment]
## Mid-Sprint Update 10-24-24

Changes are in [PR](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19450#issuecomment-2436136974) and have been approved by our team so we are waiting on Platform review at this time.

**Comment by dsasser** [comment]
## End of Sprint Update 10-29-24

Work is still in PR. There have been some minor changes requested by Platform, so we are just getting through those as fast as we can. Currently we are waiting for the (hopefully) final round of review.

**Comment by jilladams** [comment]
This merged and has been deployed according to https://www.va.gov/atlas/apps/vets-api/deploy_status. Not sure what we do to verify or if this can just close?

**Comment by SnowboardTechie** [comment]
@jilladams I reviewed the code for this, it was no functionality but created the models and DB tables I will be utilizing when create the service for #19451. I would be comfortable with this being closed
