### ISSUE TITLE
Update Drupal core to 9.1.x

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1948]
## Acceptance criteria

- [x] PR to update core to Drupal `9.1.x` is created and merged
- [x] Upgrade runbook is created and followed (if necessary)
- [x] there are no regressions in functionality
- [x] no new errors, warnings or notices in logs
- [x] [group testing sessions split into separate issues] 
- [x] SSO is tested.

## Assumptions

- all modules and infrastructure are compatible w/ 9.1.x

**Comment by ndouglas** [comment]
Current commands for updating necessary dependencies and Drupal itself simultaneously:

```
lando composer require \
  drupal/core-recommended:^9.0.0 \
  drupal/core-composer-scaffold:^9.0.0 \
  drupal/core-project-message:^9.0.0 \
  symfony/config:^4.0 \
  symfony/routing:^4.0 \
  --no-update;
 
lando composer require --dev \
  acquia/drupal-spec-tool:^4.0.0 \
  --no-update;  
```

With the work done in #4951 and #4947, this will get past patching core.

**Comment by acrollet** [comment]
Necessary changes for tooltips can be found here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5364#issuecomment-852510087

**Comment by acrollet** [comment]
@ndouglas can you briefly document the work performed during Sprint 35 here in a comment? Then we'll kick it to 36. Thanks!!

**Comment by ndouglas** [comment]
A probably-comprehensive document of work performed during Sprint 35 on this issue:

- A Cypress test was causing failures with Drupal 9.1 because it was looking for "Parent item" when the field is now called "Parent link".  Or vice-versa 🤔  I changed the field label that the test was trying to find.
- Some PHPUnit tests were failing against Drupal 9.1 because PHPUnit itself was not able to execute correctly in all situations.  I updated PHPUnit and its dependencies to compatible versions.
- Some Behat tests were failing because Behat was not able to detect when the simulated user was logged in.  I added a "logged-in" class to the `<body>` element when a user is logged in, after deciding this was less disruptive to UX and more reliable than altering menu text or searching for alternative text.
- Some PHPUnit tests were failing because of slight incompatibilities.  I updated the relevant tests.
- The Entity Meta Display block plugin annotation was using a deprecated property and consequently did not appear.  I updated the annotation to use the modern property.
- A deprecated function was in use in a test.  I replaced this with a modern pattern.
- Drupal Console is not yet compatible with Drupal 9 (😩 ) so the queue runner command was failing.  I switched the queue runner command to use Drush instead.
- I added an AfterStep action in Behat tests to automatically dump HTML and text versions of the page where a test failed to ease debugging.
- A couple more Cypress tests were failing because of the Parent Item/Parent Link thing.  I fixed that too.
- I removed an obsolete (though harmless) line that specified which autoloader to use.
- I made some changes to the tooltip code to more closely match style under Tippy 6 to Tippy 5 (as in D8), and fixed some issues with the attachment code that were 1) preventing the tooltips from showing up, and 2) making several of them show up.

**Comment by acrollet** [comment]
Blocked on #5753  (We need to ensure SSO works with D9 before launching)
