### ISSUE TITLE
Ngrok - VA CSOC Security Alert

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19595]
## User Story or Problem Statement
As a member of VA CSOC, I need to understand how CMS is using ngrok and how it plans to remove it from usage. 

## Description or Additional Context 
CMS help desk received a security alert from the VA CSOC team about usage of ngrok in training-qtpbfivdfzrlrlyiqwmanznaobpek1ca.demo.cms.va.gov. Ngrok is not approved for use within the VA, so the CMS team needs to collaborate with the Sitewide team to understand how and where Ngrok is being used, remediate the situation, and use the CSOC runbook to communicate with the security officer. 

## Relevant Links
- Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-8139
- VA CSOC CIR Security Alert Runbook: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3124854936/VA+CSOC+CIR+Secret+Scan+Security+Alert+Runbook

## Steps for Implementation
- Collaborate with the Sitewide team to understand how and where Ngrok was used.
- Collaborate with the Sitewide team to understand how to approach removing Ngrok usage within CMS. 
- Use the [CSOC CIR Security Alert Runbook](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3124854936/VA+CSOC+CIR+Secret+Scan+Security+Alert+Runbook) to communicate and document next steps with the Security Officer. 

## Acceptance Criteria
- [x] The scope of ngrok usage within CMS is understood and the appropriate team (either CMS or sitewide) is communicating with VA CSOC about the remediation plan.

**Comment by 7hunderbird** [comment]
The three TL;DR to know

1. We are now using Datadog on the training site's EC2 host to watch for any ngrok traffic
2. The CMS application (which runs the training site) has no runtime dependencies that use ngrok
3. Because any developer can install and run `ngrok` we need to communicate that it's not a tool to use

### Infrastructure

- The report came in that the https://training.cms.va.gov website (aka https://training-qtpbfivdfzrlrlyiqwmanznaobpek1ca.demo.cms.va.gov/) was linked to an `ngrok` instance
- Reviewed what was being [recored to datadog](https://vagov.ddog-gov.com/dash/host/8970072?fromUser=false&refresh_mode=sliding&from_ts=1729696287088&to_ts=1729699887088&live=true)
  - No network information was being recorded
  - To turn on network information, process monitoring also needed to be turned on
- With network monitoring enabled, a [Datadog DNS query](https://vagov.ddog-gov.com/network/dns?saved-view-id=2391) is added
  ```
  (network.dns_query:*.ngrok-free.app OR network.dns_query:*.ngrok-free.dev OR network.dns_query:*.ngrok.io OR network.dns_query:*.ngrok.com)
  ```
- Then ran a call and caught my request from Tugboat EC2 instance out to `api.ngrok.com`
  ```
  curl https://api.ngrok.com -H "authorization: Bearer {MY_API_TOKEN}" -H "ngrok-version: 2"
  ```
- We are now recording any DNS lookups of `ngrok` related domains

### Application

- the cms app [2 years ago](https://github.com/search?q=VACMS-8588&type=pullrequests) used lando for a local development environment
  - lando used ngrok
  - but we've not used lando and have transitioned to ddev 2 years ago
- the cms app uses the content-build and vets-website repos
- both content-build and vets-website use cypress
- cypress uses blob-util
  - blob-util has a _development_ dependency for ngrok
  - blob-util doesn't use ngrok when compiled

### Ngrok CLI Usage

- Any developer can install a binary CLI on their local laptop
  - This has been used as a work around when Tugboat is not working
    - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17306
- Anyone can start a tunnel with a command like
  ```
  ngrok http -–domain=panda-new-kit.ngrok-free.app 80
  ```
- the `*.ngrok-free.app` domain is for free-tier users
  - https://ngrok.com/blog-post/new-ngrok-domains
  - https://www.infoq.com/news/2023/08/ngrok-free-static-domain/

**Comment by gracekretschmer-metrostar** [comment]
Security incident ticket here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2070
