### ISSUE TITLE
Past recurring event is showing for "All upcoming"

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19669]
## Description
There is an event ("Veteran Walk-in Flu Clinics") that happened on 9/24/24 that is showing at the top of "All upcoming". This event is not showing on prod in this position.
- Next Outreach and Events listing that shows this event at the top: https://dev.va.gov/outreach-and-events/events/
- Prod Outreach and Events listing that does not have this event: https://www.va.gov/outreach-and-events/events/

This is showing the first instance of this recurring event rather than the next upcoming instance

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Please include a set of steps that allows an independent tester to see the problem.
2. Write them so that after the defect is fixed, the steps will result in the expected result.
3. It is helpful to write the steps methodically so they can be the foundation of an automated test.

**Expected result:** What should be the outcome?<br />
**Actual result:** What currently happens?

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by oddballpete** [comment]
IIR is including this ticket in our upcoming planning; will ensure property placement / parity with out board

**Comment by jilladams** [comment]
@oddballpete @AdamKing0126 Can this item be closed out in the AP board? The linked IIR ticket, https://github.com/department-of-veterans-affairs/va-iir/issues/1213, was closed as a dupe but not sure where the correct tracking ticket is.

**Comment by AdamKing0126** [comment]
Hey @jilladams I am not sure of the proper way to track these tickets, I was under the impression that we were leaving them on the next board as the main source of truth

**Comment by AdamKing0126** [comment]
i am having a bit of trouble understanding how to develop in this environment.  Finding it quite difficult to detangle:
- the "events" page is a statically generated page, which creates a json object which is stashed in a javascript variable
- the vets-website application contains the code for rendering the events, and it uses that json object to build them
- instructions on running the applications are not clear to me 
    - must we be running `vets-website` and `next-build` at the same time, locally? 
    - how do we tell `next-build` to retrieve the components from our local `vets-website`? 
    - if we are running both applications, we are running two node servers - which one do we visit, to test?

I have asked a question in https://dsva.slack.com/archives/C01SR56755H/p1733855391865419

**Comment by jilladams** [comment]
(re: where to manage the ticket - great! I'd thought IIR was making tracking tickets for everything, sort of Collab Cycle style, but it seems much easier to just use the existing ticket in your team board, so 1 closure for everything.)

**Comment by AdamKing0126** [comment]
following up:

you have to run `yarn setup` in order to pull assets from `vets-website` into a folder in the `next-build` repo, in order to view them.  Running `yarn setup` on its own will pull assets from dev, which will show the current defect.

What we need to do is to pull local `vets-website` assets.  The README instructs us to `BUILD_TYPE=localhost yarn setup` to pull those assets from [vets-website/build/localhost/generated](https://github.com/department-of-veterans-affairs/next-build/blob/62fa075cf7a8eb10805c1f56860478e65c552677/scripts/yarn/vets-website-assets.js#L27-L30).  

In `vets-website`, both `yarn watch` and `yarn build` drop the assets into that directory, so you *should* be able to run `yarn watch` to get hot reloading going as you develop in `vets-website`, however with each change you'll need to run the `BUILD_TYPE=localhost yarn setup` in `next-build` to pull those changes in.

HOWEVER, I'm not finding any success with this method.  Running this command and then `yarn dev` in `next-build`, I still get a 404 when I visit `/outreach-and-events/events` (does not happen when pulling assets from the `dev` environment by just running `yarn setup`).

I need to recruit some help to finish this, I think.  @john-rodriguez-adhocteam and @nicksayre maybe can help

**Comment by AdamKing0126** [comment]
The [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33610)

**Comment by jilladams** [comment]
Verified in prod: 
https://www.va.gov/outreach-and-events/events/75572/ - an event with a 12/19 recurrence, as well as recurrences from 12/12-12/18. 

The 12/19 recurrence correctly shows in Upcoming today. The older ones don't.

**Comment by jilladams** [comment]
Flag: it looks like this change went farther than intended, and removed all Past events in general from occuring on VA.gov, rather than only filtering past recurrences of an event from the Upcoming list. 

Right now, no past events show on any VAMC: 
https://www.va.gov/minneapolis-health-care/events/?selectedOption=past

Reopening. FYI @AdamKing0126 @mmiddaugh @oddballpete

**Comment by jilladams** [comment]
I am double checking if we need to revert this change before code freeze, or if it's ok that Past events don't appear til after code freeze. Unclear if that matters or not.

**Comment by AdamKing0126** [comment]
@jilladams would you mind revising the acceptance criteria for the completion of this ticket?  I was under the understanding that we wanted to exclude previous events from the event list

**Comment by jilladams** [comment]
Yeah man - I don't see any ACs at all. :/  Apologies for that. Normally our team would refine / update ACs before we picked up a ticket, but these netherworld AP tickets aren't going through any product team with product knowledge to get that in shape before IIR is asked to pick them up. That's something we should make sure to work with y'all on before you get assigned more. I will def add an AC section, once we figure out if this ticket should stay closed actually or what.

**Comment by AdamKing0126** [comment]
Ok cool, keep me posted

**Comment by jilladams** [comment]
Ok - Michelle's call: since Upcoming events are working ok, and since the code change here does fix the issue of past recurrences showing as upcoming, we are gonna let it stand. I'm going to re-close the ticket, and file a new one that Sitewide will own to adjust the behavior for Past events.

**Comment by AdamKing0126** [comment]
Alright, thanks Jill

**Comment by oddballpete** [comment]
Thanks @jilladams let us know if / what action is needed here.
