### ISSUE TITLE
[Events - NB] Add to Calendar link inconsistent in displaying the purple visited link style

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19697]
Noting: we are using web components here so it may be spiky and end up as a DST ticket.
If this passes the points timebox, throw a flag. 

## Description
While QA-ing Next-build events, I noticed that the "Add to calendar" link is not consistent as to when it does and does not get the purple visited link style. This is an existing curiosity on Prod which is why I'm filing it for Sitewide rather then a defect in the next-build board.

### What is happening
I have found multiple events, both VAMC events and National outreach events where the "Add to calendar" link is purple, indicated it has been "visited", and conversely I have also found multiple events where this link remains blue and I can't seem to find a pattern as to what determines this:

- Purple visited link style:
  - https://www.va.gov/outreach-and-events/events/64661/
  - https://www.va.gov/outreach-and-events/events/73833/
  - https://www.va.gov/wichita-health-care/events/74431/
  - https://www.va.gov/northern-indiana-health-care/events/73769/
- Standard blue link style:
  - https://www.va.gov/hampton-health-care/events/70887/
  - https://www.va.gov/outreach-and-events/events/70103/
  - https://www.va.gov/outreach-and-events/events/70102/

### User story

**AS A** Veteran et al
**I WANT** the links in events to consistently display purple or blue, depending on whether I've visited the link
**SO THAT** I have visual guides as to whether or not I've already clicked a link

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] Links should consistently display in the color purple if they have been visited
- [ ] Links should consistently display in the color blue if they have NOT been visited

**Comment by jilladams** [comment]
Noting: we are using web components here so it may be spiky and end up as a DST ticket.

**Comment by chriskim2311** [comment]
@laflannery @FranECross I took a look at this and the Add to Calendar links are using the va-link DST component. They are all blue for me locally and I checked all the links from Laura's findings. And I actually found that I cannot get them to turn purple(visited). 

From my understanding the way a tags get the `a:visted` attribute is based on web history cookies. The way this link is built has the href as the current page it is on and actually does not navigate anywhere and just downloads the calendar file. Also on the DST component page the Add to Calendar link does not change as well.

Share on Facebook va-link works as expected once I click back since it took me to a new URL.
![Image](https://github.com/user-attachments/assets/e979b659-3ce8-41d0-b560-49a91c2990b2)
 
I think given the way this is built currently we wont be able to get it to be purple as its not a functioning link to another page/url. I think this is a no-op but open to thoughts. Thanks!

**Comment by jilladams** [comment]
@laflannery @FranECross thoughts here? 

@chriskim2311 just confiriming: ticket is in "Code review / A11y review" just waiting for feedback on how to repro, right? There's been no PR so far?

**Comment by laflannery** [comment]
I don't have a strong opinion, I was just noting behavior differences I saw but if this isn't supposed to be purple then it's fine? It is interesting that I also am not seeing the visited link color anymore either - worth noting that this is now next and before it was content-build so who knows if that's the difference?

**Comment by jilladams** [comment]
I'm gonna go ahead and close this as a no-op then, since DST doesn't document expectations for a :visited state, and it's not reproing anymore. Thanks, y'all.
