### ISSUE TITLE
Exploring Defining DORA Metrics for CMS

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19900]
## User Story or Problem Statement
As a member of the CMS team, I need to understand what is feasible within the data within CMS infrastructure to meet the DORA metrics. 

## Description or Additional Context 
Feedback from OCTO leadership: the CMS team will need to start tracking DORA metrics (@EWashb will provide PDF that has definition of DORA):
- Deploy Frequency
- Lead Time for Changes
- Change Failure Rate
- Time to Restore Services

DORA metrics are used in OCTO OKRs (see [here](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2936995854/2024+-+OCTO+Objectives+Key+Results):
- Objective: Our platforms are the best way to deliver products at VA
- Key Result: Our platforms hit the “elite” level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service. 

More information about DORA metrics here: 
- https://www.datadoghq.com/knowledge-center/dora-metrics/
- https://dsva.slack.com/archives/CT4GZBM8F/p1732728218729449

Platform has to do this too, so they are a good resource. 

## Steps for Implementation
- Review research done by previous teams around this work (look in slack). 

## Acceptance Criteria
- [ ] A documented understanding (using the Now, Next, Later framework) of what is feasible within CMS data to track the DORA metrics.

**Comment by 7hunderbird** [comment]
@EWashb can you please provide PDF with definition of DORA?

**Comment by EWashb** [comment]
> ~~@EWashb can you please provide PDF with definition of DORA?~~
> 
> I think this was the PDF: https://dsva.slack.com/archives/CT4GZBM8F/p1732728248244479?thread_ts=1732728218.729449&cid=CT4GZBM8F
> 

That's the one @7hunderbird

**Comment by 7hunderbird** [comment]
First draft is started here: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3695542870/DORA+Metrics+DevOps+Roadmapping

**Comment by 7hunderbird** [comment]
This would help me limit the scope so I can complete this work.

@MDomngz @gracekretschmer-metrostar I read into the "Acceptance Criteria" the idea that I would add a roadmap to the end.

>  A documented understanding (using the Now, Next, Later framework) of what is feasible within CMS data to track the DORA metrics.

But I wanted to get a clarification that this would be more about taking the four categories of a DORA summary and apply the "now, next, later" to each of those.

For example rather than creating a generic "roadmap" section at the end, there would be something like this.

## Platform CMS

### Deployment frequency

#### Now
- we deploy this many times a week

#### Next
- we deploy this many times a day

#### Later
- we deploy any time

### Lead time to changes

....


So is that what you were thinking with the "now, next, later" framework?

**Comment by 7hunderbird** [comment]
This is the complete draft that can be shared as done.  This represents a good-faith estimation of where we are now.  It does not contain any future looking information (the next or later ideas of how we continue to develop DORA metrics.

- https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3695542870/DORA+Metrics+for+CMS+2024
