### ISSUE TITLE
Edits to link teaser summary on node 716 on prod are not

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2073]
**Describe the defect**

Edits made to a paragraph entity on prod

**To Reproduce**
1. Go /node/716/edit
2. Find  "List of link teasers" in "Main content" and click "edit" button.
2. Trying to change 
"Apply for Veteran Readiness and Employment (VR&E) services, get support for your Veteran-owned small business, and access other career resources."
 to
 "Apply for vocational rehabilitation services, get support for your Veteran-owned small business, and access other career resources."
3  A new revision is created, but the content change does not show.

We could not reproduce this on staging at 12:21 ET today. 
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
I am redeploying `f2c0cb1da588e199837c72bd8f3944613b899fab` to STAGING now to see if we can reproduce.

**Comment by swirtSJW** [comment]
Might be related to this 
![image](https://user-images.githubusercontent.com/5752113/85054059-77559000-b169-11ea-8997-5a15a7e1ca0d.png)

Seems like it is showing the wrong revision on edit.

**Comment by swirtSJW** [comment]
It is reproduceable on prod and local but not staging .

**Comment by indytechcook** [comment]
We were able to reproduce the issue.  There is a bug with the change check logic in the paragraph module.

Published Revision: A

1. Edit the node.
2. Change a field on a paragraph on the edit form
3. Save the new draft creating **revision B**.
4. See the Latest version updated value.
5. Edit the same node.
6. Change the same paragraph field back to the exact original value from **revision A.**
7. Save the Node to create **revision C.**
8. See the Paragraph field have the save value from **revision A**

A possible workaround includes workaround is to add a space, save the node, publish the node then credit the node and remove the space.

I'm creating a follow up issue to address the root cause.

**Comment by indytechcook** [comment]
Drupal.org issue created: https://www.drupal.org/project/paragraphs/issues/3153277
