### ISSUE TITLE
Paragraph entities sometimes do not save revision changes

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2091]
This is a follow-up fo https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2073

## How to reproduce

Start with a Published Revision: A

1. Edit the node.
2. Change a field on a paragraph on the edit form
3. Save the new draft creating revision B.
4. See the Latest version updated value.
5. Edit the same node.
6. Change the same paragraph field back to the exact original value from revision A.
7. Save the Node to create revision C.

Published Revision: A

**Expected Result**
Revision C contains the text entered on the edit form.

**Actual Result:**
Revision C has the save value from revision A

Drupal.org issue: https://www.drupal.org/project/paragraphs/issues/3153277

**Comment by swirtSJW** [comment]
1. Go to /node/716/edit
2. Expand Scroll down to the "Main content" field and edit  the "list of link teasers"
![image.png](https://images.zenhubusercontent.com/5dcda45425f6cc0001763cb5/fce4f479-1838-4509-bb87-a08140b23dc9)
Change the /disabilty link text from `Disability` to `Disability BOO`
3. Set the workflow to `Draft` and  click the "Save" button.
4. Scroll down and validate that the unpublished revision now has `Disability BOO` 5. Edit the latest revision and scroll down to The link teaser and change `Disability BOO` back to `Disability` and save the revision as either published or draft (makes no difference) 
5.  Scroll down the page and see that the page still contains `Disability BOO`

**Comment by beeyayjay** [comment]
The patch from https://www.drupal.org/project/drupal/issues/2859042#comment-12711915 works. 

One odd side effect, the intermediate revision (B) gets the same value as rev A and rev C. Steps to reproduce:

1. On patched site, go to Go to /node/716/edit
2. Change the /disabilty link text from `Disability` to `Disability BOO`
3. Save as draft
4. Go to Revisions tab and compare latest revision with published revision. See that `BOO` was added after `Disability`.
5. Edit and and change `Disability BOO` back to `Disability` and save.
6. See that Latest Version tab now shows `Disability`.
4. Go to Revisions tab and compare previous revision with published revision. See that they are now identical.

**Comment by indytechcook** [comment]
This is an interesting side effect.  Reading through the D.O issue, it looks like https://www.drupal.org/project/drupal/issues/3152820#comment-13705883 is another possible solution.  It would be great to test both and report back to D.O.

**Comment by beeyayjay** [comment]
Investigation didn't suggest an obvious fix. It appears that the second edit (the one that changes the field back to the original value) doesn't create a new field revision, but edits the existing one.

After initial edit (change `Disability` to `Disability bar`):
![Screen Shot 2020-07-14 at 3.03.12 PM.png](https://images.zenhubusercontent.com/5d7908d1fb288f0001ceb853/dd732348-94cb-4561-af2e-58cdf20859f6)

After second edit (change `Disability bar` back to `Disability`):
![Screen Shot 2020-07-14 at 3.10.16 PM.png](https://images.zenhubusercontent.com/5d7908d1fb288f0001ceb853/b61a0c57-e055-436f-8512-cc7dc586d864)

I'm going to push the patch as is, since an incorrect history is preferable to an uneditable field.

**Comment by beeyayjay** [comment]
btw, I tried the second patch. It didn't fix the original issue for me (still couldn't revert the field value).
