### ISSUE TITLE
Support VAMC upgrade team with creation of VISN 19 devshop environments

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2255]
## User Story or Problem Statement

As a member of VAMC upgrade team, i need devshop environments on which i can publish nodes for each VAMC, for stakeholder review. 

## Acceptance Criteria
* Each VAMC system in VISN 19 has its own devshop environment, just like VISN 4

- [ ] VA Cheyenne health care
- [ ] VA Eastern Colorado health care
- [ ] VA Eastern Oklahoma health care
- [ ] VA Montana health care
- [ ] VA Oklahoma health care
- [ ] VA Salt Lake City health care
- [ ] VA Sheridan health care
- [ ] VA Western Colorado health care

## Implementation

- [ ] Train VAMC upgrade team (eg, share the video)

**Comment by kevwalsh** [comment]
@SgardnerPMP 

We documented [devshop for product teams](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/demo-environments.md) and developed a training around it, but i realize now there's one user story missing, which is the one you need! 

I've just added "[User story 1b](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/demo-environments.md#user-story-1b-not-covered-in-slidedeck-or-video)" to the documentation, which is probably all you need to get going on this. If you're missing any context or the framework, i encourage you to read the PDF slidedeck or watch the video listed at the top of the page. 

Please let us know via #cms-support if you need any additional help with this. 

/cc @davidconlon

**Comment by SgardnerPMP** [comment]
Kevin and team,   Quick customer perspective and review of guidelines for empowering product team members to complete these actions (instead of CMS).  1) Video is not available.  Receive error "This recording does not exist. (3,301).  2) Instructions in User story 1b and context in user story is very uninformative, suggest you either just remove it as it is of no help and miss leading, or at least provide a step by step that is more accurate.  3)  PDF does NOT show product members HOW to build a new Demo environment.  In all instances it stated (Will cover that later).  Yet it is never covered in the PDF slide.  Only suggestion provided is to request an environment in CMS support.   Please advise.  If you want to just walk me through this process in a quick session, I can record it for training.  Thank you.

**Comment by SgardnerPMP** [comment]
Kevin, I've begun to create the VISN-19 pages.  I will rebuild one this next sprint.  If you wish to close this issue, please feel free as I have saved the User story 1b for reference. Thank you.
