### ISSUE TITLE
Create a design doc for how to handle broken link incidents 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2417]
## Problem statement

1. The CMS can continue to try to improve UX around links, but we simply can’t guarantee no broken links will be created by editors
2. Broken link reports from Jenkins (which depend on a vets-website build, usually from a PR) get reported to CMS team, not to the editors who need it. They sometimes have false positives due to weird race conditions.
3. We work quickly with Public Websites to help them fix broken links, which isn’t too hard on Slack
4. All of the above won’t scale outside the confines of DEPO/Slack

## solution ideas

Generate json output of broken links, that drupal can parse, and decide who to notify. 

Then it's ok to have some broken links because it won't last long.

**Comment by cmaeng** [comment]
Our team's understanding that the link checker was only looking at Drupal pages was incorrect. Based on [this thread](https://dsva.slack.com/archives/C52CL1PKQ/p1600696850047600), it's checking every page on the website (Drupal/vagov-content/React apps) which amplifies this issue because our team then becomes default triage to identify the source of the broken link (inside or outside of Drupal) and who to contact to resolve.

**Comment by swirtSJW** [comment]
I just submitted this Design doc for review.  https://github.com/department-of-veterans-affairs/va.gov-team/pull/14092
