### ISSUE TITLE
Create "cms" application user on servers

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2526]
## Background
Currently to run commands on server we have to run them as a non-login shell `apache` user and this is a PITA. 

e.g. `sudo -u apache bash -c "source /etc/sysconfig/httpd; PATH=$PATH:/usr/local/bin scripts/sync-db.sh 2>&1`

We should make a `cms` user that we login, that has a login shell so we can just run commands. 

## Acceptance Criteria
- [x] When logging in, the user is cd'd to the web root
- [x] User can `sudo su - cms` and become the cms user
- [x] Environment variables are loaded
- [x] `webroot/bin` has been added to `$PATH`
- [x] user is added to appropriate web user in `/etc/group` (e.g. `www`)
- [x] `drush` is in the user's default path, is executable and functions correctly, and is owned by the web user (`httpd`(?))
- [x] File permissions are set correctly with a `drush cache:rebuild` and any other file modifying commands

## Implementation

There may be an available ansible role to do at least some of this.

**Comment by ElijahLynn** [comment]
We are setting this up correctly on the new K8s containers, probably should refine this more.

**Comment by mchelen-gov** [comment]
how is it being set up in K8S, does this need further refinement?

**Comment by ElijahLynn** [comment]
@ndouglas did some good work here https://github.com/department-of-veterans-affairs/devops/pull/9746 towards this. One last thing I can think of is making sure a `drush cache:rebuild` doesn't mess with permissions on the files.

**Comment by ElijahLynn** [comment]
> @ndouglas did some good work here [department-of-veterans-affairs/devops#9746](https://github.com/department-of-veterans-affairs/devops/pull/9746) towards this. One last thing I can think of is making sure a `drush cache:rebuild` as the new `cms` user doesn't mess with permissions on the files.

Doh, Nate already addressed this in the PR notes and we still have to tackle that bit. I'll add that as an AC for this story.

**Comment by olivereri** [comment]
Regarding the file permissions. I looked at Nate's notes and recommendations did some reading and tested it out on CMS-Test staging. I like the permission changes and default new file permission for users.

chmod g+ws makes sure users in the group `apache` (i.e. `apache`, `cms`) can write to folders in /var/www/cms. Previously, it was only read and execute. Execute has changed with the `s` option to ensure new files and folders created below /var/www/cms all inherit the parent's group, not the default group of the user creating them. CMS user won't make files where the group is set as CMS instead it will default to apache.

chmod g+w makes sure users in the group `apache` (i.e. `apache`, `cms`) can write to files in /var/www/cms. Previously, it was only read and execute.

umask 002 is only being defined in /etc/sysconfig/httpd since the cms user already sources this in `.bash_profile`. With this mask default directory permissions are 775 and default file permissions are 664.

Folders created by apache or cms will automatically assign read,write,execute for Owner and group, then read,execute for all.
Files created by apache or cms will automatically assign read,write for Owner and group, then read for all.

This looks like all the things we want to share files in a group and prevent group ownership from changing that could cause errors in the httpd service. Also, default file and folder permissions on creation is a little bit more permissive to help group file sharing.
