### ISSUE TITLE
Images derived from cropped image styles do not respect the crop. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2743]
**Describe the defect**
Some cropped images do not respect the user-specified crops 

**To Reproduce**

I'm not able to reproduce this when uploading new images at /media/add/image, but i am able to find issues where existing images that are derivative of crops do not respect the crops. 

Try reproducing by uploading new photos, eg at /media/add/image. Crop at 2x1, and change the default crop. Derivative images of that crop (eg image styles `2_1_large` and `2_1_medium_thumbnail`) should be based on the crop you made. 

On staging and on local, this was true. However, on prod there are definitely examples of images where the derivatives do nto match the crop, see screenshots below:

Possible causes i can think of: 

* this is prod specific
* browser or operating system
* this occurs when adding images from /node/add/news_story (did not test), but not when adding at /media/add/image (did test)
* happens to older images (whether seconds old, or possibly much older)

![IMG_20200504_194411627_jpg__480×240__and_Edit_Image_IMG_20200504_194411627_jpg___VA_gov_CMS](https://user-images.githubusercontent.com/643678/90931573-e69a6b00-e3ca-11ea-88d3-c3a3c41055b7.jpg)
![Item-0_and_Item-0_and_Item-0_and_Item-0_and_com_bjango_istatmenus_combined_and_Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/643678/90931597-f4e88700-e3ca-11ea-9cda-e3b2d19d715f.jpg)

**Comment by VanessaLuxen** [comment]
This issue has resurfaced with Ryan Stubblebine reaching out via email. I hopped on a zoom call for him to show me exactly what he is continuing to see with cropping images. This is not stopping his work but is an ongoing frustration. He is also reporting that the image quality seems to be reduced in prod. 
![Image Editing 1](https://user-images.githubusercontent.com/73555217/104741477-43e6de00-5717-11eb-8ffc-7c2f2b2c5544.jpg)
![Image Editing 2](https://user-images.githubusercontent.com/73555217/104741483-46493800-5717-11eb-8007-d1ec70341a37.jpg)

**Comment by ndouglas** [comment]
Unless I'm missing something, I _am_ able to reproduce this locally:

Image (reuploaded) with a very specific crop:

<img width="866" alt="Screen Shot 2021-01-19 at 8 54 34 AM" src="https://user-images.githubusercontent.com/1318579/105043948-25912300-5a34-11eb-9959-aa4c8867a097.png">

`2_1_medium_thumbnail` derivative does not respect the crop:

<img width="1130" alt="Screen Shot 2021-01-19 at 8 56 43 AM" src="https://user-images.githubusercontent.com/1318579/105044129-5cffcf80-5a34-11eb-853a-38ab4c4abb4e.png">

Being able to reproduce this locally should make this a lot easier to find the issue.

**Comment by ndouglas** [comment]
The issue seems to be an interaction of the `image_widget_crop` module with the `image_style_warmer` module.

The `image_style_warmer` module generates an image derivative.  However, I think at that point the image style is not fully incorporating the changes that are introduced by by the `image_widget_crop` module.  As a result, the image derivative is not correct.

If you delete the derivative and then request it via HTTP or by resaving the media, it will be generated correctly.

The following lines from the DB log indicate the order in which these functions are called (in reverse order chronologically):

<img width="746" alt="Screen Shot 2021-01-19 at 1 09 53 PM" src="https://user-images.githubusercontent.com/1318579/105075359-aca3c280-5a57-11eb-9fb0-4b12e35f50d4.png">

Unfortunately, the simple solution of simply altering the module weights won't work here because different hooks are used by the two modules and they act at different levels of the data (`image_style_warmer` kicks in as soon as a File is saved, whereas `image_widget_crop` acts on the File fields of an updated/saved entity), so this is not a simple fix.
