### ISSUE TITLE
Deploys failing due to performanceLoginTest failures (too long)

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2788]
We are currently seeing a lot of intermittent failures (flickers) on our performanceLoginTest on our upper level environments which do not have a local MySQL (e.g. RDS), which is currently set to pass if under 3 seconds (previously 2 seconds, see #1657). I agreed on scrum this morning to bump up to 4 seconds if we prioritize a story for next sprint to do some performance profiling here. This story needs to be prioritized for Sprint 14 and we need to get this back down under 3 seconds.

I am making a PR for this issue to increase the time from 3-4 seconds, as a temporary adjustment so we can still deploy in the short term. 

AC:
- [ ]  Regression is identified
  - [x] Post profiling results if you do any (e.g. Blackfire, Xhprof)
  - [ ] Post summary of what the regression was
  - [x] Open any follow up stories as needed

Follow-up story Goal: Get 10 login tests in a row to pass with a threshold of 3 seconds on RDS environments 
`source /etc/sysconfig/httpd; PATH=$PATH:/usr/local/bin composer yaml-tests phpunit --dry-run 2>&1` (there is a better way to run just the login test but that is a good start).

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1657#issuecomment-631755887 for previous identical issue.

**Comment by ElijahLynn** [comment]
This was auto-closed, re-opened.

**Comment by oksana-c** [comment]
@ElijahLynn , please include profiling and any expected outcomes as an AC of this story. Thanks.

**Comment by ElijahLynn** [comment]
Done :heavy_check_mark:. 

The main outcome I care about is "Get 10 login tests in a row to pass with a threshold of 3 seconds on RDS environments", which I think would involve profiling but doesn't necessarily need to which is why I left it out.

**Comment by ndouglas** [comment]
Working on this, but have a couple Blackfire profiles I wanna post before I lose them:

- [HEAD: ~10s](https://blackfire.io/profiles/ec8b8fc0-02a2-4973-8bc4-84297b5c97ab/graph)
- [s/setMaxDepth(4)/setMaxDepth(1)/: ~3s](https://blackfire.io/profiles/74df9d00-08b3-49a0-aa34-a8779d6d108c/graph)

**Comment by ElijahLynn** [comment]
Per meeting just now. Nathan and Neil think we may need the dynamic_page_cache enabled for this. The issue is suspected to be the menu link rendering, particularly the sections menu.

**Comment by indytechcook** [comment]
Follow up ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3246

**Comment by ndouglas** [comment]
To summarize our findings:

Profiling with Blackfire led immediately to the `admin_toolbar_prerender_toolbar_administration_tray` function in the `admin_toolbar` module.

Changing the max-depth of the menu rendering had a dramatic effect on execution time, which strengthened our suspicion that this process was involved in some way.

Blackfire profiling dramatically distorted execution time; short-circuiting various sections of code that had wildly disproportionate shares of execution time (for instance, access checking) seemed to indicate that they did not actually cause the issue.  Rather, it seemed to be mostly just Blackfire overhead on function calls (of which there were many tens of thousands for access checking), etc.

However, truncating the data structure of the menu prior to exiting the `admin_toolbar_prerender_toolbar_administration_tray` function had a dramatic effect on execution time when not profiling with Blackfire.  To me, this seems to indicate, as Elijah mentioned above, that the actual rendering process seems to be implicated.  This was supported by some limited further caveman-debugging elsewhere in the system.

Part of the issue -- or maybe the entire issue -- with the test is that the user logging in and out does not seem to have the desired effect of warming the cache, at least as far as the section menu is concerned.  Poking around, it seemed like that section menu was just not getting cached appropriately.  

This might be due to the absence of `dynamic_page_cache`, or it might be due to some of the ease-of-development settings in non-prod environments.  

I enabled and configured `dynamic_page_cache` and didn't see a dramatic improvement, but I didn't audit other performance settings that might've been tweaked to eliminate cache-clearing toil, etc.

@indytechcook might have further thoughts or corrections for what I've said here.
