### ISSUE TITLE
[devops] Disable backup and periodic jobs during PROD deploys so that we don't get failed jobs to track down

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2890]
The backup and periodic jobs currently run every 15 minutes, including during PROD deploys. They should not do this as they fail sometimes and we have to hunt down Slack alerts. 

- [ ] Abort or block backup and periodic jobs if a PROD deploy is in progress.
- [ ] The backup jobs must run when the PROD deploy itself triggers it

**Comment by ElijahLynn** [comment]
Possible risk: Having to add a new Plugin to Jenkins.

**Comment by olivereri** [comment]
Using "Lockable Resources" Plugin, not at the step or stage level, but at the job level. Effective job blocking solution.
https://stackoverflow.com/questions/17651210/locking-multiple-external-resources-in-jenkins

Build-Blocker does not support Pipeline jobs.
https://issues.jenkins-ci.org/browse/JENKINS-51607?focusedCommentId=391558&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-391558

**Comment by olivereri** [comment]
I've fully implemented the job blocking system for CMS-TEST so that

1. Periodic Tasks
2. DB Backup
3. Post Deploy Tests

Block Deployments from occurring and forces them to wait for the locks to be freed. This works the other way around too. Since Deployment jobs don't wait for the next stage to finish, calling the Post-deploy-test stage doesn't result in a deadlock.
I've implemented 10 new jobs that allow for job blocking across each environment
CMS/CMS-Test:

1. cms dev Post-Deploy Tests
2. cms staging Post-Deploy Tests
3. CMS periodic tasks run on dev
4. CMS periodic tasks run on staging
5. CMS periodic tasks run on prod

So far it looks like it's working as intended. Still testing out job combinations.

**Comment by olivereri** [comment]
If I set the pipeline job options to use the lock plugin it'll lock on the entire job. The resource name can be anything we want, so long as the connected jobs also use that lock name. I've started with the pattern:
`path/to/job1-name Block path/to/job2-name`
This way you can take the path, partial URL, and plug it in after jenkins.vfs.va.gov/job/ and see the jobs.
