### ISSUE TITLE
Create semantic keyed values for facility health service select lists and migrate existing data

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3009]
Facility health services have fields with key values 0 and 1 and 2 that would be better addressed with more semantic values for front end and api users. 

See [slack thread ](https://dsva.slack.com/archives/CT4GZBM8F/p1601291612096200) for additional context

e.g. https://prod.cms.va.gov/node/4931/edit
![Screenshot 2023-05-24 at 12 55 02 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/5615714f-fb99-49df-914a-843f992cb568)

AC
- [ ] Validate that there are still facility health services with these values. 
- [ ] Migrate any, if necessary.

**Comment by JQuaggles** [comment]
@davidmpickett Can we chat later tomorrow about what this is (I cant see the slack thread)?

**Comment by davidmpickett** [comment]
@JQuaggles I don't have any context and this is definitely not a priority. I removed the needs refining label because it was in the refined pipeline and I was doing quick housekeeping to make the pipelines and labels match. Perhaps should instead add the label back and move to the unrefined pipeline.

**Comment by davidmpickett** [comment]
FYI 
![Screen Shot 2023-05-24 at 3 03 35 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a4430a31-3876-4b87-946f-2e06235bbdcf)
