### ISSUE TITLE
Optimize Composer Install

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3011]
- [ ] Composer install should run with the following arguments when building for production:

`composer install --prefer-dist --no-dev --optimize-autoloader --classmap-authoritative --apcu-autoloader`

**Comment by ndouglas** [comment]
@indytechcook advised me to look into adding this to the `config` key in `composer.json`, as this seemed to be the cleanest way to make changes throughout Composer with less risk of encountering issues with Jeff Geerling's ansible stuff, etc.  The drawback of this is that some options, namely `classmap-authoritative`, might be unsuitable for non-BRD environments.

Per [this](https://getcomposer.org/doc/articles/autoloader-optimization.md), though, it seems that `classmap-authoritative` and `apcu-autoloader` should not be used together.  Since `apcu-autoloader` seems to be a good choice and I think APCu is available in all of our environments, I'm just going to add that and forget anyone ever mentioned `classmap-authoritative`.

**Comment by indytechcook** [comment]
The php ini change has been made on devshop

`apc.enable_cli = 1` on /etc/php-7.1.d/50-apc.ini
