### ISSUE TITLE
Allow Feature Flag requests while in deploy mode (currently 503)

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3184]
See (internal) https://dsva.slack.com/archives/C01512KN35G/p1602790797407100 for original report from @mpelzsherman. 

> I’m getting an error when running yarn build:content --use-cms-export:
> Querying for non-node content
> Error: HTTP error: 503: Service Unavailable
>     at Object.query (/Users/michaelpelz-sherman/source/vets-website/src/site/stages/build/drupal/api.js:114:13)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> Failed to pipe Drupal content into Metalsmith!
> /Users/michaelpelz-sherman/source/vets-website/src/site/stages/build/index.js:272
>     if (err) throw err;
>              ^

This is because we recently launched a new deploy mode that bypasses Drupal's bootstrapping system and return a 503 during the deploy with a maintenance message to users. We forgot to put the CMS Export endpoint on the Allowlist to allow requests for this to continue as usual, with a 200.

**Comment by indytechcook** [comment]
The path `/cms-export/content` is already setup to redirect to the tar file if it exists during the deploy.  The process coeds work correctly locally.

It's possible the tar file wasn't created successfully which would use this error to occur.  I'll test again during today's deploy to see what's going on.

**Comment by indytechcook** [comment]
I tested in during the deploy today and it the tar was successfully served.

**Comment by indytechcook** [comment]
This issue is actually with pulling the drupal feature flags and not the export itself.

**Comment by ElijahLynn** [comment]
As discussed on a call right now. Currently the main graphql request is 503 too, and is unavailable during a deploy, which it should be.

**Comment by indytechcook** [comment]
Some initial thoughts here.  

Since we need access to this configuration without connecting to the database, we need to find a way to save the feature flag config to a file.

The menu callback for feature flags is at `Drupal\va_gov_flags\Controller\VaGovFlagsController::renderApi`.  This endpoint integrates with the `feature_toggle` module.  This module saves it'ss config in `feature_toggle.features`.  The `features_togle` module fires and a few events after updating the flags as seen at `Drupal\feature_toggle\Event\FeatureUpdateEvents` and `Drupal\feature_toggle\dispatch`.  

When the event is fired a json file can be created.  This file can then be used to serve the API.
