### ISSUE TITLE
R&S content breadcrumbs are returned as expected in GraphQL and content export

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3256]
## Acceptance Criteria

- [ ] ~we've confirmed that R&S content breadcrumbs returned by GraphQL and content export match patterns outlined below and made adjustments if the output consumed by FE templates doesn't match the required breadcrumbs structure~
- [x] breadcrumbs FE component is updated to cover requested breadcrumb patterns outlined below

**Page**  | **URL** | **Breadcrumb** | **Notes**
--- | --- | --- | ---
Landing page   | www.va.gov/resources/   |  Home  > Resources and support   |  |
LC Category term   | www.va.gov/resources/[category-name]/  |  Home  > Resources and support > [h1] |
Checklist, Step-by-step, Media list - Images, Media list - Videos, Q&A,  FAQ - multiple Q&A, Learning Center Details page   | www.va.gov/resources/[article-title]/  |  Home  > Resources and support > [Article title] |
Topics, Audience - beneficiaries, Audience - non-beneficiaries Terms  | www.va.gov/resources/tag/[tag-name]/   |  Home  > Resources and support > [h1]   |

**Comment by ethanteague** [comment]
The logic in https://github.com/department-of-veterans-affairs/vets-website/pull/14687 will cover all of the patterns defined by this task.

Here's how it works: In template for content type or term, add breadcrumb include like this:
`{% include "src/site/includes/breadcrumbs.drupal.liquid" with constructLcBreadcrumbs = true titleInclude = true %}`
To construct an Lc crumb trail, add `constructLcBreadcrumbs = true` and to add the page title (e.g., for a content type page as opposed to a term landing page) set titleInclude to true: `titleInclude = true`

cc: @oksana-c @kelsonic @ncksllvn

**Comment by kelsonic** [comment]
Adding ourselves for visibility, not sure if there's any FE change we need to make to support this new behavior, thanks for taking care of this @ethanteague! 🙂

**Comment by jenniferlee-dsva** [comment]
One type of page not listed ^ is the search results page. Is that because the breadcumb for search results will not be generated by the CMS? @ethanteague @oksana-c   (I know search results pages are dynamic FE and not build in the CMS, but wasn't sure about  breadcrumbs.)

Mikki's IA doc includes: 


Search results | www.va.gov/resources/search/[query-parms] | Home  > Resources and support > [h1]
-- | -- | --

**Comment by ncksllvn** [comment]
The search results page has its own separate breadcrumbs. That's usually just the pattern for React apps because it's easier to have it standalone instead of wired to Drupal. But we could set it up so that the page is a Drupal node and the search results themselves are a widget, like we did Find Forms.

**Comment by jenniferlee-dsva** [comment]
That's ok @ncksllvn - I think we're okay with the whole search results being a react page.

**Comment by jenniferlee-dsva** [comment]
Thx for explaining.

**Comment by jenniferlee-dsva** [comment]
@oksana-c @ethanteague - The breadcrumb on articles are appearing with a double RS link, like this: 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/8e268711-8b0a-419c-b130-272ae6d02464)


^ node: http://preview-prod.vfs.va.gov/preview?nodeId=8684

**Comment by ethanteague** [comment]
Pr to fix this, @jenniferlee-dsva https://github.com/department-of-veterans-affairs/vets-website/pull/14750
