### ISSUE TITLE
JIRA Service Desk - Slack integration

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3331]
We have support requests coming in via Slack and need to facilitate flow of these requests to JIRA Service Desk (JSD).

## Acceptance criteria

- [x] A6 Slack VFS-CMS Helpdesk channel for internal communication exists
- [x] Slack channels for helpdesk bots (DSVA)
- [x] Slack integration in `#cms-support` channel w/ JSD or manual process to transition support requests from Slack to JSD exists

**Comment by indytechcook** [comment]
Slack/Jira plugin: https://confluence.atlassian.com/slack/using-jira-applications-with-slack-966662163.html

**Comment by MaggieBrazeau** [comment]
@oksana-c  Who on the A6 team would we need to get with to get the JIRA/Slack integration underway?

**Comment by oksana-c** [comment]
scheduled a call on Nov 17 to discuss this issue in depth

**Comment by erogray** [comment]
Discussed today — Oksana has created a bots channel for Jira statuses, and submitted a request to DSVA slack admins to approve Jira integration

**Comment by oksana-c** [comment]
#cms-helpdesk-bot channel is created to intake all JSD tickets and updates. Screenshot w/ current config below
<img width="973" alt="Screen Shot 2020-11-18 at 2 14 55 PM" src="https://user-images.githubusercontent.com/16477724/99589284-ffee8b80-29a8-11eb-9ea3-1a53a306d9b2.png">

@MaggieBrazeau tested by creating a new request + making an update to the ticket and the team verified the integration is working.

**Comment by erogray** [comment]
@oksana-c since we have two-way working Slack integration I'd advocate for moving the parts about moving existing slack users to their own ticket, since that seems like a whole different can of worms:

- change management process to transition existing #cms-support user base to a new workflow: announcement to various groups
 - the CMS team understands new helpdesk workflow
- Workflow for managing requests originated in Slack exists

**Comment by erogray** [comment]
We've tested notifications _from_ Jira to Slack, and also using `/jira create` to create tickets from Slack to Jira. The latter can be customized so that it's user-friendly and may even replace the existing Slack workflow.  But it'll need some tinkering, and seems much less time-sensitive since we aren't planning to move Slack users over to Jira right away.

**Comment by daddison48** [comment]
moved transition items to https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3537
