### ISSUE TITLE
Spike: help text patterns

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3333]
## Problem statement

Inability to assign a custom position and/or format to help text per field is becoming an impediment to improving UX throughout CMS forms.

"Learn more" pattern was reviewed as a POC https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1777 and consensus is that we should make it available to our Content Strategists.

## Acceptance Criteria

- [ ] review Rachel's [Help text mural](https://app.mural.co/t/vagov6717/m/vagov6717/1586882180337/415aa0adba23f935239d291d83fda234b16f1957) for "Learn more" and other patterns
- [ ] discuss technical implementation options
   * which help text patterns should be prioritized. So far we've focused on Learn more pattern, but there are other low hanging fruits, e.g. help text position
   * should "Learn more" pattern be implemented on the field storage level OR form widget display level
      * what options can be offered for this pattern: Rich text, images, etc
   * should we build a contrib module to support Learn more and potentially other patterns
   * should this contrib also include other help text options, eg. help text positioning within the field/widget
   * what should be our MVP for learn more pattern implementation. e.g. Rich text only and no image attachment options; limited field types / widgets that this pattern can be applied to

## Participants

@rachel-kauff @acrollet @ndouglas @oksana-c @jordanamello

**Comment by kevwalsh** [comment]
@oksana-c This issue was bumped in the context of CLP editorial experience (implementing Rachel's designs), and @kaise-lafrai expressed interest in evaluating approaches to putting help text between the label and field... and we have some bandwidth next sprint for this problem space.  

If learn more module is going to be delayed further, seems like it would be worth evaluating [the existing widgets](https://docs.google.com/spreadsheets/d/18Nd89JY7Qpf8gHZJndA0BdJr0vYjBcDwzXQjpsEUxDk/edit#gid=600020787) to determine what might be candidates for a short-to-medium term solution for moving the help text... probably various text field widgets, and some of the most commonly used widgets.

![Quantitative_Audit__Form_widgets___Entity_types_-_Google_Sheets.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/393e2353-ea3d-4837-833d-a46d2ebd2a8a)

Perhaps Kaise could take this past the technical spike into a POC in Sprint 25

**Comment by oksana-c** [comment]
@kevwalsh that's great! If Kaise can research options for relocating help text and implement some - that would leave the "learn more" pattern as a standalone implementation. It's better handled that way anyway. Thanks for raising this.

**Comment by msbtterswrth** [comment]
@kevwalsh should we close this in favor of the design system work taking place? we did end up moving help text for all fields under the label, so this in at least some part was completed.
