### ISSUE TITLE
Improve Alert block management, governance, UX

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3380]
### User Story or Problem Statement

The reusable alert library was built to provide a single source of truth for certain reusable alerts in the Benefits Hub pages. 

For example, the mental health alert, which has content that has been extensively tested with veterans, is used on a half dozen benefits detail pages. That content is also leveraged by other products, such as some VAMC pages. 

The banner block type was also expanded in March 2019 to allow it to add site-wide banners, both dismissible and dismissible. It has not been used much, if at all. Subsequent to that, a VAMC banner alert system was built to target VAMC system pages. and homepage banner has been managed via github in vets-website. The full-width banner alert should probably either be removed altogether, moved to another content type, or significantly iterated on.

 

### Affected users and stakeholders

* All editors who can create or edit alert blocks

### Some questions that need answering, in a spike

Should content moderation be removed from blocks? 

Should we abandon blocks and moved to nodes, for consistency? This may be desired if we retain content moderation, so that we can avoid applying EWA to blocks. 

Should site-wide banners be decoupled in the content model from content blocks? 

Do banner alerts need to be expanded in their possible scope, to hit non-drupal pages (currently they are limited to pages known to drupal). 

What kind of dashboard is needed? 

How might reusable blocks be surfaced on various dashboards, such as VAMC, if at all?  

### Hypotheses

TBD based on spike.

**Comment by rachel-kauff** [comment]
**7-19-2021 Notes from meeting w/ Randi about alerts usability**

Context from Randi:

1. In-age alerts

When editing an in-page alert in context within a page, it defaults to published instead of draft
Confusing doing the editing in the page bc saving two different things - the alert and the page.
2. Create an alert

Scope field - help text is misleading bc you can leave the field blank and it won't appear on every page.
Context from Kev

Alert block content type is trying to do two different things - in page AND banner alerts. The scope field guidance only applies to banner alerts (not in-page alerts)

Banner alerts should never have been lumped in with in page alerts

Would be great if we could improve the entire banner alert experience, but keeps getting deprioritized

Recommended next steps

Alerts content type: if in-page alert, hide irrelevant fields such as scope
In-page alerts block: default to saving as draft
Could use the pattern we use in the Vet Centers form for locations to surface the editorial workflow status
Could use form validation to warn users trying to publish a page with a draft alert in it
How will users know they need to save the page in addition to saving the alert block in order for changes to manifest?
Don't use editorial workflow for non-reusable blocks
Form validation at the alert level so editors get expectations set before they do the big save
OR don't allow reusable alerts to be edited in context, only allow them to be edited in their own screen, like resources and support (but make sure there's a link for easy access)

**Comment by rachel-kauff** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5901

**Comment by FranECross** [comment]
Old ticket; closing.
