### ISSUE TITLE
Spike: Research / Help desk integration

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3652]
## Background

We're getting ready to build a more comprehensive research/design infrastructure for 2021 and believe that the integration with help desk can be very fruitful!

## Acceptance criteria 

- [x] research / help desk meet and discuss 
   - [x] data points we'd like to collect via help desk processes
   - [x] define where in the helpdesk process (and how) we can include and collect the data points
   - [x] how we can include design in the triage process
- [x] next steps identified and translated into a backlog for Q1 2021

**Comment by jordanamello** [comment]
Summary of the first meeting with @daddison48 @oksana-c @hie1 @cmaeng @VanessaLuxen and Ero:
- The _Journey_ and _Editorial Experience_ items [in this doc](https://docs.google.com/spreadsheets/d/1iBvqWLLLQ3ROlvGE0_T3WdNIx0j14szYYjEswqmmx5U/edit#gid=0) will be integrated to the labeling system. Either a separate category will be created or the items will be added to the existing labels.
- Jordana to schedule a recurring working session with Ero, Vanessa, Hayley and David (optional) to figure out the details of helpdesk + design collaboration - review historic help desk interactions and applying labels, labels glossary, ticket review routine etc.

**Comment by jordanamello** [comment]
@erogray @VanessaLuxen @hie1 @jordanamello defined that for now the best course of action is to have weekly co-working sessions between UX/Helpdesk/Training to:
- Label current and historic tickets together in order to build common understanding.
- Build labels glossary.
- Identify training opportunities.
- Build reports.

Re: _Journey_ and _Editorial Experience_ items integration to help desk system:
- A custom field was created to accomodate _Journeys_ items. The field will be optional in order to accomodate N/A cases.
- _Editorial experience_ items will were integrated as labels. In order to differentiate them, the prefix "ex-" was added to each item, e.g. "ex-publishing".
- Historical issues will also be labeled according to _Journey_ and _Editorial Experience_.
