### ISSUE TITLE
Database dump text encoding issue

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#3664]
**Describe the defect**
The export of production data is incorrectly encoded:

<img width="309" alt="Screen Shot 2020-12-08 at 10 07 23 AM" src="https://user-images.githubusercontent.com/101649/101517461-05068100-393e-11eb-8b77-0b2c857e7372.png">

The ? character should be a "💬" character. It's not currently known whether the error occurs during the DB export or sanitization.

**To Reproduce**
Compare https://prod.cms.va.gov/help/support/release-notes with https://staging.cms.va.gov/help/support/release-notes

**Expected behavior**
All text should be exported in the same encoding as it is stored in the production DB.

**Comment by ndouglas** [comment]
One possible fix for this sort of behavior appears to be a `--default-character-set=utf8mb4` command line parameter that can be passed to `mysqldump`.  I've passed that command locally after modification and can confirm that it fixes at least some instances of this, but because of the size of the dump and its unwieldiness in IDE/text editors and that I need to re-insert the problematic emoji locally, it's a little aggravating to confirm the fix.  I think it also requires some changes on import, too.

**Comment by ElijahLynn** [comment]
This work has been completed by @ndouglas PR in https://github.com/department-of-veterans-affairs/devops/pull/8305 which was just merged. I created a backup and then sanitize job and refreshed an environment in Tugboat and... we have EMOJI 🙋🏼‍♂️🙋🏻‍♀️🙋🏿 downstream!!!

Nice work @ndouglas and @acrollet!

![image](https://user-images.githubusercontent.com/1504756/108144115-d7e0f800-707d-11eb-8756-83fcdb3154e1.png)
