### ISSUE TITLE
JSD form and widget are updated w/ UX and help desk recommendations

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3818]
## Timeline
Needs to be done early sprint 22 (Mon or Tues)
- @ero to give it a first pass
- @rachel-kauff and @VanessaLuxen to review 

## Wireframes
https://balsamiq.cloud/s21kwcm/py46j7t/r3E59

## Acceptance Criteria
- [x] JSD request form and widget settings are updated per recommendations in #3399

**Comment by erogray** [comment]
I've updated the Jira request type and widget settings to come as close as possible to the Balsamiq recommendations at https://balsamiq.cloud/s21kwcm/py46j7t/r3E59. Some caveats/limitations:

- field helptext does not appear to exist for the widget. That means that the helptext suggestions appear in the Portal now, but not in the widget.
- the thank you confirmation was longer than the allowed number of characters, so I reduced it slightly.

**Comment by erogray** [comment]
Reviewed with @VanessaLuxen — ready for you @rachel-kauff

**Comment by rachel-kauff** [comment]
Thanks @erogray . I'm looking now, will post some comments shortly. Right off the bat though, is is possible to adjust the landing page copy to match what I had in the wires? 
![Screen Shot 2020-12-22 at 12 01 41 PM](https://user-images.githubusercontent.com/41017988/102938598-73c8fb80-4461-11eb-8299-0912080d1c83.png)

**Comment by rachel-kauff** [comment]
Reviewed! Some notes:

- field helptext does not appear to exist for the widget. That means that the helptext suggestions appear in the Portal now, but not in the widget.
   - Too bad about help text on the widget, but I think we can live without it. 
- the thank you confirmation was longer than the allowed number of characters, so I reduced it slightly.
   - Right on!
 - we can't rename the values in the Priority field, so I switched it out for a different field (which I hadn't known existed!) called Urgency. The values for Urgency also slightly mismatch, but are closer to what we're looking for: they're Critical, High, Medium and Low. (We will want to think a little about how to use this; I think re-mapping our reports to use Urgency instead of Priority makes sense, for instance.)
   - Sweet! Glad there's a workaround.

**More notes:**
- After seeing it in the form itself, I had a few edits for my own work to make things a bit shorter (marked with pink arrows in the wireframe). Sorry for the extra fiddly stuff @erogray, but I'd appreciate it if you could tweak it again. 
-

**Comment by rachel-kauff** [comment]
Lastly, I don't think we need `Media library` or `Banners and alerts` in the products menu, because they're cross-product items, and the multiple choices might confuse people .(For example, if I'm having trouble adding a photo in the VAMC product, what do I pick?)  
<img width="655" alt="Screen Shot 2020-12-22 at 2 43 53 PM" src="https://user-images.githubusercontent.com/41017988/102940111-6bbe8b00-4464-11eb-9eca-0841d9f37128.png">

**Comment by erogray** [comment]
Hi @rachel-kauff -- thanks for the keen eye. I made the changes to the widget, and because many of those changes take place at the Request Type level in Jira, I noticed that they also affected the Portal — but didn't cross-check that they also matched how you wanted the portal to look.

I've updated the portal to match Balsamiq as well as I could — including changing the Request Type name to "Contact help desk", which is a little weird but works. I think mostly this is pretty nice, though I'm unable to make the helptext for each field show up above the field instead of below it.

I also like the widget text changes, and have made those also.

For the Banners and Alerts vs. Media Library issue, those are in our Components list; I don't have enough context to know which should be removed, maybe someone with more product experience can recommend?

**Comment by rachel-kauff** [comment]
Nice. Thanks for updating! 

Yeah, I agree that the request type looks weird. I forgot that we couldn't remove that label called "What can we help you with?."

I do think I knew about the position of the help text. Not ideal, but we can live with it.

As for banners and alerts and media library, those are documented as a product in the components list for internal purposes, but for helpdesk purposes, I suspect they will just confuse people, and recommend omitting them from the dropdown menu.
