### ISSUE TITLE
Tier 1 learns about differences between Teamsite vs. Drupal CMS

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#3879]
## Participants
- @VanessaLuxen 
- @rachel-kauff 

## Story
As a new CMS user who is used to Teamsite, I want a cheat sheet that helps me translate between terms I'm used to (such as "Promote") and their approximate equivalent in Drupal (Promote > Publish).

## ACs
- [ ] Identify where cheatsheet belongs in help center IA - Rachel
- [ ] Draft Teamsite vs. Drupal cheat sheet in CMS help center - Vanessa
- [ ] Review with ___ ?
- [ ] Publish - Vanessa
- [ ] Socialize w/ training, cms team - Vanessa
- [ ] Announcement - Rachel

**Comment by rachel-kauff** [comment]
This 2019 research may be a source of info on Teamsite. @kevwalsh may know where to look for more on this. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/VAMC-Pittsburgh-discovery-January2019/20190110_AX_Pittsburgh%20Author%20and%20Stakeholder%20Research%20Summary.pdf

**Comment by erogray** [comment]
@rachel-kauff do you know if we have any of the "cheat sheets" that folks used in the past for Teamsite?

**Comment by erogray** [comment]
What we know now:
Teamsite users have commented that Drupal seems like a straightforward CMS. 
We've also heard that Teamsite users say "promote" but Drupal uses "publish". 
Past user research showed that users wrote HTML separately and then added to Teamsite, rather than building pages within the tool.

**Comment by erogray** [comment]
Let's bump this back a couple sprints since we don't know enough yet to publish a user-visible document. We've started to collect notes internally in  https://docs.google.com/spreadsheets/d/1iBvqWLLLQ3ROlvGE0_T3WdNIx0j14szYYjEswqmmx5U/edit#gid=1572922267

**Comment by erogray** [comment]
@oksana-c I've bumped this to Sprint 25 in hopes that we have more info by then.

**Comment by oksana-c** [comment]
@erogray @VanessaLuxen James Hoehn (VISN19 Web master) could be a good person to talk about differences in terminology Drupal vs Teamsite.

**Comment by erogray** [comment]
Let's schedule a meeting with James Hoehn  (and maybe Jordana) to discuss the user experience and how it differs.

**Comment by kevwalsh** [comment]
Just saw this thread. 

I'm curious what prompted this ticket. Is this more for us, so that we can better understand requests coming in? Or as a documentation and training tool for our users? 

I think there's probably more value (empathizing with where our users are coming from) for the former than the latter.  

There's a school of thought in tech training that mapping new systems to old doesn't have a huge ROI, and can in some cases confuse editors. I'd be curious on @xiongjaneg 's take on this, but there are folks in the Education Services area of CivicActions that have some insight here.

**Comment by xiongjaneg** [comment]
@kevwalsh I defer to UX on this. I do know Dave C. has tended away from crosswalks for VAMC Upgrade because some users aren't familiar with Teamsite or they might bring bad habits from Teamsite. Crosswalks can be helpful for a 1:1 relationship between concepts, but when an environment is based on a completely different frame of reference, there may not be 1:1 comparisons.

**Comment by VanessaLuxen** [comment]
@kevwalsh @xiongjaneg @rachel-kauff @erogray I think the intention of this ticket was for an internal document that would help define terms for incoming issues. There was discussion of perhaps making a public document in the help center but if it would be more confusing than helpful keeping it internal would be good. This may be something that just develops over time as tickets and issues come in.

**Comment by erogray** [comment]
Let's keep it an internal google doc scratchpad. Since we already have it, this ticket seems unnecessary.
Proposal: let's turn this ticket into a meeting with James Hoehn and Vanessa and Ero, since that seems useful still.

**Comment by erogray** [comment]
I've changed the ticket title

**Comment by VanessaLuxen** [comment]
Email received back from James. Will keep a ticket open in Jira as pending and will reach back out to him at the end of February. https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-397

Hi Vanessa – I don’t think I’ve got enough Drupal experience yet until VISN19 goes live to make an accurate comparison with TeamSite. 

I tend to approach things from the editorial end, especially content. I’m a former newspaper web editor (Clickability then web editor-in-chief at a college (WordPress), with a bunch of other CMS and analytics background – as well as a writer, reporter, etc. 

So when I look at Pittsburgh’s new Drupal site, I tend to look at the traffic, what’s dropped off, what’s not being read that used to be popular on TeamSite. 

I’ve been able to maximize TeamSite and greatly improve web traffic in certain areas, so waiting to see if that translates to Drupal. 

I’m finding that many of the issues with VA’s outward facing websites is lack of knowledge of digital media, who looks at what, content generation, and tying the web, social media and posters in the hallway together. Drupal is a huge improvement (and opportunity), but it still boils down to doing the work. 

To me, Drupal is similar to WordPress, but with different terminology. Hopefully, I’ll be much better prepared by the end of February to give a more accurate comparison between Drupal and TeamSite in terms of the VA websites.

**Comment by erogray** [comment]
Moving to icebox since there's no current need for this, or path forward to do anything about it.
