### ISSUE TITLE
Get Jenkins API Token from SSM

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3955]
## Description

Use AWS SSM Parameter Store as the source of Jenkins API tokens. This will allow Jenkins to be deployed and loss of api tokens will be tolerable as we can create a new token and populate the parameter store with the current api token.

This is an issue to track the work here: ~#3410~ #4149 

## Acceptance Criteria
- [ ] The Front end manual release process works.

**Comment by ndouglas** [comment]
Hey @indytechcook did you want me to use the AWS SDK instead of `exec()` to retrieve the token?

**Comment by indytechcook** [comment]
> Hey @indytechcook did you want me to use the AWS SDK instead of exec() to retrieve the token?

That would be nice

**Comment by ndouglas** [comment]
Might be easier to do it as a followup, just because the coordination on this PR as-is is non-trivial.

**Comment by ndouglas** [comment]
Copied from Slack:

>So here is a basic run down:
The instance running drupal needs its IAM Role updated so that it can read the SSM Parameter that stores the Jenkins API key. That is accomplished with this PRS: https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/9
Once that PR is merged and that instance has the correct IAM permissions we will need to take the current token and put in the ssm param store that was created with that PR :point_up: .
After that is done and we confirm that drupal will be able to pull down the parameter we can merge the PR that started this thread https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4149
Once all that is done and working, I think I can stop bugging CMS folks and will be able to do some changes and do Jenkins deployments without disrupting drupals ability to trigger content deploys in Jenkins.
