### ISSUE TITLE
Form validation errors in CLP with closed fieldsets

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4137]
**Describe the defect**
In sprint 25 we fixed this in #4024, but it's come up again with 

**To Reproduce**
1. Go to /node/15068/edit
2. Remove audience field content and keep the Why this matters fieldset closed
3. Click Save

**Expected behavior**
Form validation behavior should work as expected.

**ACs** 

- [x] users get useful form validation feedback, in all cases including when their parent collapsible fieldsets are closed or open
- [x] consider adding an automated test (update estimate if necessary)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/dc5ac546-b455-42a8-ac6d-fd94ad491163)

**Comment by kaise-lafrai** [comment]
@kevwalsh This took a bit longer because I had to refactor the code some more and ran into some odd errors. It is ready for review here: https://pr4157-hyaoho8p1qfmpvov3dznwuj6eyfk4tfm.ci.cms.va.gov

I am still working on the automated test. If this fix is a high priority it can move ahead if it needs to.

**Comment by kaise-lafrai** [comment]
@kevwalsh This ticket is ready for review and now includes a new automated behat test :)
