### ISSUE TITLE
Resolve performance issue with preview on Production

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4151]
## Acceptance criteria

- [ ] ~preview performance on Production is improved - Preview loads under 5 seconds~
- [x] any issues that are not in scope for CMS are coordinated with other teams

## Related Slack thread (internal)

https://dsva.slack.com/archives/CBU0KDSB1/p1611857007368600

## Related JIRA issue

https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-355

**Comment by ElijahLynn** [comment]
Still thinking this _might_ be related to #4178 which we just identified. Will revisit tomorrow after that is resolved.

**Comment by ElijahLynn** [comment]
K, progress, the issue is an eager cache invalidation issue. When loading a preview node, it takes a bit the first time and subsequent loads are fast, within a second or two usually, BUT if I edit ANY CMS node then the graphql cache is invalidated and the next preview request takes a long time again. 

On DEV these are 15 seconds. 

This will be resolved when we move from the GraphQL based build system to the CMS Export JSON build system and THEN move preview to consume that as well. So we might just leave this for now since that move is so close.

**Comment by indytechcook** [comment]
Linking to an issue which will help with performance: https://github.com/department-of-veterans-affairs/vets-website/pull/15974

**Comment by ElijahLynn** [comment]
Triaged to Public Websites team in > https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4251

**Comment by oksana-c** [comment]
Closing as this issues has been triaged / prioritized by a different team.
