### ISSUE TITLE
Research options for automatically opening a JSD issue for Broken Link incidents

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4230]
As a CMS help desk team member, I want the Broken Link incident automatically creting an issue in Jira Service Desk (JSD), so that I don't have to waste time for manually copy/pasting info.

## Acceptance Criteria

- [ ] the help desk team researched methods for automatic creation of JSD issues from Broken Link incidents
   - create JSD issue using JSD API
   - create JSD issue via Slack command
   - create JSD issue by sending an email to `support@va-gov.atlassian.net`
- [ ] the help desk team selected the most feasible method after consulting with engineers
- [ ] backlog for any follow up technical implementation exists

**Comment by ElijahLynn** [comment]
One option that I think we can look into is Halp (by atlassian) as it advertises a 2 way sync from/to Slack and Jira Helpdesk. We can request a 1:1 demo with our team at https://halp.com/demo.

**Comment by erogray** [comment]
*create JSD issue using JSD API* 
This looks like it should be possible via 
https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/?_ga=2.157320761.2089437250.1557061318-247648608.1537283601#servicedeskapi/request-createCustomerRequest
https://community.atlassian.com/t5/Jira-questions/How-to-create-a-ticket-via-service-desk-api/qaq-p/1075512 

*create JSD issue via Slack command*
We can already do this, for any Slack channel that's sync'd to Jira, via `/jira`. However, we probably don't want to sync `#cms-team` to Jira. We could however send broken-link alerts to `#cms-helpdesk-bot` and then make tickets from there pretty easily. Since that channel is also the main way that Vanessa and I know if we have incoming tickets, it could work pretty well.
 
*create JSD issue by sending an email to `support@va-gov.atlassian.net*
This is the easiest -- if sending an email is easy, then this automatically creates a ticket in JSD. The subject line can say anything informative (like "Broken Links Alert on master branch") and we'll then be able to set up Jira automation as needed, and/or filter by it later as needed.

IN Jira:
once we have alerts creating tickets, we'll want to assess:
- Do we want to use automation to send these tickets through a unique workflow?
- Do we want to use automation to auto-label these tickets and/or change their Request Type?
We'll also need to set up:
- SLA time for this ticket type
- Reporting for this ticket type
- For reporting, we may need to explicitly ignore duplicates
- There may be other duplicate-handling needed if we receive many identical warnings.

**Comment by jefflbrauer** [comment]
Decision 2/24 - Option 2 seems to be most feasible solution and @oksana-c will write follow up story:

create JSD issue via Slack command
We can already do this, for any Slack channel that's sync'd to Jira, via /jira. However, we probably don't want to sync #cms-team to Jira. We could however send broken-link alerts to #cms-helpdesk-bot and then make tickets from there pretty easily. Since that channel is also the main way that Vanessa and I know if we have incoming tickets, it could work pretty well.
This seems easy to do: just re-point Jenkins at the other channel. But, it doesn't make tickets automatically, so it's not a complete solution. (But, maybe that's fine?)

**Comment by erogray** [comment]
Created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4485, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4486, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4487, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4488
