### ISSUE TITLE
Participate in Campaign Landing Page beta user onboarding

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4317]
Timeboxing this at 3 story points due to focus on Vet Center in Sprint 26

ACs
- [x] Attend onboarding sessions between CLP product team and stakeholders who will act as beta users
- [x] Note opportunities for end-to-end CMS team service, from onboarding, training, content lifecycle.

**Comment by kevwalsh** [comment]
Rough notes from meeting Feb 13 with @xiongjaneg @nataliedunbarCS 

**What do you we want to learn from user onboarding sessions?**

Natalie: 
- Friction points moving from section to section on the form
- Are editors empowered, and understand why things are the way they are?
- Is this purpose inherent in each part of the CMS while they building the CLP

Jane: 
- What are pain points, what’s working and what’s not working? 
- Because i’m totally new to this, don’t know how this is different from the rest of the editorial experience? How does this fit into that?


Natalie: 
- Visual guides 
- Is this effective? Can it be improved?

Training needs
- How should “the” content strategy be incorporated? Eg why are things are structured the way things are

End-to-end service
- From kickoff to implementation
- What might we want to learn from CLP request form
- What are the CMS team touchpoints at each step?

**Comment by nataliedunbarCS** [comment]
First demo session attended on  2/25.
Second demo session attended on 3/3.
CMS team (@xiongjaneg and @nataliedunbarCS ) will facilitate beta testing session. Schedule TBD.

**Comment by xiongjaneg** [comment]
Notes from session 2 with VEO on March 3:

Participant questions and comments
- Who decides who uses the CLP?
- What’s wrong with using it for a content page?
- How did this get prioritized?
- When and why would we use this?
- PDF is a favorite way to share this information.
- The policy is no PDFs on the website except those mandated by law. Link to an existing PDF on the site.
- Can we link to videos on other platforms than YouTube? How can we embed videos?
- Can we link to an RSS feed (Vantage Point)?
- Does allowing downloadable resources send a conflicting message if we don’t allow PDFs?
- Why are only 10 FAQs allowed? What if this is a dealbreaker for our leaders?
- FAQs are a bad user experience.
- Are sections drag and drop? (John said yes for now, possibly in our backlog.)
- Is there a place for someone to enter their email for subscription?
- Can we add GovDelivery API?
- Can we limit image sizing so they are consistent across the page?
- When uploading a new image, if we crop, is the original image saved or is the cropped image saved in the library?
- What would an ideal URL be?
- Not allowing vanity URLs isn’t realistic.
- We need a link shortener that can be customized.
- Not all outreach will be benefit-adjacent.
- VACO isn’t in VA.gov.
- Other groups (Women Veterans, etc.) will want to use this but can’t because they’re not part of the MVP.
- Contact the Web Governance team.
- This is a lot better than what we have, which is nothing.
- I see this as a landing page.

**Comment by xiongjaneg** [comment]
Notes from VBA demo February 25

VBA attendees: Sandy Tadeo, Adrianne Hooten, Jessica Tangitau

Demo

- CMS form
- Differentiated between View vs Edit vs Preview
- Explained required fields and impact on Save
- Preview on VA.gov

Questions

- Will there be a video guide to this form? Yes along with other resources
- What are the image requirements? Can they be added to the form?
- Is there image cropping in the CMS (would be helpful to have for users with less access to editing tools)? Not currently
- How does the hero banner look on mobile? It isn’t shown on a mobile phone, may show more or less of the image on a tablet. Some of the images may be repositioned depending on the display.
- Why limit the number of audiences? Targeted campaigns should be limited to top audience groups. If the audiences/purposes are too different, they might need different campaigns.
- Is the audience optional? There must be at least one.
- What if I want to link to more than one page? Is the CLP a one-stop shop for the campaign? Does limiting the number of CTA buttons affect the ability to link to other resources? Campaigns should have one primary CTA, can still link in other areas, like Spotlight.
- Can Spotlight be moved higher? No, the order of can’t be changed but you don’t have to use all the sections, only the required ones.
- How can we get leadership buy-in if we think we’re losing some capabilities in this product?
- Can we use videos in other sections? No, only in Video. You could use Spotlight to link to a video.
- What’s the turnaround between requesting a page and publishing it? The process would involve a request from a stakeholder, you would collect information and create it for them, there would be a meeting with DEPO to discuss and review the product, analytics, strategy, IA (URL), 508, then you would publish. The review meeting might take about an hour. It’s more lightweight than the existing QA process.
- VBA does a lot of campaigns, including short weekly or bi-monthly ones where this timeline would be a concern. Is there guidance for which campaigns this should be used for?

Comments:
“The panels are helpful.”

**Comment by xiongjaneg** [comment]
VHA demo postponed. John will notify when rescheduled.
