### ISSUE TITLE
Deploy Status URL on BRD

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4319]
## Description

The Content Release status is not populating on BRD.  The URL in use is `va.gov`.  BRD requires `www.va.gov`

* Technical info: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4210/files#diff-72b3a89fda61565942685a556a1b00e21c9b783146f64e1a244c8fac193417fdR82

## Acceptance Criteria
- [ ] The Deploy status message should display on BRD

**Comment by acrollet** [comment]
@indytechcook @rachel-kauff @jordanamello for the long-term fix for this issue, we have a couple of challenges to address:

Without refactoring the service that gives us the FE URL, each environment will show the last content release _for that environment_. So, when on prod, you would see the last content release to www.va.gov as expected. However, staging would show the last release to staging.va.gov, and so on. Without a fair bit more work, nothing would be shown on tugboat/local environments.

Here are our main choices:

1. disable the tooltip on all environments except BRD, and let each of prod/staging/dev show the last content release _for that environment_. (If this is acceptable, the wording will need to be updated for staging/dev.)
2. keep the behavior as it is now, showing the last production content release time on all environments.

@jordanamello can you let us know which is preferable from the UX perspective? Thanks!

**Comment by rachel-kauff** [comment]
@acrollet cc: @jordanamello I suspect that making this tooltip serve different scenarios/environment could confuse things.

I suspect we should keep it to appear just on prod so that its primary purpose is to answer the question, "when did my content last go live in the world?" (so that might be option 1ish - disable tooltip everywhere except prod)

Without a lot more UI design work to unpack some more of our decoupled concepts, this could get really tricky.

Thoughts?

**Comment by acrollet** [comment]
I created #4437 as a follow-on, closing this issue as the immediate defect has already been resolved.
