### ISSUE TITLE
Review process for handling Broken Link incidents

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4480]
Follow-up to #4273 

## Problem statement

We are handling all broken links via ad-hoc processes. As we approach critical user / content mass, it's time to formalize our approach.

Process outline -> https://docs.google.com/document/d/1s41l8-kQWzfII1QZMprQK5nUe-tArYQLx_2kaDJkjuM/edit# 

## Acceptance Criteria
- [x] process outline is reviewed and accepted by the CMS Core Application Team PO (@mchelen-gov )

**Comment by erogray** [comment]
Current process is described at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/broken-link-process.md

**Comment by jefflbrauer** [comment]
@erogray As part of this ticket, I'd like to also fill out our SLA agreements for broken links in this doc created by Megan on FE Tools:

See page 2
https://docs.google.com/document/d/1uc9s6EbHna_ZQXVMwg7qkNvWzw_sbH5xTvqSnSsaXwU/edit#

**Comment by erogray** [comment]
https://docs.google.com/document/d/1uc9s6EbHna_ZQXVMwg7qkNvWzw_sbH5xTvqSnSsaXwU/edit#heading=h.u66cnuxhe32l is updated

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/broken-link-process.md is also updated

**Comment by erogray** [comment]
Current process is ready for review (in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/broken-link-process.md ) by @mchelen-gov and @davidconlon

**Comment by mchelen-gov** [comment]
this looks good! it's very clear in terms of process and covers the situation very well.
a few questions that may be worth addressing or following up on:
1. slack notification for broken links should only ever be occurring on `master` branch of `vets-website` so I'm not sure why it is saying `null` in some cases?
2. having a fast response time is great! is the 1 hour timeframe manageable in terms of resolution, since we may not have direct control of the problem? i want to make sure we're not putting unreasonable time pressure on cms teams
3. it might be worth linking to service desk & tier 2 hours during which these guidelines apply

**Comment by acrollet** [comment]
@erogray we discussed how to lower the impact on our teams in core scrum and made the following decision:

- we will add an issue to our backlog to update the broken link checker to only fail the build if:
   - there are ANY broken links on the homepage, OR
   - there are more than 15 broken links in total

@mchelen-gov will socialize this change with platform.

We then proposed updating this SLA to keep the one-hour resolution only in the cases where broken links fail the content build, and otherwise changing the SLA to 1 business day. Does that make sense to you?

cc @jefflbrauer @joshworkscivicactions @VanessaLuxen @cmaeng

**Comment by joshworkscivicactions** [comment]
@mchelen-gov Broken Links Procedure update and PR pending Ero's approval which should be committed later this evening.

**Comment by mchelen-gov** [comment]
@joshworkscivicactions Looks good, made 2 updates to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/broken-link-process.md :
- Slack notifications currently only go to #cms-helpdesk-bot (see https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L221 )
- Updated link to Helpdesk SLA https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/service_level_agreement.md#help-desk-service-level-agreement-sla

lmk if any of that looks incorrect
