### ISSUE TITLE
[tugboat] Determine user impact of lost demo environment data

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4560]
AC: 
- [x] Talk with Demo environment users (e.g. Stan and Lisa) and identify what impact it has on them. 
    - How many hours of work lost?
    - How bad would it be for them if we cannot guarantee data retention in the future?
    - How helpful would it be if we could guarantee data retention?

**Comment by oksana-c** [comment]
Talked to Stan and Lisa (VAMC Upgrade) about the impact of the lost data on demo environments. Here's the info they shared:

* The data was lost for the four (4) demo environments that were in active use and the team had to take the time to rebuild and republish each environment.
* An additional VISN (~6 environments) also lost demo data, but the timing for the data loss was tolerable to the team because they planned to rebuild all environments in that specific VISN in the morning anyway.
* The VAMC Upgrade team had commented that this incident couldn't have happened at a better time. The consequences to their workflow were described as minimal.

**Data retention**
* VAMC Upgrade understands that demo environments are transient in their nature and that our environment retention policy is 30 days of inactivity. 
* VAMC Upgrade team stated that coordination of maintenance times that can compromise data is important in their current workflow (VAMC Dual-state launches).
* The CMS Core Application team's process should be as follows - protect the data whenever possible and coordinate maintenance timing with all demo environment stakeholders in the case that the data loss is unavoidable.

cc @ElijahLynn @olivereri @mchelen-gov @indytechcook

**Comment by ElijahLynn** [comment]
> protect the data whenever possible and coordinate maintenance timing with all demo environment stakeholders in the case that the data loss is unavoidable.

Thanks for getting this feedback Oksana! Our deploys will soon be automated and data-loss should not happen on DEMO environments but in the case it does we will follow this guidance in the case it does:

**Comment by mchelen-gov** [comment]
> Talked to Stan and Lisa (VAMC Upgrade) about the impact of the lost data on demo environments. Here's the info they shared:
> 
> * The data was lost for the four (4) demo environments that were in active use and the team had to take the time to rebuild and republish each environment.
> * An additional VISN (~6 environments) also lost demo data, but the timing for the data loss was tolerable to the team because they planned to rebuild all environments in that specific VISN in the morning anyway.
> * The VAMC Upgrade team had commented that this incident couldn't have happened at a better time. The consequences to their workflow were described as minimal.
> 

Good to hear, TY! Can this be added to https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-03-03-tugboat-cms-demo-environment-data-reset.md#impact ?

**Comment by oksana-c** [comment]
added to postmortem doc 👍
