### ISSUE TITLE
Comms about Phase 4 hourly content releases (8am - 8pm ET)

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4632]
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4474 for background.

## Acceptance Criteria
- [ ] Comms strategy about _**hourly**_ content releases reviewed and confirmed w/ @davidconlon @johnhashva
- [ ] Communication about _**hourly**_ content releases is distributed to the CMS user base [Slack / Email] - ETA 3/31
- [ ] Existing documentation updated

**Comment by jefflbrauer** [comment]
I recommend we hold on this because CMS team is now accountable for triage of broken links, and we are not currently contracted to have tier 2 capacity past 5pm Eastern, there is not yet a business case to support content releases past 5pm ET, and the helpdesk team tier 1 is currently unfunded (at risk).

**Comment by mchelen-gov** [comment]
is this OBE?

**Comment by acrollet** [comment]
@mchelen-gov OBE = Overcome By Events? If so, I believe so.

**Comment by acrollet** [comment]
Iceboxing until when/if 5pm-8pm ET content releases happen.
