### ISSUE TITLE
Specify a smaller og:image for all content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4865]
## User Story or Problem Statement

As a Veteran looking at VA.gov content on social media sites, or unfurled via Slack, i want an image that is not too heavy. 

Currently, the original image is loaded (see https://github.com/department-of-veterans-affairs/va.gov-team/issues/20480) 

[See relevant slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1617041237292300)

## Acceptance Criteria
- [ ] GraphQL returns a derivative image for any content type that has a field_media image
- [ ] Image size and aspect ratio TBD (see thread above)

## Implementation steps

Update og image field on `/admin/config/search/metatag/node` to use a derivative (see [this d.o. thread for an example](https://www.drupal.org/project/token/issues/3050528). 

![Edit_default_meta_tags___VA_gov_CMS](https://user-images.githubusercontent.com/643678/112896669-ab70c080-90ac-11eb-9196-fa1184e9f042.png)

**Comment by mpelzsherman** [comment]
> GraphQL returns a derivative image for any content type that has a field_media image

I think we only want this change to affect the `entityMetatags` `og:image` URLs, not every image on the site.

**Comment by mpelzsherman** [comment]
We may want to add og:image:width and og:image:height Open Graph tags as well.

Using these tags will specify the image dimensions to the crawler so that it can render the image immediately without having to asynchronously download and process it.

See [Facebook docs](https://developers.facebook.com/docs/sharing/webmasters/images/) for more info.

**Comment by kevwalsh** [comment]
This was addressed in #6646
