### ISSUE TITLE
Continue to update draft of "Helpdesk manual" in Github

### ISSUE THREAD

**Issue by erogray** [department-of-veterans-affairs/va.gov-cms#4867]
## Description
Continuation of #4691  — continue making https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/overview_wip.md more useful as a help desk manual and central resource.

## Acceptance Criteria
- [ ] Document uses hierarchical headers correctly for outlining and linking convenience
- [ ] Compare what's in GitHub vs. what's in google drive

**Comment by stefaniefgray** [comment]
Do we know if this is going to stay in Github or if it will be transferred to Confluence?

See https://agilesix.slack.com/archives/CD6CPAGCU/p1644354811842639

**Comment by cmaeng** [comment]
if google drive is the source of truth for helpdesk manuals and info then what's in GitHub can be bare bones.

**Comment by stefaniefgray** [comment]
Google Drive is not currently the source of truth, @94Jwatson had to keep 26 different browser tabs open from Google Docs in order to perform Tier 1 helpdesking

New source of truth is Notion, where disorganized/outdated documentation materials have been organized and streamlined for easy reference: https://www.notion.so/invite/dca4f216e0c74fe419bc443f2047dd1bc580725b

Frequently used responses are cross-referenced across multiple pages so that if they are updated in one place, they are updated in others

**Comment by stefaniefgray** [comment]
Created Notion workbook

Can re-open in the future if Help Desk documentation within Github is needed

Closing
