### ISSUE TITLE
Yaml Tasks conflicts with Symfony/Process >= 4.0, preventing D9 upgrade.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4871]
## Description
[Yaml Tasks](https://packagist.org/packages/devshop/yaml-tasks) depends heavily on [Power-Process](https://packagist.org/packages/devshop/power-process), which builds on Symfony Process.  However:

>The Symfony Process component has different typehints in the parameters of several APIs in Symfony 4 than Symfony 3 does. This is due to the fact that Symfony 4 requires PHP 7.1.3 or later, which supports a number of typehints not permitted in earlier PHP versions. This difference is minor for most clients, but presents problems for code that subclasses Process, as it is not possible to be compatible with both the Symofny 3 and the Symfony 4 typehints at the same time.

[`drupal/core`](https://packagist.org/packages/drupal/core) @9.anything requires Symfony Process >= 4.4.

A few possible solutions:

- Submit patches upstream for `devshop/power-process` to be compatible with the Symfony 4 typehints -- seems straightforward
- Replace Yaml Tasks
- Something else that I'm missing.

## Acceptance Criteria
- [ ] Yaml Tasks no longer blocks the Drupal 9 upgrade.

**Comment by acrollet** [comment]
related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4109#issuecomment-788154979

**Comment by ElijahLynn** [comment]
Summary from 16th minute:

* Composer-patch seems more difficult because it is a dependency resolution issue and the patches apply after dependencies have been resolved and installed, so it won't work. 
* ACs for replacing yaml-tasks with Task are:
  * Marks commit statuses as pending
  * Marks corresponding commit status as fail/pass when test suite is finished
* Benefits of moving forward towards Task are:
  * Significantly lower feedback loops for CI tests by parallizing some of the test suites
  * CD to DEV/STAGING can be significantly faster with parallelization
  * Moving to a tool with greater community support
  * Untying toolchain dependencies from application dependencies
* Moving to ReviewDog to get back commit-level test output GitHub comments (we broke this with the yaml-tests > yaml-tasks update and really need to get this back as it lowered the feedback loop (when it worked, which it didn't always for Behat because the output was too long and didn't fit inside the comment length limit, so we have room to improve that use case too). 

Unanimously decided to move forward with a PoC of Task with the intent of adding ReviewDog soon after, so that Drupal 9 can be unblocked.
