### ISSUE TITLE
Extend URL alias limit from 100 to 150 characters 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4882]
## User Story or Problem Statement

[see long slack thread](https://dsva.slack.com/archives/CPQFCQKEH/p1617118153164200)

Both Wm. Jennings Bryan Dorn Department of Veterans Affairs Medical Center and Corporal Michael J. Crescenz Department of Veterans Affairs Medical Center get the “Medical Center” cut off, because they exceed 100 characters. (114 and 108 characters, respectively).  I recommend upping the limit to 150 characters in order to:

1. Allow the official name to be completely included in the URL
2. Allow child FE pages of these facilities, such as a campus map, to use the full URL
3. Allow facility health service URLs (CMS-only), like  to fit, such as Spinal cord injury and disorders - `Corporal Michael J. Crescenz Department of Veterans Affairs Medical Center`, which currently gets aliased to a pretty meaningless `philadelphia-health-care/locations/corporal-michael-j-crescenz-department-of-veterans-affairs-17`  (where 17 means its the 18th alias to share this pattern!) 

## Acceptance Criteria
- [ ] Aliases can be created up to 150 characters long

## Implementation steps
- [ ] update pathauto settings

**Comment by swirtSJW** [comment]
Since we are removing the pattern check on all nodes upon publish, the change being proposed would not impact any currently published nodes.   This would only impact
1. taxonomy terms (sections and services) but I think those would not really be impacted
2. Pages that have not been been published.
3. would need to test bulk operations of publishing the affected pages like philadelphia-health-care/locations/corporal-michael-j-crescenz-department-of-veterans-affairs-17   I am not sure if it will use the pattern or not.
