### ISSUE TITLE
Implement monitoring for Elasticache production instances

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4928]
## Acceptance Criteria
- Grafana monitoring is present for:
  - [x] network I/O
  - [x] CPU utilization
  - [x] hit rate
  - [x] evictions
  - [x] swapUsage 
  - [x] currConnections
 - [ ] Grafana dashboard is added to documentation

**Comment by olivereri** [comment]
| What to Monitor | AWS Metric for Memcached | Description
| ----------- | ----------- | ----------- |
| memory utilization      | UnusedMemory       | The amount of memory not used by data. |
| network I/O   | BytesReadIntoMemcached,BytesWrittenOutFromMemcached        | |
| disk I/O (IOPS)  | ? There is no disk ?        | |
| CPU utilization   | CPUUtilization        | |
| cache size   | BytesUsedForCacheItems        | |
| hit rate   | CasHits / CasMisses       | The number of Cas requests the cache has received where the requested key was found and the Cas value matched divided by the number of Cas requests the cache has received where the key requested was not found.  |

**Comment by ElijahLynn** [comment]
@mchelen We are removing "disk I/O" as an AC because it is not applicable as it is an in memory cache. Sizing stays same.

**Comment by olivereri** [comment]
We should consider following AWS's recommendation for monitoring Elasticache Metrics. We have CPU Utilization on the list already.
https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/CacheMetrics.WhichShouldIMonitor.html

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/7f21da7b-a673-434b-bfc3-35055b99cbc1)

**Comment by olivereri** [comment]
I'm starting to think that memory utilization may not be an effective metric to track, since there doesn't appear to be a way to easily get and use the total memory for any given node on these AWS managed devices.  Evictions seems to be a better alternative. Evictions are unexpired items in the cache that are removed to make room for new items. Depending on the value of the threshold it can indicate that we are running out of capacity.

The FreeableMemory metric, described as `The amount of free memory available on the host. This is derived from the RAM, buffers, and cache that the OS reports as freeable.` may help somewhat satisfy the memory utilization AC. As that number trends to zero we know we are running out of capacity but won't give us a clean utilization %.

Additionally, tracking the SwapUsage metric will uncover memory capacity issues as Memcache will write to this swap space that's on disk when it runs out. While these don't look like traditional memory utilization metrics that we are accustomed to for EC2 they should work well to highlight cache capacity issues.

I think these two metrics are more appropriate to keep an eye on the health of the cache rather than how we've described the AC.

**Comment by olivereri** [comment]
Thinking more about the current ACs don't seem appropriate because they are telling me what I should be monitoring. Instead it I think it should be asking me to discover/research what is appropriate to monitor to track the health of the cache and implement it.

**Comment by olivereri** [comment]
Hitrate can be more easily computed:
`
 	This is a calculated metric: get_hits / cmd_get. It indicates how efficient your Memcached server is.
`

https://blog.serverdensity.com/monitor-memcached/

**Comment by mchelen-gov** [comment]
reminder to add dashboard link to docs

**Comment by olivereri** [comment]
The dashboard link to add to documentation:
Must be on Socks Proxy.
http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&refresh=5s
Memcache specific panels at the bottom of the page.

**Comment by mchelen-gov** [comment]
i added an AC about docs, sorry i didn't notice that earlier during grooming
