### ISSUE TITLE
Send RDS logs to Datadog

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5029]
The following logs need to be sent to Datadog from RDS:

![image](https://user-images.githubusercontent.com/121603/107531609-05640800-6b8b-11eb-9e1b-ccbd2a247d0c.png)

## Acceptance Criteria

- [ ] Confirm that logs are visible in Datadog

**Comment by acrollet** [comment]
This is a tracking issue for an Ops team task.

**Comment by ndouglas** [comment]
I don't think we have a pressing need for this at present, because:

1) content-build has been stable, performance-wise, for quite some time now

2) slow queries are very rarely the answer to the question, and when they are, we can just look at the logs within RDS/Cloudwatch.

3) Datadog costs money. A lot of money.
