### ISSUE TITLE
Discover modifications to preview server required for single-page builds

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5044]
## Description

In order to determine if the existing preview server code can be used to build individual site sections, we need to discover which modifications are necessary to get output matching the full content build.

## Tasks
- Evaluate differences between current full content build process and preview server. (code, infrastructure/monitoring, output)

## Acceptance Criteria

- [x] Identify & document significant differences between preview server and full content build code
- [x] Identify & document significant differences between preview server and full content build HTML output

**Comment by ncksllvn** [comment]
## Summary
The Preview Server is used by editors to see their changes on the website as a standalone page with any unpublished revisions. 

For instance, if you visit `http://prod.cms.va.gov/health-care/` in the CMS, click `Preview`, you will be navigated to  `http://preview-prod.vfs.va.gov/preview?nodeId=67`. This is the same as `www.va.gov/health-care/`, plus any unpublished revisions.

The Preview Server does this by operating essentially as a floating Metalsmith build - it is a Node.js server that fetches pages from the CMS using GraphQL via the `nodeId` query parameter then passes it through its own Metalsmith pipeline (separate from the Content Build but shares most code with it), then finally returns the resultant HTML page to the editor's browser. Basically, it can render a page on-the-fly instead of doing a full Content Build via Jenkins.

The Preview Server then is an opportunity to actually _publish_ a page as well. For instance, instead of returning an HTML page to the user's browser, the Preview Server could possibly upload the HTML page to S3, along with any required files. 

### Pros
- Relatively low unknowns
- Simple architecture
- Bypasses the overhead of a Jenkins job - No Docker container setup, Git checkout, GitHub releases, various other small updates.
- Potentially, presents an opportunity to architect the the Preview Server as a CRUD server that manipulates the HTML "cache" in S3 on behalf of the CMS. Like our own "Gatsby Cloud".

### Cons
- Does not simplify the Content Build
- The Preview Server still uses a monolithic GraphQL query that is slow and sometimes times out. We need to fix this - it needs to be refactored and optimized the same way as the Content Build's GraphQL queries so that it is also lightning fast. __This is very doable but I would need 1-2 days of solid focus time.__
- We _might_ need to consider ways to centralize certain menu configs into `.json` files if we are worried about inconsistencies if a section menu is edited then a single page in that section it published - it would get the updated menu before the rest of the section.

### Unknowns
- Will the Preview Server be _allowed_ to upload to S3? As in, we will need the AWS credentials available in its environment.

**Comment by acrollet** [comment]
@ncksllvn thanks for the awesome summary! Noting that @indytechcook and I discussed that a first-pass MVP could work around the static asset issue by avoiding page updates when attached static assets have been modified in any way. He'll be looking into how to detect this in #5037.

**Comment by indytechcook** [comment]
This is a great summary of our discussion.

> Will the Preview Server be allowed to upload to S3? As in, we will need the AWS credentials available in its environment.

We won't need the actual credentials anywhere, AWS does role base security where the EC2 or Lamda will use the role assigned to it to access s3.

A risk is the current state of the preview server requires a decent amount of devops work to get it production-ready.  We had discussed moving this to lamda so it would scale horizontally really easily.

**Comment by ncksllvn** [comment]
Cross-linking to Public Websites ticket on speeding up the Preview Server -> https://github.com/department-of-veterans-affairs/va.gov-team/issues/19787

**Comment by ncksllvn** [comment]
This will also be important too. Currently the Preview Server doesn't support sidebars for the VAMC pages. This issue is to fix that, https://github.com/department-of-veterans-affairs/va.gov-team/issues/21133.

**Comment by ncksllvn** [comment]
Oh geez, and then there is this ancient issue about parity between the preview server and the Content Build, https://github.com/department-of-veterans-affairs/va.gov-team/issues/951.

**Comment by indytechcook** [comment]
Do you think it would be easier to update the full build to run in a node server (lambda) rather then updating the preview to work like the full build?

**Comment by ncksllvn** [comment]
Good idea - Potentially but I haven't thought through that fully and haven't worke with Lambdas

**Comment by ncksllvn** [comment]
For archival purposes, I moved this into a Markdown document at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/proof-of-concepts-summaries/SinglePageBuildsUsingPreviewServer.md

**Comment by jefflbrauer** [comment]
Per @mchelen-gov Let's cross link this ticket to the POC tickets. 

link to the POC Matrix is here: https://docs.google.com/spreadsheets/d/1qrXyjnED4aaJuQ0AgqHHFK2RMjjqeAP1GL1hw5lo0tU/edit#gid=0
