### ISSUE TITLE
Write announcements about new "Section settings" fieldgroup and user guide

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5251]
See #5250, PR environment: https://pr5285-r4jbzvazezkcgutivtgga5l3wjjgi2ek.ci.cms.va.gov/

ACs
- [x] Announcement drafted (see #5088)
- [x] Create a draft change to https://prod.cms.va.gov/help/cms-basics/roles-and-permissions
- [x] Sent to our users when #5250 goes out. 

## Checklist
- [ ] Add this issue as a dependency to the work that will get released
- [ ] Draft announcement content
  -  If you're new to writing announcements, [review this guide](https://airtable.com/tblulo3XrMLuh4N0l/viwSVSkpseM78xmgw?blocks=hide)
  - Use the template to draft the announcement content in the [AT annoucement log](https://airtable.com/tblulo3XrMLuh4N0l/viwSVSkpseM78xmgw?blocks=hide).
- [ ]  Get review: post the drafted release note in #cms-team. Tag the product manager and teammate who worked on it. Work out any clarifications/edits in the thread, and then get 👍🏻 from PM.
- [ ] Publish: Once you get the ping that the dev has merged the changes, publish immediately after the deploy (~3:30/4:00 ET)
  - [ ] Post in #cms-support (can schedule this in advance using the workflow builder)
  - [ ] Post in [CMS Annoucements](https://prod.cms.va.gov/help/support/release-notes)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by rachel-kauff** [comment]
Migrating the announcement draft over from #5088

@ here **🔍 Section = where you can find and edit content**

Recently we made a few small changes so that the CMS uses the term "Sections" in a way that's consistent and clear. You may or may not notice them, but here's a reminder of what you need to know about this important CMS concept:

All CMS content is belongs to one or more Sections
Each CMS editor is assigned to a section based on what kind of content they work on.
When creating a brand new piece of content, you may need to select which section it belongs to if you work on more than one section.
You can see what Section a piece of content belongs to when searching for content.
That's all for now. Still seeking some serious Sections schooling? Let us know in the 🧵.”

**Comment by rachel-kauff** [comment]
@kevwalsh Announcement drafted, help guide updated. This is ready to go out whenever #5250 is ready.

**Comment by rachel-kauff** [comment]
Publishing the content once the work ready is now in the runbook for #2427, which means the last AC is accounted for, even though we didn't publish it this sprint.

**Comment by rachel-kauff** [comment]
Ready to publish this announcement on Monday.
