### ISSUE TITLE
D9 testing session - Core Team

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5378]
## Description

Drupal 9 upgrade is scheduled for ~Jun 8.

Two two-hour sessions

1. ~10 days before go-live (May 31-Jun 1) - Mural board: https://app.mural.co/t/vagov6717/m/vagov6717/1621271183953/68dc32b7a17bc395139389638fda28903ab82e9d?sender=ubaf99e382a028c7225790206
2. The day before go-live (~Jun 7)

All hands on deck to manually test.

## Acceptance Criteria
- [ ] Fragile / high risk user stories have been collaboratively identified and manually tested
- [ ] User stories custom code has been manually tested

**Comment by acrollet** [comment]
(Estimate was duplicated from #4945)

**Comment by ndouglas** [comment]
[Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1625081947838/12019914294ed01a3fdf89fde728c751f9e74c93)

## Session Report

The following team members were present: @ElijahLynn @ndouglas @indytechcook @kevwalsh @ethanteague 

The general approach was similar to the [first session](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4945).  The focus was on previously-identified critical functionality, including areas that had issues in the first mob-testing session, and some areas that had not been tested in the first session due to issues interfering with the BRD deployment.

Some issues were identified:
- The toolbar tooltip was broken because @ndouglas had not manually patched some JS files.  This was remedied after the session, and @ndouglas looked upon @ethanteague's works and saw that it was Good.  This does need to be re-deployed to BRD and tested there, however (see #5364).
- Certain tooltips submit forms, e.g. node edit forms.  It was hoped that this would be fixed by the above tooltip fixes but it was not, and @ndouglas missed this when testing issues because he misread the issue blockers 😞  @ndouglas is following up on this (see #5366).
- SSO could not be tested, likely due to a certificate issue with non-prod BRD environments.  This is being followed up on by @ElijahLynn.
- Preview links did not work, likely due to environment issues.  @ndouglas is following up on this.
