### ISSUE TITLE
Make static assets publicly available in S3

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5480]
## Background

In order to make content publicly available without a deployment process, static assets must also be made publicly available at or before the time content referencing them is published.

## Acceptance Criteria

- [ ] Static assets are directly published to S3 (or another publicly available content store) in a new location by Drupal
- [ ] Direct publishing of static assets does not cause unwanted changes to existing, published content

## Current Situation

The `content-build` build process retrieves static assets from Drupal and publishes them to S3 in one of the build steps. This step takes approximately ~1.5 minutes during the production content build. There are also content build steps that rewrite static asset paths.

Retrieving assets, varying from 50-90s in these samples:
https://github.com/department-of-veterans-affairs/content-build/runs/5118079201?check_suite_focus=true#step:12:17265
https://github.com/department-of-veterans-affairs/content-build/runs/5130372480?check_suite_focus=true#step:12:17306
https://github.com/department-of-veterans-affairs/content-build/runs/5126183253?check_suite_focus=true#step:12:17273

These assets are also pulled as part of the content build in general, which hampers local development. We will pull some examples, but anecdotally, it adds over an hour to content build and makes FE developers hesitant to interact with the CMS.

### User Story or Problem Statement

As a consumer of the Drupal content API, I would like to be able to retrieve static asset paths, so that I may provide access to these assets to Veterans and the public.

As a VFS engineer, I wish to have access to static assets (published and unpublished) on a public endpoint, in order to be able to quickly build the site in a local development environment.

### Affected users and stakeholders

- VFS engineers working on VA.gov templates
- Content API consumers (FE tools)
- CMS engineers

## Hypothesis

We believe that directly publishing static assets to S3 will provide the following benefits:

- Allow providing a public content API
- Improve the local development experience by eliminating the need to cache static assets from behind the SOCKS proxy (We'll know this is true if local development build time is decreased)
- Increased reliability (No worries about TIC blocking requests for assets)
- Increased security (No need to directly expose Drupal to the public via HTTP)

Potentially:
- Reduce the execution time for the current build process by removing the static asset downloading and publishing step and removing static asset path rewriting steps
- Reduce complexity in the `content-build` codebase

## Runbook

1. Assets are published publicly
1. S3 paths are returned by all Content APIs

**Comment by indytechcook** [comment]
A few notes about some of the goals for static asset publishing

> Improve the local development experience by eliminating the need to cache static assets from behind the SOCKS proxy

* Recently a change was added to content build to skip download assets by adding the `--use-cached-assets` argument`: https://github.com/department-of-veterans-affairs/content-build/pull/295/files
* When `--use-cached-assets` then the assets from Drupal will not be redownloaded if they are already cached. 
* The first download still needs to pull all assets and Drupal data.
* SOCKS is still needed to pull assets initially and on follow-ups.
* Local engineers use the preview server for a large portion of the development, in these scenarios assets are not downloaded as they point to Drupal directly.  The asset requires SOCKS to work correctly.

> Reduce the execution time for the current build process by removing the static asset downloading and publishing step and removing the static asset path re-writing step

* The "Download Drupal" asset step in the content-build currently takes [approx. 12 seconds](http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod/514/consoleFull).  This is not a significant part of the build.
* The primary performance improvements expected in the path renaming.  The Path renaming step changes the path for both image fields and WYSIWYG elements. 

> Reduce the content build complexity

With Drupal sending the absolute path directly to content build, the logic to change paths and move assets around will be moved to Drupal.  While this doesn't remove all of the complexity, it removes multiple moving of assets (Drupal to CI server; CI server to S3).   Moving business logic to Drupa also has the benefit of consolidating logic to make the build process simpler to understand and troubleshoot.

**Comment by indytechcook** [comment]
These are questions @mchelen-gov asked. I'm documented here:  

- Why not use relative paths?
- Trade-offs between the drupal module s3fs and flysystem_s3 and custom.
- does the bucket name / environment variable section refer to drupal env or content build env?
- are s3 file uploads dependent on environment?
- how are file deletions handled?
- how would these asset paths be exposed through JSON:API?
- what would be a recommended approach to handling assets in a dynamic decoupled arch?

> does the bucket name / environment variable section refer to drupal env or content build env?

These are in Drupal.  With the logic of the path to the assets in Drupal, the calls to the API doe not have to make any changes.

> are s3 file uploads dependent on the environment?

Yes.  Dev/Stage/Prod each have their own bucket and tugboat shares a bucket.  More info in this issue: https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5611

> how are file deletions handled

The details on how will be work out in [this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5611) but in Tugboat they will be handled per environment and dev/stage/prod will stay forever. 

> Trade-offs between the drupal module s3fs and flysystem_s3 and custom.

The s3fs module contains a large amount of complex code.  It stores metadata in a table in Drupal as well as in s3.  The metadata needs to stay in sync with s3 which requires more maintenance, more moving parts, and more complexity.

Using the `flysystem_s3` along with some custom code is a simpler solution with much less code.  The `flysystem_s3` module provides a file schema that handles the transport between Drupal and s3, we just trigger it. 

Also due to the files needing to be versioned in an append-only method, custom code is required in order to manage the naming of the files. 

> Why not use relative paths?

* Possible performance issues and TIC droppage.  
* Relative paths could be used with the build, CI and local.  
* The paths still have to be renamed from `sites/default/files` to `img/`or `files/`.  See `convertAssetPath`.
* Assets are still downloaded to CI then to S3.
* Path and build complexity still stays in the build layer.

> how would these asset paths be exposed through JSON:API?
>  what would be a recommended approach to handling assets in a dynamic decoupled arch?

The paths would be a Drupal field.  This field can be queried and added to API responses like any other field. 

The architecture described in the Epic assumes a separate content build.  What to do with assets in architecture with Drupal public will occur at the occur later.
