### ISSUE TITLE
[SPIKE] Direct S3 asset publishing technical planning

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5481]
## Description

In order to create the correct technical implementation plan for direct static asset publishing, the engineers involved should meet, discuss considerations to be resolved, and document next steps.

Some issues that should be discussed:
- how we can be certain that the content build's needs are met
- how we can version assets so that a changed asset is never referenced by a page before that page's content has been published
- whether to use [Flysystem](https://www.drupal.org/project/flysystem_s3), the s3fs module or another approach

## Acceptance Criteria
- [x] 1.5 hour spike is held
- [x] conclusions have been documented on this issue
- [x] follow-on issues have been created for any items requiring further research

**Comment by ElijahLynn** [comment]
We may consider using Flysystem instead of S3FS. https://www.drupal.org/project/flysystem_s3 

And we should keep the scope of this to just a specific folder/path, as EFS is much better for our system assets and image cache/style derivatives than S3FS.

**Comment by acrollet** [comment]
Meeting scheduled 6/10 @1200 EDT

**Comment by acrollet** [comment]
Working doc: https://docs.google.com/document/d/1VutdyyeNFzMBexkHW4QhN6e85SJxPG923v9zILD8rDA/edit

**Comment by indytechcook** [comment]
Conclusions from Discovery:

* A new field will be added to the file entity content type.  The new field will be the name of the key on s3 where the file is stored.  There will be a Drupal setting that has the base path.  The graphql field will prefix the s3 base to the value on request.
* A custom GraphQL field plugin can be used to change the output of the field.  Ideally, a custom field would be added also so GraphQL can target the field directly instead of targeting the name of the field.
* A file will be uploaded to s3 from Drupal on the file entity creation and update.  Careful attention needs to be made to make sure this is the last hook/event which runs to allow for other module's file processing to occur.  All derivatives of files also need to be updated.  
* The name of the files on s3 will contain the revision id.  This will create uniqueness for each version for content and make sure file updates on s3 do not override live files. See `Drupal\graphql_core\Plugin\GraphQL\Fields\Entity\Fields\Image\ImageDerivative::resolveValues` for examples of using image derivatives. 
* The s3 bucket will be separate then the current live content-build bucket.
* The front end templates/build will be updated to use the new field.

**Comment by mchelen-gov** [comment]
Are we able to estimate LoE or performance impact at this point?

**Comment by indytechcook** [comment]
> Are we able to estimate LoE or performance impact at this point?

I've created the stories but they haven't been pointed.  I'd say 2 sprints. One for pushing the files to s3 and one for updating the build.

**Comment by mchelen-gov** [comment]
@indytechcook can you add an issue for arch diagram creation?
