### ISSUE TITLE
Monitoring for teamsite endpoints

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5537]
## Description
 VAMC Facility migration depends on upstream data from Teamsites https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/vamc-facilities.md

## Acceptance Criteria
- [ ] Teamsite endpoints are tested every 15 minutes or less
- [ ] Response times are recorded
- [ ] HTTP response codes are recorded
- [ ] Response times and codes are visible to the CMS team
- [ ] Any scripts used are documented and/or committed to the repo

## Implementation Notes

(Also ok to manually maintain list of endpoints)

* Prometheus exporter script that runs every 15 minutes
  `:devops/ansible/deployment/config/prometheus`
* Get list of endpoints (~120) from Drupal config dynamically, from `master` branch
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
* Maybe use `yq` to get this out after curl
  * `curl ... | sed -n '/  delimiter: "\\\t"/q;p' | yq r - -j | jq '.source.urls[]' -r` to get around improper character in yaml and into a workable format 
* Create new Grafana dashboard (don't use CMS dashboard) and panel(s) 
  Consider re-using http://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1 OR create another one very similar to it
  
![image](https://user-images.githubusercontent.com/1504756/127903026-c09c438d-30cb-40e5-a340-66087de113d7.png)
* Look at the variables in the panel to automatically pull the labels into Grafana for repeating rows
  * https://grafana.com/blog/2020/06/09/learn-grafana-how-to-automatically-repeat-rows-and-panels-in-dynamic-dashboards/

**Comment by ElijahLynn** [comment]
Consider pulling the endpoint list an using `yq` to parse the list from the va.gov-cms repo.

**Comment by olivereri** [comment]
Relevant slack thread about endpoint monitoring. Discussion begins about half-way in:
https://dsva.slack.com/archives/CBU0KDSB1/p1622653890436300

**Comment by ElijahLynn** [comment]
I attempted to add a step to the Multistep test and I was able to retrieve the list of endpoints from https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-cms/master/config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml and regex filter them into a variable but wasn't able to use the correct backreference to only get the capture group AND Datadog doesn't appear to support LIST variables. 

I contacted Datadog support via chat and they are going to get back to me by EOD tomorrow to see if this scenario that I described is supported (basically a loop). So, I don't think it is possible to automate it completely in their UI, which would have been amazing!

So, next I explored using `dog`shell (https://docs.datadoghq.com/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell/) but it doesn't appear to support creating new synthetics. 

Therefore, looks like we have to use the API directly to do this in a repeatable, automated way where we don't have to click a bunch of buttons to create and update the test. There is good docs here https://docs.datadoghq.com/api/latest/synthetics/ with some examples in various languages (curl, go, python, ruby, typescript and java). I think I will try to get it working with curl first though in a bash script (because of cross-os dependency ease).

**Comment by ElijahLynn** [comment]
It looks like we may be able to do this in Terraform, attached is a mapping of the Terraform Cloudposse module and the DD API which looks like it could work. 

@acrollet also let me know about a tool to export them out of the API and into Terraform > https://github.com/amnk/dd2tf/, but they don't support Synthetics right now, it seems (https://github.com/amnk/dd2tf/search?q=synthetic).  

![image](https://user-images.githubusercontent.com/1504756/130275329-b6ce2a7e-a15c-4b10-923a-285e8c792592.png)


https://github.com/cloudposse/terraform-datadog-monitor#input_datadog_synthetics
https://docs.datadoghq.com/api/latest/synthetics/
https://www.datadoghq.com/blog/managing-datadog-with-terraform/

**Comment by ElijahLynn** [comment]
@acrollet and I worked on finishing this out today and we got it working BUT we are now blocked by this error I just received:

```
{"errors": ["properties.config.properties.steps.maxItems:
```

https://docs.datadoghq.com/synthetics/multistep/?tab=requestoptions

> Note: By default, a maximum of 10 steps can be created. Reach out to Datadog support team to increase it.

I opened a support ticket to increase it to at least 108, which is how many locations we have. 

I pushed the work up here https://github.com/department-of-veterans-affairs/va.gov-cms/commit/3292ae6dc72a4cb6525c5172dc732f8762a0bada in https://github.com/department-of-veterans-affairs/va.gov-cms/tree/VACMS-5537-monitoring-teamsite-endpoints.

**Comment by ElijahLynn** [comment]
update: Been chatting with Datadog and we are working through upping the step limit. I have CCd @mchelen, @acrollet, @olivereri, @ndouglas and @indytechcook on the ticket (552160).

**Comment by acrollet** [comment]
Let's give DD 2-3 more days and implement with one test per endpoint if they don't get back to us, discussed during planning 9/13.

**Comment by ElijahLynn** [comment]
K, finally got back on this. Did a bunch of `jq` schooling and am working on putting this all into individual tests now. DD got back to us and said they are considering implementing a higher step limit and we are going to have a call to discuss our use case. Until then the max steps is 50 steps and they would have to enable that, so we are going to do individual tests for now. 

Also, not going to use Terraform for this, because there isn't the ability to dynamically pull our updated list of endpoints from GitHub and parse it, I think at least. So, I'm updating this script to use all sorts of `jq` magic!
