### ISSUE TITLE
Go through recent Dependabot security alerts

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#5548]
### CMS Team
New `high severity` security alerts have come through Dependabot [**here**](https://github.com/department-of-veterans-affairs/va.gov-cms/security/dependabot).

This task is to review them and come up with a plan to address.

## Acceptance Criteria

- [ ] No issues are reported on https://github.com/department-of-veterans-affairs/va.gov-cms/security/dependabot

**Comment by mchelen-gov** [comment]
is the goal of this ticket to resolve all the dependabot alerts?

**Comment by ndouglas** [comment]
My implicit understanding was resolve it if it's trivial, then handle each of the non-trivial issues as appropriate.  `npm audit` and Dependabot don't really do a 1:1 thing (though it's close).  I think there might be a couple issues remaining after my PR is closed because of packages that are deeply embedded in our dependency tree, but given that the repo root `package.json` dependencies are all dev/test dependencies and not user-facing stuff, the cost/benefit ratio for doing any serious work is debatable.  The Drupal theme dependencies are user-facing at least but the PR resolves all of them.

**Comment by ndouglas** [comment]
@mchelen-gov Update -- that PR _did_ close everything with the exception of [this one](https://github.com/department-of-veterans-affairs/va.gov-cms/security/dependabot/composer.lock/phpmailer%2Fphpmailer/open), which is being worked on in #5665 (testing it is a little non-trivial).
