### ISSUE TITLE
Create allowlist for password login

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5567]
## Description

As a Platform crew leader, I want to ensure that only users who cannot log in to the CMS with a PIV card are allowed to use a password to log in, so that off-boarding effort can be reduced and system security enhanced.

## Acceptance Criteria
- [ ] Drupal users may be marked as allowed for password login
- [ ] A list of users with password login access may be viewed under the 'People' administration tab
   - [ ] This list may be exported as a CSV

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5567?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5567?planning-poker) with ZenHub @cweagans

**Comment by td-usds** [comment]
This seems very sketchy to me. Can someone justify to me why we would want to degrade security? Why would users without a (functioning?) PIV be granted access to this thing?
Also, what is this need or desire for reducing the off-boarding effort and how does it tie into this?

From a security perspective, this ticket raises a whole bunch of flags that I cannot take down until Platform Security knows more about this and understand the issue more completely...

**Comment by acrollet** [comment]
I'm no longer on this team, tagging @jkalexander7 🙂

**Comment by ElijahLynn** [comment]
> This seems very sketchy to me. Can someone justify to me why we would want to degrade security? Why would users without a (functioning?) PIV be granted access to this thing? Also, what is this need or desire for reducing the off-boarding effort and how does it tie into this?
> 
> From a security perspective, this ticket raises a whole bunch of flags that I cannot take down until Platform Security knows more about this and understand the issue more completely...

We didn't used to have PIV login in the beginning. And then when we did, we were told that the PIV login service isn't always reliable, so we needed to keep the user/pass login working indefinitely, because we need a way to login for users if PIV doesn't work. And we have had intermittent PIV issues, on both sides, and the user/pass login has been useful during those times. 

We have some developers who need access to PROD who still don't have PIV cards too. 

We also need user/pass login working on all the test environments. 

So I think this issue was created to move users towards PIV and eventually only have user/pass enabled/allowed for engineers.

**Comment by xiongjaneg** [comment]
Helpdesk has one documented case where a VAMC editor asked for u/p login while their PIV was malfunctioning and it would take them about a week to get it up and running. Our VA product owner gave us the go-ahead for this editor to use this option for that limited time.

All editor accounts are created using VA email for the username and they are only instructed to login using the PIV link.  A few platform team members don't yet have PIV and an account is created with their company email in that narrow case so that they can go ahead of their work on the platform.

**Comment by TheBoatyMcBoatFace** [comment]
This was handled by the PIV login flow. Reopen if necessary.
