### ISSUE TITLE
Direct Publish Static Assets to S3 - Architecture Diagram

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#5640]
Conclusions from Discovery:

* A new field will be added to the media entity content type.  The new field will be the name of the key on s3 where the file is stored.  There will be a Drupal setting that has the base path.  The graphql field will prefix the s3 base to the value on request.  The field doesn't have to be a "Dupal Field", it could be a dynamic/metadata based field.
* A custom GraphQL field plugin can be used to change the output of the field.  Ideally, a custom field would be added also so GraphQL can target the field directly instead of targeting the name of the field.
* A file will be uploaded to s3 from Drupal on the file entity creation and update.  Careful attention needs to be made to make sure this is the last hook/event which runs to allow for other module's file processing to occur.  All derivatives of files also need to be updated.  
* The name of the files on s3 will contain the revision id.  This will create uniqueness for each version for content and make sure file updates on s3 do not override live files. See `Drupal\graphql_core\Plugin\GraphQL\Fields\Entity\Fields\Image\ImageDerivative::resolveValues` for examples of using image derivatives. 
* The s3 bucket will be separate then the current live content-build bucket.
* The front end templates/build will be updated to use the new field

Open Items
* Is there a contrib module that gets us close?
* Traditional Drupal field or custom dynamic field?
* Actual Performance hit
* Do we replace the path to the asset in GraphQL or front end build?

AC:
[ ] Architecture diagram for proposed static asset handling solution outlined in #5481 is added to the accelerated publishing small batch publishing folder
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing

[ ] Identify any other relevant CMS documentation affected by this proposed change that will need to be updated.

**Comment by indytechcook** [comment]
@mchelen-gov 

Here is what I put together for discussion:  https://lucid.app/lucidchart/3be57bd4-a5f0-4eb3-9635-e9df69639f60/edit?page=BXNMOmLI-_a2#

**Comment by indytechcook** [comment]
Questions to Answer
* Why not use relative paths?
* Trade-offs between the drupal module s3fs and flysystem_s3 and custom.

**Comment by indytechcook** [comment]
> does the bucket name / environment variable section refer to drupal env or content build env?

These are in Drupal.

> are s3 file uploads dependent on environment?

Yes.  Dev/Stage/Prod each have their own bucket and tugboat shares a bucket.  More info in this issue: https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5611

> how are file deletions handled

The details on how will be work out in [this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5611) but in Tugboat they will be handled per environment and dev/stage/prod will stay forever. 

> Trade-offs between the drupal module s3fs and flysystem_s3 and custom.

The s3fs module contains a large amount of complex code.  It stores metadata in a table in Drupal as well as in s3.  The metadata needs to stay in sync with s3 which requires more maintenance, more moving parts, and more complexity.

Using the `flysystem_s3` along with some custom code is a simpler solution with much less code.  The `flysystem_s3` module provides a file schema that handles the transport between Drupal and s3, we just trigger it. 

Also due to the files needing to be versioned in an append-only method, custom code is required in order to manage the naming of the files.

**Comment by indytechcook** [comment]
The preview server directly links to the asset on Drupal. See  http://preview-prod.vfs.va.gov/preview?nodeId=318 `http://prod.cms.va.gov/sites/default/files/styles/3_2_medium_thumbnail/public/2019-02/HJ-heinz-ambulatory-care3_0.jpg?h=afdcd683`.  This could be used for local
