### ISSUE TITLE
Editorial experience design iteration for Centralized Content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5688]
## Description

See #4028 for background. 

Assumptions 
* User stories and anti-user stories for centralized content are available from #5686, Vet Centers discovery mural, and #4028

## Acceptance Criteria
- [x] We have an understanding of technical constraints of "Centralized Content" (VA.gov CMS specific) and EFF (Drupal contrib). 
- [x] We have design recommendations for an iteration on the centralized content experience, including
  - [x] Design spec for #4016 
  - [ ] Stretch: #4205 
  - [x] Possibly other needs
- [ ] We have a plan for user feedback (not a full research plan)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by rachel-kauff** [comment]
Please use the Figma prototype (not screenshots!) for specifications on spacing, padding, colors, type styles for all of these recommendations. Thank you!

Summary of design recommendations in order of appearance:
1. For all users: Add a h2 to the top for all the `About` information
   - Display content type submission guidelines beneath
![Screen Shot 2021-09-01 at 2 24 33 PM](https://user-images.githubusercontent.com/41017988/131747278-6f737adc-7c1e-4bd4-acba-b07fedb7b9f4.png)

2. For admins: Rename `Title` field to `Node name.` Add help text to prompt use of naming convention.
![Screen Shot 2021-09-01 at 2 26 22 PM](https://user-images.githubusercontent.com/41017988/131747466-332f5ec0-1ae5-4f9c-8f5c-fa6542d64a46.png)

3. For non-admins: Hide the `Node name` field
3. Add multi-value select field for `Product` (we currently have a single select product field for KB)
![Screen Shot 2021-09-01 at 2 31 48 PM](https://user-images.githubusercontent.com/41017988/131748063-82f2d49d-b882-466b-8b16-2e560c770c7e.png)

3. Break `Purpose and scope` field into two different fields
   - `Applied to` 
   - `Purpose` w/ 200 character limit and help text
 
![Screen Shot 2021-09-01 at 2 30 36 PM](https://user-images.githubusercontent.com/41017988/131747926-38c9ef0f-e11c-4230-ade2-5aabe77f9d8d.png)

4. For non-admins: display `Product`, `Applied to`, and `Purpose` as body copy instead of fields. Like so:
![Screen Shot 2021-09-01 at 2 29 47 PM](https://user-images.githubusercontent.com/41017988/131747849-0c32bd6d-8ddf-457a-8722-79d52ea956eb.png)

5. Paragraphs for non-admins: Remove UI elements that allow adding and reordering paragraphs
   - Paragraphs table heading (the one labeled CONTENT)
   - 'Show row weights' and drag and drop handles
   - Paragraph bundle label
   - 'Remove' button
   - Horizontal line that separates each paragraph

<img width="947" alt="Screen Shot 2021-09-01 at 2 14 11 PM" src="https://user-images.githubusercontent.com/41017988/131746072-50901744-3347-41f6-ba21-f2ee8652119b.png">

6. Add an h2 titled `Content components` like so
![Screen Shot 2021-09-01 at 2 34 05 PM](https://user-images.githubusercontent.com/41017988/131748323-25151f5c-af51-4f33-a1f7-082014d62469.png)

7. Paragraphs for non-admins: Replace SCOPE field group with an uneditable component heading like so. If possible, indent paragraph contents below the heading by 18px. 
![Screen Shot 2021-09-01 at 2 34 50 PM](https://user-images.githubusercontent.com/41017988/131748388-75b9c831-27b8-4320-a0b8-a122240dff60.png)

**Comment by ethanteague** [comment]
@rachel-kauff can you post the link to the figma doc in this ticket? I know it's around here somewhere, I just haven't been able to find it.

**Comment by rachel-kauff** [comment]
@ethanteague Figma link: https://www.figma.com/file/bTK5OXEKBvuXpCLqHLyOyt/Centralized-content?node-id=0%3A1
