### ISSUE TITLE
SPIKE: Curly quotes not straight quotes

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5886]
See epic #5885 for background and possible implementation steps.

AC
- [ ] We have a path to adding some support for curly quotes on va.gov, with or without CMS

**Comment by EWashb** [comment]
Discussed the process with Sitewide Content. Provided them with instructions on adding keyboard shortcuts to alleviate the issue in the interim. After consulting with all stakeholders and our team, CKeditor5 would be the preference because it offers a more holistic fix to the issue. Not only will it help with this, but also #7963. Anything short of that is a patch with high effort. 

However, there are dependencies here with BE search. Special characters are not searchable with the current drupal search functionality. We may need to look into a KB article of "how to search" while we deal with OOTB search and also look into other search options.
