### ISSUE TITLE
Vet Center service creation not defaulting info

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6048]
**Describe the defect**
On a Vet Center page, when you click `Create service` it used to default with the Vet Center and Section of the user. It looks like a regression bug crept in and it's not any more.

**To Reproduce**
1. Go to edit any Vet Center page
2. Scroll down to the list of services
3. Click on 'Create service'
4. See that the Vet Center and Section does not default

**Expected behavior**
Default to the VC and section the user's profile is tied to.

**Screenshots**
![image (17).png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/621737e0-ac46-420c-b121-5002495e22b7)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by ethanteague** [comment]
Not able to reproduce this one, @cmaeng - when I go to `/node/3862/edit` (Jackson Vet center), the two selects for entity association are set, and hidden (expected behavior) - see screenshot.
Gonna close for now, but feel free to open it back up if you are able to reproduce.
![image](https://user-images.githubusercontent.com/2404547/129080512-199b8836-0135-450b-b0c3-99f3b487512d.png)
