### ISSUE TITLE
Ensure codespaces config is ready for use by any developer

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6251]
## Description

As a CMS engineer, I wish to be able to have access to a functional development environment during onboarding, so that I can begin working without a time-consuming setup process.

## Implementation

Follow the instructions under "Local VS Code" on the [codespaces readme](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/codespaces.md#local-vs-code) to get set up.

## Acceptance Criteria

- [x] Development environment is functional ootb
- [x] XDebug is functional ootb
- [x] linting/testing is functional ootb
- [x] [Codespaces README](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/codespaces.md) has been updated for currency & accuracy

**Comment by indytechcook** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6251?planning-poker) with ZenHub @ElijahLynn @ndouglas

**Comment by acrollet** [comment]
Codespaces config is here: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/master/.devcontainer

**Comment by acrollet** [comment]
I just tried firing up a codespace from the latest master and XDebug worked out of the box. So, I'm not sure what was going on before but it would be good for someone else to verify. Making a note that it could be worth investigating the `remote.localPortHost` setting if we have trouble in the future. https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_57.md#port-forwarding-tunnels-are-bound-to-localhost

**Comment by ndouglas** [comment]
I figured I might be a good test case for this because I haven't looked at Codespaces before and have only opened VS Code 2-3 times in my life.

I attempted this but I can't select my own fork of the repo: 

<img width="446" alt="Screen Shot 2021-09-09 at 8 53 03 AM" src="https://user-images.githubusercontent.com/1318579/132689283-22ffde95-7ca2-45ab-933b-3521c98f1b26.png">

My repos are not highlighted, whereas the VA repos are.

Docs are pretty clear overall, just not sure where the issue is here.

**Comment by ndouglas** [comment]
>You'll have access to codespaces under the following conditions:

>- You are a member of an organization that has enabled Codespaces and set a spending limit.
>- An organization owner has granted you access to Codespaces.
>- The repository is owned by the organization that has enabled Codespaces.

The last condition might be an issue.  I think everyone else joined a beta, but I didn't -- maybe that's causing the problem.

**Comment by ndouglas** [comment]
https://github.com/department-of-veterans-affairs/github-user-requests/issues/8171#issuecomment-920226669 **TL;DR**: Looks like this isn't gonna happen for a while, @acrollet

**Comment by acrollet** [comment]
Whoops this one got lost in the github email notifications deluge. I'll bring this up as a 16th minute today but it looks like our only reasoning for using forks is to avoid having lots of branches on the main repo: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/workflow.md#git

**Comment by acrollet** [comment]
16th minute takeaway: let's see if there's a reasonable workflow for creating a codespace from the main repo and then manually checking out the personal fork.

**Comment by acrollet** [comment]
hmm, it's set up with https on my upstream codespace:

```
codespace ➜ /workspaces/va.gov-cms (master ✗) $ git remote -v
origin  https://github.com/acrollet/va.gov-cms (fetch)
origin  https://github.com/acrollet/va.gov-cms (push)
upstream        https://github.com/department-of-veterans-affairs/va.gov-cms.git (fetch)
upstream        https://github.com/department-of-veterans-affairs/va.gov-cms.git (push)
```

**Comment by ndouglas** [comment]
Well, I'll be.  I managed to get it to work.  I assumed they were using some config or MITM or something for auth with GH, but I copypasta'ed my SSH private key and it works 🎉

**Comment by ndouglas** [comment]
@acrollet I added some documentation [here](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/9f40a9b09215a1fcdb41bada43ee5d4c5e8ea0ef#diff-2eecbe798a9758d5039105f597625a4bbecea83da74239aa1a6646a36b3abf0d).  Just lemme know if you want me to go more in detail on anything.

**Comment by ndouglas** [comment]
https://dsva.slack.com/archives/C01AN96U39V/p1632264513024600?thread_ts=1632249082.014900&cid=C01AN96U39V

The story took a turn:

>Okay, so Engineering says this functionality is already available. If you fork a VA owned repo into your personal account, you should be able to launch a codespace from your fork. If you are a member of the VA org, and your fork is a direct child of the VA repo, i.e., not a fork-of-a-fork, then your codespace usage will be billed back to the VA. But I believe you guys said if you attempt to launch a Codespace from your fork, there was no option to do so

https://dsva.slack.com/archives/C01AN96U39V/p1632338628028200

>Engineering said they are about an hour out on the fix, and they hope they can still deploy it to GitHub.com today, but that just depends on how fast they can get code review done it.

This does appear to be working correctly now:

<img width="419" alt="Screen Shot 2021-09-23 at 6 18 04 AM" src="https://user-images.githubusercontent.com/1318579/134491185-f8d73b22-60b8-4a05-ade5-b53229a2c1ac.png">

Since @timcosgrove has already opened a PR through Codespaces, I think this can be considered done, and since the problems I encountered were due to a Codespaces bug there doesn't seem to be any need for additional documentation.  I'm going to assign Tim on this issue too, since he deserves the credit for 1) testing this, and 2) actually getting the root issue identified and fixed.
