### ISSUE TITLE
Implement temporary workaround to prevent GraphQL notifications during deploy downtime

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6290]
## Description

As a CMS Devops Engineer, I wish to not receive GraphQL alerts during CMS deploy windows, so that I am not distracted by unnecessary notifications.

## Implementation

Datadog does not appear to directly offer boolean logic for API test assertions - they document this workaround: https://docs.datadoghq.com/synthetics/guide/or-logic-api-tests-assertions/

## Acceptance Criteria

- [ ] GraphQL alerts are not generated during CMS deploy windows

**Comment by olivereri** [comment]
Trying to understand the implementation details on the issue.  During the deployment should the API endpoint return anything besides a 503? I'm not sure how a match regex comparator is going to work here.

This was from a deploy outside the scheduled deployment window today:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/7ee5d58c-3978-4edb-a150-48140019127e)
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/49de639c-9c83-4b38-b6a9-f2279c53bdd8)
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/c3c27ddf-f950-424f-a5b1-6b7474448ecd)

We want to catch 503s but it's impossible in Datadog to tell the difference from 503s during a deploy.  What might make a bit more sense would be to set the alert to go to CMS Critical. During a deploy CMS Critical should be in a maintenance window and won't alert. Should the API being down be considered a critical event as well? Thoughts?

**Comment by olivereri** [comment]
> We want to catch 503s but it's impossible in Datadog to tell the difference from 503s during a deploy. 

But there is a way since the 503 returned is one crafted by Drupal with a predefined response body. Parsing the `response body` for text like `System update in progress` will identify real 503s from deploy 503s. Test success can be defined as: if `status code` is `503` and `response body` contains `System update in progress` should the Pagerduty maintenance window route not work.

**Comment by acrollet** [comment]
@olivereri could you briefly mention what solution you ended up using on here? Thanks!

**Comment by olivereri** [comment]
> @olivereri could you briefly mention what solution you ended up using on here? Thanks!

The DataDog Monitor was sending to a message to PagerDuty CMS-NonCritical service and alerting during a maintenance window since one isn't configured for that service.  Instead since this is critical the message DataDog sends was directed towards CMS-Critical which respects the Production maintenance window and won't alert to Slack during that time.
