### ISSUE TITLE
Identify initial 2-3 products to use for PoCs

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6509]
## Background

As a CMS engineer, I need to determined which products to use for PoCs, so that I may test each hypothesis against representative content.

## Implementation

Perhaps one high volume, standard content type, one non-standard content type (R&S?)

## Acceptance Criteria

- [ ] 2-3 API use cases to test have been identified and documented in the epic's description
- [ ] Above use cases have been socialized with FE teams

**Comment by acrollet** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/content-build/menus-widgets-apis.md#resources-search

**Comment by indytechcook** [comment]
Current product content model: https://whimsical.com/va-gov-high-level-content-model-PyatLZVHkA8QPxzuAqUEe8

**Comment by indytechcook** [comment]
Drupal content types represented in the "Resources" Product: https://github.com/department-of-veterans-affairs/vets-website/blob/900b03495c07dbcf470cbd464d568f2229c8d3bc/src/site/stages/build/plugins/create-resources-and-support-section.js#L28

* `q_a`
* `checklist`
* `media_list_images`
* `media_list_videos`
* `support_resources_detail_page`
* `faq_multiple_q_a`
* `step_by_step`

**Comment by timcosgrove** [comment]
@indytechcook and I discussed `q_a` as a reasonable section of the Resources product. We also talked about Banners as being potentially a good candidate for the POC, partly because the data is relatively simple and partially because having Banners available via live Content API would be a win, since it could then feed a component that pulls Banners in real time and therefore Banners would no longer need to trigger builds.

**Comment by acrollet** [comment]
@timcosgrove Resources search

**Comment by timcosgrove** [comment]
POC use cases
**Q&A**
[] Endpoint returns sufficient data to render the content of the page (menus, sidebars etc not included at this stage)
[] Individual QA page renders via live data
[] Updates to the CMS content reflect immediately in that render
* example page: https://www.va.gov/resources/how-do-i-change-my-name-in-my-deers-record/
* More added if they show interesting scenarios.
* QA chosen because it is sufficiently complex - multiple paragraph fields as well as other entity references - while being less complex than say FAQ, which collects multiple QAs together.

**Resources search**
[] Endpoint returns sufficient data to match the functionality of the current resources search
[] Resources search widget makes use of this endpoint and can be interacted with via live CMS data
[] CMS updates reflect in the search results returned
* Chosen as a more 'interactive' element that is nevertheless currently driven by a process which renders data to a static file

**Banners**
[] Banners for a given page are retrievable by route or page ID (i.e. an endpoint exists that, given a page, will return any banners that should display on that page)
[] Banners can be added and modified via the CMS, including adding new display paths to an existing banner, and the banner data will then be available via that endpoint for that page/route
* Chosen because Banner addition/update is currently a content-build trigger independent of hourly build, and so removing the need for that build trigger would be a win
* Chosen because the need for banners is often time sensitive, and so allowing them to essentially be published instantly would be a huge win.

**Comment by indytechcook** [comment]
This is great and pretty much where I was going.

> More added if they show interesting scenarios.

What does this mean?

**Comment by timcosgrove** [comment]
> > More added if they show interesting scenarios.
> What does this mean?

Just that if there's a URL/page that shows anything interesting re: how the POC API is pulling that information together, they would be added as an example. I just wanted to identify specific pages that we'd show, just so we have them at hand, especially since it's a pretty small set of QAs that are available as pages.

Editing the text to make it more clear

**Comment by mchelen-gov** [comment]
https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1923088577/CAPI+Proof+of+concept+use+cases
