### ISSUE TITLE
Design inline taxonomy term content for Vet Center and VAMC services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6641]
## User Story or Problem Statement

From #5800 
1. As an editor of health service content at a VAMC or Vet Center, I want to be able to see the nationally standardized content, such as general service description and the patient friendly name, within my form (and on proofing screens), so that I can write my content in relation to it (and so I can avoid duplicating anything).

Examples of where I'm working:
- [VAMC System Health Service form](https://staging.cms.va.gov/node/5352/edit)
- [VAMC System Health Service proofing screen](https://staging.cms.va.gov/philadelphia-health-care/health-services/women-veteran-care-at-va-philadelphia-health-care)
- [Vet Center Service form](https://pr6622-5yhhe6qab5dz3plu1gtbtud9yorrvyhz.ci.cms.va.gov/node/3690/edit)

- You can see an example of this national service content implemented (without design) as screenshots in Ethan's POC issue, #6622 

2. [Stretch] As an editor of health service content at a VAMC or Vet Center, I want to be know who controls this content, in case I wan't to request a change to it.

3. [Stretch] As a manager of national health service content, I want to be able to collect feedback about the health service taxonomy in a standardized way, so that I can respond to it.

~~See #6332 For epic about required Vet Center services~~ (Moved into a separate issue)

## Assumptions you can make for design

All taxonomy terms have a Type of Care value and a Description. Some also have Patient-friendly name.  Some VAMC services also have "Common conditions", but Vet Centers typically don't.  You can see the diversity of data at https://prod.cms.va.gov/vha-health-services

## Artifacts
[Figma prototype](https://www.figma.com/file/SfJsjIxAySehvDsrgyusxh/Standardized-content-design-patterns?node-id=0%3A1)

## Acceptance Criteria

Figma prototype that covers various scenarios
- [ ] Vet Center services form (inline on the Vet Center content type form, eg  /node/3690/edit)
   - [x] Default: "Service description" and "Type of Care" 
   - [x] Variant 1: add "Patient friendly name" 
  ~~- [x] Variants 2: Required or not required health services (Vet Centers for now, but probably VAMC in the future)~~
   - [x] Update linked Knowledge Base article with more specific content guidance about "care we provide"
   ~~- [ ] Stretch: Proofing experience for Vet Center services~~ 
- [x ] VAMC system health service form
   - [x] Default: "Service description" and "Type of Care" 
   - [x] Variants: Add "Patient friendly name" and/or "Common Conditions" 
   - [ ] Update linked Knowledge Base article with more specific content guidance about "care we provide"
  ~~- [ ] Stretch:  Proofing experience for VAMC system health service (this already exists to some extent, see for example [Pulmonory medicine at Houston Health Care](https://prod.cms.va.gov/houston-health-care/health-services/pulmonary-medicine-at-va-houston-health-care))~~
   
## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
@rachel-kauff [The boilerplate content is in this airtable tab](https://airtable.com/appFAI4CcmcIhg767/tbl287e56dBRPTRfI/viwzCioMcKFhc8l7Z?blocks=hide). In some ways, the boilerplate _is_ the guidance, but people stray from it.

**Comment by EWashb** [comment]
@kevwalsh @rachel-kauff  Stan referred me to Larry West. He provided the following explanation yesterday, 11/11/21:

Primarily, we wanted to keep the descriptions concise while also making them informative and useful to Veterans, their families, and their caretakers. In addition, we wanted to create standardized descriptions for all system health services, which could be used across all systems with either no changes at all or only slight variations in cases where a system might have some unusual specialty. To that end, the guidance we used was:

- An introductory paragraph of 1-3 sentences, giving a general description of the health service.
- No more than 6 bullets (and preferably fewer) with additional details.
- Bullets should be relative short, 128 characters or less, with no more than one bullet exceeding that length.

As you can see, we were trying to force these descriptions to be concise. In practice, the character count restriction proved unwieldy in some cases, because there were a few health services that required us to name specific medical tests or treatments that ran long. That wasn't really a problem, because all of these points were intended as guidelines rather than rules set in stone. Their primary purpose was to give us a framework and to remind us to make the descriptions concise, clear, and easy to understand. You may want to set a less restrictive character count for these, or you may prefer to drop it altogether and simply remind people to keep the bullets short and to the point.
We eventually standardized all system health descriptions and created a master health services library and taxonomy, which became the basis of everything you see today.
