### ISSUE TITLE
POC: Set up Lagoon on EKS and get a demo of the CMS up and running

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#6674]
## Description

As a CMS engineer, I would like to validate that Lagoon will be sufficient for our needs so that we can begin to evaluate the value and cost-savings that Lagoon potentially offers.

## Acceptance Criteria
- [x] We have administrative access to a cluster for testing purposes
- [x] Documentation has been added concerning the details of:
  - [x] deploying and configuring the Lagoon system on EKS
  - [x] configuring end user tooling for Lagoon
  - [x] creating and deploying a Lagoon project for the CMS 
- [x] A retrospective report on the proof-of-concept has been authored and made available to the CMS team and other interested parties.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

Related #6673

**Comment by ndouglas** [comment]
I'm blocked on moving _much_ forward by the outgoing Git/SSH issue, but I can move forward with other things...

## EFS
I created an EFS filesystem `dsva-vagov-lagoon-dev-cms-efs` and created it with the following command:

```
helm upgrade --install --create-namespace --namespace lagoon-efs-provisioner -f efs-provisioner-values.yaml  lagoon-efs-provisioner stable/efs-provisioner
```

This created a storage class with the name `lagoon-bulk`.  Easy enough.

That does nothing to unblock me with regard to Git/SSH, though, and I still need to figure out a couple things:
- logging (this looks nontrivial)
- file transfer from prod
- database transfer from prod
- ???

**Comment by ndouglas** [comment]
The ops team, in office hours, confirmed our suspicions that this restriction on outbound SSH is pretty legit.  As such, this PoC is blocked.

We have a number of options for moving forward:

* Press forward with Lagoon
    * Open port 22 outbound + appeal up the chain as necessary
    * Fix lagoon to support https clone (see [this discussion](https://github.com/uselagoon/lagoon/discussions/2898))
        * Then maybe composer install issues
        * Definitely would need to fix CA trust in the build container so VA can MITM with us
    * Do we even _need_ to worry about the dev/stage/prod vpcs? Why? Can we just run in util?
    * Move Lagoon builds to Utility _then_ ship them off to the various VPCs?
* Non Lagoon solutions?
    * Lots of options

**Comment by ndouglas** [comment]
## Roundabout Approaches

![RnGEd93](https://user-images.githubusercontent.com/1318579/139862670-efd29013-0e8d-4b47-befd-c28427ef266a.jpg)

A few of the options above could actually be addressed.  I've addressed them, sorta, and will discuss.

### Modifying the Lagoon Build Deploy Image

No one has responded yet to my [discussion thread](https://github.com/uselagoon/lagoon/discussions/2898) about git cloning via HTTPS.  However, even if they had, it wouldn't work because the DHS is MITMing the TLS.

I forked the [Lagoon service images](https://github.com/ndouglas/lagoon-service-images), rebuilt the `kubectl` image, pushed it to Docker Hub, modified the derivative `kubectl-build-deploy-dind` image to insert the cert, rebuilt the image, and pushed it to Docker Hub.

The second half of that was to actually alter the Lagoon configuration to use the new Docker image.  I injected the override into the remote-values.yaml and updated the `lagoon-remote` deployment, but unfortunately the keycloak pods went into `ImagePullBackoff` because we'd hit the Docker pull limit.

### Modifying the codebase

There are some changes that need to be made to the CMS codebase as part of a move to Lagoon.  I made them in #6867, although I have no way of testing them.

**Comment by ndouglas** [comment]
Per this exchange:

<img width="633" alt="Screen Shot 2021-11-02 at 12 52 22 PM" src="https://user-images.githubusercontent.com/1318579/139909958-dd3a7bb1-c5af-4ff9-be75-f3c60f312fc5.png">

There is no way to move forward with this PoC.

**Comment by ndouglas** [comment]
![](https://user-images.githubusercontent.com/1318579/140052597-1a402404-d62a-4587-b185-302a8f4c7bc2.jpeg)

So got some responses on [this discussion thread](https://github.com/uselagoon/lagoon/discussions/2898) saying that although the build-deploy pipeline was implemented with Git/SSH in mind, that was mostly to accommodate GitHub deploy keys and that there was no real hard reason that HTTPS cloning should not work.

Who's to blame?

![The Tick](https://user-images.githubusercontent.com/1318579/140052899-0ff9ddf9-e7c4-478f-9981-d5c73490f562.jpg)

I mentioned that I'd injected the TIC TLS cert into a Docker container, at which point Toby pointed out that I was using an older Dockerfile -- a great catch which undoubtedly would save me some frustration.

So going back to Docker to build the new image:

```
#17 20.15   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#17 20.16                                  Dload  Upload   Total   Spent    Left  Speed
100 38.3M  100 38.3M    0     0  17.7M      0  0:00:02  0:00:02 --:--:-- 17.7M
#17 22.33   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#17 22.33                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
```

I ran into [this issue](https://github.com/concourse/concourse/issues/6038) which seems to plague Docker for Mac.  I don't want to upgrade Docker for Mac because that's caused issues with Lando in the past.  Fortunately, I have about sixty LXC containers with Docker installed, so I'll just SSH into one of them and build the image and push it from there.

Well, then SSH is hanging.  I can't SSH into any of said containers, or anything else on my network.  SSH works with everything else on my network... except my work computer.

![st,small,507x507-pad,600x600,f8f8f8](https://user-images.githubusercontent.com/1318579/140055131-113886e3-8f20-429f-a8e3-37ab49c2d988.jpg)

I attempted to find a solution for a few minutes, but being pressed for time I ended up just switching computers, SSHing into my work computer from my personal computer, grabbing the updated Dockerfile, then SSHing into an LXC container to build the `kubectl` and `kubectl-build-deploy-dind` images.  After adding my SSH pub key for that machine to GitHub.  And `docker login`ing.

The CMS project's URL is HTTPS, so I can attempt to deploy the branch PR to see where my PR (see #6867 ) fails:

```bash
🔔nathan.douglas@Belmore:~/Projects/lagoon-stuff$ lagoon deploy branch -p lagoon-dev -b VACMS-6674-lagoon
✔ Yes
success
```

Now I can log into Lagoon UI because Keycloak is running because it's no longer in `ImagePullBackoff` because it didn't have Docker Hub credentials.  

And:

<img width="1323" alt="Screen Shot 2021-11-03 at 8 17 16 AM" src="https://user-images.githubusercontent.com/1318579/140058490-48f37d9d-ffd7-4c23-83a9-b0af5cc751d4.png">

🎉 

It's taking longer to fail than it has before.  Which is, technically, progress.

```
🔔nathan.douglas@Belmore:~/Projects/va.gov-cms$ kubectl get pods --all-namespaces | grep lagoon-build

lagoon-dev-vacms-6674-lagoon   lagoon-build-vkn4ha                                            0/1     Error               0          3m12s
lagoon                         lagoon-remote-lagoon-build-deploy-758bd85997-vdkth             2/2     Running             0          18h
🔔nathan.douglas@Belmore:~/Projects/va.gov-cms$ kubectl logs -n lagoon-dev-vacms-6674-lagoon lagoon-build-vkn4ha
<snip>
HEAD is now at 040fe2b7 Fix webroot.
+ git submodule update --init --recursive --jobs=6
+ [[ -n '' ]]
+ '[' '!' -f .lagoon.yml ']'
++ cat .lagoon.yml
++ shyaml get-value environment_variables.git_sha false
+ INJECT_GIT_SHA=true
+ '[' true == true ']'
++ git rev-parse HEAD
+ LAGOON_GIT_SHA=040fe2b79034c9f31832b64bd9281d9188df7973
+ REGISTRY_SECRETS=()
+ PRIVATE_REGISTRY_COUNTER=0
+ PRIVATE_REGISTRY_URLS=()
+ PRIVATE_DOCKER_HUB_REGISTRY=0
+ PRIVATE_EXTERNAL_REGISTRY=0
+ set +x
User "lagoon/kubernetes.default.svc" set.
Cluster "kubernetes.default.svc" set.
Context "default/lagoon/kubernetes.default.svc" created.
Switched to context "default/lagoon/kubernetes.default.svc".
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://harbor.lagoon-dev.cms.va.gov/v2/: x509: certificate is valid for *.ci.cms.va.gov, *.demo.cms.va.gov, *.tugboat.vfs.va.gov, tugboat.vfs.va.gov, not harbor.lagoon-dev.cms.va.gov
```

So something is requesting Harbor, but doing so via HTTPS and not HTTP.  Since I've not specified HTTPS anywhere, this would appear to be an issue with a script somewhere.

After doing so, I don't see any commands issued after `WARNING! Using --password via the CLI is insecure. Use --password-stdin.`, which is a Docker error message.  So I think the HTTPS error is from Docker attempting to log in to Harbor and failing to do so because of the certificate.

Why?  Well, [Docker requires some additional configuration](https://docs.docker.com/registry/insecure/) for insecure registries -- configuration that I don't believe the `kubectl-build-deploy-dind` scripts perform.  So I gotta do that.

The problem is that I think since this is built around Docker-in-Docker that we're using insecure registries as specified by the host, not by the container.  So I think this might be doomed to fail.

<snip: I tried it anyway.  It failed.>

So the only way to move forward at this point, AFAICT, is to add the insecure registry for Harbor to the `/etc/docker/daemon.json` file, add that to a custom AMI, and recreate the EKS cluster using that AMI.  As far as I can tell.

So I'm blocked again.

**Comment by ndouglas** [comment]
LOL, I remember none of this.

Summarizing significant issues that I encountered in this PoC:

1. Lagoon attempts to clone repos via SSH, but SSH outbound is blocked by the TIC. We need to keep Lagoon Core in the `vagov-utility` VPC and corresponding EKS cluster, which means outgoing connections transit the TIC. This means Lagoon needs to support HTTPS cloning.

2. Lagoon's Docker image builds target Harbor and that's viewed as "insecure" from the perspective of EKS at this time, and we don't have authority to modify the relevant settings in the EKS cluster. So we might conceivably need to set request and justify settings modifications to support using Harbor insecurely or do the necessary work to make Harbor secure from the perspective of the EKS cluster.
