### ISSUE TITLE
CMS SSOi Monitoring and Alerting

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#6704]
## Acceptance Criteria
- [ ] SSOi status is monitored within CMS-controlled systems (see https://iamportal.iam.va.gov/iamv2/index.php) 
- [ ] SAML signing certificates are monitored for validity 
- [ ] When SSOi is down or a signing certificate is found to be expiring within 2 weeks or invalid, CMS engineers are alerted
- [ ] Monitoring and alert config is in code

### CMS Team

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by ENeal49** [comment]
Noting you can access url.

**Comment by cweagans** [comment]
Apologies, didn't see this @ENeal49 . From what I've heard, I don't think we can accomplish the intent of this ticket (which to my understanding was to monitor the validity of the signing certificate, not the availability of the SSO service).

However, based on recent communication from the IDM team (regarding next weeks cert rollover), I'm not sure we _need_ to do this anyway. They were pretty communicative. Maybe we just put an event on the shared calendar for the expiration date of the new certificate that is rolling out next week and call it a day?

**Comment by ElijahLynn** [comment]
Related thread with one of the IAM Architects, Damien DeAntonio: https://dsva.slack.com/archives/CSFV4QTKN/p1638469647312700

**Comment by cweagans** [comment]
We landed on this not being possible due to SSOi not providing a metadata endpoint for us to use to retrieve the signing certificate. Next actions here:

* [ ] Add a check for HTTP 200 on iamportal.iam.va.gov/iamv2/index.php every few minutes
* [x] Add extra ACs to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7026 to set up Slack/Confluence reminders for cert expiration

**Comment by jkalexander7** [comment]
Followup ticket for HTTP 200 check: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7174
