### ISSUE TITLE
Implement top task form designs from #6877

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6878]

**Comment by suzanne-gray** [comment]
design file here: https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=0%3A1

**Comment by JayDarnell** [comment]
@EWashb @kevwalsh @swirtSJW @cmaeng @suzanne-gray - things got a little murky this sprint in terms of which tickets the top task work lived in. A bunch of items from this ticket (work items coming from #6877) ended up being implemented as part of #6880. But because this ticket wasn't assigned to me I didn't look at it and some items were likely missed.

I think we should make sure any items not implemented are carried over to #7595 and close this ticket. I made 7595 yesterday as a catch all for outstanding top task UX work.

**Comment by kevwalsh** [comment]
Closing this in favor of #7595
