### ISSUE TITLE
[POC] Evaluate WayPoint project for the CMS

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7010]
## User Story or Problem Statement

As a CMS engineer, I want to explore the technical feasibility of WayPoint, so that we can evaluate adopting the solution for running and deploying the Drupal CMS.

## Acceptance Criteria
- [ ] Research the tool and explore the offered features
- [ ] Get a test instance of the tool up and running
- [ ] Get a test instance of the CMS up on the tool
- [ ] Evaluate the tool against the decision criteria with some info about why the scores were set
- [ ] Document findings within ticket

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by indytechcook** [comment]
Here is the evaluation criteria: https://docs.google.com/spreadsheets/d/1thN-Hs_k5R3WDVoXZEqb6OIJ3RDJzjlT4Krw2dxYZPE/edit#gid=0

**Comment by cweagans** [comment]
# Findings

I did not get Waypoint up and running in the VA-managed kubernetes cluster on AWS due to access issues. By the time I had my access straightened out, I was already well into local experimentation. Fortunately, experimenting with Waypoint locally was enough (IMO) to make an assessment about whether or not it would be a good fit for the VA.

## The good

* I was extremely happy with how easy Waypoint was to set up. After installing the Waypoint client (more on this later), installing the Waypoint server was three commands (as detailed [in the docs](https://www.waypointproject.io/docs/kubernetes/install#installing-the-waypoint-server-with-helm)). The details of this express setup method are largely irrelevant and for our purposes, we can assume that they'll work as expected on the VA kubernetes cluster (the biggest question would be whether or not there is persistent volume support set up on the cluster. If not, that would be a fairly minor undertaking).
* The command line tool and developer experience of working with Waypoint to deploy an application are both excellent. Waypoint operates from a small manifest file that uses the same syntax as Terraform. The overall structure of this manifest can be seen here: https://www.waypointproject.io/docs/waypoint-hcl#template-waypoint-hcl
* Waypoint has separate lifecycle states for build, release, and deploy as our current tooling does, but the meanings are slightly different from how we use those terms in that `release` is staging the application up on the target infrastructure and `deploy` is promoting it to a state where it's actually handing traffic (lifecycle docs are here: https://www.waypointproject.io/docs/lifecycle).
* Waypoint has an _extensive_ hook system that in my opinion is the gold standard for any kind of deployment orchestration tool. It's simple, but extremely powerful. You can essentially run any number of extra scripts before or after any of the lifecycle states and determine if the deployment should continue if one of the hooks fails. Docs are here: https://www.waypointproject.io/docs/lifecycle/hooks
* As with many other Hashicorp products, Waypoint is extensible through a very nice plugin system. You can use the Waypoint SDK to extend Waypoint in any language as long as that language is Go (in theory, you could extend Waypoint with any language that can speak gRPC, but the SDK is not available in any other language and it may be a somewhat painful experience).

## Some annoying things

* Waypoint can perform operations in a number of different ways and it's not always clear _where_ those operations are being executed. For example, Waypoint has the concept of _runners_ (in the same way that Github Actions does). These runners can be used to do a number of things including running arbitrary commands in waypoint-managed application containers or watching a git repository for changes and doing continuous deployment. The waypoint CLI can _also_ do some of these things. If you have a hook configured, it'll run in a runner. If you run `waypoint run foo`, the execution is actually happening locally (the cli basically registers itself as a temporary runner while the operation is in progress). This can be a problem if you expect that an operation is going to run in the same way every time (for instance, if it needs access to something on the VA network). This would be a pretty frustrating thing to try to debug if we were triggering waypoint operations through github actions or similar. It's worth noting that you can do without runners, but some operations won't happen automatically (like polling a git repo) and would have to be kicked off manually through the CLI.
* Waypoint has a built-in temporary URL creator thing that uses a public service hosted by Hashicorp. It's super convenient for testing purposes, but would present some challenges for us if we were to operate Waypoint in production. You _must_ have a waypoint URL service available, and while you can disable the public URL service that is enabled by default and self-host the same service, it's a much bigger lift and frankly not something that we should have to do. Unfortunately, I think it's something that we'd be _required_ to do since the Hashicorp URL service is (presumably) not fedramp'd. The docs even warn against it: https://www.waypointproject.io/docs/url#self-hosting

## The bad

* A Waypoint server is the largest unit of deployment in the Waypoint world. That is, a Waypoint server expects to "own" all aspects of a deployment of any number of versions of an application and having separate waypoint servers running for dev, staging, and prod would be extremely cumbersome (switching waypoint servers in the cli requires a re-auth, which is mostly an interactive operation as far as I can see. Maybe it could be automated somehow, but that'd be a big question mark for me). Hashicorp does have this on their roadmap though: https://www.waypointproject.io/docs/roadmap#app-promotion -- it appears that they're going to extend their existing Workspaces feature to allow it, so potentially down the road, this may not be an issue.	
	* It's worth noting that this has been a persistent problem for us when evaluating various Kubernetes tools. Having completely separate clusters in completely separate VPCs that can't talk to each other is a very weird setup that not many tools will accommodate out of the box. It might be worth discussing whether or not we can reframe that a bit. For instance, can we run all of the dev, stage, prod, and PR environments in the production VPC? That is, we'd consider "production" the production version of the infrastructure, not just the production version of the various applications running on it.

# Conclusion

Maybe Waypoint is an option down the road. It's a nice experience and it would be great to be able to lean into the Hashicorp ecosystem more, especially if they can help us get it up and running properly in our weird multi-VPC environment. For now, upgrading BRD still seems like a much more straightforward option and I would advocate for continuing on that path. I'm not in a huge rush to take on the complexity of Kubernetes, but if we do, I'd be pretty happy about using Waypoint.
