### ISSUE TITLE
SSOi status monitoring and alerting

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7174]
## User Story or Problem Statement

CMS SSOi status is monitored and CMS engineers are alerted when SSOi is down so that we can respond as quickly as possible and restore service to CMS editors.

## Acceptance Criteria

- [x] Add a check for HTTP 200 on iamportal.iam.va.gov/iamv2/index.php every few minutes
- [x] Alert is sent in event of SSOi failure

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by mchelen-gov** [comment]
@cweagans is there some cert error coming from DD synthetic agent when querying https://iamportal.iam.va.gov/iamv2/index.php ?

**Comment by cweagans** [comment]
@mchelen-gov Sorry for the delay getting back to you here. Yes, the datadog test is failing because that URL uses the internal VA CA. I have another PR open that allows self-signed certs, which should sidestep that issue for now. It's probably worth looking into why the synthetic agent doesn't know about our CA though.
