### ISSUE TITLE
Test and validate drupal running on Amazon Linux 2 with PHP 7.4

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7583]
## User Story or Problem Statement

As a CMS engineer, I need to run Drupal on Amazon Linux 2 (on CMS test) so that I can validate this solution works with PHP 7.4 and move forward with further upgrades of the BRD system.

## Acceptance Criteria

- [x] Validate no issues with running on PHP 7.4
- [x] Ensure post-deployment tests complete successfully
- [x] Application server build won't fail at first Ansible SSH connection attempt that prevents successful build.
- [x] Implement systemd specific automated environment variable injection for HTTPd service. This is done ad hoc to make drupal work
- [x] Add new cms application user https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2526

**Comment by jkalexander7** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/7583?planning-poker) with ZenHub @amponce @cweagans @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by olivereri** [comment]
Previous work on AL2 + PHP 7.4 for CMS in BRD tracked in this branch:
https://github.com/department-of-veterans-affairs/devops/tree/eo-cms-test-aml2

**Comment by olivereri** [comment]
### RE: AC: Add DSVA user to sshd_config's AllowUsers at startup or baked into the base image

It really looks like the Ansible tasks are running before the user-data script completes:

**/var/log/secure**
```
Jan 19 19:09:16 ip-172-31-16-8 sshd[2508]: Invalid user dsva from 52.61.71.205 port 14529
Jan 19 19:09:16 ip-172-31-16-8 sshd[2508]: input_userauth_request: invalid user dsva [preauth]
Jan 19 19:09:16 ip-172-31-16-8 sshd[2508]: Connection closed by 52.61.71.205 port 14529 [preauth]
**Jan 19 19:09:16 ip-172-31-16-8 useradd[2522]: new group: name=dsva, GID=1001
Jan 19 19:09:16 ip-172-31-16-8 useradd[2522]: new user: name=dsva, UID=1001, GID=1001, home=/home/dsva, shell=/bin/bash**
Jan 19 19:11:14 ip-172-31-16-8 useradd[2763]: new group: name=ssm-user, GID=1002
Jan 19 19:11:14 ip-172-31-16-8 useradd[2763]: new user: name=ssm-user, UID=1002, GID=1002, home=/home/ssm-user, shell=/bin/bash
```

**Comment by mchelen-gov** [comment]
@olivereri that change is acceptable to me :+1:

**Comment by olivereri** [comment]
/var/log/httpd/error_log output while using test.staging.cms.va.gov


`[Wed Jan 26 19:08:54.330178 2022] [http2:warn] [pid 4472] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive`

`[Wed Jan 26 19:08:54.347409 2022] [mpm_prefork:notice] [pid 4472] AH00163: Apache/2.4.52 () OpenSSL/1.0.2k-fips PHP/7.4.26 configured -- resuming normal operations`

`[Wed Jan 26 20:17:41.638227 2022] [autoindex:error] [pid 13227] [client 10.247.34.152:53524] AH01276: Cannot serve directory /var/www/cms/docroot/static/health-care/: No matching DirectoryIndex (index.php,index.html,index.htm) found, and server-generated directory index forbidden by Options directive, referer: http://internal-dsva-vagov-staging-cms-test-1869958309.us-gov-west-1.elb.amazonaws.com/static/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services/
`

**Comment by ndouglas** [comment]
Just for the record, I've seen those messages under the current iteration of BRD, so I don't think they represent a change in configuration or behavior:

e.g.:

```
[Wed Jan 26 23:13:15.440977 2022] [http2:warn] [pid 4628] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Wed Jan 26 23:13:15.441354 2022] [lbmethod_heartbeat:notice] [pid 4628] AH02282: No slotmem from mod_heartmonitor
[Wed Jan 26 23:13:15.509531 2022] [mpm_prefork:notice] [pid 4628] AH00163: Apache/2.4.52 (Amazon) OpenSSL/1.0.2k-fips PHP/7.3.30 configured -- resuming normal operations
[Wed Jan 26 23:13:15.509550 2022] [core:notice] [pid 4628] AH00094: Command line: '/usr/sbin/httpd'
[Wed Jan 26 23:30:09.447127 2022] [php7:notice] [pid 15326] [client 10.247.35.50:57086] PHP Notice:  MemcachePool::get(): Server 10.247.34.27 (tcp 11211, udp 0) failed with: SERVER_ERROR object too large for cache\r\n (3) in /var/www/cms/docroot/modules/contrib/memcache/src/Driver/MemcacheDriver.php on line 60
[Wed Jan 26 23:59:54.767349 2022] [php7:notice] [pid 28799] [client 10.247.35.50:61848] PHP Notice:  MemcachePool::get(): Server 10.247.34.27 (tcp 11211, udp 0) failed with: SERVER_ERROR object too large for cache\r\n (3) in /var/www/cms/docroot/modules/contrib/memcache/src/Driver/MemcacheDriver.php on line 60
[Thu Jan 27 00:20:34.658621 2022] [autoindex:error] [pid 2721] [client 10.247.35.50:1476] AH01276: Cannot serve directory /var/www/cms/docroot/static/health-care/: No matching DirectoryIndex (index.php,index.html,index.htm) found, and server-generated directory index forbidden by Options directive, referer: http://internal-dsva-vagov-staging-cms-1188006.us-gov-west-1.elb.amazonaws.com/static/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services/
```

**Comment by ndouglas** [comment]
(sorry, moved wrong issue)

**Comment by olivereri** [comment]
## Solution details
- [ ] Ensure post-deployment tests complete successfully

Two separate problems were solved to satisfy this AC:
1. Previous (AL1) Memcached yum packages created a initialization file in /etc/php.d/20-memcached.ini. The build process appended parameters to this file. The new (AL2) provided yum packages creates a 40-memcached.ini in the same directory. The build was creating 20-memcached.ini and the package was creating 40-memcached.ini and PHP kept trying to load it twice and threw warnings. These warnings kept failing post-deploy test.
2. This overlaps with the next AC. While the proper way to provide Systemd Services with additional configuration items like environment variables was used, the httpd service still wouldn't load them and failed to connect with the database at testing time. The Deployment Ansible tasks weren't waiting for AWS instance post-boot scripts (user-data) to complete. This caused problems with the httpd service and properly loading environment variables. Adding this wait just after deployment is created fixed the issue.

- [ ] Implement systemd specific automated environment variable injection for HTTPd service. This is done ad hoc to make drupal work
1. Short circuiting this method `systemctl edit myservice` to directly create and populate a file in path `/etc/systemd/system/httpd.service.d/env.conf` which Systemd will read env vars when the service starts and is available to the service to connect to devices like Databases. The only complicationg factor was that AWS Instance post-boot scripts would prevent this from working properly; explained above.

This solution works well because we only host one website with Apache. If we have the need to over host more, we will need to rethink how env vars are provided to the service and narrow it down only to the specific vhost to prevent other vhosts from accessing unnecessary vars.

**Comment by ndouglas** [comment]
In response to your closing thoughts, I think SetEnv/PassEnv might be better than the systemd approach.  That'd mean in many cases that we'd need to modify settings.php to get those from `$_SERVER` (where PHP accesses Apache environment variables) to `$_ENV` (where PHP accesses process enviroment variables) or something else.  

IMHO it's a nasty anti-pattern for module code to read these directly, and they should be in some sort of DI container or whatever, but the Raven module reads its Sentry config from `$_SERVER` directly and I'm sure other modules read `$_ENV` directly and so forth.  Our `settings.*.php` files do, but there's not much we can do about that given how early those are called in the app lifecycle.

Just thoughts for the future. 🔮
