### ISSUE TITLE
Design h1s CMS editing experience for each content type

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7698]

**Comment by EWashb** [comment]
@laflannery I know I'm asking a lot here, but do you know of anything a11y related for H1s off the top of your head? I know we've chatted about header issues CMS wide. Maybe this is what this ticket was getting at? If so, we probably have a ticket you've already created for this. If not, I'll close it.

**Comment by laflannery** [comment]
Regarding H1, there should be one and only one on a page. I believe we already have that covered - from what I've seen so far on the front-end, the Page title is the H1 and we do not allow the editor to add additional H1s within the rich text editors so I feel the main concerns are covered.

Within the CMS itself there is an issue of multiple H1s but I am aware of this and was wrapping this into the overall heading structure issues.

I can't really think of anything else this might be referring to? I think you can probably close this because I do think we have this covered with other tickets.
