### ISSUE TITLE
Investigate content build slowdown due to code changes between 2021-12-23 and 2022-01-04

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7724]
## Description
Around Jan 3 2022, the average content build time became approximately 5 minutes slower: https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?fullscreen_end_ts=1642813745148&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1640135345148&fullscreen_widget=7727346438800838&from_ts=1640369100921&to_ts=1643047500921&live=true

There does appear to be some change in GraphQL time at this point, but it does not explain the shift. Taking GraphQL time out of total build time shows that the non-GraphQL time has also jumped: https://app.datadoghq.com/dashboard/gm3-xnt-et5?fullscreen_end_ts=1643047588779&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1640369188779&fullscreen_widget=8055303753625958&from_ts=1640369184121&to_ts=1643047584121&live=true

The jump almost certainly happened as we came out of code release. Therefore, there is a range of work that could be responsible for the change. This is the full range of commits from 12/23 - 1/5, beginning of code freeze until just beyond: https://github.com/department-of-veterans-affairs/content-build/compare/22763456b64f001903126c2cebe2a38b0fe8c561...4b29aa4bb7405a01fb25255811d545da9fe2d934

We should do timeboxed investigation into this to identify the changes that have caused the slowdown. If fixing the problem is more involved than an hour's work, a follow up ticket should be created with the team which owns the code in question to rectify the problem. 

## Acceptance Criteria
- [ ] The change(s) which are responsible for the slowdown have been identified.
- [ ] A follow-up ticket is created with the team that owns the changes, to fix the issue

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`

**Comment by ElijahLynn** [comment]
`git bisect` FTW (to start with).

**Comment by indytechcook** [comment]
I've found a few things that I'll write up today.

**Comment by indytechcook** [comment]
To analyze deeper into the build results, I created https://github.com/department-of-veterans-affairs/cms-build-parse-utility to change the timing out put from the build into a CSV which can easily be imported into a spreadsheet.

Then I created https://docs.google.com/spreadsheets/d/1ZFlBQA2faAnCci5VjBozicqt0PR9w4vboviDnBiW_UM/edit#gid=1891384104 to analyze which steps are causing the most difference.  Due to the logs being pursed after 30 days, I wasn't able to get anything before 1/3.  What I found is that most steps were actually slightly slower on 1/3, the `Get Drupal content`  step showed a change of just over 3 minutes.  

Next steps are to check look at the code in that step which changed and profile it.

**Comment by indytechcook** [comment]
Here is the diff between releases: https://github.com/department-of-veterans-affairs/content-build/compare/v0.0.1738...v0.0.2166

Since the slowness occurs in the `Get Drupal content` step, we need to look at the code under the `src/site/stages/build/drupal` folder as this folder contains all of the code for this step.

**Comment by indytechcook** [comment]
Queries to profile. I'll edit this comment with updates

* nodeHealthCareRegionPage.graphql.js
* nodeCampaignLandingPage.graphql.js
* nodeEvent.graphql.js (with and without breadcrumbs)
* nodeEventListing.graphql.js
* nodeOffice.graphql.js

**Comment by indytechcook** [comment]
I was unable to get Blackfire working in the time I had available to be able to profile the queries but looking at  the diffs, A large number of fields were added to the `nodeOffice`, `nodeEvent`, and `nodeEventListing` queries.  The office and evnet listing queries catch my eye because lot of fields were added to pulling in the event entity which is providing as a listing.  This mean the new fields are added to every recored in the listing and most likely, these new fields are not used.
