### ISSUE TITLE
Spike: Research FE tools for building design system components

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#7808]
## Description
The wireframes for our product are composed 100% from components within the [VA Design System](design.va.gov). The design teams created a Sketch library to make their work within the system more efficient. On the engineering side, we want to find out what technical tools or libraries already exist in the ecosystem to make our front-end development work more efficient.

Here are some [wireframes for what we are building](https://www.sketch.com/s/fe67a951-84d1-4a61-bd7c-e13ab686ac5c).  A good model to explore/compare/contrast might be the [Facility Locator](https://www.va.gov/find-locations) app.

Per Dave: Storybook may have code snippets that help, but be wary of "experimental design" section.

### Acceptance Criteria

- [ ] Understand how to build the "search" filter input within VA system
- [ ] Understand how to build the "works with these offices" (possibly "read more" component?) within VA system

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
Findings:
- It seems like the Search menu component is still [under construction](https://design.va.gov/storybook/?path=/docs/components-searchmenu--default), and even then, the current one on Storybook doesn't fulfill the wireframes' needs.
  - we don't need a dropdown toggle to open up the search field
  - we need to implement an additional filter on top of the search field 
  - we need the submit request to function in the React app and search/filter on the same page instead of appending a query to the URL (i.e. requesting a new page)
  - See [ticket 7878](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7878) for implementation ticket

-  See [ticket 8191](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8191) for Additional Information component implementation
