### ISSUE TITLE
Content build updates for Drupal api user/password

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7965]
## User Story or Problem Statement

Drupal user **api** should be disabled per security disclosures linked in related issue #6973. 

Target date to disable Drupal api current user is March 1, 2022. Prior to disabling the user, there are necessary updates to the content build to ensure that content release does not break and FE engineers can still work locally with no issue.

## Acceptance Criteria

- [x] Content build should use new credentials (for tugboat, Prod)
- [x] FE engineers should be able to specify username in content build CLI command
  - [x] Not just to specify credentials, but an easy way to set and forget credentials and just use `yarn build`

## Implementation

A note regarding how `content-build` pulls in drupal credentials.  There is an order of overriding the connection information.

This is a list of an order of priority.  The higher items are priority over the lower:

1. Arguments to the CLI
  * `drupal-address`
  * `drupal-user`
  * `drupal-password`
2. [Constants](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/constants/drupals.js#L17 )(only prod one is used)

In the [GHA](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L314), the `DRUPAL_ADDRESS` is provided via a in the[ `set-env` step](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L100) which is [hard coded here](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L139).  The user name and password are pulled from the [constants](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/constants/drupals.js#L17 )

The quick way to have the content build repo use the new user/password is to update the `set-env` step.
* Add a step to get the Drupal auth info from param store similar to [this](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L47).
* In the new step, export the variable to `DRUPAL_USER` and `DRUPAL_PASSWORD`
* Update the[ build command](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L314) to:
```
yarn build --buildtype=${{ needs.set-env.outputs.BUILDTYPE }} --asset-source=local --drupal-address=${{ needs.set-env.outputs.DRUPAL_ADDRESS }} --drupal-user=${{ needs.set-env.outputs.DRUPAL_USER }} --drupal-password=${{ needs.set-env.outputs.DRUPAL_PASSWORD }}--pull-drupal --drupal-max-parallel-requests=15 --no-drupal-proxy --verbose | tee build-output.txt
```

Here are a few other suggestions which aren't required to change the build user/password but are important to address DX.

When the api user is disabled, there will most likely be a users who haven't updated their locals.  The Drupal connection information shouldn't be pulled from a constants file at all.  It should either be pulled in via cli argument or env arguments.  Information directing users to `#cms-support` to get a user if they don't have one one should be included in an error message (along with what env variables and/or cli arguments should be used.  Also, the default URL should be the tugboat url, not prod.

**Comment by olivereri** [comment]
https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/constants/drupals.js#L17

**Comment by olivereri** [comment]
## DDev / Tugboat

Tugboat uses constants/drupal.js when running the va:gov:webuild against itself to build the static site. `api` user is being disabled so the constants for staging and dev should be updated to `content_build_api`. This should also cover `ddev`.

## Front-end Engies

An easy way to set and forget per engineer Drupal user in environment variables instead of defaulting to Prod constants in constatns/drupal.js

## Production Content-build/release

Update set-env to pull creds from Parameter Store then modify the `yarn-build` command to use `--drupal-user` and `drupal-password`

**Comment by cweagans** [comment]
I think it's just that we shouldn't hardcode the credentials in any JS files. So this could all go away: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/constants/drupals.js#L3-L21 and be replaced with something that pulls the creds from `process.env` or something. It'll be an extra setup step for frontend devs (they'll have to get the credentials from somewhere), but I think that's pretty unavoidable.

**Comment by olivereri** [comment]
## Error handling for Drupal connection information

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/58e36251-2c66-4e7f-8b0a-95c956a3cd88)

**Comment by mchelen-gov** [comment]
Ok so to summarize:
- Drupal user/pass is set to default value using `.env.example` and pointed at Tugboat instance
- Docs for running `content-build` up and running are here: https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html#Settingupyourlocalfrontendenvironment-content-build
- Docs for connecting to prod Drupal are here: https://github.com/department-of-veterans-affairs/content-build#building-static-content

Questions:
- Are the default credentials `.env.example` shared by GHA content build or only other local developers?

Suggestions:
- Include a link from [getting started](https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html#Settingupyourlocalfrontendenvironment-content-build) to [connecting to prod](https://github.com/department-of-veterans-affairs/content-build#building-static-content)
- Use either a GH issue template or CMS helpdesk for Drupal user/pass instead of directing users to a slack channel
