### ISSUE TITLE
Developer login spacing issues

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8185]
The developer login page has some spacing issues, especially when there are site alerts, error alerts, and announcement alerts in play.

ACs
- [x] Updated design recs + feasibility review
- [ ] Implementation

**Comment by tjheffner** [comment]
this may be a non-issue now that the announcement block is gone off the homepage

**Comment by EWashb** [comment]
@tjheffner you think we can just close this?

**Comment by tjheffner** [comment]
@EWashb @rachel-kauff let's repurpose this ticket to remove the block & commit that config... i know Rachel disabled it previously, but it is currently re-appearing every time prod is redeployed, due to how block config is managed between environments

<img width="718" alt="Screen Shot 2022-04-08 at 8 54 26 AM" src="https://user-images.githubusercontent.com/11279744/162478630-1d4ec511-e598-4726-a2c5-4ae8d1e1e4dc.png">

**Comment by EWashb** [comment]
Thanks @tjheffner I'll remove the site alert as a blocker for this to free it up for next sprint. Let me know if I interpreted your comment incorrectly, though.

**Comment by EWashb** [comment]
I'll be closing this issue since the login spacing has been fixed, but the other concerns about the block config are in this new ticket #8719

**Comment by EWashb** [comment]
lynn closed #8334 which fixed the spacing issues
