### ISSUE TITLE
[SPIKE] Investigate design system tooling for the CMS

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8187]
To properly consume & maintain the figma design system in code, we need to set up some sort of component library that can be used by drupal (and potentially other services too). Investigate how this would work in our repo + infrastructure.

ACs:
- [x] Investigate potential tooling solutions (Pattern Lab, Storybook, etc..)
- [x] Chosen solution builds locally without errors & can be reached for local dev
- [x] (stretch) Work with rest of sitewide/platform team to understand how we can host for tugboat/other environments
- [ ] Components defined in solution can be imported in Drupal templates without errors
- [ ] Base design system tokens are visible in tooling

**Comment by tjheffner** [comment]
initial thought: pattern lab

- the php version of pattern lab (what i have used before for drupal 8 builds) is unmaintained
- the node version of pattern is missing key support for functionality provided by composer plugins that made drupal integration simple

looked at storybook next. there's a framework out there called wingsuit which is storybook + twig, (and based on a previous PL-based framework I built at a past job, called Particle), but too opinionated for our existing drupal theme. would be a solution if starting from scratch. 

I think the path forward here is to roll our own storybook + twig integration. Storybook seems like a safe/the correct choice due to its existing use in the VA ecosystem. Some work required to roll our own, but makes the most sense for our situation.

Using Storybook may potentially make it easier for us to integrate react components on the CMS side in the future, if we ever decide to go that route.
