### ISSUE TITLE
Add Search + Popular links block (desk + mobile; non-functional search)

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-cms#8361]
## Description
For [Step 3 of Home page iteration](https://www.sketch.com/s/58c718b6-196f-4b6a-a433-fb2a65d7a4d2/a/dlP7YYL), we will be replacing top tasks hub links with a condensed list of links, along with a Search input (frontend only). 

- We can reuse some styles of `.hub-links-container` in `home.drupal.liquid` 
- Search functionality will be placed into another ticket
- How these two sections stack on mobile is TBD
  - Edit 3/17/2022: Per RT, Search will stack above Popular

## Acceptance Criteria
- [ ] Responsive breakpoints (ie desktop & mobile)
- [ ] Entering search term takes the user to production [Search Results page](https://www.va.gov/search/?query=test&t=false).
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@allisonlu, note that I'm updating this issue to include basic search functionality, but **not** type-ahead. (That is a separate issue.)

**Comment by jilladams** [comment]
Pulled in mid-Sprint 56 from stretch goals.

**Comment by jilladams** [comment]
This section had some design concerns over how the gray / white blocks align with the column grid. Wes & I reviewed with Ryan Thurlwell and Dave today, (more notes in [homepage design review Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1650408594492/7245d261b15a8a1efc05c2a47e08d6f96cd61871?sender=u252e7152800e3981889d1910)), and takeaways are: 
* The 12 column layout doesn't map 1:1 with Sketch column overlay & gutters, so we can feel free to follow the column grids in code. 
* RyanT did create the Search box slightly wider than 50% in order to avoid having the gray / white break align exactly with the right side of the Blog image, which creates a weird 4 quadrant look. Current width / alignment of those sections is not a firm decision, so we can tweak this to align or not align the Search section / blog image break, as needed.

**Comment by allisonlu** [comment]
PR here: https://github.com/department-of-veterans-affairs/content-build/pull/1089

Since this is the first iteration of these Homepage changes, we will focus on refining pixels and writing tests at a later time (probably after usability testing). We can address this in a new ticket.

**Comment by allisonlu** [comment]
PR `content-build`: https://github.com/department-of-veterans-affairs/content-build/pull/1089
PR on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/21008

Both pending review approvals to be merged into feature branch.

**Comment by allisonlu** [comment]
Both PRs finally merged!
