### ISSUE TITLE
Spike: Message stack modules in test environment

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8721]
## Hypothesis

Message Subscribe out of the box module from drupal will allow CMS users to receive a variety of messages without implementing a large amount of technical debt. 

## ACs
- [x] Message ~Subscribe~ Stack module is stood up in test
- [x] Tech feasibility is determined
- [ ] Design constraints are determined for UX hand off
- [ ] New design ticket is made with tech feasibility outlined

**Comment by EWashb** [comment]
@swirtSJW let me know if I missed anything here. I think I captured what all needs to happen.

**Comment by swirtSJW** [comment]
## Findings

1. The message stack does very little out of the box.
2. There are good example submodules that show how to 
   - create messages around events 
   - How to subscribe multiple users to specific events (example, all editors in a VAMC system are subscribed to upstream data changes)
 3.  Can use queue out of the box.
 4. Notifications can be templated and templates are content with tokens.
 5. [Message notification center](https://www.drupal.org/project/mnc), an ideal module for our use, is not released in D8 yet. though it does have a 2.0 dev branch in progress that we may be able to help along.
 6. Message notify only has an email plugin at this time.  However I don't think it would be difficult to create a slack notifier.  The limitation at the moment is that it would be channel based rather than being able to notify a specific user.

**Comment by swirtSJW** [comment]
I don't think we are even close to a UX handoff or design constraints.  I have to get some notifications created and and a subscription. 
 I think creating a POC around VA form flagging notification.  Why forms?
- we need it
- it is only one content type
- it can be built using the existing VA form flagging.

**Comment by EWashb** [comment]
I like the forms idea @swirtSJW. Should I create an issue for that or do you want to work off of this ticket? My plan is to either mention this ticket (or the new one?) on the next sprint plan.

**Comment by swirtSJW** [comment]
> I like the forms idea @swirtSJW. Should I create an issue for that or do you want to work off of this ticket? My plan is to either mention this ticket (or the new one?) on the next sprint plan.
I'll work off this ticket.

**Comment by swirtSJW** [comment]
Rudimentary POC AC's
- [ ] when a VA form is flagged as new,  a notification is created.
- [ ] stretch: The notification is sent to Slack va  forms channel

**Comment by swirtSJW** [comment]
i have the basics working
When a form detail page is added, an email notification is generated.
![image](https://user-images.githubusercontent.com/5752113/164595728-8d0f96d4-b8ec-4069-abbc-d2dd3070d357.png)

Some limitations to playing around with this.
* Locally the mail is set to appear in mailhog. (no mailhog on tugboat)
* Our database sanitization process wipes all user email addresses.  
* Email templates are content, not config,  so every time tugboat rebuilds, the  templates need to be recreated.
* I haven't wired up tokens yet.

**Comment by swirtSJW** [comment]
I am going to call this done.  I've answered my technical concerns.

- We can do separate email messaging.  
- We can notify slack with out  much extra code
- We can create Views or Dashboards.
- We can grant some control over subscribing and preferences.
- 
I have enough to knowledge not to create  individual issues for epics. 

I am recommending an epic of epics   
- MegaEpic: Notifications
   - Epic: VAForm Notifications
   - Epic: Facility API related Notifications
   - Epic: ...
