### ISSUE TITLE
Public Websites Sprint 56

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8723]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

</details>

## Transition items

- [ ] Learn Redirects (with Jay from Facilities)

## #7158 Support Cerner

- [ ] #8686 🥅 (56)
- [ ] #7860 (56, but deadline is 57)
- [ ] #8687 (by end of 59, in time for VA Roseburg June 12)

### #8340 Iterate VA.gov changes for demo/testing in publicly accessible environment

- [x] #8668
- [x] #8360 
- [x] #8358 

- [ ] Onboard Cindy and Michelle

## Events V2

As of today on Facilities but will likely come back here

**Comment by jilladams** [comment]
Sprint 56 planning notes: 

**In sprint priorities:**
Board is updated to reflect, but anecdotally:
1. #8686 
2. Sprint 55 Homepage carry-over
3. Homepage Stretch / Next sprint items (except #8359)
4. Ramp up on redirects

**Future notes**
- Events V2 may come back to public websites, due to lack of capacity on Facilities team.
- Global header / footer has queued work
- Forms: have a Q2 ticket for SPIKE to get ramped up on product / how it works. We still have Lighthouse support, and Steve can/will help with triage if issues arise prior to SPIKE.
- Deprecating IE 11 upcoming - banner presented to users. Pattern exists, banner component exists, used for announcing outages, etc. Can repurpose for this. Will be included in global header on VA.gov, and injected into team / legacy sites.
