### ISSUE TITLE
Discovery: how to use injected header for IE11 notification beyond the modernized experience

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8852]
## Description
As a Veteran, I need to be told that I'm using a browser that doesn't support the best experience so that I can change browser.

### Implementation
The injected header seems to be the place to look, as it is present across all va.gov properties that this story applies to.
Is there something that comes along with the injected header that we can leverage? E.g. the [System Maintenance Banner](https://design.va.gov/storybook/?path=/docs/components-banners-maintenancebanner--before-maintenance). Or, do we have to build something new?

Example page with injected header: [VBA home page](https://www.benefits.va.gov/benefits/appeals.asp)

What's the "menu" of components available on injected-header pages?

## Acceptance Criteria
- [x] Recommendation for path forward
- [x] Issues/stories to complete this epic - #9075

## Recommeded Solution
- Conditionally run logic to serve the purpose of informing the user they should upgrade to a modern browser (not IE11 or older). The following would be included within this logic:
  - Use JavaScript to create, append & load the generated web-components JS & CSS files, which are stored in S3, into the HEAD of the HTML Document. This will provide support for the web component which will be used to display the desired information to the user.
  - Use JavaScript to create, append & load the [Warning Alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--warning) elements into the HTML Document Body Header UI.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8852?planning-poker) with ZenHub @ryguyk @allisonlu @kind-claudio

**Comment by kind-claudio** [comment]
**WIP**

There are four scenarios for which need consideration - mobile layout header & tablet/desktop "legacy" header on both the legacy pages, as well as the modernized pages.

Mobile Layout - technical implementation: modern header widget
- Related code for the solution:
  - Project `content-build`: "Includes" consisting of `src/site/includes/header.html` & `src/site/includes/top-nav.html`
    - Generated files: `/generated/web-components.entry.js` & `/generated/web-components.entry.css`
- Modern solution:
  - Incorporate a [Warning Alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--warning) from the design system component library.
    - The alert component source code will be added to `Header/index.js`
  - A JS script is needed in order to handle IE browser detection which will activate the alert.
    - Actual JS solution TBD - should this determination be part of the follow up ticket?
- Legacy solution:
  - This will be the same as the modern solution

Tablet/Desktop Layout
- Related code for the solution:
  - "Includes" consisting of `src/site/includes/header.html` & `src/site/includes/top-nav.html`
  - Generated files: `/generated/web-components.entry.js` & `/generated/web-components.entry.css`
- Modern solution:
  - Incorporate a [Warning Alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--warning) from the design system component library.
    - The alert component source code will be copy/pasted into the `top-nav.html`
- Legacy solution:
  - This will be the same as the modern solution, with one exception - the web-components.entry files need to be added into the `<head />` of the legacy pages. How this is done is TBD.

**Comment by kind-claudio** [comment]
Updated the description to include the recommended solution.

**Comment by jilladams** [comment]
Plan is documented. Closing.
