### ISSUE TITLE
Postmortem: Investigate Root Cause of Content-release outage on April 25th & Mitigate Problem

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8889]
## Describe the defect
Content-release Broken Links began failing Friday 2022-04-22 breaching 10 broken links on 2022-04-25 Monday morning PT.

## To Reproduce
Slimmed down GraphQL query run locally on a new `event` node.

## Acceptance Criteria
- [x] Content-release succeeds with no broken links on new `event` nodes.
- [X] Post-mortem documented.
  - [2022-04-25 - Content-Build Outage Due to Broken Links](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2022-04-25-broken-links-content-build-outage.md)

 ## Additional context
* https://dsva.slack.com/archives/C030F5WV2TF/p1650902245864989
* https://dsva.slack.com/archives/CDHBKAL9W/p1650903138203809

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by mchelen-gov** [comment]
This is a good write up. There are a couple things that would be helpful to add:
> What went well
> Alerts and monitoring functioned well to gain awareness of failed content release.
Does this refer to Slack broken link notification? What other alerting and monitoring was utilized?

> Logging and Tracing fell short failing help reveal the issue
What options exist to improve logging and tracing for problems like this?

> Reproducible with event nodes by running a customized graphql query. 
Would unit, E2E, or synthetic monitoring would prevent future regressions?

**Comment by timcosgrove** [comment]
> > Alerts and monitoring functioned well to gain awareness of failed content release.

> Does this refer to Slack broken link notification? What other alerting and monitoring was utilized?

Broken link notifications revealed the symptoms. It would be fairly difficult to test or monitor for the core problem; see below.

> > Logging and Tracing fell short failing help reveal the issue

> What options exist to improve logging and tracing for problems like this?

> > Reproducible with event nodes by running a customized graphql query.

> Would unit, E2E, or synthetic monitoring would prevent future regressions?

It would be difficult to set up monitoring for the situation that occurred. The situation was: a custom query backend was put into place for node entity queries in GraphQL. I believe the original code was an attempt to mitigate the long GraphQL times VA.gov was seeing in earlier 2021. Within days of its original implementation in 2021, it was recognized as problematic, and commented out, though not removed from the codebase.

We could in theory set up an E2E test that

* Created and published new node
* Run a GraphQL query for a listing that should contain that node
* Ensure the node is there

That would provide a test that confirms this very specific regression has not occurred. But, it is very specific, and unlikely to occur again. We can test for it, but testing for improbable situations may have low value and have a negative effect on testing time.

The root cause of the problem was really the way in which the code was commented out, when it was disabled. This is the code in its commented state: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8789/files#diff-2f178073813f91c570da0967623b56c9f89352c8cc7f9a63c0cbd25d508ccdae

A better automated solution for the core problem would be linting that disallows commenting out code in this fashion, if such linting can recognize this sort of comment.

**Comment by mchelen-gov** [comment]
@timcosgrove Ok I think I am hearing you say that automated monitoring of this issue would be difficult or overly specific to provide a good return on effort.


Please add to the Postmortem:
> Logging and Tracing fell short failing help reveal the issue
- What logging and tracing was used?
- How did it fall short?
- Action items to improve logging and tracing.

**Comment by timcosgrove** [comment]
@mchelen-gov 

I updated that sentence:

> Alerts and monitoring functioned well to gain awareness once it occured, but the root cause was not something that would surface via logging or tracing, since it was a functional error rather than a technical one.

Logging/tracing would not have revealed anything about this error. It was a functional error that would need to be caught by an E2E test. Apologies for the miscommunication in the post mortem!

**Comment by mchelen-gov** [comment]
Ok got it, nothing further from my end.
