### ISSUE TITLE
Facility COVID status: work through details of any FE changes

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#8948]
Current state:
![image](https://user-images.githubusercontent.com/60702623/166825121-7a14b041-bcda-4666-be44-e68d236298f2.png)

Pages that would need to display this
[Facility Locator search results](https://www.va.gov/find-locations/?address=washington%20dc&bounds%5B%5D%5B%5D=-77.786543&bounds%5B%5D%5B%5D=38.145037&bounds%5B%5D%5B%5D=-76.286543&bounds%5B%5D%5B%5D=39.645037&bounds%5B%5D%5B%5D%5B%5D=-77.786543&bounds%5B%5D%5B%5D%5B%5D=38.145037&bounds%5B%5D%5B%5D%5B%5D=-76.286543&bounds%5B%5D%5B%5D%5B%5D=39.645037&context=Washington%2C%20District%20of%20Columbia%2C%20United%20States&facilityType=health&latitude=38.895037&longitude=-77.036543&page=1&radius=18&serviceType&bounds%5B%5D=-77.786543&bounds%5B%5D=38.145037&bounds%5B%5D=-76.286543&bounds%5B%5D=39.645037)
[VAMC facility pages](https://www.va.gov/washington-dc-health-care/locations/southern-prince-georges-county-va-clinic/)
[VAMC location pages](https://www.va.gov/washington-dc-health-care/locations/)
[VAMC situation update pages](https://www.va.gov/washington-dc-health-care/operating-status/)
~[Vet Center main pages](https://www.va.gov/washington-dc-vet-center/)~
~[Vet Center location pages](https://www.va.gov/washington-dc-vet-center/locations/)~

The nature of the work .. to be made into separate tickets
- [x] #8981
- [x] #8982
- [x] #8983
- [x] #8984
- [x] #8985
- [x] #8986

**Comment by cmaeng** [comment]
@DanielleThierryUSDSVA is handling content for this (label and details).

**Comment by mmiddaugh** [comment]
### Current flow for operating status info 
<details>
<summary> screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/167224369-f5eaa9ad-10e6-4a85-a03f-6a994042bf7e.png)
![image](https://user-images.githubusercontent.com/55411834/167224410-3febdc64-b85e-44c5-96ab-ecd37d299310.png)

</details>
- When Veterans land on [a facility's page](https://www.va.gov/charleston-health-care/locations/charleston-va-clinic/), only the operating status is visible. (same is true for system level and location pages)
- To see the details, Veterans must click the alert and view the information on the Situation update/operating status page 
- Starting at the Facility Locator adds an extra click on the facility's name to get to the facility page

---

<details>
<summary> Vet Centers use an expandable alert to allow info to be viewed inline without going to a new page (in the experimental design system) </summary>
![image](https://user-images.githubusercontent.com/55411834/167224465-21d1f161-926b-4e72-992e-a07e06f59915.png)

</details>

---

## Decisions
- [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1651870712041179)
- Use expandable alert on VAMC pages to allow Veterans to view the information they need quickly
- Include COVID-specific alert information on the Situation update/operating status page so that Veterans arriving on that page are able to see the info. 
- Combine COVID-specific status info in the same list with any other operating status information so all info for a given facility is available in one place and to prevent important info from being missed
- Facility Locator functionality (linking to relevant facility page) should be maintained so they can have easy access to specific facility info rather than be directed to general info page
