### ISSUE TITLE
BE updates to Content Guidance

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8993]
## Background ##

As guidance is provided to editors for providing COVID-19 safety updates for facilities, the operating status UI should explicitly reflect this.

Draft design:
![Screen Shot 2022-05-06 at 2 12 11 PM](https://user-images.githubusercontent.com/90111970/167202845-44cd3c69-8aab-48fd-b38e-2941563d8be2.png)

## COVID-19 Status ##

Updated guidance needs to be reflected in the UI. The guidance from the Sitewide Content team will detail:
- "low, medium, high" levels
- what those levels mean

Draft text for Sitewide Content consideration:

**Label** 
COVID-19 safety guidelines

**Field help text**
Help Veterans understand COVID-19 protocols at this facility. This will show up on the facility's location page as well as on the Operating Status page.

**field label** 
COVID-19 Status

**help text**
Select the status that most closely matches your facility’s protocols. Learn more about COVID statuses.

## Operating Status ##

There will be changes to how editors are using this section. Current understanding is that this section is not to be used for COVID and mask guidelines.  Updates to the field group levels and help text might be a short-term solution but will need guidance from the Sitewide Content team.

Draft text for Sitewide Content consideration:

**Label**
Operating Status

**draft help text**
Use this for all other kinds of situations at might impact your facility’s operations. Information you edit here will show up on the facility's location page as well as on the Operating Status page.

**Draft status help text** 
Use this status for non-COVID-19 related situations, such as weather events.

**Details** 
Add further details about how the status will impact visitors to the facility. Don’t include any information about masks, screening, or visitor policies due to COVID-19. This will be communicated to site visitors through the COVID-19 status.

## AC ##
- [ ] COVID status labels are accurate per Sitewide Content guidelines
- [ ] COVID status help text accurately reflect accurate information.
- [ ] Operating status labels are accurate per Sitewide Content guidelines
- [ ] Operating status help texts are accurate per Sitewide Content guidelines
- [ ] KB article for COVID status drafted
- [ ] KB article for Operating Status is updated to include updated guidance for the Facility Notice section
- [ ] CM is considered and updated on changes to come

**Comment by rachel-kauff** [comment]
**Affected KB articles**
- How to edit a VAMC facility operating status  (6869)
   - /help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status
   - Update status guidance to make clear that editors should NOT use op status to communicate about COVID impacts.
-About VAMC alerts and operating statuses (6868)
   - /help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses
   - Update status guidance to make clear that editors should NOT use op status to communicate about COVID impacts.
 - [NEW] How to update VAMC facility COVID-19 guidelines
    - [link to come]

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rachel-kauff @EWashb. Here are some thoughts as we continue to firm up language. I'm thinking that we leave "low, medium, high" as just that for now in the labels until that's totally settled. That way, we don't risk it being incorrect and we can iterate. For the rest, take or leave what you see fit here.

Note that the posters seem to be using "VA health protection levels," but we are going to talk with the working group about that because we don't think it's necessarily the most clear/helpful way to go here.

## COVID-19 safety guidelines

Use these levels to help Veterans understand the current COVID-19 safety guidelines at your facility. The preset guidelines will appear on your facility’s location and operating status pages.

### COVID-19 safety guideline levels
Select the level that matches your facility’s current level. [link to KB article] Learn more about COVID-19 safety guideline levels
Low 
Medium
High 

## Operating status
Use this status for weather or other events that impact your facility's operations. Don’t use this for COVID-19-related information. This status will display on the facility’s location page and operating status page. 

### Status
Select the status that reflects your facility’s current operations.

### Details
Add relevant details about how this status will impact Veterans and visitors. Don’t include mask, screening, visitor, or care policies related to COVID-19. The COVID-19 safety guidelines will provide this information.

**Comment by rachel-kauff** [comment]
Thank you Danielle! I'll update the prototype with the new language, and we can keep adapting if more changes/decisions come through.

**Comment by kevwalsh** [comment]
Implemented in #8949 / PR #8999

**Comment by rachel-kauff** [comment]
@DanielleThierryUSDSVA I think we'd discussed having VHA Digital Media and the COVID future working group give the final approval for the names of the statues and the editorial guidelines before we launch this.

Is that something Sitewide Content is going to do? I want to make sure we get that thumbs up before this goes out...

**Comment by rachel-kauff** [comment]
Yes, I'll update the prototypes with the latest shortly, and post in this issue.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rachel-kauff. Latest content here.

[label] **COVID-19 health protection guidelines: Levels low**

- Everyone must wear a mask.
- We welcome visitors. 
- If you've had any COVID-19 symptoms in the past 48 hours, call first unless you need care now. [Check COVID-19 symptoms on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html)

Check each Monday for the latest guidelines for each facility you plan to go to.

[label] **COVID-19 health protection guidelines: Levels medium**

- Everyone must wear a mask.
- We welcome care partners. Ask your care team about additional visitors.
- If you have COVID-19 symptoms, call first unless you need care now. [Check COVID-19 symptoms on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html)

Check each Monday for the latest guidelines for each facility you plan to go to.
	
[label] **COVID-19 health protection guidelines: Levels high**
- Everyone must wear a mask and practice physical distancing.
- Be prepared to complete COVID-19 symptom screening.
- Visitors limited. Ask your care team who can visit.
- Ask your team about phone or video appointments.

Check each Monday for the latest guidelines for each facility you plan to go to.

**Comment by rachel-kauff** [comment]
Thanks @DanielleThierryUSDSVA  I'm about to post what we've got for the back end / editorial experience for VAMC editors.

**Comment by rachel-kauff** [comment]
@swirtSJW Posting screenshots here with the updated help text and labels. Will post Copypasteable text right after.

With radio button label work:

<img width="775" alt="Screen Shot 2022-05-10 at 2 13 29 PM" src="https://user-images.githubusercontent.com/41017988/167723067-0cd839e6-631e-4

Without radio butto
<img width="775" alt="Screen Shot 2022-05-10 at 2 16 00 PM" src="https://user-images.githubusercontent.com/41017988/167723206-47ea0eaa-fc75-4405-9482-3b42308ac2e3.png">
n work:



Operating status fields:
<img width="775" alt="Screen Shot 2022-05-10 at 2 15 15 PM" src="https://user-images.githubusercontent.com/41017988/167723105-a514187b-cad8-4f04-be59-e24f16c7aede.png">
aae-85e8-81314becbc2d.png">

**Comment by DanielleThierryUSDSVA** [comment]
Looks great - thank you, @rachel-kauff!

**Comment by rachel-kauff** [comment]
@swirtSJW 

**Field group label**
COVID-19 health protection guidelines

**Field group help text**
Use these levels to help Veterans understand the current COVID-19 health protection guidelines at your facility. The preset guidelines will appear on your facility’s location and operating status pages.

**Field label**
COVID-19 status *

**Field help text**
Select the level set by your facility’s leadership. Learn more about COVID-19 safety guidelines (opens in a new window)

**Radio button labels**
- Low 
- Medium
- High

**Field group label**
Operating status

**Field group help text**
Use this status for weather or other events that impact your facility's operations. Don’t use this for COVID-19-related information. This status will display on the facility’s location page and operating status page.

**Field label**
Status

**Field help text**
Select the status that reflects your facility’s current operations.

Radio buttons (no change)
- Normal services and hours
- Facility notice
- Limited services and hours
- Facility closed

**Field label**
Details

**Field help text**
Add relevant details about how this status will impact Veterans and visitors. Don’t include any information about masks, screening, or visitor policies due to COVID-19. This information is now covered in the COVID-19 health protection guidelines.

**Comment by swirtSJW** [comment]
I just updated this text in this pr https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9050

**Comment by cjterdi** [comment]
Latest content for the F
![components](https://user-images.githubusercontent.com/16213503/167898390-bf5c1317-2ae9-4921-8bd0-6e427aab8b63.png)
E

**Comment by rachel-kauff** [comment]
This is shipped, so probably can be closed!
