### ISSUE TITLE
Loosen coding standards requirements

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9019]
## Description

In working on #8108, I ran into a number of minor annoyances with our coding standards enforcement. I'd like to propose the following changes:

* Do not require a class docblock. Right now, the majority of our class docblocks are duplicative with the actual class names and don't add any value. e.g. `class ThingDoer` will have a class docblock along the lines of `Does the thing` or `The Thing Doer service`.
* Do not require constructor param descriptions. Same kind of problem as the class docblocks: if a constructor is asking for a `StateInterface`, the param description is usually something along the lines of `The state service`
* 80 character line length limit is only a warning, so it shouldn't fail coding standards checks. Since none of us develop on terminals that only have 80 characters of screen width, I think we should also loosen this to 120 characters or so (and still not fail coding standards checks) but I don't feel strongly about making that change.
* Let's get rid of the precommit hook. It's extremely frustrating to make a commit and have `git` try to start `ddev` so that it can run the coding standards checks. It's also frustrating to have it fail the commit when you're just trying to get things done - fixing coding standards is not something that I want to be derailed by if I've got some momentum, especially since it can be fixed after the fact. We squash all of our commits anyway, so it really doesn't matter if _each_ commit complies with our coding standards.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
```
Let's get rid of the precommit hook. It's extremely frustrating to make a commit and have git try to start ddev so that it can run the coding standards checks. It's also frustrating to have it fail the commit when you're just trying to get things done - fixing coding standards is not something that I want to be derailed by if I've got some momentum, especially since it can be fixed after the fact. We squash all of our commits anyway, so it really doesn't matter if each commit complies with our coding standards.
```

Because being agile we routinely cherry pick commits from other people's work.     I'd like to have confidence that what we are cherry picking is solid code and not full of phpcs issues that someone was going to clean up later.   We also routinely pick up where someone else left off.  Fixing coding standards in someone else's work is not something that I ever want to be derailed by, whether I have momentum or not.

When we squash and merge the commit messages are all combined.   I'd rather not have a bunch of  "fixing code sniffer BS" commit messages strewn throughout the extended commit message.  

```
Right now, the majority of our class docblocks are duplicative with the actual ~class~ method? names
```
I think you are right about this many of the times.... Setting a docblock on a well named getter or setter is kind of silly but on the times where we are not, the docblock is useful as it can and should tell the business need of the method. 
I  have issues with one set of standards for drupal contrib (and the patches we make), and one set for our custom work.    I also think from a program point of view it is more clear and meaningful to say "We follow drupal cs standards" than to say "we pick and choose our own set of rules like pirates".  I don't want to have to go through code review hand picking which method needs a docblock and which doesn't.

**Comment by cweagans** [comment]
>  Because being agile we routinely cherry pick commits from other people's work. I'd like to have confidence that what we are cherry picking is solid code and not full of phpcs issues that someone was going to clean up later. We also routinely pick up where someone else left off. Fixing coding standards in someone else's work is not something that I ever want to be derailed by, whether I have momentum or not.

How often does that happen compared to a normal commit that somebody authored directly? I can't imagine that this happens often enough to justify a precommit hook on its own.

I would also suggest that much of the work involved in fixing coding standards issues is self-imposed and is mainly due to the the extent of the Drupal coding standards. I don't think we should do this, but as a thought experiment: if we _only_ had the rules that were defined in `.editorconfig` and maybe one check that looks for `\Drupal` in any PHP file that doesn't end in `.module`, would our codebase be materially different?

> I have issues with one set of standards for drupal contrib (and the patches we make), and one set for our custom work.

I don't think we should have separate standards. We could leave the class docblock and param description checks in place, turn it into a warning, and not fail PRs on warnings. Still the same set of rules - it's just a question of severity and what should/shouldn't gate a PR merge.

>  I don't want to have to go through code review hand picking which method needs a docblock and which doesn't.

I don't want to do that either, but we shouldn't do that anyway. Give some basic guidelines and then leave it to the developers' discretion. If it's unclear to somebody down the road, `git blame` exists. It shouldn't be too hard to just ask the person who wrote it and then add a comment.
