### ISSUE TITLE
Redirect chatbot link to the main coronavirus FAQs page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#9066]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/coronavirus-chatbot/ | https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@davidconlon I have documentation ready to discuss and have been working to get that conversation on the books for a couple of weeks.  I originally hoped we could solve for this one with that discussion and then lost track of it when the convos didn't happen.

**Comment by jilladams** [comment]
Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1652372001725339  

@allisonlu  assigning to you - this should take priority over Homepage work in this sprint. Kha Huynh has been working with DevOps to plan for a deployment to prod on Mon May 16th - if you need to connect directly with him for context, please do.  Since the deadline is Monday and I'm in meetings most of today, don't want me to be a blocker, but wave a flag if you need any help coordinating / run into blockers.

Related tickets that to take a look at for context (I haven't reviewed yet): 
https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/456 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/39785

**Comment by allisonlu** [comment]
PR opened, review pending: https://github.com/department-of-veterans-affairs/devops/pull/11245

**Comment by jilladams** [comment]
Re-merged & deployed, closing.

**Comment by jilladams** [comment]
Ah, apologies -- @DanielleThierryUSDSVA ticket notes that requesting team should validate before ticket closes, so: please take a look, and feel free to reopen if you find any issues.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jill. Validated. Thank you!
