### ISSUE TITLE
Write user stories for CMS announcement block

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9123]
## Background

To provide appropriate governance for the CMS announcement block, UX should determine use cases and write user stories for the component. 

## Acceptance Criteria
- [x] Use cases are considered, especially as to how it relates to site alerts
- [x] Determine when CMS announcement block use is appropriate 
- [x] Write user stories for this component
- [x] Design system documentation

**Comment by rachel-kauff** [comment]
Drafting ideas here. Will migrate them to appropriate documentation areas (confluence) when finalized.

## User stories

"As a CMS user, I want to know about changes that affect my use of the Drupal CMS so I am not confused by changes and so I can plan my activities."

Use cases:
- New features available to me (for example, the ability to add recurring events)
- Content tasks associated with a new initiative (for example, COVID status updates)
- Changes to the interface that significantly affect my workflow or experience (for example, a new Drupal theme)

Hypothesis:
- Announcements are most effective when context-appropriate. The ability to add announcement blocks to specific content types helps get information to the right users in the right places.
- Dismissability: For some announcements, users will be able to receive the information once and not need to see it again (for example, for the new theme). For other announcements, it may be appropriate to keep the announcement up for a certain period of time so users are reminded of the situation (for example, during the two days editors had to make their first COVID updates).

**Comment by rachel-kauff** [comment]
*Draft ideas, WIP*

## Site alert vs CMS announcement block

### CMS announcements
Use when any of the following are true:
- The information needs to be context-specific (because it applies to a particular group of users or a very particular part of the interface.)
- The information isn't critical to editor' ability to access and use the essential functions of the CMS
- The information is part of a planned change to the CMS interface or workflow

**Process**
Usually CMS announcement blocks are part of a coordinated change management strategy. Be sure to check with the change management expert before proceeding.
1. Create a ticket to put the announcement block up. Identify the following:
- Where it should appear (which content type or part of the interface)
- Time period it should appear (There must be a time period. Announcement blocks should not be up indefinitely).
- Message information and related communications we can use to model the microcopy on.
- Assign the first ticket to a Sitewide CMS team UX writer or UX designer as well as a developer.
2. Create a second ticket to take the CMS announcement down. Assign a Sitewide CMS developer.

**Comment by EWashb** [comment]
This looks excellent @rachel-kauff! We could also possibly coordinate with @ContentBrewmaster to see if the use of a content block announcement could be combined with the change management template/strategy that already exists (this is not mandatory...just a thought as we are working through this)

**Comment by rachel-kauff** [comment]
Documentation in Confluence:
[Site alert](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1773338625/Site+alert)

**Comment by rachel-kauff** [comment]
Ask Lynn: will there be an ID associated with each announcement block content (related to future work on notifications framework).

**Comment by rachel-kauff** [comment]
Sent to Denise for review. Will add links to Figma and Storybook once Cindy and Tanner are ready.

**Comment by ContentBrewmaster** [comment]
I really like how you put this together @rachel-kauff. One suggestion for the change management process steps under CMS announcements:
- under #1, add bullet "Link this ticket to the associated epic."

**Comment by rachel-kauff** [comment]
Great, thanks @ContentBrewmaster . I added it as its own step:

> 2. Link the first ticket to the associated change management epic.

**Comment by ContentBrewmaster** [comment]
@rachel-kauff Kev and I decided not to create a child epic for change management, but to attach all tickets to the parent epic. I suggest adjusting the new language accordingly, unless you see an issue with this approach.

**Comment by EWashb** [comment]
This seems to be complete. Am I right @rachel-kauff?

**Comment by rachel-kauff** [comment]
@EWashb It is!

**Comment by cmaeng** [comment]
@rachel-kauff could you throw a rough point estimation on this for velocity tracking purposes please?

**Comment by rachel-kauff** [comment]
@cmaeng done.
