### ISSUE TITLE
Discovery: Mobile header and associated tech debt (if present)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9139]
## Description

At some point a mobile-only header was implemented. [Initiative brief for that work](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5e0f4d3c470ed2f32290ff1a6e2cc7c2c97f7847/products/public-websites/home-page/new-mobile-header/Initiative%20Briefing.md). 

The PW team is experiencing this separate header implementation as tech debt as we look at how injected headers work on legacy sites. 

This issue covers discovery to answer questions around how this approach and potential tech debt impacts iterations that need to be done across mobile and desktop, modernized and legacy (injected) contexts. Answer question such as:
- How stable is the current implementation?
- How separate are the mobile and desktop headers, code-wise? How much more unified could they be?
- What is the path to consolidating the mobile header back into the modernized/desktop header?

## Additional context
* Mobile header implementation - https://github.com/department-of-veterans-affairs/va.gov-team/issues/31145
* Mobile header docs: https://github.com/department-of-veterans-affairs/va.gov-team/tree/5e0f4d3c470ed2f32290ff1a6e2cc7c2c97f7847/products/public-websites/home-page/new-mobile-header
* Includes a flipper for `show_header_v2` - https://github.com/department-of-veterans-affairs/vets-api/pull/8198

## Time box

Limit analysis to 2 days (ish), return to team with insights.

## Acceptance Criteria
- [ ] Document how the headers are implemented
- [ ] Answer rough questions above as possible

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
## content-build

### files to note

- `header.html`
  - contains mobile header widget from `vets-website`
  - also includes conditional to display tablet/desktop layout (from `top-nav.html`)

- `top-nav.html`
  - only displays on tablet/desktop widths
  - contains VCL modal, menu navigation items, IE notification


## vets-website

### files to note

- `src/platform/site-wide/header/`
  - directory of all components in the header

- `src/platform/site-wide/mega-menu/components/MegaMenu.jsx`
  - HTML structure for mega menu
  - logic for displaying mega menu

- `src/platform/site-wide/mega-menu/containers/Main.jsx`
  - keyboard navigation functionality for megamenu
  - GA for selected nav item

- `src/applications/proxy-rewrite/proxy-rewrite-entry.jsx`
  - handles header/footer for TeamSite CMS / legacy pages

- `src/applications/proxy-rewrite/partials/header.js`
  - IE notification for legacy pages

- `src/platform/landing-pages/header-footer-data.json`
  - content for mega menu

## Conclusion
We will have to consider 4 scenarios:
1. Modern site - tablet/desktop header
1. Modern site - mobile header
1. Legacy site - tablet/desktop
1. Legacy site - mobile 

Since this is a highly visible component on the VA site and there are a lot of moving parts, we will have to approach this with care so we won't disrupt the current implementation which is stable (but not ideal). 

I think most of the code-wrangling will happen in the `content-build` repo, where we can slowly "merge" the two mobile and desktop implementations together. We can tackle the modern site first, then legacy.

**Comment by wesrowe** [comment]
@allisonlu, I'm wondering if you can put some more detail around the question:
> What is the path to consolidating the mobile header back into the modernized/desktop header?

Since our goal is to evaluate risk and effort, I think a little more detail around the _how_ would be helpful. If you were constrained by the 2-day time box, lmk and we can issue a new ticket for the follow-up analysis. (By the way, I think a visual/diagram of some sort might be helpful for discussion.)

**Comment by allisonlu** [comment]
Mural for today's discussion: https://app.mural.co/t/friendsfromthecity8869/m/friendsfromthecity8869/1659471489963/7d957a8f68132087527e6f9b769ea12753bc97a7?sender=u38c7b8ac21f6cf2c1bd04203
