### ISSUE TITLE
[SPIKE] Google analytics for next-build

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9255]
## Description

* Investigate which library to use and implement in appropriate manner
* Set up Environment variable(s) with appropriate GA property ids

## Acceptance Criteria

- [x] Determine what method to use for how components will be written to GA for next-build
- [x] Determine how to handle test logs (may need an additional sandbox environment cloning content-build)
  - [x] Determine which parameters are needed to pass

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by penny-lischer** [comment]
Test logs can be written to the VA.gov Non-Production Environment within Google Analytics.

**Comment by penny-lischer** [comment]
In order to mimic content-build Tag Manager must be used. The POC(https://github.com/department-of-veterans-affairs/next-build/pull/45) uses the react-gtm-module library which uses Google Tag Manager but allows for typescript, custom dataLayer, multiple dataLayers and additional events.
Events can be tracked by sending the same object as in content build. i.e. recordEvent({event: nav-linkslist})
By installing the Adswerve plugin  and enabling it, you will see the GA events listed in the developer console.

*Note: Each environment must have the following environment properties set:
Auth
Preview
GTM Id
