### ISSUE TITLE
Content Audit: TTY: 711

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#9276]
## Describe the request
Content audits are performed by searching the codebase and compiled site for specific terms. 
Please provide any context for the audit, and any related terms / alternate spellings, that could return content you are interested in.

* Context: We've updated our [style guide entry](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers) to show that when we list TTY numbers TTY: 711 needs to all be part of the hyperlink. Currently we have instances on our pages where only the 711 is linked. We are looking for all the references of TTY: 711 on our benefit detail and R&S pages so we can make this change. Not sure if you're able to check by whether it's already hyperlinked but if so, we would only want instances where the whole term wasn't hyperlinked.
* Terms of interest: TTY: 711
* Alternate spellings / terms: TTY 711 (no colon), 711
* Any Content types to specifically include or exclude?: Benefit detail pages, resources and support, root-level pages, benefit hub landing pages

### Implementation date
When does this request need to be complete?: We would like to start updating our pages in Sprint 76 if possible, which begins June 15. 

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

## Acceptance Criteria
[ ] - list of URLs

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@RLHecht We'll consider in sprint planning today.

**Comment by jilladams** [comment]
@EWashb I forgot to bring this up in our sync today - this issue is new  for prioritizing a content audit. Candidate for your next sprint, or holler if you need support and I can help run it. (FYI @dawnpruitt )

**Comment by EWashb** [comment]
@RLHecht we have this slated for our current sprint, however, Lynn is OOO until next week.

**Comment by msbtterswrth** [comment]
[tty711.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9020958/tty711.csv)

@RLHecht  I've exported all instances of `TTY: 711` within rich text fields (and Rich Text Limited fields). This sheet has the url and node ID to each node  you'll find them on. 

*NOTES* 
some of these are past revisions (which will be noted in the sheet). 
searching for `711` or `TTY` is difficult since other phone numbers contain `711` (or forms like VA-0711) or the letters `tty`. 

We are in the process of exposing the tool I used to create this audit to you and other content admins so that you can perform your own text-based searches on CMS content. We'll have a follow-up ticket with more information on that soon. 

Please let me know if there's anything else you're looking for in this particular audit!

**Comment by RLHecht** [comment]
Thanks for this @msbtterswrth! And very exciting that we'll be able to do our own audits for these kinds of things in the future!
