### ISSUE TITLE
Add unit tests to reusable logic - followup to IE11 Deprecation Work #9075

### ISSUE THREAD

**Issue by kind-claudio** [department-of-veterans-affairs/va.gov-cms#9408]
## Description
Followup to #9075 

### Overview
- Within `vets-website`, two logical files were added in #9075 which still need unit tests created.
- Create these unit tests.

## Acceptance Criteria
See [comment below](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9408#issuecomment-1181045231) that explains updated scope.
- [ ] Unit test created for `src/platform/site-wide/helpers/detection/is-browser.js` **EDIT: refactor code and write unit test**
- [ ] ~Unit test created for `src/platform/site-wide/hooks/events/use-on-loaded.js`~ This custom hook is scheduled to be removed and should not be used elsewhere in the meantime. Test coverage would be difficult at best, and not accurate at worst. Not worth the squeeze. Instead, adding commentary to code to not copy this implementation. Code will be removed in #9761 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kind-claudio** [comment]
I'll work on this next Friday (last day of sprint) when I'm back from PTO.

**Comment by jilladams** [comment]
Claudio has resigned, effective immediately, so this ticket will need reassigned and is not likely to close in Sprint 62.

**Comment by ryguyk** [comment]
@jilladams 

> ...not likely to close in Sprint 62.

I imagine this is supposed to say Sprint 61. I'm going to be working some overtime on this, so it should close _during_ this sprint (62), but I'm wondering if we want this included in this sprint from a paperwork perspective. Or should we mark this back to 61? Your call. I'm just flagging this up as I take inventory of things.

**Comment by ryguyk** [comment]
`isBrowserIE()` is not actually testable as written, as it doesn't take the `userAgent` as a parameter. This should be slightly refactored and then have tests written.  After refactor, QA should be redone per [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9577).

**Comment by jilladams** [comment]
(you're right, edited my earlier comment.)

**Comment by ryguyk** [comment]
The custom hook (`useOnLoaded`) is very difficult to test as written. Beyond that, its current implementation is less than ideal because it doesn't account for the case where the element is already loaded before the event listener is registered. In this case, `loaded` will forever be `false` despite the element having been loaded.

It's not immediately clear why this hook or its functionality (a check to ensure the window is loaded) is necessary. My hunch is that it's not. If it is necessary, it needs to be fixed to capture this case mentioned above. That might be easier said than done, though. The first step should be to see if it can be removed. Again, I have a strong suspicion that might be the case.

I'm not sure how I want to proceed in terms of capturing this in tickets. This ticket is becoming a bit misleading, as the two functions that it aims to test are going to be either heavily adjusted or removed altogether.   @jilladams should we close this in favor of new tickets?

**Comment by jilladams** [comment]
Per discussion today with Ryan & Wes, for clarity & @davidconlon 's visibility: 
Claudio wrote this ticket based on having written two functions for the IE11 deprecation banner that he assumed were testable. Ryan has been researching and determined that for the 2 functions in question:

1. `isBrowserIE` - is reusable, should be kept in code, and can be tested with a minor/low risk refactor to allow it to accept a parameter. Refactor requires re-verifying the IE11 banner in Staging, low risk. 
2. `useOnLoaded` (custom hook) - is not currently testable as written. It does not accommodate the case where the element is loaded before the event handler is registered. This hook should be removed when we deprecate the IE11 banner. We have ticketed that deprecation, and included the note about this function: #9761. We will also add a code comment to discourage other developers from using the hook meantime.

@davidconlon the proposal is: rescope this ticket's acceptance criteria to be: resolve #1 above, and add code comment for #2.

**Comment by davidconlon** [comment]
Approved for the re-scope for sprint 61
