### ISSUE TITLE
UX Discovery: Gather Q&A research and write/understand plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9530]
## Description

First issue for this epic, intended for UX designer. Create or gather documentation as appropriate.

Scope: within the Resources & Support product

Seek input from team members with expertise in content audits and migrations.

## Acceptance Criteria
- [x] Thoroughly grasp the Q&A epic (this issue's parent)
- [x] Document a plan of attack for moving ahead (i.e., major work pieces)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jcklpe** [comment]
can I get a link to some of the existing pages on the frontend? just so I can get a sense of it as a user would experience?

**Comment by jilladams** [comment]
@jcklpe some starter pieces: 
1. Internal notes from talking to @suzanne-gray about a pilot that the Sitewide Content team is running to understand how Resources & Support content are used: https://docs.google.com/document/d/1W7bE9_H54nqzv0M1rxhXuNzl7bmQ_IqYykYRAOA09fs/edit.  There are other links in that doc that are worth reading through.
2. [Github summary of pilot findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/resources-and-support-author-pilot/what-we're-learning.md) (Compiled by Beth Potts & Danielle Thierry, running the pilot)
3. There are 3 relevant content types in the CMS to look into: 
  * Q&A single
  * FAQ page
  * Resources & Support detail page
4. Existing product docs for R&S: [va.gov-team/products/resources-and-support](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support) -- not sure how relevant these will be, haven't read them.

I'm not sure about the answer on best place to keep your notes. In Github, "research" implies either Veteran or Editor research / interviews / findings, so I'm not sure the outcomes here should go there quite yet. I've asked Val/ Su their opinions in A6 slack, and @ you there.

**Comment by jilladams** [comment]
I also just learned of this epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3440

**Comment by jcklpe** [comment]
@jilladams : my board shows this as being "In Progress". But I see that it is also tagged with "needs refinement". So I will move this back into the "New unrefined " column if that's okay.

**Comment by jcklpe** [comment]
also @wesrowe  I think this can be untagged with "needs refinement"

**Comment by wesrowe** [comment]
@jcklpe, the scope here is a little poorly defined. I do think part of the "plan of attack" deliverable would be a recommendation about moderated user research. Note that a key part of this ticket is reviewing all research that exists, so ideally the plan would specifically fill gaps. A content audit may have already been done to some extent, that's a topic to cover with Sitewide Content (Beth/Danielle).
You can edit the description as you see fit. Claudio has put discovery notes in issues, but it might not be practical here. The goal is that we would come away from this ticket with a pretty good understanding of what needs to be done. I suggest that seeking input from others is also part of this, e.g. content strategist, Lynn, migration expert (Kev W maybe), etc.

**Comment by jcklpe** [comment]
@amonoxia tagged! We can maybe chat about this more if you'd like. But the main thing I take away from Lynn's epic is that this will be a consolidation of content types. If you'd like we can hop on and take a look at the CMS side together sometime.

**Comment by chri5tia** [comment]
My take (as a cowboy engineer, so disregarding user research, historical context, etc.)
- Full plan of execution requires decisions on the smaller buckets of work involved (see below)

Buckets of work outlined in epic, plus some I added, have a natural order of operations, proposed:
![Screen Shot 2022-06-23 at 8 10 41 PM](https://user-images.githubusercontent.com/22764938/175454677-ce4be0bc-9d1c-49b0-ab18-7a4b937abfee.png)

https://docs.google.com/spreadsheets/d/18DOxHt0t0ugT6eUiu9etyGdGi9jCqgthQndT6KAAS8E/edit?usp=sharing

**Comment by jcklpe** [comment]
Some notes from meeting with Danielle:

*   Would be nice to have the ability to insert information before a group of QnAs. 
*   Currently have to use QnA template to use the QnA singles together. Would be good to be able to reuse the QnA singles on other Resources and Support templates
    *   Such as Checklist
        *   would we want checklist to be a component, similar to QnA?
            *   perhaps?
*   Support and Resources details page: add QnA Group as a content block under the content block browser.

**Comment by jcklpe** [comment]
Some notes on how I think we need/could proceed:

- Add section paragraph intro text to QnA Group node
- Add QnA Group node to the content block options for the Resources and Benfits details page.
- Ask content editors to use the QnA Group node instead of the accordion stuff
- Ask content writers to use QnA Group node over the legacy QnA nodes (or paragraph content types? I wasn't super clear on that. Still need to learn more Drupal stuff. Right now delayed because I was supposed to get my temp Mac this week and didn't want to get my tutorial  dev environment stuff set up twice)
- Maybe put some copy in the actual legacy QnA nodes telling editors to use the other node.
- Convert over nodes to the new node (we do that? Or the editors do? People discussed doing a content audit but I feel like we can just start doing the conversion. But that work also seems best performed by the people who made that content or use that system)
- Might need some very very light design work for how the new node appears on the frontend but that would literally take 2 seconds. It's adding a paragraph field that should just follow the standard design system typographic palette.

relevant slack threads: https://dsva.slack.com/archives/C52CL1PKQ/p1656101746927369?thread_ts=1656079229.082099&cid=C52CL1PKQ

https://dsva.slack.com/archives/C52CL1PKQ/p1656102284141299

**Comment by chri5tia** [comment]
@jcklpe In case it is helpful, I included some UX observations and the who,what,where for the Q&A pieces here:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9579#issuecomment-1177422197

**Comment by jilladams** [comment]
@jcklpe @wesrowe based on our meetings this week, does this ticket have more to do, or could close out? Are there artifacts we expect to end up here before it closes? WOuld like to understand that before mid-sprint checkin on Monday.

**Comment by wesrowe** [comment]
It seems to me that the writing of issues to wrap up the reusable-Q&A MVP will constitute the final AC. I'm writing the FE issue this afternoon.

**Comment by wesrowe** [comment]
I just created #9755 for the FE implementation, which we'll refine next week. Closing this issue.

**Comment by wesrowe** [comment]
A few notes from the MVP scoping session on 7/7 and follow-up via Slack:
- The MVP use case will be exclusively creating new R&S Detail pages, and does NOT include adding reusable Q&A (and Groups) to existing R&S pages.
  - This simplifies requirements and design as there is no consideration required for how new Q&A Groups would appear alongside other types of Q&A content that might have been added previously.
- No migration is planned for the MVP, and therefore no content audit is needed at this time.

**Comment by jcklpe** [comment]
I don't think this has been linked here as an important piece of documentation:  https://app.mural.co/t/vagov6717/m/vagov6717/1656088606354/882d5358ec3463a39230521d787f0015233e777c?sender=u252e7152800e3981889d1910

**Comment by jilladams** [comment]
Per scrum, some open questions for this ticket, listed here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9755#issuecomment-1179416569

Would like to understand the editor perspective of why some of the current content works this way, before we refine #9755 on Thurs 7/14. Editors we can talk to this week: Laura Willwerth and Beth Potts, both are in Slack.

Reopening this ticket temporarily to reflect this piece is outstanding, Aslan to re-close once notes are posted.

**Comment by jilladams** [comment]
I had an impromptu sync with Beth re: how to check out demo of #9737 spread into the questions in comment above.

(Anecdotally, Resources & Support Detail Page used to be called About pages.) re: our questions

## Why is it hard to find an FAQ where the Section Header of the Q&A Group is actually filled in? (hypothesis: there isn't much content between the h1 and the start of Q&A Groups, usually just a paragraph and 1 or 2 CTA links.) - [Example](https://www.va.gov/resources/montgomery-gi-bill-refunds/)

FAQ pages are, by nature/design, very topically targeted, and the H1 is strategically used for search results. An FAQ page may only contain 1-3 Q&As, total. So there is not a need to group the Q&As that appear lower on the page.

Don't have many articles that are Q&A after Q&A after Q&A. So a page that contains multiple Q&A sections under one topic umbrella isn't really a use case.

https://prod.cms.va.gov/resources/gi-bill-and-other-va-education-benefit-payments-faqs - don't have an FAQ about the GI Bill big picture, but instead have multiple separate FAQ pages to address subtopics of the bigger picture
https://www.va.gov/resources/gi-bill-and-other-va-education-benefit-payments-faqs/

It's probable that Section Header and Description will be used more often on R&S pages, where the content is more flexible / Q&As may slot in more flexibly than they are used on FAQs today.

### Single Q&A: Answer = 1000 char limit
Beth/Danielle are not currently using the FAQ template because it has too many constraints, mainly the 1000 char Answer limit in Single Q&A nodes. Constraints became frustrating to navigate and took more time, so they pivoted and began using R&S detail pages instead, bc they are less constrained. They will run into this again in the current proposed implementation for putting Q&A Groups onto R&S.

- This is historically a much-hashed issue for the Sitewide Content team, and has political tendrils. We need to think through use cases / editor experience / risks, and talk to Danielle before we make changes
- In general, wouldn't want to open it to unlimited or very long char limit, to prevent abuse by non-SItewide Content editors 
  - Could take a two-way door approach and raise it to 1500/2000 
  - OR: could allow content team to override the character limit, strategically. Advantage: would prevent non-SItewide Content editors from abusing the Q&A answer length (instead of using an FAQ template) **QQ:** Does this paradigm already exist? 
    - Beth wasn't certain  If not, may be complex eng scenario, but if it's already built somewhere, we could repurpose. TODO: follow up to ask Danielle / Swirt after their PTOs. 


## Why in [this example](https://prod.cms.va.gov/node/8222/edit) would you have Q&As broken into two Q&A Groups with no distinction visible to the user? (i.e., both section headers were left blank)
This was an old page created during the migration from vets.gov to va.gov, so is probably an artifact of the structure of the CMS / content at the time,and likely mimicking the way the content was structured in the old site. Probably originally had some sort of subhead to separate the Q&A Groups. Beth would not enter content this way today, unless there was some explicit reason. (It's not prevented within the CMS.)

**Comment by jcklpe** [comment]
@jilladams  excellent notes! Couple of questions (either for you or or for us to follow up on with @bethpottsVADEPO )   
 

## **Why is it hard to find an FAQ where the Section Header of the Q&A Group is actually filled in?**

This looks good to me. 

## **Single Q&A: Answer = 1000 char limit**

*   What is the fear with letting Sitewide Content have 1000 chars in FAQs? 
*   How was the 1000 chars number reached? 
*   Have there been cases of people abusing this stuff in the past? 
*   And is managing those minority cases worth the extra lift of increasing the complexity of the editing experience for the majority? 

That said I think the two way door suggested is pretty reasonable. I don't see a problem with it being unlimited either, but if an incremental approach can get us there too then I think that seems like a wise compromise. The adding permissions or controls to go beyond the limit seems to add unnecessary complexity to the UI. 

## **Why in** [**this example**](https://prod.cms.va.gov/node/8222/edit) **would you have Q&As broken into two Q&A Groups with no distinction visible to the user?**

Cool seems we can write this off as not a pattern we don't need to carry forward.

**Comment by jilladams** [comment]
1000 char limit punted with sitewide content-  https://dsva.slack.com/archives/C52CL1PKQ/p1657735853101049?thread_ts=1657291685.669159&cid=C52CL1PKQ. Closing.
