### ISSUE TITLE
Discovery: review UX research and analytics on Benefit Detail page left nav

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9543]
## Description

Benefit Detail pages have been in production for a long time now, and it's time to try to evaluate whether usability data supports design hypotheses or not. 

- Review UX research and any other design artifacts to understand design intent and hypotheses 
- Ascertain whether Google Analytics is currently capturing the data required to evaluate hypotheses

## Acceptance Criteria

- [ ] Document gaps in analytics (if any)
- [x] Link UX research docs in ticket

**Time box**: 1 day

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by fmccaf1** [comment]
From Kevin Hoffman on Slack: 

"Findings related to "use of accordions"

Users did not detect a change when opening and/or closing menus: 

- Some of the users observed engaged in behavior that indicated they did not realize that the menus had changed when the clicked on either a parent item, or the downward carat to open the menu. 
- This was evidenced by behaviors such as not scrolling down the page to browse the menu after it was revealed beyond the scroll point/bottom of the window.
- Repeatedly clicking on a parent menu item, then expressing confusion why they hadn’t gone to the the page in question (without realizing a menu was opening and closing)
- If the menu is open, I observed people closing the menu thinking it was a link

Related to the previous issue of a detectable change in state, double clicking on this menu design creates confusion for users who are likely to double click. Older users tend to either double click by default, or double click when they believe they aren’t getting what they want from a single click. Double clicking on parent items in this menu design does essentially nothing by opening and closing the menu."

[LInk to Slack thread](https://dsva.slack.com/archives/C0NGDDXME/p1655474400556409)

**Comment by jilladams** [comment]
Dave mid-sprint checkin note: We want to pause this/ pivot, due to new info: 

The intent of this ticket was to start reviewing behavior of the left-hand nav (with Kevin Hoffman). Meantime, The left-hand nav isn't firmly scoped, and the Apartment team (new product in dev) has created a 3rd left sidebar flavor (to Dave's dismay). 

Dave's ask: We need to better integrate with the design system and work to unify the navigation across other properties. Our team to schedule meeting with Apartment designer (Meg Peters); Matt Dingee (design system); PW (Florence/Wes/me); Kevin Hoffman (optional) and Dave to drive alignment / plan. 

[For our sakes Apartment = a goal to unify management of the authenticated healthcare experience for veterans. Apartment is a codename and the shipped product will be called something else.]

It's ok for this ticket to ride across sprints until we get that meeting.

**Comment by fmccaf1** [comment]
Update: I attended analytics office hours on 6/28/22 and currently, platform Google analytics is not capturing data on the sidebar nav. I put in a ticket requesting that this feature be added.

**Comment by wesrowe** [comment]
@fmccaf1, could you please add (in your original comment) a link to the Analytics team ticket you referenced above?

**Comment by jilladams** [comment]
Re-noting: this is pending 7/15 meeting with sidebar folks.

**Comment by jilladams** [comment]
Waiting for confirmation from Dave that the 7/15 meeting is necessary after his 7/6 discussion with Chris Johnston. ([slack](https://dsva.slack.com/archives/C52CL1PKQ/p1657208700332229)). Will flag in mid-sprint checkin.
