### ISSUE TITLE
Discovery: Find a Form date handling / future dates

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9607]
## Description
We need to:

1. Analyze a bug report and some contextual data provided about Find a Form date handling
2. Determine if this is a small fixable problem or a larger enhancement required
3. Write up findings for review so PM can write tickets for implementation

## Original bug report
Find a Form shows a future date for an existing form: `Form last updated: 10-11-2022`

Form: https://prod.cms.va.gov/find-forms/about-form-10-10cgt
Display: https://www.va.gov/find-forms/?q=1010 - search page for `Form 10-10CG(T)`, and see: 

![1010-CG-T_future-dated](https://user-images.githubusercontent.com/85581471/176261159-8506c7e4-98df-4cbe-9ca7-2cfa967bfdd3.png)

Per Janel Keyes, this may be a data migration issue where we are displaying the Revision Date rather than the Issue Date for this form. 

**Q:** Why is this future date appearing? How does it come in from Forms DB / how are we handling it after import?
**Q.** Are we able to identify if many forms have this issue with future dates? This is likely a content audit question. If it's easy to answer during discovery, please do; if not, flag it in notes as needing separate ticket for follow up / audit.
**Q:** Are date fields automatically updated or validated as part of the Forms DB migration process? Any logic we have in place will be useful to summarize.

## Context
The Find a Form data set includes two date types. We need to investigate the handling of both to understand how we might improve the UX that shows when a form was last modified. 

Forms go through internal revisions, with listed Revision Dates, before being finalized, timestamped, and Issued, with an Issue date. A Revision date to a form will come before the Issue date.

| Forms DB date field  | Usage in Forms DB / why it gets modified | Presentation in VA.gov |
| ------------- | ------------- | ------------ |
| **Issue Date** | The date the form last posted to the VA Forms Site. | Should show as "Form last updated" date |
| | should match or be later than the Revision Date | |
| | * Not relevant to determining the date of the current version or when it became outdated. | |
| | * Can change several times before the OMB expiration date, if applicable. e.g. | |
| | * if there were glitches in the system when we were uploading it, and it needed to be reposted;  | |
| | * If there were non-substantive changes made (i.e., correcting a typo on the form) to the form, and it needed to be reposted | |
| | * if there was an issue with 508 compliance that needed to be corrected, and it needed to be reposted. |   |
| **Revision Date**  | The date the form was substantively changed (for VHA purpose) - the date when PJT last revised it after receiving PO SME QR approval)  | TBD, need to find out |
| | This date matches the date that is in the lower, left corner of the form. | |

### Stakeholders
Janel Keyes, Deputy Director, Contracting Officer’s Representative, Forms Manager, and Publication Control Officer
Christopher “Allan” Cargille, MS Service Line Manager, Messaging

## Discovery Acceptance Criteria

- [x] Understand the way we handle Issue Date and Revision Date during Forms DB import
- [x] Identify root cause for the future date on Form 10-10CG(T)
- [x] Assess whether our date handling  does / doesn't match the description of Issue Date vs Revision date above, and add comment to describe findings

Next steps:
- [X] Review findings with PM
- [X] PM to determine whether we need a single bugfix ticket or a larger enhancement ticket to describe other needed updates - epic created re: threat space, and questions out to Janel Keyes about date usage / if we need to update implementation
~~- [ ] PM to review open questions from Chris Cargille re: "Very old" dates and establish expected date ranges for forms~~

 

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7392 - underlying issues here / may be related.

**Comment by dsasser** [comment]
> Q: Why is this future date appearing? How does it come in from Forms DB / how are we handling it after import?

A: The future date is appearing because the date entered into the source (the Forms DB) has a revision_date of: 10/2022

> Q. Are we able to identify if many forms have this issue with future dates? This is likely a content audit question. If it's easy to answer during discovery, please do; if not, flag it in notes as needing separate ticket for follow up / audit.

A: No other forms have a future date. However, we do not currently control if the upstream Forms DB data contains a future date. We could add some logging/flag/other notification to identify if this happens again, but I do not suggest we force any business logic into the CMS to prevent future dates from being stored or displayed there. Adding a notification/log is the only actionable item that could be reasonably taken within the CMS.

SQL Query on Prod data as of 7/8/2022:
```
select count(*) from node__field_va_form_revision_date
where field_va_form_revision_date_value > '2022-07-01'
// result: 1
```


> Q: Are date fields automatically updated or validated as part of the Forms DB migration process? Any logic we have in place will be useful to summarize.

A: Dates are updated in the CMS (see below) if changed in the Forms DB. There is some basic date format validation handled by core PHP but no custom validation exists.

The following date fields are overwrite-able during nightly data migration from Forms DB into the CMS:

| Source Field  | Destination Field | Destination Label |
| ------------- | -----------------| ------------------ |
|DeletedDate | field_va_form_deleted_date | Deleted date |
|issue_date | field_va_form_issue_date | Issue date |
|revision_date | field_va_form_revision_date | Revision date |

Date Handling
> Understand the way we handle Issue Date and Revision Date during Forms DB import

Issue Date
- The csv source field, issue_date, is mapped to the destination CMS field field_va_form_issue_date.
- Soure data is consistently formatted.
- If the issue date is empty in the source csv, no data is saved into the CMS field.
- Data is transformed from the original date format 'Y-m-d H:i:s' to 'Y-m-d'. eg: from '2019-02-20 00:00:00' to '2019-02-20'

There exists 1 node (node 5858) with a future issue date (unsure if this is expected or problematic in any way, since the original issue was regarding a different date field) which is set to 03/23/2023. This value matches the date found in the source csv.

Revision Date
- The csv source field, revision_date, is mapped to the destination CMS field field_va_form_revision_date.
- Source date format has historically been inconsistent.
- Month data is normalized. Months (integers) are converted to their short-name equivalents. eg: '01' to 'Jan', '02' to 'Feb', etc.
- Date format is transformed from M/Y to 'Y-m-d'. eg: 'July/2022' to '2022-07-08'. One special note here is for the day of the month, which is not provided in the source. PHP automatically sets today's day of the month when converting date formats. So for example, assuming a source revision_date of 10/2022, for a migration running today the 8th of July, the final revision date would be formatted as '2022-10-08' and stored in the CMS db as such.

There exists one node (node 42311) with a future revision date.

**Comment by jilladams** [comment]
AMAZING. Thank you. @wesrowe & I can flag this info for Dave, and I think
it makes sense as a next step to reach out to the Forms manager who
reported the issue date vs. revision date nuances (Janel Keyes) to see if
our interpretation here matches implementation correctly. That could
potentially be a follow up ticket if timing doesn't pan out during this
sprint.

Of note: Swirt is out next week so not available to review these notes.

**Comment by jilladams** [comment]
@dsasser confirmed we can reach out to Janel Keyes, Janel.Keyes@va.gov. I'll make the intro, and cc both your A6 and VA emails.

**Comment by jilladams** [comment]
Additional note: in the front end, we display whichever is the latest date between issue / revision: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/va_form.drupal.liquid#L61

```
{% assign revisionDateIsLatestUpdate = fieldVaFormRevisionDate.value | isLaterThan: fieldVaFormIssueDate.value %}
{% if revisionDateIsLatestUpdate %}
  {{ fieldVaFormRevisionDate.value | humanizeDate }}
{% else %}
  {{ fieldVaFormIssueDate.value | humanizeDate }}
{% endif %}
```
