### ISSUE TITLE
Benchmark CMS performance with Linky entities

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9818]
## Background

As determined in #9677, testing and performance would be better served by writing script that converts all existing external links into linky links. 

Manually doing the test load would not be a valuable approach since we will need to do that at some point in the process anyway. 

## Acceptance Criteria

- [x] Write script that converts all existing external links
- [ ] New ticket is created for loading test or other next steps determined by developer

**Comment by ndouglas** [comment]
Unassigning Tanner and assigning myself per discussions 🙂

**Comment by ndouglas** [comment]
As detailed in [this comment on the PoC PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9575#issuecomment-1192584491), I wrote a script that created and saved a new revision of all existing nodes.  Doing this while Linky is installed and enabled means that all links are converted to Linky links.  

This created 6,377 Linky links.

I then timed 15 GraphQL builds with and 15 builds without Linky installed and configured.  Linky does incur a substantial measurable performance penalty.  However, I'm not sure it's substantial enough to rule out use of the module.

Measuring its effect upon JSON:API will be more difficult, since we don't have an existing collection of content queries at the scale and scope of the GraphQL queries.  There's not much to suggest it would be markedly worse or markedly better than its effects on GraphQL.

**Comment by ndouglas** [comment]
Rapped with Steve about this.  He didn't think the performance penalty was a dealbreaker either.  We discussed a few possibilities for updating the content on production, since the major issue with the script was the execution time.  He said the main content types permitting this sort of link are the Benefits Hub Detail Page and VAMC Detail Page content types, so we might be able to target only those content types and get a substantial percentage of the links created with much less time.

So I'm going to re-run the script on only `published` `healthcare_region_detail_page` and `page` nodes and see where that gets us 🙂

**Comment by ndouglas** [comment]
Renamed to match what actually took place this sprint 🙂   Created #9936, #9937, and #9939 as followups.
